export const problems = [
  {
    key: 'easy-b-001',
    title: "Tub Sonni Aniqlash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Matematika'],
    description: "Berilgan musbat butun son tub son (prime) ekanligini tekshiruvchi funksiya yozing. Tub son faqat 1 ga va o'ziga bo'linadigan, 1 dan katta sondir.\n\n**1-misol:**\nKiritma: n = 7\nNatija: true\nIzoh: 7 faqat 1 va 7 ga bo'linadi.\n\n**2-misol:**\nKiritma: n = 10\nNatija: false",
    starterCodeJs: 'function isPrime(n) {\n  // your code here\n}',
    starterCodePy: 'def is_prime(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPrime(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-002',
    title: "Faktorialni Hisoblash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Matematika'],
    description: "Berilgan manfiy bo'lmagan butun n soni uchun uning faktorialini (n!) hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: n = 5\nNatija: 120\nIzoh: 5! = 5*4*3*2*1 = 120\n\n**2-misol:**\nKiritma: n = 0\nNatija: 1",
    starterCodeJs: 'function factorial(n) {\n  // your code here\n}',
    starterCodePy: 'def factorial(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long factorial(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-003',
    title: "Fibonachchi Sonini Topish",
    difficulty: 'EASY',
    points: 13,
    tags: ['Matematika'],
    description: "Berilgan n-indeks uchun Fibonachchi ketma-ketligining n-chi hadini qaytaruvchi funksiya yozing (0, 1, 1, 2, 3, 5, ...). Iterativ (sikl orqali) yechim kutiladi.\n\n**1-misol:**\nKiritma: n = 6\nNatija: 8\n\n**2-misol:**\nKiritma: n = 0\nNatija: 0",
    starterCodeJs: 'function fibonacci(n) {\n  // your code here\n}',
    starterCodePy: 'def fibonacci(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long fibonacci(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-004',
    title: "Eng Katta Umumiy Bo'luvchi",
    difficulty: 'EASY',
    points: 12,
    tags: ['Matematika'],
    description: "Ikkita musbat butun sonning eng katta umumiy bo'luvchisini (EKUB, gcd) topuvchi funksiya yozing.\n\n**1-misol:**\nKiritma: a = 12, b = 18\nNatija: 6\n\n**2-misol:**\nKiritma: a = 17, b = 5\nNatija: 1",
    starterCodeJs: 'function gcd(a, b) {\n  // your code here\n}',
    starterCodePy: 'def gcd(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'int gcd(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-005',
    title: "Eng Kichik Umumiy Karrali",
    difficulty: 'EASY',
    points: 14,
    tags: ['Matematika'],
    description: "Ikkita musbat butun sonning eng kichik umumiy karralisini (EKUK, lcm) topuvchi funksiya yozing.\n\n**1-misol:**\nKiritma: a = 4, b = 6\nNatija: 12\n\n**2-misol:**\nKiritma: a = 3, b = 5\nNatija: 15",
    starterCodeJs: 'function lcm(a, b) {\n  // your code here\n}',
    starterCodePy: 'def lcm(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long long lcm(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-006',
    title: "Raqamlar Yig'indisi",
    difficulty: 'EASY',
    points: 10,
    tags: ['Matematika'],
    description: "Berilgan musbat butun sonning barcha raqamlari yig'indisini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: n = 1234\nNatija: 10\nIzoh: 1+2+3+4 = 10\n\n**2-misol:**\nKiritma: n = 9\nNatija: 9",
    starterCodeJs: 'function digitSum(n) {\n  // your code here\n}',
    starterCodePy: 'def digit_sum(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int digitSum(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-007',
    title: "Palindrom Sonni Tekshirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Matematika'],
    description: "Berilgan butun son palindrom ekanligini (ya'ni teskari o'qilganda ham xuddi shunday bo'lishini) tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: n = 12321\nNatija: true\n\n**2-misol:**\nKiritma: n = 12345\nNatija: false",
    starterCodeJs: 'function isPalindromeNumber(n) {\n  // your code here\n}',
    starterCodePy: 'def is_palindrome_number(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPalindromeNumber(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-008',
    title: "Sonni Darajaga Ko'tarish",
    difficulty: 'EASY',
    points: 11,
    tags: ['Matematika'],
    description: "Berilgan asos (base) va ko'rsatkich (exponent) uchun base^exponent qiymatini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: base = 2, exponent = 5\nNatija: 32\n\n**2-misol:**\nKiritma: base = 3, exponent = 0\nNatija: 1",
    starterCodeJs: 'function power(base, exponent) {\n  // your code here\n}',
    starterCodePy: 'def power(base, exponent):\n    # your code here\n    pass',
    starterCodeCpp: 'long long power(int base, int exponent) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-009',
    title: "Mukammal Sonni Aniqlash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Matematika'],
    description: "Berilgan musbat butun son mukammal son (perfect number) ekanligini tekshiruvchi funksiya yozing. Mukammal son - o'zining barcha musbat bo'luvchilari yig'indisi (o'zidan tashqari) o'ziga teng bo'lgan son.\n\n**1-misol:**\nKiritma: n = 28\nNatija: true\nIzoh: 1+2+4+7+14 = 28\n\n**2-misol:**\nKiritma: n = 12\nNatija: false",
    starterCodeJs: 'function isPerfectNumber(n) {\n  // your code here\n}',
    starterCodePy: 'def is_perfect_number(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPerfectNumber(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-010',
    title: "Armstrong Sonini Aniqlash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Matematika'],
    description: "Berilgan musbat butun son Armstrong soni ekanligini tekshiruvchi funksiya yozing. Armstrong soni - o'z raqamlarining raqamlar sonidagi darajasiga ko'tarilgan yig'indisi o'ziga teng bo'lgan son.\n\n**1-misol:**\nKiritma: n = 153\nNatija: true\nIzoh: 1^3+5^3+3^3 = 153\n\n**2-misol:**\nKiritma: n = 123\nNatija: false",
    starterCodeJs: 'function isArmstrongNumber(n) {\n  // your code here\n}',
    starterCodePy: 'def is_armstrong_number(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isArmstrongNumber(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-011',
    title: "O'nlikdan Ikkilik Sanoq Sistemasiga",
    difficulty: 'EASY',
    points: 14,
    tags: ['Matematika'],
    description: "Berilgan o'nlik (decimal) sonni ikkilik (binary) sanoq sistemasidagi satr ko'rinishiga aylantiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: n = 10\nNatija: \"1010\"\n\n**2-misol:**\nKiritma: n = 0\nNatija: \"0\"",
    starterCodeJs: 'function toBinary(n) {\n  // your code here\n}',
    starterCodePy: 'def to_binary(n):\n    # your code here\n    pass',
    starterCodeCpp: 'string toBinary(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-012',
    title: "Bo'luvchilar Sonini Hisoblash",
    difficulty: 'EASY',
    points: 13,
    tags: ['Matematika'],
    description: "Berilgan musbat butun sonning nechta musbat bo'luvchisi borligini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: n = 12\nNatija: 6\nIzoh: 1, 2, 3, 4, 6, 12 - jami 6 ta bo'luvchi.\n\n**2-misol:**\nKiritma: n = 7\nNatija: 2",
    starterCodeJs: 'function countDivisors(n) {\n  // your code here\n}',
    starterCodePy: 'def count_divisors(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int countDivisors(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-013',
    title: "Ro'yxat O'rtacha Qiymatini Topish",
    difficulty: 'EASY',
    points: 11,
    tags: ['Matematika'],
    description: "Butun sonlar ro'yxati berilgan. Ro'yxatdagi barcha sonlarning o'rtacha (arifmetik o'rtacha) qiymatini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [2, 4, 6, 8]\nNatija: 5\n\n**2-misol:**\nKiritma: nums = [1, 2, 3]\nNatija: 2",
    starterCodeJs: 'function average(nums) {\n  // your code here\n}',
    starterCodePy: 'def average(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'double average(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-014',
    title: "Ro'yxat Medianasini Topish",
    difficulty: 'EASY',
    points: 16,
    tags: ['Matematika'],
    description: "Butun sonlar ro'yxati berilgan. Ro'yxatning medianasini (saralangan holatdagi o'rta qiymatini) topuvchi funksiya yozing. Agar elementlar soni juft bo'lsa, ikkita o'rtadagi sonning o'rtachasini qaytaring.\n\n**1-misol:**\nKiritma: nums = [5, 2, 9, 1, 7]\nNatija: 5\n\n**2-misol:**\nKiritma: nums = [4, 1, 3, 2]\nNatija: 2.5",
    starterCodeJs: 'function findMedian(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_median(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'double findMedian(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-015',
    title: "Selsiydan Farengeytga Aylantirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Matematika'],
    description: "Selsiy gradusidagi haroratni Farengeyt gradusiga aylantiruvchi funksiya yozing. Formula: F = C * 9/5 + 32.\n\n**1-misol:**\nKiritma: celsius = 0\nNatija: 32\n\n**2-misol:**\nKiritma: celsius = 100\nNatija: 212",
    starterCodeJs: 'function celsiusToFahrenheit(celsius) {\n  // your code here\n}',
    starterCodePy: 'def celsius_to_fahrenheit(celsius):\n    # your code here\n    pass',
    starterCodeCpp: 'double celsiusToFahrenheit(double celsius) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-016',
    title: "Oddiy Foizni Hisoblash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Matematika'],
    description: "Bosh mablag' (principal), yillik foiz stavkasi (rate, foizda) va yillar soni (time) berilgan. Oddiy foizni (simple interest) hisoblaydigan funksiya yozing. Formula: SI = principal * rate * time / 100.\n\n**1-misol:**\nKiritma: principal = 1000, rate = 5, time = 2\nNatija: 100\n\n**2-misol:**\nKiritma: principal = 2000, rate = 10, time = 1\nNatija: 200",
    starterCodeJs: 'function simpleInterest(principal, rate, time) {\n  // your code here\n}',
    starterCodePy: 'def simple_interest(principal, rate, time):\n    # your code here\n    pass',
    starterCodeCpp: 'double simpleInterest(double principal, double rate, double time) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-017',
    title: "Rim Raqamiga Aylantirish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Matematika'],
    description: "1 dan 3999 gacha bo'lgan butun sonni Rim raqamlari ko'rinishidagi satrga aylantiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: n = 9\nNatija: \"IX\"\n\n**2-misol:**\nKiritma: n = 58\nNatija: \"LVIII\"",
    starterCodeJs: 'function toRoman(n) {\n  // your code here\n}',
    starterCodePy: 'def to_roman(n):\n    # your code here\n    pass',
    starterCodeCpp: 'string toRoman(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-018',
    title: "Juft Sonlar Yig'indisi",
    difficulty: 'EASY',
    points: 10,
    tags: ['Matematika'],
    description: "Butun sonlar ro'yxati berilgan. Ro'yxatdagi faqat juft sonlarning yig'indisini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [1, 2, 3, 4, 5, 6]\nNatija: 12\nIzoh: 2+4+6 = 12\n\n**2-misol:**\nKiritma: nums = [1, 3, 5]\nNatija: 0",
    starterCodeJs: 'function sumEvenNumbers(nums) {\n  // your code here\n}',
    starterCodePy: 'def sum_even_numbers(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int sumEvenNumbers(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-019',
    title: "Uchta Sonning EKUBini Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Matematika'],
    description: "Uchta musbat butun sonning eng katta umumiy bo'luvchisini (EKUB) topuvchi funksiya yozing.\n\n**1-misol:**\nKiritma: a = 12, b = 18, c = 24\nNatija: 6\n\n**2-misol:**\nKiritma: a = 5, b = 10, c = 15\nNatija: 5",
    starterCodeJs: 'function gcdOfThree(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def gcd_of_three(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'int gcdOfThree(int a, int b, int c) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-020',
    title: "Butun Kvadrat Ildizni Topish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Matematika'],
    description: "Berilgan manfiy bo'lmagan butun sonning butun qismidagi kvadrat ildizini (integer square root) qaytaruvchi funksiya yozing, ya'ni natija^2 <= n bo'lgan eng katta butun son.\n\n**1-misol:**\nKiritma: n = 27\nNatija: 5\nIzoh: 5*5=25 <= 27, lekin 6*6=36 > 27\n\n**2-misol:**\nKiritma: n = 16\nNatija: 4",
    starterCodeJs: 'function integerSqrt(n) {\n  // your code here\n}',
    starterCodePy: 'def integer_sqrt(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int integerSqrt(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-021',
    title: "Eng Katta va Eng Kichik Farqi",
    difficulty: 'EASY',
    points: 11,
    tags: ['Matematika'],
    description: "Butun sonlar ro'yxati berilgan. Ro'yxatdagi eng katta va eng kichik elementlar orasidagi farqni qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [3, 8, 1, 9, 4]\nNatija: 8\nIzoh: 9 - 1 = 8\n\n**2-misol:**\nKiritma: nums = [5, 5, 5]\nNatija: 0",
    starterCodeJs: 'function maxMinDifference(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_min_difference(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxMinDifference(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-022',
    title: "Uchburchak Yuzasini Hisoblash",
    difficulty: 'EASY',
    points: 16,
    tags: ['Matematika'],
    description: "Uchburchakning uchta tomoni (a, b, c) berilgan. Geron formulasi orqali uchburchak yuzasini hisoblaydigan funksiya yozing. Formula: s=(a+b+c)/2, S=sqrt(s*(s-a)*(s-b)*(s-c)).\n\n**1-misol:**\nKiritma: a = 3, b = 4, c = 5\nNatija: 6\n\n**2-misol:**\nKiritma: a = 6, b = 6, c = 6\nNatija: 15.588",
    starterCodeJs: 'function triangleArea(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def triangle_area(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'double triangleArea(double a, double b, double c) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-023',
    title: "Doira Yuzasi va Perimetri",
    difficulty: 'EASY',
    points: 15,
    tags: ['Matematika'],
    description: "Doiraning radiusi berilgan. Doira yuzasi va perimetrini hisoblab, ikkalasini ham qaytaruvchi funksiya yozing. Natija [yuza, perimetr] massivi ko'rinishida bo'lsin (pi = 3.14159 dan foydalaning).\n\n**1-misol:**\nKiritma: radius = 2\nNatija: [12.566, 12.566]\n\n**2-misol:**\nKiritma: radius = 1\nNatija: [3.14159, 6.28318]",
    starterCodeJs: 'function circleAreaAndPerimeter(radius) {\n  // your code here\n}',
    starterCodePy: 'def circle_area_and_perimeter(radius):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<double> circleAreaAndPerimeter(double radius) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-024',
    title: "Ikkilikdan O'nlik Sanoq Sistemasiga",
    difficulty: 'EASY',
    points: 13,
    tags: ['Matematika'],
    description: "Ikkilik (binary) sanoq sistemasidagi sonni ifodalovchi satr berilgan. Uni o'nlik (decimal) songa aylantiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: binary = \"1010\"\nNatija: 10\n\n**2-misol:**\nKiritma: binary = \"111\"\nNatija: 7",
    starterCodeJs: 'function binaryToDecimal(binary) {\n  // your code here\n}',
    starterCodePy: 'def binary_to_decimal(binary):\n    # your code here\n    pass',
    starterCodeCpp: 'int binaryToDecimal(string binary) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-025',
    title: "Chegirmadan Keyingi Narxni Hisoblash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Matematika'],
    description: "Mahsulotning asl narxi (price) va chegirma foizi (discountPercent) berilgan. Chegirma qo'llangandan keyingi yakuniy narxni hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: price = 200000, discountPercent = 15\nNatija: 170000\n\n**2-misol:**\nKiritma: price = 50000, discountPercent = 0\nNatija: 50000",
    starterCodeJs: 'function priceAfterDiscount(price, discountPercent) {\n  // your code here\n}',
    starterCodePy: 'def price_after_discount(price, discount_percent):\n    # your code here\n    pass',
    starterCodeCpp: 'double priceAfterDiscount(double price, double discountPercent) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-026',
    title: "Rekursiv Faktorial",
    difficulty: 'EASY',
    points: 11,
    tags: ['Rekursiya'],
    description: "Berilgan manfiy bo'lmagan butun n soni uchun uning faktorialini rekursiv (o'z-o'zini chaqiruvchi) funksiya yordamida hisoblang. Yechim albatta rekursiya orqali amalga oshirilishi kerak.\n\n**1-misol:**\nKiritma: n = 5\nNatija: 120\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function factorialRecursive(n) {\n  // your code here\n}',
    starterCodePy: 'def factorial_recursive(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long factorialRecursive(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-027',
    title: "Rekursiv Fibonachchi",
    difficulty: 'EASY',
    points: 14,
    tags: ['Rekursiya'],
    description: "Berilgan n-indeks uchun Fibonachchi ketma-ketligining n-chi hadini rekursiya yordamida topuvchi funksiya yozing. Iterativ sikllardan foydalanmasdan, faqat rekursiv chaqiruvlar orqali yeching.\n\n**1-misol:**\nKiritma: n = 7\nNatija: 13\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function fibonacciRecursive(n) {\n  // your code here\n}',
    starterCodePy: 'def fibonacci_recursive(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long fibonacciRecursive(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-028',
    title: "Massiv Elementlari Yig'indisi (Rekursiv)",
    difficulty: 'EASY',
    points: 12,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi berilgan. Massivning barcha elementlari yig'indisini rekursiv funksiya yordamida hisoblang (sikllardan foydalanmang).\n\n**1-misol:**\nKiritma: nums = [1, 2, 3, 4]\nNatija: 10\n\n**2-misol:**\nKiritma: nums = []\nNatija: 0",
    starterCodeJs: 'function sumArrayRecursive(nums) {\n  // your code here\n}',
    starterCodePy: 'def sum_array_recursive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'long long sumArrayRecursive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-029',
    title: "Rekursiv Daraja Hisoblash",
    difficulty: 'EASY',
    points: 13,
    tags: ['Rekursiya'],
    description: "Berilgan asos (base) va manfiy bo'lmagan butun ko'rsatkich (exponent) uchun base^exponent qiymatini rekursiv funksiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: base = 3, exponent = 4\nNatija: 81\n\n**2-misol:**\nKiritma: base = 5, exponent = 0\nNatija: 1",
    starterCodeJs: 'function powerRecursive(base, exponent) {\n  // your code here\n}',
    starterCodePy: 'def power_recursive(base, exponent):\n    # your code here\n    pass',
    starterCodeCpp: 'long long powerRecursive(int base, int exponent) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-030',
    title: "Satrni Rekursiv Teskari Aylantirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Rekursiya'],
    description: "Berilgan satrni rekursiv funksiya yordamida teskari tartibga o'girib qaytaruvchi funksiya yozing. Sikllardan foydalanmasdan faqat rekursiya bilan yeching.\n\n**1-misol:**\nKiritma: s = \"salom\"\nNatija: \"molas\"\n\n**2-misol:**\nKiritma: s = \"a\"\nNatija: \"a\"",
    starterCodeJs: 'function reverseStringRecursive(s) {\n  // your code here\n}',
    starterCodePy: 'def reverse_string_recursive(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string reverseStringRecursive(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-031',
    title: "Rekursiv Binar Qidiruv",
    difficulty: 'EASY',
    points: 21,
    tags: ['Rekursiya'],
    description: "Saralangan butun sonlar massivi va qidirilayotgan qiymat (target) berilgan. Rekursiv binar qidiruv (binary search) algoritmi yordamida target elementning indeksini toping, agar topilmasa -1 qaytaring. Yechim rekursiv funksiya orqali amalga oshirilishi kerak.\n\n**1-misol:**\nKiritma: nums = [1, 3, 5, 7, 9, 11], target = 7\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [2, 4, 6, 8], target = 5\nNatija: -1",
    starterCodeJs: 'function binarySearchRecursive(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def binary_search_recursive(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int binarySearchRecursive(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-032',
    title: "Rekursiv Raqamlar Yig'indisi",
    difficulty: 'EASY',
    points: 10,
    tags: ['Rekursiya'],
    description: "Berilgan musbat butun sonning barcha raqamlari yig'indisini rekursiv funksiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: n = 4321\nNatija: 10\n\n**2-misol:**\nKiritma: n = 5\nNatija: 5",
    starterCodeJs: 'function digitSumRecursive(n) {\n  // your code here\n}',
    starterCodePy: 'def digit_sum_recursive(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int digitSumRecursive(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-033',
    title: "Rekursiv EKUB (Evklid Algoritmi)",
    difficulty: 'EASY',
    points: 13,
    tags: ['Rekursiya'],
    description: "Ikkita musbat butun sonning eng katta umumiy bo'luvchisini (EKUB) Evklid algoritmi asosida rekursiv funksiya yordamida toping.\n\n**1-misol:**\nKiritma: a = 48, b = 18\nNatija: 6\n\n**2-misol:**\nKiritma: a = 7, b = 13\nNatija: 1",
    starterCodeJs: 'function gcdRecursive(a, b) {\n  // your code here\n}',
    starterCodePy: 'def gcd_recursive(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'int gcdRecursive(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-034',
    title: "Hanoy Minorasi Harakatlar Soni",
    difficulty: 'EASY',
    points: 15,
    tags: ['Rekursiya'],
    description: "Hanoy minorasi (Tower of Hanoi) masalasida n ta halqani bir tayoqchadan boshqasiga o'tkazish uchun zarur bo'lgan minimal harakatlar sonini rekursiv funksiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 7\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function hanoiMoves(n) {\n  // your code here\n}',
    starterCodePy: 'def hanoi_moves(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long hanoiMoves(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-035',
    title: "Ichma-ich Massivni Tekislash",
    difficulty: 'EASY',
    points: 20,
    tags: ['Rekursiya'],
    description: "Ichma-ich (nested) massivlar berilgan, ular istalgan chuqurlikda joylashgan bo'lishi mumkin. Barcha elementlarni bitta tekis (flat) massivga yig'ib qaytaruvchi rekursiv funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, [2, 3], [4, [5, 6]]]\nNatija: [1, 2, 3, 4, 5, 6]\n\n**2-misol:**\nKiritma: arr = [[1], [2], [3]]\nNatija: [1, 2, 3]",
    starterCodeJs: 'function flattenArrayRecursive(arr) {\n  // your code here\n}',
    starterCodePy: 'def flatten_array_recursive(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> flattenArrayRecursive(vector<vector<int>>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-036',
    title: "Palindrom Satrni Rekursiv Tekshirish",
    difficulty: 'EASY',
    points: 13,
    tags: ['Rekursiya'],
    description: "Berilgan satr palindrom ekanligini (old va yangi tomondan bir xil o'qilishini) rekursiv funksiya yordamida tekshiring.\n\n**1-misol:**\nKiritma: s = \"dodod\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"olma\"\nNatija: false",
    starterCodeJs: 'function isPalindromeRecursive(s) {\n  // your code here\n}',
    starterCodePy: 'def is_palindrome_recursive(s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPalindromeRecursive(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-037',
    title: "Massivda Maksimal Elementni Rekursiv Topish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi berilgan. Massivdagi eng katta elementni rekursiv funksiya yordamida toping (sikllardan foydalanmasdan).\n\n**1-misol:**\nKiritma: nums = [3, 7, 2, 9, 4]\nNatija: 9\n\n**2-misol:**\nKiritma: nums = [1]\nNatija: 1",
    starterCodeJs: 'function findMaxRecursive(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_max_recursive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMaxRecursive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-038',
    title: "Sonning Raqamlar Sonini Rekursiv Sanash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Rekursiya'],
    description: "Berilgan musbat butun sonda nechta raqam borligini rekursiv funksiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: n = 123456\nNatija: 6\n\n**2-misol:**\nKiritma: n = 7\nNatija: 1",
    starterCodeJs: 'function countDigitsRecursive(n) {\n  // your code here\n}',
    starterCodePy: 'def count_digits_recursive(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int countDigitsRecursive(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-039',
    title: "Ro'yxatdagi Juft Sonlarni Rekursiv Sanash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Rekursiya'],
    description: "Butun sonlar ro'yxati berilgan. Ro'yxatdagi juft sonlar sonini rekursiv funksiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: nums = [1, 2, 3, 4, 5, 6]\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [1, 3, 5]\nNatija: 0",
    starterCodeJs: 'function countEvenRecursive(nums) {\n  // your code here\n}',
    starterCodePy: 'def count_even_recursive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int countEvenRecursive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-040',
    title: "Satrda Belgi Uchrashini Rekursiv Sanash",
    difficulty: 'EASY',
    points: 13,
    tags: ['Rekursiya'],
    description: "Satr va bitta belgi (char) berilgan. Berilgan belgi satrda necha marta uchrashini rekursiv funksiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: s = \"banana\", ch = \"a\"\nNatija: 3\n\n**2-misol:**\nKiritma: s = \"salom\", ch = \"z\"\nNatija: 0",
    starterCodeJs: 'function countCharRecursive(s, ch) {\n  // your code here\n}',
    starterCodePy: 'def count_char_recursive(s, ch):\n    # your code here\n    pass',
    starterCodeCpp: 'int countCharRecursive(string s, char ch) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-041',
    title: "Massivni Rekursiv Teskari Aylantirish",
    difficulty: 'EASY',
    points: 13,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi berilgan. Massiv elementlarini teskari tartibda joylashtirib, yangi massiv qaytaruvchi rekursiv funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [1, 2, 3, 4]\nNatija: [4, 3, 2, 1]\n\n**2-misol:**\nKiritma: nums = [5]\nNatija: [5]",
    starterCodeJs: 'function reverseArrayRecursive(nums) {\n  // your code here\n}',
    starterCodePy: 'def reverse_array_recursive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> reverseArrayRecursive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-042',
    title: "N Gacha Bo'lgan Sonlar Yig'indisi (Rekursiv)",
    difficulty: 'EASY',
    points: 10,
    tags: ['Rekursiya'],
    description: "Berilgan musbat butun n soni uchun 1 dan n gacha bo'lgan barcha sonlarning yig'indisini rekursiv funksiya yordamida hisoblang (formuladan emas, rekursiv chaqiruvlardan foydalaning).\n\n**1-misol:**\nKiritma: n = 5\nNatija: 15\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function sumToNRecursive(n) {\n  // your code here\n}',
    starterCodePy: 'def sum_to_n_recursive(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long sumToNRecursive(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-043',
    title: "Ikkilik Sonni O'nlikka Rekursiv Aylantirish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Rekursiya'],
    description: "Ikkilik (binary) sonni ifodalovchi satr berilgan. Uni o'nlik songa rekursiv funksiya yordamida aylantiring.\n\n**1-misol:**\nKiritma: binary = \"1101\"\nNatija: 13\n\n**2-misol:**\nKiritma: binary = \"10\"\nNatija: 2",
    starterCodeJs: 'function binaryToDecimalRecursive(binary) {\n  // your code here\n}',
    starterCodePy: 'def binary_to_decimal_recursive(binary):\n    # your code here\n    pass',
    starterCodeCpp: 'int binaryToDecimalRecursive(string binary) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-044',
    title: "Uchta Sonning EKUBini Rekursiv Topish",
    difficulty: 'EASY',
    points: 16,
    tags: ['Rekursiya'],
    description: "Uchta musbat butun sonning eng katta umumiy bo'luvchisini rekursiv funksiyalar yordamida toping.\n\n**1-misol:**\nKiritma: a = 24, b = 36, c = 48\nNatija: 12\n\n**2-misol:**\nKiritma: a = 5, b = 15, c = 25\nNatija: 5",
    starterCodeJs: 'function gcdThreeRecursive(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def gcd_three_recursive(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'int gcdThreeRecursive(int a, int b, int c) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-045',
    title: "Massivda Elementni Rekursiv Qidirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi va qidirilayotgan qiymat (target) berilgan. Rekursiv chiziqli qidiruv (linear search) yordamida target massivda mavjudligini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [4, 2, 7, 1], target = 7\nNatija: true\n\n**2-misol:**\nKiritma: nums = [4, 2, 7, 1], target = 9\nNatija: false",
    starterCodeJs: 'function containsRecursive(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def contains_recursive(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool containsRecursive(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-046',
    title: "Satrni Rekursiv Kichik Harflarga O'tkazish",
    difficulty: 'EASY',
    points: 11,
    tags: ['Rekursiya'],
    description: "Berilgan satrdagi barcha lotin harflarini kichik harflarga rekursiv funksiya yordamida o'tkazing (sikllardan foydalanmasdan, har bir belgini rekursiv qayta ishlang).\n\n**1-misol:**\nKiritma: s = \"HELLO\"\nNatija: \"hello\"\n\n**2-misol:**\nKiritma: s = \"AbC\"\nNatija: \"abc\"",
    starterCodeJs: 'function toLowerCaseRecursive(s) {\n  // your code here\n}',
    starterCodePy: 'def to_lower_case_recursive(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string toLowerCaseRecursive(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-047',
    title: "Pascal Uchburchagi Elementini Rekursiv Topish",
    difficulty: 'EASY',
    points: 25,
    tags: ['Rekursiya'],
    description: "Pascal uchburchagida n-qator va k-ustundagi qiymatni (binomial koeffitsient C(n,k)) rekursiv funksiya yordamida hisoblang. Rekursiya munosabati: C(n,k) = C(n-1,k-1) + C(n-1,k).\n\n**1-misol:**\nKiritma: n = 5, k = 2\nNatija: 10\n\n**2-misol:**\nKiritma: n = 4, k = 0\nNatija: 1",
    starterCodeJs: 'function pascalElementRecursive(n, k) {\n  // your code here\n}',
    starterCodePy: 'def pascal_element_recursive(n, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long pascalElementRecursive(int n, int k) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-048',
    title: "Ikki Sonni Rekursiv Ko'paytirish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Rekursiya'],
    description: "Ikkita musbat butun sonni faqat qo'shish amali va rekursiya yordamida (ko'paytirish operatoridan foydalanmasdan) ko'paytiring.\n\n**1-misol:**\nKiritma: a = 6, b = 4\nNatija: 24\n\n**2-misol:**\nKiritma: a = 5, b = 0\nNatija: 0",
    starterCodeJs: 'function multiplyRecursive(a, b) {\n  // your code here\n}',
    starterCodePy: 'def multiply_recursive(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long long multiplyRecursive(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-049',
    title: "Raqamlar Ildizi (Digital Root, Rekursiv)",
    difficulty: 'EASY',
    points: 15,
    tags: ['Rekursiya'],
    description: "Berilgan musbat butun sonning raqamlar ildizini (digital root) rekursiv funksiya yordamida toping. Digital root - son bitta raqamgacha qisqarguncha uning raqamlari yig'indisini qayta-qayta hisoblash natijasi.\n\n**1-misol:**\nKiritma: n = 9875\nNatija: 2\nIzoh: 9+8+7+5=29, 2+9=11, 1+1=2\n\n**2-misol:**\nKiritma: n = 5\nNatija: 5",
    starterCodeJs: 'function digitalRootRecursive(n) {\n  // your code here\n}',
    starterCodePy: 'def digital_root_recursive(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int digitalRootRecursive(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-b-050',
    title: "Ichma-ich Ro'yxatning Maksimal Chuqurligi",
    difficulty: 'EASY',
    points: 19,
    tags: ['Rekursiya'],
    description: "Ichma-ich (nested) massivlar berilgan. Massivning maksimal ichma-ichlik chuqurligini rekursiv funksiya yordamida toping. Oddiy (ichma-ich bo'lmagan) massiv chuqurligi 1 hisoblanadi.\n\n**1-misol:**\nKiritma: arr = [1, [2, [3, [4]]]]\nNatija: 4\n\n**2-misol:**\nKiritma: arr = [1, 2, 3]\nNatija: 1",
    starterCodeJs: 'function maxDepthRecursive(arr) {\n  // your code here\n}',
    starterCodePy: 'def max_depth_recursive(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxDepthRecursive(vector<vector<int>>& arr) {\n    // your code here\n}',
  },
];
