export const problems = [
  {
    key: 'easy-c-001',
    title: "N-chi Fibonachchi Sonini Topish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Dinamik dasturlash'],
    description: "Berilgan n uchun Fibonachchi ketma-ketligining n-chi hadini toping. Ketma-ketlikda F(0)=0, F(1)=1 va har bir keyingi had oldingi ikkita hadning yig'indisiga teng: F(n) = F(n-1) + F(n-2). Yechimni memoizatsiya yordamida samarali hisoblang.\n\n**1-misol:**\nKiritma: n = 5\nNatija: 5\nIzoh: 0, 1, 1, 2, 3, 5 ketma-ketligining 5-hadi 5 ga teng.\n\n**2-misol:**\nKiritma: n = 8\nNatija: 21",
    starterCodeJs: 'function fibonacci(n) {\n  // your code here\n}',
    starterCodePy: 'def fibonacci(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int fibonacci(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-002',
    title: "Zinapoyaga Chiqish Usullari Soni",
    difficulty: 'EASY',
    points: 12,
    tags: ['Dinamik dasturlash'],
    description: "n ta pog'onadan iborat zinaga chiqish kerak. Har bir qadamda 1 yoki 2 pog'onaga ko'tarilish mumkin. Zinaning tepasiga necha xil usul bilan chiqish mumkinligini toping.\n\n**1-misol:**\nKiritma: n = 2\nNatija: 2\nIzoh: (1+1) yoki (2) usullari bilan chiqish mumkin.\n\n**2-misol:**\nKiritma: n = 3\nNatija: 3",
    starterCodeJs: 'function climbStairs(n) {\n  // your code here\n}',
    starterCodePy: 'def climb_stairs(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int climbStairs(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-003',
    title: "Minimal Xarajat bilan Zinapoyaga Chiqish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Dinamik dasturlash'],
    description: "cost massivi berilgan, bunda cost[i] — i-pog'onaga qadam qo'yish narxi. Har safar 1 yoki 2 pog'onaga ko'tarilish mumkin va boshlanish 0- yoki 1-pog'onadan bo'lishi mumkin. Zinaning tepasiga (massiv oxiridan keyingi pog'onaga) yetib borish uchun minimal umumiy xarajatni toping.\n\n**1-misol:**\nKiritma: cost = [10,15,20]\nNatija: 15\nIzoh: 1-pog'onadan (narxi 15) boshlab, ikkita pog'ona sakrab tepaga chiqiladi.\n\n**2-misol:**\nKiritma: cost = [1,100,1,1,1,100,1,1,100,1]\nNatija: 6",
    starterCodeJs: 'function minCostClimbingStairs(cost) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_climbing_stairs(cost):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCostClimbingStairs(vector<int>& cost) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-004',
    title: "Uylardan O'g'irlik (Qo'shni Uylarsiz)",
    difficulty: 'EASY',
    points: 15,
    tags: ['Dinamik dasturlash'],
    description: "Ko'cha bo'ylab joylashgan uylarda pul miqdorlari nums massivida berilgan. Signalizatsiya tizimi tufayli ikkita qo'shni uyni bir kechada o'g'irlab bo'lmaydi. Bir kechada o'g'irlash mumkin bo'lgan maksimal pul miqdorini toping.\n\n**1-misol:**\nKiritma: nums = [1,2,3,1]\nNatija: 4\nIzoh: 1-uy va 3-uy tanlanadi: 1 + 3 = 4.\n\n**2-misol:**\nKiritma: nums = [2,7,9,3,1]\nNatija: 12",
    starterCodeJs: 'function houseRobber(nums) {\n  // your code here\n}',
    starterCodePy: 'def house_robber(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int houseRobber(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-005',
    title: "Doiraviy Joylashgan Uylardan O'g'irlik",
    difficulty: 'EASY',
    points: 16,
    tags: ['Dinamik dasturlash'],
    description: "Uylar doira shaklida joylashgan (ya'ni birinchi va oxirgi uy ham bir-biriga qo'shni hisoblanadi), pul miqdorlari nums massivida berilgan. Ikkita qo'shni uyni bir kechada o'g'irlab bo'lmaydi. Maksimal o'g'irlash mumkin bo'lgan pul miqdorini toping.\n\n**1-misol:**\nKiritma: nums = [2,3,2]\nNatija: 3\nIzoh: 1-uy va 3-uy qo'shni hisoblangani uchun faqat bittasini tanlash mumkin.\n\n**2-misol:**\nKiritma: nums = [1,2,3,1]\nNatija: 4",
    starterCodeJs: 'function houseRobberCircular(nums) {\n  // your code here\n}',
    starterCodePy: 'def house_robber_circular(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int houseRobberCircular(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-006',
    title: "Jadval Bo'ylab Yo'llar Soni",
    difficulty: 'EASY',
    points: 18,
    tags: ['Dinamik dasturlash'],
    description: "m x n o'lchamdagi jadvalning yuqori chap burchagidan pastki o'ng burchagigacha borish kerak, har safar faqat o'ngga yoki pastga siljish mumkin. Nechta noyob yo'l mavjudligini toping.\n\n**1-misol:**\nKiritma: m = 3, n = 2\nNatija: 3\n\n**2-misol:**\nKiritma: m = 3, n = 3\nNatija: 6",
    starterCodeJs: 'function uniquePaths(m, n) {\n  // your code here\n}',
    starterCodePy: 'def unique_paths(m, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int uniquePaths(int m, int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-007',
    title: "To'siqli Jadvalda Yo'llar Soni",
    difficulty: 'EASY',
    points: 20,
    tags: ['Dinamik dasturlash'],
    description: "m x n o'lchamdagi grid berilgan, bunda ba'zi katakchalar to'siq (1 bilan belgilangan), qolganlari bo'sh (0). Yuqori chap burchakdan pastki o'ng burchakkacha faqat o'ngga yoki pastga siljib, to'siqlardan aylanib o'tib nechta noyob yo'l borligini toping.\n\n**1-misol:**\nKiritma: grid = [[0,0,0],[0,1,0],[0,0,0]]\nNatija: 2\n\n**2-misol:**\nKiritma: grid = [[0,1],[0,0]]\nNatija: 1",
    starterCodeJs: 'function uniquePathsWithObstacles(grid) {\n  // your code here\n}',
    starterCodePy: 'def unique_paths_with_obstacles(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int uniquePathsWithObstacles(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-008',
    title: "Jadvalda Minimal Yig'indili Yo'l",
    difficulty: 'EASY',
    points: 22,
    tags: ['Dinamik dasturlash'],
    description: "Manfiy bo'lmagan sonlardan iborat m x n grid berilgan. Yuqori chap burchakdan pastki o'ng burchakkacha faqat o'ngga yoki pastga siljib borish kerak. Yo'ldagi sonlar yig'indisi eng kichik bo'lgan yo'lning yig'indisini toping.\n\n**1-misol:**\nKiritma: grid = [[1,3,1],[1,5,1],[4,2,1]]\nNatija: 7\nIzoh: 1 -> 3 -> 1 -> 1 -> 1 yo'li bo'yicha yig'indi 7 ga teng.\n\n**2-misol:**\nKiritma: grid = [[1,2],[1,1]]\nNatija: 3",
    starterCodeJs: 'function minPathSum(grid) {\n  // your code here\n}',
    starterCodePy: 'def min_path_sum(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int minPathSum(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-009',
    title: "Uchburchakda Minimal Yig'indili Yo'l",
    difficulty: 'EASY',
    points: 24,
    tags: ['Dinamik dasturlash'],
    description: "Sonlardan tashkil topgan uchburchak berilgan. Yuqoridagi elementdan boshlab, har qatorda joriy indeks yoki undan keyingi indeksga o'tib, eng pastki qatorgacha yetib borish kerak. Yo'l bo'yicha sonlar yig'indisi minimal bo'lgan qiymatni toping.\n\n**1-misol:**\nKiritma: triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]\nNatija: 11\nIzoh: 2 -> 3 -> 5 -> 1 yo'li minimal yig'indini beradi.\n\n**2-misol:**\nKiritma: triangle = [[1],[2,3]]\nNatija: 3",
    starterCodeJs: 'function minimumTotal(triangle) {\n  // your code here\n}',
    starterCodePy: 'def minimum_total(triangle):\n    # your code here\n    pass',
    starterCodeCpp: 'int minimumTotal(vector<vector<int>>& triangle) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-010',
    title: "Bitta Nominal Tanga bilan Yig'indiga Erishish",
    difficulty: 'EASY',
    points: 25,
    tags: ['Dinamik dasturlash'],
    description: "Faqat bitta nominaldagi (coin) tangalar mavjud va ularning soni cheklanmagan. Berilgan target summasini aynan shu tangalar yordamida yig'ish mumkinligini aniqlang.\n\n**1-misol:**\nKiritma: coin = 3, target = 9\nNatija: true\nIzoh: 3 + 3 + 3 = 9.\n\n**2-misol:**\nKiritma: coin = 4, target = 10\nNatija: false",
    starterCodeJs: 'function canMakeSum(coin, target) {\n  // your code here\n}',
    starterCodePy: 'def can_make_sum(coin, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canMakeSum(int coin, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-011',
    title: "Minimal Tangalar Soni bilan Qaytim Berish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Dinamik dasturlash'],
    description: "coins massivida turli nominaldagi tangalar berilgan (har birining soni cheksiz). Berilgan amount summasini yig'ish uchun kerak bo'ladigan minimal tangalar sonini toping. Agar summani yig'ib bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: coins = [1,2,5], amount = 11\nNatija: 3\nIzoh: 5 + 5 + 1 = 11, jami 3 ta tanga.\n\n**2-misol:**\nKiritma: coins = [2], amount = 3\nNatija: -1",
    starterCodeJs: 'function minCoins(coins, amount) {\n  // your code here\n}',
    starterCodePy: 'def min_coins(coins, amount):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCoins(vector<int>& coins, int amount) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-012',
    title: "Tangalar bilan Yig'indiga Erishish Usullari Soni",
    difficulty: 'EASY',
    points: 12,
    tags: ['Dinamik dasturlash'],
    description: "coins massivida turli nominaldagi tangalar berilgan (har birining soni cheksiz). Berilgan amount summasini yig'ish mumkin bo'lgan turli kombinatsiyalar sonini toping (tartib muhim emas).\n\n**1-misol:**\nKiritma: coins = [1,2,5], amount = 5\nNatija: 4\nIzoh: (1+1+1+1+1), (1+1+1+2), (1+2+2), (5) — jami 4 usul.\n\n**2-misol:**\nKiritma: coins = [2,5], amount = 3\nNatija: 0",
    starterCodeJs: 'function countCoinWays(coins, amount) {\n  // your code here\n}',
    starterCodePy: 'def count_coin_ways(coins, amount):\n    # your code here\n    pass',
    starterCodeCpp: 'int countCoinWays(vector<int>& coins, int amount) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-013',
    title: "Tribonachchi Sonini Topish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Dinamik dasturlash'],
    description: "Tribonachchi ketma-ketligida T(0)=0, T(1)=1, T(2)=1 va har bir keyingi had T(n) = T(n-1) + T(n-2) + T(n-3) formulasi bilan hisoblanadi. Berilgan n uchun T(n) qiymatini toping.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 4\n\n**2-misol:**\nKiritma: n = 6\nNatija: 13",
    starterCodeJs: 'function tribonacci(n) {\n  // your code here\n}',
    starterCodePy: 'def tribonacci(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int tribonacci(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-014',
    title: "1, 2 yoki 3 Qadam bilan Zinapoyaga Chiqish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Dinamik dasturlash'],
    description: "n ta pog'onadan iborat zinaga chiqish kerak, har bir qadamda 1, 2 yoki 3 pog'onaga ko'tarilish mumkin. Zinaning tepasiga necha xil usul bilan chiqish mumkinligini toping.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 4\nIzoh: (1+1+1), (1+2), (2+1), (3) usullari mavjud.\n\n**2-misol:**\nKiritma: n = 4\nNatija: 7",
    starterCodeJs: 'function climbStairsThreeSteps(n) {\n  // your code here\n}',
    starterCodePy: 'def climb_stairs_three_steps(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int climbStairsThreeSteps(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-015',
    title: "Eng Uzun O'suvchi Ketma-ketlik Uzunligi",
    difficulty: 'EASY',
    points: 16,
    tags: ['Dinamik dasturlash'],
    description: "Butun sonlardan iborat nums massivi berilgan. Massivning eng uzun qat'iy o'suvchi ketma-ketligi (subsequence, elementlar ketma-ket bo'lishi shart emas) uzunligini toping.\n\n**1-misol:**\nKiritma: nums = [10,9,2,5,3,7,101,18]\nNatija: 4\nIzoh: [2,3,7,101] o'suvchi ketma-ketlik uzunligi 4.\n\n**2-misol:**\nKiritma: nums = [0,1,0,3,2,3]\nNatija: 4",
    starterCodeJs: 'function lengthOfLIS(nums) {\n  // your code here\n}',
    starterCodePy: 'def length_of_lis(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int lengthOfLIS(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-016',
    title: "Ikki Satrning Eng Uzun Umumiy Ketma-ketligi",
    difficulty: 'EASY',
    points: 18,
    tags: ['Dinamik dasturlash'],
    description: "text1 va text2 satrlari berilgan. Ikkala satrda ham (ketma-ket bo'lishi shart emas, lekin tartib saqlanishi kerak) umumiy bo'lgan eng uzun ketma-ketlik uzunligini toping.\n\n**1-misol:**\nKiritma: text1 = \"abcde\", text2 = \"ace\"\nNatija: 3\nIzoh: umumiy ketma-ketlik \"ace\".\n\n**2-misol:**\nKiritma: text1 = \"abc\", text2 = \"abc\"\nNatija: 3",
    starterCodeJs: 'function longestCommonSubsequence(text1, text2) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_subsequence(text1, text2):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestCommonSubsequence(string text1, string text2) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-017',
    title: "Massivning Maksimal Davomiy Yig'indisi",
    difficulty: 'EASY',
    points: 20,
    tags: ['Dinamik dasturlash'],
    description: "Butun sonlardan iborat nums massivi berilgan. Massivning davomiy (ketma-ket) qism massivlaridan eng katta yig'indiga egasini toping.\n\n**1-misol:**\nKiritma: nums = [-2,1,-3,4,-1,2,1,-5,4]\nNatija: 6\nIzoh: [4,-1,2,1] qism massiv yig'indisi 6 ga teng.\n\n**2-misol:**\nKiritma: nums = [5,4,-1,7,8]\nNatija: 23",
    starterCodeJs: 'function maxSubArray(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_sub_array(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxSubArray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-018',
    title: "2×N Maydonni Domino bilan Qoplash Usullari",
    difficulty: 'EASY',
    points: 22,
    tags: ['Dinamik dasturlash'],
    description: "2 x n o'lchamdagi maydonni 1x2 o'lchamdagi domino plitkalari bilan (gorizontal yoki vertikal joylashtirib) to'liq qoplash mumkin bo'lgan usullar sonini toping.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 3\n\n**2-misol:**\nKiritma: n = 4\nNatija: 5",
    starterCodeJs: 'function numTilings(n) {\n  // your code here\n}',
    starterCodePy: 'def num_tilings(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int numTilings(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-019',
    title: "Kichik Ryukzak Masalasi",
    difficulty: 'EASY',
    points: 24,
    tags: ['Dinamik dasturlash'],
    description: "weights va values massivlarida buyumlarning og'irliklari va qiymatlari berilgan, hamda ryukzakning maksimal ko'tara oladigan og'irligi capacity berilgan. Har bir buyumni faqat bir marta olish mumkin. Ryukzakka solingan buyumlarning umumiy og'irligi capacity dan oshmagan holda, ularning maksimal umumiy qiymatini toping.\n\n**1-misol:**\nKiritma: weights = [1,3,4], values = [15,20,30], capacity = 4\nNatija: 35\nIzoh: 1- va 3-og'irlikdagi buyumlar tanlanadi: 15 + 20 = 35.\n\n**2-misol:**\nKiritma: weights = [2,3], values = [3,4], capacity = 5\nNatija: 7",
    starterCodeJs: 'function knapsack(weights, values, capacity) {\n  // your code here\n}',
    starterCodePy: 'def knapsack(weights, values, capacity):\n    # your code here\n    pass',
    starterCodeCpp: 'int knapsack(vector<int>& weights, vector<int>& values, int capacity) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-020',
    title: "Massivni Teng Ikkiga Bo'lish Mumkinligi",
    difficulty: 'EASY',
    points: 25,
    tags: ['Dinamik dasturlash'],
    description: "Manfiy bo'lmagan butun sonlardan iborat nums massivi berilgan. Massivni ikkita qism to'plamga bo'lib, ularning yig'indilari bir-biriga teng bo'lishi mumkinligini aniqlang.\n\n**1-misol:**\nKiritma: nums = [1,5,11,5]\nNatija: true\nIzoh: [1,5,5] va [11] qismlarining yig'indilari teng: 11 = 11.\n\n**2-misol:**\nKiritma: nums = [1,2,3,5]\nNatija: false",
    starterCodeJs: 'function canPartition(nums) {\n  // your code here\n}',
    starterCodePy: 'def can_partition(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canPartition(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-021',
    title: "Minimal Tahrirlash Masofasi",
    difficulty: 'EASY',
    points: 10,
    tags: ['Dinamik dasturlash'],
    description: "word1 va word2 satrlari berilgan. word1 ni word2 ga aylantirish uchun kerak bo'ladigan minimal amallar sonini toping, ruxsat etilgan amallar: bitta harfni qo'shish, o'chirish yoki almashtirish.\n\n**1-misol:**\nKiritma: word1 = \"horse\", word2 = \"ros\"\nNatija: 3\n\n**2-misol:**\nKiritma: word1 = \"cat\", word2 = \"cat\"\nNatija: 0",
    starterCodeJs: 'function minDistance(word1, word2) {\n  // your code here\n}',
    starterCodePy: 'def min_distance(word1, word2):\n    # your code here\n    pass',
    starterCodeCpp: 'int minDistance(string word1, string word2) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-022',
    title: "Sakrash O'yinida Maksimal Ochko To'plash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Dinamik dasturlash'],
    description: "points massivida har bir katakdagi ochkolar soni berilgan. 0-indeksdan boshlab, har safar 1 yoki 2 katak oldinga sakrab, oxirgi katakkacha yetib borish kerak. Yo'l davomida tashrif buyurilgan katakchalardagi ochkolarning maksimal yig'indisini toping.\n\n**1-misol:**\nKiritma: points = [1,2,9,4]\nNatija: 16\nIzoh: 0 -> 1 -> 2 -> 3 yo'li orqali 1+2+9+4 = 16 ochko to'planadi.\n\n**2-misol:**\nKiritma: points = [5,1,1,5]\nNatija: 12",
    starterCodeJs: 'function maxJumpScore(points) {\n  // your code here\n}',
    starterCodePy: 'def max_jump_score(points):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxJumpScore(vector<int>& points) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-023',
    title: "Ikki Satrning Eng Uzun Umumiy Pastqatori",
    difficulty: 'EASY',
    points: 14,
    tags: ['Dinamik dasturlash'],
    description: "text1 va text2 satrlari berilgan. Ikkala satrda ham ketma-ket (uzluksiz) joylashgan eng uzun umumiy pastqator (substring) uzunligini toping.\n\n**1-misol:**\nKiritma: text1 = \"abcdef\", text2 = \"zabcy\"\nNatija: 3\nIzoh: umumiy pastqator \"abc\".\n\n**2-misol:**\nKiritma: text1 = \"abc\", text2 = \"def\"\nNatija: 0",
    starterCodeJs: 'function longestCommonSubstring(text1, text2) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring(text1, text2):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestCommonSubstring(string text1, string text2) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-024',
    title: "Sakrab Oxirgi Indeksga Yetib Borish Mumkinligi",
    difficulty: 'EASY',
    points: 15,
    tags: ['Dinamik dasturlash'],
    description: "Manfiy bo'lmagan sonlardan iborat nums massivi berilgan, bunda nums[i] — i-indeksdan oldinga sakrash mumkin bo'lgan maksimal masofa. 0-indeksdan boshlab, massivning oxirgi indeksiga yetib borish mumkinligini aniqlang.\n\n**1-misol:**\nKiritma: nums = [2,3,1,1,4]\nNatija: true\n\n**2-misol:**\nKiritma: nums = [3,2,1,0,4]\nNatija: false",
    starterCodeJs: 'function canJumpToEnd(nums) {\n  // your code here\n}',
    starterCodePy: 'def can_jump_to_end(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canJumpToEnd(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-025',
    title: "Sonni 1 ga Tushirish uchun Minimal Amallar Soni",
    difficulty: 'EASY',
    points: 16,
    tags: ['Dinamik dasturlash'],
    description: "Musbat butun son n berilgan. Har bir amalda n ni 1 ga kamaytirish mumkin, agar n juft bo'lsa 2 ga bo'lish mumkin, agar n 3 ga bo'linsa 3 ga bo'lish mumkin. n ni 1 ga tushirish uchun kerak bo'ladigan minimal amallar sonini toping.\n\n**1-misol:**\nKiritma: n = 10\nNatija: 3\nIzoh: 10 -> 9 -> 3 -> 1 (ayirish, so'ngra ikki marta 3 ga bo'lish).\n\n**2-misol:**\nKiritma: n = 15\nNatija: 4",
    starterCodeJs: 'function minOperationsToOne(n) {\n  // your code here\n}',
    starterCodePy: 'def min_operations_to_one(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int minOperationsToOne(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-026',
    title: "Grafdagi Tugunlar va Qirralar Sonini Hisoblash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Grafiklar'],
    description: "Graf n ta tugundan (0 dan n-1 gacha raqamlangan) va edges ro'yxatida berilgan qirralardan iborat. Grafdagi umumiy tugunlar sonini va qirralar sonini [tugunlar_soni, qirralar_soni] ko'rinishida qaytaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]]\nNatija: [4, 3]\n\n**2-misol:**\nKiritma: n = 5, edges = [[0,1],[0,2],[1,3],[3,4]]\nNatija: [5, 4]",
    starterCodeJs: 'function countNodesAndEdges(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def count_nodes_and_edges(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countNodesAndEdges(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-027',
    title: "Ikki Tugun Bevosita Bog'langanligini Tekshirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Berilgan ikkita tugun a va b orasida to'g'ridan-to'g'ri qirra mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], a = 1, b = 2\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], a = 0, b = 3\nNatija: false",
    starterCodeJs: 'function areDirectlyConnected(n, edges, a, b) {\n  // your code here\n}',
    starterCodePy: 'def are_directly_connected(n, edges, a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'bool areDirectlyConnected(int n, vector<vector<int>>& edges, int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-028',
    title: "Qirralar Ro'yxatidan Qo'shnilar Ro'yxatini Qurish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati (har bir qirra [u, v] ko'rinishida) orqali berilgan. Har bir tugun uchun uning qo'shnilari ro'yxatidan iborat adjacency list (qo'shnilar ro'yxati) tuzing.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: [[1],[0,2],[1]]\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[0,3]]\nNatija: [[1,2,3],[0],[0],[0]]",
    starterCodeJs: 'function buildAdjacencyList(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def build_adjacency_list(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> buildAdjacencyList(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-029',
    title: "Berilgan Tugunning Qo'shnilarini Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Berilgan node tuguniga bevosita bog'langan barcha qo'shni tugunlarni o'sish tartibida qaytaring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[0,2],[1,3]], node = 0\nNatija: [1, 2]\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], node = 2\nNatija: [1, 3]",
    starterCodeJs: 'function getNeighbors(n, edges, node) {\n  // your code here\n}',
    starterCodePy: 'def get_neighbors(n, edges, node):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> getNeighbors(int n, vector<vector<int>>& edges, int node) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-030',
    title: "BFS Yordamida Ikki Tugun Orasida Yo'l Borligini Tekshirish",
    difficulty: 'EASY',
    points: 16,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Kenglik bo'yicha qidiruv (BFS) algoritmidan foydalanib, start tugunidan end tuguniga yo'l mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[3,4]], start = 0, end = 2\nNatija: true\n\n**2-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[3,4]], start = 0, end = 4\nNatija: false",
    starterCodeJs: 'function hasPathBFS(n, edges, start, end) {\n  // your code here\n}',
    starterCodePy: 'def has_path_bfs(n, edges, start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'bool hasPathBFS(int n, vector<vector<int>>& edges, int start, int end) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-031',
    title: "DFS Yordamida Ikki Tugun Orasida Yo'l Borligini Tekshirish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Chuqurlik bo'yicha qidiruv (DFS) algoritmidan foydalanib, start tugunidan end tuguniga yo'l mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], start = 0, end = 3\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[2,3]], start = 0, end = 3\nNatija: false",
    starterCodeJs: 'function hasPathDFS(n, edges, start, end) {\n  // your code here\n}',
    starterCodePy: 'def has_path_dfs(n, edges, start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'bool hasPathDFS(int n, vector<vector<int>>& edges, int start, int end) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-032',
    title: "Graf To'liq Bog'langanligini Tekshirish",
    difficulty: 'EASY',
    points: 20,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Grafning barcha tugunlari bir-biri bilan (bevosita yoki bilvosita) bog'langan, ya'ni graf to'liq bog'langan ekanligini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]]\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[2,3]]\nNatija: false",
    starterCodeJs: 'function isConnectedGraph(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def is_connected_graph(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isConnectedGraph(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-033',
    title: "Grafdagi Bog'langan Komponentalar Sonini Hisoblash",
    difficulty: 'EASY',
    points: 22,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Grafdagi bog'langan komponentalar (bir-biri bilan bog'langan tugunlar guruhlari) sonini toping.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[3,4]]\nNatija: 2\n\n**2-misol:**\nKiritma: n = 4, edges = []\nNatija: 4",
    starterCodeJs: 'function countConnectedComponents(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def count_connected_components(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int countConnectedComponents(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-034',
    title: "Tugunning Darajasini Hisoblash",
    difficulty: 'EASY',
    points: 24,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Berilgan node tugunining darajasini, ya'ni unga bog'langan qirralar sonini toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[0,3]], node = 0\nNatija: 3\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2]], node = 1\nNatija: 2",
    starterCodeJs: 'function getDegree(n, edges, node) {\n  // your code here\n}',
    starterCodePy: 'def get_degree(n, edges, node):\n    # your code here\n    pass',
    starterCodeCpp: 'int getDegree(int n, vector<vector<int>>& edges, int node) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-035',
    title: "Eng Katta Darajaga Ega Tugunni Topish",
    difficulty: 'EASY',
    points: 25,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Eng ko'p qo'shniga ega bo'lgan (eng katta darajali) tugunning raqamini toping. Bir nechta tugun bir xil eng katta darajaga ega bo'lsa, eng kichik raqamlisini qaytaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[0,3]]\nNatija: 0\n\n**2-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[1,3],[1,4]]\nNatija: 1",
    starterCodeJs: 'function findMaxDegreeNode(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def find_max_degree_node(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMaxDegreeNode(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-036',
    title: "Grafdagi Izolyatsiyalangan Tugunlarni Topish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Hech qanday qirraga ega bo'lmagan (qo'shnisi yo'q) tugunlarning ro'yxatini o'sish tartibida qaytaring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2]]\nNatija: [3, 4]\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: []",
    starterCodeJs: 'function findIsolatedNodes(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def find_isolated_nodes(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findIsolatedNodes(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-037',
    title: "BFS orqali Barcha Erishiladigan Tugunlarni Topish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. start tugunidan BFS algoritmi yordamida erishish mumkin bo'lgan barcha tugunlarni (start tugunining o'zini ham qo'shib) o'sish tartibida qaytaring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[3,4]], start = 0\nNatija: [0, 1, 2]\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[2,3]], start = 2\nNatija: [2, 3]",
    starterCodeJs: 'function bfsReachable(n, edges, start) {\n  // your code here\n}',
    starterCodePy: 'def bfs_reachable(n, edges, start):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> bfsReachable(int n, vector<vector<int>>& edges, int start) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-038',
    title: "DFS orqali Barcha Erishiladigan Tugunlarni Topish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. start tugunidan DFS algoritmi yordamida erishish mumkin bo'lgan barcha tugunlarni (start tugunining o'zini ham qo'shib) o'sish tartibida qaytaring.\n\n**1-misol:**\nKiritma: n = 6, edges = [[0,1],[1,2],[3,4],[4,5]], start = 3\nNatija: [3, 4, 5]\n\n**2-misol:**\nKiritma: n = 3, edges = [], start = 1\nNatija: [1]",
    starterCodeJs: 'function dfsReachable(n, edges, start) {\n  // your code here\n}',
    starterCodePy: 'def dfs_reachable(n, edges, start):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> dfsReachable(int n, vector<vector<int>>& edges, int start) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-039',
    title: "Ikki Tugun Orasidagi Eng Qisqa Yo'l Uzunligini Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat vaznlanmagan yo'naltirilmagan graf edges ro'yxati orqali berilgan. BFS algoritmidan foydalanib, start tugunidan end tugunigacha bo'lgan eng qisqa yo'ldagi qirralar sonini toping. Agar yo'l mavjud bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,3],[3,4]], start = 0, end = 3\nNatija: 3\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[2,3]], start = 0, end = 3\nNatija: -1",
    starterCodeJs: 'function shortestPathLength(n, edges, start, end) {\n  // your code here\n}',
    starterCodePy: 'def shortest_path_length(n, edges, start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestPathLength(int n, vector<vector<int>>& edges, int start, int end) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-040',
    title: "Grafda O'z-o'ziga Qirra Mavjudligini Tekshirish",
    difficulty: 'EASY',
    points: 16,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat graf edges ro'yxati orqali berilgan. Grafda biror tugunni o'zi bilan bog'laydigan qirra (self-loop, ya'ni [u, u] ko'rinishidagi qirra) mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,1],[1,2]]\nNatija: true\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: false",
    starterCodeJs: 'function hasSelfLoop(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def has_self_loop(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'bool hasSelfLoop(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-041',
    title: "Qo'shnilik Matritsasi Simmetrik Ekanligini Tekshirish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Grafiklar'],
    description: "n x n o'lchamdagi qo'shnilik matritsasi (adjacency matrix) matrix ko'rinishida berilgan, bunda matrix[i][j] = 1 agar i va j tugunlari bog'langan bo'lsa. Matritsa simmetrik ekanligini, ya'ni yo'naltirilmagan grafni to'g'ri ifodalashini tekshiring.\n\n**1-misol:**\nKiritma: matrix = [[0,1,0],[1,0,1],[0,1,0]]\nNatija: true\n\n**2-misol:**\nKiritma: matrix = [[0,1,0],[0,0,1],[0,0,0]]\nNatija: false",
    starterCodeJs: 'function isSymmetricMatrix(matrix) {\n  // your code here\n}',
    starterCodePy: 'def is_symmetric_matrix(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isSymmetricMatrix(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-042',
    title: "Qo'shnilar Ro'yxatidan Qirralar Ro'yxatini Tuzish",
    difficulty: 'EASY',
    points: 20,
    tags: ['Grafiklar'],
    description: "Yo'naltirilmagan graf uchun adjList qo'shnilar ro'yxati berilgan, bunda adjList[i] — i tugunining qo'shnilari ro'yxati. Grafning barcha noyob qirralarini [u, v] (u < v) ko'rinishida ro'yxat qilib qaytaring.\n\n**1-misol:**\nKiritma: adjList = [[1],[0,2],[1]]\nNatija: [[0,1],[1,2]]\n\n**2-misol:**\nKiritma: adjList = [[1,2],[0],[0]]\nNatija: [[0,1],[0,2]]",
    starterCodeJs: 'function adjacencyListToEdges(adjList) {\n  // your code here\n}',
    starterCodePy: 'def adjacency_list_to_edges(adj_list):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> adjacencyListToEdges(vector<vector<int>>& adjList) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-043',
    title: "Berilgan Tugundan Barcha Tugunlarga Yo'l Borligini Tekshirish",
    difficulty: 'EASY',
    points: 22,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. start tugunidan grafdagi barcha boshqa tugunlarga yo'l mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], start = 0\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[2,3]], start = 0\nNatija: false",
    starterCodeJs: 'function canReachAllNodes(n, edges, start) {\n  // your code here\n}',
    starterCodePy: 'def can_reach_all_nodes(n, edges, start):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canReachAllNodes(int n, vector<vector<int>>& edges, int start) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-044',
    title: "Ikki Grafning Bir Xilligini Tekshirish",
    difficulty: 'EASY',
    points: 24,
    tags: ['Grafiklar'],
    description: "Bir xil sondagi tugunlarga ega ikkita yo'naltirilmagan graf edges1 va edges2 qirralar ro'yxati orqali berilgan. Ikkala graf bir xil qirralar to'plamiga ega ekanligini (qirralarning tartibi muhim emas) aniqlang.\n\n**1-misol:**\nKiritma: edges1 = [[0,1],[1,2]], edges2 = [[1,2],[0,1]]\nNatija: true\n\n**2-misol:**\nKiritma: edges1 = [[0,1],[1,2]], edges2 = [[0,1],[0,2]]\nNatija: false",
    starterCodeJs: 'function areGraphsEqual(edges1, edges2) {\n  // your code here\n}',
    starterCodePy: 'def are_graphs_equal(edges1, edges2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool areGraphsEqual(vector<vector<int>>& edges1, vector<vector<int>>& edges2) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-045',
    title: "Eng Kam Darajaga Ega Tugunni Topish",
    difficulty: 'EASY',
    points: 25,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Eng kam qo'shniga ega bo'lgan (eng kichik darajali) tugunning raqamini toping. Bir nechta tugun bir xil eng kichik darajaga ega bo'lsa, eng kichik raqamlisini qaytaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[0,3]]\nNatija: 1\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1]]\nNatija: 2\nIzoh: 2-tugun hech kim bilan bog'lanmagan, darajasi 0.",
    starterCodeJs: 'function findMinDegreeNode(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def find_min_degree_node(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinDegreeNode(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-046',
    title: "Grafning Yulduzcha Shaklida Ekanligini Tekshirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Graf 'yulduzcha' (star) shaklida bo'lishi uchun bitta markaziy tugun qolgan barcha n-1 ta tugun bilan bevosita bog'langan bo'lishi va boshqa qirralar mavjud bo'lmasligi kerak. Graf shu shartga mos kelishini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[0,3]]\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[0,3]]\nNatija: false",
    starterCodeJs: 'function isStarGraph(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def is_star_graph(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isStarGraph(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-047',
    title: "Grafdagi Barg Tugunlar Sonini Hisoblash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. Faqat bitta qo'shniga ega bo'lgan tugunlar 'barg' (leaf) deb ataladi. Grafdagi barg tugunlar sonini toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[1,3]]\nNatija: 3\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: 2",
    starterCodeJs: 'function countLeafNodes(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def count_leaf_nodes(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int countLeafNodes(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-048',
    title: "Ikki Tugun Ikkita Qadamgacha Bog'langanligini Tekshirish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges ro'yxati orqali berilgan. a va b tugunlari orasida to'g'ridan-to'g'ri qirra yoki bitta oraliq tugun orqali (ya'ni uzunligi 1 yoki 2 bo'lgan yo'l) bog'lanish mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], a = 0, b = 2\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], a = 0, b = 3\nNatija: false",
    starterCodeJs: 'function isConnectedWithinTwoSteps(n, edges, a, b) {\n  // your code here\n}',
    starterCodePy: 'def is_connected_within_two_steps(n, edges, a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isConnectedWithinTwoSteps(int n, vector<vector<int>>& edges, int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-049',
    title: "Grafdagi Qirralarning Umumiy Og'irligini Hisoblash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Grafiklar'],
    description: "Vaznlangan yo'naltirilmagan graf edges ro'yxati orqali berilgan, bunda har bir qirra [u, v, weight] ko'rinishida ifodalangan. Grafdagi barcha qirralarning og'irliklari yig'indisini toping.\n\n**1-misol:**\nKiritma: edges = [[0,1,4],[1,2,3],[2,3,5]]\nNatija: 12\n\n**2-misol:**\nKiritma: edges = [[0,1,10]]\nNatija: 10",
    starterCodeJs: 'function sumOfEdgeWeights(edges) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_edge_weights(edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int sumOfEdgeWeights(vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'easy-c-050',
    title: "Qo'shnilik Matritsasidan Qirralar Ro'yxatini Tuzish",
    difficulty: 'EASY',
    points: 16,
    tags: ['Grafiklar'],
    description: "n x n o'lchamdagi qo'shnilik matritsasi (adjacency matrix) matrix ko'rinishida berilgan, bunda matrix[i][j] = 1 agar i va j tugunlari bog'langan bo'lsa. Grafning barcha noyob qirralarini [u, v] (u < v) ko'rinishida ro'yxat qilib qaytaring.\n\n**1-misol:**\nKiritma: matrix = [[0,1,1],[1,0,0],[1,0,0]]\nNatija: [[0,1],[0,2]]\n\n**2-misol:**\nKiritma: matrix = [[0,0],[0,0]]\nNatija: []",
    starterCodeJs: 'function matrixToEdgeList(matrix) {\n  // your code here\n}',
    starterCodePy: 'def matrix_to_edge_list(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> matrixToEdgeList(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
];
