export const problems = [
  {
    key: 'easy-d-001',
    title: "Daraxt Tugunlarini Sanash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Daraxtlar'],
    description: "Berilgan ikkilik daraxtdagi barcha tugunlar sonini hisoblaydigan funksiya yozing. Daraxt har bir tugunda `value`, `left` va `right` maydonlariga ega bo'lgan tugunlar orqali berilgan.\n\n**1-misol:**\nKiritma: daraxt = {value: 1, left: {value: 2}, right: {value: 3}}\nNatija: 3\nIzoh: Daraxtda jami 3 ta tugun bor.\n\n**2-misol:**\nKiritma: daraxt = null\nNatija: 0",
    starterCodeJs: 'function countNodes(root) {\n  // your code here\n}',
    starterCodePy: 'def count_nodes(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int countNodes(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-002',
    title: "Daraxt Balandligini Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Daraxtlar'],
    description: "Berilgan ikkilik daraxtning balandligini (root tugundan eng uzoq bargigacha bo'lgan tugunlar soni) qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 1, left: {value: 2, left: {value: 4}}, right: {value: 3}}\nNatija: 3\nIzoh: Eng uzun yo'l 1 -> 2 -> 4 bo'lib, unda 3 ta tugun bor.\n\n**2-misol:**\nKiritma: daraxt = {value: 5}\nNatija: 1",
    starterCodeJs: 'function treeHeight(root) {\n  // your code here\n}',
    starterCodePy: 'def tree_height(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int treeHeight(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-003',
    title: "Daraxtdagi Eng Katta Qiymatni Topish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtdagi barcha tugunlar orasidan eng katta qiymatni topadigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 4, left: {value: 9}, right: {value: 7}}\nNatija: 9\n\n**2-misol:**\nKiritma: daraxt = {value: -2, left: {value: -8}}\nNatija: -2",
    starterCodeJs: 'function findMaxValue(root) {\n  // your code here\n}',
    starterCodePy: 'def find_max_value(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMaxValue(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-004',
    title: "Tugun Barg Ekanligini Tekshirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Daraxtlar'],
    description: "Berilgan tugun barg (ya'ni chap va o'ng farzandi yo'q) ekanligini tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: tugun = {value: 7, left: null, right: null}\nNatija: true\n\n**2-misol:**\nKiritma: tugun = {value: 7, left: {value: 3}, right: null}\nNatija: false",
    starterCodeJs: 'function isLeaf(node) {\n  // your code here\n}',
    starterCodePy: 'def is_leaf(node):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isLeaf(TreeNode* node) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-005',
    title: "Daraxt Tugunlari Yig'indisini Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtdagi barcha tugunlar qiymatlarining yig'indisini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 1, left: {value: 2}, right: {value: 3}}\nNatija: 6\n\n**2-misol:**\nKiritma: daraxt = null\nNatija: 0",
    starterCodeJs: 'function sumOfNodes(root) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_nodes(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int sumOfNodes(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-006',
    title: "Inorder Aylanib Chiqish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtni inorder (chap - ildiz - o'ng) tartibida aylanib chiqib, tugunlar qiymatlarini massiv shaklida qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 2, left: {value: 1}, right: {value: 3}}\nNatija: [1, 2, 3]\n\n**2-misol:**\nKiritma: daraxt = {value: 1, left: null, right: {value: 2}}\nNatija: [1, 2]",
    starterCodeJs: 'function inorderTraversal(root) {\n  // your code here\n}',
    starterCodePy: 'def inorder_traversal(root):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> inorderTraversal(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-007',
    title: "Preorder Aylanib Chiqish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtni preorder (ildiz - chap - o'ng) tartibida aylanib chiqib, tugunlar qiymatlarini massiv shaklida qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 2, left: {value: 1}, right: {value: 3}}\nNatija: [2, 1, 3]\n\n**2-misol:**\nKiritma: daraxt = {value: 1, left: null, right: {value: 2}}\nNatija: [1, 2]",
    starterCodeJs: 'function preorderTraversal(root) {\n  // your code here\n}',
    starterCodePy: 'def preorder_traversal(root):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> preorderTraversal(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-008',
    title: "Postorder Aylanib Chiqish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtni postorder (chap - o'ng - ildiz) tartibida aylanib chiqib, tugunlar qiymatlarini massiv shaklida qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 2, left: {value: 1}, right: {value: 3}}\nNatija: [1, 3, 2]\n\n**2-misol:**\nKiritma: daraxt = {value: 1, left: {value: 2}, right: null}\nNatija: [2, 1]",
    starterCodeJs: 'function postorderTraversal(root) {\n  // your code here\n}',
    starterCodePy: 'def postorder_traversal(root):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> postorderTraversal(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-009',
    title: "Barg Tugunlarini Sanash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtdagi barg tugunlar (chap va o'ng farzandi bo'lmagan tugunlar) sonini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 1, left: {value: 2}, right: {value: 3}}\nNatija: 2\nIzoh: 2 va 3 qiymatli tugunlar barg hisoblanadi.\n\n**2-misol:**\nKiritma: daraxt = {value: 1}\nNatija: 1",
    starterCodeJs: 'function countLeaves(root) {\n  // your code here\n}',
    starterCodePy: 'def count_leaves(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int countLeaves(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-010',
    title: "Daraxtdagi Eng Kichik Qiymatni Topish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtdagi barcha tugunlar orasidan eng kichik qiymatni topadigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 4, left: {value: 9}, right: {value: 1}}\nNatija: 1\n\n**2-misol:**\nKiritma: daraxt = {value: 5}\nNatija: 5",
    starterCodeJs: 'function findMinValue(root) {\n  // your code here\n}',
    starterCodePy: 'def find_min_value(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinValue(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-011',
    title: "Daraxt Bo'shligini Tekshirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Daraxtlar'],
    description: "Berilgan ikkilik daraxt bo'sh (hech qanday tugunga ega bo'lmagan) yoki yo'qligini tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = null\nNatija: true\n\n**2-misol:**\nKiritma: daraxt = {value: 1}\nNatija: false",
    starterCodeJs: 'function isTreeEmpty(root) {\n  // your code here\n}',
    starterCodePy: 'def is_tree_empty(root):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isTreeEmpty(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-012',
    title: "Daraxtda Qiymat Qidirish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtda berilgan qiymat mavjud yoki yo'qligini tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 5, left: {value: 3}, right: {value: 8}}, target = 3\nNatija: true\n\n**2-misol:**\nKiritma: daraxt = {value: 5, left: {value: 3}, right: {value: 8}}, target = 10\nNatija: false",
    starterCodeJs: 'function containsValue(root, target) {\n  // your code here\n}',
    starterCodePy: 'def contains_value(root, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool containsValue(TreeNode* root, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-013',
    title: "Ichki Tugunlar Sonini Sanash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtdagi ichki tugunlar (kamida bitta farzandga ega bo'lgan tugunlar) sonini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: daraxt = {value: 1, left: {value: 2}, right: {value: 3}}\nNatija: 1\nIzoh: Faqat 1 qiymatli ildiz tugun ichki tugun hisoblanadi.\n\n**2-misol:**\nKiritma: daraxt = {value: 1}\nNatija: 0",
    starterCodeJs: 'function countInternalNodes(root) {\n  // your code here\n}',
    starterCodePy: 'def count_internal_nodes(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int countInternalNodes(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-014',
    title: "Eng Kam Tanga Bilan Summani To'lash",
    difficulty: 'EASY',
    points: 18,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Berilgan summani standart tangalar (1, 5, 10, 25) yordamida to'lash uchun kerak bo'ladigan eng kam tangalar sonini ochko'z (greedy) usulda hisoblang — har doim eng katta nominaldagi tangani tanlang.\n\n**1-misol:**\nKiritma: summa = 41\nNatija: 4\nIzoh: 25 + 10 + 5 + 1 = 41, jami 4 ta tanga.\n\n**2-misol:**\nKiritma: summa = 30\nNatija: 2",
    starterCodeJs: 'function minCoins(amount) {\n  // your code here\n}',
    starterCodePy: 'def min_coins(amount):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCoins(int amount) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-015',
    title: "Tadbirlarni Tanlash",
    difficulty: 'EASY',
    points: 20,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Berilgan tadbirlarning boshlanish va tugash vaqtlari asosida, bir vaqtda faqat bitta tadbir amalga oshirilishi mumkinligini hisobga olib, maksimal sonda bir-biriga to'g'ri kelmaydigan tadbirlarni tanlang. Ochko'z usulda tadbirlarni tugash vaqti bo'yicha saralab tanlang.\n\n**1-misol:**\nKiritma: start = [1, 3, 0], end = [2, 4, 6]\nNatija: 2\nIzoh: (1,2) va (3,4) tadbirlari tanlanadi.\n\n**2-misol:**\nKiritma: start = [1, 2], end = [3, 4]\nNatija: 2",
    starterCodeJs: 'function maxActivities(start, end) {\n  // your code here\n}',
    starterCodePy: 'def max_activities(start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxActivities(vector<int>& start, vector<int>& end) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-016',
    title: "Bir-biriga To'g'ri Kelmaydigan Intervallar Soni",
    difficulty: 'EASY',
    points: 20,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Berilgan intervallar ro'yxatidan, bir-biri bilan kesishmaydigan intervallarning maksimal sonini ochko'z algoritm yordamida toping (intervallarni tugash nuqtasi bo'yicha saralab tanlang).\n\n**1-misol:**\nKiritma: intervallar = [[1,2],[2,3],[3,4],[1,3]]\nNatija: 3\nIzoh: [1,2], [2,3], [3,4] intervallari tanlanadi.\n\n**2-misol:**\nKiritma: intervallar = [[1,5],[2,3]]\nNatija: 1",
    starterCodeJs: 'function maxNonOverlapping(intervals) {\n  // your code here\n}',
    starterCodePy: 'def max_non_overlapping(intervals):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxNonOverlapping(vector<vector<int>>& intervals) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-017',
    title: "Raqamlardan Eng Katta Sonni Tuzish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Berilgan musbat sonlar massividan, ularning barcha raqamlarini birlashtirib, eng katta sonni tuzuvchi funksiya yozing. Sonlarni to'g'ri tartibda ochko'z usulda joylashtiring.\n\n**1-misol:**\nKiritma: sonlar = [3, 30, 34, 5, 9]\nNatija: \"9534330\"\n\n**2-misol:**\nKiritma: sonlar = [10, 2]\nNatija: \"210\"",
    starterCodeJs: 'function largestNumber(nums) {\n  // your code here\n}',
    starterCodePy: 'def largest_number(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'string largestNumber(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-018',
    title: "Bolalarga Pechene Taqsimlash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Har bir bolaning ochko'zlik darajasi (kamida shuncha o'lchamdagi pechene kerak) va har bir pechenening o'lchami berilgan. Ochko'z usulda mumkin qadar ko'p bolani qondiring va qondirilgan bolalar sonini qaytaring.\n\n**1-misol:**\nKiritma: g = [1, 2, 3], s = [1, 1]\nNatija: 1\n\n**2-misol:**\nKiritma: g = [1, 2], s = [1, 2, 3]\nNatija: 2",
    starterCodeJs: 'function findContentChildren(g, s) {\n  // your code here\n}',
    starterCodePy: 'def find_content_children(g, s):\n    # your code here\n    pass',
    starterCodeCpp: 'int findContentChildren(vector<int>& g, vector<int>& s) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-019',
    title: "Limonad Uchun Qaytim Berish",
    difficulty: 'EASY',
    points: 20,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Limonad narxi 5 dollar. Mijozlar navbat bilan 5, 10 yoki 20 dollarlik pul bilan to'laydilar. Har bir mijozga to'g'ri qaytim berish mumkinligini ochko'z usulda aniqlang (avval kattaroq banknotlarni ishlatishga harakat qiling) va barcha mijozlarga qaytim berish mumkin bo'lsa true, aks holda false qaytaring.\n\n**1-misol:**\nKiritma: bills = [5, 5, 5, 10, 20]\nNatija: true\n\n**2-misol:**\nKiritma: bills = [5, 5, 10, 10, 20]\nNatija: false",
    starterCodeJs: 'function lemonadeChange(bills) {\n  // your code here\n}',
    starterCodePy: 'def lemonade_change(bills):\n    # your code here\n    pass',
    starterCodeCpp: 'bool lemonadeChange(vector<int>& bills) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-020',
    title: "Byudjet Ichida Maksimal Mahsulot Sotib Olish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Mahsulotlarning narxlari va mavjud byudjet berilgan. Ochko'z usulda avval eng arzon mahsulotlarni tanlab, byudjet ichida sotib olish mumkin bo'lgan maksimal mahsulotlar sonini toping.\n\n**1-misol:**\nKiritma: narxlar = [4, 3, 2, 5], byudjet = 7\nNatija: 2\nIzoh: Eng arzon ikkita mahsulot (2 va 3) jami 5 dollar bo'lib, byudjetga sig'adi.\n\n**2-misol:**\nKiritma: narxlar = [1, 1, 1], byudjet = 2\nNatija: 2",
    starterCodeJs: 'function maxItemsWithinBudget(prices, budget) {\n  // your code here\n}',
    starterCodePy: 'def max_items_within_budget(prices, budget):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxItemsWithinBudget(vector<int>& prices, int budget) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-021',
    title: "Qayiqqa Odamlarni Joylashtirish",
    difficulty: 'EASY',
    points: 22,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Har bir qayiq maksimal ikkita odamni va belgilangan og'irlik chegarasini ko'tara oladi. Odamlarning og'irliklari berilgan. Ochko'z usulda (eng yengil va eng og'ir odamni juftlashtirib) barcha odamlarni tashish uchun kerak bo'ladigan minimal qayiqlar sonini toping.\n\n**1-misol:**\nKiritma: og'irliklar = [1, 2], limit = 3\nNatija: 1\n\n**2-misol:**\nKiritma: og'irliklar = [3, 2, 2, 1], limit = 3\nNatija: 3",
    starterCodeJs: 'function numRescueBoats(weights, limit) {\n  // your code here\n}',
    starterCodePy: 'def num_rescue_boats(weights, limit):\n    # your code here\n    pass',
    starterCodeCpp: 'int numRescueBoats(vector<int>& weights, int limit) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-022',
    title: "Muddatlar Asosida Ishlarni Rejalashtirish",
    difficulty: 'EASY',
    points: 20,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Har bir ish bitta vaqt birligida bajariladi va uning bajarilishi kerak bo'lgan oxirgi muddati (deadline) berilgan. Ochko'z usulda maksimal sonda ishni muddatidan kechikmasdan bajarish mumkinligini toping.\n\n**1-misol:**\nKiritma: muddatlar = [2, 1, 2, 1]\nNatija: 2\nIzoh: Faqat 2 ta ish o'z muddatida bajarilishi mumkin.\n\n**2-misol:**\nKiritma: muddatlar = [1, 2, 3]\nNatija: 3",
    starterCodeJs: 'function maxJobsScheduled(deadlines) {\n  // your code here\n}',
    starterCodePy: 'def max_jobs_scheduled(deadlines):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxJobsScheduled(vector<int>& deadlines) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-023',
    title: "Juftliklar Yig'indisini Maksimal Qilish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Berilgan juft sondagi elementlardan iborat massivni juftlarga ajratib, har bir juftdagi kichik sonlar yig'indisini maksimal qilish kerak. Massivni saralab, ketma-ket juftlarga bo'lish ochko'z yechim hisoblanadi.\n\n**1-misol:**\nKiritma: nums = [1, 4, 3, 2]\nNatija: 4\nIzoh: (1,2) va (3,4) juftlarida kichiklari 1 va 3, yig'indisi 4.\n\n**2-misol:**\nKiritma: nums = [6, 2, 6, 5, 1, 2]\nNatija: 9",
    starterCodeJs: 'function arrayPairSum(nums) {\n  // your code here\n}',
    starterCodePy: 'def array_pair_sum(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int arrayPairSum(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-024',
    title: "Sharlarni Otish Uchun Minimal O'q Soni",
    difficulty: 'EASY',
    points: 22,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Gorizontal chiziqda joylashgan sharlar berilgan, har biri boshlanish va tugash koordinatasiga ega. Bitta o'q vertikal yo'nalishda otiladi va shu vertikal chiziqqa tegib turgan barcha sharlarni yorib o'tadi. Barcha sharlarni yorish uchun kerak bo'ladigan minimal o'qlar sonini ochko'z usulda toping.\n\n**1-misol:**\nKiritma: sharlar = [[10,16],[2,8],[1,6],[7,12]]\nNatija: 2\n\n**2-misol:**\nKiritma: sharlar = [[1,2],[3,4],[5,6]]\nNatija: 3",
    starterCodeJs: 'function findMinArrowShots(points) {\n  // your code here\n}',
    starterCodePy: 'def find_min_arrow_shots(points):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinArrowShots(vector<vector<int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-025',
    title: "Aksiyalarni Sotib Olish va Sotishdan Maksimal Foyda",
    difficulty: 'EASY',
    points: 15,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Kunlar bo'yicha aksiya narxlari berilgan. Bitta aksiyani bir marta sotib olib, keyinroq bir marta sotish orqali olinishi mumkin bo'lgan maksimal foydani ochko'z usulda (eng past narxni kuzatib borish orqali) toping.\n\n**1-misol:**\nKiritma: narxlar = [7, 1, 5, 3, 6, 4]\nNatija: 5\nIzoh: 1-kunda sotib olib, 5-kunda sotilsa (narx 6), foyda 5 bo'ladi.\n\n**2-misol:**\nKiritma: narxlar = [7, 6, 4, 3, 1]\nNatija: 0",
    starterCodeJs: 'function maxProfit(prices) {\n  // your code here\n}',
    starterCodePy: 'def max_profit(prices):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxProfit(vector<int>& prices) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-026',
    title: "N Ta Eng Katta Sonning Yig'indisi",
    difficulty: 'EASY',
    points: 12,
    tags: ['Ochko\'zlik algoritmlari'],
    description: "Berilgan massiv va N soni asosida, massivdagi eng katta N ta sonni tanlab, ularning yig'indisini ochko'z usulda (massivni kamayish tartibida saralab, birinchi N tasini olish) hisoblang.\n\n**1-misol:**\nKiritma: nums = [5, 2, 9, 1, 7], n = 3\nNatija: 21\nIzoh: Eng katta 3 ta son: 9, 7, 5, yig'indisi 21.\n\n**2-misol:**\nKiritma: nums = [4, 4, 4], n = 2\nNatija: 8",
    starterCodeJs: 'function sumOfTopN(nums, n) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_top_n(nums, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int sumOfTopN(vector<int>& nums, int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-027',
    title: "Pufakchali Saralash (Bubble Sort)",
    difficulty: 'EASY',
    points: 15,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan butun sonlar massivini pufakchali saralash (bubble sort) algoritmi yordamida o'sish tartibida saralaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [5, 2, 4, 1]\nNatija: [1, 2, 4, 5]\n\n**2-misol:**\nKiritma: nums = [3, 1, 2]\nNatija: [1, 2, 3]",
    starterCodeJs: 'function bubbleSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def bubble_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> bubbleSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-028',
    title: "Chiziqli Qidiruv",
    difficulty: 'EASY',
    points: 10,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan massivda chiziqli qidiruv (linear search) yordamida target qiymatning indeksini toping. Agar element topilmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [4, 2, 7, 1], target = 7\nNatija: 2\n\n**2-misol:**\nKiritma: nums = [4, 2, 7, 1], target = 9\nNatija: -1",
    starterCodeJs: 'function linearSearch(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def linear_search(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int linearSearch(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-029',
    title: "Ikkilik Qidiruv (Binary Search)",
    difficulty: 'EASY',
    points: 15,
    tags: ['Saralash va qidiruv'],
    description: "O'sish tartibida saralangan massivda ikkilik qidiruv (binary search) algoritmi yordamida target qiymatning indeksini toping. Agar element topilmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [1, 3, 5, 7, 9], target = 7\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [1, 3, 5, 7, 9], target = 4\nNatija: -1",
    starterCodeJs: 'function binarySearch(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def binary_search(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int binarySearch(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-030',
    title: "K-chi Eng Kichik Elementni Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan massivni saralab, undagi k-chi eng kichik elementni qaytaruvchi funksiya yozing (k 1 dan boshlanadi).\n\n**1-misol:**\nKiritma: nums = [7, 10, 4, 3, 20, 15], k = 3\nNatija: 7\n\n**2-misol:**\nKiritma: nums = [1, 2, 3], k = 1\nNatija: 1",
    starterCodeJs: 'function findKthSmallest(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def find_kth_smallest(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int findKthSmallest(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-031',
    title: "Inversiyalar Sonini Sanash",
    difficulty: 'EASY',
    points: 20,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan massivda inversiyalar sonini hisoblang. Inversiya deb, i < j bo'lganda nums[i] > nums[j] shartini qanoatlantiruvchi juftlikka aytiladi.\n\n**1-misol:**\nKiritma: nums = [2, 4, 1]\nNatija: 2\nIzoh: (2,1) va (4,1) juftliklari inversiya hisoblanadi.\n\n**2-misol:**\nKiritma: nums = [1, 2, 3]\nNatija: 0",
    starterCodeJs: 'function countInversions(nums) {\n  // your code here\n}',
    starterCodePy: 'def count_inversions(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int countInversions(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-032',
    title: "Tanlash Orqali Saralash (Selection Sort)",
    difficulty: 'EASY',
    points: 15,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan butun sonlar massivini tanlash orqali saralash (selection sort) algoritmi yordamida o'sish tartibida saralaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [29, 10, 14, 37]\nNatija: [10, 14, 29, 37]\n\n**2-misol:**\nKiritma: nums = [3, 1, 2]\nNatija: [1, 2, 3]",
    starterCodeJs: 'function selectionSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def selection_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> selectionSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-033',
    title: "Kiritish Orqali Saralash (Insertion Sort)",
    difficulty: 'EASY',
    points: 15,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan butun sonlar massivini kiritish orqali saralash (insertion sort) algoritmi yordamida o'sish tartibida saralaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [12, 11, 13, 5, 6]\nNatija: [5, 6, 11, 12, 13]\n\n**2-misol:**\nKiritma: nums = [4, 3]\nNatija: [3, 4]",
    starterCodeJs: 'function insertionSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def insertion_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> insertionSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-034',
    title: "Ikkita Saralangan Massivni Birlashtirish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Saralash va qidiruv'],
    description: "Ikkita o'sish tartibida saralangan massivni bitta saralangan massivga birlashtiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: a = [1, 3, 5], b = [2, 4, 6]\nNatija: [1, 2, 3, 4, 5, 6]\n\n**2-misol:**\nKiritma: a = [1, 2], b = [3]\nNatija: [1, 2, 3]",
    starterCodeJs: 'function mergeSortedArrays(a, b) {\n  // your code here\n}',
    starterCodePy: 'def merge_sorted_arrays(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergeSortedArrays(vector<int>& a, vector<int>& b) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-035',
    title: "Elementning Birinchi Uchrashini Topish",
    difficulty: 'EASY',
    points: 18,
    tags: ['Saralash va qidiruv'],
    description: "O'sish tartibida saralangan va takrorlanuvchi elementlarga ega massivda, ikkilik qidiruv yordamida target qiymatning birinchi (eng chap) uchrashi indeksini toping. Agar element bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [2, 4, 4, 4, 7], target = 4\nNatija: 1\n\n**2-misol:**\nKiritma: nums = [1, 2, 3], target = 5\nNatija: -1",
    starterCodeJs: 'function findFirstOccurrence(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def find_first_occurrence(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int findFirstOccurrence(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-036',
    title: "Massiv Saralanganligini Tekshirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Saralash va qidiruv'],
    description: "Berilgan massiv o'sish tartibida saralanganligini tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [1, 2, 3, 4]\nNatija: true\n\n**2-misol:**\nKiritma: nums = [3, 1, 2]\nNatija: false",
    starterCodeJs: 'function isSorted(nums) {\n  // your code here\n}',
    starterCodePy: 'def is_sorted(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isSorted(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-037',
    title: "Ikkita Massiv Bir Xil Elementlardan Iboratligini Tekshirish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Saralash va qidiruv'],
    description: "Ikkita massivni saralab, ular xuddi shu elementlar (bir xil sondagi va qiymatdagi) dan iboratligini tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: a = [1, 2, 3], b = [3, 2, 1]\nNatija: true\n\n**2-misol:**\nKiritma: a = [1, 2, 2], b = [1, 1, 2]\nNatija: false",
    starterCodeJs: 'function areSameSets(a, b) {\n  // your code here\n}',
    starterCodePy: 'def are_same_sets(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'bool areSameSets(vector<int>& a, vector<int>& b) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-038',
    title: "0 va 1 Lardan Iborat Massivni Saralash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Saralash va qidiruv'],
    description: "Faqat 0 va 1 sonlaridan iborat massivni barcha 0 lar boshida, barcha 1 lar oxirida bo'ladigan tartibda saralaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: nums = [1, 0, 1, 0, 0]\nNatija: [0, 0, 0, 1, 1]\n\n**2-misol:**\nKiritma: nums = [0, 1]\nNatija: [0, 1]",
    starterCodeJs: 'function sortZerosAndOnes(nums) {\n  // your code here\n}',
    starterCodePy: 'def sort_zeros_and_ones(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> sortZerosAndOnes(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-039',
    title: "Juft yoki Toqligini Bit Amali Bilan Tekshirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Bit amallari'],
    description: "Berilgan butun sonning juft yoki toq ekanligini bitwise AND (&) amali yordamida tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: son = 4\nNatija: true\nIzoh: 4 juft son.\n\n**2-misol:**\nKiritma: son = 7\nNatija: false",
    starterCodeJs: 'function isEven(n) {\n  // your code here\n}',
    starterCodePy: 'def is_even(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isEven(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-040',
    title: "Ikkilik Sanoq Sistemasidagi Birlar Sonini Sanash",
    difficulty: 'EASY',
    points: 15,
    tags: ['Bit amallari'],
    description: "Berilgan musbat butun sonning ikkilik (binary) ko'rinishidagi 1 raqamlari sonini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: son = 11\nNatija: 3\nIzoh: 11 soni ikkilik sanoq sistemasida 1011 bo'lib, unda 3 ta 1 bor.\n\n**2-misol:**\nKiritma: son = 8\nNatija: 1",
    starterCodeJs: 'function countSetBits(n) {\n  // your code here\n}',
    starterCodePy: 'def count_set_bits(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int countSetBits(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-041',
    title: "XOR Yordamida Ikkita Sonni Almashtirish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Bit amallari'],
    description: "Ikkita butun sonni qo'shimcha o'zgaruvchisiz, faqat XOR (^) amali yordamida almashtiradigan (swap qiladigan) funksiya yozing. Funksiya ikkala sonning yangi qiymatlarini massiv/tuple sifatida qaytarishi kerak.\n\n**1-misol:**\nKiritma: a = 5, b = 9\nNatija: [9, 5]\n\n**2-misol:**\nKiritma: a = 1, b = 2\nNatija: [2, 1]",
    starterCodeJs: 'function swapWithXor(a, b) {\n  // your code here\n}',
    starterCodePy: 'def swap_with_xor(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<int,int> swapWithXor(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-042',
    title: "Sonning 2 ning Darajasi Ekanligini Tekshirish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Bit amallari'],
    description: "Berilgan musbat butun son 2 ning darajasi (1, 2, 4, 8, ...) ekanligini bit amallari yordamida tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: son = 16\nNatija: true\n\n**2-misol:**\nKiritma: son = 18\nNatija: false",
    starterCodeJs: 'function isPowerOfTwo(n) {\n  // your code here\n}',
    starterCodePy: 'def is_power_of_two(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPowerOfTwo(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-043',
    title: "Yakka Sonni Topish (Single Number)",
    difficulty: 'EASY',
    points: 18,
    tags: ['Bit amallari'],
    description: "Berilgan massivda barcha sonlar ikki martadan uchraydi, faqat bitta son bir marta uchraydi. XOR amali yordamida shu yakka sonni toping.\n\n**1-misol:**\nKiritma: nums = [4, 1, 2, 1, 2]\nNatija: 4\n\n**2-misol:**\nKiritma: nums = [2, 2, 3]\nNatija: 3",
    starterCodeJs: 'function singleNumber(nums) {\n  // your code here\n}',
    starterCodePy: 'def single_number(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int singleNumber(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-044',
    title: "Berilgan Pozitsiyadagi Bitni Olish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Bit amallari'],
    description: "Berilgan sonning i-chi pozitsiyasidagi bit qiymatini (0 yoki 1) qaytaruvchi funksiya yozing. Pozitsiyalar 0 dan boshlanadi (eng kichik razryaddan).\n\n**1-misol:**\nKiritma: son = 10, i = 1\nNatija: 1\nIzoh: 10 soni ikkilik ko'rinishda 1010, i=1 pozitsiyadagi bit 1.\n\n**2-misol:**\nKiritma: son = 10, i = 0\nNatija: 0",
    starterCodeJs: 'function getBit(n, i) {\n  // your code here\n}',
    starterCodePy: 'def get_bit(n, i):\n    # your code here\n    pass',
    starterCodeCpp: 'int getBit(int n, int i) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-045',
    title: "Berilgan Pozitsiyadagi Bitni O'rnatish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Bit amallari'],
    description: "Berilgan sonning i-chi pozitsiyasidagi bitni 1 ga o'rnatadigan (set qiladigan) funksiya yozing va natijadagi sonni qaytaring.\n\n**1-misol:**\nKiritma: son = 8, i = 1\nNatija: 10\nIzoh: 8 soni 1000, i=1 pozitsiyani 1 qilsak 1010 = 10 hosil bo'ladi.\n\n**2-misol:**\nKiritma: son = 0, i = 2\nNatija: 4",
    starterCodeJs: 'function setBit(n, i) {\n  // your code here\n}',
    starterCodePy: 'def set_bit(n, i):\n    # your code here\n    pass',
    starterCodeCpp: 'int setBit(int n, int i) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-046',
    title: "Berilgan Pozitsiyadagi Bitni Tozalash",
    difficulty: 'EASY',
    points: 12,
    tags: ['Bit amallari'],
    description: "Berilgan sonning i-chi pozitsiyasidagi bitni 0 ga tozalaydigan (clear qiladigan) funksiya yozing va natijadagi sonni qaytaring.\n\n**1-misol:**\nKiritma: son = 10, i = 1\nNatija: 8\nIzoh: 10 soni 1010, i=1 pozitsiyani 0 qilsak 1000 = 8 hosil bo'ladi.\n\n**2-misol:**\nKiritma: son = 15, i = 0\nNatija: 14",
    starterCodeJs: 'function clearBit(n, i) {\n  // your code here\n}',
    starterCodePy: 'def clear_bit(n, i):\n    # your code here\n    pass',
    starterCodeCpp: 'int clearBit(int n, int i) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-047',
    title: "Bitli Siljitish Orqali Ko'paytirish/Bo'lish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Bit amallari'],
    description: "Berilgan sonni bitwise chap siljitish (<<) yordamida 2 ga ko'paytiruvchi va bitwise o'ng siljitish (>>) yordamida 2 ga bo'luvchi bitta funksiya yozing: son va amal turi (\"multiply\" yoki \"divide\") berilganda mos natijani qaytaring.\n\n**1-misol:**\nKiritma: son = 5, amal = \"multiply\"\nNatija: 10\n\n**2-misol:**\nKiritma: son = 9, amal = \"divide\"\nNatija: 4",
    starterCodeJs: 'function shiftOperation(n, op) {\n  // your code here\n}',
    starterCodePy: 'def shift_operation(n, op):\n    # your code here\n    pass',
    starterCodeCpp: 'int shiftOperation(int n, string op) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-048',
    title: "Sonni Ifodalash Uchun Kerakli Bitlar Sonini Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Bit amallari'],
    description: "Berilgan musbat butun sonni ikkilik sanoq sistemasida ifodalash uchun kerak bo'ladigan minimal bitlar sonini (bit uzunligini) hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: son = 9\nNatija: 4\nIzoh: 9 soni ikkilik ko'rinishda 1001 bo'lib, 4 ta bitdan iborat.\n\n**2-misol:**\nKiritma: son = 1\nNatija: 1",
    starterCodeJs: 'function bitLength(n) {\n  // your code here\n}',
    starterCodePy: 'def bit_length(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int bitLength(int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-049',
    title: "Ikkita Sonning Ishorasi Qarama-Qarshiligini Tekshirish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Bit amallari'],
    description: "Ikkita butun sonning ishoralari (musbat/manfiy) qarama-qarshi ekanligini XOR amali yordamida tekshiradigan funksiya yozing.\n\n**1-misol:**\nKiritma: a = 5, b = -3\nNatija: true\n\n**2-misol:**\nKiritma: a = 4, b = 7\nNatija: false",
    starterCodeJs: 'function haveOppositeSigns(a, b) {\n  // your code here\n}',
    starterCodePy: 'def have_opposite_signs(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'bool haveOppositeSigns(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'easy-d-050',
    title: "1 dan N gacha Bo'lgan Sonlarning XOR Yig'indisi",
    difficulty: 'EASY',
    points: 18,
    tags: ['Bit amallari'],
    description: "1 dan n gacha bo'lgan barcha butun sonlarning XOR qiymatini hisoblaydigan funksiya yozing.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 4\nIzoh: 1^2^3^4 = 4.\n\n**2-misol:**\nKiritma: n = 5\nNatija: 1",
    starterCodeJs: 'function xorFromOneToN(n) {\n  // your code here\n}',
    starterCodePy: 'def xor_from_one_to_n(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int xorFromOneToN(int n) {\n    // your code here\n}',
  },
];
