export const problems = [
  {
    key: 'easy-a-001',
    title: "Massiv Elementlari Yig'indisi",
    difficulty: 'EASY',
    points: 10,
    tags: ['Massivlar'],
    description: "Butun sonlardan iborat massiv berilgan. Massivning barcha elementlari yig'indisini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4, 5]\nNatija: 15\n\n**2-misol:**\nKiritma: arr = [-2, 3, -1]\nNatija: 0",
    starterCodeJs: 'function arraySum(arr) {\n  // your code here\n}',
    starterCodePy: 'def array_sum(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int arraySum(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-002',
    title: "Massivdagi Eng Katta Element",
    difficulty: 'EASY',
    points: 10,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivdagi eng katta (maksimal) elementni topib qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [3, 7, 2, 9, 4]\nNatija: 9\n\n**2-misol:**\nKiritma: arr = [-5, -1, -8]\nNatija: -1",
    starterCodeJs: 'function findMax(arr) {\n  // your code here\n}',
    starterCodePy: 'def find_max(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMax(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-003',
    title: "Massivdagi Eng Kichik Element",
    difficulty: 'EASY',
    points: 11,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivdagi eng kichik (minimal) elementni topib qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [3, 7, 2, 9, 4]\nNatija: 2\n\n**2-misol:**\nKiritma: arr = [-5, -1, -8]\nNatija: -8",
    starterCodeJs: 'function findMin(arr) {\n  // your code here\n}',
    starterCodePy: 'def find_min(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMin(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-004',
    title: "Ikkinchi Eng Katta Element",
    difficulty: 'EASY',
    points: 14,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivdagi ikkinchi eng katta elementni topib qaytaring. Massivda kamida ikkita turli qiymat borligini hisobga oling.\n\n**1-misol:**\nKiritma: arr = [5, 1, 9, 4, 9, 3]\nNatija: 5\nIzoh: Eng katta element 9, ikkinchi eng katta esa 5.\n\n**2-misol:**\nKiritma: arr = [10, 20]\nNatija: 10",
    starterCodeJs: 'function secondLargest(arr) {\n  // your code here\n}',
    starterCodePy: 'def second_largest(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int secondLargest(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-005',
    title: "Massivni Teskari Tartibga Keltirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massiv elementlarini teskari tartibda joylashtiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4]\nNatija: [4, 3, 2, 1]\n\n**2-misol:**\nKiritma: arr = [7]\nNatija: [7]",
    starterCodeJs: 'function reverseArray(arr) {\n  // your code here\n}',
    starterCodePy: 'def reverse_array(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> reverseArray(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-006',
    title: "Massivni Chapga Siljitish (Rotate)",
    difficulty: 'EASY',
    points: 16,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi va k soni berilgan. Massiv elementlarini chapga k pozitsiyaga siljituvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4, 5], k = 2\nNatija: [3, 4, 5, 1, 2]\n\n**2-misol:**\nKiritma: arr = [1, 2, 3], k = 1\nNatija: [2, 3, 1]",
    starterCodeJs: 'function rotateLeft(arr, k) {\n  // your code here\n}',
    starterCodePy: 'def rotate_left(arr, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> rotateLeft(vector<int>& arr, int k) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-007',
    title: "Yetishmayotgan Sonni Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Massivlar'],
    description: "1 dan n gacha bo'lgan sonlardan bittasi tushirib qoldirilgan massiv berilgan (n ta o'rniga n-1 ta element bor). Yetishmayotgan sonni topuvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 4, 5], n = 5\nNatija: 3\n\n**2-misol:**\nKiritma: arr = [2, 3, 4], n = 4\nNatija: 1",
    starterCodeJs: 'function findMissingNumber(arr, n) {\n  // your code here\n}',
    starterCodePy: 'def find_missing_number(arr, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMissingNumber(vector<int>& arr, int n) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-008',
    title: "Ikki Elementning Yig'indisi (Two Sum)",
    difficulty: 'EASY',
    points: 18,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi va target soni berilgan. Yig'indisi target ga teng bo'lgan ikkita elementning indekslarini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [2, 7, 11, 15], target = 9\nNatija: [0, 1]\nIzoh: arr[0] + arr[1] = 2 + 7 = 9.\n\n**2-misol:**\nKiritma: arr = [3, 2, 4], target = 6\nNatija: [1, 2]",
    starterCodeJs: 'function twoSum(arr, target) {\n  // your code here\n}',
    starterCodePy: 'def two_sum(arr, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> twoSum(vector<int>& arr, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-009',
    title: "Saralangan Massivdan Takrorlanuvchilarni Olib Tashlash",
    difficulty: 'EASY',
    points: 14,
    tags: ['Massivlar'],
    description: "O'sish tartibida saralangan butun sonlar massivi berilgan. Takrorlanuvchi elementlarni olib tashlab, faqat noyob (unique) elementlarni o'z ichiga olgan yangi massiv qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 1, 2, 2, 3]\nNatija: [1, 2, 3]\n\n**2-misol:**\nKiritma: arr = [0, 0, 1, 1, 1, 2]\nNatija: [0, 1, 2]",
    starterCodeJs: 'function removeDuplicates(arr) {\n  // your code here\n}',
    starterCodePy: 'def remove_duplicates(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> removeDuplicates(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-010',
    title: "Ikkita Saralangan Massivni Birlashtirish",
    difficulty: 'EASY',
    points: 17,
    tags: ['Massivlar'],
    description: "O'sish tartibida saralangan ikkita butun sonlar massivi berilgan. Ularni birlashtirib, yagona saralangan massiv qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr1 = [1, 3, 5], arr2 = [2, 4, 6]\nNatija: [1, 2, 3, 4, 5, 6]\n\n**2-misol:**\nKiritma: arr1 = [1, 2], arr2 = [3]\nNatija: [1, 2, 3]",
    starterCodeJs: 'function mergeSortedArrays(arr1, arr2) {\n  // your code here\n}',
    starterCodePy: 'def merge_sorted_arrays(arr1, arr2):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergeSortedArrays(vector<int>& arr1, vector<int>& arr2) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-011',
    title: "Eng Ko'p Uchraydigan Element",
    difficulty: 'EASY',
    points: 15,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivda eng ko'p marta uchraydigan elementni topib qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 3, 2, 3, 4, 3]\nNatija: 3\nIzoh: 3 soni massivda 3 marta uchraydi, bu eng ko'p.\n\n**2-misol:**\nKiritma: arr = [5, 5, 6]\nNatija: 5",
    starterCodeJs: 'function mostFrequent(arr) {\n  // your code here\n}',
    starterCodePy: 'def most_frequent(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int mostFrequent(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-012',
    title: "Prefiks Yig'indilar Massivi",
    difficulty: 'EASY',
    points: 16,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Har bir indeksda boshidan shu indeksgacha bo'lgan elementlar yig'indisini o'z ichiga olgan prefiks yig'indilar massivini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4]\nNatija: [1, 3, 6, 10]\n\n**2-misol:**\nKiritma: arr = [5, 0, 2]\nNatija: [5, 5, 7]",
    starterCodeJs: 'function prefixSum(arr) {\n  // your code here\n}',
    starterCodePy: 'def prefix_sum(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> prefixSum(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-013',
    title: "Ikki Massivning Kesishmasi",
    difficulty: 'EASY',
    points: 17,
    tags: ['Massivlar'],
    description: "Ikkita butun sonlar massivi berilgan. Ikkala massivda ham uchraydigan noyob elementlarni o'z ichiga olgan massiv qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr1 = [1, 2, 2, 3], arr2 = [2, 3, 4]\nNatija: [2, 3]\n\n**2-misol:**\nKiritma: arr1 = [4, 9, 5], arr2 = [9, 4, 9, 8]\nNatija: [4, 9]",
    starterCodeJs: 'function arrayIntersection(arr1, arr2) {\n  // your code here\n}',
    starterCodePy: 'def array_intersection(arr1, arr2):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> arrayIntersection(vector<int>& arr1, vector<int>& arr2) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-014',
    title: "Massiv Saralanganligini Tekshirish",
    difficulty: 'EASY',
    points: 11,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massiv o'sish tartibida saralanganligini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 2, 5, 9]\nNatija: true\n\n**2-misol:**\nKiritma: arr = [3, 1, 4]\nNatija: false",
    starterCodeJs: 'function isSorted(arr) {\n  // your code here\n}',
    starterCodePy: 'def is_sorted(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isSorted(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-015',
    title: "Nollarni Massiv Oxiriga Surish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Nolga teng bo'lgan barcha elementlarni, qolgan elementlarning nisbiy tartibini saqlagan holda, massiv oxiriga suruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [0, 1, 0, 3, 12]\nNatija: [1, 3, 12, 0, 0]\n\n**2-misol:**\nKiritma: arr = [0, 0, 1]\nNatija: [1, 0, 0]",
    starterCodeJs: 'function moveZeros(arr) {\n  // your code here\n}',
    starterCodePy: 'def move_zeros(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'void moveZeros(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-016',
    title: "Berilgan Yig'indiga Ega Juftliklarni Sanash",
    difficulty: 'EASY',
    points: 19,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi va target soni berilgan. Yig'indisi target ga teng bo'lgan barcha juftliklar sonini hisoblovchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 5, 7, -1], target = 6\nNatija: 2\nIzoh: (1,5) va (7,-1) juftliklari yig'indisi 6 ga teng.\n\n**2-misol:**\nKiritma: arr = [1, 1, 1], target = 2\nNatija: 3",
    starterCodeJs: 'function countPairsWithSum(arr, target) {\n  // your code here\n}',
    starterCodePy: 'def count_pairs_with_sum(arr, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int countPairsWithSum(vector<int>& arr, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-017',
    title: "Massiv O'rtacha Qiymati",
    difficulty: 'EASY',
    points: 10,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massiv elementlarining o'rtacha arifmetik qiymatini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4]\nNatija: 2.5\n\n**2-misol:**\nKiritma: arr = [10, 20, 30]\nNatija: 20",
    starterCodeJs: 'function arrayAverage(arr) {\n  // your code here\n}',
    starterCodePy: 'def array_average(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'double arrayAverage(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-018',
    title: "Massivni Bo'laklarga Bo'lish (Chunk)",
    difficulty: 'EASY',
    points: 18,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi va k soni berilgan. Massivni har birida k tadan elementi bo'lgan kichik massivlarga (bo'laklarga) bo'luvchi funksiya yozing. Oxirgi bo'lakda k tadan kam element bo'lishi mumkin.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4, 5], k = 2\nNatija: [[1, 2], [3, 4], [5]]\n\n**2-misol:**\nKiritma: arr = [1, 2, 3, 4], k = 4\nNatija: [[1, 2, 3, 4]]",
    starterCodeJs: 'function chunkArray(arr, k) {\n  // your code here\n}',
    starterCodePy: 'def chunk_array(arr, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> chunkArray(vector<int>& arr, int k) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-019',
    title: "Ikki O'lchamli Massivni Bir O'lchamga Keltirish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Massivlar'],
    description: "Ikki o'lchamli (matritsa ko'rinishidagi) butun sonlar massivi berilgan. Uni bitta bir o'lchamli massivga aylantiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: matrix = [[1, 2], [3, 4], [5]]\nNatija: [1, 2, 3, 4, 5]\n\n**2-misol:**\nKiritma: matrix = [[1], [2, 3]]\nNatija: [1, 2, 3]",
    starterCodeJs: 'function flattenArray(matrix) {\n  // your code here\n}',
    starterCodePy: 'def flatten_array(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> flattenArray(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-020',
    title: "Binar Qidiruv",
    difficulty: 'EASY',
    points: 20,
    tags: ['Massivlar'],
    description: "O'sish tartibida saralangan butun sonlar massivi va target soni berilgan. Binar qidiruv (binary search) algoritmi yordamida target ning massivdagi indeksini toping, agar mavjud bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: arr = [1, 3, 5, 7, 9, 11], target = 7\nNatija: 3\n\n**2-misol:**\nKiritma: arr = [2, 4, 6], target = 5\nNatija: -1",
    starterCodeJs: 'function binarySearch(arr, target) {\n  // your code here\n}',
    starterCodePy: 'def binary_search(arr, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int binarySearch(vector<int>& arr, int target) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-021',
    title: "Juft Sonlarni Ajratib Olish",
    difficulty: 'EASY',
    points: 11,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivdan faqat juft sonlarni ajratib, ularning tartibini saqlagan holda yangi massiv qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4, 5, 6]\nNatija: [2, 4, 6]\n\n**2-misol:**\nKiritma: arr = [7, 9, 11]\nNatija: []",
    starterCodeJs: 'function filterEvens(arr) {\n  // your code here\n}',
    starterCodePy: 'def filter_evens(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> filterEvens(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-022',
    title: "Manfiy Sonlarni Sanash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivdagi manfiy sonlar sonini hisoblovchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [-1, 2, -3, 4, -5]\nNatija: 3\n\n**2-misol:**\nKiritma: arr = [1, 2, 3]\nNatija: 0",
    starterCodeJs: 'function countNegatives(arr) {\n  // your code here\n}',
    starterCodePy: 'def count_negatives(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int countNegatives(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-023',
    title: "Ko'pchilik Elementni Topish (Majority Element)",
    difficulty: 'EASY',
    points: 21,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan, unda bitta element massiv uzunligining yarmidan ko'prog'ida uchraydi. Shu elementni topib qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [2, 2, 1, 2, 3, 2]\nNatija: 2\n\n**2-misol:**\nKiritma: arr = [5, 5, 5, 1, 2]\nNatija: 5",
    starterCodeJs: 'function majorityElement(arr) {\n  // your code here\n}',
    starterCodePy: 'def majority_element(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int majorityElement(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-024',
    title: "Yig'ma Ko'paytma Massivi (Cumulative Product)",
    difficulty: 'EASY',
    points: 16,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Har bir indeksda boshidan shu indeksgacha bo'lgan elementlarning ko'paytmasini o'z ichiga olgan massiv qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 4]\nNatija: [1, 2, 6, 24]\n\n**2-misol:**\nKiritma: arr = [2, 5]\nNatija: [2, 10]",
    starterCodeJs: 'function cumulativeProduct(arr) {\n  // your code here\n}',
    starterCodePy: 'def cumulative_product(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> cumulativeProduct(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-025',
    title: "Massivda Takrorlanuvchi Element Bor-yo'qligini Tekshirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi berilgan. Massivda kamida bitta element ikki marta takrorlansa true, aks holda false qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: arr = [1, 2, 3, 1]\nNatija: true\n\n**2-misol:**\nKiritma: arr = [1, 2, 3, 4]\nNatija: false",
    starterCodeJs: 'function containsDuplicate(arr) {\n  // your code here\n}',
    starterCodePy: 'def contains_duplicate(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'bool containsDuplicate(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-026',
    title: "Satrni Teskari Tartibga Keltirish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Satrlar'],
    description: "Satr berilgan. Uning belgilarini teskari tartibda joylashtirib qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"salom\"\nNatija: \"molas\"\n\n**2-misol:**\nKiritma: s = \"dunyo\"\nNatija: \"oynud\"",
    starterCodeJs: 'function reverseString(s) {\n  // your code here\n}',
    starterCodePy: 'def reverse_string(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string reverseString(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-027',
    title: "Palindrom Tekshiruvi",
    difficulty: 'EASY',
    points: 12,
    tags: ['Satrlar'],
    description: "Satr berilgan. Ushbu satr palindrom (old va orqa tomondan bir xil o'qiladigan) ekanligini tekshiruvchi funksiya yozing. Katta-kichik harflarga e'tibor bermang.\n\n**1-misol:**\nKiritma: s = \"Ana\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"salom\"\nNatija: false",
    starterCodeJs: 'function isPalindrome(s) {\n  // your code here\n}',
    starterCodePy: 'def is_palindrome(s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPalindrome(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-028',
    title: "Anagram Tekshiruvi",
    difficulty: 'EASY',
    points: 15,
    tags: ['Satrlar'],
    description: "Ikkita satr berilgan. Ular bir-birining anagrammi (bir xil harflardan tuzilgan, lekin tartibi boshqacha) ekanligini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s1 = \"tola\", s2 = \"lato\"\nNatija: true\n\n**2-misol:**\nKiritma: s1 = \"kitob\", s2 = \"kito\"\nNatija: false",
    starterCodeJs: 'function isAnagram(s1, s2) {\n  // your code here\n}',
    starterCodePy: 'def is_anagram(s1, s2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isAnagram(string s1, string s2) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-029',
    title: "Unli Va Undosh Harflarni Sanash",
    difficulty: 'EASY',
    points: 16,
    tags: ['Satrlar'],
    description: "Lotin harflaridan iborat satr berilgan. Undagi unli (a,e,i,o,u) va undosh harflar sonini hisoblab, [unlilar_soni, undoshlar_soni] ko'rinishida qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"hello\"\nNatija: [2, 3]\n\n**2-misol:**\nKiritma: s = \"sky\"\nNatija: [0, 3]",
    starterCodeJs: 'function countVowelsConsonants(s) {\n  // your code here\n}',
    starterCodePy: 'def count_vowels_consonants(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countVowelsConsonants(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-030',
    title: "Satrni Katta Harflarga O'tkazish",
    difficulty: 'EASY',
    points: 10,
    tags: ['Satrlar'],
    description: "Satr berilgan. Uning barcha harflarini katta (bosh) harflarga o'tkazuvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"salom dunyo\"\nNatija: \"SALOM DUNYO\"\n\n**2-misol:**\nKiritma: s = \"Test123\"\nNatija: \"TEST123\"",
    starterCodeJs: 'function toUpperCase(s) {\n  // your code here\n}',
    starterCodePy: 'def to_upper_case(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string toUpperCase(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-031',
    title: "Ichki Satrni Qidirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Satrlar'],
    description: "Asosiy satr va qidirilayotgan kichik satr (substring) berilgan. Kichik satr asosiy satr tarkibida mavjudligini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"dasturlash\", sub = \"tur\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"dasturlash\", sub = \"kod\"\nNatija: false",
    starterCodeJs: 'function containsSubstring(s, sub) {\n  // your code here\n}',
    starterCodePy: 'def contains_substring(s, sub):\n    # your code here\n    pass',
    starterCodeCpp: 'bool containsSubstring(string s, string sub) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-032',
    title: "Belgi Uchrash Sonini Hisoblash",
    difficulty: 'EASY',
    points: 11,
    tags: ['Satrlar'],
    description: "Satr va bitta belgi berilgan. Ushbu belgi satr ichida necha marta uchrashini hisoblovchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"banana\", ch = 'a'\nNatija: 3\n\n**2-misol:**\nKiritma: s = \"hello\", ch = 'l'\nNatija: 2",
    starterCodeJs: 'function countChar(s, ch) {\n  // your code here\n}',
    starterCodePy: 'def count_char(s, ch):\n    # your code here\n    pass',
    starterCodeCpp: 'int countChar(string s, char ch) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-033',
    title: "Takrorlanuvchi Belgilarni Olib Tashlash",
    difficulty: 'EASY',
    points: 17,
    tags: ['Satrlar'],
    description: "Satr berilgan. Undagi takrorlanuvchi belgilarni olib tashlab, har bir belgi birinchi marta uchragan tartibda faqat bir marta qatnashadigan yangi satr qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"programming\"\nNatija: \"progamin\"\n\n**2-misol:**\nKiritma: s = \"aabbcc\"\nNatija: \"abc\"",
    starterCodeJs: 'function removeDuplicateChars(s) {\n  // your code here\n}',
    starterCodePy: 'def remove_duplicate_chars(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string removeDuplicateChars(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-034',
    title: "Gapdagi Eng Uzun So'zni Topish",
    difficulty: 'EASY',
    points: 15,
    tags: ['Satrlar'],
    description: "Bo'sh joylar bilan ajratilgan so'zlardan iborat gap berilgan. Gapdagi eng uzun so'zni topib qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: sentence = \"Men dasturlashni yaxshi ko'raman\"\nNatija: \"dasturlashni\"\n\n**2-misol:**\nKiritma: sentence = \"u uy ket\"\nNatija: \"uy\"",
    starterCodeJs: 'function longestWord(sentence) {\n  // your code here\n}',
    starterCodePy: 'def longest_word(sentence):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestWord(string sentence) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-035',
    title: "Harflar Chastotasini Hisoblash",
    difficulty: 'EASY',
    points: 18,
    tags: ['Satrlar'],
    description: "Satr berilgan. Satrdagi har bir harfning necha marta uchrashini hisoblab, harf-son juftliklari (lug'at/xarita) ko'rinishida qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"aabbc\"\nNatija: {a: 2, b: 2, c: 1}\n\n**2-misol:**\nKiritma: s = \"xyz\"\nNatija: {x: 1, y: 1, z: 1}",
    starterCodeJs: 'function charFrequency(s) {\n  // your code here\n}',
    starterCodePy: 'def char_frequency(s):\n    # your code here\n    pass',
    starterCodeCpp: 'map<char, int> charFrequency(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-036',
    title: "Satrni Siqish (Compression)",
    difficulty: 'EASY',
    points: 19,
    tags: ['Satrlar'],
    description: "Satr berilgan. Ketma-ket takrorlanuvchi belgilarni belgi va uning takrorlanish sonidan iborat qisqa ko'rinishga siquvchi funksiya yozing. Agar siqilgan satr asl satrdan uzunroq bo'lsa, asl satrni qaytaring.\n\n**1-misol:**\nKiritma: s = \"aaabbc\"\nNatija: \"a3b2c1\"\n\n**2-misol:**\nKiritma: s = \"abc\"\nNatija: \"abc\"",
    starterCodeJs: 'function compressString(s) {\n  // your code here\n}',
    starterCodePy: 'def compress_string(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string compressString(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-037',
    title: "To'g'ri Qavslarni Tekshirish",
    difficulty: 'EASY',
    points: 20,
    tags: ['Satrlar'],
    description: "Faqat '(', ')', '{', '}', '[', ']' belgilaridan iborat satr berilgan. Qavslar to'g'ri ochilib-yopilganligini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"({[]})\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"(]\"\nNatija: false",
    starterCodeJs: 'function isValidParentheses(s) {\n  // your code here\n}',
    starterCodePy: 'def is_valid_parentheses(s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isValidParentheses(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-038',
    title: "Har Bir So'zni Bosh Harf Bilan Boshlash",
    difficulty: 'EASY',
    points: 13,
    tags: ['Satrlar'],
    description: "Bo'sh joylar bilan ajratilgan so'zlardan iborat gap berilgan. Gapdagi har bir so'zning birinchi harfini katta harfga aylantiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: sentence = \"assalomu alaykum\"\nNatija: \"Assalomu Alaykum\"\n\n**2-misol:**\nKiritma: sentence = \"salom\"\nNatija: \"Salom\"",
    starterCodeJs: 'function capitalizeWords(sentence) {\n  // your code here\n}',
    starterCodePy: 'def capitalize_words(sentence):\n    # your code here\n    pass',
    starterCodeCpp: 'string capitalizeWords(string sentence) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-039',
    title: "Gapdagi So'zlar Sonini Hisoblash",
    difficulty: 'EASY',
    points: 11,
    tags: ['Satrlar'],
    description: "Bo'sh joylar bilan ajratilgan so'zlardan iborat gap berilgan. Undagi so'zlar sonini hisoblovchi funksiya yozing.\n\n**1-misol:**\nKiritma: sentence = \"Salom dunyo qandaysan\"\nNatija: 3\n\n**2-misol:**\nKiritma: sentence = \"  bitta   so'z  \"\nNatija: 2",
    starterCodeJs: 'function countWords(sentence) {\n  // your code here\n}',
    starterCodePy: 'def count_words(sentence):\n    # your code here\n    pass',
    starterCodeCpp: 'int countWords(string sentence) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-040',
    title: "Gapdagi So'zlarni Teskari Tartibga Keltirish",
    difficulty: 'EASY',
    points: 16,
    tags: ['Satrlar'],
    description: "Bo'sh joylar bilan ajratilgan so'zlardan iborat gap berilgan. So'zlarning tartibini teskari qilib (har bir so'zning o'zi o'zgarishsiz qolgan holda) qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: sentence = \"Men kitob o'qiyman\"\nNatija: \"o'qiyman kitob Men\"\n\n**2-misol:**\nKiritma: sentence = \"salom dunyo\"\nNatija: \"dunyo salom\"",
    starterCodeJs: 'function reverseWords(sentence) {\n  // your code here\n}',
    starterCodePy: 'def reverse_words(sentence):\n    # your code here\n    pass',
    starterCodeCpp: 'string reverseWords(string sentence) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-041',
    title: "Ikkita Satr Bir-birining Aylanishi Ekanligini Tekshirish",
    difficulty: 'EASY',
    points: 19,
    tags: ['Satrlar'],
    description: "Ikkita satr berilgan. Ikkinchi satr birinchi satrning aylantirilgan (rotation) ko'rinishi ekanligini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s1 = \"kitob\", s2 = \"tobki\"\nNatija: true\n\n**2-misol:**\nKiritma: s1 = \"salom\", s2 = \"lomsa\"\nNatija: false",
    starterCodeJs: 'function areRotations(s1, s2) {\n  // your code here\n}',
    starterCodePy: 'def are_rotations(s1, s2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool areRotations(string s1, string s2) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-042',
    title: "Satrdan Bo'sh Joylarni Olib Tashlash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Satrlar'],
    description: "Satr berilgan. Undagi barcha bo'sh joy belgilarini olib tashlovchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"salom  dunyo\"\nNatija: \"salomdunyo\"\n\n**2-misol:**\nKiritma: s = \" a b c \"\nNatija: \"abc\"",
    starterCodeJs: 'function removeWhitespace(s) {\n  // your code here\n}',
    starterCodePy: 'def remove_whitespace(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string removeWhitespace(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-043',
    title: "Satrdagi Belgi Turlarini Sanash",
    difficulty: 'EASY',
    points: 18,
    tags: ['Satrlar'],
    description: "Satr berilgan. Undagi harflar, raqamlar va maxsus belgilar sonini hisoblab, [harflar_soni, raqamlar_soni, maxsus_belgilar_soni] ko'rinishida qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"Salom123!\"\nNatija: [5, 3, 1]\n\n**2-misol:**\nKiritma: s = \"abc\"\nNatija: [3, 0, 0]",
    starterCodeJs: 'function countCharTypes(s) {\n  // your code here\n}',
    starterCodePy: 'def count_char_types(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countCharTypes(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-044',
    title: "Birinchi Takrorlanmagan Belgini Topish",
    difficulty: 'EASY',
    points: 17,
    tags: ['Satrlar'],
    description: "Satr berilgan. Satrda faqat bir marta uchraydigan birinchi belgini topib qaytaruvchi funksiya yozing. Agar bunday belgi bo'lmasa, bo'sh belgi qaytaring.\n\n**1-misol:**\nKiritma: s = \"topqirlik\"\nNatija: \"t\"\n\n**2-misol:**\nKiritma: s = \"aabb\"\nNatija: \"\"",
    starterCodeJs: 'function firstNonRepeatingChar(s) {\n  // your code here\n}',
    starterCodePy: 'def first_non_repeating_char(s):\n    # your code here\n    pass',
    starterCodeCpp: 'char firstNonRepeatingChar(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-045',
    title: "Satr Faqat Raqamlardan Iboratligini Tekshirish",
    difficulty: 'EASY',
    points: 12,
    tags: ['Satrlar'],
    description: "Satr berilgan. Ushbu satr faqat raqamlardan iborat ekanligini (ya'ni butun songa aylantirish mumkinligini) tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"12345\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"12a45\"\nNatija: false",
    starterCodeJs: 'function isNumeric(s) {\n  // your code here\n}',
    starterCodePy: 'def is_numeric(s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isNumeric(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-046',
    title: "Satrlar Massivining Umumiy Prefiksi",
    difficulty: 'EASY',
    points: 18,
    tags: ['Satrlar'],
    description: "Satrlar massivi berilgan. Barcha satrlar uchun umumiy bo'lgan eng uzun boshlang'ich qismni (prefiksni) topib qaytaruvchi funksiya yozing. Agar umumiy prefiks bo'lmasa, bo'sh satr qaytaring.\n\n**1-misol:**\nKiritma: strs = [\"gulzor\", \"gulshan\", \"gultoj\"]\nNatija: \"gul\"\n\n**2-misol:**\nKiritma: strs = [\"olma\", \"anor\"]\nNatija: \"\"",
    starterCodeJs: 'function longestCommonPrefix(strs) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_prefix(strs):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonPrefix(vector<string>& strs) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-047',
    title: "Satrni Songa Aylantirish",
    difficulty: 'EASY',
    points: 20,
    tags: ['Satrlar'],
    description: "Raqamlardan (va ixtiyoriy '-' belgisidan) iborat satr berilgan. Uni butun songa aylantiruvchi funksiya yozing (standart kutubxona funksiyalaridan foydalanmasdan, o'zingiz amalga oshiring).\n\n**1-misol:**\nKiritma: s = \"123\"\nNatija: 123\n\n**2-misol:**\nKiritma: s = \"-45\"\nNatija: -45",
    starterCodeJs: 'function stringToInt(s) {\n  // your code here\n}',
    starterCodePy: 'def string_to_int(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int stringToInt(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-048',
    title: "Satr Berilgan Qism Bilan Boshlanishi Yoki Tugashini Tekshirish",
    difficulty: 'EASY',
    points: 14,
    tags: ['Satrlar'],
    description: "Asosiy satr va boshqa bir kichik satr berilgan. Asosiy satr shu kichik satr bilan boshlanishi yoki tugashini tekshiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"dasturlash\", sub = \"das\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"dasturlash\", sub = \"lish\"\nNatija: false",
    starterCodeJs: 'function startsOrEndsWith(s, sub) {\n  // your code here\n}',
    starterCodePy: 'def starts_or_ends_with(s, sub):\n    # your code here\n    pass',
    starterCodeCpp: 'bool startsOrEndsWith(string s, string sub) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-049',
    title: "Satrdagi Unlilar Sonini Hisoblash",
    difficulty: 'EASY',
    points: 10,
    tags: ['Satrlar'],
    description: "Satr berilgan. Undagi unli harflar (a, e, i, o, u) sonini hisoblovchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"salom dunyo\"\nNatija: 3\n\n**2-misol:**\nKiritma: s = \"tst\"\nNatija: 0",
    starterCodeJs: 'function countVowels(s) {\n  // your code here\n}',
    starterCodePy: 'def count_vowels(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int countVowels(string s) {\n    // your code here\n}',
  },
  {
    key: 'easy-a-050',
    title: "Harflar Registrini Almashtirish (Swap Case)",
    difficulty: 'EASY',
    points: 13,
    tags: ['Satrlar'],
    description: "Satr berilgan. Undagi katta harflarni kichikka, kichik harflarni esa kattaga aylantiruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: s = \"Salom Dunyo\"\nNatija: \"sALOM dUNYO\"\n\n**2-misol:**\nKiritma: s = \"ABC\"\nNatija: \"abc\"",
    starterCodeJs: 'function swapCase(s) {\n  // your code here\n}',
    starterCodePy: 'def swap_case(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string swapCase(string s) {\n    // your code here\n}',
  },
];
