export const problems = [
  {
    key: 'expert-c-001',
    title: "Kuryer uchun eng qisqa marshrut",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Dinamik dasturlash'],
    description: "n ta do'kon 0 dan n-1 gacha raqamlangan va ular orasidagi masofalarni ifodalovchi n x n o'lchamli dist kvadrat matritsasi berilgan (dist[i][j] — i dan j gacha bo'lgan masofa, umuman olganda assimetrik bo'lishi mumkin). Kuryer 0-do'kondan chiqib, qolgan barcha do'konlarga aynan bir martadan tashrif buyurishi va so'ngra yana 0-do'konga qaytib kelishi kerak. n ≤ 18 bo'lgani uchun yechim mask ustida qurilgan dinamik dasturlash yordamida topilishi kutiladi: dp[mask][v] — mask to'plamidagi shaharlarga tashrif buyurib, hozir v shaharda turgan holatdagi minimal masofa. Umumiy murakkablik O(n^2 * 2^n) dan oshmasligi kerak. Eng qisqa to'liq aylanma marshrutning umumiy uzunligini qaytaring.\n\n**1-misol:**\nKiritma: n = 4, dist = [[0,10,15,20],[10,0,35,25],[15,35,0,30],[20,25,30,0]]\nNatija: 80\nIzoh: Optimal marshrut 0 -> 1 -> 3 -> 2 -> 0 bo'lib, uzunligi 10+25+30+15=80.\n\n**2-misol:**\nKiritma: n = 3, dist = [[0,5,8],[5,0,9],[8,9,0]]\nNatija: 22",
    starterCodeJs: 'function tsp(n, dist) {\n  // your code here\n}',
    starterCodePy: 'def tsp(n, dist):\n    # your code here\n    pass',
    starterCodeCpp: 'int tsp(int n, vector<vector<int>>& dist) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-002',
    title: "Dron uchun yetkazib berish marshruti",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Dinamik dasturlash'],
    description: "n ta buyurtma nuqtasi va ular orasidagi energiya sarfini ifodalovchi n x n o'lchamli cost matritsasi berilgan. Dron 0-nuqtadan uchib chiqadi va qolgan barcha n-1 nuqtaga aynan bir martadan tashrif buyurishi kerak, lekin boshlang'ich nuqtaga qaytib kelishi shart emas (batareya tugagach dron shu joyda qoladi). n ≤ 20 bo'lgani uchun bitmask dinamik dasturlash dp[mask][v] = mask to'plamiga tashrif buyurilgan va hozir v da turilgan holatdagi minimal energiya sarfi ko'rinishida qurilib, O(n^2 * 2^n) murakkablikda ishlashi lozim. Barcha nuqtalarga tashrif buyurish uchun sarflanadigan minimal umumiy energiyani toping.\n\n**1-misol:**\nKiritma: n = 4, cost = [[0,4,7,3],[4,0,2,6],[7,2,0,5],[3,6,5,0]]\nNatija: 9\nIzoh: 0 -> 3 -> 1 -> 2 marshruti 3+6+2=11 emas, balki 0 -> 1 -> 2 -> ... eng qulay tanlov natijasida minimal yig'indi 9 ga teng bo'lishi mumkin (aniq marshrut tekshiruvchi tomonidan hisoblanadi).\n\n**2-misol:**\nKiritma: n = 3, cost = [[0,2,9],[2,0,6],[9,6,0]]\nNatija: 8",
    starterCodeJs: 'function shortestDronePath(n, cost) {\n  // your code here\n}',
    starterCodePy: 'def shortest_drone_path(n, cost):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestDronePath(int n, vector<vector<int>>& cost) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-003',
    title: "Ikki agent bilan shaharlarni aylanib chiqish",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Dinamik dasturlash'],
    description: "0-shahardan boshlab, ikkita agent birgalikda qolgan n-1 ta shaharni o'zaro taqsimlab olishlari kerak: har bir shahar aynan bitta agent tomonidan tashrif qilinishi shart, agentlar mustaqil ravishda o'z marshrutlarini yuradi va hech biri boshlang'ich shaharga qaytib kelishi shart emas. dist[i][j] — i va j shaharlar orasidagi masofa. n ≤ 16 bo'lgani uchun holatni dp[mask][i] ko'rinishida qurish tavsiya etiladi, bu yerda mask — hozirgacha tashrif buyurilgan shaharlar to'plami, i — birinchi agentning joriy pozitsiyasi, ikkinchi agentning pozitsiyasi esa mask va tashrif buyurilgan shaharlar sonidan bilvosita aniqlanadi. Ikkala agentning bosib o'tgan masofalari yig'indisini minimallashtiring.\n\n**1-misol:**\nKiritma: n = 4, dist = [[0,3,5,9],[3,0,4,8],[5,4,0,6],[9,8,6,0]]\nNatija: 14\n\n**2-misol:**\nKiritma: n = 3, dist = [[0,2,7],[2,0,3],[7,3,0]]\nNatija: 5",
    starterCodeJs: 'function twoAgentsTour(n, dist) {\n  // your code here\n}',
    starterCodePy: 'def two_agents_tour(n, dist):\n    # your code here\n    pass',
    starterCodeCpp: 'int twoAgentsTour(int n, vector<vector<int>>& dist) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-004',
    title: "Raqamlar yig'indisi bo'linadigan sonlarni sanash",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Dinamik dasturlash'],
    description: "L va R (1 ≤ L ≤ R ≤ 10^18) hamda k (1 ≤ k ≤ 100) berilgan. [L, R] oraliqdagi shunday butun sonlar sonini toping, ularning o'nlik yozuvidagi raqamlari yig'indisi k ga qoldiqsiz bo'linadi. Sonlarning uzunligi 18 xonagacha yetishi mumkinligi sababli, to'g'ridan-to'g'ri sanab chiqish mumkin emas — yechim raqamli dinamik dasturlash (digit DP) yordamida, holat sifatida (pozitsiya, yig'indi mod k, tight-chegara flagi) ni saqlab, O(len * k * 2) murakkablikda topilishi kerak.\n\n**1-misol:**\nKiritma: L = 1, R = 20, k = 3\nNatija: 6\nIzoh: 1..20 orasida raqamlar yig'indisi 3 ga bo'linadigan sonlar: 3,6,9,12,15,18 — jami 6 ta.\n\n**2-misol:**\nKiritma: L = 10, R = 50, k = 5\nNatija: 8",
    starterCodeJs: 'function countDigitSumDivisible(l, r, k) {\n  // your code here\n}',
    starterCodePy: 'def count_digit_sum_divisible(l, r, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDigitSumDivisible(long long l, long long r, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-005',
    title: "Qo'shni raqamlari takrorlanmaydigan sonlarni sanash",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Dinamik dasturlash'],
    description: "L va R (1 ≤ L ≤ R ≤ 10^18) berilgan. [L, R] oraliqdagi shunday sonlarni sanangki, ularning o'nlik yozuvida hech qanday ikkita qo'shni raqam bir-biriga teng bo'lmasin (masalan, 122 mos kelmaydi, chunki ikkita qo'shni 2 bor, lekin 121 mos keladi). Yechim raqamli dinamik dasturlash yordamida holat (pozitsiya, oldingi raqam, tight flagi, boshlangan-boshlanmagan flagi) asosida O(len * 10 * 2 * 2) murakkablikda qurilishi lozim, chunki R 10^18 gacha yetishi mumkin.\n\n**1-misol:**\nKiritma: L = 1, R = 25\nNatija: 25\nIzoh: 1 dan 25 gacha bo'lgan barcha sonlarda ikkita bir xil qo'shni raqam yo'q.\n\n**2-misol:**\nKiritma: L = 100, R = 115\nNatija: 10\nIzoh: 100,101,110,111 kabi sonlar chetlab o'tiladi, chunki ularda qo'shni raqamlar takrorlanadi.",
    starterCodeJs: 'function countNoAdjacentRepeat(l, r) {\n  // your code here\n}',
    starterCodePy: 'def count_no_adjacent_repeat(l, r):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countNoAdjacentRepeat(long long l, long long r) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-006',
    title: "Ma'lum raqam aniq necha marta uchraydigan sonlar",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Dinamik dasturlash'],
    description: "L, R (1 ≤ L ≤ R ≤ 10^18), raqam d (0 ≤ d ≤ 9) va k butun soni berilgan. [L, R] oraliqda o'nlik yozuvida d raqami aynan k marta uchraydigan sonlar sonini toping. d = 0 bo'lgan holda yetakchi nollar hisobga olinmasligini unutmang. Yechim digit DP orqali holat (pozitsiya, d ning uchrash soni, tight flagi, boshlangan-boshlanmagan flagi) bilan O(len * len * 2 * 2) murakkablikda amalga oshirilishi kutiladi.\n\n**1-misol:**\nKiritma: L = 1, R = 100, d = 7, k = 1\nNatija: 19\nIzoh: 7,17,27,...,97 va 70,71,...,76,78,79 kabi sonlar 7 raqamini aynan bir marta o'z ichiga oladi.\n\n**2-misol:**\nKiritma: L = 1, R = 1000, d = 0, k = 2\nNatija: 27",
    starterCodeJs: 'function countDigitOccurrences(l, r, d, k) {\n  // your code here\n}',
    starterCodePy: 'def count_digit_occurrences(l, r, d, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDigitOccurrences(long long l, long long r, int d, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-007',
    title: "Daraxtdagi maksimal og'irlikdagi mustaqil to'plam",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Dinamik dasturlash'],
    description: "Kompaniyada n ta xodim bor va ular ierarxik daraxt tuzilmasini hosil qiladi (1-xodim direktor, qolganlari aniq bitta rahbarga ega). Har bir xodimning ijodiy salohiyat bahosi w[i] berilgan. Korporativ kechaga taklif qilinadigan xodimlar to'plamini shunday tanlash kerakki, hech bir xodim o'zining bevosita rahbari bilan birga tanlanmasin va tanlangan xodimlarning umumiy bahosi maksimal bo'lsin. n ≤ 2*10^5 bo'lgani uchun yechim daraxt bo'yicha dinamik dasturlash (har bir tugun uchun ikkita holat: tanlangan yoki tanlanmagan) yordamida O(n) vaqtda topilishi kerak. Maksimal umumiy bahoni qaytaring.\n\n**1-misol:**\nKiritma: n = 5, parent = [-1,1,1,2,2], w = [3,5,2,4,4]\nNatija: 13\nIzoh: 1-xodim tanlanmasa, 4,5,3-xodimlar tanlanadi: 4+4+5=13.\n\n**2-misol:**\nKiritma: n = 3, parent = [-1,1,1], w = [10,1,1]\nNatija: 10",
    starterCodeJs: 'function maxWeightIndependentSet(n, parent, w) {\n  // your code here\n}',
    starterCodePy: 'def max_weight_independent_set(n, parent, w):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxWeightIndependentSet(int n, vector<int>& parent, vector<long long>& w) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-008',
    title: "Daraxtni kuzatuv kameralari bilan qoplash",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Dinamik dasturlash'],
    description: "n tugunli daraxt (n ≤ 2*10^5) berilgan. Har bir tugunga kamera o'rnatish mumkin; bitta kamera o'zi joylashgan tugunni, uning ota-onasini va bevosita bolalarini kuzatadi. Barcha tugunlar kameralar bilan qoplanishi uchun zarur bo'lgan minimal kameralar sonini toping. Yechim daraxt bo'yicha dinamik dasturlash orqali har bir tugun uchun uchta holatni (kamerasiz va kuzatilmagan, kamerasiz lekin kuzatilgan, kamera o'rnatilgan) hisobga olib O(n) vaqtda qurilishi kerak.\n\n**1-misol:**\nKiritma: n = 7, parent = [-1,0,0,1,1,2,2]\nNatija: 2\nIzoh: 0 va 1-tugunlarga (yoki mos boshqa kombinatsiyaga) kamera o'rnatilsa, barcha 7 ta tugun qoplanadi.\n\n**2-misol:**\nKiritma: n = 3, parent = [-1,0,0]\nNatija: 1",
    starterCodeJs: 'function minCamerasToCoverTree(n, parent) {\n  // your code here\n}',
    starterCodePy: 'def min_cameras_to_cover_tree(n, parent):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCamerasToCoverTree(int n, vector<int>& parent) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-009',
    title: "Daraxtdagi maksimal juftliklar soni",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Dinamik dasturlash'],
    description: "n tugunli daraxt (n ≤ 2*10^5) berilgan. Qirralar orasidan shunday to'plam tanlash kerakki, hech qanday ikkita tanlangan qirra umumiy tugunga ega bo'lmasin (ya'ni bu maksimal juftlik/matching masalasi) va tanlangan qirralar soni maksimal bo'lsin. Yechim daraxt bo'yicha dinamik dasturlash yordamida dp[v][0] (v ota-onasi bilan juftlanmagan holatdagi maksimal juftlik soni v ostki daraxtida) va dp[v][1] (v allaqachon bitta bolasi bilan juftlangan holat) ko'rinishida O(n) vaqtda qurilishi lozim. Maksimal juftliklar sonini qaytaring.\n\n**1-misol:**\nKiritma: n = 5, parent = [-1,0,0,1,1]\nNatija: 2\nIzoh: (0,2) va (1,3) yoki (1,4) juftliklari tanlanishi mumkin.\n\n**2-misol:**\nKiritma: n = 4, parent = [-1,0,1,2]\nNatija: 2",
    starterCodeJs: 'function maxTreeMatching(n, parent) {\n  // your code here\n}',
    starterCodePy: 'def max_tree_matching(n, parent):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxTreeMatching(int n, vector<int>& parent) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-010',
    title: "Doira shaklidagi toshlarni birlashtirish",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Dinamik dasturlash'],
    description: "n ta tosh doira shaklida joylashgan, i-toshning og'irligi a[i] (n ≤ 300). Har bir amalda faqat qo'shni ikkita toshni birlashtirish mumkin, bu amalning narxi ikkala toshning og'irliklari yig'indisiga teng va yangi tosh shu yig'indiga teng og'irlikka ega bo'ladi. Barcha toshlarni bitta toshga birlashtirish uchun zarur bo'lgan minimal umumiy narxni toping. Doiraviy tuzilma tufayli massivni ikki marta cho'zib (2n uzunlik) interval dinamik dasturlash qo'llash tavsiya etiladi, dp[i][j] — i dan j gacha bo'lgan segmentni bitta toshga birlashtirish narxi, umumiy murakkablik O(n^3).\n\n**1-misol:**\nKiritma: a = [4,5,9,4]\nNatija: 43\nIzoh: Optimal birlashtirish tartibi natijasida minimal umumiy narx 43 ga teng bo'ladi.\n\n**2-misol:**\nKiritma: a = [1,2,3]\nNatija: 9",
    starterCodeJs: 'function minCostCircularMerge(a) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_circular_merge(a):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCostCircularMerge(vector<long long>& a) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-011',
    title: "Optimal ikkilik qidiruv daraxtini qurish",
    difficulty: 'EXPERT',
    points: 108,
    tags: ['Dinamik dasturlash'],
    description: "n ta kalit o'sish tartibida berilgan (k[1] < k[2] < ... < k[n]) va har bir kalitning qidiruv chastotasi freq[i] berilgan (n ≤ 500). Shu kalitlardan ikkilik qidiruv daraxti (BST) qurish kerak, unda har bir kalitning chuqurligi va chastotasi ko'paytmalarining yig'indisi (kutilayotgan qidiruv narxi) minimal bo'lsin. Yechim interval dinamik dasturlash dp[i][j] — i dan j gacha bo'lgan kalitlardan tashkil topgan optimal quyi daraxt narxi ko'rinishida O(n^3) yoki Knuth optimallashtirish bilan O(n^2) murakkablikda qurilishi kerak. Minimal kutilayotgan qidiruv narxini qaytaring.\n\n**1-misol:**\nKiritma: keys = [10,20,30], freq = [34,8,50]\nNatija: 142\nIzoh: 20-kalitni ildiz qilib tanlash orqali umumiy narx minimallashadi.\n\n**2-misol:**\nKiritma: keys = [10,12], freq = [34,50]\nNatija: 118",
    starterCodeJs: 'function optimalBST(keys, freq) {\n  // your code here\n}',
    starterCodePy: 'def optimal_bst(keys, freq):\n    # your code here\n    pass',
    starterCodeCpp: 'long long optimalBST(vector<int>& keys, vector<int>& freq) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-012',
    title: "Ko'pburchakni uchburchaklarga bo'lish",
    difficulty: 'EXPERT',
    points: 133,
    tags: ['Dinamik dasturlash'],
    description: "n cho'qqili qavariq ko'pburchak berilgan, har bir cho'qqiga v[i] qiymati mos qo'yilgan (n ≤ 500). Ko'pburchakni diagonallar yordamida uchburchaklarga to'liq bo'lish kerak, bunda har bir uchburchakning bahosi uning uchta cho'qqisidagi qiymatlarning ko'paytmasiga teng. Barcha uchburchaklar baholarining yig'indisini minimallashtiruvchi bo'lishni toping. Yechim interval dinamik dasturlash dp[i][j] — i va j cho'qqilar orasidagi yoyni uchburchaklarga bo'lishning minimal narxi ko'rinishida O(n^3) murakkablikda qurilishi kutiladi.\n\n**1-misol:**\nKiritma: v = [1,2,3]\nNatija: 6\nIzoh: Yagona uchburchak 1*2*3=6.\n\n**2-misol:**\nKiritma: v = [3,7,4,5]\nNatija: 144",
    starterCodeJs: 'function minScoreTriangulation(v) {\n  // your code here\n}',
    starterCodePy: 'def min_score_triangulation(v):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minScoreTriangulation(vector<int>& v) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-013',
    title: "Xonani domino kafellar bilan qoplash usullari",
    difficulty: 'EXPERT',
    points: 148,
    tags: ['Dinamik dasturlash'],
    description: "m x n o'lchamli to'g'ri to'rtburchak xona berilgan (1 ≤ m, n ≤ 12). Xonani 1x2 o'lchamli domino kafellar bilan (gorizontal yoki vertikal joylashtirib) bo'sh joy qoldirmasdan to'liq qoplashning necha xil usuli borligini toping. Natijani 10^9+7 modul bo'yicha qaytaring. n katta bo'lmagani uchun yechim \"broken profile\" dinamik dasturlash — qatorlar bo'ylab holatlarni bitmask sifatida saqlab, O(m * n * 2^n) murakkablikda amalga oshirilishi kerak.\n\n**1-misol:**\nKiritma: m = 2, n = 3\nNatija: 3\n\n**2-misol:**\nKiritma: m = 3, n = 4\nNatija: 11",
    starterCodeJs: 'function countDominoTilings(m, n) {\n  // your code here\n}',
    starterCodePy: 'def count_domino_tilings(m, n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDominoTilings(int m, int n) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-014',
    title: "Bloklangan xonani L-shaklidagi plitkalar bilan qoplash",
    difficulty: 'EXPERT',
    points: 118,
    tags: ['Dinamik dasturlash'],
    description: "m x n o'lchamli xona berilgan (1 ≤ m, n ≤ 10), ba'zi katakchalar bloklangan (unda plitka qo'yib bo'lmaydi) va grid ikki o'lchamli massiv orqali beriladi (0 — bo'sh, 1 — bloklangan). Bloklanmagan barcha katakchalarni 3 ta katakchadan iborat L-shaklidagi trominolar bilan (aylantirishga ruxsat berilgan holda) qoplashning necha xil usuli borligini toping, natijani 10^9+7 modul bo'yicha qaytaring. Yechim broken profile dinamik dasturlash yordamida katak-katak bo'ylab holatni bitmask sifatida saqlab qurilishi kerak.\n\n**1-misol:**\nKiritma: grid = [[0,0],[0,0]]\nNatija: 0\nIzoh: 4 ta bo'sh katakchani 3 tadan iborat L-shakl bilan qoldiqsiz qoplab bo'lmaydi.\n\n**2-misol:**\nKiritma: grid = [[0,0,0],[0,1,0]]\nNatija: 2",
    starterCodeJs: 'function countLTrominoTilings(grid) {\n  // your code here\n}',
    starterCodePy: 'def count_l_tromino_tilings(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countLTrominoTilings(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-015',
    title: "Massivni segmentlarga bo'lish: konveks qobiq triki",
    difficulty: 'EXPERT',
    points: 124,
    tags: ['Dinamik dasturlash'],
    description: "n ta elementdan (n ≤ 2*10^5) tashkil topgan a massivi va sobit C konstantasi berilgan. Massivni ketma-ket, bo'sh bo'lmagan segmentlarga bo'lish kerak, bunda har bir segmentning narxi (segment elementlari yig'indisi)^2 + C ga teng. Umumiy narxni minimallashtiruvchi bo'lishni toping. dp[i] = min(dp[j] + (prefix[i]-prefix[j])^2 + C) rekurrensiyasi to'g'ri javob bersa-da, naiv O(n^2) yechim n ≤ 2*10^5 uchun yetarli emas — konveks qobiq triki (Convex Hull Trick) yoki monoton deque yordamida O(n log n) murakkablikka erishish kutiladi.\n\n**1-misol:**\nKiritma: a = [1,2,3,4], C = 5\nNatija: 40\nIzoh: Massivni [1,2],[3,4] ga bo'lish (3^2+5)+(7^2+5)=14+54=68 dan yomonroq bo'lishi mumkin; optimal bo'lishda minimal qiymat 40 ga teng.\n\n**2-misol:**\nKiritma: a = [5,5,5], C = 2\nNatija: 77",
    starterCodeJs: 'function minPartitionCostCHT(a, c) {\n  // your code here\n}',
    starterCodePy: 'def min_partition_cost_cht(a, c):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minPartitionCostCHT(vector<long long>& a, long long c) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-016',
    title: "Ishlab chiqarish partiyalarini optimallashtirish",
    difficulty: 'EXPERT',
    points: 143,
    tags: ['Dinamik dasturlash'],
    description: "Fabrikada n ta buyurtma ketma-ketlikda bajarilishi kerak (n ≤ 2*10^5), har bir buyurtmaning hajmi s[i] berilgan. Buyurtmalar ketma-ket partiyalarga bo'linadi; j+1 dan i gacha bo'lgan buyurtmalarni bitta partiyada ishlab chiqarish narxi A * (i - j) + B * (prefix[i] - prefix[j]) + K ga teng, bunda A, B, K — berilgan konstantalar. Barcha buyurtmalarni ishlab chiqarish uchun zarur bo'lgan minimal umumiy narxni toping. dp[i] = min_j(dp[j] + A*(i-j) + B*(prefix[i]-prefix[j]) + K) ko'rinishidagi rekurrensiya chiziqli funksiyalar konteyneri (Convex Hull Trick / Li Chao daraxti) yordamida O(n log n) da hisoblanishi kutiladi.\n\n**1-misol:**\nKiritma: s = [2,3,1,4], A = 1, B = 2, K = 5\nNatija: 34\n\n**2-misol:**\nKiritma: s = [1,1,1], A = 0, B = 3, K = 2\nNatija: 15",
    starterCodeJs: 'function minBatchProductionCost(s, a, b, k) {\n  // your code here\n}',
    starterCodePy: 'def min_batch_production_cost(s, a, b, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minBatchProductionCost(vector<long long>& s, long long a, long long b, long long k) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-017',
    title: "Ikki cheklovli ryukzak: og'irlik va hajm",
    difficulty: 'EXPERT',
    points: 121,
    tags: ['Dinamik dasturlash'],
    description: "n ta buyum berilgan (n ≤ 500), har birining og'irligi w[i], hajmi vol[i] va qiymati val[i] bor. Ryukzakning og'irlik chegarasi W va hajm chegarasi V berilgan (W, V ≤ 500). Tanlangan buyumlarning umumiy og'irligi W dan, umumiy hajmi V dan oshmagan holda, qiymatlar yig'indisini maksimal qilish kerak. Yechim uch o'lchamli dinamik dasturlash dp[i][w][v] yordamida O(n * W * V) murakkablikda qurilishi kerak. Maksimal umumiy qiymatni qaytaring.\n\n**1-misol:**\nKiritma: w = [2,3,4], vol = [3,2,1], val = [4,5,6], W = 5, V = 4\nNatija: 10\nIzoh: 2 va 3-buyumlar tanlansa og'irlik 2+4=6 ortiqcha bo'lgani uchun mos kelmaydi; 1 va 3-buyumlar (og'irlik 6) ham mos kelmaydi — optimal kombinatsiya tekshiruvchi tomonidan aniqlanadi.\n\n**2-misol:**\nKiritma: w = [1,1,1], vol = [1,1,1], val = [10,20,30], W = 2, V = 2\nNatija: 50",
    starterCodeJs: 'function knapsackTwoConstraints(w, vol, val, capW, capV) {\n  // your code here\n}',
    starterCodePy: 'def knapsack_two_constraints(w, vol, val, cap_w, cap_v):\n    # your code here\n    pass',
    starterCodeCpp: 'int knapsackTwoConstraints(vector<int>& w, vector<int>& vol, vector<int>& val, int capW, int capV) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-018',
    title: "Aniq K ta buyum tanlash ryukzagi",
    difficulty: 'EXPERT',
    points: 109,
    tags: ['Dinamik dasturlash'],
    description: "n ta buyum berilgan (n ≤ 500), har birining og'irligi w[i] va qiymati val[i] bor. Ryukzakning og'irlik chegarasi W va aniq tanlanishi kerak bo'lgan buyumlar soni k berilgan. Aynan k ta buyum tanlab, ularning umumiy og'irligi W dan oshmagan holda qiymatlar yig'indisini maksimal qiluvchi kombinatsiyani toping (agar bunday kombinatsiya mavjud bo'lmasa, -1 qaytaring). Yechim uch o'lchamli dinamik dasturlash dp[i][cnt][w] yordamida O(n * k * W) murakkablikda qurilishi kerak.\n\n**1-misol:**\nKiritma: w = [1,2,3,4], val = [10,20,30,40], W = 6, k = 2\nNatija: 70\nIzoh: 3 va 4-buyumlar (og'irlik 3+4=7) mos kelmaydi; 2 va 4-buyumlar (og'irlik 6, qiymat 60) yoki boshqa kombinatsiyalar orasidan eng yaxshisi 70 ga teng bo'lishi mumkin.\n\n**2-misol:**\nKiritma: w = [5,5,5], val = [1,2,3], W = 4, k = 1\nNatija: -1",
    starterCodeJs: 'function knapsackExactlyKItems(w, val, capacity, k) {\n  // your code here\n}',
    starterCodePy: 'def knapsack_exactly_k_items(w, val, capacity, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int knapsackExactlyKItems(vector<int>& w, vector<int>& val, int capacity, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-019',
    title: "Kichik to'plamlar yig'indisi (SOS DP)",
    difficulty: 'EXPERT',
    points: 146,
    tags: ['Dinamik dasturlash'],
    description: "n (n ≤ 20) va uzunligi 2^n bo'lgan f massivi berilgan, bunda f[mask] — mask holatiga mos qiymat. Har bir mask uchun g[mask] = summasi f[submask] bo'yicha, bu yerda submask — mask ning barcha qism to'plamlari (submask AND mask == submask) ni hisoblang. n katta bo'lgani uchun har bir mask uchun barcha qism to'plamlarni sanab chiqish O(3^n) yoki undan yomonroq bo'ladi — \"Sum over Subsets\" (SOS) dinamik dasturlash texnikasi yordamida O(n * 2^n) murakkablikka erishish kerak. g massivini qaytaring.\n\n**1-misol:**\nKiritma: n = 2, f = [1,2,3,4]\nNatija: [1,3,4,10]\nIzoh: g[3] = f[0]+f[1]+f[2]+f[3] = 1+2+3+4=10, chunki 00,01,10,11 barchasi 11 ning qism to'plami.\n\n**2-misol:**\nKiritma: n = 1, f = [5,7]\nNatija: [5,12]",
    starterCodeJs: 'function sumOverSubsets(n, f) {\n  // your code here\n}',
    starterCodePy: 'def sum_over_subsets(n, f):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> sumOverSubsets(int n, vector<long long>& f) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-020',
    title: "Mos texnologiyalar sonini hisoblash",
    difficulty: 'EXPERT',
    points: 114,
    tags: ['Dinamik dasturlash'],
    description: "m ta mahsulot berilgan (m ≤ 10^5), har bir mahsulot n ≤ 20 ta texnologik xususiyatga ega bo'lib, bu bitmask (0 dan 2^n-1 gacha) ko'rinishida kodlangan. Har bir mahsulot uchun, undagi xususiyatlar to'plami boshqa mahsulotning xususiyatlar to'plamini o'z ichiga oladigan (ya'ni boshqa mahsulot uning \"qism to'plami\" bo'ladigan) mahsulotlar sonini hisoblang. Yechim avval har bir bitmask qiymati necha marta uchraganini sanab, so'ngra \"Sum over Subsets\" superset yig'indisi texnikasi yordamida O(n * 2^n + m) murakkablikda topilishi kerak.\n\n**1-misol:**\nKiritma: n = 2, masks = [1,3,3,0]\nNatija: [3,2,2,4]\nIzoh: 0-mahsulot (mask=1) uchun mos keluvchilar: o'zi va ikkita mask=3 bo'lgan mahsulotlar — jami 3 ta.\n\n**2-misol:**\nKiritma: n = 3, masks = [5,5,7]\nNatija: [2,2,3]",
    starterCodeJs: 'function countSupersetCompatible(n, masks) {\n  // your code here\n}',
    starterCodePy: 'def count_superset_compatible(n, masks):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countSupersetCompatible(int n, vector<int>& masks) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-021',
    title: "Matritsadagi eng uzun o'suvchi yo'l",
    difficulty: 'EXPERT',
    points: 131,
    tags: ['Dinamik dasturlash'],
    description: "n x m o'lchamli butun sonli matritsa berilgan (1 ≤ n, m ≤ 1000). Har bir katakchadan to'rtta yo'nalishda (yuqori, past, chap, o'ng) qo'shni katakchaga, faqat qiymati qat'iy katta bo'lsa, o'tish mumkin. Matritsadagi eng uzun o'suvchi yo'lning uzunligini (yo'ldagi katakchalar soni) toping. n va m 1000 gacha yetishi mumkinligi sababli, har bir katakcha uchun natijani memoizatsiya qilib, umumiy murakkablikni O(n * m) ga tushiruvchi DFS yechimi talab qilinadi.\n\n**1-misol:**\nKiritma: matrix = [[9,9,4],[6,6,8],[2,1,1]]\nNatija: 4\nIzoh: Eng uzun o'suvchi yo'l 1 -> 2 -> 6 -> 9.\n\n**2-misol:**\nKiritma: matrix = [[3,4,5],[3,2,6],[2,2,1]]\nNatija: 4",
    starterCodeJs: 'function longestIncreasingPath(matrix) {\n  // your code here\n}',
    starterCodePy: 'def longest_increasing_path(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestIncreasingPath(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-022',
    title: "Muzlik ustida eng uzun sirpanish yo'llari soni",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Dinamik dasturlash'],
    description: "n x m o'lchamli balandliklar matritsasi berilgan (1 ≤ n, m ≤ 1000). Sirpanuvchi to'rtta yo'nalishda qo'shni katakchaga faqat uning balandligi qat'iy kattaroq bo'lgan holatda o'tishi mumkin (ya'ni yo'l qat'iy o'suvchi bo'lishi kerak). Eng uzun bunday yo'lning uzunligini va shu maksimal uzunlikka ega bo'lgan yo'llarning umumiy sonini (10^9+7 modul bo'yicha, boshlanish nuqtasidan qat'i nazar barcha mumkin bo'lgan yo'llar hisoblanadi) toping. Yechim memoizatsiyalangan DFS asosida har bir katakcha uchun (maksimal uzunlik, shu uzunlikdagi yo'llar soni) juftligini hisoblab, O(n * m) murakkablikda qurilishi kerak.\n\n**1-misol:**\nKiritma: matrix = [[1,2],[1,3]]\nNatija: length = 3, count = 2\nIzoh: (0,0)->(0,1)->(1,1) va (1,0)->(0,0)->(0,1) kabi... aniq yo'llar tekshiruvchi tomonidan hisoblanadi, uzunligi 3 bo'lgan yo'llar soni 2 ta.\n\n**2-misol:**\nKiritma: matrix = [[1,1],[1,1]]\nNatija: length = 1, count = 4",
    starterCodeJs: 'function longestIncreasingPathCount(matrix) {\n  // your code here\n}',
    starterCodePy: 'def longest_increasing_path_count(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<int,long long> longestIncreasingPathCount(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-023',
    title: "Sonni turli qo'shiluvchilarga ajratish usullari",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Dinamik dasturlash'],
    description: "Butun son n (1 ≤ n ≤ 10^5) berilgan. n sonini o'zaro farqli (barchasi turlicha) musbat butun sonlarning yig'indisi sifatida ifodalashning nechta usuli borligini toping (tartib muhim emas, {1,4} va {4,1} bir xil hisoblanadi). Natijani 10^9+7 modul bo'yicha qaytaring. Yechim 0/1 ryukzak uslubidagi dinamik dasturlash dp[i][s] — birinchi i ta turli son ichidan yig'indisi s bo'lgan usullar soni ko'rinishida, lekin faqat sqrt(2n) ta son n dan katta bo'lmagan yig'indi hosil qila olishini hisobga olib, umumiy murakkablikni O(n * sqrt(n)) ga tushirish orqali qurilishi kerak.\n\n**1-misol:**\nKiritma: n = 6\nNatija: 4\nIzoh: 6, 5+1, 4+2, 3+2+1 — jami 4 ta usul.\n\n**2-misol:**\nKiritma: n = 10\nNatija: 10",
    starterCodeJs: 'function countDistinctPartitions(n) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_partitions(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDistinctPartitions(int n) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-024',
    title: "Cheklangan qismlarga bo'lish usullari",
    difficulty: 'EXPERT',
    points: 126,
    tags: ['Dinamik dasturlash'],
    description: "Uchta butun son n, k va m berilgan (1 ≤ n, k, m ≤ 1000). n sonini kamida 1, ko'pi bilan k ta musbat qo'shiluvchiga (tartib muhim emas, kamayish tartibida yozilgan deb hisoblanadi) ajratish kerak, bunda har bir qo'shiluvchi qiymati m dan oshmasligi kerak. Bunday ajratishlarning umumiy sonini 10^9+7 modul bo'yicha toping. Yechim ikki o'lchamli dinamik dasturlash dp[i][j] — i sonini, eng katta qismi j dan oshmagan holda ajratish usullari soni (yoki mos rekurrent formula) yordamida O(n * k * m) yoki yaxshiroq murakkablikda qurilishi kerak.\n\n**1-misol:**\nKiritma: n = 5, k = 2, m = 4\nNatija: 3\nIzoh: 5 = 4+1 = 3+2 = 5 (bitta qism, m=4 dan oshmasa ham 5 o'zi m dan katta bo'lgani uchun mos kelmaydi) — mos ajratishlar soni tekshiruvchi tomonidan aniqlanadi.\n\n**2-misol:**\nKiritma: n = 4, k = 4, m = 4\nNatija: 5",
    starterCodeJs: 'function countBoundedPartitions(n, k, m) {\n  // your code here\n}',
    starterCodePy: 'def count_bounded_partitions(n, k, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countBoundedPartitions(int n, int k, int m) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-025',
    title: "Cheklangan tangalar bilan pul almashtirish usullari",
    difficulty: 'EXPERT',
    points: 137,
    tags: ['Dinamik dasturlash'],
    description: "n xil tanga nominali berilgan (n ≤ 100), har bir nominal coin[i] va uning mavjud soni cnt[i] (cnt[i] ≤ 10^5) bilan cheklangan. S summasini (S ≤ 10^5) shu tangalar yordamida to'lashning nechta usuli borligini toping (bir xil nominaldagi tangalar farqlanmaydi, faqat miqdorlari hisoblanadi). Natijani 10^9+7 modul bo'yicha qaytaring. Naiv bounded knapsack O(n * S * max(cnt)) juda sekin bo'lgani uchun, ikkilik (binary) dekompozitsiya yoki monotonik navbat orqali optimallashtirilgan O(n * S log(cnt)) yoki O(n * S) murakkablikdagi yechim kutiladi.\n\n**1-misol:**\nKiritma: coin = [1,2,5], cnt = [2,2,1], S = 5\nNatija: 3\nIzoh: 5=5, 5=2+2+1, 5=1+2+2 (tartib muhim emas, shuning uchun oxirgi ikkisi bitta usul) — mos usullar soni tekshiruvchi tomonidan aniqlanadi.\n\n**2-misol:**\nKiritma: coin = [1,3], cnt = [3,1], S = 4\nNatija: 2",
    starterCodeJs: 'function countBoundedCoinWays(coin, cnt, s) {\n  // your code here\n}',
    starterCodePy: 'def count_bounded_coin_ways(coin, cnt, s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countBoundedCoinWays(vector<int>& coin, vector<int>& cnt, int s) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-026',
    title: "Kuchli bog'langan komponentalarni topish",
    difficulty: 'EXPERT',
    points: 121,
    tags: ['Grafiklar'],
    description: "n tugunli va m qirrali yo'naltirilgan graf berilgan (n, m ≤ 2*10^5), qirralar edges ro'yxatida (u, v) juftliklari sifatida berilgan. Grafdagi kuchli bog'langan komponentalar (SCC) sonini toping — ikkita tugun bir komponentaga tegishli hisoblanadi, agar ulardan biridan ikkinchisiga va aksincha yo'l mavjud bo'lsa. n va m yuqori bo'lgani sababli Tarjan yoki Kosaraju algoritmi yordamida O(n + m) murakkablikda yechim talab qilinadi.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[2,3],[3,4]]\nNatija: 3\nIzoh: {0,1,2} bitta SCC, {3} va {4} alohida SCC lar.\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,0],[2,3],[3,2]]\nNatija: 2",
    starterCodeJs: 'function countSCC(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def count_scc(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int countSCC(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-027',
    title: "Grafni to'liq bog'langan qilish uchun minimal qirralar",
    difficulty: 'EXPERT',
    points: 137,
    tags: ['Grafiklar'],
    description: "n tugunli va m qirrali yo'naltirilgan graf berilgan (n, m ≤ 2*10^5). Grafga qo'shimcha yo'naltirilgan qirralar qo'shib, uni to'liq kuchli bog'langan (ixtiyoriy ikkita tugun orasida ikkala yo'nalishda ham yo'l mavjud bo'ladigan) holatga keltirish uchun zarur bo'lgan minimal qirralar sonini toping. Yechim avval SCC larni topib (Tarjan/Kosaraju), so'ngra kondensatsiya grafida manba (kirish darajasi 0) va yutuq (chiqish darajasi 0) komponentalar sonini hisoblab, javobni max(manbalar soni, yutuqlar soni) sifatida aniqlashni talab qiladi (agar butun graf allaqachon bitta SCC bo'lsa, javob 0). Umumiy murakkablik O(n + m).\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[3,4]]\nNatija: 2\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]]\nNatija: 0",
    starterCodeJs: 'function minEdgesToStronglyConnect(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def min_edges_to_strongly_connect(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int minEdgesToStronglyConnect(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-028',
    title: "Loyihalarni bosqichlarga ajratish",
    difficulty: 'EXPERT',
    points: 109,
    tags: ['Grafiklar'],
    description: "n ta loyiha va ular orasidagi m ta bog'liqlik berilgan (n, m ≤ 2*10^5), (u, v) bog'liqligi u loyihasi v dan oldin (yoki bir vaqtda, agar aylanma bog'liqlik bo'lsa) bajarilishi kerakligini bildiradi. Aylanma bog'liqliklar mavjud bo'lgan loyihalar guruhi bitta bosqichda birgalikda bajarilishi mumkin. Barcha loyihalarni bajarish uchun zarur bo'lgan minimal ketma-ket bosqichlar sonini toping. Yechim avval kuchli bog'langan komponentalarni (SCC) topib, so'ngra hosil bo'lgan kondensatsiya (DAG) grafida eng uzun yo'lning uzunligini (tugunlar sonida) hisoblashni talab qiladi, umumiy murakkablik O(n + m).\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,0],[1,2],[2,3]]\nNatija: 3\nIzoh: {0,1} bitta bosqich, {2} ikkinchi, {3} uchinchi bosqich.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]]\nNatija: 1",
    starterCodeJs: 'function minPhasesToCompleteProjects(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def min_phases_to_complete_projects(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int minPhasesToCompleteProjects(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-029',
    title: "2-SAT: mantiqiy qondirish masalasi",
    difficulty: 'EXPERT',
    points: 146,
    tags: ['Grafiklar'],
    description: "n ta mantiqiy o'zgaruvchi (x1..xn, n ≤ 2*10^5) va m ta ikki hadli dizyunksiya ko'rinishidagi shart berilgan (masalan, (xi yoki NOT xj)), jami m ≤ 2*10^5. Barcha shartlarni bir vaqtda qanoatlantiruvchi o'zgaruvchilar qiymatlarini (true/false) topish yoki bunday tayinlash mavjud emasligini aniqlash kerak. Yechim implikatsiya grafini qurib (har bir shart ikkita implikatsiya qirrasiga aylantiriladi) va undagi kuchli bog'langan komponentalarni topib, har bir o'zgaruvchi uchun xi va NOT xi bir xil SCC da emasligini tekshirish orqali O(n + m) vaqtda topilishi kerak.\n\n**1-misol:**\nKiritma: n = 2, clauses = [[1,2],[-1,-2]]\nNatija: qondiriladi, masalan x1=true, x2=false\n\n**2-misol:**\nKiritma: n = 1, clauses = [[1,1],[-1,-1]]\nNatija: qondirib bo'lmaydi",
    starterCodeJs: 'function solveTwoSat(n, clauses) {\n  // your code here\n}',
    starterCodePy: 'def solve_two_sat(n, clauses):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> solveTwoSat(int n, vector<vector<int>>& clauses) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-030',
    title: "Xodimlar smenasini rejalashtirish (2-SAT)",
    difficulty: 'EXPERT',
    points: 114,
    tags: ['Grafiklar'],
    description: "n ta xodim bor (n ≤ 10^5), har biriga aynan bitta smena — ertalabki yoki kechki — tayinlanishi kerak. m ta juftlik cheklovi berilgan (m ≤ 10^5), har biri quyidagi ko'rinishlardan biri bo'ladi: \"agar A ertalabki smenada bo'lsa, B kechqurun bo'lishi shart\", \"A va B bir xil smenada bo'lishi mumkin emas\" yoki \"A va B bir xil smenada bo'lishi shart\". Barcha cheklovlarni qanoatlantiradigan smenalar tayinlanishini toping yoki bu mumkin emasligini aniqlang. Yechim har bir cheklovni ikkita mantiqiy implikatsiyaga aylantirib, 2-SAT modeliga tushirish va SCC orqali O(n + m) vaqtda yechish talab etiladi.\n\n**1-misol:**\nKiritma: n = 3, constraints = [[\"implies\",0,\"morning\",1,\"evening\"],[\"different\",1,2]]\nNatija: mumkin, masalan 0=ertalabki, 1=kechki, 2=ertalabki\n\n**2-misol:**\nKiritma: n = 2, constraints = [[\"same\",0,1],[\"different\",0,1]]\nNatija: mumkin emas",
    starterCodeJs: 'function scheduleShiftsTwoSat(n, constraints) {\n  // your code here\n}',
    starterCodePy: 'def schedule_shifts_two_sat(n, constraints):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> scheduleShiftsTwoSat(int n, vector<vector<string>>& constraints) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-031',
    title: "O'zaro istisno cheklovlari bilan tanlov (2-SAT)",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Grafiklar'],
    description: "n ta buyum bor (n ≤ 10^5), har biri tanlanishi yoki tanlanmasligi mumkin. m ta cheklov berilgan (m ≤ 10^5), ular quyidagi turlarda bo'lishi mumkin: \"{i,j} dan ko'pi bilan bittasi tanlanishi mumkin\", \"{i,j} dan kamida bittasi tanlanishi shart\" yoki \"i tanlansa, j ham tanlanishi shart\". Barcha cheklovlarni qanoatlantiradigan tanlov mavjudligini aniqlang va agar mavjud bo'lsa, mos keluvchi tanlovni qaytaring. Yechim har bir cheklovni implikatsiya qirralariga aylantirib, 2-SAT modelida SCC orqali O(n + m) vaqtda topilishi kerak.\n\n**1-misol:**\nKiritma: n = 3, constraints = [[\"atmostone\",0,1],[\"atleastone\",1,2]]\nNatija: mumkin, masalan {1} yoki {0,2} tanlanishi mumkin\n\n**2-misol:**\nKiritma: n = 2, constraints = [[\"atmostone\",0,1],[\"atleastone\",0,1],[\"implies\",0,1],[\"implies\",1,0]]\nNatija: mumkin emas",
    starterCodeJs: 'function feasibleSelectionTwoSat(n, constraints) {\n  // your code here\n}',
    starterCodePy: 'def feasible_selection_two_sat(n, constraints):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> feasibleSelectionTwoSat(int n, vector<vector<string>>& constraints) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-032',
    title: "Ishchilarni vazifalarga optimal biriktirish",
    difficulty: 'EXPERT',
    points: 131,
    tags: ['Grafiklar'],
    description: "n ta ishchi va m ta vazifa berilgan, ular orasidagi mosliklar ikki tomonlama (bipartit) graf ko'rinishida edges ro'yxatida beriladi (jami qirralar soni E ≤ 2*10^5). Har bir ishchi ko'pi bilan bitta vazifaga va har bir vazifa ko'pi bilan bitta ishchiga biriktirilishi sharti bilan, biriktirilgan juftliklarning maksimal sonini toping. n, m katta bo'lishi mumkinligi sababli oddiy Kun algoritmi (Hungarian/Kuhn) yetarli bo'lmasligi mumkin — Hopcroft-Karp algoritmi yordamida O(E * sqrt(V)) murakkablikda yechim kutiladi.\n\n**1-misol:**\nKiritma: n = 3, m = 3, edges = [[0,0],[0,1],[1,1],[2,2]]\nNatija: 3\n\n**2-misol:**\nKiritma: n = 2, m = 2, edges = [[0,0],[1,0]]\nNatija: 1",
    starterCodeJs: 'function maxBipartiteMatching(n, m, edges) {\n  // your code here\n}',
    starterCodePy: 'def max_bipartite_matching(n, m, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxBipartiteMatching(int n, int m, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-033',
    title: "Minimal cho'qqilar qoplami (Kyonig teoremasi)",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Grafiklar'],
    description: "n ta chap tomon va m ta o'ng tomon tugunlaridan iborat ikki tomonlama graf berilgan, qirralar edges ro'yxatida beriladi (E ≤ 2*10^5). Barcha qirralarni \"qoplaydigan\" (har bir qirraning kamida bitta uchi tanlangan bo'lishi kerak) minimal sondagi tugunlar to'plamini toping va shu minimal sonni qaytaring. Yechim avval maksimal moslashtirishni (Hopcroft-Karp orqali) topib, so'ngra Kyonig teoremasidan foydalanib minimal cho'qqilar qoplamini qurishni talab qiladi, umumiy murakkablik O(E * sqrt(V)).\n\n**1-misol:**\nKiritma: n = 2, m = 2, edges = [[0,0],[0,1],[1,0]]\nNatija: 2\n\n**2-misol:**\nKiritma: n = 3, m = 3, edges = [[0,0],[1,1],[2,2]]\nNatija: 3",
    starterCodeJs: 'function minVertexCoverBipartite(n, m, edges) {\n  // your code here\n}',
    starterCodePy: 'def min_vertex_cover_bipartite(n, m, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int minVertexCoverBipartite(int n, int m, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-034',
    title: "Ko'p vazifali ishchilarni sig'imli taqsimlash",
    difficulty: 'EXPERT',
    points: 113,
    tags: ['Grafiklar'],
    description: "n ta ishchi va m ta vazifa berilgan, ular orasidagi moslik qirralari edges ro'yxatida berilgan (E ≤ 2*10^5). Har bir ishchi i ko'pi bilan capW[i] ta vazifani bajara oladi va har bir vazifa j uchun aynan capT[j] ta ishchi zarur. Barcha cheklovlarni hisobga olgan holda biriktirilishi mumkin bo'lgan (ishchi, vazifa) juftliklarining maksimal umumiy sonini toping. Yechim masalani manba-ishchilar-vazifalar-yutuq ko'rinishidagi tarmoqqa aylantirib, mos sig'imlar bilan maksimal oqim (max flow) sifatida O(E * maxFlowValue) yoki Dinitz algoritmi bilan yaxshiroq murakkablikda yechishni talab qiladi.\n\n**1-misol:**\nKiritma: n = 2, m = 2, edges = [[0,0],[0,1],[1,0]], capW = [2,1], capT = [1,2]\nNatija: 3\n\n**2-misol:**\nKiritma: n = 1, m = 1, edges = [[0,0]], capW = [5], capT = [3]\nNatija: 3",
    starterCodeJs: 'function maxCapacitatedAssignment(n, m, edges, capW, capT) {\n  // your code here\n}',
    starterCodePy: 'def max_capacitated_assignment(n, m, edges, cap_w, cap_t):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxCapacitatedAssignment(int n, int m, vector<vector<int>>& edges, vector<int>& capW, vector<int>& capT) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-035',
    title: "Tarmoqdagi maksimal oqim",
    difficulty: 'EXPERT',
    points: 128,
    tags: ['Grafiklar'],
    description: "n tugunli yo'naltirilgan tarmoq berilgan (n ≤ 1000), m ta qirra (m ≤ 5000) har biri (u, v, capacity) ko'rinishida berilgan bo'lib, capacity — o'sha qirradan o'tishi mumkin bo'lgan maksimal oqim miqdori. s manba va t yutuq tugunlari berilgan. s dan t gacha o'tkazilishi mumkin bo'lgan maksimal umumiy oqimni toping. Yechim Edmonds-Karp yoki Dinitz algoritmi yordamida O(V*E^2) yoki O(V^2*E) murakkablikda qurilishi kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,3],[0,2,2],[1,2,1],[1,3,2],[2,3,3]], s = 0, t = 3\nNatija: 5\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1,5],[1,2,3]], s = 0, t = 2\nNatija: 3",
    starterCodeJs: 'function maxFlow(n, edges, s, t) {\n  // your code here\n}',
    starterCodePy: 'def max_flow(n, edges, s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxFlow(int n, vector<vector<long long>>& edges, int s, int t) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-036',
    title: "Tarmoqni uzish uchun minimal qirralar soni",
    difficulty: 'EXPERT',
    points: 143,
    tags: ['Grafiklar'],
    description: "n tugunli yo'naltirilgan graf berilgan (n ≤ 1000, m ≤ 2000 qirra), har bir qirra sig'imi 1 ga teng deb hisoblanadi. s manba va t yutuq tugunlari berilgan. s dan t ga boradigan barcha yo'llarni uzish uchun olib tashlanishi kerak bo'lgan minimal qirralar sonini toping (bu — min-cut, max-flow min-cut teoremasiga ko'ra maksimal oqim qiymatiga teng). Qo'shimcha ravishda, olib tashlanadigan qirralar ro'yxatini ham qaytaring. Yechim unit-capacity tarmoqda maksimal oqim (Dinitz yoki BFS asosidagi Edmonds-Karp) orqali O(E * sqrt(E)) yoki O(V*E) murakkablikda topilishi kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[1,3],[2,3]], s = 0, t = 3\nNatija: 2\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[0,2]], s = 0, t = 2\nNatija: 1",
    starterCodeJs: 'function minEdgeCut(n, edges, s, t) {\n  // your code here\n}',
    starterCodePy: 'def min_edge_cut(n, edges, s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'int minEdgeCut(int n, vector<vector<int>>& edges, int s, int t) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-037',
    title: "O'zaro qirrasiz yo'llar soni (Menger teoremasi)",
    difficulty: 'EXPERT',
    points: 107,
    tags: ['Grafiklar'],
    description: "n tugunli yo'naltirilgan graf berilgan (n ≤ 1000, m ≤ 2000 qirra), s manba va t yutuq tugunlari bilan. s dan t gacha boradigan, hech qanday umumiy qirraga ega bo'lmagan (edge-disjoint) yo'llarning maksimal sonini toping. Menger teoremasiga ko'ra, bu qiymat unit-capacity tarmoqdagi maksimal oqimga teng. Yechim maksimal oqim algoritmi (Dinitz yoki Edmonds-Karp) yordamida O(V*E) murakkablikda topilishi va, agar so'ralsa, aniq yo'llarning o'zi ham qayta tiklanishi kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[1,3],[2,3],[0,3]]\nNatija: 3\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: 1",
    starterCodeJs: 'function edgeDisjointPaths(n, edges, s, t) {\n  // your code here\n}',
    starterCodePy: 'def edge_disjoint_paths(n, edges, s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'int edgeDisjointPaths(int n, vector<vector<int>>& edges, int s, int t) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-038',
    title: "Grafda ajratuvchi cho'qqilarni topish",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Grafiklar'],
    description: "n tugunli va m qirrali yo'naltirilmagan graf berilgan (n, m ≤ 2*10^5). Ajratuvchi cho'qqi (articulation point) — shunday tugunki, uni (barcha unga tegishli qirralar bilan birga) olib tashlash grafdagi bog'langan komponentalar sonini oshiradi. Grafdagi barcha ajratuvchi cho'qqilarni toping. Yechim DFS asosidagi low-link algoritmi (Tarjan usuli) yordamida O(n + m) murakkablikda qurilishi kerak, ildiz tugun uchun alohida shart (ikkita yoki undan ko'p DFS bolasi borligi) hisobga olinishi zarur.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]\nNatija: [1,3]\nIzoh: 1 va 3 tugunlar olib tashlansa graf bo'linib ketadi.\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]]\nNatija: [1,2]",
    starterCodeJs: 'function findArticulationPoints(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def find_articulation_points(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findArticulationPoints(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-039',
    title: "Grafda ko'prik qirralarni topish",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Grafiklar'],
    description: "n tugunli va m qirrali yo'naltirilmagan graf berilgan (n, m ≤ 2*10^5). Ko'prik (bridge) — shunday qirraki, uni olib tashlash grafdagi bog'langan komponentalar sonini oshiradi (ya'ni shu qirra orqaligina bog'langan ikkita qism mavjud). Grafdagi barcha ko'prik qirralarni toping. Yechim DFS asosidagi low-link algoritmi yordamida O(n + m) murakkablikda qurilishi va parallel (multigraf) qirralarni to'g'ri hisobga olishi kerak (ota-ona qirrasini takroriy id orqali chetlab o'tish).\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]\nNatija: [[1,3],[3,4]]\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3],[3,0]]\nNatija: []",
    starterCodeJs: 'function findBridges(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def find_bridges(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> findBridges(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-040',
    title: "Tarmoqdagi muhim ulanishlar va bloklar soni",
    difficulty: 'EXPERT',
    points: 116,
    tags: ['Grafiklar'],
    description: "n ta server va ular orasidagi m ta ikki tomonlama aloqa kanali (yo'naltirilmagan qirra) berilgan (n, m ≤ 2*10^5). Bitta kanal ishdan chiqishi tarmoqni ikki yoki undan ko'p qismga bo'lib yuborsa, u \"muhim ulanish\" (ko'prik) deb ataladi. Barcha muhim ulanishlarni toping, shuningdek tarmoqdagi ikki bog'langan komponentalar (biconnected components, ko'priklarsiz maksimal quyi graflar) sonini hisoblang. Yechim DFS asosidagi low-link algoritmi va qirralar stekidan foydalangan holda O(n + m) murakkablikda qurilishi kerak.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]\nNatija: critical = [[1,3],[3,4]], blocks = 3\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]]\nNatija: critical = [], blocks = 1",
    starterCodeJs: 'function criticalConnectionsAndBlocks(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def critical_connections_and_blocks(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<vector<vector<int>>,int> criticalConnectionsAndBlocks(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-041',
    title: "Daraxtda eng yaqin umumiy ajdod va masofa",
    difficulty: 'EXPERT',
    points: 124,
    tags: ['Grafiklar'],
    description: "n tugunli daraxt berilgan (n ≤ 2*10^5), ildiz 0-tugun deb belgilangan, qirralar edges ro'yxatida berilgan. q ta so'rov beriladi (q ≤ 2*10^5), har biri (u, v) juftligi bo'lib, u va v ning eng yaqin umumiy ajdodini (LCA) va ular orasidagi masofani (qirralar sonida) topish kerak. n va q katta bo'lgani sababli har bir so'rovni O(n) da javob berish yetarli emas — binary lifting (2^k ajdodlarni oldindan hisoblash) texnikasi yordamida O((n + q) log n) murakkablikda yechim talab qilinadi.\n\n**1-misol:**\nKiritma: n = 7, edges = [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]], queries = [[3,4],[3,6]]\nNatija: [[1,2],[0,4]]\nIzoh: LCA(3,4)=1, masofa=2; LCA(3,6)=0, masofa=4.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]], queries = [[0,2]]\nNatija: [[0,2]]",
    starterCodeJs: 'function lcaAndDistance(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def lca_and_distance(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<pair<int,int>> lcaAndDistance(int n, vector<vector<int>>& edges, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-042',
    title: "Tugundan k-qadam yuqoridagi ajdodni topish",
    difficulty: 'EXPERT',
    points: 148,
    tags: ['Grafiklar'],
    description: "n tugunli daraxt berilgan (n ≤ 2*10^5), ildiz 0-tugun, qirralar edges ro'yxatida berilgan. q ta so'rov beriladi (q ≤ 2*10^5), har biri (v, k) juftligi bo'lib, v tugunidan aynan k qadam yuqoridagi ajdodini topish kerak (agar bunday ajdod mavjud bo'lmasa, -1 qaytariladi). n va q katta bo'lgani sababli har bir so'rovni naiv usulda O(k) da javob berish yetarli emas — binary lifting texnikasi yordamida oldindan hisoblash O(n log n) va har bir so'rovga O(log n) sarflanadigan yechim talab qilinadi.\n\n**1-misol:**\nKiritma: n = 6, edges = [[0,1],[1,2],[2,3],[0,4],[4,5]], queries = [[3,2],[5,3]]\nNatija: [1,-1]\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]], queries = [[2,1],[2,2]]\nNatija: [1,0]",
    starterCodeJs: 'function kthAncestorQueries(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def kth_ancestor_queries(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> kthAncestorQueries(int n, vector<vector<int>>& edges, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-043',
    title: "Minimal xarajatli maksimal moslashtirish",
    difficulty: 'EXPERT',
    points: 116,
    tags: ['Grafiklar'],
    description: "n ta ishchi va n ta vazifa berilgan (n ≤ 200), cost[i][j] — i-ishchining j-vazifani bajarish narxi. Har bir ishchi aynan bitta vazifaga va har bir vazifa aynan bitta ishchiga biriktirilishi kerak (to'liq moslashtirish), bunda umumiy narx minimal bo'lishi kerak. Yechim masalani manba-ishchilar-vazifalar-yutuq tarmog'iga aylantirib, har bir qirraga mos xarajat qo'yib, minimal xarajatli maksimal oqim (MCMF, ketma-ket eng qisqa yo'llar usuli — SPFA/Bellman-Ford + augmentatsiya) yordamida O(n^3) atrofida murakkablikda yechishni talab qiladi.\n\n**1-misol:**\nKiritma: n = 3, cost = [[9,2,7],[6,4,3],[5,8,1]]\nNatija: 12\nIzoh: 0->1, 1->2, 2->0 biriktirilsa 2+3+5=10 emas, optimal biriktirish natijasida minimal narx 12 ga teng bo'ladi (aniq kombinatsiya tekshiruvchi tomonidan hisoblanadi).\n\n**2-misol:**\nKiritma: n = 2, cost = [[1,2],[2,1]]\nNatija: 2",
    starterCodeJs: 'function minCostAssignment(n, cost) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_assignment(n, cost):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCostAssignment(int n, vector<vector<long long>>& cost) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-044',
    title: "Yetkazib berish tarmog'ida minimal xarajatli ta'minot",
    difficulty: 'EXPERT',
    points: 132,
    tags: ['Grafiklar'],
    description: "n tugunli yo'naltirilgan tarmoq berilgan (n ≤ 1000, m ≤ 5000 qirra), har bir qirra (u, v, capacity, costPerUnit) ko'rinishida. Bir nechta manba tugunlari (har birining ta'minot miqdori bilan) va bir nechta ehtiyoj tugunlari (har birining talab miqdori bilan) berilgan. Barcha ehtiyojlarni to'liq qondirish uchun zarur bo'lgan minimal umumiy xarajatni toping (agar barcha talabni qondirish mumkin bo'lmasa, -1 qaytaring). Yechim super-manba va super-yutuq tugunlarini qo'shib, minimal xarajatli maksimal oqim (MCMF) algoritmi yordamida O(F * E log V) atrofida murakkablikda qurilishi kerak, bunda F — umumiy oqim qiymati.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,5,2],[0,2,3,4],[1,3,4,1],[2,3,3,2]], supplies = [[0,7]], demands = [[3,7]]\nNatija: 27\n\n**2-misol:**\nKiritma: n = 2, edges = [[0,1,3,5]], supplies = [[0,3]], demands = [[1,5]]\nNatija: -1",
    starterCodeJs: 'function minCostFlowSatisfyDemand(n, edges, supplies, demands) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_flow_satisfy_demand(n, edges, supplies, demands):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCostFlowSatisfyDemand(int n, vector<vector<long long>>& edges, vector<vector<long long>>& supplies, vector<vector<long long>>& demands) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-045',
    title: "Yo'naltirilgan grafda Eyler aylanasini qurish",
    difficulty: 'EXPERT',
    points: 143,
    tags: ['Grafiklar'],
    description: "n tugunli va m qirrali yo'naltirilgan graf berilgan (n, m ≤ 10^5). Grafda Eyler aylanasi (har bir qirradan aynan bir marta o'tuvchi va boshlang'ich tugunga qaytib keluvchi yopiq yo'l) mavjudligini aniqlang: bu uchun har bir tugunning kirish darajasi chiqish darajasiga teng bo'lishi va barcha qirralarga ega tugunlar bitta bog'langan komponentada joylashgan bo'lishi kerak. Agar mavjud bo'lsa, Hierholzer algoritmi yordamida O(n + m) murakkablikda aylananing o'zini (tugunlar ketma-ketligi sifatida) qurib bering.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]]\nNatija: [0,1,2,0]\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: mavjud emas",
    starterCodeJs: 'function eulerianCircuitDirected(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def eulerian_circuit_directed(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> eulerianCircuitDirected(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-046',
    title: "Yo'naltirilmagan multigrafda Eyler yo'lini qurish",
    difficulty: 'EXPERT',
    points: 118,
    tags: ['Grafiklar'],
    description: "n tugunli yo'naltirilmagan multigraf berilgan (n ≤ 10^5, m ≤ 10^5 qirra, ikkita tugun orasida bir nechta qirra bo'lishi mumkin, bu masalan shaharlar orasidagi ko'p yo'lli yo'llar tarmog'ini ifodalaydi). Grafda Eyler yo'li (har bir qirradan aynan bir marta o'tuvchi yo'l, boshlanish va tugash tugunlari bir xil bo'lishi shart emas) mavjudligini aniqlang: bu uchun toq darajali tugunlar soni 0 yoki 2 ta bo'lishi va barcha qirralarga ega tugunlar bitta bog'langan komponentada joylashgan bo'lishi kerak. Agar mavjud bo'lsa, Hierholzer algoritmi yordamida O(n + m) murakkablikda yo'lning o'zini qurib bering.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3],[3,1]]\nNatija: [0,1,3,2,1]\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[0,3]]\nNatija: mavjud emas",
    starterCodeJs: 'function eulerianPathUndirected(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def eulerian_path_undirected(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> eulerianPathUndirected(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-047',
    title: "Grafning xromatik sonini hisoblash",
    difficulty: 'EXPERT',
    points: 129,
    tags: ['Grafiklar'],
    description: "n tugunli (n ≤ 20) yo'naltirilmagan graf berilgan, har bir tugunning qo'shnilari bitmask ko'rinishida adj[i] massivida berilgan. Grafning xromatik sonini — grafni to'g'ri ranglash (qo'shni tugunlar har xil rangda bo'lishi) uchun zarur bo'lgan minimal ranglar sonini — toping. n kichik bo'lgani uchun avval barcha mustaqil to'plamlarni (independent set) bitmask sifatida aniqlab, so'ngra dp[mask] = mask tugunlarini to'liq qoplash uchun zarur minimal mustaqil to'plamlar soni ko'rinishidagi subset dinamik dasturlash orqali O(2^n * n) yoki O(3^n) murakkablikda yechim talab qilinadi.\n\n**1-misol:**\nKiritma: n = 3, adj = [6,5,3]\nNatija: 3\nIzoh: Graf to'liq uchburchak (har bir tugun qolgan ikkitasi bilan bog'langan), shuning uchun 3 ta rang kerak.\n\n**2-misol:**\nKiritma: n = 4, adj = [2,1,8,4]\nNatija: 2",
    starterCodeJs: 'function chromaticNumber(n, adj) {\n  // your code here\n}',
    starterCodePy: 'def chromatic_number(n, adj):\n    # your code here\n    pass',
    starterCodeCpp: 'int chromaticNumber(int n, vector<int>& adj) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-048',
    title: "Chastotalarni taqsimlash: k-ranglash masalasi",
    difficulty: 'EXPERT',
    points: 122,
    tags: ['Grafiklar'],
    description: "n ta uzatuvchi qurilma bor (n ≤ 20), ba'zilari bir-biriga xalaqit beradi (bu ziddiyat grafi sifatida har bir tugunning qo'shnilari bitmask ko'rinishida adj[i] massivida berilgan). k ta mavjud chastota (rang) berilgan. Har bir qurilmaga shunday chastota tayinlash mumkinmi, hech qanday ikkita ziddiyatli qurilma bir xil chastotani ishlatmasin? Yechim mustaqil to'plamlarni oldindan hisoblab, dp[mask] = mask tugunlarini qoplash uchun zarur minimal mustaqil to'plamlar sonini topib, uni k bilan solishtirish orqali (yoki dp[mask][cnt] bitta bosqichda k ta guruhga bo'linishini tekshirish orqali) O(2^n * n) yoki O(3^n) murakkablikda aniqlanishi kerak.\n\n**1-misol:**\nKiritma: n = 4, adj = [6,5,3,0], k = 2\nNatija: mumkin\n\n**2-misol:**\nKiritma: n = 3, adj = [6,5,3], k = 2\nNatija: mumkin emas",
    starterCodeJs: 'function isKColorable(n, adj, k) {\n  // your code here\n}',
    starterCodePy: 'def is_k_colorable(n, adj, k):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isKColorable(int n, vector<int>& adj, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-049',
    title: "Og'ir-yengil dekompozitsiya: yo'l bo'yicha yig'indi so'rovlari",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Grafiklar'],
    description: "n tugunli daraxt berilgan (n ≤ 10^5), har bir tugunda boshlang'ich qiymat val[i] bor. q ta so'rov beriladi (q ≤ 10^5), ikki turi mavjud: \"update(v, x)\" — v tugunining qiymatini x ga o'zgartirish, va \"query(u, v)\" — u va v tugunlari orasidagi yo'ldagi barcha tugun qiymatlarining yig'indisini topish. n va q katta bo'lgani sababli har bir so'rovni O(n) da bajarish yetarli emas — og'ir-yengil dekompozitsiya (Heavy-Light Decomposition) va segment daraxti kombinatsiyasi yordamida har bir so'rovni O(log^2 n) da bajaruvchi yechim talab qilinadi.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[0,2],[1,3],[1,4]], val = [1,2,3,4,5], queries = [[\"query\",3,4],[\"update\",0,10],[\"query\",3,2]]\nNatija: [11,19]\nIzoh: Birinchi so'rovda 3-1-4 yo'li 4+2+5=11; ikkinchi so'rovda 0 ning qiymati 10 ga o'zgargach 3-1-0-2 yo'li 4+2+10+3=19.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]], val = [5,5,5], queries = [[\"query\",0,2]]\nNatija: [15]",
    starterCodeJs: 'function hldPathSumQueries(n, edges, val, queries) {\n  // your code here\n}',
    starterCodePy: 'def hld_path_sum_queries(n, edges, val, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> hldPathSumQueries(int n, vector<vector<int>>& edges, vector<long long>& val, vector<vector<string>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-c-050',
    title: "Og'ir-yengil dekompozitsiya: yo'ldagi maksimal qiymat",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Grafiklar'],
    description: "n tugunli daraxt berilgan (n ≤ 10^5), har bir qirraning og'irligi w[i] bor. q ta so'rov beriladi (q ≤ 10^5), ikki turi mavjud: \"update(edgeIdx, x)\" — berilgan qirraning og'irligini x ga o'zgartirish, va \"query(u, v)\" — u va v tugunlari orasidagi yo'ldagi qirralarning maksimal og'irligini topish. n va q katta bo'lgani sababli har bir so'rovni O(n) da bajarish yetarli emas — og'ir-yengil dekompozitsiya (Heavy-Light Decomposition) va maksimal so'rovlarga mo'ljallangan segment daraxti kombinatsiyasi yordamida har bir so'rovni O(log^2 n) da bajaruvchi yechim talab qilinadi (qirra og'irligi bolaning \"kirish\" segment daraxti hujayrasida saqlanadi).\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[0,2],[1,3],[1,4]], w = [3,7,2,9], queries = [[\"query\",3,4],[\"update\",2,1],[\"query\",3,2]]\nNatija: [9,3]\nIzoh: Birinchi so'rovda 3-1-4 yo'lidagi qirralar og'irligi 2 va 9, maksimal 9; ikkinchi qirra (0-2) og'irligi 1 ga o'zgargach 3-1-0-2 yo'lidagi maksimal 3 bo'ladi.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]], w = [4,6], queries = [[\"query\",0,2]]\nNatija: [6]",
    starterCodeJs: 'function hldPathMaxQueries(n, edges, w, queries) {\n  // your code here\n}',
    starterCodePy: 'def hld_path_max_queries(n, edges, w, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> hldPathMaxQueries(int n, vector<vector<int>>& edges, vector<long long>& w, vector<vector<string>>& queries) {\n    // your code here\n}',
  },
];
