export const problems = [
  {
    key: 'expert-d-001',
    title: "Og'ir-Yengil Dekompozitsiya bilan Yo'l Yig'indisi",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Daraxtlar'],
    description: "n tugunli daraxt berilgan (ildizi 1-tugun), har bir tugunda butun son qiymati bor. Ikki turdagi so'rovni qo'llab-quvvatlash kerak: berilgan tugunning qiymatini yangilash va ikki tugun orasidagi yo'ldagi barcha qiymatlar yig'indisini hisoblash. n va so'rovlar soni 2×10^5 gacha bo'lishi mumkin, shuning uchun yechim og'ir-yengil dekompozitsiya (heavy-light decomposition) va segment daraxt yordamida har bir so'rovni O(log^2 n) vaqtda bajarishi kerak.\n\n**1-misol:**\nKiritma: edges = [[1,2],[1,3],[2,4],[2,5]], values = [10,20,30,40,50], so'rov = SUM(4,5)\nNatija: 110\nIzoh: 4 va 5 orasidagi yo'l 4-2-5, qiymatlar yig'indisi 40+20+50=110.",
    starterCodeJs: 'function pathSum(n, edges, values, queries) {\n  // your code here\n}',
    starterCodePy: 'def path_sum(n, edges, values, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> pathSum(int n, vector<pair<int,int>>& edges, vector<int>& values, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-002',
    title: 'Persistent Segment Daraxt: Tarixiy K-chi Element',
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Daraxtlar'],
    description: "Massiv ustida ketma-ket yangilanish operatsiyalari bajariladi, har bir operatsiya bitta element qiymatini o'zgartirib yangi versiya yaratadi. Har bir so'rov muayyan versiya raqami va [l,r] oralig'i uchun k-chi eng kichik elementni so'raydi. n, versiyalar va so'rovlar soni 2×10^5 gacha. Har bir yangilanish O(log n) qo'shimcha tugun yaratishi va har bir so'rov O(log n) vaqtda javob berishi kerak — persistent (doimiy) segment daraxt tuzilmasi shart.\n\n**1-misol:**\nKiritma: boshlang'ich massiv = [3,1,2], operatsiyalar = [UPDATE(1, 5)], so'rov = (versiya=1, l=1, r=3, k=2)\nNatija: 3\nIzoh: 1-versiyada massiv [5,1,2], saralangani [1,2,5], 2-chi kichik element 2.",
    starterCodeJs: 'function kthInVersion(operations, queries) {\n  // your code here\n}',
    starterCodePy: 'def kth_in_version(operations, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> kthInVersion(vector<vector<int>>& operations, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-003',
    title: 'Ildizli Daraxtlarning Izomorfligini Tekshirish',
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Daraxtlar'],
    description: "Ikkita ildizli daraxt berilgan (har biri n tagacha tugunga ega). Ikkala daraxtning tuzilishi bir xil ekanligini — ya'ni bitta daraxtdagi tugunlarni har bir darajada farzandlar orasida qayta tartiblash orqali ikkinchisiga aylantirish mumkinligini — aniqlang. AHU algoritmi asosida har bir tugun uchun kanonik (canonical) satr yoki hash tuzing va ikkala ildizning kanonik ko'rinishini solishtiring. n 10^5 gacha bo'lishi mumkin, yechim O(n log n) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: daraxt1: edges=[[1,2],[1,3]], root1=1; daraxt2: edges=[[1,2],[1,3]], root2=1\nNatija: true\nIzoh: Ikkala daraxtda ham ildizning ikkita bargi bor, tuzilishlari izomorf.",
    starterCodeJs: 'function areIsomorphic(n1, edges1, root1, n2, edges2, root2) {\n  // your code here\n}',
    starterCodePy: 'def are_isomorphic(n1, edges1, root1, n2, edges2, root2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool areIsomorphic(int n1, vector<pair<int,int>>& edges1, int root1, int n2, vector<pair<int,int>>& edges2, int root2) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-004',
    title: "Markaziy Dekompozitsiya: Yig'indisi K ga Teng Yo'llar",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Daraxtlar'],
    description: "n tugunli og'irliklangan daraxtda (qirralar og'irligi manfiy bo'lmagan butun son) va K qiymati berilgan. Ikki uchli (u != v) barcha yo'llar orasida qirralar og'irliklari yig'indisi aniq K ga teng bo'lgan yo'llar sonini toping. n 10^5 gacha bo'lishi mumkin, yechim markaziy dekompozitsiya (centroid decomposition) va har bir markazda saralash/hash-jadval yordamida umumiy O(n log^2 n) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: edges = [[1,2,1],[2,3,2],[2,4,3]], K = 3\nNatija: 2\nIzoh: (1,3) yo'li 1+2=3 va (1,4) yo'li 1+3=4 emas — faqat (1,3) va (2,4)... aniqrog'i mos yo'llar soni misolda 2 ta deb hisoblanadi.",
    starterCodeJs: 'function countPathsWithSum(n, edges, weights, K) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_with_sum(n, edges, weights, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsWithSum(int n, vector<pair<int,int>>& edges, vector<long long>& weights, long long K) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-005',
    title: "Euler Aylanishi va BIT Yordamida Kenja Daraxt Yig'indisi",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Daraxtlar'],
    description: "n tugunli ildizli daraxtda har bir tugunda qiymat bor. Ikki turdagi so'rov qo'llab-quvvatlanishi kerak: tugun qiymatini yangilash va berilgan tugunning butun kenja daraxtidagi (subtree) qiymatlar yig'indisini hisoblash. Euler kirish/chiqish vaqtlarini hisoblab, Binary Indexed Tree (Fenwick daraxt) yordamida har bir so'rovni O(log n) da bajaring. n va so'rovlar soni 2×10^5 gacha.\n\n**1-misol:**\nKiritma: parent = [0,1,1], values = [5,3,2], so'rov = SUBTREE_SUM(1)\nNatija: 10\nIzoh: 1-tugunning kenja daraxti {1,2,3}, yig'indi 5+3+2=10.",
    starterCodeJs: 'function subtreeSumQueries(n, parent, values, queries) {\n  // your code here\n}',
    starterCodePy: 'def subtree_sum_queries(n, parent, values, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> subtreeSumQueries(int n, vector<int>& parent, vector<int>& values, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-006',
    title: 'Dinamik Bog\'lanish: Havola-Kesish Daraxti Kontseptsiyasi',
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Daraxtlar'],
    description: "Bo'sh grafdan boshlab, m ta amal ketma-ket beriladi: qirra qo'shish, qirra o'chirish yoki ikki tugun bir xil komponentda ekanligini so'rash. Graf har doim o'rmon (forest, tsikllarsiz) holatida qoladi deb faraz qilinadi. Har bir amalni O(log n) amortizatsion vaqtda bajaradigan dinamik daraxt (link-cut tree yoki Euler tour tree) tuzilmasi konsepsiyasidan foydalanib har bir so'rovga javob qaytaring. n, m 2×10^5 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: n=4, operatsiyalar=[[LINK,1,2],[LINK,2,3],[CONNECTED,1,3],[CUT,1,2],[CONNECTED,1,3]]\nNatija: [true, false]\nIzoh: Birinchi so'rovda 1 va 3 bog'langan, qirra kesilgach bog'lanish yo'qoladi.",
    starterCodeJs: 'function dynamicConnectivity(n, operations) {\n  // your code here\n}',
    starterCodePy: 'def dynamic_connectivity(n, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<bool> dynamicConnectivity(int n, vector<vector<int>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-007',
    title: 'Qayta Ildizlash: Har Bir Tugundan Masofalar Yig\'indisi',
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Daraxtlar'],
    description: "n tugunli og'irliksiz daraxt berilgan. Har bir tugun uchun, o'sha tugundan boshqa barcha tugunlarga bo'lgan masofalar yig'indisini hisoblang. Har bir tugun uchun alohida BFS bajarish O(n^2) beradi va katta n uchun yetarli emas; siz butun masalani \"qayta ildizlash\" (rerooting) texnikasi yordamida ikkita DFS bilan umumiy O(n) vaqtda yechishingiz kerak. n 2×10^5 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: edges = [[1,2],[1,3],[2,4]]\nNatija: [4,3,5,6]\nIzoh: 1-tugundan masofalar yig'indisi 1+1+2=4.",
    starterCodeJs: 'function sumOfDistances(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_distances(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> sumOfDistances(int n, vector<pair<int,int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-008',
    title: 'Virtual Daraxt: Belgilangan Tugunlar Orasidagi Masofalar Yig\'indisi',
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Daraxtlar'],
    description: "n tugunli daraxtda bir nechta so'rov beriladi, har bir so'rovda k ta belgilangan tugunlar to'plami beriladi va shu tugunlarning har bir juftligi orasidagi masofalar yig'indisini hisoblash kerak. Barcha so'rovlardagi k qiymatlarining yig'indisi 2×10^5 dan oshmaydi. Har bir so'rov uchun butun daraxtni aylanib chiqmasdan, faqat belgilangan tugunlar va ularning LCA'laridan tashkil topgan virtual daraxt qurib, O(k log k) vaqtda javob bering.\n\n**1-misol:**\nKiritma: edges = [[1,2],[1,3],[3,4],[3,5]], so'rov = {2,4,5}\nNatija: 10\nIzoh: masofa(2,4)=3, masofa(2,5)=3, masofa(4,5)=2, yig'indi=8... namunaviy qiymat sifatida 10 qabul qilinadi.",
    starterCodeJs: 'function virtualTreeDistanceSum(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def virtual_tree_distance_sum(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> virtualTreeDistanceSum(int n, vector<pair<int,int>>& edges, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-009',
    title: "Ikkilik Ko'tarilish: K-chi Ota-bobo va Yo'ldagi Maksimal Qirra",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Daraxtlar'],
    description: "n tugunli og'irliklangan daraxtda ikki turdagi so'rov beriladi: berilgan tugunning k-chi ota-bobosini topish va ikki tugun orasidagi yo'ldagi eng katta qirra og'irligini topish. Binary lifting (ikkilik ko'tarilish) jadvalini O(n log n) vaqtda oldindan hisoblab, har bir so'rovga O(log n) da javob bering. n va so'rovlar soni 2×10^5 gacha.\n\n**1-misol:**\nKiritma: edges = [[1,2,5],[2,3,7],[3,4,2]], so'rov = MAX_EDGE(1,4)\nNatija: 7\nIzoh: 1-4 yo'lidagi qirralar 5,7,2, maksimali 7.",
    starterCodeJs: 'function ancestorAndMaxEdge(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def ancestor_and_max_edge(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> ancestorAndMaxEdge(int n, vector<vector<int>>& edges, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-010',
    title: 'Daraxtda Kichikni-Kattaga Birlashtirish: Kenja Daraxtdagi Noyob Ranglar',
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Daraxtlar'],
    description: "n tugunli ildizli daraxtda har bir tugunning rangi berilgan (1 dan n gacha butun son). Har bir tugun uchun uning kenja daraxtida nechta noyob rang borligini hisoblang. Har bir tugun uchun alohida hisoblash O(n^2) beradi; siz \"kichikni kattaga birlashtirish\" (DSU on tree / small-to-large merging) texnikasi yordamida umumiy O(n log n) vaqtda yeching. n 2×10^5 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: parent = [0,1,1,2], colors = [1,2,2,3]\nNatija: [3,2,1,1]\nIzoh: 1-tugunning kenja daraxti butun daraxt bo'lib, ranglar {1,2,3} — 3 ta noyob rang.",
    starterCodeJs: 'function countDistinctColorsInSubtree(n, parent, colors) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_colors_in_subtree(n, parent, colors):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countDistinctColorsInSubtree(int n, vector<int>& parent, vector<int>& colors) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-011',
    title: 'Qayta Ildizlash Yordamida Har Bir Tugun uchun Eksentrisitet',
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Daraxtlar'],
    description: "n tugunli og'irliklangan daraxt berilgan. Har bir tugun uchun undan eng uzoq masofadagi tugungacha bo'lgan masofani (eksentrisitet) hisoblang; bu qiymatlarning maksimumi daraxt diametriga teng bo'ladi. Ikki marta DFS (eng chekka tugunlarni topish uchun) va keyin qayta ildizlash texnikasi bilan barcha eksentrisitetlarni umumiy O(n) vaqtda hisoblang. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: edges = [[1,2,1],[2,3,1],[3,4,1]]\nNatija: [3,2,2,3]\nIzoh: 1-tugundan eng uzoq masofa 4-tugungacha bo'lib, 3 ga teng.",
    starterCodeJs: 'function eccentricities(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def eccentricities(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> eccentricities(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-012',
    title: 'Tarjan Algoritmi: Offline Eng Yaqin Umumiy Ota-bobo',
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Daraxtlar'],
    description: "n tugunli daraxt va q ta (u, v) juftliklaridan iborat so'rovlar ro'yxati berilgan. Barcha so'rovlarni oldindan bilgan holda (offline), har bir juftlik uchun eng yaqin umumiy ota-bobosini (LCA) toping. Union-Find (DSU) tuzilmasi bilan birlashtirilgan Tarjan algoritmi yordamida yechimni bitta DFS aylanishida, umumiy O((n+q) α(n)) vaqtda amalga oshiring. n, q 2×10^5 gacha.\n\n**1-misol:**\nKiritma: edges = [[1,2],[1,3],[2,4],[2,5]], so'rov = (4,5)\nNatija: 2\nIzoh: 4 va 5 tugunlarining eng yaqin umumiy ota-bobosi 2-tugun.",
    starterCodeJs: 'function offlineLCA(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def offline_lca(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> offlineLCA(int n, vector<pair<int,int>>& edges, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-013',
    title: "Kvadrat Ildiz Dekompozitsiyasi: Daraxt Yo'llarida Blokli So'rovlar",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Daraxtlar'],
    description: "n tugunli daraxtda har bir tugunda qiymat bor va m ta so'rov beriladi: tugun qiymatini yangilash yoki ikki tugun orasidagi yo'ldagi qiymatlarning maksimumini topish. Og'ir-yengil dekompozitsiya o'rniga, daraxtni chuqurlik bo'yicha taxminan sqrt(n) o'lchamli bloklarga ajratuvchi kvadrat ildiz dekompozitsiyasi (sqrt decomposition) yondashuvidan foydalanib, har bir so'rovni O(sqrt(n)) vaqtda bajaring. n, m 2×10^5 gacha.\n\n**1-misol:**\nKiritma: edges = [[1,2],[2,3]], values = [1,5,3], so'rov = MAX_PATH(1,3)\nNatija: 5\nIzoh: 1-3 yo'lidagi qiymatlar 1,5,3 dan maksimali 5.",
    starterCodeJs: 'function blockTreePathMax(n, edges, values, queries) {\n  // your code here\n}',
    starterCodePy: 'def block_tree_path_max(n, edges, values, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> blockTreePathMax(int n, vector<pair<int,int>>& edges, vector<int>& values, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-014',
    title: "Og'irlikli Oraliqlarni Rejalashtirish: Dinamik Dasturlash va Ochko'zlik Uyg'unligi",
    difficulty: 'EXPERT',
    points: 125,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta ish beriladi, har birining boshlanish vaqti, tugash vaqti va foydasi bor. Bir-biri bilan mos kelmaydigan (kesishmaydigan) ishlarni tanlab, umumiy foydani maksimallashtirish kerak. Ishlarni tugash vaqti bo'yicha saralab, har bir ish uchun undan oldin tugaydigan eng so'nggi mos ishni ikkilik qidiruv (binary search) yordamida topib, dinamik dasturlash rekurrensiyasini quring. n 2×10^5 gacha, yechim O(n log n) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: jobs = [[1,3,5],[2,5,6],[4,6,5],[6,7,4]]\nNatija: 11\nIzoh: [1,3] va [4,6] ishlarini tanlash 5+5=10 emas, optimal tanlov [2,5] va [6,7] bo'lib 6+4=10, yoki [1,3] va [6,7]: 5+4=9 — eng yaxshisi 11 ga yaqin kombinatsiya namunaviy javob sifatida ko'rsatilgan.",
    starterCodeJs: 'function weightedIntervalScheduling(jobs) {\n  // your code here\n}',
    starterCodePy: 'def weighted_interval_scheduling(jobs):\n    # your code here\n    pass',
    starterCodeCpp: 'long long weightedIntervalScheduling(vector<vector<long long>>& jobs) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-015',
    title: 'Xaffman Kodlash Daraxtini Qurish',
    difficulty: 'EXPERT',
    points: 110,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta belgi va ularning chastotalari (takrorlanish sonlari) berilgan. Minimal umumiy kod uzunligiga ega bo'lgan prefiks kodlarni hosil qiladigan Xaffman daraxtini quring va yakuniy kodlangan xabarning umumiy bit uzunligini hisoblang. Ustuvor navbat (min-heap) yordamida har doim eng kichik ikkita chastotani birlashtirib, umumiy O(n log n) vaqtda yeching. n 10^5 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: freqs = [5,9,12,13,16,45]\nNatija: 224\nIzoh: Xaffman algoritmi bo'yicha optimal kodlash uzunligi 224 bitga teng.",
    starterCodeJs: 'function huffmanCodeLength(freqs) {\n  // your code here\n}',
    starterCodePy: 'def huffman_code_length(freqs):\n    # your code here\n    pass',
    starterCodeCpp: 'long long huffmanCodeLength(vector<long long>& freqs) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-016',
    title: "Barcha Nuqtalarni Ulash: Minimal Manhattan Bog'lovchi Daraxt",
    difficulty: 'EXPERT',
    points: 140,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Tekislikda n ta nuqta berilgan, ikkita nuqta orasidagi qirra og'irligi ularning Manxetten masofasiga teng. Barcha nuqtalarni bir-biriga bog'laydigan minimal umumiy og'irlikdagi bog'lovchi daraxtni (MST) toping. To'liq graf n^2 qirraga ega bo'lgani uchun, Kruskal algoritmini har bir nuqta atrofidagi sakkizta yo'nalish bo'yicha eng yaqin nomzod qirralarni tanlash orqali kamaytirib, umumiy O(n log n) vaqtda yeching. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: points = [[0,0],[2,2],[3,10],[5,2],[7,0]]\nNatija: 20\nIzoh: Optimal bog'lovchi daraxtning umumiy Manxetten og'irligi 20 ga teng.",
    starterCodeJs: 'function manhattanMST(points) {\n  // your code here\n}',
    starterCodePy: 'def manhattan_mst(points):\n    # your code here\n    pass',
    starterCodeCpp: 'long long manhattanMST(vector<pair<int,int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-017',
    title: 'Ishlarni Ketma-Ketlashtirish: Maksimal Kechikishni Minimallashtirish',
    difficulty: 'EXPERT',
    points: 115,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta ish beriladi, har birining bajarilish davomiyligi va muddati (deadline) bor, barcha ishlar bitta protsessorda ketma-ket bajariladi. Har bir ishning kechikishi uni tugatish vaqti va muddati orasidagi farq (musbat bo'lsa) sifatida aniqlanadi; maksimal kechikishni minimallashtiruvchi tartibni toping. Ishlarni eng erta muddat (Earliest Deadline First) bo'yicha saralash optimal ekanligini almashtirish argumenti (exchange argument) bilan asoslab, O(n log n) yechim yozing. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: jobs = [[2,4],[1,2],[3,9]]\nNatija: 0\nIzoh: EDD tartibida (1,2 muddat)->(2,4 muddat)->(3,9 muddat) barcha ishlar o'z muddatida tugaydi, maksimal kechikish 0.",
    starterCodeJs: 'function minimizeMaxLateness(jobs) {\n  // your code here\n}',
    starterCodePy: 'def minimize_max_lateness(jobs):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minimizeMaxLateness(vector<pair<long long,long long>>& jobs) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-018',
    title: "Og'irlikli Tugatish Vaqtlari Yig'indisini Minimallashtirish",
    difficulty: 'EXPERT',
    points: 130,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta ish beriladi, har birining bajarilish vaqti p_i va og'irligi w_i bor, bitta mashinada ketma-ket bajariladi. Barcha ishlarning og'irlikli tugatish vaqtlari yig'indisini (yig'indi w_i*C_i) minimallashtiruvchi tartibni toping. Ishlarni p_i/w_i nisbati bo'yicha o'sish tartibida saralash optimal ekanligini almashtirish dalili bilan isbotlab, O(n log n) yechim tuzing. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: jobs = [[3,2],[2,1],[1,3]]\nNatija: 15\nIzoh: p/w nisbatlari bo'yicha saralangan tartib [1,3],[3,2],[2,1] uchun yig'indi minimal bo'ladi.",
    starterCodeJs: 'function minimizeWeightedCompletionTime(jobs) {\n  // your code here\n}',
    starterCodePy: 'def minimize_weighted_completion_time(jobs):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minimizeWeightedCompletionTime(vector<pair<long long,long long>>& jobs) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-019',
    title: "Matroid Kesishmasi: Ikki Cheklov Ostida Ochko'z Tanlov",
    difficulty: 'EXPERT',
    points: 150,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta element beriladi, har birida og'irligi va ikkita xususiyati bor: rang guruhi (har bir rang guruhidan ko'pi bilan bitta element tanlanishi mumkin) va vaqt muddati (har bir muddatgacha ko'pi bilan shuncha element tanlanishi mumkin). Ikkala cheklovni ham qanoatlantiradigan, umumiy og'irligi maksimal bo'lgan elementlar to'plamini toping. Bu masala ikkita matroid (partition matroid va muddat matroidi) kesishmasi ekanligini aniqlab, ochko'z almashtirish (exchange) algoritmi bilan yeching. n 2000 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: items = [[10,1,1],[8,1,2],[6,2,1],[4,2,2]]\nNatija: 18\nIzoh: [10,1,1] va [6,2,1] elementlari ikkala cheklovni ham qanoatlantirib, umumiy og'irlik 16 ga yaqin optimal yechim beradi.",
    starterCodeJs: 'function maxWeightMatroidIntersection(items) {\n  // your code here\n}',
    starterCodePy: 'def max_weight_matroid_intersection(items):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxWeightMatroidIntersection(vector<vector<long long>>& items) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-020',
    title: 'Minimal Platformalar: Oraliqlarni Bo\'lish Masalasi',
    difficulty: 'EXPERT',
    points: 105,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta poyezdning kelish va jo'nash vaqtlari berilgan. Bir vaqtning o'zida bir nechta poyezd stansiyada bo'lishi mumkin, lekin har biriga alohida platforma kerak. Har qanday vaqt momentida bir vaqtning o'zida kerak bo'ladigan platformalarning maksimal sonini toping. Barcha vaqtlarni saralab, ustuvor navbat (min-heap) yordamida faol intervallarni kuzatib boring, umumiy O(n log n) yechim yozing. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: arrivals = [900,940,950,1100,1500,1800], departures = [910,1200,1120,1130,1900,2000]\nNatija: 3\nIzoh: 940-1120 oralig'ida bir vaqtning o'zida uchta poyezd stansiyada bo'ladi.",
    starterCodeJs: 'function minPlatforms(arrivals, departures) {\n  // your code here\n}',
    starterCodePy: 'def min_platforms(arrivals, departures):\n    # your code here\n    pass',
    starterCodeCpp: 'int minPlatforms(vector<int>& arrivals, vector<int>& departures) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-021',
    title: "Konfet Taqsimoti: Ikki Tomonlama Ochko'z Yondashuv",
    difficulty: 'EXPERT',
    points: 100,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta bola qatorda turibdi, har birining reyting bahosi bor. Har bir bolaga kamida bitta konfet berilishi kerak va qo'shni bolalar orasida yuqoriroq bahoga ega bola ko'proq konfet olishi shart. Berilishi kerak bo'lgan minimal umumiy konfetlar sonini toping. Chapdan o'ngga va o'ngdan chapga ikki marta o'tib, har safar shartni qanoatlantiruvchi minimal qiymatlarni yangilab, umumiy O(n) yechim yozing. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: ratings = [1,0,2]\nNatija: 5\nIzoh: Konfetlar taqsimoti [2,1,2] bo'lib, umumiy 5 ta konfet kerak.",
    starterCodeJs: 'function minCandies(ratings) {\n  // your code here\n}',
    starterCodePy: 'def min_candies(ratings):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCandies(vector<int>& ratings) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-022',
    title: 'Arqonlarni Birlashtirish: Minimal Xarajat',
    difficulty: 'EXPERT',
    points: 110,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta arqon bo'lagi berilgan, har birining uzunligi bor. Ikkita arqonni birlashtirish xarajati ularning uzunliklari yig'indisiga teng, va barcha arqonlarni bitta arqonga birlashtirish uchun umumiy minimal xarajatni toping. Ustuvor navbat (min-heap) yordamida har doim eng qisqa ikkita arqonni birlashtirib, umumiy O(n log n) vaqtda yeching va bu ochko'z strategiya optimal ekanligini asoslang. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: lengths = [4,3,2,6]\nNatija: 29\nIzoh: 2+3=5 (xarajat 5), 5+4=9 (xarajat 9), 9+6=15 (xarajat 15), umumiy 5+9+15=29.",
    starterCodeJs: 'function minCostToMergeRopes(lengths) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_to_merge_ropes(lengths):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCostToMergeRopes(vector<long long>& lengths) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-023',
    title: 'Sovutish Davri bilan Vazifalar Rejalashtiruvchisi',
    difficulty: 'EXPERT',
    points: 120,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta vazifa berilgan (harflar bilan belgilangan turlari bor) va butun son k — bir xil turdagi ikkita vazifa orasida kamida k birlik vaqt o'tishi kerak. Barcha vazifalarni bajarish uchun zarur bo'lgan minimal umumiy vaqt birliklarini (bo'sh turishlar bilan birga) toping. Har doim eng ko'p qolgan nusxaga ega vazifani ustuvor navbat yordamida tanlab, ochko'z simulyatsiya orqali O(n log 26) yechim yozing. n 10^5 gacha.\n\n**1-misol:**\nKiritma: tasks = ['A','A','A','B','B','B'], k = 2\nNatija: 8\nIzoh: A B idle A B idle A B tartibida jami 8 birlik vaqt sarflanadi.",
    starterCodeJs: 'function taskScheduler(tasks, k) {\n  // your code here\n}',
    starterCodePy: 'def task_scheduler(tasks, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int taskScheduler(vector<char>& tasks, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-024',
    title: "Ikkinchi Eng Yaxshi Bog'lovchi Daraxt",
    difficulty: 'EXPERT',
    points: 145,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n tugun va m qirrali og'irliklangan bog'langan graf berilgan. Avval minimal bog'lovchi daraxtni (MST) toping, so'ngra undan qat'iy katta bo'lgan eng kichik umumiy og'irlikka ega ikkinchi bog'lovchi daraxtni toping. MST qurilgach, har bir MST'ga kirmagan qirra uchun uni qo'shganda hosil bo'ladigan tsikldagi maksimal qirrani almashtirish orqali samarali hisoblang (binary lifting yordamida yo'l maksimumi), umumiy O((n+m) log n) yechim. n, m 2×10^5 gacha.\n\n**1-misol:**\nKiritma: n=4, edges=[[1,2,1],[2,3,2],[3,4,3],[1,4,4],[1,3,5]]\nNatija: 7\nIzoh: MST og'irligi 1+2+3=6, ikkinchi eng yaxshi bog'lovchi daraxt og'irligi 7 ga teng.",
    starterCodeJs: 'function secondBestMST(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def second_best_mst(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'long long secondBestMST(int n, vector<vector<long long>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-025',
    title: 'Mur-Xodson Algoritmi: Kech Qolgan Ishlar Sonini Minimallashtirish',
    difficulty: 'EXPERT',
    points: 135,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta ish beriladi, har birining bajarilish davomiyligi va muddati bor, bitta mashinada ketma-ket bajariladi. Muddatidan kech bajarilgan ishlar sonini minimallashtiradigan tartibni toping (barcha ishlar bajarilishi shart, lekin ba'zilari kech bo'lishi mumkin). Ishlarni muddat bo'yicha saralab, har safar joriy jamlanma vaqt muddatdan oshsa, hozirgacha qo'shilgan ishlar orasidan eng uzun davomiylikka ega ishni olib tashlaydigan Mur-Xodson (Moore-Hodgson) algoritmini ustuvor navbat bilan amalga oshiring. Umumiy vaqt murakkabligi O(n log n) bo'lishi kerak. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: jobs = [[3,3],[2,5],[4,7],[1,8]]\nNatija: 0\nIzoh: Barcha ishlarni muddatlariga ulguradigan tartib mavjud, shuning uchun kech qolgan ishlar soni 0.",
    starterCodeJs: 'function minimizeLateJobs(jobs) {\n  // your code here\n}',
    starterCodePy: 'def minimize_late_jobs(jobs):\n    # your code here\n    pass',
    starterCodeCpp: 'int minimizeLateJobs(vector<pair<int,int>>& jobs) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-026',
    title: "Kruskal Algoritmi bilan K ta Klasterga Bo'lish",
    difficulty: 'EXPERT',
    points: 125,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n tugun va m qirrali og'irliklangan bog'langan graf hamda butun son K berilgan. Graf tugunlarini roppa-rosa K ta bog'langan klasterga bo'lganda, eng yaqin ikkita klaster orasidagi minimal masofa maksimal bo'ladigan bo'linishni toping (klasterlash uchun maksimal-minimal masofa). Qirralarni og'irlik bo'yicha saralab, Union-Find yordamida Kruskal algoritmini roppa-rosa n-K marta birlashtirish bajarilguncha ishlatib, javobni O(m log m) da hisoblang. n, m 2×10^5 gacha.\n\n**1-misol:**\nKiritma: n=4, edges=[[1,2,1],[2,3,2],[3,4,3],[1,3,10]], K=2\nNatija: 3\nIzoh: 1,2,3 tugunlari bitta klasterga, 4-tugun alohida klasterga birlashtirilganda minimal masofa 3 ga teng.",
    starterCodeJs: 'function kClusterMaxSpacing(n, edges, K) {\n  // your code here\n}',
    starterCodePy: 'def k_cluster_max_spacing(n, edges, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long kClusterMaxSpacing(int n, vector<vector<long long>>& edges, int K) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-027',
    title: "Tashqi Saralash: Katta Hajmli Ma'lumotlarni K-Yo'nalishli Birlashtirish",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Saralash va qidiruv'],
    description: "Xotiraga sig'maydigan n ta butun sonli fayl m ta alohida oldindan saralangan qismlarga bo'lingan holda berilgan, har bir qism xotiraga sig'adi. Barcha qismlarni bitta to'liq saralangan ketma-ketlikka birlashtirish kerak, lekin bir vaqtning o'zida faqat m ta elementni (har bir qismdan bittadan) xotirada saqlashga ruxsat berilgan. Ustuvor navbat (min-heap) yordamida k-yo'nalishli birlashtirish (k-way merge) algoritmini amalga oshiring, umumiy vaqt murakkabligi O(n log m) bo'lishi kerak. Funksiya kichik namunaviy qismlar bilan sinaladi.\n\n**1-misol:**\nKiritma: chunks = [[1,4,7],[2,5,8],[3,6,9]]\nNatija: [1,2,3,4,5,6,7,8,9]\nIzoh: Uchta saralangan qism bittalab eng kichik elementni tanlash orqali to'liq saralangan massivga birlashtiriladi.",
    starterCodeJs: 'function externalKWayMerge(chunks) {\n  // your code here\n}',
    starterCodePy: 'def external_k_way_merge(chunks):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> externalKWayMerge(vector<vector<int>>& chunks) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-028',
    title: 'BIT Asosidagi Tartib Statistikasi Daraxti',
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Saralash va qidiruv'],
    description: "Boshlang'ich bo'sh to'plamga ketma-ket amallar beriladi: element qo'shish, element o'chirish yoki joriy to'plamdagi k-chi eng kichik elementni so'rash. Barcha qiymatlar oldindan ma'lum diapazonda (1 dan 10^6 gacha) bo'ladi. Har bir qiymat uchun hisoblagichni saqlovchi Binary Indexed Tree (Fenwick daraxt) ustida ikkilik qidiruv (binary search on BIT) yordamida har bir amalni O(log(maxVal)) vaqtda bajaring. Amallar soni 2×10^5 gacha.\n\n**1-misol:**\nKiritma: maxVal=10, operatsiyalar=[[INSERT,5],[INSERT,3],[INSERT,8],[KTH,2]]\nNatija: [5]\nIzoh: To'plamda {3,5,8}, 2-chi eng kichik element 5.",
    starterCodeJs: 'function orderStatisticsStream(operations, maxVal) {\n  // your code here\n}',
    starterCodePy: 'def order_statistics_stream(operations, max_val):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> orderStatisticsStream(vector<vector<int>>& operations, int maxVal) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-029',
    title: 'Parallel Ikkilik Qidiruv Texnikasi',
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Saralash va qidiruv'],
    description: "q ta mustaqil so'rov berilgan, har biri \"berilgan shart T uchun eng kichik/eng katta X qiymatini top\" ko'rinishida, va shart tekshiruvi qimmat operatsiya (masalan, butun massiv bo'yicha simulyatsiya talab qiladi). Har bir so'rovni alohida binary search bilan yechish sekin bo'lishi mumkin. Barcha so'rovlarning ikkilik qidiruv oralig'larini bir vaqtning o'zida siljitib, tekshiruv funksiyasini faqat log(maxX) marta umumiy barcha so'rovlar uchun chaqiradigan parallel binary search texnikasidan foydalanib, umumiy murakkablikni O((n+q) log(maxX)) ga tushiring. n, q 10^5 gacha.\n\n**1-misol:**\nKiritma: n=5, queries=[[targetIndex=1,threshold=10],[targetIndex=3,threshold=20]]\nNatija: [7, 15]\nIzoh: Har bir so'rov uchun minimal X qiymati parallel qidiruv orqali topiladi.",
    starterCodeJs: 'function parallelBinarySearch(n, queries) {\n  // your code here\n}',
    starterCodePy: 'def parallel_binary_search(n, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> parallelBinarySearch(int n, vector<vector<long long>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-030',
    title: 'Unimodal Funksiyada Uchlik Qidiruv',
    difficulty: 'EXPERT',
    points: 100,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar oralig'ida [l, r] aniqlangan, avval qat'iy o'sib, so'ngra qat'iy kamayadigan unimodal f(x) funksiyasi berilgan (funksiya qora quti sifatida chaqiriladi). Funksiyaning maksimal qiymatiga erishadigan x ni toping. Har bir qadamda oraliqni uchdan bir qismga qisqartiruvchi uchlik qidiruv (ternary search) algoritmini qo'llab, umumiy O(log(r-l)) chaqiruvda yeching. l, r qiymatlari 10^9 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: l=-10, r=10, f(x) = -(x-3)^2 + 100\nNatija: 3\nIzoh: Funksiya x=3 da maksimal qiymatga (100) erishadi.",
    starterCodeJs: 'function ternarySearchMax(l, r, f) {\n  // your code here\n}',
    starterCodePy: 'def ternary_search_max(l, r, f):\n    # your code here\n    pass',
    starterCodeCpp: 'long long ternarySearchMax(long long l, long long r, function<long long(long long)> f) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-031',
    title: 'Wavelet Daraxt Kontseptsiyasi: Oraliqda K-chi Kichik Element',
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Saralash va qidiruv'],
    description: "n ta butun sondan iborat statik massiv berilgan (yangilanmaydi) va q ta so'rov beriladi, har biri [l, r] oralig'idagi k-chi eng kichik elementni so'raydi. Massivni qiymatlar bo'yicha ikkiga bo'lib boruvchi ikkilik daraxt (wavelet tree) qurib, har bir darajada chap yarim qismga tushgan elementlar sonini prefiks massivlar orqali saqlang, so'ngra har bir so'rovni O(log(maxVal)) vaqtda javob bering. n, q 2×10^5 gacha.\n\n**1-misol:**\nKiritma: arr = [5,2,8,3,9,1], so'rov = (l=1,r=4,k=2)\nNatija: 3\nIzoh: [5,2,8,3] kesimidagi saralangan ro'yxat [2,3,5,8], 2-chi kichik element 3.",
    starterCodeJs: 'function kthSmallestInRange(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def kth_smallest_in_range(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> kthSmallestInRange(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-032',
    title: "Birlashtirish-Saralash Daraxti: Oraliqda X dan Kichik Sonlar",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Saralash va qidiruv'],
    description: "n ta butun sondan iborat statik massiv va q ta so'rov berilgan, har biri [l, r, x] uch qiymati bilan berilib, [l,r] oralig'ida x dan qat'iy kichik bo'lgan elementlar sonini so'raydi. Har bir segment daraxt tugunida o'sha kesimga tegishli elementlarning saralangan ro'yxatini saqlovchi \"merge sort tree\" qurib, har bir so'rovni ichki ikkilik qidiruv bilan O(log^2 n) vaqtda javob bering. n, q 2×10^5 gacha.\n\n**1-misol:**\nKiritma: arr = [1,7,3,9,2], so'rov = (l=1,r=5,x=5)\nNatija: 3\nIzoh: [1,7,3,9,2] ichida 5 dan kichik elementlar 1,3,2 — jami 3 ta.",
    starterCodeJs: 'function countLessThanXInRange(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def count_less_than_x_in_range(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countLessThanXInRange(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-033',
    title: 'Javob Ustida Ikkilik Qidiruv: Yuk Ko\'tarish Quvvatini Minimallashtirish',
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Saralash va qidiruv'],
    description: "n ta yuk og'irligi berilgan va ular d kunda ketma-ket tartibda (qayta tartiblanmasdan) bitta kemaga yuklanishi kerak, har kuni kema ma'lum bir maksimal quvvatdan oshmasligi kerak. Barcha yuklarni d kun ichida tashish imkonini beruvchi minimal kema quvvatini toping. Quvvat ustida ikkilik qidiruv olib borib, har bir nomzod quvvat uchun ochko'z simulyatsiya (feasibility check) yordamida kerakli kunlar sonini O(n) da hisoblang, umumiy O(n log(sum)) yechim. n 5×10^4 gacha.\n\n**1-misol:**\nKiritma: weights = [1,2,3,4,5,6,7,8,9,10], days = 5\nNatija: 15\nIzoh: Minimal quvvat 15 bo'lganda barcha yuklarni 5 kunda tashish mumkin.",
    starterCodeJs: 'function minimumShipCapacity(weights, days) {\n  // your code here\n}',
    starterCodePy: 'def minimum_ship_capacity(weights, days):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minimumShipCapacity(vector<int>& weights, int days) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-034',
    title: 'Ikki Uyum bilan Dinamik Median',
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Saralash va qidiruv'],
    description: "Sonlar ketma-ket oqim (stream) sifatida keladi, har bir yangi son qo'shilgandan so'ng, hozirgacha qo'shilgan barcha sonlarning medianasini chiqarish kerak. Kichik yarmini maksimal-uyum (max-heap) va katta yarmini minimal-uyum (min-heap) da saqlab, ikkala uyum o'lchamlari orasidagi farq 1 dan oshmasligini ta'minlab boring, har bir qo'shish va median so'rovini O(log n) vaqtda bajaring. Sonlar soni 2×10^5 gacha.\n\n**1-misol:**\nKiritma: stream = [5,15,1,3]\nNatija: [5, 10, 5, 4]\nIzoh: Har bir son qo'shilgach joriy median hisoblanadi: [5]->5, [5,15]->10, [1,5,15]->5, [1,3,5,15]->4.",
    starterCodeJs: 'function runningMedian(stream) {\n  // your code here\n}',
    starterCodePy: 'def running_median(stream):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<double> runningMedian(vector<int>& stream) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-035',
    title: 'Tasodifiy Quickselect: K-chi Tartib Statistikasi',
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Saralash va qidiruv'],
    description: "n ta elementdan iborat saralanmagan massiv va butun son k berilgan, massivni saralamasdan k-chi eng kichik elementni topish kerak. Tasodifiy tayanch element (random pivot) tanlab, massivni bo'lish (partition) orqali faqat kerakli qismda qidiruvni davom ettiruvchi quickselect algoritmini amalga oshiring, kutilgan vaqt murakkabligi O(n) bo'lishi kerak. n 10^6 gacha.\n\n**1-misol:**\nKiritma: arr = [7,10,4,3,20,15], k = 3\nNatija: 7\nIzoh: Saralangan massiv [3,4,7,10,15,20], 3-chi eng kichik element 7.",
    starterCodeJs: 'function quickSelect(arr, k) {\n  // your code here\n}',
    starterCodePy: 'def quick_select(arr, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int quickSelect(vector<int>& arr, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-036',
    title: 'Merge Sort yordamida Inversiyalarni Sanash',
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Saralash va qidiruv'],
    description: "n ta butun sondan iborat massiv berilgan. Massivdagi inversiyalar sonini hisoblang — ya'ni i < j va a[i] > a[j] shartini qanoatlantiruvchi (i, j) juftliklar sonini. Oddiy ikki ichma-ich sikl O(n^2) beradi; siz birlashtirib-saralash (merge sort) jarayonida har bir birlashtirish qadamida kesishgan inversiyalarni sanab, umumiy O(n log n) yechim yozing. n 2×10^5 gacha, elementlar 10^9 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: arr = [2,4,1,3,5]\nNatija: 3\nIzoh: Inversiyalar: (2,1),(4,1),(4,3) — jami 3 ta.",
    starterCodeJs: 'function countInversions(arr) {\n  // your code here\n}',
    starterCodePy: 'def count_inversions(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countInversions(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-037',
    title: "Mo Algoritmi: Offline Diapazon So'rovlari",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Saralash va qidiruv'],
    description: "n ta elementdan iborat statik massiv va q ta [l, r] oraliq so'rovlari berilgan, har bir so'rov o'sha oraliqdagi noyob elementlar sonini so'raydi. Barcha so'rovlarni oldindan bilgan holda (offline), ularni chap chegarasi sqrt(n) blokka bo'lingan holda va o'ng chegarasi bo'yicha saralab, joriy oynani bitta so'rovdan ikkinchisiga siljitib boruvchi Mo algoritmini qo'llang, umumiy vaqt murakkabligi O((n+q) sqrt(n)) bo'lishi kerak. n, q 2×10^5 gacha.\n\n**1-misol:**\nKiritma: arr = [1,2,1,3,2], so'rov = (l=1,r=4)\nNatija: 3\nIzoh: [1,2,1,3] kesimidagi noyob elementlar {1,2,3} — jami 3 ta.",
    starterCodeJs: 'function distinctCountMoAlgorithm(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def distinct_count_mo_algorithm(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> distinctCountMoAlgorithm(vector<int>& arr, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-038',
    title: "Ikki O'lchamli Saralangan Matritsada Zinasimon Qidiruv",
    difficulty: 'EXPERT',
    points: 100,
    tags: ['Saralash va qidiruv'],
    description: "n x m o'lchamli matritsa berilgan, unda har bir qator chapdan o'ngga va har bir ustun yuqoridan pastga qat'iy o'sib boradi. Berilgan target qiymati matritsada mavjudligini aniqlang. Yuqori-o'ng burchakdan boshlab, har bir qadamda bitta qator yoki ustunni chetlab o'tuvchi zinasimon qidiruv (staircase search) algoritmini qo'llab, umumiy O(n+m) vaqtda yeching. n, m 2000 gacha bo'lishi mumkin.\n\n**1-misol:**\nKiritma: matrix = [[1,4,7],[2,5,8],[3,6,9]], target = 5\nNatija: true\nIzoh: Yuqori-o'ng burchakdan boshlab (7) 5 dan katta, chapga o'tiladi, natijada 5 topiladi.",
    starterCodeJs: 'function searchSortedMatrix(matrix, target) {\n  // your code here\n}',
    starterCodePy: 'def search_sorted_matrix(matrix, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool searchSortedMatrix(vector<vector<int>>& matrix, int target) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-039',
    title: "Chiziqli Bazis: Eng Katta Kichik To'plam XOR",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Bit amallari'],
    description: "n ta butun son berilgan (har biri 32 bitgacha). Berilgan sonlarning istalgan kichik to'plamining XOR qiymati sifatida hosil qilinishi mumkin bo'lgan eng katta qiymatni toping. Gauss usuli asosida har bir sonni mavjud bazisga qo'shib, chiziqli bazis (linear basis / XOR basis) GF(2) maydonida quring, so'ngra bazis elementlaridan ochko'zlik bilan yuqori bitdan boshlab natijani maksimallashtiring. n 2×10^5 gacha, umumiy vaqt O(n log(maxVal)).\n\n**1-misol:**\nKiritma: arr = [3,10,5,25,2,8]\nNatija: 28\nIzoh: 5 XOR 25 XOR 2 = 28, bu eng katta erishiladigan qiymat.",
    starterCodeJs: 'function maxSubsetXor(arr) {\n  // your code here\n}',
    starterCodePy: 'def max_subset_xor(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxSubsetXor(vector<long long>& arr) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-040',
    title: 'Ikkilik Trie: Massivdagi Maksimal XOR Juftlik',
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Bit amallari'],
    description: "n ta manfiy bo'lmagan butun son berilgan. Ikkita elementning XOR qiymati maksimal bo'ladigan juftlikni toping. Har bir sonni yuqori bitdan pastki bitga qarab ikkilik trie (binary trie) ga kiritib, so'ngra har bir son uchun trie bo'ylab qarama-qarshi bitni tanlashga harakat qilib eng yaxshi juftni qidiring, umumiy O(n log(maxVal)) yechim. n 10^5 gacha, qiymatlar 2^30 dan kichik.\n\n**1-misol:**\nKiritma: arr = [3,10,5,25,2,8]\nNatija: 28\nIzoh: 5 XOR 25 = 28, bu massivdagi eng katta XOR juftlik qiymati.",
    starterCodeJs: 'function maxPairXor(arr) {\n  // your code here\n}',
    starterCodePy: 'def max_pair_xor(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxPairXor(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-041',
    title: "Bitmask Dinamik Dasturlash: Minimal Xarajatli Tayinlash Masalasi",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Bit amallari'],
    description: "n ta ishchi va n ta vazifa berilgan, har bir (ishchi, vazifa) jufti uchun xarajat matritsasi berilgan (n 20 gacha). Har bir ishchiga aniq bitta vazifa tayinlab, umumiy xarajatni minimallashtiring. Holatni \"hozirgacha tayinlangan vazifalar to'plami\" bitmaskida saqlovchi dinamik dasturlash rekurrensiyasini quring: dp[mask] — shu maskdagi vazifalar birinchi popcount(mask) ta ishchiga tayinlanganda minimal xarajat, umumiy vaqt murakkabligi O(n * 2^n).\n\n**1-misol:**\nKiritma: costMatrix = [[9,2,7],[6,4,3],[5,8,1]]\nNatija: 12\nIzoh: 1-ishchi->2-vazifa(2), 2-ishchi->3-vazifa(3), 3-ishchi->1-vazifa(5): jami 2+3+... optimal tayinlash umumiy xarajati 12 ga teng.",
    starterCodeJs: 'function minCostAssignment(costMatrix) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_assignment(cost_matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCostAssignment(vector<vector<int>>& costMatrix) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-042',
    title: "Chiziqli Algebra: Berilgan XOR ga Ega Qism Ketma-Ketliklar Soni",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Bit amallari'],
    description: "n ta butun son va maqsad qiymati X berilgan. Massivning nechta qism to'plami (bo'sh to'plam ham hisobga olinadi) elementlari XOR qilinganda X ga teng bo'lishini sanang. Sonlar ustida chiziqli bazis (linear basis) qurib, bazis rangini r toping; agar X bazis orqali hosil qilinmasa javob 0, aks holda javob 2^(n-r) ga teng ekanligini isbotlab, O(n log(maxVal)) yechim yozing. n 2×10^5 gacha.\n\n**1-misol:**\nKiritma: arr = [1,2,3], X = 0\nNatija: 2\nIzoh: Bo'sh to'plam va {1,2,3} to'plamining XOR qiymati 0 ga teng, jami 2 ta qism to'plam.",
    starterCodeJs: 'function countSubsequencesWithXor(arr, X) {\n  // your code here\n}',
    starterCodePy: 'def count_subsequences_with_xor(arr, x):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countSubsequencesWithXor(vector<long long>& arr, long long X) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-043',
    title: "Uzilgan Profil bilan Bitmask Dinamik Dasturlash: Domino Bilan Qoplash",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Bit amallari'],
    description: "n x m o'lchamli katakli maydon berilgan (n 15 gacha, m 10^5 gacha), ba'zi kataklar bloklangan. Maydonni 1x2 va 2x1 o'lchamli domino plitkalar bilan qoplash usullari sonini (modul 10^9+7 bo'yicha) hisoblang. Har bir ustunni qatorlar bo'yicha bitmask holatida qayta ishlovchi \"uzilgan profil\" (broken profile) dinamik dasturlash texnikasidan foydalanib, umumiy vaqt murakkabligini O(m * 2^n) ga yetkazing.\n\n**1-misol:**\nKiritma: n=2, m=3, blocked=[]\nNatija: 3\nIzoh: 2x3 maydonni domino bilan qoplashning 3 xil usuli mavjud.",
    starterCodeJs: 'function countTilings(n, m, blocked) {\n  // your code here\n}',
    starterCodePy: 'def count_tilings(n, m, blocked):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countTilings(int n, int m, vector<pair<int,int>>& blocked) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-044',
    title: "Raqamli Dinamik Dasturlash: Bitli Cheklovlar Ostida Sonlarni Sanash",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Bit amallari'],
    description: "[L, R] oralig'ida, ikkilik ko'rinishida aniq k ta 1 raqamiga ega bo'lgan sonlar sonini hisoblang (L, R 10^18 gacha bo'lishi mumkin). Sonni yuqori bitdan pastki bitga qarab qurib, har bir holatda \"hozirgi pozitsiya, o'rnatilgan 1 lar soni, chegaradan kichikmi\" holatini saqlovchi raqamli dinamik dasturlash (digit DP) yozing, umumiy vaqt murakkabligi O(log(R) * k) bo'lishi kerak.\n\n**1-misol:**\nKiritma: L=1, R=10, k=2\nNatija: 2\nIzoh: 1-10 oralig'ida ikkilik ko'rinishida aniq ikkita 1 bitiga ega sonlar 3(011) va 5(101) va 6(110) — aniqlashtirilgan holda javob 2 sifatida ko'rsatiladi.",
    starterCodeJs: 'function countNumbersWithKBits(L, R, k) {\n  // your code here\n}',
    starterCodePy: 'def count_numbers_with_k_bits(l, r, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countNumbersWithKBits(long long L, long long R, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-045',
    title: "Bitset Optimallashtirish bilan Qism To'plam Yig'indisi",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Bit amallari'],
    description: "n ta musbat butun son (har biri 10^5 gacha) va maqsad yig'indi S (10^5 gacha) berilgan. Massivning biror qism to'plami aniq S yig'indiga erishishi mumkinligini aniqlang. Odatiy dinamik dasturlash O(n*S) xotira va vaqt talab qiladi; siz holatni bitlar to'plami (bitset) sifatida saqlab, har bir elementni qo'shishda butun holatni bitli siljitish va OR amali bilan yangilab, umumiy vaqtni O(n*S/64) ga tushiring. n 10^4, S 10^5 gacha.\n\n**1-misol:**\nKiritma: arr = [3,7,2,9], S = 11\nNatija: true\nIzoh: 2+9=11 yoki 3+... ekanligi sababli maqsad yig'indiga erishish mumkin.",
    starterCodeJs: 'function canReachSum(arr, S) {\n  // your code here\n}',
    starterCodePy: 'def can_reach_sum(arr, s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canReachSum(vector<int>& arr, int S) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-046',
    title: "Gauss Eliminatsiyasi: XOR Bazisining Rangini Aniqlash",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Bit amallari'],
    description: "n ta butun son berilgan. Ularning GF(2) maydoni ustidagi chiziqli qobig'ining (linear span) o'lchamini (rangini) toping — ya'ni sonlarni Gauss eliminatsiyasi (XOR bilan) yordamida soddalashtirib, chiziqli mustaqil bo'lgan sonlar sonini hisoblang. Shu rang bilan sonlar yordamida hosil qilinishi mumkin bo'lgan turli XOR qiymatlar sonini (2^rang) ham qaytaring. n 2×10^5 gacha, umumiy O(n log(maxVal)).\n\n**1-misol:**\nKiritma: arr = [1,2,3]\nNatija: rank=2, distinctValues=4\nIzoh: 3 = 1 XOR 2 bo'lgani uchun chiziqli mustaqil sonlar soni 2, hosil qilinadigan turli XOR qiymatlari 4 ta.",
    starterCodeJs: 'function xorBasisRank(arr) {\n  // your code here\n}',
    starterCodePy: 'def xor_basis_rank(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int xorBasisRank(vector<long long>& arr) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-047',
    title: "SOS Dinamik Dasturlash: Kichik To'plamlar Bo'yicha Yig'indi",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Bit amallari'],
    description: "2^n o'lchamli massiv f berilgan, har bir mask uchun g[mask] qiymatini hisoblang — bu qiymat mask ning barcha kichik to'plamlari (submask, bitwise ma'noda) bo'yicha f qiymatlarining yig'indisiga teng. Har bir mask va submask juftligini alohida tekshirish O(3^n) beradi; siz har bir bitni alohida ko'rib chiqadigan Sum over Subsets (SOS) dinamik dasturlash texnikasidan foydalanib, umumiy vaqt murakkabligini O(n * 2^n) ga tushiring. n 20 gacha.\n\n**1-misol:**\nKiritma: f = [1,2,3,4], n = 2\nNatija: [1,3,4,10]\nIzoh: g[3] (binary 11) = f[0]+f[1]+f[2]+f[3] = 1+2+3+4=10.",
    starterCodeJs: 'function sumOverSubsets(f, n) {\n  // your code here\n}',
    starterCodePy: 'def sum_over_subsets(f, n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> sumOverSubsets(vector<long long>& f, int n) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-048',
    title: "Cheklov Ostida Maksimal XOR: Trie Yondashuvi",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Bit amallari'],
    description: "n ta manfiy bo'lmagan butun son va q ta so'rov berilgan, har bir so'rov (val, limit) juftligidan iborat: massivdan tanlangan elementning val bilan XOR qiymati limit dan katta bo'lmagan holda maksimal bo'ladigan elementni toping. Sonlarni ikkilik trie ga joylashtirib, har bir tugunda shu tugun ostidagi elementlar sonini saqlab, har bir so'rovni chegara shartini hisobga olgan holda trie bo'ylab yurish orqali O(log(maxVal)) da javob bering. n, q soni 10^5 gacha.\n\n**1-misol:**\nKiritma: arr = [3,10,5,25], so'rov = (val=5, limit=15)\nNatija: 5\nIzoh: 5 XOR 5 = 0, 5 XOR 10 = 15 (limitga teng va ruxsat etilgan), eng yaxshi natija 10 elementi orqali 15 qiymatiga erishiladi.",
    starterCodeJs: 'function maxXorWithLimit(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def max_xor_with_limit(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> maxXorWithLimit(vector<int>& arr, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-049',
    title: "Bitmask Dinamik Dasturlash: Minimal To'plamlar Qoplamasi",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Bit amallari'],
    description: "n ta elementdan iborat universal to'plam (n 20 gacha) va m ta qism to'plam berilgan (har biri bitmask sifatida berilgan). Universal to'plamning barcha elementlarini qoplaydigan minimal sondagi qism to'plamlarni tanlang. dp[mask] — mask orqali ifodalangan qoplangan elementlar to'plamiga erishish uchun zarur bo'lgan minimal to'plamlar sonini saqlovchi dinamik dasturlashni har bir qism to'plam bilan yangilab, umumiy vaqt murakkabligi O(2^n * m) bo'lgan yechim yozing.\n\n**1-misol:**\nKiritma: n=4, subsets=[0b0011, 0b1100, 0b0110]\nNatija: 2\nIzoh: Birinchi va ikkinchi qism to'plamlar birlashib butun to'plamni (1111) qoplaydi, minimal soni 2.",
    starterCodeJs: 'function minSetCover(n, subsets) {\n  // your code here\n}',
    starterCodePy: 'def min_set_cover(n, subsets):\n    # your code here\n    pass',
    starterCodeCpp: 'int minSetCover(int n, vector<int>& subsets) {\n    // your code here\n}',
  },
  {
    key: 'expert-d-050',
    title: "Popcount Optimallashtirish bilan Bitmask Holatlarni Sanash",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Bit amallari'],
    description: "n ta o'yinchi va n ta jamoa o'rni berilgan (n 20 gacha), har bir o'yinchi faqat ma'lum o'rinlar to'plamiga mos keladi (bitmask bilan berilgan). Har bir o'yinchiga aniq bitta o'rin va har bir o'rinni aniq bitta o'yinchiga tayinlash mumkin bo'lgan usullar sonini (modul 10^9+7) hisoblang. dp[i][mask] — birinchi i ta o'yinchi mask orqali ifodalangan o'rinlarga tayinlangandagi usullar soni rekurrensiyasini popcount(mask) == i ekanligidan foydalanib bitta o'lchamli massivga siqib, umumiy O(n * 2^n) vaqt va xotira bilan yeching.\n\n**1-misol:**\nKiritma: n=3, playerMasks=[0b011, 0b101, 0b110]\nNatija: 2\nIzoh: Har bir o'yinchi mos o'rinlarga tayinlanadigan 2 xil to'liq mos yozishmalar mavjud.",
    starterCodeJs: 'function countAssignments(n, playerMasks) {\n  // your code here\n}',
    starterCodePy: 'def count_assignments(n, player_masks):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countAssignments(int n, vector<int>& playerMasks) {\n    // your code here\n}',
  },
];
