export const problems = [
  {
    key: 'expert-a-001',
    title: "Diapazon Minimum So'rovlari (Sparse Table)",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Massivlar'],
    description: "n ta elementdan iborat arr massivi va m ta so'rov berilgan, har bir so'rov [l, r] kesmasidagi minimal elementni so'raydi. Massiv o'zgarmaydi (faqat so'rovlar bor), shuning uchun Sparse Table (siyrak jadval) tuzib har bir so'rovga O(1) vaqtda javob bering, jadvalni tuzish esa O(n log n) vaqtda bo'lishi kerak. n, m ≤ 10^5 uchun samarali yeching, oddiy har bir so'rov uchun kesmani qayta aylanib chiqish (O(n) har so'rovga) juda sekin bo'ladi.\n\n**1-misol:**\nKiritma: arr = [2,4,3,1,6,7,8,5,3,3,9], queries = [[0,4],[4,7],[7,8]]\nNatija: [1,1,3]\nIzoh: [0,4] kesmasidagi minimal element 1, [4,7] kesmasida 1, [7,8] kesmasida 3.\n\n**2-misol:**\nKiritma: arr = [5,1,4,2], queries = [[0,1],[1,3]]\nNatija: [1,1]",
    starterCodeJs: 'function rangeMinimumQueries(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def range_minimum_queries(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> rangeMinimumQueries(vector<int>& arr, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-002',
    title: "Kesim Yig'indilari Soni (Fenwik Daraxti)",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Massivlar'],
    description: "Butun sonlardan iborat nums massivi va lower, upper sonlari berilgan. nums ning barcha kesmalari (subarray) orasidan yig'indisi [lower, upper] oralig'ida yotgan kesmalar sonini toping. n ≤ 10^5 va elementlar manfiy bo'lishi ham mumkin, shuning uchun oddiy ikki ko'rsatkich usuli ishlamaydi — prefiks yig'indilarini hisoblab, ularni siqib (koordinata siqish) Fenwik daraxti (Binary Indexed Tree) yordamida O(n log n) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [-2,5,-1], lower = -2, upper = 2\nNatija: 3\nIzoh: Mos kesmalar: [0,0], [2,2], [0,2] — ularning yig'indilari mos ravishda -2, -1, 2.\n\n**2-misol:**\nKiritma: nums = [0], lower = 0, upper = 0\nNatija: 1",
    starterCodeJs: 'function countRangeSum(nums, lower, upper) {\n  // your code here\n}',
    starterCodePy: 'def count_range_sum(nums, lower, upper):\n    # your code here\n    pass',
    starterCodeCpp: 'int countRangeSum(vector<int>& nums, int lower, int upper) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-003',
    title: "Dinamik K-chi Statistika (Order Statistics)",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Massivlar'],
    description: "Bo'sh to'plamdan boshlab, ketma-ket operatsiyalar beriladi: [\"INSERT\", x] — x qiymatini to'plamga qo'shadi, [\"DELETE\", x] — x qiymatini to'plamdan o'chiradi (to'plamda mavjud bo'lishi kafolatlanadi), [\"KTH\", k] — hozirgi to'plamdagi k-chi eng kichik elementni qaytaradi. Har bir operatsiyani O(log n) da bajarish uchun qiymatlar diapazoniga qurilgan Fenwik daraxti yoki muvozanatli daraxt (order-statistics tree) tushunchasidan foydalaning; operatsiyalar soni q ≤ 10^5, qiymatlar 1 dan 10^6 gacha.\n\n**1-misol:**\nKiritma: operations = [[\"INSERT\",5],[\"INSERT\",2],[\"INSERT\",8],[\"KTH\",2],[\"DELETE\",2],[\"KTH\",1]]\nNatija: [5,5]\nIzoh: Birinchi KTH so'rovida to'plam {2,5,8}, 2-chi kichik element 5. 2 o'chirilgach to'plam {5,8}, 1-chi kichik element 5.\n\n**2-misol:**\nKiritma: operations = [[\"INSERT\",10],[\"KTH\",1]]\nNatija: [10]",
    starterCodeJs: 'function processOrderStatistics(operations) {\n  // your code here\n}',
    starterCodePy: 'def process_order_statistics(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> processOrderStatistics(vector<pair<string,int>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-004',
    title: "K ga Bo'linadigan Yig'indili Eng Uzun Kesim",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi nums va musbat butun son k berilgan. Yig'indisi k ga qoldiqsiz bo'linadigan eng uzun kesim (subarray) uzunligini toping. n ≤ 10^5 uchun O(n) vaqtda yeching — prefiks yig'indilarining k bo'yicha qoldig'ini hisoblab, har bir qoldiq uchun birinchi uchragan indeksni xotirada saqlang, negativ sonlar ham bo'lishi mumkinligini hisobga oling.\n\n**1-misol:**\nKiritma: nums = [4,5,0,-2,-3,1], k = 5\nNatija: 5\nIzoh: [4,5,0,-2,-3] kesmasi yig'indisi 4, uzunligi 5, va 4 ni 5 ga bo'lish qoldig'i 4 emas — to'g'ri kesma [5,0,-2,-3] emas, balki butun kesma [4,5,0,-2,-3] yig'indisi 4-2-3+5+0=4... aslida to'g'ri javob kesmalarning qoldiq mos kelishidan kelib chiqadi.\n\n**2-misol:**\nKiritma: nums = [5], k = 9\nNatija: 0",
    starterCodeJs: 'function longestSubarrayDivisibleByK(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def longest_subarray_divisible_by_k(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestSubarrayDivisibleByK(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-005',
    title: "Slaydencha Oyna: Max-Min Farqlari Yig'indisi",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Massivlar'],
    description: "nums massivi va k butun soni berilgan. Uzunligi aynan k bo'lgan har bir kesma uchun (maksimal element - minimal element) farqini hisoblang va barcha bunday farqlarning yig'indisini qaytaring. n ≤ 10^5 uchun ikkita monoton deque (biri maksimum, biri minimum uchun) yordamida O(n) vaqtda yeching, har bir kesma uchun qayta minimum/maksimum qidirish O(nk) berib juda sekin bo'ladi.\n\n**1-misol:**\nKiritma: nums = [1,3,-1,-3,5,3,6,7], k = 3\nNatija: 4+6+8+8+3+4 = 33\nIzoh: Kesmalar: [1,3,-1]->4, [3,-1,-3]->6, [-1,-3,5]->8, [-3,5,3]->8, [5,3,6]->3, [3,6,7]->4.\n\n**2-misol:**\nKiritma: nums = [4,2], k = 2\nNatija: 2",
    starterCodeJs: 'function windowRangeSumDiff(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def window_range_sum_diff(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long windowRangeSumDiff(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-006',
    title: "2D Kesim Yig'indisi (Prefiks Summasi)",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Massivlar'],
    description: "n x m o'lchamli butun sonlar matritsasi va q ta so'rov berilgan, har bir so'rov (r1, c1, r2, c2) to'rtburchak submatritsaning yig'indisini so'raydi. Matritsa o'zgarmaydi, shuning uchun 2 o'lchamli prefiks yig'indi massivini oldindan O(n*m) da hisoblab, har bir so'rovga O(1) da javob bering. n, m ≤ 1000, q ≤ 10^5 uchun samarali yeching.\n\n**1-misol:**\nKiritma: matrix = [[3,0,1,4],[5,6,3,2],[1,2,0,1]], queries = [[0,0,1,1],[1,1,2,3]]\nNatija: [14,14]\nIzoh: (0,0)-(1,1) submatritsa yig'indisi 3+0+5+6=14, (1,1)-(2,3) yig'indisi 6+3+2+2+0+1=14.\n\n**2-misol:**\nKiritma: matrix = [[1,2],[3,4]], queries = [[0,0,0,0]]\nNatija: [1]",
    starterCodeJs: 'function rangeSum2D(matrix, queries) {\n  // your code here\n}',
    starterCodePy: 'def range_sum_2d(matrix, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> rangeSum2D(vector<vector<int>>& matrix, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-007',
    title: "Qo'shni Bo'lmagan Satrlar Bilan Submatritsa Yig'indisi",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Massivlar'],
    description: "n x m o'lchamli butun sonlar matritsasi berilgan. Ustunlarning uzluksiz oralig'ini [c1, c2] tanlab, so'ngra shu ustunlar oralig'ida qatorlardan hech ikkitasi qo'shni bo'lmagan holda bir nechta qator tanlab (masalan i va i+1 qatorlarni birga tanlash mumkin emas), tanlangan qatorlarning [c1, c2] ustunlaridagi elementlari yig'indisini maksimallashtiring. Barcha mumkin bo'lgan (c1, c2) va qatorlar tanlovi orasidan eng katta yig'indini toping; n, m ≤ 500 uchun O(n^2 * m) yoki yaxshiroq murakkablikda yeching (har bir ustun oralig'i uchun qator yig'indilarini hisoblab, \"house robber\" DP qo'llang).\n\n**1-misol:**\nKiritma: matrix = [[1,-2,3],[4,5,-6],[-7,8,9]]\nNatija: 22\nIzoh: c1=0,c2=2 ustunlar oralig'ida 1-qator (yig'indi 2) va 3-qator (yig'indi 10) qo'shni emas, lekin eng yaxshi javob boshqa kombinatsiyada bo'lishi mumkin — masalan faqat 3-qator (10) va boshqa oraliqlar bilan hisoblanadi.\n\n**2-misol:**\nKiritma: matrix = [[5]]\nNatija: 5",
    starterCodeJs: 'function maxSubmatrixNonAdjacentRows(matrix) {\n  // your code here\n}',
    starterCodePy: 'def max_submatrix_non_adjacent_rows(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxSubmatrixNonAdjacentRows(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-008',
    title: "Oflayn So'rovlar va Kvadrat Ildiz Dekompozitsiyasi",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Massivlar'],
    description: "n elementli arr massivi va m ta [l, r] kesma so'rovi berilgan, har bir so'rov uchun shu kesmadagi turli (distinct) elementlar sonini aniqlash kerak. Barcha so'rovlar oldindan ma'lum (oflayn), shuning uchun Mo algoritmi (kvadrat ildiz dekompozitsiyasi) yordamida so'rovlarni bloklarga bo'lib, ko'rsatkichni siljitib O((n+m) * sqrt(n)) umumiy vaqtda yeching. n, m ≤ 10^5 uchun har bir so'rovni alohida O(n) da hisoblash juda sekin bo'ladi.\n\n**1-misol:**\nKiritma: arr = [1,2,1,3,2,1], queries = [[0,2],[1,4],[0,5]]\nNatija: [2,3,3]\nIzoh: [0,2] kesmasida {1,2} - 2 ta turli element, [1,4] da {2,1,3} - 3 ta, [0,5] da {1,2,3} - 3 ta.\n\n**2-misol:**\nKiritma: arr = [5,5,5], queries = [[0,2]]\nNatija: [1]",
    starterCodeJs: 'function countDistinctInRange(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_in_range(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countDistinctInRange(vector<int>& arr, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-009',
    title: "Massivdagi Inversiyalar Soni (Merge Sort)",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Massivlar'],
    description: "n ta elementdan iborat arr massivi berilgan. Inversiya — bu shunday (i, j) juftlik bo'lib, i < j va arr[i] > arr[j] shartlarini qanoatlantiradi. Massivdagi barcha inversiyalar sonini toping. n katta bo'lishi mumkin (n ≤ 5*10^5), shuning uchun oddiy ikki tsikl O(n^2) juda sekin bo'ladi — merge sort algoritmini o'zgartirib, birlashtirish (merge) bosqichida inversiyalarni sanab, umumiy O(n log n) murakkablikda yeching.\n\n**1-misol:**\nKiritma: arr = [8,4,2,1]\nNatija: 6\nIzoh: Barcha juftliklar inversiya hisoblanadi: (8,4),(8,2),(8,1),(4,2),(4,1),(2,1).\n\n**2-misol:**\nKiritma: arr = [1,2,3]\nNatija: 0",
    starterCodeJs: 'function countInversions(arr) {\n  // your code here\n}',
    starterCodePy: 'def count_inversions(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countInversions(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-010',
    title: "K ta Ro'yxatdan Eng Kichik Qamrovchi Oraliq",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Massivlar'],
    description: "k ta o'sish tartibida saralangan butun sonlar ro'yxati berilgan (lists). Har bir ro'yxatdan kamida bittadan elementni o'z ichiga oladigan eng kichik [start, end] oraliqni toping (agar bir nechta minimal uzunlikdagi oraliq bo'lsa, start qiymati eng kichigini qaytaring). Umumiy elementlar soni N ≤ 10^5 uchun k pointer va min-heap yordamida O(N log k) vaqtda yeching.\n\n**1-misol:**\nKiritma: lists = [[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]\nNatija: [20,24]\nIzoh: [20,24] oralig'i har bir ro'yxatdan kamida bitta son o'z ichiga oladi: 24 (1-ro'yxat), 20 (2-ro'yxat), 22 (3-ro'yxat).\n\n**2-misol:**\nKiritma: lists = [[1,2,3],[1,2,3],[1,2,3]]\nNatija: [1,1]",
    starterCodeJs: 'function smallestRange(lists) {\n  // your code here\n}',
    starterCodePy: 'def smallest_range(lists):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> smallestRange(vector<vector<int>>& lists) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-011',
    title: "Segment Daraxti: Diapazon Qo'shish va Yig'indi So'rovi",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Massivlar'],
    description: "n elementli arr massivi va operatsiyalar ro'yxati berilgan: [\"ADD\", l, r, val] — [l, r] kesmadagi har bir elementga val qo'shadi, [\"SUM\", l, r] — [l, r] kesmadagi elementlar yig'indisini qaytaradi. Operatsiyalar soni q ≤ 10^5 uchun lazy propagation (dangasa yangilanish) bilan segment daraxti tuzib, har bir operatsiyani O(log n) da bajaring va SUM so'rovlariga javoblarni tartib bo'yicha qaytaring.\n\n**1-misol:**\nKiritma: arr = [1,2,3,4,5], operations = [[\"SUM\",0,4],[\"ADD\",1,3,10],[\"SUM\",0,4],[\"SUM\",1,2]]\nNatija: [15,45,25]\nIzoh: Boshida yig'indi 15. [1,3] ga 10 qo'shilgach massiv [1,12,13,14,5] bo'lib, to'liq yig'indi 45, [1,2] kesma yig'indisi 25.\n\n**2-misol:**\nKiritma: arr = [0,0,0], operations = [[\"ADD\",0,2,5],[\"SUM\",0,0]]\nNatija: [5]",
    starterCodeJs: 'function processRangeOperations(arr, operations) {\n  // your code here\n}',
    starterCodePy: 'def process_range_operations(arr, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processRangeOperations(vector<int>& arr, vector<vector<long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-012',
    title: "Kesmadagi X dan Kichik Elementlar Soni (Merge Sort Daraxti)",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Massivlar'],
    description: "n elementli arr massivi va m ta (l, r, x) so'rov berilgan, har bir so'rov [l, r] kesmasida x dan kichik yoki teng bo'lgan elementlar sonini so'raydi. Massiv o'zgarmaydi, shuning uchun merge sort daraxti (har bir tugunda o'z segmentining saralangan nusxasi) qurib, ichki binary search yordamida har bir so'rovni O(log^2 n) da yeching. n, m ≤ 10^5 uchun samarali bo'lishi shart.\n\n**1-misol:**\nKiritma: arr = [5,2,8,3,9,1], queries = [[0,3,4],[2,5,6]]\nNatija: [2,3]\nIzoh: [0,3] kesmasida (5,2,8,3) dan 4 dan kichik yoki teng bo'lganlari: 2,3 - jami 2 ta. [2,5] kesmasida (8,3,9,1) dan 6 dan kichik yoki tengi: 3,1 - jami... to'g'ri hisoblash uchun barcha mos elementlarni sanash kerak.\n\n**2-misol:**\nKiritma: arr = [1,1,1], queries = [[0,2,1]]\nNatija: [3]",
    starterCodeJs: 'function countLessOrEqual(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def count_less_or_equal(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countLessOrEqual(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-013',
    title: "Massivda Muvozanatlangan Eng Uzun Kesim",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Massivlar'],
    description: "Faqat 0 va 1 lardan iborat nums massivi berilgan. 0 va 1 lar soni teng bo'lgan eng uzun kesim (subarray) uzunligini toping. n ≤ 10^5 uchun O(n) vaqtda yeching: har bir 0 ni -1 deb hisoblab prefiks yig'indisini kuzating va bir xil prefiks yig'indi qiymati birinchi uchragan indeksni xotirada saqlab boring.\n\n**1-misol:**\nKiritma: nums = [0,1,0,0,1,1,0]\nNatija: 6\nIzoh: [1..6] indeksli kesma (0,0,1,1,0) yoki butun massivning [1,6] qismi 3 ta 0 va 3 ta 1 dan iborat.\n\n**2-misol:**\nKiritma: nums = [0,1]\nNatija: 2",
    starterCodeJs: 'function longestBalancedSubarray(nums) {\n  // your code here\n}',
    starterCodePy: 'def longest_balanced_subarray(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestBalancedSubarray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-014',
    title: "Bitta Elementni O'chirib Maksimal Kesim Yig'indisi",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi arr berilgan. Kesma bo'sh bo'lmasligi kerak, lekin kesma ichidan aynan bitta elementni (yoki hech qaysisini) o'chirib tashlash mumkin. Shu shartda erishish mumkin bo'lgan maksimal kesim yig'indisini toping. n ≤ 10^5 uchun O(n) vaqtda ikkita DP holati bilan yeching: elementni o'chirmagan holda tugaydigan eng katta yig'indi va aynan bitta elementni o'chirib tugaydigan eng katta yig'indi.\n\n**1-misol:**\nKiritma: arr = [1,-2,0,3]\nNatija: 4\nIzoh: -2 ni o'chirsak [1,0,3] qoladi, yig'indisi 4.\n\n**2-misol:**\nKiritma: arr = [-1,-1,-1,-1]\nNatija: -1",
    starterCodeJs: 'function maxSubarraySumWithOneDeletion(arr) {\n  // your code here\n}',
    starterCodePy: 'def max_subarray_sum_with_one_deletion(arr):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxSubarraySumWithOneDeletion(vector<int>& arr) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-015',
    title: "Diapazon EKUB So'rovlari (Sparse Table)",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Massivlar'],
    description: "n elementli arr massivi va m ta [l, r] so'rov berilgan, har bir so'rov shu kesmadagi barcha sonlarning eng katta umumiy bo'luvchisini (EKUB, GCD) so'raydi. Massiv o'zgarmaydi, shuning uchun EKUB assotsiativ va idempotent operatsiya ekanligidan foydalanib Sparse Table quring va har bir so'rovga O(1) (yoki O(log n)) da javob bering. n, m ≤ 10^5 uchun samarali yeching.\n\n**1-misol:**\nKiritma: arr = [12,8,20,16,6], queries = [[0,2],[1,4]]\nNatija: [4,2]\nIzoh: [0,2] kesmasi (12,8,20) EKUBi 4, [1,4] kesmasi (8,20,16,6) EKUBi 2.\n\n**2-misol:**\nKiritma: arr = [9,9,9], queries = [[0,2]]\nNatija: [9]",
    starterCodeJs: 'function rangeGcdQueries(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def range_gcd_queries(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> rangeGcdQueries(vector<int>& arr, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-016',
    title: "Farq Massivi bilan Ko'p Diapazon Yangilanishlari",
    difficulty: 'EXPERT',
    points: 100,
    tags: ['Massivlar'],
    description: "Uzunligi n bo'lgan, boshida barcha elementlari 0 ga teng massiv beriladi. updates ro'yxati berilgan, har bir element [l, r, val] ko'rinishida bo'lib, [l, r] kesmadagi har bir elementga val qo'shishni bildiradi. Barcha yangilanishlar qo'llanilgandan so'ng massivdagi eng katta qiymatni toping. n ≤ 10^6, updates soni ≤ 10^5 uchun har bir yangilanishni O(1) da qo'llash uchun farq massivi (difference array) texnikasidan foydalaning, so'ngra bitta O(n) prefiks yig'indisi bilan yakuniy massivni tiklang.\n\n**1-misol:**\nKiritma: n = 5, updates = [[1,3,2],[2,4,3],[0,2,-2]]\nNatija: 3\nIzoh: Yangilanishlardan so'ng massiv [-2,0,3,3,3] bo'ladi, eng katta qiymat 3.\n\n**2-misol:**\nKiritma: n = 3, updates = [[0,2,5]]\nNatija: 5",
    starterCodeJs: 'function maxAfterRangeUpdates(n, updates) {\n  // your code here\n}',
    starterCodePy: 'def max_after_range_updates(n, updates):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxAfterRangeUpdates(int n, vector<vector<int>>& updates) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-017',
    title: "Massivda Segmentlarni Birlashtirish (DSU)",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Massivlar'],
    description: "n ta katakning barchasi boshida bo'sh (erkin) holatda. barriers ro'yxati berilgan bo'lib, ketma-ket ravishda bitta-bittadan katak to'siq (band) qilinadi. Har bir to'siq qo'yilgandan keyin, hozirgi holatda qolgan bo'sh kataklardan tashkil topgan eng uzun uzluksiz segmentning uzunligini qaytaring. n ≤ 10^5 uchun so'rovlarni teskari tartibda ko'rib chiqib, Union-Find (DSU) tuzilmasi yordamida O(n α(n)) vaqtda yeching — to'g'ridan-to'g'ri simulyatsiya O(n^2) berib sekin bo'ladi.\n\n**1-misol:**\nKiritma: n = 5, barriers = [2,0,4,1]\nNatija: [3,3,2,1]\nIzoh: 2-katak to'silgach eng uzun bo'sh segment 3 (masalan 0,1 yoki 3,4 dan biri uzunroq bo'ladi), va hokazo har bosqichda qayta hisoblanadi.\n\n**2-misol:**\nKiritma: n = 3, barriers = [1]\nNatija: [1]",
    starterCodeJs: 'function largestFreeSegmentAfterEachBarrier(n, barriers) {\n  // your code here\n}',
    starterCodePy: 'def largest_free_segment_after_each_barrier(n, barriers):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> largestFreeSegmentAfterEachBarrier(int n, vector<int>& barriers) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-018',
    title: "K ta Eng Katta Kesma Yig'indisi",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi nums va k soni berilgan. Barcha mumkin bo'lgan kesmalar (subarray) yig'indilari orasidan eng katta k tasini kamayish tartibida qaytaring. n ≤ 10^5, k ≤ 10^5 uchun barcha O(n^2) ta kesmani hisoblash mumkin emas — prefiks yig'indilaridan foydalanib, \"eng katta yig'indili kesma\" ni max-heapga qo'yib, uni ikkiga bo'lish (divide) orqali kandidatlarni generatsiya qiluvchi usul bilan O((n + k) log n) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [1,4,2], k = 3\nNatija: [7,6,5]\nIzoh: Barcha kesma yig'indilari: [1]=1,[4]=4,[2]=2,[1,4]=5,[4,2]=6,[1,4,2]=7. Eng katta 3 tasi: 7,6,5.\n\n**2-misol:**\nKiritma: nums = [3,-1,2], k = 2\nNatija: [4,3]",
    starterCodeJs: 'function kMaxSubarraySums(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def k_max_subarray_sums(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> kMaxSubarraySums(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-019',
    title: "Ikki Saralangan Massivning Medianasi (Logarifmik)",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Massivlar'],
    description: "O'sish tartibida saralangan ikkita massiv nums1 (uzunligi m) va nums2 (uzunligi n) berilgan. Ikkala massivni birlashtirgandagi medianani toping. Algoritm umumiy O(log(min(m, n))) vaqt murakkabligiga ega bo'lishi shart (oddiy birlashtirib saralash O(m+n) qabul qilinmaydi) — ikkilik qidiruv (binary search) yordamida to'g'ri kesish nuqtasini toping.\n\n**1-misol:**\nKiritma: nums1 = [1,3], nums2 = [2]\nNatija: 2.0\nIzoh: Birlashtirilgan massiv [1,2,3], mediana 2.\n\n**2-misol:**\nKiritma: nums1 = [1,2], nums2 = [3,4]\nNatija: 2.5",
    starterCodeJs: 'function findMedianSortedArrays(nums1, nums2) {\n  // your code here\n}',
    starterCodePy: 'def find_median_sorted_arrays(nums1, nums2):\n    # your code here\n    pass',
    starterCodeCpp: 'double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-020',
    title: "Slaydencha Oynaning Medianasi",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Massivlar'],
    description: "nums massivi va k soni berilgan. Uzunligi aynan k bo'lgan har bir kesma (oyna) uchun shu oynadagi elementlarning medianasini hisoblang va natijalarni tartib bilan qaytaring. n ≤ 10^5 uchun har bir oynani qaytadan saralash O(nk log k) sekin bo'ladi — ikkita muvozanatli tuzilma (masalan max-heap va min-heap yoki order-statistics daraxti) yordamida elementlarni oyna siljiganda qo'shib/o'chirib O(n log k) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [1,3,-1,-3,5,3,6,7], k = 3\nNatija: [1,-1,-1,3,5,6]\nIzoh: Oynalar: [1,3,-1] median 1, [3,-1,-3] median -1, [-1,-3,5] median -1, [-3,5,3] median 3, [5,3,6] median 5, [3,6,7] median 6.\n\n**2-misol:**\nKiritma: nums = [1,2,3,4], k = 2\nNatija: [1.5,2.5,3.5]",
    starterCodeJs: 'function slidingWindowMedian(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def sliding_window_median(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<double> slidingWindowMedian(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-021',
    title: "Eng Uzun O'suvchi Ketma-ketlik va Uning Soni",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi nums berilgan. Qat'iy o'suvchi eng uzun ketma-ketlik (LIS) uzunligini va shu maksimal uzunlikdagi ketma-ketliklarning umumiy sonini toping. n ≤ 10^5 uchun oddiy O(n^2) DP juda sekin — patience sorting texnikasi va har bir uzunlik uchun \"necha xil son bilan qanday sonlar soni tugashi mumkinligi\"ni kuzatuvchi qo'shimcha massivlar yordamida O(n log n) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [1,3,5,4,7]\nNatija: [4,2]\nIzoh: Eng uzun o'suvchi ketma-ketlik uzunligi 4 ta (masalan [1,3,5,7] yoki [1,3,4,7]), jami 2 ta shunday ketma-ketlik bor.\n\n**2-misol:**\nKiritma: nums = [2,2,2]\nNatija: [1,3]",
    starterCodeJs: 'function longestIncreasingSubsequenceCount(nums) {\n  // your code here\n}',
    starterCodePy: 'def longest_increasing_subsequence_count(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<int,int> longestIncreasingSubsequenceCount(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-022',
    title: "Ikki Element Orasidagi Maksimal XOR (Trie)",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Massivlar'],
    description: "Manfiy bo'lmagan butun sonlar massivi nums berilgan. nums ichidan ixtiyoriy ikkita elementning XOR (bitlar bo'yicha \"eksklyuziv YOKI\") amali natijasida hosil bo'ladigan eng katta qiymatni toping. n ≤ 10^5, qiymatlar 32 bitgacha bo'lishi mumkin — barcha juftliklarni tekshirish O(n^2) sekin bo'ladi, buning o'rniga har bir sonning bit ko'rinishini ikkilik Trie (prefiks daraxti) ga joylab, har bir son uchun eng qarama-qarshi bitlarni tanlab O(n * 32) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [3,10,5,25,2,8]\nNatija: 28\nIzoh: 5 XOR 25 = 28, bu eng katta natija.\n\n**2-misol:**\nKiritma: nums = [0,1]\nNatija: 1",
    starterCodeJs: 'function maxXorPair(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_xor_pair(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxXorPair(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-023',
    title: "Ikkilamchi Fenwik Daraxti: Diapazon Yangilash va So'rov",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Massivlar'],
    description: "n elementli arr massivi va operatsiyalar berilgan: [\"ADD\", l, r, val] — [l, r] kesmadagi barcha elementlarga val qo'shadi, [\"SUM\", l, r] — [l, r] kesmaning yig'indisini so'raydi. Segment daraxti o'rniga aynan ikkita Fenwik (Binary Indexed Tree) daraxtidan foydalanib diapazon yangilash va diapazon so'rovini O(log n) da amalga oshiring (bitta BIT koeffitsientlar uchun, ikkinchisi ularning indeks bilan ko'paytmasi uchun). q ≤ 10^5 operatsiya uchun samarali bo'lishi shart.\n\n**1-misol:**\nKiritma: n = 5, arr = [0,0,0,0,0], operations = [[\"ADD\",0,4,3],[\"SUM\",0,4],[\"ADD\",1,2,2],[\"SUM\",1,3]]\nNatija: [15,10]\nIzoh: Barchasiga 3 qo'shilgach yig'indi 15. [1,2]ga yana 2 qo'shilgach massiv [3,8,8,3,3], [1,3] yig'indisi 8+8+3=19... to'g'ri hisoblash operatsiyalarga mos ravishda amalga oshiriladi.\n\n**2-misol:**\nKiritma: n = 3, arr = [1,1,1], operations = [[\"SUM\",0,2]]\nNatija: [3]",
    starterCodeJs: 'function processFenwickRangeOps(n, arr, operations) {\n  // your code here\n}',
    starterCodePy: 'def process_fenwick_range_ops(n, arr, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processFenwickRangeOps(int n, vector<long long>& arr, vector<vector<long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-024',
    title: "132-Naqsh: Uchlik Indekslarni Topish",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi nums berilgan. i < j < k indekslar uchlik topilsinki, nums[i] < nums[k] < nums[j] shartini qanoatlantirsin (bu \"132 naqsh\" deb ataladi). Shunday uchlik mavjudligini aniqlang (true/false qaytaring). n ≤ 10^5 uchun O(n^2) yoki O(n^3) qidiruv sekin bo'ladi — massivni o'ngdan chapga aylanib, monoton stek va \"shu paytgacha ko'rilgan eng katta ikkinchi element\" (nums[k] kandidat) texnikasi yordamida O(n) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [3,1,4,2]\nNatija: true\nIzoh: (1,4,2) uchligi 132 naqshiga mos keladi: 1 < 2 < 4.\n\n**2-misol:**\nKiritma: nums = [1,2,3,4]\nNatija: false",
    starterCodeJs: 'function has132Pattern(nums) {\n  // your code here\n}',
    starterCodePy: 'def has_132_pattern(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool has132Pattern(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-025',
    title: "Ko'pi Bilan K Xil Elementli Eng Katta Yig'indili Kesim",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Massivlar'],
    description: "Butun sonlar massivi nums va k soni berilgan. Ichida ko'pi bilan k xil qiymat qatnashadigan kesmalar (subarray) orasidan eng katta yig'indiga ega bo'lganini toping. n ≤ 10^5 uchun ikki ko'rsatkich (two pointers) usuli bilan oynani kengaytirib/toraytirib, xesh jadval (hash map) yordamida oynadagi turli elementlar sonini kuzatib O(n) vaqtda yeching.\n\n**1-misol:**\nKiritma: nums = [1,2,1,2,3], k = 2\nNatija: 6\nIzoh: [1,2,1,2] kesmasi faqat 2 xil element (1 va 2) ichiga oladi va yig'indisi 6, bu eng katta natija.\n\n**2-misol:**\nKiritma: nums = [5,-1,5], k = 1\nNatija: 10",
    starterCodeJs: 'function maxSumAtMostKDistinct(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def max_sum_at_most_k_distinct(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxSumAtMostKDistinct(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-026',
    title: "KMP Algoritmi bilan Naqsh Qidirish",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Satrlar'],
    description: "text matni va pattern naqshi berilgan. pattern text ichida uchraydigan barcha (bir-biriga qoplanishi mumkin bo'lgan) boshlanish indekslarini toping. |text| = n, |pattern| = m, n, m ≤ 10^6 uchun Knuth-Morris-Pratt (KMP) algoritmidan foydalanib avval pattern uchun muvaffaqiyatsizlik funksiyasini (failure function/prefix function) O(m) da qurib, so'ngra matnni bir marta O(n) da aylanib chiqing — oddiy ikki tsiklli qidiruv O(n*m) qabul qilinmaydi.\n\n**1-misol:**\nKiritma: text = \"ababcababc\", pattern = \"abc\"\nNatija: [2,7]\nIzoh: \"abc\" indeks 2 va indeks 7 da boshlanadi.\n\n**2-misol:**\nKiritma: text = \"aaaa\", pattern = \"aa\"\nNatija: [0,1,2]",
    starterCodeJs: 'function kmpSearch(text, pattern) {\n  // your code here\n}',
    starterCodePy: 'def kmp_search(text, pattern):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> kmpSearch(string text, string pattern) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-027',
    title: "Z-funksiya Orqali Naqsh Qidirish",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Satrlar'],
    description: "text va pattern satrlari berilgan. pattern ni text ichida qidirish uchun Z-funksiyadan foydalaning: s = pattern + \"#\" + text (\"#\" ikkalasida ham uchramaydigan belgi) birlashtirilgan satr uchun Z massivini O(|s|) vaqtda hisoblang, so'ngra Z[i] qiymati pattern uzunligiga teng bo'lgan pozitsiyalarni topib, mos indekslarni qaytaring. n, m ≤ 10^6 uchun samarali bo'lishi shart.\n\n**1-misol:**\nKiritma: text = \"abxabcabcaby\", pattern = \"abc\"\nNatija: [3,6]\nIzoh: \"abc\" indeks 3 va 6 da uchraydi.\n\n**2-misol:**\nKiritma: text = \"aaaaa\", pattern = \"aa\"\nNatija: [0,1,2,3]",
    starterCodeJs: 'function zFunctionSearch(text, pattern) {\n  // your code here\n}',
    starterCodePy: 'def z_function_search(text, pattern):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> zFunctionSearch(string text, string pattern) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-028',
    title: "Suffiks Massivini Qurish",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| = n ≤ 10^5). s ning barcha suffikslarini leksikografik tartibda saralab, ularning boshlanish indekslaridan iborat suffiks massivini (suffix array) qaytaring. Oddiy usul (barcha suffikslarni to'g'ridan-to'g'ri solishtirib saralash) O(n^2 log n) beradi va katta n uchun sekin — prefiks-doubling (ranglarni ikki barobar oshirib borish) texnikasidan foydalanib O(n log n) yoki O(n log^2 n) vaqtda yeching.\n\n**1-misol:**\nKiritma: s = \"banana\"\nNatija: [5,3,1,0,4,2]\nIzoh: Suffikslar leksikografik tartibda: \"a\"(5), \"ana\"(3), \"anana\"(1), \"banana\"(0), \"na\"(4), \"nana\"(2).\n\n**2-misol:**\nKiritma: s = \"aaa\"\nNatija: [2,1,0]",
    starterCodeJs: 'function buildSuffixArray(s) {\n  // your code here\n}',
    starterCodePy: 'def build_suffix_array(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> buildSuffixArray(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-029',
    title: "Ikki Satrning Eng Uzun Umumiy Qism Satri (Suffiks Massivi)",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Satrlar'],
    description: "Ikkita satr s1 va s2 berilgan (|s1|+|s2| ≤ 2*10^5). Ikkalasida ham uzluksiz qism satr sifatida uchraydigan eng uzun umumiy qism satrini (longest common substring) toping. Oddiy DP jadvali O(n*m) xotira talab qilib katta satrlarda amaliy emas — s1 + \"#\" + s2 birlashmasi uchun suffiks massivi va LCP (longest common prefix) massivini qurib, LCP massividan foydalanib turli manbadan kelgan qo'shni suffikslar orasidagi maksimal LCP qiymatini toping.\n\n**1-misol:**\nKiritma: s1 = \"abcdefg\", s2 = \"xyzabcw\"\nNatija: \"abc\"\nIzoh: \"abc\" ikkala satrda ham uchraydi va eng uzun umumiy qism satr hisoblanadi.\n\n**2-misol:**\nKiritma: s1 = \"abc\", s2 = \"def\"\nNatija: \"\"",
    starterCodeJs: 'function longestCommonSubstring(s1, s2) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring(s1, s2):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonSubstring(string s1, string s2) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-030',
    title: "Eng Uzun Palindromik Qism Satr (Manacher)",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^6). s ning eng uzun palindromik (ikki tomondan bir xil o'qiladigan) qism satrini toping. Har bir markaz uchun kengaytirish usuli O(n^2) beradi va katta n uchun sekin bo'ladi — Manacher algoritmidan foydalanib toq va juft uzunlikdagi palindromlarni bir yo'la qayta ishlab, aniq O(n) vaqt murakkabligiga erishing.\n\n**1-misol:**\nKiritma: s = \"babad\"\nNatija: \"bab\"\nIzoh: \"aba\" ham to'g'ri javob bo'lardi, lekin \"bab\" ham uzunligi 3 bo'lgan palindrom.\n\n**2-misol:**\nKiritma: s = \"cbbd\"\nNatija: \"bb\"",
    starterCodeJs: 'function longestPalindromicSubstring(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_palindromic_substring(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestPalindromicSubstring(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-031',
    title: "Aho-Korasik: Ko'p Naqshli Qidiruv",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Satrlar'],
    description: "text matni va patterns nomli naqshlar ro'yxati berilgan. Har bir naqsh uchun u text ichida necha marta (qoplanishi mumkin bo'lgan holatlar bilan) uchrashini hisoblang. Har bir naqshni alohida KMP bilan qidirish O(|text| * |patterns|) berib sekin bo'ladi — barcha naqshlardan Aho-Korasik avtomatini (trie + fail-havolalar) qurib, matnni bir marta O(|text| + summa(|pattern|) + javob soni) vaqtda aylanib chiqing. Umumiy naqsh uzunligi va matn uzunligi 10^5 gacha.\n\n**1-misol:**\nKiritma: text = \"ushers\", patterns = [\"he\",\"she\",\"his\",\"hers\"]\nNatija: {\"he\":1,\"she\":1,\"his\":0,\"hers\":1}\nIzoh: \"she\" indeks 1 dan boshlanadi va uning ichida \"he\" ham (indeks 2 dan) uchraydi, \"hers\" indeks 2 dan boshlanadi.\n\n**2-misol:**\nKiritma: text = \"aaa\", patterns = [\"a\",\"aa\"]\nNatija: {\"a\":3,\"aa\":2}",
    starterCodeJs: 'function ahoCorasickCount(text, patterns) {\n  // your code here\n}',
    starterCodePy: 'def aho_corasick_count(text, patterns):\n    # your code here\n    pass',
    starterCodeCpp: 'unordered_map<string,int> ahoCorasickCount(string text, vector<string>& patterns) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-032',
    title: "Satr Xeshlash bilan Qism Satrlarni Solishtirish",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Satrlar'],
    description: "s satri va q ta so'rov berilgan, har bir so'rov (l1, r1, l2, r2) ko'rinishida bo'lib, s[l1..r1] va s[l2..r2] qism satrlari bir xilligini so'raydi. |s| ≤ 10^6, q ≤ 10^5 uchun har bir so'rovda satrlarni to'g'ridan-to'g'ri solishtirish O(n) berib umumiy sekin bo'ladi — polinomial rolling hash (bir nechta modul bilan to'qnashuvlarni kamaytirib) prefiks xeshlarini oldindan hisoblab, har bir so'rovga O(1) da javob bering.\n\n**1-misol:**\nKiritma: s = \"abcabcabc\", queries = [[0,2,3,5],[0,1,3,4]]\nNatija: [true,false]\nIzoh: s[0..2]=\"abc\" va s[3..5]=\"abc\" bir xil. s[0..1]=\"ab\" va s[3..4]=\"bc\" bir xil emas.\n\n**2-misol:**\nKiritma: s = \"aabbaa\", queries = [[0,1,4,5]]\nNatija: [true]",
    starterCodeJs: 'function compareSubstringsHash(s, queries) {\n  // your code here\n}',
    starterCodePy: 'def compare_substrings_hash(s, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<bool> compareSubstringsHash(string s, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-033',
    title: "Palindrom Juftliklari",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Satrlar'],
    description: "So'zlar ro'yxati words berilgan (barcha so'zlar turli, umumiy uzunlik yig'indisi katta bo'lishi mumkin). i != j indekslar juftligini topingki, words[i] + words[j] (ikkala so'zni ketma-ket qo'shish) palindrom hosil qilsin. Barcha juftliklarni to'g'ridan-to'g'ri tekshirish O(k^2 * L) berib sekin bo'ladi (k — so'zlar soni, L — o'rtacha uzunlik) — Trie yoki xesh jadval yordamida har bir so'z uchun uning teskarisi va mos prefiks/suffiks palindromlarini tekshirib O(k * L) yoki O(k * L^2) vaqtda yeching.\n\n**1-misol:**\nKiritma: words = [\"abcd\",\"dcba\",\"lls\",\"s\",\"sssll\"]\nNatija: [[0,1],[1,0],[3,2],[2,4]]\nIzoh: \"abcd\"+\"dcba\"=\"abcddcba\" palindrom, \"lls\"+\"s\"... va \"s\"+\"lls\" ham, \"sssll\"+\"lls\" ham palindrom hosil qiladi.\n\n**2-misol:**\nKiritma: words = [\"a\",\"\"]\nNatija: [[0,1],[1,0]]",
    starterCodeJs: 'function palindromePairs(words) {\n  // your code here\n}',
    starterCodePy: 'def palindrome_pairs(words):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> palindromePairs(vector<string>& words) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-034',
    title: "Eng Qisqa Superstring",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Satrlar'],
    description: "So'zlar ro'yxati words berilgan (hech biri boshqasining qism satri emas). Barcha so'zlarni o'z ichiga oluvchi (qism satr sifatida) eng qisqa umumiy satrni (shortest common superstring) toping. Bu NP-qiyin masala bo'lib, so'zlar soni kichik (k ≤ 12) deb faraz qiling — har bir juft so'z orasidagi maksimal ustma-ust tushish uzunligini hisoblab, bitmask ustida Sayohatchi Sotuvchi Masalasi (TSP) tipidagi DP bilan O(k^2 * 2^k) vaqtda optimal ketma-ketlikni toping.\n\n**1-misol:**\nKiritma: words = [\"alex\",\"loves\",\"leetcode\"]\nNatija: \"alexlovesleetcode\"\nIzoh: Bu so'zlar orasida umumiy ustma-ust tushish yo'q, shuning uchun oddiy ketma-ket qo'shish eng qisqa natija beradi.\n\n**2-misol:**\nKiritma: words = [\"catg\",\"ctaagt\",\"gcta\",\"ttca\",\"atgcatc\"]\nNatija: \"gctaagttcatgcatc\"",
    starterCodeJs: 'function shortestSuperstring(words) {\n  // your code here\n}',
    starterCodePy: 'def shortest_superstring(words):\n    # your code here\n    pass',
    starterCodeCpp: 'string shortestSuperstring(vector<string>& words) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-035',
    title: "Satrdagi Turli Qism Satrlar Soni",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^5). s ning barcha turli (bir-biriga teng bo'lmagan) qism satrlarining umumiy sonini toping (bo'sh qism satr hisobga olinmaydi). Barcha qism satrlarni generatsiya qilib xesh to'plamga solish O(n^2) yoki undan ham ko'proq xotira talab qiladi — suffiks massivi va LCP massividan foydalanib (yoki suffiks avtomati tushunchasidan) O(n log n) vaqtda yeching: har bir suffiks qo'shadigan yangi qism satrlar soni = (n - suffiks boshlanish indeksi) - LCP[qo'shni suffiks bilan].\n\n**1-misol:**\nKiritma: s = \"abab\"\nNatija: 7\nIzoh: Turli qism satrlar: \"a\",\"b\",\"ab\",\"ba\",\"aba\",\"bab\",\"abab\" — jami 7 ta.\n\n**2-misol:**\nKiritma: s = \"aaa\"\nNatija: 3",
    starterCodeJs: 'function countDistinctSubstrings(s) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_substrings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDistinctSubstrings(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-036',
    title: "Eng Uzun Palindromik Ketma-ketlik",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 2000). s ning eng uzun palindromik ketma-ketligini (subsequence, harflar ketma-ketligi saqlanadi lekin uzluksiz bo'lishi shart emas) uzunligini toping. Bu klassik intervalli dinamik dasturlash masalasi bo'lib, dp[i][j] — s[i..j] kesmasidagi eng uzun palindromik ketma-ketlik uzunligini bildiradi; O(n^2) vaqt va xotirada, o'tish s[i]==s[j] bo'lsa dp[i+1][j-1]+2, aks holda max(dp[i+1][j], dp[i][j-1]) ko'rinishida yeching.\n\n**1-misol:**\nKiritma: s = \"bbbab\"\nNatija: 4\nIzoh: \"bbbb\" eng uzun palindromik ketma-ketlik (harflarni tanlab olib, ularning tartibini o'zgartirmasdan).\n\n**2-misol:**\nKiritma: s = \"cbbd\"\nNatija: 2",
    starterCodeJs: 'function longestPalindromicSubsequence(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_palindromic_subsequence(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestPalindromicSubsequence(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-037',
    title: "Tahrirlash Masofasi (Levenshtein)",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Satrlar'],
    description: "Ikkita satr word1 va word2 berilgan (uzunliklari ≤ 2000). word1 ni word2 ga aylantirish uchun zarur bo'lgan minimal amallar sonini toping, ruxsat etilgan amallar: bitta harfni qo'shish, o'chirish yoki almashtirish (har biri bitta amal). Klassik ikki o'lchamli DP bilan O(n*m) vaqt va xotirada dp[i][j] — word1 ning birinchi i harfini word2 ning birinchi j harfiga aylantirish narxini ifodalaydi tarzda yeching.\n\n**1-misol:**\nKiritma: word1 = \"horse\", word2 = \"ros\"\nNatija: 3\nIzoh: horse -> rorse (h->r almashtirish) -> rose (r o'chirish) -> ros (e o'chirish), jami 3 amal.\n\n**2-misol:**\nKiritma: word1 = \"intention\", word2 = \"execution\"\nNatija: 5",
    starterCodeJs: 'function editDistance(word1, word2) {\n  // your code here\n}',
    starterCodePy: 'def edit_distance(word1, word2):\n    # your code here\n    pass',
    starterCodeCpp: 'int editDistance(string word1, string word2) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-038',
    title: "Ikki Satrning Eng Uzun Umumiy Ketma-ketligi",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Satrlar'],
    description: "Ikkita satr s1 va s2 berilgan (uzunliklari ≤ 2000). Ikkalasida ham ketma-ketlik sifatida (harflar tartibi saqlangan holda, lekin uzluksiz bo'lishi shart emas) uchraydigan eng uzun umumiy ketma-ketlikni (LCS) toping va uni aynan qaytaring (uzunligini emas, o'zini). O(n*m) DP jadvalini quring, so'ngra jadval bo'ylab orqaga qaytib (backtrack) natijaviy satrni tiklang.\n\n**1-misol:**\nKiritma: s1 = \"abcde\", s2 = \"ace\"\nNatija: \"ace\"\nIzoh: \"ace\" ikkala satrda ham ketma-ketlik sifatida uchraydi va eng uzuni hisoblanadi.\n\n**2-misol:**\nKiritma: s1 = \"abc\", s2 = \"abc\"\nNatija: \"abc\"",
    starterCodeJs: 'function longestCommonSubsequence(s1, s2) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_subsequence(s1, s2):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonSubsequence(string s1, string s2) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-039',
    title: "Eng Kichik Leksikografik Aylantirish (Booth Algoritmi)",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^5). s ning barcha siklik aylantirishlari (rotation) orasidan leksikografik jihatdan eng kichigini toping. Har bir aylantirishni generatsiya qilib solishtirish O(n^2) berib katta n uchun sekin — Booth algoritmi (modifikatsiyalangan muvaffaqiyatsizlik funksiyasi asosida) yordamida O(n) vaqtda eng kichik aylantirishning boshlanish indeksini toping.\n\n**1-misol:**\nKiritma: s = \"bbaaccbdd\"\nNatija: \"aaccbdd bb\" bo'shliqsiz \"aaccbddbb\"\nIzoh: Barcha aylantirishlar orasida \"aaccbddbb\" leksikografik eng kichigi.\n\n**2-misol:**\nKiritma: s = \"cba\"\nNatija: \"acb\"",
    starterCodeJs: 'function minimalRotation(s) {\n  // your code here\n}',
    starterCodePy: 'def minimal_rotation(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string minimalRotation(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-040',
    title: "Eng Uzun Takrorlanuvchi Qism Satr",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^5). s ichida kamida ikki marta (bir-biriga qoplanishi mumkin bo'lgan holatlar bilan ham) uchraydigan eng uzun qism satrni toping (agar bunday qism satr bo'lmasa, bo'sh satr qaytaring). Barcha juft qism satrlarni solishtirish sekin bo'ladi — suffiks massivi va LCP (longest common prefix) massivini qurib, LCP massividagi eng katta qiymatga mos keluvchi qism satrni O(n log n) vaqtda toping.\n\n**1-misol:**\nKiritma: s = \"banana\"\nNatija: \"ana\"\nIzoh: \"ana\" satrda ikki marta (indeks 1 va 3 dan) uchraydi va eng uzun takrorlanuvchi qism satr hisoblanadi.\n\n**2-misol:**\nKiritma: s = \"abcd\"\nNatija: \"\"",
    starterCodeJs: 'function longestRepeatedSubstring(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_repeated_substring(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestRepeatedSubstring(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-041',
    title: "Satrning Davriyligi (KMP Muvaffaqiyatsizlik Funksiyasi)",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^6). s ning eng kichik davrini (period) toping — ya'ni eng kichik p uzunlik shundayki, s ni p uzunlikdagi bir bo'lakni bir necha marta (to'liq yoki qisman oxirgi marta qisqartirilgan holda) takrorlash orqali hosil qilish mumkin bo'lsin (agar s davriy bo'lmasa, p = |s| qaytariladi). KMP algoritmining muvaffaqiyatsizlik funksiyasidan (prefix function) foydalanib, pi[n-1] qiymati orqali p = n - pi[n-1] formulasi bilan O(n) vaqtda hisoblang.\n\n**1-misol:**\nKiritma: s = \"abcabcabc\"\nNatija: 3\nIzoh: \"abc\" davri bilan uch marta takrorlanadi.\n\n**2-misol:**\nKiritma: s = \"abcabcab\"\nNatija: 3",
    starterCodeJs: 'function stringPeriod(s) {\n  // your code here\n}',
    starterCodePy: 'def string_period(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int stringPeriod(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-042',
    title: "Wildcard Naqsh Moslashtirish",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Satrlar'],
    description: "s satri va pattern naqshi berilgan (uzunliklari ≤ 2000), pattern tarkibida oddiy harflardan tashqari '?' (ixtiyoriy bitta belgi) va '*' (ixtiyoriy uzunlikdagi, bo'sh bo'lishi ham mumkin bo'lgan ketma-ketlik) belgilari bo'lishi mumkin. s pattern ga to'liq mos kelishini (true/false) aniqlang. Ikki o'lchamli DP jadvali dp[i][j] — s ning birinchi i belgisi pattern ning birinchi j belgisiga mos kelishini bildiradi tarzda O(n*m) vaqtda yeching, '*' holatini to'g'ri qayta ishlashga alohida e'tibor bering.\n\n**1-misol:**\nKiritma: s = \"adceb\", pattern = \"*a*b\"\nNatija: true\nIzoh: Birinchi '*' bo'sh mos keladi, 'a' mos keladi, ikkinchi '*' \"dce\" ni yutadi, 'b' mos keladi.\n\n**2-misol:**\nKiritma: s = \"cb\", pattern = \"?a\"\nNatija: false",
    starterCodeJs: 'function isWildcardMatch(s, pattern) {\n  // your code here\n}',
    starterCodePy: 'def is_wildcard_match(s, pattern):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isWildcardMatch(string s, string pattern) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-043',
    title: "Regulyar Ifoda Moslashtirish",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Satrlar'],
    description: "s satri va pattern naqshi berilgan (uzunliklari ≤ 1000), pattern tarkibida '.' (ixtiyoriy bitta belgi) va '*' (undan oldingi belgining 0 yoki undan ko'p takrorlanishi) belgilari bo'lishi mumkin. s pattern ga to'liq mos kelishini aniqlang (true/false). Ikki o'lchamli DP dp[i][j] yordamida, '*' belgisini uchratganda ikkita holatni (0 marta ishlatish yoki oldingi belgini takrorlab davom ettirish) hisobga olib O(n*m) vaqtda yeching.\n\n**1-misol:**\nKiritma: s = \"aa\", pattern = \"a*\"\nNatija: true\nIzoh: '*' 'a' ni bir necha marta takrorlaydi, shu jumladan ikki marta.\n\n**2-misol:**\nKiritma: s = \"mississippi\", pattern = \"mis*is*p*.\"\nNatija: false",
    starterCodeJs: 'function isRegexMatch(s, pattern) {\n  // your code here\n}',
    starterCodePy: 'def is_regex_match(s, pattern):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isRegexMatch(string s, string pattern) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-044',
    title: "Prefiks Daraxti: Kamida K ta So'zda Uchraydigan Eng Uzun Prefiks",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Satrlar'],
    description: "Kichik lotin harflaridan iborat so'zlar ro'yxati strings va butun son k berilgan. Kamida k ta so'zning prefiksi bo'lgan eng uzun satrni toping (bir nechta javob bo'lsa, ixtiyoriy birini qaytaring; hech qanday mos prefiks bo'lmasa bo'sh satr qaytaring). Barcha so'z juftlarini solishtirish sekin bo'ladi — barcha so'zlarni bitta Trie (prefiks daraxti) ga joylab, har bir tugunda undan o'tuvchi so'zlar sonini saqlab, chuqurligi eng katta va hisob ≥ k bo'lgan tugunni O(summa uzunliklar) vaqtda toping.\n\n**1-misol:**\nKiritma: strings = [\"flower\",\"flow\",\"flight\",\"flock\"], k = 3\nNatija: \"fl\"\nIzoh: \"fl\" prefiksi 4 ta so'zda ham uchraydi, lekin \"flo\" faqat 2 tasida, shuning uchun k=3 uchun eng uzun mos prefiks \"fl\".\n\n**2-misol:**\nKiritma: strings = [\"dog\",\"cat\",\"bird\"], k = 2\nNatija: \"\"",
    starterCodeJs: 'function longestPrefixInAtLeastK(strings, k) {\n  // your code here\n}',
    starterCodePy: 'def longest_prefix_in_at_least_k(strings, k):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestPrefixInAtLeastK(vector<string>& strings, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-045',
    title: "Suffiks Avtomati Orqali Qism Satr Takrorlari",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Satrlar'],
    description: "s satri (|s| ≤ 10^5) va q ta qism satr so'rovi (queries) berilgan. Har bir so'ralgan qism satr s ichida (qoplanishi mumkin bo'lgan holatlar bilan) necha marta uchrashini toping. Har bir so'rovni s bo'yicha to'liq qidirish (KMP) O(q*n) berib sekin bo'ladi — s uchun suffiks avtomati (yoki suffiks daraxti + har bir tugunning \"end-pos\" hajmi) qurib, har bir so'rovni avtomat bo'ylab yurish orqali O(|so'rov|) vaqtda javob bering, umumiy murakkablik O(n + summa(|so'rov|)).\n\n**1-misol:**\nKiritma: s = \"abcabcabc\", queries = [\"abc\",\"bca\",\"abcabc\",\"xyz\"]\nNatija: [3,2,2,0]\nIzoh: \"abc\" 3 marta, \"bca\" 2 marta, \"abcabc\" 2 marta (indeks 0 va 3 dan boshlanib), \"xyz\" umuman uchramaydi.\n\n**2-misol:**\nKiritma: s = \"aaaa\", queries = [\"aa\"]\nNatija: [3]",
    starterCodeJs: 'function substringOccurrenceCount(s, queries) {\n  // your code here\n}',
    starterCodePy: 'def substring_occurrence_count(s, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> substringOccurrenceCount(string s, vector<string>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-046',
    title: "Barcha Davrlarni Topish (Z-funksiya)",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^6). s uchun barcha mumkin bo'lgan davrlarni (period) — ya'ni shunday p qiymatlarini toping, ular uchun s[i] == s[i+p] barcha to'g'ri i lar uchun (0 ≤ i ≤ n-p-1) o'rinli bo'lsin, va p qiymatlarni o'sish tartibida qaytaring. Z-funksiyani O(n) da hisoblab, har bir i uchun i + Z[i] == n shartini tekshirish orqali barcha davrlarni O(n) vaqtda toping.\n\n**1-misol:**\nKiritma: s = \"abababab\"\nNatija: [2,4,6,8]\nIzoh: p=2 uchun \"ab\" takrorlanadi, p=4,6 uchun ham shart bajariladi, p=8 (butun satr uzunligi) har doim davr hisoblanadi.\n\n**2-misol:**\nKiritma: s = \"abcabc\"\nNatija: [3,6]",
    starterCodeJs: 'function findAllPeriods(s) {\n  // your code here\n}',
    starterCodePy: 'def find_all_periods(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findAllPeriods(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-047',
    title: "Lug'atdagi So'zlarning Matndagi Umumiy Uchrashi",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Satrlar'],
    description: "text matni (|text| ≤ 10^6) va dictionary nomli so'zlar ro'yxati (umumiy uzunlik ≤ 10^5) berilgan. text ichida dictionary dagi barcha so'zlarning (bir-biriga qoplanishi mumkin bo'lgan holatlar bilan) jami necha marta uchraganini hisoblang (har bir uchrashish alohida sanaladi, hatto bitta pozitsiyada bir nechta so'z tugasa ham). Har bir so'zni alohida qidirish sekin bo'ladi — Aho-Korasik avtomatini qurib (trie + fail-havolalar + \"dictionary link\" orqali chuqur mos kelishlarni ham hisobga olib), matnni bitta marta O(|text| + qurish vaqti) da aylanib chiqing.\n\n**1-misol:**\nKiritma: text = \"abcabc\", dictionary = [\"a\",\"ab\",\"bc\",\"abc\"]\nNatija: 8\nIzoh: \"a\" 2 marta, \"ab\" 2 marta, \"bc\" 2 marta, \"abc\" 2 marta uchraydi, jami 8.\n\n**2-misol:**\nKiritma: text = \"aaa\", dictionary = [\"a\"]\nNatija: 3",
    starterCodeJs: 'function totalDictionaryOccurrences(text, dictionary) {\n  // your code here\n}',
    starterCodePy: 'def total_dictionary_occurrences(text, dictionary):\n    # your code here\n    pass',
    starterCodeCpp: 'long long totalDictionaryOccurrences(string text, vector<string>& dictionary) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-048',
    title: "Lindon So'zlariga Ajratish (Duval Algoritmi)",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^6). s ni kamayuvchi bo'lmagan tartibda joylashgan Lindon so'zlariga (Lyndon word — o'zining har qanday to'g'ri siklik aylantirishidan leksikografik jihatdan qat'iy kichik bo'lgan satr) ajrating, ya'ni s = w1 + w2 + ... + wk bo'lib, w1 ≥ w2 ≥ ... ≥ wk va har bir wi Lindon so'zi. Duval algoritmi yordamida O(n) vaqtda barcha Lindon so'zlarini ro'yxat sifatida qaytaring.\n\n**1-misol:**\nKiritma: s = \"abcabcabcabd\"\nNatija: [\"abcabcabcabd\"]\nIzoh: Butun satr o'zi Lindon so'zi bo'lib chiqadi, chunki uning istalgan aylantirishidan leksikografik kichik.\n\n**2-misol:**\nKiritma: s = \"banana\"\nNatija: [\"b\",\"an\",\"an\",\"a\"]",
    starterCodeJs: 'function lyndonDecomposition(s) {\n  // your code here\n}',
    starterCodePy: 'def lyndon_decomposition(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> lyndonDecomposition(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-049',
    title: "Berrouz-Uiler Almashtirishi (BWT)",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^5, oxirida noyob '$' belgisi bilan tugaydi deb faraz qiling). s ning Berrouz-Uiler almashtirishini (Burrows-Wheeler Transform) hisoblang — bu barcha siklik aylantirishlarni leksikografik saralab, ularning oxirgi ustunini birlashtirish orqali hosil qilinadi. Barcha n ta aylantirishni to'g'ridan-to'g'ri saralash O(n^2 log n) berib sekin bo'ladi — suffiks massividan foydalanib (suffiks massivi elementi i bo'lsa, natija ustuni s[i-1] bo'ladi, i=0 bo'lsa s[n-1]) O(n log n) vaqtda hisoblang.\n\n**1-misol:**\nKiritma: s = \"banana$\"\nNatija: \"annb$aa\"\nIzoh: Barcha siklik aylantirishlarni saralab, oxirgi ustunni o'qish orqali \"annb$aa\" hosil bo'ladi.\n\n**2-misol:**\nKiritma: s = \"abc$\"\nNatija: \"c$ab\"",
    starterCodeJs: 'function bwtTransform(s) {\n  // your code here\n}',
    starterCodePy: 'def bwt_transform(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string bwtTransform(string s) {\n    // your code here\n}',
  },
  {
    key: 'expert-a-050',
    title: "Barcha Palindromik Qism Satrlar Soni",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Satrlar'],
    description: "s satri berilgan (|s| ≤ 10^6). s ning barcha palindromik qism satrlarining umumiy sonini hisoblang (bir xil qiymatli lekin turli pozitsiyadagi qism satrlar alohida sanaladi). Har bir markazdan kengaytirish usuli O(n^2) berib katta n uchun sekin bo'ladi — Manacher algoritmini kengaytirib, har bir markaz uchun topilgan maksimal radiusdan foydalanib barcha palindromlar sonini O(n) vaqtda hisoblang.\n\n**1-misol:**\nKiritma: s = \"abc\"\nNatija: 3\nIzoh: Palindromik qism satrlar: \"a\", \"b\", \"c\" — jami 3 ta.\n\n**2-misol:**\nKiritma: s = \"aaa\"\nNatija: 6\nIzoh: \"a\",\"a\",\"a\",\"aa\",\"aa\",\"aaa\" — jami 6 ta palindromik qism satr (pozitsiyalari bilan hisoblanganda).",
    starterCodeJs: 'function countPalindromicSubstrings(s) {\n  // your code here\n}',
    starterCodePy: 'def count_palindromic_substrings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPalindromicSubstrings(string s) {\n    // your code here\n}',
  },
];
