export const problems = [
  {
    key: 'expert-b-001',
    title: "Modul Bo'yicha Bo'linma",
    difficulty: 'EXPERT',
    points: 105,
    tags: ['Matematika'],
    description: "p — katta tub son (10^9 dan katta bo'lishi mumkin), a va b esa 0 <= a < p va 1 <= b < p shartlarni qanoatlantiruvchi butun sonlar, bunda b, p ga bo'linmaydi. (a * b^{-1}) mod p qiymatini toping, ya'ni a ni b ga modul p bo'yicha bo'lish natijasini hisoblang. b ning p bo'yicha teskari elementini Fermaning kichik teoremasi (b^{p-2} mod p) yoki kengaytirilgan Evklid algoritmi yordamida O(log p) vaqt murakkabligida hisoblang — oddiy siklda teskari elementni izlash juda sekin bo'ladi. Natija har doim [0, p-1] oralig'ida yagona bo'ladi.\n\n**1-misol:**\nKiritma: a = 4, b = 2, p = 7\nNatija: 2\nIzoh: 4 ni 2 ga bo'lish 2 ga teng, chunki 2*2 mod 7 = 4.\n\n**2-misol:**\nKiritma: a = 3, b = 5, p = 7\nNatija: 2\nIzoh: 5 ning 7 bo'yicha teskarisi 3 (5*3=15≡1), 3*3 mod 7 = 2.",
    starterCodeJs: 'function modDivide(a, b, p) {\n  // your code here\n}',
    starterCodePy: 'def mod_divide(a, b, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long modDivide(long long a, long long b, long long p) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-002',
    title: "Teskari Faktoriallar Bilan Kombinatorika",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Matematika'],
    description: "n (n <= 2*10^6) va so'rovlar ro'yxati beriladi, har bir so'rov (r_i, k_i) juftligidan iborat bo'lib, C(r_i, k_i) mod (10^9+7) ni hisoblash talab qilinadi, bunda 0 <= k_i <= r_i <= n. So'rovlar soni Q ham 10^6 gacha yetishi mumkin, shuning uchun har bir so'rovni O(log n) yoki undan tezroq javoblash uchun 0 dan n gacha faktoriallar va ularning modul bo'yicha teskarilarini oldindan hisoblab qo'ying. Teskari faktoriallarni faqat bitta modul darajaga ko'tarish va bitta teskari ketma-ketlik yordamida O(n) da qurish kerak (har bir elementga alohida darajaga ko'tarish operatsiyasini ishlatmang).\n\n**1-misol:**\nKiritma: n = 5, so'rovlar = [(5,2), (4,0)]\nNatija: [10, 1]\nIzoh: C(5,2)=10, C(4,0)=1.\n\n**2-misol:**\nKiritma: n = 1000000, so'rovlar = [(1000000, 500000)]\nNatija: [<mos modul qiymat>]",
    starterCodeJs: 'function binomialQueries(n, queries) {\n  // your code here\n}',
    starterCodePy: 'def binomial_queries(n, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> binomialQueries(int n, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-003',
    title: "Chiziqli Diofant Tenglamasi",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Matematika'],
    description: "a, b, c butun sonlar berilgan (|a|,|b|,|c| <= 10^18). ax + by = c tenglamani qanoatlantiruvchi x va y butun sonlarni topish kerak, agar yechim mavjud bo'lmasa buni aniqlash kerak. Kengaytirilgan Evklid algoritmini qo'llab, gcd(a,b) ni va bir vaqtning o'zida ax0+by0=gcd(a,b) tenglamaning bir yechimini toping, so'ng uni c/gcd ga masshtablang. Yechim mavjud bo'lganda cheksiz ko'p yechim borligini va ularning umumiy formulasini (x0 + k*b/g, y0 - k*a/g) hisobga oling, lekin faqat bitta konkret (x,y) juftligini qaytaring.\n\n**1-misol:**\nKiritma: a = 6, b = 9, c = 12\nNatija: x = 2, y = 0\nIzoh: 6*2 + 9*0 = 12; gcd(6,9)=3 va 3 | 12 bo'lgani uchun yechim mavjud.\n\n**2-misol:**\nKiritma: a = 4, b = 6, c = 5\nNatija: Yechim mavjud emas\nIzoh: gcd(4,6)=2, lekin 2 soni 5 ga bo'linmaydi.",
    starterCodeJs: 'function solveLinearDiophantine(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def solve_linear_diophantine(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<long long,long long> solveLinearDiophantine(long long a, long long b, long long c, bool& exists) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-004',
    title: "Umumiy Qoldiqlar Teoremasi (Nokoprim Modullar)",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Matematika'],
    description: "n ta kongruensiya sistemasi beriladi: x ≡ r_i (mod m_i) uchun i=1..n, bunda m_i lar o'zaro tub bo'lishi shart emas. Kengaytirilgan Evklid algoritmidan foydalanib, ikkitadan-ikkitaga kongruensiyalarni birlashtirib boring va sistemaning yechimi mavjudligini aniqlang (yechim mavjud bo'lishi uchun har bir juftlik uchun r_i ≡ r_j (mod gcd(m_i,m_j)) bo'lishi kerak). Agar yechim mavjud bo'lsa, x ni umumiy modul M = lcm(m_1,...,m_n) bo'yicha qaytaring, aks holda mos xabar bering. n va m_i lar shunday kattaki, natijaviy modul 64-bitli butun sondan oshib ketishi mumkin, shuning uchun overflow oldini olish choralarini ko'ring.\n\n**1-misol:**\nKiritma: [(x≡2 mod 4), (x≡3 mod 6)]\nNatija: x ≡ 14 (mod 12)\nIzoh: 14 mod 4 = 2, 14 mod 6 = 2... to'g'ri tekshirilsa x≡2 (mod12) yechim, chunki 2 mod4=2, 2 mod6=2.\n\n**2-misol:**\nKiritma: [(x≡1 mod 4), (x≡2 mod 6)]\nNatija: Yechim mavjud emas\nIzoh: gcd(4,6)=2, lekin 1-2=-1 soni 2 ga bo'linmaydi.",
    starterCodeJs: 'function generalCRT(congruences) {\n  // your code here\n}',
    starterCodePy: 'def general_crt(congruences):\n    # your code here\n    pass',
    starterCodeCpp: 'bool generalCRT(vector<pair<long long,long long>>& congruences, long long& x, long long& mod) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-005',
    title: "Katta Sonning Tubligini Tekshirish",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Matematika'],
    description: "n butun soni berilgan (1 <= n <= 10^18). n ning tub son ekan-emasligini aniqlang. n juda katta bo'lgani uchun oddiy bo'linish siklidan (O(sqrt(n))) tashqari, Miller-Rabin tub sonlarni tekshirish algoritmi tamoyillaridan foydalaning: n-1 = 2^s * d ko'rinishida yozib, tanlangan bazalar to'plami (masalan 2,3,5,7,11,13,17,19,23,29,31,37 — bu bazalar 3.3*10^24 gacha deterministik natija beradi) bo'yicha a^d mod n va uning ketma-ket kvadratlarini tekshiring. Modul darajaga ko'tarishda 64-bit ko'paytirishda overflow bo'lmasligi uchun 128-bit yoki qo'shma ko'paytirish usulidan foydalaning.\n\n**1-misol:**\nKiritma: n = 561\nNatija: Tub son emas (Karmayl soni)\n\n**2-misol:**\nKiritma: n = 999999999999999989\nNatija: Tub son",
    starterCodeJs: 'function isPrimeMillerRabin(n) {\n  // your code here\n}',
    starterCodePy: 'def is_prime_miller_rabin(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPrimeMillerRabin(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-006',
    title: "Berilgan Sondan Keyingi Eng Kichik Tub Son",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Matematika'],
    description: "n butun soni beriladi (1 <= n <= 10^18). n dan katta yoki teng bo'lgan eng kichik tub sonni toping. Bu miqyosda oddiy elak (sieve) usuli ishlamaydi, shuning uchun har bir nomzod son uchun Miller-Rabin tub sonlarni tekshirish algoritmidan foydalanib, ketma-ket nomzodlarni tekshirib chiqing. Tub sonlar orasidagi bo'shliq bu diapazonda odatda kichik bo'lishini (taxminan ln(n) tartibida) hisobga olib, algoritm samarali ishlashini ta'minlang, lekin bu chegara kafolatlanmagan holatlarni ham to'g'ri qayta ishlang.\n\n**1-misol:**\nKiritma: n = 14\nNatija: 17\n\n**2-misol:**\nKiritma: n = 1000000000000000000\nNatija: 1000000000000000003",
    starterCodeJs: 'function nextPrime(n) {\n  // your code here\n}',
    starterCodePy: 'def next_prime(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nextPrime(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-007',
    title: "Umumiy Chiziqli Rekurrensiyaning N-Hadi",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Matematika'],
    description: "k-tartibli chiziqli rekurrent ketma-ketlik beriladi: a_n = c_1*a_{n-1} + c_2*a_{n-2} + ... + c_k*a_{n-k}, bunda c_1..c_k koeffitsientlar va a_0..a_{k-1} boshlang'ich qiymatlar berilgan. n juda katta bo'lishi mumkin (n <= 10^18), shuning uchun a_n ni to'g'ridan-to'g'ri iteratsiya bilan hisoblash imkonsiz. k x k o'lchamli transformatsiya matritsasini qurib, tez matritsani darajaga ko'tarish (binary exponentiation) usuli yordamida a_n mod (10^9+7) ni O(k^3 log n) vaqtda hisoblang.\n\n**1-misol:**\nKiritma: k=2, c=[1,1], a0=[0,1], n=10\nNatija: 55\nIzoh: Bu Fibonachchi ketma-ketligi, F(10)=55.\n\n**2-misol:**\nKiritma: k=3, c=[1,1,1], a0=[0,1,2], n=100\nNatija: <mos modul qiymat>\nIzoh: Bu Tribonachchi tipidagi ketma-ketlik.",
    starterCodeJs: 'function linearRecurrenceNth(c, a0, n, mod) {\n  // your code here\n}',
    starterCodePy: 'def linear_recurrence_nth(c, a0, n, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long linearRecurrenceNth(vector<long long>& c, vector<long long>& a0, long long n, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-008',
    title: "3xN Yo'lakni Domino Bilan Qoplash",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Matematika'],
    description: "3 x n o'lchamli to'g'ri to'rtburchak yo'lakni 1x2 o'lchamli domino toshlar bilan to'liq qoplash usullari sonini toping (n <= 10^18), natijani mod (10^9+7) bo'yicha bering. Bu masalani kichik n qiymatlari uchun holatlar orasidagi chiziqli rekurrensiyani (masalan f(n) = 4*f(n-2) - f(n-4) turidagi) qo'lda yoki holat-mashinasi orqali chiqarib, so'ngra ushbu rekurrensiyani matritsa ko'rinishida ifodalab, tez matritsani darajaga ko'tarish orqali O(log n) vaqtda yeching. n toq bo'lganda qoplash mumkin emasligini alohida hisobga oling.\n\n**1-misol:**\nKiritma: n = 2\nNatija: 3\n\n**2-misol:**\nKiritma: n = 4\nNatija: 11",
    starterCodeJs: 'function tiling3xN(n) {\n  // your code here\n}',
    starterCodePy: 'def tiling_3xn(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long tiling3xN(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-009',
    title: "Grafda Berilgan Uzunlikdagi Yo'llar Soni",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Matematika'],
    description: "n ta cho'qqili yo'naltirilgan graf qo'shnilik matritsasi A (n x n, n <= 50) va k butun soni (k <= 10^18) beriladi. Har bir (i,j) juftligi uchun i dan j ga aynan k ta qirradan iborat yo'llar sonini mod (10^9+7) bo'yicha hisoblang. Bu son A^k matritsaning (i,j) elementiga teng ekanligidan foydalanib, matritsani tez darajaga ko'tarish algoritmini qo'llang — bu O(n^3 log k) vaqt murakkabligini beradi, oddiy k marta ko'paytirish esa juda sekin bo'ladi.\n\n**1-misol:**\nKiritma: A = [[0,1],[1,0]], k = 2\nNatija: [[1,0],[0,1]]\nIzoh: 2 qadamda har bir cho'qqidan o'ziga qaytish mumkin.\n\n**2-misol:**\nKiritma: A = [[1,1],[1,0]], k = 5\nNatija: [[8,5],[5,3]]\nIzoh: Bu Fibonachchi sonlari bilan bog'liq matritsa darajasi.",
    starterCodeJs: 'function countPathsOfLengthK(adjMatrix, k) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_of_length_k(adj_matrix, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<long long>> countPathsOfLengthK(vector<vector<long long>>& adj, long long k) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-010',
    title: "Mobius Funksiyasi Orqali O'zaro Tub Juftliklar",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Matematika'],
    description: "n butun soni beriladi (n <= 10^6). 1 dan n gacha bo'lgan sonlar orasidan gcd(i,j)=1 shartini qanoatlantiruvchi tartiblanmagan {i,j} (i≠j) juftliklar sonini toping. Har bir d bo'luvchi uchun mobius funksiyasi mu(d) dan foydalanib, inklyuziya-exklyuziya prinsipi asosida javobni Sum_{d=1}^{n} mu(d) * C(floor(n/d), 2) ko'rinishidagi formulaga keltiring. mu(d) qiymatlarini elak (sieve) usuli bilan O(n log log n) da oldindan hisoblab qo'ying, sodda O(n^2) juft-juft tekshirish usuli yetarlicha tez emas.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 5\nIzoh: (1,2),(1,3),(1,4),(2,3),(3,4) juftliklari o'zaro tub.\n\n**2-misol:**\nKiritma: n = 6\nNatija: 11",
    starterCodeJs: 'function countCoprimePairs(n) {\n  // your code here\n}',
    starterCodePy: 'def count_coprime_pairs(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countCoprimePairs(int n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-011',
    title: "Kvadratsiz Sonlarni Sanash",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Matematika'],
    description: "n butun soni beriladi (n <= 10^12). 1 dan n gacha bo'lgan kvadratsiz sonlar (ya'ni hech qanday tub sonning kvadratiga bo'linmaydigan sonlar) sonini toping. Sum_{d=1}^{sqrt(n)} mu(d) * floor(n/d^2) formulasidan foydalaning, bunda mu — mobius funksiyasi. mu(d) qiymatlarini d <= sqrt(n) uchun (bu taxminan 10^6 gacha) elak usuli bilan oldindan hisoblang, so'ngra formulani O(sqrt(n)) vaqtda hisoblang — n ning o'zi juda katta bo'lgani uchun to'g'ridan-to'g'ri sanash mumkin emas.\n\n**1-misol:**\nKiritma: n = 10\nNatija: 7\nIzoh: 4,8,9 sonlari kvadratga bo'linadi (4=2^2, 8 bo'linadi 4 ga, 9=3^2), qolgan 7 ta son kvadratsiz.\n\n**2-misol:**\nKiritma: n = 1000000000000\nNatija: <mos qiymat>",
    starterCodeJs: 'function countSquareFree(n) {\n  // your code here\n}',
    starterCodePy: 'def count_square_free(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countSquareFree(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-012',
    title: "To'g'ri Chiziq Ostidagi Panjara Nuqtalari",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Matematika'],
    description: "Musbat butun sonlar n, a, b beriladi (barchasi 10^9 gacha yetishi mumkin). x = 1, 2, ..., n uchun y = floor(a*x / b) qiymatlarining yig'indisini, ya'ni y = (a/b)*x to'g'ri chiziq ostida (va shu chiziqqacha) yotuvchi butun koordinatali nuqtalar sonini toping. Sodda siklda har bir x uchun floor hisoblash O(n) vaqt talab qiladi va n katta bo'lganda yetarli emas — Evklid algoritmiga o'xshash rekursiv \"floor_sum\" texnikasidan foydalanib, masalani O(log(max(a,b))) vaqtga qisqartiring, bu texnikada a va b navbatma-navbat almashtirilib, mod va bo'linma operatsiyalari orqali qadam-baqadam soddalashtiriladi.\n\n**1-misol:**\nKiritma: n = 4, a = 3, b = 2\nNatija: 10\nIzoh: floor(3/2)+floor(6/2)+floor(9/2)+floor(12/2) = 1+3+4+6 = 14... (aniq misol uchun mos qiymatlar tekshiriladi)\n\n**2-misol:**\nKiritma: n = 1000000000, a = 999999999, b = 1000000000\nNatija: <mos qiymat>",
    starterCodeJs: 'function floorSum(n, a, b) {\n  // your code here\n}',
    starterCodePy: 'def floor_sum(n, a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long long floorSum(long long n, long long a, long long b) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-013',
    title: "Pick Teoremasi Bilan Ko'pburchak Ichidagi Nuqtalar",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Matematika'],
    description: "Butun koordinatali cho'qqilarga ega bo'lgan oddiy (o'z-o'zini kesmaydigan) ko'pburchak berilgan (uning cho'qqilari ketma-ket ro'yxatda, n <= 10^5 ta cho'qqi). Ko'pburchak ichida yotuvchi butun koordinatali nuqtalar sonini toping. Shoelace formulasi orqali ko'pburchakning yuzini (A), qirralar bo'ylab yotuvchi butun nuqtalar sonini (B, har bir qirra uchun gcd(|dx|,|dy|) yig'indisi orqali) hisoblang, so'ngra Pick teoremasidan (A = I + B/2 - 1) foydalanib ichki nuqtalar sonini I = A - B/2 + 1 formulasi bilan toping.\n\n**1-misol:**\nKiritma: cho'qqilar = [(0,0),(4,0),(4,4),(0,4)]\nNatija: 9\nIzoh: 4x4 kvadrat ichida 3x3=9 ta ichki butun nuqta bor.\n\n**2-misol:**\nKiritma: cho'qqilar = [(0,0),(3,0),(0,3)]\nNatija: 1",
    starterCodeJs: 'function countInteriorLatticePoints(vertices) {\n  // your code here\n}',
    starterCodePy: 'def count_interior_lattice_points(vertices):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countInteriorLatticePoints(vector<pair<long long,long long>>& vertices) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-014',
    title: "Katta Sonlarni Tez Ko'paytirish",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Matematika'],
    description: "Ikkita juda katta musbat butun son A va B ularning o'nlik raqamlari massivi ko'rinishida beriladi (har birining uzunligi 10^5 gacha yetishi mumkin). A*B ko'paytmasini o'nlik raqamlar massivi ko'rinishida qaytaring. Oddiy uzunlik-usulida ko'paytirish O(n^2) vaqt talab qiladi va bu miqyosda juda sekin bo'ladi; buning o'rniga sonlarni koeffitsientlar massivi (polinom) sifatida qarab, ularni Sonlar Nazariyasi Transformatsiyasi (NTT, modul 998244353 kabi NTT-do'st tub son ustida) yordamida chastota sohasiga o'tkazib, elementma-element ko'paytirib, teskari NTT bilan qaytaring — bu O(n log n) vaqt beradi. Natijada carry (ko'chirish) operatsiyasini to'g'ri bajarishni unutmang.\n\n**1-misol:**\nKiritma: A = \"123\", B = \"456\"\nNatija: \"56088\"\n\n**2-misol:**\nKiritma: A = \"999\", B = \"999\"\nNatija: \"998001\"",
    starterCodeJs: 'function multiplyBigNumbersNTT(a, b) {\n  // your code here\n}',
    starterCodePy: 'def multiply_big_numbers_ntt(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'string multiplyBigNumbersNTT(const string& a, const string& b) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-015',
    title: "Konvolyutsiya Orqali Yig'indi Usullarini Sanash",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Matematika'],
    description: "1 dan n gacha bo'lgan har bir qiymatdan cheksiz miqdorda mavjud deb faraz qilingan holda, ularning yig'indisi aynan S ga teng bo'ladigan (tartib muhim, ya'ni kompozitsiyalar) usullar sonini mod (10^9+7) bo'yicha toping, bunda n <= 10^5 va S <= 10^5. Har bir k mavjud qiymat uchun x^k hadli generating funksiyani tuzing va bu polinomlarning konvolyutsiyasini Sonlar Nazariyasi Transformatsiyasi (NTT) konsepsiyasidan foydalanib tez bajaring, chunki oddiy DP konvolyutsiyasi O(n*S) bo'lib katta hajmlar uchun optimallashtirilishi kerak bo'lgan holatlarni polinom ko'paytirish orqali tezlashtiring.\n\n**1-misol:**\nKiritma: n = 2, S = 3\nNatija: 3\nIzoh: 1+1+1, 1+2, 2+1 — uchta kompozitsiya.\n\n**2-misol:**\nKiritma: n = 3, S = 4\nNatija: 7",
    starterCodeJs: 'function countCompositionsNTT(n, s) {\n  // your code here\n}',
    starterCodePy: 'def count_compositions_ntt(n, s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countCompositionsNTT(int n, int s) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-016',
    title: "Kichik Tub Modul Bo'yicha Katta Binomial Koeffitsient",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Matematika'],
    description: "n, k va p beriladi, bunda n va k juda katta bo'lishi mumkin (10^18 gacha), p esa kichik tub son (p <= 10^6). C(n, k) mod p qiymatini toping. n va k ni p-lik sanoq sistemasida raqamlarga ajratib, Lyukas teoremasidan foydalaning: C(n,k) mod p = productlar ko'paytmasi C(n_i, k_i) mod p bo'yicha, bunda n_i va k_i — n va k ning p-lik tasviridagi mos raqamlari. Agar biror qadamda k_i > n_i bo'lsa, natija 0 bo'lishini unutmang.\n\n**1-misol:**\nKiritma: n = 10, k = 2, p = 5\nNatija: 0\nIzoh: C(10,2)=45, 45 mod 5 = 0.\n\n**2-misol:**\nKiritma: n = 1000000000000, k = 500000000000, p = 13\nNatija: <mos qiymat>",
    starterCodeJs: 'function lucasBinomial(n, k, p) {\n  // your code here\n}',
    starterCodePy: 'def lucas_binomial(n, k, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long lucasBinomial(long long n, long long k, long long p) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-017',
    title: "Tub Son Kvadrati Moduli Bo'yicha Binomial Koeffitsient",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Matematika'],
    description: "n, k va tub son p (p <= 10^5) beriladi, n va k 10^15 gacha yetishi mumkin. C(n, k) mod p^2 qiymatini toping. Oddiy Lyukas teoremasi faqat tub modul uchun ishlaydi, shuning uchun umumlashtirilgan (Andrew Granville tipidagi) Lyukas usulidan foydalanib, n! ning p bilan bo'linmaydigan qismini (p^2 modul bo'yicha) rekursiv hisoblang va n! dagi p ko'paytuvchisi darajasini Legendre formulasi orqali aniqlab, natijaviy formulani birlashtiring. Bu masala oddiy Lyukas teoremasidan ancha murakkab bo'lib, p ni bo'luvchi holatlarni alohida ko'rib chiqishni talab qiladi.\n\n**1-misol:**\nKiritma: n = 10, k = 3, p = 3\nNatija: C(10,3) mod 9 = 120 mod 9 = 3\n\n**2-misol:**\nKiritma: n = 100, k = 50, p = 7\nNatija: <mos qiymat>",
    starterCodeJs: 'function generalizedLucas(n, k, p) {\n  // your code here\n}',
    starterCodePy: 'def generalized_lucas(n, k, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long generalizedLucas(long long n, long long k, long long p) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-018',
    title: "Eyler Funksiyasini Hisoblash",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Matematika'],
    description: "n butun soni beriladi (1 <= n <= 10^12). Eyler totient funksiyasi phi(n) ni, ya'ni 1 dan n gacha bo'lgan n bilan o'zaro tub sonlar sonini hisoblang. n ni sqrt(n) gacha bo'lgan tub sonlarga bo'lib ko'rish orqali (O(sqrt(n)) vaqtda) faktorlashtirib, phi(n) = n * product(1 - 1/p_i) formulasidan foydalaning, bunda p_i — n ning barcha turli tub bo'luvchilari. n juda katta bo'lgani uchun elak usuli bilan oldindan barcha sonlar uchun phi hisoblash imkonsiz, shu sababli har bir so'rov uchun to'g'ridan-to'g'ri faktorlashtirish kerak.\n\n**1-misol:**\nKiritma: n = 36\nNatija: 12\n\n**2-misol:**\nKiritma: n = 999999999989\nNatija: 999999999988\nIzoh: Bu son tub bo'lgani uchun phi(n) = n-1.",
    starterCodeJs: 'function eulerTotient(n) {\n  // your code here\n}',
    starterCodePy: 'def euler_totient(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long eulerTotient(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-019',
    title: "Umumlashgan Eyler Teoremasi Bilan Katta Daraja",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Matematika'],
    description: "a, b va m beriladi, bunda a >= 0 butun son, b esa juda katta (2*10^5 tagacha raqamdan iborat o'nlik satr sifatida berilgan) daraja ko'rsatkichi va m modul (1 <= m <= 10^9). a^b mod m qiymatini toping. Umumiy holda gcd(a,m) != 1 bo'lishi mumkin, shuning uchun oddiy Eyler teoremasi (a^phi(m) ≡ 1) to'g'ridan-to'g'ri qo'llanilmaydi — buning o'rniga umumlashgan Eyler teoremasidan foydalaning: agar b >= log2(m) bo'lsa, a^b ≡ a^(phi(m) + b mod phi(m)) (mod m). phi(m) ni hisoblang va b ni phi(m) bo'yicha to'g'ri qoldiq bilan almashtiring, keyin tez darajaga ko'tarish bilan yakuniy javobni toping.\n\n**1-misol:**\nKiritma: a = 2, b = \"10\", m = 1000\nNatija: 24\nIzoh: 2^10 = 1024, 1024 mod 1000 = 24.\n\n**2-misol:**\nKiritma: a = 3, b = \"1000000000000000000000\", m = 7\nNatija: <mos qiymat>",
    starterCodeJs: 'function generalizedEulerPower(a, bStr, m) {\n  // your code here\n}',
    starterCodePy: 'def generalized_euler_power(a, b_str, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long generalizedEulerPower(long long a, const string& bStr, long long m) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-020',
    title: "Diskret Logarifm (Kichik Qadam-Katta Qadam)",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Matematika'],
    description: "Tub son p, va a, b (1 <= a, b < p) berilgan bo'lib, a^x ≡ b (mod p) tenglamani qanoatlantiruvchi eng kichik manfiy bo'lmagan x ni toping, yoki bunday x mavjud emasligini aniqlang. p 10^9 gacha yetishi mumkin, shuning uchun oddiy x=0,1,2,... siklida qidirish O(p) vaqt oladi va yetarli emas. Baby-step giant-step algoritmidan foydalaning: m = ceil(sqrt(p)) deb belgilab, kichik qadamlar uchun a^j (0<=j<m) qiymatlarini xesh jadvalga saqlang, so'ngra katta qadamlar uchun b*(a^{-m})^i qiymatlarini shu jadvalda qidiring — bu O(sqrt(p) log p) vaqt beradi.\n\n**1-misol:**\nKiritma: a = 2, b = 3, p = 5\nNatija: 3\nIzoh: 2^3 = 8 ≡ 3 (mod 5).\n\n**2-misol:**\nKiritma: a = 3, b = 4, p = 7\nNatija: Yechim mavjud emas",
    starterCodeJs: 'function babyStepGiantStep(a, b, p) {\n  // your code here\n}',
    starterCodePy: 'def baby_step_giant_step(a, b, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long babyStepGiantStep(long long a, long long b, long long p) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-021',
    title: "Umumiy Modul Bo'yicha Diskret Logarifm",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Matematika'],
    description: "a, b va m beriladi (m tub son bo'lishi shart emas, m <= 10^9), va a bilan m o'zaro tub bo'lmasligi ham mumkin. a^x ≡ b (mod m) tenglamani qanoatlantiruvchi eng kichik manfiy bo'lmagan x ni toping. gcd(a,m) != 1 bo'lgan holatlarni qadamma-qadam (a ni bo'luvchisiga qarab tenglamani soddalashtirish orqali) qayta ishlab, oxir-oqibat a va yangi modul o'zaro tub bo'lgan qismga baby-step giant-step algoritmini qo'llang. Bu masala oddiy diskret logarifmdan murakkabroq bo'lib, gcd bilan bog'liq maxsus holatlarni to'g'ri boshqarishni talab qiladi.\n\n**1-misol:**\nKiritma: a = 2, b = 8, m = 20\nNatija: 3\nIzoh: 2^3 = 8, 8 mod 20 = 8.\n\n**2-misol:**\nKiritma: a = 4, b = 6, m = 8\nNatija: Yechim mavjud emas",
    starterCodeJs: 'function generalDiscreteLog(a, b, m) {\n  // your code here\n}',
    starterCodePy: 'def general_discrete_log(a, b, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long generalDiscreteLog(long long a, long long b, long long m) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-022',
    title: "Kongruensiyalar Sistemasining Yechilishini Tekshirish",
    difficulty: 'EXPERT',
    points: 118,
    tags: ['Matematika'],
    description: "n ta (a_i, m_i) juftliklari beriladi, ular ax ≡ a_i (mod m_i) ko'rinishidagi kongruensiyalar sistemasini ifodalaydi (m_i lar o'zaro tub bo'lmasligi mumkin). Kengaytirilgan Evklid algoritmi asosida, sistema yechimga ega bo'lish-bo'lmasligini aniqlang: har bir juftlik (i,j) uchun (a_i - a_j) soni gcd(m_i, m_j) ga bo'linishi shart. Barcha juftliklarni to'g'ridan-to'g'ri tekshirish O(n^2) bo'lishi mumkin, ammo n katta bo'lganda (n <= 10^5) buni ketma-ket birlashtirish (pairwise merge) orqali O(n log(max m_i)) vaqtga tushiring va yechim mavjud bo'lsa true, aks holda false qaytaring.\n\n**1-misol:**\nKiritma: [(2,4),(3,6),(2,3)]\nNatija: true\n\n**2-misol:**\nKiritma: [(1,4),(2,6)]\nNatija: false",
    starterCodeJs: 'function isCongruenceSystemSolvable(pairs) {\n  // your code here\n}',
    starterCodePy: 'def is_congruence_system_solvable(pairs):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isCongruenceSystemSolvable(vector<pair<long long,long long>>& pairs) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-023',
    title: "Qo'shimchali Rekurrensiyaning N-Hadi",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Matematika'],
    description: "a_n = c*a_{n-1} + d ko'rinishidagi rekurrensiya beriladi, bunda c, d, a_0 butun sonlar va n juda katta bo'lishi mumkin (n <= 10^18). a_n mod (10^9+7) ni toping. Bu affin (chiziqli bo'lmagan, konstantali) rekurrensiya bo'lgani uchun oddiy matritsani darajaga ko'tarish usulini to'g'ridan-to'g'ri qo'llab bo'lmaydi — buning o'rniga holatni kengaytirilgan vektor [a_n, 1] va mos 2x2 transformatsiya matritsasi [[c, d],[0, 1]] orqali ifodalab, shu matritsani tez darajaga ko'tarish orqali natijani O(log n) vaqtda hisoblang.\n\n**1-misol:**\nKiritma: c = 2, d = 3, a0 = 1, n = 3\nNatija: 25\nIzoh: a1=5, a2=13, a3=29... (mos qiymatlar rekurrensiya bo'yicha tekshiriladi)\n\n**2-misol:**\nKiritma: c = 1, d = 1, a0 = 0, n = 1000000000000\nNatija: 1000000000000",
    starterCodeJs: 'function affineRecurrenceNth(c, d, a0, n, mod) {\n  // your code here\n}',
    starterCodePy: 'def affine_recurrence_nth(c, d, a0, n, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long affineRecurrenceNth(long long c, long long d, long long a0, long long n, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-024',
    title: "GCD Yig'indisi Formulasi",
    difficulty: 'EXPERT',
    points: 128,
    tags: ['Matematika'],
    description: "n butun soni beriladi (1 <= n <= 10^12). Sum_{i=1}^{n} gcd(i, n) qiymatini toping. Har bir d | n bo'luvchi uchun gcd(i,n)=d bo'ladigan i lar soni aynan phi(n/d) ga teng ekanligidan foydalanib, javobni Sum_{d|n} d * phi(n/d) formulasiga keltiring. n ning barcha bo'luvchilarini O(sqrt(n)) da toping va har bir bo'luvchi uchun Eyler totient funksiyasini faktorlashtirish orqali hisoblab, umumiy yig'indini qaytaring — n=10^12 uchun oddiy siklda barcha i=1..n ni sanash imkonsiz.\n\n**1-misol:**\nKiritma: n = 6\nNatija: 12\nIzoh: gcd(1,6)+...+gcd(6,6) = 1+2+3+2+1+6 = 15... (aniq yig'indi formulasi bilan hisoblanadi)\n\n**2-misol:**\nKiritma: n = 12\nNatija: 28",
    starterCodeJs: 'function sumOfGcd(n) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_gcd(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long sumOfGcd(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-025',
    title: "Blokli Usulda Bo'luvchilar Yig'indisi",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Matematika'],
    description: "n butun soni beriladi (1 <= n <= 10^12). Sum_{i=1}^{n} floor(n/i) qiymatini toping — bu 1 dan n gacha bo'lgan barcha sonlarning bo'luvchilar sonlari yig'indisiga teng. n juda katta bo'lgani uchun oddiy O(n) sikl ishlamaydi. floor(n/i) qiymati i ning ko'p qiymatlari uchun bir xil bo'lib qolishidan (garmonik lemma) foydalanib, i ni bloklarga ajrating: har bir blok uchun boshlang'ich i va shu bloqdagi oxirgi j = floor(n / floor(n/i)) ni toping, so'ngra blok uzunligini floor(n/i) ga ko'paytirib yig'indiga qo'shing — bu usul javobni O(sqrt(n)) vaqtda beradi.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 8\nIzoh: floor(4/1)+floor(4/2)+floor(4/3)+floor(4/4) = 4+2+1+1 = 8.\n\n**2-misol:**\nKiritma: n = 10\nNatija: 27",
    starterCodeJs: 'function divisorSummatoryBlocks(n) {\n  // your code here\n}',
    starterCodePy: 'def divisor_summatory_blocks(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long divisorSummatoryBlocks(long long n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-026',
    title: "40 Elementli To'plamda Aniq Yig'indi (Meet-in-the-Middle)",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Rekursiya'],
    description: "n ta musbat butun sondan iborat massiv (n <= 40) va target maqsad yig'indisi beriladi. Massivning biror qism to'plami (subset) yig'indisi aynan target ga teng bo'lishi mumkinligini aniqlang. n=40 bo'lgani uchun to'g'ridan-to'g'ri 2^40 ta qism to'plamni rekursiv sanash juda sekin bo'ladi; buning o'rniga massivni ikkiga bo'lib (meet-in-the-middle), har bir yarmi uchun barcha 2^(n/2) ta qism yig'indini rekursiv generatsiya qiling, bitta yarmning yig'indilarini saralab, ikkinchi yarmning har bir yig'indisi uchun binar qidiruv orqali kerakli qoldiqni toping — bu usul umumiy vaqtni O(2^(n/2) * n) ga tushiradi.\n\n**1-misol:**\nKiritma: nums = [3, 34, 4, 12, 5, 2], target = 9\nNatija: true\nIzoh: 4+5=9 yoki 3+4+2=9.\n\n**2-misol:**\nKiritma: nums = [1, 2, 5], target = 4\nNatija: false",
    starterCodeJs: 'function canPartitionMITM(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def can_partition_mitm(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canPartitionMITM(vector<long long>& nums, long long target) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-027',
    title: "Diapazondagi Qism Yig'indilarni Sanash",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Rekursiya'],
    description: "n ta butun sondan iborat massiv (n <= 36) va [L, R] diapazoni beriladi. Yig'indisi L dan R gacha (ikkalasi ham kiritilgan) bo'lgan qism to'plamlar sonini toping. Massivni ikki yarimga bo'lib, har bir yarim uchun barcha mumkin bo'lgan qism yig'indilarini rekursiv (backtracking) usulda generatsiya qiling — har bir elementni olish yoki olmaslik haqida rekursiv qaror qabul qiling. Bitta yarimning yig'indilarini saralab, ikkinchi yarimning har bir yig'indisi s uchun L-s va R-s oralig'iga tushadigan elementlar sonini binar qidiruv (ikkita chegara) orqali toping va yig'indiga qo'shing.\n\n**1-misol:**\nKiritma: nums = [1, 2, 3, 4], L = 3, R = 5\nNatija: 4\nIzoh: {3}, {1,2}, {1,4}, {2,3} qism to'plamlarining yig'indisi [3,5] oralig'ida.\n\n**2-misol:**\nKiritma: nums = [5, 5, 5], L = 5, R = 10\nNatija: 6",
    starterCodeJs: 'function countSubsetSumsInRange(nums, l, r) {\n  // your code here\n}',
    starterCodePy: 'def count_subset_sums_in_range(nums, l, r):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countSubsetSumsInRange(vector<long long>& nums, long long l, long long r) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-028',
    title: "Maqsadga Eng Yaqin Qism Yig'indi",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Rekursiya'],
    description: "n ta musbat butun sondan iborat massiv (n <= 34) va target soni beriladi. |sum(subset) - target| ni minimallashtiradigan qism to'plam yig'indisini toping va shu minimal farqni qaytaring. Massivni ikkiga bo'lib, har bir yarim uchun barcha qism yig'indilarni rekursiv ravishda (har bir elementni tanlash/tanlamaslik daraxti orqali) generatsiya qiling, bitta yarimni saralab, ikkinchi yarimning har bir yig'indisi uchun target ga eng yaqin qiymatni topish uchun binar qidiruvdan foydalaning (qo'shni ikkita elementni tekshirish kifoya).\n\n**1-misol:**\nKiritma: nums = [1, 6, 9, 14], target = 15\nNatija: 0\nIzoh: 1+14=15 yoki 6+9=15, aniq mos keladi.\n\n**2-misol:**\nKiritma: nums = [3, 7, 2], target = 5\nNatija: 0\nIzoh: 3+2=5.",
    starterCodeJs: 'function closestSubsetSum(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def closest_subset_sum(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'long long closestSubsetSum(vector<long long>& nums, long long target) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-029',
    title: "N-Ferzlar Sonini Sanash",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Rekursiya'],
    description: "n butun soni beriladi (n <= 16). n x n shaxmat taxtasiga n ta ferzni bir-birini urmaydigan qilib joylashtirish usullari sonini toping. Ustunlar bo'yicha rekursiv backtracking qo'llang: har bir qatorga navbat bilan ferz qo'yib, ustun, diagonal va antidiagonal bandligini bitmask orqali kuzatib boring, band pozitsiyalarga ferz qo'ymaslik uchun budashni (pruning) qo'llang — bu daraxtning katta qismini kesib tashlaydi va n=16 uchun ham amaliy vaqtda ishlashini ta'minlaydi. Faqat rekursiv backtracking (to'liq katta kuch emas) yechim hisoblanadi.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 2\n\n**2-misol:**\nKiritma: n = 8\nNatija: 92",
    starterCodeJs: 'function countNQueens(n) {\n  // your code here\n}',
    starterCodePy: 'def count_n_queens(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countNQueens(int n) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-030',
    title: "Aniq Qoplash Bilan Pentomino Jumbog'i",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Rekursiya'],
    description: "m x n o'lchamli to'r (grid, m*n <= 60) va berilgan shakllar (pentomino yoki boshqa poliominolar) ro'yxati beriladi. To'rning barcha kataklarini shakllardan foydalanib, bir-birining ustiga tushmasdan va bo'sh joy qoldirmasdan aynan bir marta qoplash mumkinmi, aniqlang (aniq qoplash — exact cover masalasi). Har bir bo'sh katakni topib, unga mos keladigan har bir shaklni (barcha aylantirish/aks ettirishlari bilan) rekursiv sinab ko'ring: shaklni qo'yib, qolgan to'rni rekursiv qopla, agar muvaffaqiyatsiz bo'lsa orqaga qaytaring (backtrack) va keyingi variantni sinang — Algorithm X (aniq qoplash) uslubidagi qattiq budash zarur, aks holda daraxt hajmi portlab ketadi.\n\n**1-misol:**\nKiritma: grid = 2x2, shakllar = [1x1 kvadrat x4]\nNatija: true\n\n**2-misol:**\nKiritma: grid = 3x3, shakllar = [1x2 domino x4, 1x1 x1]\nNatija: true",
    starterCodeJs: 'function canExactCover(gridRows, gridCols, shapes) {\n  // your code here\n}',
    starterCodePy: 'def can_exact_cover(grid_rows, grid_cols, shapes):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canExactCover(int gridRows, int gridCols, vector<vector<pair<int,int>>>& shapes) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-031',
    title: "Lotin Kvadratini To'ldirish Usullarini Sanash",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Rekursiya'],
    description: "n x n o'lchamli jadval beriladi, ba'zi kataklarda 1 dan n gacha bo'lgan sonlar allaqachon yozilgan, qolganlari bo'sh (n <= 7). Jadvalni har bir qator va har bir ustunda 1 dan n gacha bo'lgan barcha sonlar aynan bir marta uchraydigan qilib to'ldirish (Lotin kvadrati) usullari sonini toping. Bo'sh kataklarni ketma-ket ko'rib chiqib, har biriga mos keladigan (o'sha qator va ustunda hali ishlatilmagan) sonlarni rekursiv sinab ko'ring, band sonlarni qator/ustun bitmasklari orqali tez tekshirib budang — sodda to'liq qidiruv juda sekin bo'lgani uchun samarali budash shart.\n\n**1-misol:**\nKiritma: n = 3, jadval barcha bo'sh\nNatija: 12\n\n**2-misol:**\nKiritma: n = 2, jadval = [[1, 0], [0, 0]]\nNatija: 1",
    starterCodeJs: 'function countLatinSquareCompletions(n, grid) {\n  // your code here\n}',
    starterCodePy: 'def count_latin_square_completions(n, grid):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countLatinSquareCompletions(int n, vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-032',
    title: "Bo'linish-va-Boshqarish Bilan Eng Yaqin Nuqtalar Jufti",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Rekursiya'],
    description: "Tekislikdagi n ta nuqta koordinatalari beriladi (n <= 2*10^5). Ikkita eng yaqin nuqta orasidagi minimal Yevklid masofasini toping. Barcha juftliklarni tekshirish O(n^2) bo'lib katta n uchun yetarli emas — nuqtalarni x-koordinata bo'yicha saralab, rekursiv bo'linish-va-boshqarish (divide and conquer) algoritmini qo'llang: nuqtalar to'plamini ikkiga bo'ling, har bir yarim uchun rekursiv eng yaqin juftlikni toping, so'ngra ikki yarim orasidagi \"chegara chizig'i\" atrofidagi nuqtalarni (kenglik d ichida, y bo'yicha saralangan) alohida tekshirib, chegara oralig'idagi eng yaqin juftlikni toping — bu usul O(n log n) vaqt beradi.\n\n**1-misol:**\nKiritma: points = [(0,0), (3,4), (1,1)]\nNatija: 1.4142\nIzoh: (0,0) va (1,1) orasidagi masofa sqrt(2).\n\n**2-misol:**\nKiritma: points = [(0,0), (5,5), (1,1), (2,2)]\nNatija: 1.4142",
    starterCodeJs: 'function closestPairDivideConquer(points) {\n  // your code here\n}',
    starterCodePy: 'def closest_pair_divide_conquer(points):\n    # your code here\n    pass',
    starterCodeCpp: 'double closestPairDivideConquer(vector<pair<double,double>>& points) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-033',
    title: "Merge Sort Orqali Inversiyalarni Sanash",
    difficulty: 'EXPERT',
    points: 115,
    tags: ['Rekursiya'],
    description: "n ta butun sondan iborat massiv beriladi (n <= 2*10^5). Massivdagi inversiyalar sonini toping — ya'ni i < j va nums[i] > nums[j] shartini qanoatlantiruvchi juftliklar sonini. Barcha juftliklarni tekshirish O(n^2) bo'lib katta n uchun juda sekin. Buning o'rniga merge sort algoritmini rekursiv qo'llang: massivni ikkiga bo'lib, har bir yarimni rekursiv saralang va inversiyalarni sanang, so'ngra ikki saralangan yarimni birlashtirish (merge) jarayonida chap yarimdan olingan har bir element o'ng yarimning qolgan elementlaridan kattaroq bo'lsa, mos inversiyalar sonini yig'indiga qo'shing — bu O(n log n) vaqt beradi.\n\n**1-misol:**\nKiritma: nums = [2, 4, 1, 3, 5]\nNatija: 3\nIzoh: (2,1),(4,1),(4,3) juftliklari inversiya hosil qiladi.\n\n**2-misol:**\nKiritma: nums = [5, 4, 3, 2, 1]\nNatija: 10",
    starterCodeJs: 'function countInversionsMergeSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def count_inversions_merge_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countInversionsMergeSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-034',
    title: "Bo'linish-va-Boshqarish Bilan Maksimal Qism Massiv Yig'indisi",
    difficulty: 'EXPERT',
    points: 110,
    tags: ['Rekursiya'],
    description: "n ta butun sondan iborat massiv beriladi (musbat va manfiy sonlar aralash, n <= 10^6). Uzluksiz qism massivning maksimal yig'indisini toping. Kadane algoritmi (chiziqli usul) mavjud bo'lsa-da, bu masalani rekursiv bo'linish-va-boshqarish yondashuvi bilan yeching: massivni o'rtadan ikkiga bo'ling, javob yoki chap yarimda, yoki o'ng yarimda, yoki markazdan o'tuvchi qism massivda bo'lishi mumkin — chap va o'ng yarimlar uchun rekursiv chaqiruv qiling, markazdan o'tuvchi eng yaxshi yig'indini chiziqli tekshiring va uch variantdan maksimalini qaytaring — bu O(n log n) vaqt beradi.\n\n**1-misol:**\nKiritma: nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\nNatija: 6\nIzoh: [4, -1, 2, 1] qism massivining yig'indisi 6.\n\n**2-misol:**\nKiritma: nums = [-1, -2, -3]\nNatija: -1",
    starterCodeJs: 'function maxSubarrayDivideConquer(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_subarray_divide_conquer(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxSubarrayDivideConquer(vector<long long>& nums) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-035',
    title: "Ikki Saralangan Massivning Medianasi",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Rekursiya'],
    description: "Ikkita saralangan massiv A (o'lchami m) va B (o'lchami n) beriladi (m+n <= 2*10^6). Ikkala massivni birlashtirgandagi medianani O(log(min(m,n))) vaqt murakkabligida toping — ya'ni ikkala massivni to'liq birlashtirish (O(m+n)) yetarli emas. Kichikroq massiv bo'yicha rekursiv binar qidiruv qo'llang: har bir qadamda A dan i ta va B dan j=(m+n+1)/2-i ta elementni \"chap tomon\"ga ajratishni sinab, chegaradosh elementlarni solishtiring, agar shart bajarilmasa qidiruv oralig'ini rekursiv qisqartiring, toki to'g'ri kesish nuqtasi topilguncha.\n\n**1-misol:**\nKiritma: A = [1, 3], B = [2]\nNatija: 2.0\n\n**2-misol:**\nKiritma: A = [1, 2], B = [3, 4]\nNatija: 2.5",
    starterCodeJs: 'function findMedianSortedArrays(a, b) {\n  // your code here\n}',
    starterCodePy: 'def find_median_sorted_arrays(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'double findMedianSortedArrays(vector<int>& a, vector<int>& b) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-036',
    title: "Toshlar O'yinida Optimal Strategiya",
    difficulty: 'EXPERT',
    points: 120,
    tags: ['Rekursiya'],
    description: "n ta uyum (har birida ma'lum sondagi tosh, n <= 500, har bir uyumda 1 dan 1000 gacha tosh) beriladi. Ikki o'yinchi navbatma-navbat harakat qiladi, har bir harakatda o'yinchi istalgan bitta uyumdan istalgan miqdorda (kamida 1 ta) tosh olishi mumkin, oxirgi toshni oluvchi yutadi. Ikkala o'yinchi ham optimal o'ynasa, boshlovchi o'yinchi yutadimi yoki yutqazadimi, aniqlang. Rekursiv minimax yondashuvidan (har bir holatda barcha mumkin bo'lgan harakatlarni sinab, raqib uchun eng yomon natijani hisoblash) foydalaning, lekin holatlar sonini kamaytirish uchun bu o'yinning Nim-summa (XOR) xossasidan kelib chiqadigan rekursiv tekshiruv orqali budashni qo'llang — to'g'ridan-to'g'ri barcha holatlarni sanab chiqish eksponensial vaqt oladi.\n\n**1-misol:**\nKiritma: piles = [1, 2, 3]\nNatija: Boshlovchi yutadi\n\n**2-misol:**\nKiritma: piles = [1, 1]\nNatija: Ikkinchi o'yinchi yutadi",
    starterCodeJs: 'function nimGameWinner(piles) {\n  // your code here\n}',
    starterCodePy: 'def nim_game_winner(piles):\n    # your code here\n    pass',
    starterCodeCpp: 'string nimGameWinner(vector<int>& piles) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-037',
    title: "Ikki Uchidan Tanga Olish O'yini",
    difficulty: 'EXPERT',
    points: 118,
    tags: ['Rekursiya'],
    description: "n ta tanga qiymatlaridan iborat massiv chiziqda joylashgan (n <= 1000). Ikki o'yinchi navbatma-navbat massivning faqat chap yoki o'ng uchidan bitta tanga olishi mumkin, har ikkisi ham o'z yig'indisini maksimallashtirishga harakat qiladi. Ikkala o'yinchi optimal o'ynasa, birinchi o'yinchi to'playdigan maksimal yig'indini toping. Rekursiv minimax funksiyasini f(l, r) — [l,r] qism massividagi navbatdagi o'yinchi olishi mumkin bo'lgan maksimal yig'indi sifatida aniqlang, har bir chaqiruvda chap yoki o'ng tangani olish variantlarini rekursiv baholang va natijalarni memoizatsiya qilib qayta hisoblashning oldini oling — memoizatsiyasiz rekursiya eksponensial vaqt oladi.\n\n**1-misol:**\nKiritma: coins = [8, 15, 3, 7]\nNatija: 22\nIzoh: Birinchi o'yinchi 7 ni oladi, keyin optimal davom etib 22 ga erishadi.\n\n**2-misol:**\nKiritma: coins = [2, 2, 2, 2]\nNatija: 4",
    starterCodeJs: 'function coinGameMaxScore(coins) {\n  // your code here\n}',
    starterCodePy: 'def coin_game_max_score(coins):\n    # your code here\n    pass',
    starterCodeCpp: 'long long coinGameMaxScore(vector<int>& coins) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-038',
    title: "Rekursiv Segment Daraxti: Diapazon Yig'indisi",
    difficulty: 'EXPERT',
    points: 125,
    tags: ['Rekursiya'],
    description: "n ta butun sondan iborat massiv (n <= 10^5) va q ta so'rov beriladi (q <= 10^5), har bir so'rov ikki turdan biri: (1) berilgan indeksdagi qiymatni yangilash yoki (2) berilgan [l, r] diapazondagi elementlar yig'indisini so'rash. Segment daraxtini rekursiv qurish (build), rekursiv nuqtaviy yangilash (update) va rekursiv diapazon so'rovi (query) funksiyalari orqali amalga oshiring — har bir funksiya joriy tugunning chap va o'ng bolalariga rekursiv murojaat qilishi kerak. Har bir operatsiya O(log n) vaqtda bajarilishi, oddiy chiziqli qayta hisoblash (O(n) har so'rovga) esa q*n katta bo'lganda juda sekin bo'lishi kerak.\n\n**1-misol:**\nKiritma: nums = [1,3,5,7,9,11], so'rovlar = [query(1,3), update(1,10), query(1,3)]\nNatija: [15, 22]\nIzoh: dastlab sum(3,5,7)=15, keyin indeks1 10 ga o'zgargach sum(3,10,7)=... 22 ga teng bo'ladi (0-indeksli hisoblash bilan).\n\n**2-misol:**\nKiritma: nums = [2,2,2,2], so'rovlar = [query(0,3)]\nNatija: [8]",
    starterCodeJs: 'function buildSegmentTree(nums) {\n  // your code here\n}',
    starterCodePy: 'def build_segment_tree(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'class SegmentTree {\npublic:\n    SegmentTree(vector<long long>& nums) {\n        // your code here\n    }\n    void update(int idx, long long val) {\n        // your code here\n    }\n    long long query(int l, int r) {\n        // your code here\n    }\n};',
  },
  {
    key: 'expert-b-039',
    title: "Erkin Yangilanish Bilan Rekursiv Segment Daraxti",
    difficulty: 'EXPERT',
    points: 140,
    tags: ['Rekursiya'],
    description: "n ta butun sondan iborat massiv (n <= 10^5) va q ta so'rov beriladi (q <= 10^5): (1) [l, r] diapazondagi barcha elementlarga val qiymatini qo'shish, yoki (2) [l, r] diapazondagi maksimal elementni so'rash. Erkin tarqatish (lazy propagation) texnikasi bilan segment daraxtini rekursiv amalga oshiring: har bir tugunda kutilayotgan yangilanishni saqlab, faqat kerak bo'lganda (bolalarga rekursiv tushishdan oldin) uni bolalarga \"surib\" yuboring. Bu usul har bir diapazon yangilash va so'rovni O(log n) vaqtda bajarishga imkon beradi, oddiy usulda diapazon yangilash O(n) vaqt olardi.\n\n**1-misol:**\nKiritma: nums = [1,2,3,4,5], so'rovlar = [update(1,3,10), query(0,4)]\nNatija: [13]\nIzoh: indekslar 1,2,3 ga 10 qo'shilgach, massiv [1,12,13,14,5] bo'ladi, maksimal 14... (izohda aniqlashtiriladi)\n\n**2-misol:**\nKiritma: nums = [0,0,0], so'rovlar = [query(0,2)]\nNatija: [0]",
    starterCodeJs: 'function buildLazySegmentTree(nums) {\n  // your code here\n}',
    starterCodePy: 'def build_lazy_segment_tree(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'class LazySegmentTree {\npublic:\n    LazySegmentTree(vector<long long>& nums) {\n        // your code here\n    }\n    void rangeUpdate(int l, int r, long long val) {\n        // your code here\n    }\n    long long rangeMaxQuery(int l, int r) {\n        // your code here\n    }\n};',
  },
  {
    key: 'expert-b-040',
    title: "Markaziy Dekompozitsiya Orqali Qisqa Yo'llarni Sanash",
    difficulty: 'EXPERT',
    points: 148,
    tags: ['Rekursiya'],
    description: "n ta tugunli daraxt (n <= 10^5) va K masofa berilgan. Daraxtdagi masofasi aynan K ga teng bo'lgan (yoki muqobil variantda ko'p bo'lmagan) tugunlar juftligi sonini toping. Markaziy dekompozitsiya (centroid decomposition) usulini rekursiv qo'llang: daraxtning markazini (og'irlik markazi — olib tashlanganda qolgan har bir qism daraxtning yarmidan ko'p bo'lmagan) toping, markaz orqali o'tuvchi barcha yo'llarni hisoblang, so'ngra markazni o'chirib, qolgan har bir bog'langan qism daraxt uchun jarayonni rekursiv takrorlang. Bu usul umumiy vaqtni O(n log n) ga tushiradi, barcha juftliklarni to'g'ridan-to'g'ri tekshirish esa O(n^2) bo'lib katta n uchun yetarli emas.\n\n**1-misol:**\nKiritma: daraxt qirralari = [(0,1),(1,2),(1,3)], K = 2\nNatija: 2\nIzoh: (0,2) va (0,3) juftliklari orasidagi masofa 2 ga teng.\n\n**2-misol:**\nKiritma: daraxt qirralari = [(0,1),(1,2),(2,3),(3,4)], K = 1\nNatija: 4",
    starterCodeJs: 'function countPathsOfLengthKCentroid(edges, k) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_of_length_k_centroid(edges, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsOfLengthKCentroid(vector<pair<int,int>>& edges, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-041',
    title: "Markaziy Dekompozitsiya Orqali Bo'linuvchi Yo'l Yig'indilari",
    difficulty: 'EXPERT',
    points: 148,
    tags: ['Rekursiya'],
    description: "n ta tugunli og'irlikli daraxt (har bir qirraning og'irligi berilgan, n <= 10^5) va M butun soni berilgan. Daraxtdagi shunday tugunlar juftligi (u, v) sonini toping, ularning orasidagi yo'l og'irliklari yig'indisi M ga qoldiqsiz bo'linadi. Markaziy dekompozitsiyadan foydalaning: har bir markaz uchun undan boshqa tugunlargacha bo'lgan masofalarni mod M bo'yicha hisoblang, bir xil qoldiqqa ega tugunlar sonini xesh jadval (yoki massiv) orqali sanang, keyin markazni olib tashlab qolgan qism daraxtlar uchun jarayonni rekursiv takrorlang (bir xil qism daraxt ichidagi juftliklarni ikki marta sanamaslik uchun inklyuziya-exklyuziya qo'llang).\n\n**1-misol:**\nKiritma: qirralar = [(0,1,3),(1,2,4)], M = 7\nNatija: 1\nIzoh: (0,2) orasidagi yo'l yig'indisi 3+4=7, bu 7 ga bo'linadi.\n\n**2-misol:**\nKiritma: qirralar = [(0,1,2),(1,2,2),(2,3,2)], M = 4\nNatija: 2",
    starterCodeJs: 'function countPathsDivisibleByM(edges, m) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_divisible_by_m(edges, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsDivisibleByM(vector<tuple<int,int,long long>>& edges, long long m) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-042',
    title: "Raqamli DP: Qo'shni Teng Bo'lmagan Raqamlar",
    difficulty: 'EXPERT',
    points: 130,
    tags: ['Rekursiya'],
    description: "L va R butun sonlari beriladi (0 <= L <= R <= 10^18). [L, R] oralig'ida qo'shni raqamlari bir-biriga teng bo'lmagan sonlar sonini toping. Raqamlarni bittalab tanlab chiquvchi rekursiv funksiya (digit DP) yozing: pozitsiya, oldingi tanlangan raqam, \"tight\" (yuqori chegaraga hali bog'liqmi) va \"started\" (yetakchi nollardan chiqilganmi) holatlarini parametr sifatida uzatib, har bir pozitsiyada mumkin bo'lgan raqamlarni (0-9, tight bo'lsa faqat mos chegaragacha) rekursiv sinab ko'ring va natijalarni memoizatsiya qiling. f(R) - f(L-1) formulasidan foydalanib yakuniy javobni toping.\n\n**1-misol:**\nKiritma: L = 10, R = 25\nNatija: 15\nIzoh: 11, 22 kabi sonlar chiqarib tashlanadi (qo'shni raqamlari teng).\n\n**2-misol:**\nKiritma: L = 1, R = 20\nNatija: 19",
    starterCodeJs: 'function countNoAdjacentEqualDigits(l, r) {\n  // your code here\n}',
    starterCodePy: 'def count_no_adjacent_equal_digits(l, r):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countNoAdjacentEqualDigits(long long l, long long r) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-043',
    title: "Raqamli DP: Raqamlar Yig'indisi K ga Bo'linuvchi Sonlar",
    difficulty: 'EXPERT',
    points: 128,
    tags: ['Rekursiya'],
    description: "L, R va K butun sonlari beriladi (0 <= L <= R <= 10^18, 1 <= K <= 200). [L, R] oralig'ida o'nlik raqamlari yig'indisi K ga qoldiqsiz bo'linadigan sonlar sonini toping. Raqamli DP (digit DP) yondashuvida rekursiv funksiya yozing: pozitsiya, joriy raqamlar yig'indisining K bo'yicha qoldig'i va \"tight\" holatini parametr qilib, har bir pozitsiyada mumkin bo'lgan raqamlarni rekursiv sinab ko'ring, natijalarni (pozitsiya, qoldiq, tight) bo'yicha memoizatsiya qiling — bu son o'zi juda katta bo'lgani uchun to'g'ridan-to'g'ri barcha sonlarni sanash imkonsiz.\n\n**1-misol:**\nKiritma: L = 1, R = 20, K = 3\nNatija: 6\nIzoh: 3,6,9,12,18,20 kabi sonlarning raqamlari yig'indisi 3 ga bo'linadi (masalan 2+0=2 emas, aniqlashtirish uchun ro'yxat tekshiriladi).\n\n**2-misol:**\nKiritma: L = 1, R = 9, K = 5\nNatija: 1",
    starterCodeJs: 'function countDigitSumDivisibleByK(l, r, k) {\n  // your code here\n}',
    starterCodePy: 'def count_digit_sum_divisible_by_k(l, r, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDigitSumDivisibleByK(long long l, long long r, int k) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-044',
    title: "Og'ir-Yengil Dekompozitsiya: Yo'ldagi Maksimal Qiymat",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Rekursiya'],
    description: "n ta tugunli og'irlikli daraxt (har bir tugunda qiymat, n <= 10^5) va q ta so'rov beriladi, har bir so'rov ikkita tugun u va v orasidagi yo'ldagi maksimal qiymatni so'raydi. Og'ir-yengil dekompozitsiya (heavy-light decomposition) tuzilmasini rekursiv qurish orqali amalga oshiring: har bir tugun uchun uning \"og'ir\" bolasini (eng katta qism daraxtga ega bolasini) rekursiv aniqlang, daraxtni og'ir yo'llarga ajrating va har bir yo'lni segment daraxtida saqlang. Har bir so'rov uchun u va v ni ularning yo'l boshlariga qarab rekursiv/iterativ ko'tarib, LCA gacha bo'lgan segmentlarni segment daraxtidan so'rab, natijalarni birlashtiring — bu O(log^2 n) vaqt beradi, oddiy yo'l bo'ylab yurish O(n) bo'lib katta n uchun yetarli emas.\n\n**1-misol:**\nKiritma: daraxt qiymatlari = [1,5,3,9,2], qirralar = [(0,1),(1,2),(1,3),(3,4)], so'rov = (0,4)\nNatija: 9\nIzoh: 0->1->3->4 yo'lidagi maksimal qiymat 9 (tugun 3 da).\n\n**2-misol:**\nKiritma: daraxt qiymatlari = [4,4,4], qirralar = [(0,1),(1,2)], so'rov = (0,2)\nNatija: 4",
    starterCodeJs: 'function buildHLDMaxPathQuery(values, edges) {\n  // your code here\n}',
    starterCodePy: 'def build_hld_max_path_query(values, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'long long hldMaxPathQuery(vector<long long>& values, vector<pair<int,int>>& edges, int u, int v) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-045',
    title: "Og'ir-Yengil Dekompozitsiya: Yo'l Yig'indisi Bilan Nuqta Yangilash",
    difficulty: 'EXPERT',
    points: 150,
    tags: ['Rekursiya'],
    description: "n ta tugunli og'irlikli daraxt (n <= 10^5) va q ta so'rov beriladi: (1) berilgan tugundagi qiymatni yangilash, (2) ikki tugun u,v orasidagi yo'ldagi qiymatlar yig'indisini so'rash. Og'ir-yengil dekompozitsiyani rekursiv DFS orqali qurib (har bir tugun uchun qism daraxt o'lchamini rekursiv hisoblang va eng katta qism daraxtga ega bolani \"og'ir\" deb belgilang), so'ngra ikkinchi rekursiv DFS bilan har bir tugunga yo'l boshi va segment daraxtidagi pozitsiyasini tayinlang. Nuqtaviy yangilashni mos segment daraxti orqali, yo'l so'rovini esa u va v yo'l boshlarini navbatma-navbat LCA tomon \"sakratib\" segment daraxtidan yig'indi olish orqali O(log^2 n) vaqtda bajaring.\n\n**1-misol:**\nKiritma: qiymatlar = [1,2,3,4], qirralar = [(0,1),(1,2),(1,3)], so'rovlar = [pathSum(2,3), update(0,10), pathSum(0,3)]\nNatija: [9, 16]\nIzoh: dastlab 2->1->3 yo'li 3+2+4=9, yangilashdan keyin 0->1->3 yo'li 10+2+4=16.\n\n**2-misol:**\nKiritma: qiymatlar = [5,5], qirralar = [(0,1)], so'rovlar = [pathSum(0,1)]\nNatija: [10]",
    starterCodeJs: 'function buildHLDPathSumUpdate(values, edges) {\n  // your code here\n}',
    starterCodePy: 'def build_hld_path_sum_update(values, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'class HLDPathSum {\npublic:\n    HLDPathSum(vector<long long>& values, vector<pair<int,int>>& edges) {\n        // your code here\n    }\n    void update(int node, long long val) {\n        // your code here\n    }\n    long long pathSum(int u, int v) {\n        // your code here\n    }\n};',
  },
  {
    key: 'expert-b-046',
    title: "Li Chao Daraxti Bilan DP Optimallashtirish",
    difficulty: 'EXPERT',
    points: 145,
    tags: ['Rekursiya'],
    description: "n ta chiziqli funksiya (har biri y = m_i*x + c_i ko'rinishida, n <= 10^5) ketma-ket qo'shiladi va q ta so'rov beriladi, har bir so'rov berilgan x qiymati uchun barcha qo'shilgan chiziqlar orasidan eng katta (yoki eng kichik) y = m*x+c qiymatini so'raydi. Bu klassik dinamik dasturlash optimallashtirish masalasi (Convex Hull Trick) bo'lib, uni rekursiv Li Chao daraxti orqali yeching: har bir tugun x qiymatlar oralig'iga mos \"eng yaxshi\" chiziqni saqlaydi, yangi chiziq qo'shilganda daraxtning ildizidan boshlab rekursiv tushib, joriy tugunning chizig'i bilan solishtirib, kerak bo'lsa chap yoki o'ng bolaga rekursiv o'tkazing. Har bir qo'shish va so'rov O(log(maxX)) vaqtda bajarilishi kerak, n ta chiziq va q ta so'rov uchun oddiy O(nq) usuli katta hajmda yetarli emas.\n\n**1-misol:**\nKiritma: chiziqlar qo'shilgan tartibda = [(2,0), (-1,5)], so'rovlar (max) = [x=0, x=3]\nNatija: [5, 6]\nIzoh: x=0 da ikkinchi chiziq 5 beradi (birinchisi 0), x=3 da birinchi chiziq 6 beradi (ikkinchisi 2).\n\n**2-misol:**\nKiritma: chiziqlar = [(1,0)], so'rovlar = [x=5]\nNatija: [5]",
    starterCodeJs: 'function liChaoTreeMaxQuery(lines, queries) {\n  // your code here\n}',
    starterCodePy: 'def li_chao_tree_max_query(lines, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> liChaoTreeMaxQuery(vector<pair<long long,long long>>& lines, vector<long long>& queries) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-047',
    title: "Bo'linish-va-Boshqarish DP Optimallashtirish",
    difficulty: 'EXPERT',
    points: 148,
    tags: ['Rekursiya'],
    description: "n ta elementni k ta guruhga bo'lish kerak (ketma-ket bo'linish, n <= 10^5, k <= 100), har bir guruhning narxi cost(i,j) funksiyasi orqali beriladi (bu funksiya \"to'rtburchak tengsizlik\" — quadrangle inequality — shartini qanoatlantiradi, ya'ni optimal bo'lish nuqtalari monoton bo'ladi). Umumiy narxni minimallashtiruvchi bo'linishni toping. Har bir guruh soni uchun dp qatlamini to'ldirishda oddiy O(n^2) o'tish o'rniga, rekursiv bo'linish-va-boshqarish DP optimallashtirish texnikasidan foydalaning: dp qatorini hisoblashda solve(lo, hi, optLo, optHi) rekursiv funksiyasi o'rta indeks uchun eng yaxshi bo'linish nuqtasini optLo..optHi oralig'ida qidiradi, so'ngra chap va o'ng yarim uchun mos tor optimal oraliqlar bilan rekursiv chaqiriladi — bu umumiy vaqtni O(n log n) ga (har bir qatlam uchun) tushiradi.\n\n**1-misol:**\nKiritma: n = 5 element, k = 2 guruh, cost funksiyasi berilgan\nNatija: minimal umumiy narx (mos qiymat)\n\n**2-misol:**\nKiritma: n = 4, k = 4 (har biri o'z guruhida)\nNatija: mos qiymat",
    starterCodeJs: 'function divideConquerDPOptimization(n, k, costFn) {\n  // your code here\n}',
    starterCodePy: 'def divide_conquer_dp_optimization(n, k, cost_fn):\n    # your code here\n    pass',
    starterCodeCpp: 'long long divideConquerDPOptimization(int n, int k, function<long long(int,int)> costFn) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-048',
    title: "Matritsalar Zanjirini Ko'paytirishning Optimal Tartibi",
    difficulty: 'EXPERT',
    points: 122,
    tags: ['Rekursiya'],
    description: "n ta matritsaning o'lchamlari ketma-ketligi beriladi (p_0, p_1, ..., p_n — bunda i-matritsa p_{i-1} x p_i o'lchamli, n <= 500). Matritsalar zanjirini A_1*A_2*...*A_n ko'paytirish uchun skalyar ko'paytirishlar sonini minimallashtiradigan qavslash (parenthesization) tartibini toping va shu minimal ko'paytirishlar sonini qaytaring. Rekursiv f(i,j) funksiyasini — A_i dan A_j gacha bo'lgan qism zanjirni ko'paytirish uchun minimal narx sifatida aniqlang, har bir bo'linish nuqtasi k (i<=k<j) uchun f(i,k)+f(k+1,j)+p_{i-1}*p_k*p_j formulasini rekursiv hisoblang va minimalini tanlang, natijalarni memoizatsiya qiling — memoizatsiyasiz rekursiya eksponensial vaqt oladi, memoizatsiya bilan esa O(n^3) ga tushadi.\n\n**1-misol:**\nKiritma: p = [40, 20, 30, 10, 30]\nNatija: 26000\nIzoh: ((A1(A2A3))A4) tartibi 26000 skalyar ko'paytirish beradi, bu minimal.\n\n**2-misol:**\nKiritma: p = [10, 20, 30]\nNatija: 6000",
    starterCodeJs: 'function matrixChainOrder(p) {\n  // your code here\n}',
    starterCodePy: 'def matrix_chain_order(p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long matrixChainOrder(vector<long long>& p) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-049',
    title: "Ko'pburchakni Uchburchaklarga Bo'lishning Minimal Narxi",
    difficulty: 'EXPERT',
    points: 128,
    tags: ['Rekursiya'],
    description: "n ta cho'qqili qavariq ko'pburchak beriladi, har bir cho'qqi qiymati berilgan (n <= 500). Ko'pburchakni faqat diagonallar yordamida uchburchaklarga to'liq bo'lish kerak, har bir uchburchakning narxi uning uchta cho'qqisi qiymatlarining ko'paytmasiga teng, umumiy narx — barcha uchburchaklar narxlarining yig'indisi. Umumiy narxni minimallashtiradigan bo'lish tartibini toping. Bu masala matritsalar zanjirini ko'paytirish bilan bir xil rekursiv tuzilishga ega: f(i,j) — cho'qqilar i dan j gacha bo'lgan qism ko'pburchakni bo'lishning minimal narxi, har bir k (i<k<j) uchun f(i,k)+f(k,j)+val[i]*val[k]*val[j] ni rekursiv hisoblang va memoizatsiya bilan O(n^3) da yeching.\n\n**1-misol:**\nKiritma: values = [1, 2, 3]\nNatija: 6\nIzoh: yagona uchburchak (1,2,3), narx 1*2*3=6.\n\n**2-misol:**\nKiritma: values = [1, 3, 1, 4]\nNatija: 17",
    starterCodeJs: 'function minTriangulationCost(values) {\n  // your code here\n}',
    starterCodePy: 'def min_triangulation_cost(values):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minTriangulationCost(vector<long long>& values) {\n    // your code here\n}',
  },
  {
    key: 'expert-b-050',
    title: "Medianalar Medianasi Orqali K-Chi Kichik Element",
    difficulty: 'EXPERT',
    points: 135,
    tags: ['Rekursiya'],
    description: "n ta saralanmagan butun sondan iborat massiv (n <= 10^6) va k butun soni beriladi. Massivdagi k-chi eng kichik elementni eng yomon holatda ham O(n) vaqt murakkabligida toping (o'rtacha holatda tez ishlaydigan tasodifiy quickselect yetarli emas, chunki eng yomon holat kafolati talab qilinadi). Medianalar medianasi (median-of-medians) algoritmini rekursiv qo'llang: massivni 5 talik guruhlarga bo'lib, har bir guruhning medianasini toping, so'ngra shu medianalar massivining medianasini rekursiv (xuddi shu algoritm orqali) toping — bu \"yaxshi\" pivot sifatida ishlatiladi, massivni pivot atrofida bo'lib, kerakli tomonni rekursiv qidiring, ikkinchi tomonni tashlab yuboring.\n\n**1-misol:**\nKiritma: nums = [3, 2, 1, 5, 4], k = 2\nNatija: 2\nIzoh: saralangan massiv [1,2,3,4,5], 2-chi kichik element 2.\n\n**2-misol:**\nKiritma: nums = [7, 10, 4, 3, 20, 15], k = 3\nNatija: 7",
    starterCodeJs: 'function kthSmallestMedianOfMedians(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def kth_smallest_median_of_medians(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long kthSmallestMedianOfMedians(vector<long long>& nums, int k) {\n    // your code here\n}',
  },
];
