export const problems = [
  {
    key: 'hard-b-001',
    title: "Fibonachchi Sonini Tez Hisoblash",
    difficulty: 'HARD',
    points: 70,
    tags: ['Matematika'],
    description: "n va m (moduli) butun sonlar sifatida beriladi. n-Fibonachchi sonini (F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2)) 2x2 matritsani darajaga tez oshirish usuli yordamida O(log n) vaqt murakkabligida hisoblang va natijani m bo'yicha modul olib qaytaring. n qiymati juda katta (10^18 gacha) bo'lishi mumkin, shu sababli oddiy tsikl orqali hisoblash yetarlicha tez ishlamaydi.\n\n**1-misol:**\nKiritma: n = 10, m = 1000000007\nNatija: 55\n\n**2-misol:**\nKiritma: n = 20, m = 1000000007\nNatija: 6765",
    starterCodeJs: 'function nthFibonacciMod(n, m) {\n  // your code here\n}',
    starterCodePy: 'def nth_fibonacci_mod(n, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nthFibonacciMod(long long n, long long m) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-002',
    title: "Diapazondagi Tub Sonlar Soni",
    difficulty: 'HARD',
    points: 78,
    tags: ['Matematika'],
    description: "L va R butun sonlari berilgan (1 <= L <= R <= 10^12, R - L <= 10^6). [L, R] oralig'ida joylashgan tub sonlar sonini toping. R qiymati juda katta bo'lgani uchun oddiy elash [1..R] xotiraga sig'maydi — segmentli elash (segmented sieve) usulidan foydalaning: avval sqrt(R) gacha bo'lgan tub sonlarni toping, so'ng ular yordamida faqat [L, R] segmentini elang.\n\n**1-misol:**\nKiritma: L = 10, R = 20\nNatija: 4\nIzoh: 11, 13, 17, 19 — jami 4 ta tub son.\n\n**2-misol:**\nKiritma: L = 1, R = 10\nNatija: 4",
    starterCodeJs: 'function countPrimesInRange(L, R) {\n  // your code here\n}',
    starterCodePy: 'def count_primes_in_range(L, R):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPrimesInRange(long long L, long long R) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-003',
    title: "Butun Kvadrat Ildiz",
    difficulty: 'HARD',
    points: 62,
    tags: ['Matematika'],
    description: "Manfiy bo'lmagan butun son x berilgan (x 2^62 gacha bo'lishi mumkin). floor(sqrt(x)) qiymatini, ya'ni x dan katta bo'lmagan eng katta butun kvadrat ildizni, tilning o'rnatilgan sqrt/pow funksiyalaridan foydalanmasdan hisoblang. Ikkilik qidiruv (binary search) yoki Nyuton usulidan foydalaning, chunki x juda katta bo'lganda oddiy tsikl bilan sanash sekin ishlaydi.\n\n**1-misol:**\nKiritma: x = 8\nNatija: 2\nIzoh: 2^2=4 <= 8 < 9=3^2 bo'lgani uchun natija 2.\n\n**2-misol:**\nKiritma: x = 2147483647\nNatija: 46340",
    starterCodeJs: 'function integerSqrt(x) {\n  // your code here\n}',
    starterCodePy: 'def integer_sqrt(x):\n    # your code here\n    pass',
    starterCodeCpp: 'long long integerSqrt(long long x) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-004',
    title: "Xitoy Qoldiqlar Teoremasi",
    difficulty: 'HARD',
    points: 80,
    tags: ['Matematika'],
    description: "Ikkita kongruensiya berilgan: x ≡ r1 (mod m1) va x ≡ r2 (mod m2), bunda m1 va m2 albatta o'zaro tub (coprime) bo'lmasligi ham mumkin. Xitoy qoldiqlar teoremasining umumlashgan ko'rinishidan foydalanib, berilgan ikkala kongruensiyani ham qanoatlantiruvchi eng kichik manfiy bo'lmagan x ni toping. Agar yechim mavjud bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: r1 = 2, m1 = 3, r2 = 3, m2 = 5\nNatija: 8\nIzoh: 8 mod 3 = 2 va 8 mod 5 = 3.\n\n**2-misol:**\nKiritma: r1 = 1, m1 = 4, r2 = 2, m2 = 6\nNatija: -1\nIzoh: gcd(4,6)=2 bo'lib, (2-1) bu songa bo'linmagani uchun yechim yo'q.",
    starterCodeJs: 'function chineseRemainder(r1, m1, r2, m2) {\n  // your code here\n}',
    starterCodePy: 'def chinese_remainder(r1, m1, r2, m2):\n    # your code here\n    pass',
    starterCodeCpp: 'long long chineseRemainder(long long r1, long long m1, long long r2, long long m2) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-005',
    title: "Kombinatsiya Sonini Modul Bo'yicha Hisoblash",
    difficulty: 'HARD',
    points: 72,
    tags: ['Matematika'],
    description: "n, r va tub son p berilgan (0 <= r <= n <= 10^6, p — 10^9 dan katta tub son). C(n, r) mod p qiymatini hisoblang. n juda katta bo'lgani uchun Paskal uchburchagini to'liq qurish mumkin emas — 0 dan n gacha bo'lgan faktoriallarni oldindan hisoblab, modul bo'yicha teskari elementlar (modular inverse, Fermat kichik teoremasi orqali) yordamida O(n) vaqtda yeching.\n\n**1-misol:**\nKiritma: n = 10, r = 3, p = 1000000007\nNatija: 120\n\n**2-misol:**\nKiritma: n = 5, r = 2, p = 1000000007\nNatija: 10",
    starterCodeJs: 'function nCrMod(n, r, p) {\n  // your code here\n}',
    starterCodePy: 'def n_cr_mod(n, r, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nCrMod(long long n, long long r, long long p) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-006',
    title: "N-Xonali Sonlar Ko'paytmasidan Eng Katta Palindrom",
    difficulty: 'HARD',
    points: 84,
    tags: ['Matematika'],
    description: "Butun son n berilgan. Ikkita n-xonali musbat butun sonning ko'paytmasidan hosil bo'ladigan eng katta palindromni (o'ngdan chapga o'qilganda ham xuddi shunday o'qiladigan sonni) toping va uni 1337 ga bo'lgandagi qoldiqni qaytaring (natija juda katta bo'lib ketmasligi uchun). Barcha juftliklarni to'g'ridan-to'g'ri tekshirish katta n larda sekin ishlaydi, shuning uchun eng katta mumkin bo'lgan ko'paytmadan pastga qarab qidirishni optimallashtiring.\n\n**1-misol:**\nKiritma: n = 2\nNatija: 987\nIzoh: eng katta palindrom 9009 = 91 * 99, 9009 mod 1337 = 987.\n\n**2-misol:**\nKiritma: n = 1\nNatija: 9",
    starterCodeJs: 'function largestPalindromeProduct(n) {\n  // your code here\n}',
    starterCodePy: 'def largest_palindrome_product(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int largestPalindromeProduct(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-007',
    title: "Katta Daraja: Massiv Ko'rsatkichli Darajaga Oshirish",
    difficulty: 'HARD',
    points: 76,
    tags: ['Matematika'],
    description: "Butun son a va juda katta ko'rsatkichni ifodalovchi raqamlar massivi b berilgan (b ning uzunligi 10000 gacha yetishi mumkin). a^b mod 1337 qiymatini hisoblang. Ko'rsatkich odatiy butun son turiga sig'maydigan darajada katta bo'lgani uchun daraja qonunlari (a^(10*x+y) = (a^10)^x * a^y) va tez darajaga oshirishdan foydalaning.\n\n**1-misol:**\nKiritma: a = 2, b = [3]\nNatija: 8\n\n**2-misol:**\nKiritma: a = 2, b = [1, 0]\nNatija: 1024",
    starterCodeJs: 'function superPow(a, b) {\n  // your code here\n}',
    starterCodePy: 'def super_pow(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'int superPow(int a, vector<int>& b) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-008',
    title: "Asosiy Kalkulyator",
    difficulty: 'HARD',
    points: 88,
    tags: ['Matematika'],
    description: "Butun sonlar, '+', '-', '*', '/' amallari, qavslar va bo'sh joylardan iborat matematik ifoda satr ko'rinishida berilgan. eval() kabi tayyor funksiyalardan foydalanmasdan, amallar ustuvorligi va qavslarni to'g'ri hisobga olib, ifodaning natijasini hisoblang. Bo'lish natijasi nolga qarab kesiladi (truncate toward zero).\n\n**1-misol:**\nKiritma: s = \"3+2*2\"\nNatija: 7\n\n**2-misol:**\nKiritma: s = \"(1+(4+5+2)-3)+(6+8)\"\nNatija: 23",
    starterCodeJs: 'function calculate(s) {\n  // your code here\n}',
    starterCodePy: 'def calculate(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int calculate(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-009',
    title: "Kasrni Davriy O'nlik Kasrga Aylantirish",
    difficulty: 'HARD',
    points: 74,
    tags: ['Matematika'],
    description: "numerator (surat) va denominator (maxraj) butun sonlari berilgan (denominator != 0). Kasrni o'nlik kasr ko'rinishidagi satrga aylantiring. Agar o'nlik qism davriy (takrorlanuvchi) bo'lsa, takrorlanuvchi qismni qavs ichiga oling. Uzun bo'lish algoritmi jarayonida qoldiqlarni kuzatib borish orqali takrorlanish boshlangan joyni aniqlang.\n\n**1-misol:**\nKiritma: numerator = 1, denominator = 2\nNatija: \"0.5\"\n\n**2-misol:**\nKiritma: numerator = 2, denominator = 3\nNatija: \"0.(6)\"",
    starterCodeJs: 'function fractionToDecimal(numerator, denominator) {\n  // your code here\n}',
    starterCodePy: 'def fraction_to_decimal(numerator, denominator):\n    # your code here\n    pass',
    starterCodeCpp: 'string fractionToDecimal(long long numerator, long long denominator) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-010',
    title: "Takrorlanmas Raqamli Sonlar Soni",
    difficulty: 'HARD',
    points: 69,
    tags: ['Matematika'],
    description: "Butun son n berilgan (0 <= n <= 8). 0 <= x < 10^n oralig'idagi, barcha raqamlari bir-biridan farq qiladigan (takrorlanmagan) butun sonlar sonini toping. n katta bo'lganda 10^n tagacha barcha sonlarni sanab chiqish sekin ishlaydi, shuning uchun kombinatorika formulalaridan (o'rinlashtirish - permutation) foydalanib to'g'ridan-to'g'ri hisoblang.\n\n**1-misol:**\nKiritma: n = 2\nNatija: 91\nIzoh: 0 dan 99 gacha bo'lgan sonlar orasida faqat 11,22,...,99 kabi 9 ta son raqamlari takrorlangan, 100-9=91.\n\n**2-misol:**\nKiritma: n = 1\nNatija: 10",
    starterCodeJs: 'function countUniqueDigitNumbers(n) {\n  // your code here\n}',
    starterCodePy: 'def count_unique_digit_numbers(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countUniqueDigitNumbers(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-011',
    title: "Tribonachchi Sonini Matritsa Darajasi Bilan Topish",
    difficulty: 'HARD',
    points: 73,
    tags: ['Matematika'],
    description: "Tribonachchi ketma-ketligi T(0)=0, T(1)=1, T(2)=1, T(n)=T(n-1)+T(n-2)+T(n-3) (n>=3) ko'rinishida aniqlangan. n va modul m berilgan holda (n 10^18 gacha bo'lishi mumkin) T(n) mod m qiymatini 3x3 matritsani tez darajaga oshirish usuli yordamida O(log n) vaqtda hisoblang.\n\n**1-misol:**\nKiritma: n = 4, m = 1000000007\nNatija: 4\nIzoh: T(2)=1,T(3)=2,T(4)=1+1+2=4.\n\n**2-misol:**\nKiritma: n = 6, m = 1000000007\nNatija: 13",
    starterCodeJs: 'function nthTribonacciMod(n, m) {\n  // your code here\n}',
    starterCodePy: 'def nth_tribonacci_mod(n, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nthTribonacciMod(long long n, long long m) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-012',
    title: "Eyler Funksiyasi Yig'indisi",
    difficulty: 'HARD',
    points: 81,
    tags: ['Matematika'],
    description: "Butun son n berilgan (1 <= n <= 10^6). Eyler funksiyasi phi(i) — 1 dan i gacha bo'lgan, i bilan o'zaro tub bo'lgan sonlar sonini bildiradi. sum(phi(i)) for i=1..n yig'indisini toping. Har bir i uchun alohida faktorizatsiya qilish sekin ishlaydi, shuning uchun elash (sieve) asosidagi chiziqli yoki deyarli chiziqli usuldan foydalanib barcha phi qiymatlarini oldindan hisoblab chiqing.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 6\nIzoh: phi(1)=1, phi(2)=1, phi(3)=2, phi(4)=2, yig'indi=6.\n\n**2-misol:**\nKiritma: n = 5\nNatija: 10",
    starterCodeJs: 'function eulerTotientSum(n) {\n  // your code here\n}',
    starterCodePy: 'def euler_totient_sum(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long eulerTotientSum(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-013',
    title: "Chiziqli Diofant Tenglamasini Yechish",
    difficulty: 'HARD',
    points: 77,
    tags: ['Matematika'],
    description: "Butun sonlar a, b, c berilgan. a*x + b*y = c tenglamasini qanoatlantiruvchi butun sonlar x va y ni toping (kengaytirilgan Evklid algoritmi - extended Euclidean algorithm - yordamida). Agar gcd(a,b) c ni bo'lmasa, yechim mavjud emas, shu holatda null (yoki mos tilda unga muqobil bo'sh qiymat) qaytaring. Aks holda [x, y] massivini istalgan to'g'ri yechim sifatida qaytaring.\n\n**1-misol:**\nKiritma: a = 3, b = 6, c = 9\nNatija: [3, 0]\nIzoh: 3*3 + 6*0 = 9. Boshqa to'g'ri javoblar ham qabul qilinadi.\n\n**2-misol:**\nKiritma: a = 2, b = 4, c = 7\nNatija: null\nIzoh: gcd(2,4)=2 soni 7 ni bo'lmaydi, demak yechim yo'q.",
    starterCodeJs: 'function solveDiophantine(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def solve_diophantine(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> solveDiophantine(long long a, long long b, long long c) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-014',
    title: "Katalan Sonini Modul Bo'yicha Hisoblash",
    difficulty: 'HARD',
    points: 75,
    tags: ['Matematika'],
    description: "Butun son n va tub son p berilgan (0 <= n <= 10^6). n-Katalan sonini C_n = (2n)! / ((n+1)! * n!) formulasi orqali p bo'yicha modul olib hisoblang. Faktoriallarni oldindan hisoblab, modul bo'yicha teskari elementlardan (Fermat kichik teoremasi orqali) foydalaning, chunki n katta bo'lganda katalan sonlarini rekursiv formula bilan to'g'ridan-to'g'ri hisoblash juda sekin bo'ladi.\n\n**1-misol:**\nKiritma: n = 3, p = 1000000007\nNatija: 5\n\n**2-misol:**\nKiritma: n = 4, p = 1000000007\nNatija: 14",
    starterCodeJs: 'function nthCatalanMod(n, p) {\n  // your code here\n}',
    starterCodePy: 'def nth_catalan_mod(n, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nthCatalanMod(long long n, long long p) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-015',
    title: "Katta Sonlarni Satr Ko'rinishida Ko'paytirish",
    difficulty: 'HARD',
    points: 71,
    tags: ['Matematika'],
    description: "Ikkita manfiy bo'lmagan katta son num1 va num2 satr ko'rinishida berilgan (har biri 200 xonagacha bo'lishi mumkin, tilning o'rnatilgan katta sonlar - BigInt kabi - turiga to'g'ridan-to'g'ri aylantirmasdan). Ularning ko'paytmasini yana satr ko'rinishida qaytaring, buning uchun qo'lda raqamma-raqam ko'paytirish algoritmidan (uzun ko'paytirish) foydalaning.\n\n**1-misol:**\nKiritma: num1 = \"123\", num2 = \"456\"\nNatija: \"56088\"\n\n**2-misol:**\nKiritma: num1 = \"99\", num2 = \"99\"\nNatija: \"9801\"",
    starterCodeJs: 'function multiplyStrings(num1, num2) {\n  // your code here\n}',
    starterCodePy: 'def multiply_strings(num1, num2):\n    # your code here\n    pass',
    starterCodeCpp: 'string multiplyStrings(string num1, string num2) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-016',
    title: "Faktorialdagi Oxirgi Nollar Soni",
    difficulty: 'HARD',
    points: 66,
    tags: ['Matematika'],
    description: "Butun son n berilgan (1 <= n <= 10^9). n! (n faktorial) sonining oxiridagi nollar sonini, n! ni to'g'ridan-to'g'ri hisoblamasdan toping. Legandr formulasidan (Legendre's formula) foydalaning: nollar soni 5, 25, 125, ... larga bo'lish natijalarining butun qismlari yig'indisiga teng.\n\n**1-misol:**\nKiritma: n = 5\nNatija: 1\nIzoh: 5! = 120, oxirida bitta nol bor.\n\n**2-misol:**\nKiritma: n = 25\nNatija: 6",
    starterCodeJs: 'function trailingZeroesInFactorial(n) {\n  // your code here\n}',
    starterCodePy: 'def trailing_zeroes_in_factorial(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long trailingZeroesInFactorial(long long n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-017',
    title: "Raqamlar Yig'indisi Berilgan Sonlarni Sanash",
    difficulty: 'HARD',
    points: 89,
    tags: ['Matematika'],
    description: "L, R (1 <= L <= R <= 10^18) va maqsad raqamlar yig'indisi S berilgan. [L, R] oralig'idagi, o'z raqamlari yig'indisi aynan S ga teng bo'lgan butun sonlar sonini toping. R juda katta bo'lgani uchun har bir sonni alohida tekshirish mumkin emas — raqamlar bo'yicha dinamik dasturlash (digit DP) usulidan, holatni (pozitsiya, joriy yig'indi, yuqori chegara bilan bog'liqlik) saqlab foydalaning.\n\n**1-misol:**\nKiritma: L = 1, R = 20, S = 3\nNatija: 2\nIzoh: 3 va 12 sonlarining raqamlar yig'indisi 3 ga teng.\n\n**2-misol:**\nKiritma: L = 10, R = 99, S = 10\nNatija: 9",
    starterCodeJs: 'function countByDigitSum(L, R, S) {\n  // your code here\n}',
    starterCodePy: 'def count_by_digit_sum(L, R, S):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countByDigitSum(long long L, long long R, int S) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-018',
    title: "Jozefus Masalasi",
    difficulty: 'HARD',
    points: 68,
    tags: ['Matematika'],
    description: "n kishi doira bo'lib turishadi (0 dan n-1 gacha raqamlangan) va sanash har doim 1-kishidan boshlanadi. Har k-chi kishi doiradan chiqariladi, bu jarayon faqat bitta kishi qolguncha davom etadi. n va k berilgan holda (n 10^6 gacha bo'lishi mumkin), qolib ketgan kishining boshlang'ich (0-indeksli) o'rnini toping. Doirani simulyatsiya qilib har safar elementni o'chirish sekin ishlaydi (ayniqsa k katta bo'lganda), shuning uchun J(1)=0, J(m)=(J(m-1)+k) mod m rekurrent formulasidan O(n) vaqtda foydalaning.\n\n**1-misol:**\nKiritma: n = 5, k = 2\nNatija: 2\n\n**2-misol:**\nKiritma: n = 7, k = 3\nNatija: 3",
    starterCodeJs: 'function josephusSurvivor(n, k) {\n  // your code here\n}',
    starterCodePy: 'def josephus_survivor(n, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int josephusSurvivor(int n, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-019',
    title: "Sonning Eng Katta Tub Bo'luvchisi",
    difficulty: 'HARD',
    points: 79,
    tags: ['Matematika'],
    description: "Butun son n berilgan (2 <= n <= 10^18). n ning eng katta tub bo'luvchisini (largest prime factor) toping. n juda katta bo'lgani uchun oddiy 2 dan n gacha tsikl bilan tekshirish yaramaydi — faqat sqrt(n) gacha bo'luvchilarni sinab, har topilgan bo'luvchiga n ni to'liq bo'linguncha bo'lib boring (bu qolgan qismni kichraytiradi va samaradorlikni oshiradi).\n\n**1-misol:**\nKiritma: n = 13195\nNatija: 29\n\n**2-misol:**\nKiritma: n = 600851475143\nNatija: 6857",
    starterCodeJs: 'function largestPrimeFactor(n) {\n  // your code here\n}',
    starterCodePy: 'def largest_prime_factor(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long largestPrimeFactor(long long n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-020',
    title: "Miller-Rabin Tublik Testi",
    difficulty: 'HARD',
    points: 85,
    tags: ['Matematika'],
    description: "Juda katta butun son n berilgan (2 <= n <= 10^18). n tub sonmi yoki yo'qligini aniqlang. n shu qadar katta bo'lishi mumkinki, sqrt(n) gacha oddiy bo'luvchilarni tekshirish (bu ~10^9 amal talab qilishi mumkin) qabul qilinishi mumkin bo'lmagan darajada sekin bo'lishi mumkin, shu sababli Miller-Rabin ehtimoliy (yoki kichik n lar uchun deterministik) tublik testidan foydalaning.\n\n**1-misol:**\nKiritma: n = 97\nNatija: true\n\n**2-misol:**\nKiritma: n = 1000000000000000000\nNatija: false",
    starterCodeJs: 'function isPrimeMillerRabin(n) {\n  // your code here\n}',
    starterCodePy: 'def is_prime_miller_rabin(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPrimeMillerRabin(long long n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-021',
    title: "N Gacha Bo'lgan Aniq Darajalar Soni",
    difficulty: 'HARD',
    points: 83,
    tags: ['Matematika'],
    description: "Butun son N berilgan. [2, N] oralig'ida a^b (a >= 2, b >= 2 butun sonlar) ko'rinishida ifodalanadigan barcha noyob (aniq daraja - perfect power) sonlarni sanang. Bitta son bir necha xil (a,b) juftligi orqali ifodalanishi mumkin (masalan, 64 = 2^6 = 4^3 = 8^2), lekin u faqat bir marta hisoblanishi kerak — takroriy hisoblashning oldini olish uchun to'plam (set) dan foydalaning.\n\n**1-misol:**\nKiritma: N = 20\nNatija: 4\nIzoh: 4, 8, 9, 16 sonlari aniq darajalardir.\n\n**2-misol:**\nKiritma: N = 100\nNatija: 12",
    starterCodeJs: 'function countPerfectPowers(N) {\n  // your code here\n}',
    starterCodePy: 'def count_perfect_powers(N):\n    # your code here\n    pass',
    starterCodeCpp: 'int countPerfectPowers(long long N) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-022',
    title: "Chiziqli Kongruensiyani Yechish",
    difficulty: 'HARD',
    points: 76,
    tags: ['Matematika'],
    description: "Butun sonlar a, b, m berilgan (m > 0). a*x ≡ b (mod m) chiziqli kongruensiyasini qanoatlantiruvchi eng kichik manfiy bo'lmagan x ni toping. a va m o'zaro tub bo'lmasligi ham mumkin, shu sababli kengaytirilgan Evklid algoritmi orqali gcd(a,m) ni toping va bu gcd b ni bo'lish-bo'lmasligini tekshiring; agar yechim bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: a = 3, b = 6, m = 9\nNatija: 2\nIzoh: 3*2 = 6, 6 mod 9 = 6.\n\n**2-misol:**\nKiritma: a = 2, b = 3, m = 4\nNatija: -1\nIzoh: gcd(2,4)=2 soni 3 ni bo'lmaydi.",
    starterCodeJs: 'function solveLinearCongruence(a, b, m) {\n  // your code here\n}',
    starterCodePy: 'def solve_linear_congruence(a, b, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long solveLinearCongruence(long long a, long long b, long long m) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-023',
    title: "Lyuka Teoremasi Bilan Kombinatsiya",
    difficulty: 'HARD',
    points: 87,
    tags: ['Matematika'],
    description: "Butun sonlar n, r (0 <= r <= n <= 10^18) va kichik tub son p (p <= 10^5) berilgan. C(n, r) mod p qiymatini Lyuka teoremasi (Lucas' theorem) yordamida hisoblang: n va r sonlarini p asosidagi raqamlarga ajratib, har bir mos raqamlar juftligi uchun kichik C(n_i, r_i) mod p qiymatlarini ko'paytiring. Bu usul n juda katta bo'lganda ham to'g'ri va tez ishlaydi.\n\n**1-misol:**\nKiritma: n = 10, r = 2, p = 5\nNatija: 0\n\n**2-misol:**\nKiritma: n = 7, r = 3, p = 3\nNatija: 2",
    starterCodeJs: 'function nCrModLucas(n, r, p) {\n  // your code here\n}',
    starterCodePy: 'def n_cr_mod_lucas(n, r, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nCrModLucas(long long n, long long r, long long p) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-024',
    title: "K-chi Kichik Chiroyli Son",
    difficulty: 'HARD',
    points: 70,
    tags: ['Matematika'],
    description: "Chiroyli son (ugly number) — faqat 2, 3 va 5 tub ko'paytuvchilariga ega bo'lgan musbat butun son (1 ham chiroyli son hisoblanadi). Butun son k berilgan holda, ketma-ket k-chi (eng kichikdan boshlab tartiblangan) chiroyli sonni toping. k katta bo'lganda barcha sonlarni birma-bir tekshirish samarasiz, shuning uchun uch ko'rsatkichli dinamik dasturlash (yoki minimal-uyum) usulidan foydalanib ketma-ketlikni to'g'ridan-to'g'ri quring.\n\n**1-misol:**\nKiritma: k = 10\nNatija: 12\nIzoh: ketma-ketlik: 1,2,3,4,5,6,8,9,10,12.\n\n**2-misol:**\nKiritma: k = 1\nNatija: 1",
    starterCodeJs: 'function nthUglyNumber(k) {\n  // your code here\n}',
    starterCodePy: 'def nth_ugly_number(k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nthUglyNumber(int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-025',
    title: "Frobenius Soni",
    difficulty: 'HARD',
    points: 65,
    tags: ['Matematika'],
    description: "O'zaro tub bo'lgan ikkita musbat butun son a va b berilgan. a va b ning manfiy bo'lmagan butun koeffitsiyentli chiziqli kombinatsiyasi (ya'ni p*a + q*b, p,q >= 0 butun sonlar) sifatida ifodalab bo'lmaydigan eng katta butun sonni (Frobenius sonini) toping. Barcha sonlarni birma-bir tekshirish katta a, b larda amaliy emas — Chicken McNugget teoremasidagi yopiq formuladan (a*b - a - b) foydalaning.\n\n**1-misol:**\nKiritma: a = 3, b = 5\nNatija: 7\nIzoh: 7 ni 3 va 5 ning manfiy bo'lmagan kombinatsiyasi sifatida ifodalab bo'lmaydi, lekin undan katta har qanday son ifodalanadi.\n\n**2-misol:**\nKiritma: a = 4, b = 7\nNatija: 17",
    starterCodeJs: 'function frobeniusNumber(a, b) {\n  // your code here\n}',
    starterCodePy: 'def frobenius_number(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long long frobeniusNumber(long long a, long long b) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-026',
    title: "N Ferzin Masalasi - Barcha Yechimlar",
    difficulty: 'HARD',
    points: 82,
    tags: ['Rekursiya'],
    description: "n x n shaxmat taxtasiga n ta ferzni shunday joylashtiring-ki, ularning hech biri bir-birini urib olmasin (bir qatorda, bir ustunda yoki bir diagonalda bo'lmasin). Barcha mumkin bo'lgan yechimlarni toping, har bir yechim taxta holatini ifodalovchi satrlar massivi ko'rinishida bo'lsin ('Q' - ferz, '.' - bo'sh katak). Yechimni faqat rekursiv orqaga qaytish (backtracking) orqali toping: har bir qatorga navbatma-navbat ferz qo'yib ko'ring, ziddiyat bo'lsa orqaga qayting.\n\n**1-misol:**\nKiritma: n = 4\nNatija: [[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [[\"Q\"]]",
    starterCodeJs: 'function solveNQueens(n) {\n  // your code here\n}',
    starterCodePy: 'def solve_n_queens(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<string>> solveNQueens(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-027',
    title: "Sudoku Yechuvchi",
    difficulty: 'HARD',
    points: 90,
    tags: ['Rekursiya'],
    description: "9x9 sudoku taxtasi qisman to'ldirilgan holda berilgan, bo'sh kataklar '.' belgisi bilan ko'rsatilgan. Taxtani sudoku qoidalariga (har qatorda, har ustunda va har 3x3 quti ichida 1-9 raqamlari faqat bir marta uchrashi kerak) mos ravishda to'liq to'ldiring. Yechimni rekursiv orqaga qaytish (backtracking) usuli bilan toping: bo'sh katakka mumkin bo'lgan raqamni qo'yib ko'ring, agar keyingi kataklarni to'ldirib bo'lmasa orqaga qaytib boshqa raqamni sinab ko'ring.\n\n**1-misol:**\nKiritma: board (qisman to'ldirilgan 9x9 massiv, ko'p bo'sh kataklar '.' bilan)\nNatija: board to'liq va sudoku qoidalariga mos to'ldirilgan holda qaytariladi (in-place yoki yangi massiv sifatida).\nIzoh: to'liq 9x9 taxtani matnda ko'rsatish qulay emas, lekin yechim yagona va qoidalarga to'liq mos bo'lishi kerak.",
    starterCodeJs: 'function solveSudoku(board) {\n  // your code here\n}',
    starterCodePy: 'def solve_sudoku(board):\n    # your code here\n    pass',
    starterCodeCpp: 'void solveSudoku(vector<vector<char>>& board) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-028',
    title: "So'zni Katakchada Qidirish",
    difficulty: 'HARD',
    points: 74,
    tags: ['Rekursiya'],
    description: "Harflardan iborat ikki o'lchamli grid va word so'zi berilgan. word ketma-ket qo'shni (yuqori, past, chap, o'ng — diagonal emas) kataklardagi harflardan tuzilishi mumkinligini aniqlang; bitta katakdan bir marta foydalanish mumkin. Yechimni rekursiv DFS orqaga qaytish (backtracking) usuli bilan toping: har bir katakdan boshlab so'zning keyingi harfini qo'shni kataklarda qidiring, ishlatilgan katakni vaqtincha belgilab, orqaga qaytishda belgini olib tashlang.\n\n**1-misol:**\nKiritma: board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"\nNatija: true\n\n**2-misol:**\nKiritma: board (yuqoridagidek), word = \"SEE\"\nNatija: true",
    starterCodeJs: 'function wordSearchExists(board, word) {\n  // your code here\n}',
    starterCodePy: 'def word_search_exists(board, word):\n    # your code here\n    pass',
    starterCodeCpp: 'bool wordSearchExists(vector<vector<char>>& board, string word) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-029',
    title: "To'g'ri Qavslar Kombinatsiyalari",
    difficulty: 'HARD',
    points: 63,
    tags: ['Rekursiya'],
    description: "Butun son n berilgan, u n juft ochiluvchi va yopiluvchi qavslarni bildiradi. Barcha to'g'ri (well-formed) qavslar kombinatsiyalarini generatsiya qiling. Yechimni rekursiv orqaga qaytish orqali toping: har bosqichda ochiluvchi qavs qo'shish mumkinligini (ochiqlar soni n dan kam) va yopiluvchi qavs qo'shish mumkinligini (yopiqlar soni ochiqlardan kam) tekshiring.\n\n**1-misol:**\nKiritma: n = 3\nNatija: [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [\"()\"]",
    starterCodeJs: 'function generateParenthesis(n) {\n  // your code here\n}',
    starterCodePy: 'def generate_parenthesis(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> generateParenthesis(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-030',
    title: "Palindromlarga Bo'lish",
    difficulty: 'HARD',
    points: 71,
    tags: ['Rekursiya'],
    description: "s satri berilgan. s ni shunday bo'laklarga bo'lingki, har bir bo'lak palindrom (oldindan va orqadan bir xil o'qiladigan satr) bo'lsin. Barcha mumkin bo'lgan bo'lish variantlarini qaytaring. Yechimni rekursiv orqaga qaytish orqali toping: s ning boshidan har xil uzunlikdagi prefikslarni sinab ko'ring, agar prefiks palindrom bo'lsa, qolgan qismini rekursiv ravishda bo'lishda davom eting.\n\n**1-misol:**\nKiritma: s = \"aab\"\nNatija: [[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]\n\n**2-misol:**\nKiritma: s = \"a\"\nNatija: [[\"a\"]]",
    starterCodeJs: 'function palindromePartition(s) {\n  // your code here\n}',
    starterCodePy: 'def palindrome_partition(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<string>> palindromePartition(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-031',
    title: "IP Manzillarni Tiklash",
    difficulty: 'HARD',
    points: 75,
    tags: ['Rekursiya'],
    description: "Faqat raqamlardan iborat s satri berilgan. s ga uchta nuqta qo'shib, uni to'g'ri IPv4 manziliga aylantirishning barcha mumkin bo'lgan usullarini qaytaring (har bir qism 0 dan 255 gacha bo'lgan son bo'lishi, va agar qism birdan ortiq raqamdan iborat bo'lsa, boshida nol bo'lmasligi kerak). Yechimni rekursiv orqaga qaytish orqali toping: har safar 1, 2 yoki 3 ta raqamni keyingi segment sifatida ajratib, qolgan qismni rekursiv davom eting.\n\n**1-misol:**\nKiritma: s = \"25525511135\"\nNatija: [\"255.255.11.135\",\"255.255.111.35\"]\n\n**2-misol:**\nKiritma: s = \"0000\"\nNatija: [\"0.0.0.0\"]",
    starterCodeJs: 'function restoreIpAddresses(s) {\n  // your code here\n}',
    starterCodePy: 'def restore_ip_addresses(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> restoreIpAddresses(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-032',
    title: "Ifodaga Amallar Qo'shish",
    difficulty: 'HARD',
    points: 88,
    tags: ['Rekursiya'],
    description: "Faqat raqamlardan iborat num satri va target butun soni berilgan. num raqamlari orasiga '+', '-', '*' amal belgilarini shunday joylashtiringki, hosil bo'lgan ifoda target ga teng bo'lsin (amallar ustuvorligiga rioya qilingan holda, ko'p xonali sonlarda boshida nol bo'lmasligi kerak, 0 ning o'zi bundan mustasno). Barcha to'g'ri ifodalarni qaytaring. Yechimni rekursiv orqaga qaytish orqali toping, ko'paytirish amali uchun oldingi qo'shilgan/ayirilgan operandni alohida kuzatib boring.\n\n**1-misol:**\nKiritma: num = \"123\", target = 6\nNatija: [\"1+2+3\",\"1*2*3\"]\n\n**2-misol:**\nKiritma: num = \"105\", target = 5\nNatija: [\"1*0+5\",\"10-5\"]",
    starterCodeJs: 'function addOperators(num, target) {\n  // your code here\n}',
    starterCodePy: 'def add_operators(num, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> addOperators(string num, int target) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-033',
    title: "Takrorlanuvchi Elementli Qism To'plamlar",
    difficulty: 'HARD',
    points: 67,
    tags: ['Rekursiya'],
    description: "Takrorlanuvchi elementlarga ega bo'lishi mumkin bo'lgan nums massivi berilgan. Barcha mumkin bo'lgan noyob qism to'plamlarni (bo'sh to'plam ham kiradi) qaytaring, takrorlanuvchi qism to'plamlar bo'lmasligi kerak. Yechimni rekursiv orqaga qaytish orqali toping: avval massivni tartiblang, har bir rekursiya darajasida bir xil qiymatni takroran tanlamaslik uchun oldingi tengdosh elementlarni o'tkazib yuboring.\n\n**1-misol:**\nKiritma: nums = [1,2,2]\nNatija: [[],[1],[1,2],[1,2,2],[2],[2,2]]\n\n**2-misol:**\nKiritma: nums = [0]\nNatija: [[],[0]]",
    starterCodeJs: 'function subsetsWithDup(nums) {\n  // your code here\n}',
    starterCodePy: 'def subsets_with_dup(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> subsetsWithDup(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-034',
    title: "Ikkilik Daraxtni Ketma-Ketlikka O'girish",
    difficulty: 'HARD',
    points: 79,
    tags: ['Rekursiya'],
    description: "Ikkilik daraxt (binary tree) ni bitta satrga serializatsiya qilib, keyin xuddi shu tuzilishni tiklab (deserializatsiya) qaytarish algoritmini yozing. Rekursiv preorder aylanish (root, chap, o'ng) yordamida daraxtni satrga o'giring, bo'sh (null) tugunlarni maxsus belgi bilan kodlang; deserializatsiya vaqtida ham xuddi shu tartibda rekursiv ravishda daraxtni qayta tiklang.\n\n**1-misol:**\nKiritma: tree = [1,2,3,null,null,4,5]\nNatija: serialize natijasi masalan \"1,2,#,#,3,4,#,#,5,#,#\" bo'lishi mumkin, deserialize esa aynan asl daraxt tuzilishini qaytaradi.\n\n**2-misol:**\nKiritma: tree = []\nNatija: serialize -> \"#\", deserialize(\"#\") -> bo'sh daraxt (null)",
    starterCodeJs: 'function serialize(root) {\n  // your code here\n}\nfunction deserialize(data) {\n  // your code here\n}',
    starterCodePy: 'def serialize(root):\n    # your code here\n    pass\n\ndef deserialize(data):\n    # your code here\n    pass',
    starterCodeCpp: 'string serialize(TreeNode* root) {\n    // your code here\n}\nTreeNode* deserialize(string data) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-035',
    title: "Labirintdagi Barcha Yo'llar",
    difficulty: 'HARD',
    points: 78,
    tags: ['Rekursiya'],
    description: "0 (ochiq katak) va 1 (devor) lardan iborat 2D labirint (maze) grid berilgan. (0,0) katakdan (m-1,n-1) katakka, faqat yuqoriga, pastga, chapga yoki o'ngga harakat qilib, bitta yo'lda bir xil katakni ikki marta bosib o'tmasdan borishning barcha mumkin bo'lgan yo'llarini toping (har bir yo'l harakatlar ketma-ketligi 'U','D','L','R' ko'rinishida ifodalansin). Yechimni rekursiv DFS orqaga qaytish orqali toping: har bir katakdan barcha yo'nalishlarni sinab ko'ring, ishlatilgan katakni belgilab, orqaga qaytishda belgini bekor qiling.\n\n**1-misol:**\nKiritma: maze = [[0,0],[0,0]]\nNatija: [\"DR\",\"RD\"]\n\n**2-misol:**\nKiritma: maze = [[0,1],[0,0]]\nNatija: [\"DR\"]",
    starterCodeJs: 'function findAllMazePaths(maze) {\n  // your code here\n}',
    starterCodePy: 'def find_all_maze_paths(maze):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> findAllMazePaths(vector<vector<int>>& maze) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-036',
    title: "Takrorlanuvchi Elementlarning Noyob Almashtirishlari",
    difficulty: 'HARD',
    points: 73,
    tags: ['Rekursiya'],
    description: "Takrorlanuvchi elementlarga ega bo'lishi mumkin bo'lgan nums massivi berilgan. Uning barcha noyob (takrorlanmaydigan) almashtirishlarini (permutation) qaytaring. Yechimni rekursiv orqaga qaytish orqali toping: avval massivni tartiblang, har bir rekursiya bosqichida bir xil qiymatni bir necha marta bir xil pozitsiyada ishlatmaslik uchun oldingi tengdosh va hali ishlatilmagan elementni o'tkazib yuboring.\n\n**1-misol:**\nKiritma: nums = [1,1,2]\nNatija: [[1,1,2],[1,2,1],[2,1,1]]\n\n**2-misol:**\nKiritma: nums = [1,2,3]\nNatija: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]",
    starterCodeJs: 'function permuteUnique(nums) {\n  // your code here\n}',
    starterCodePy: 'def permute_unique(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> permuteUnique(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-037',
    title: "Yig'indi Kombinatsiyasi",
    difficulty: 'HARD',
    points: 69,
    tags: ['Rekursiya'],
    description: "Bir-biridan farqli musbat butun sonlar candidates massivi va target butun soni berilgan. Yig'indisi target ga teng bo'lgan barcha noyob kombinatsiyalarni toping, bunda bitta son cheksiz marta qayta tanlanishi mumkin. Yechimni rekursiv orqaga qaytish orqali toping: har bir qadamda joriy sonni yana tanlash yoki keyingi songa o'tishni sinab ko'ring, joriy yig'indi target dan oshib ketsa orqaga qayting.\n\n**1-misol:**\nKiritma: candidates = [2,3,6,7], target = 7\nNatija: [[2,2,3],[7]]\n\n**2-misol:**\nKiritma: candidates = [2,3,5], target = 8\nNatija: [[2,2,2,2],[2,3,3],[3,5]]",
    starterCodeJs: 'function combinationSum(candidates, target) {\n  // your code here\n}',
    starterCodePy: 'def combination_sum(candidates, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> combinationSum(vector<int>& candidates, int target) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-038',
    title: "Yig'indi Kombinatsiyasi II",
    difficulty: 'HARD',
    points: 72,
    tags: ['Rekursiya'],
    description: "Takrorlanuvchi sonlarga ega bo'lishi mumkin bo'lgan candidates massivi va target butun soni berilgan. Har bir son faqat bir marta ishlatilishi mumkin bo'lgan holda, yig'indisi target ga teng bo'lgan barcha noyob kombinatsiyalarni toping (takroriy kombinatsiyalar bo'lmasligi kerak). Yechimni rekursiv orqaga qaytish orqali toping: massivni tartiblab, har bir rekursiya darajasida bir xil qiymatni takror tanlamaslik uchun tengdosh elementlarni o'tkazib yuboring.\n\n**1-misol:**\nKiritma: candidates = [10,1,2,7,6,1,5], target = 8\nNatija: [[1,1,6],[1,2,5],[1,7],[2,6]]\n\n**2-misol:**\nKiritma: candidates = [2,5,2,1,2], target = 5\nNatija: [[1,2,2],[5]]",
    starterCodeJs: 'function combinationSum2(candidates, target) {\n  // your code here\n}',
    starterCodePy: 'def combination_sum2(candidates, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> combinationSum2(vector<int>& candidates, int target) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-039',
    title: "Yig'indi Kombinatsiyasi III",
    difficulty: 'HARD',
    points: 64,
    tags: ['Rekursiya'],
    description: "Butun sonlar k va n berilgan. Faqat 1 dan 9 gacha bo'lgan raqamlardan (har biri kombinatsiyada eng ko'pi bilan bir marta ishlatiladi) tashkil topgan, aynan k ta sondan iborat va yig'indisi n ga teng bo'lgan barcha kombinatsiyalarni toping. Yechimni rekursiv orqaga qaytish orqali toping: har bir qadamda joriy sondan katta bo'lgan keyingi raqamni tanlab, yig'indi va tanlangan sonlar sonini kuzatib boring.\n\n**1-misol:**\nKiritma: k = 3, n = 7\nNatija: [[1,2,4]]\n\n**2-misol:**\nKiritma: k = 3, n = 9\nNatija: [[1,2,6],[1,3,5],[2,3,4]]",
    starterCodeJs: 'function combinationSum3(k, n) {\n  // your code here\n}',
    starterCodePy: 'def combination_sum3(k, n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> combinationSum3(int k, int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-040',
    title: "Telefon Raqami Harflari Kombinatsiyasi",
    difficulty: 'HARD',
    points: 60,
    tags: ['Rekursiya'],
    description: "2 dan 9 gacha bo'lgan raqamlardan iborat digits satri berilgan (eski telefon klaviaturasidagi kabi, har bir raqamga bir nechta harf mos keladi, masalan 2 -> \"abc\"). digits ifodalashi mumkin bo'lgan barcha harflar kombinatsiyalarini istalgan tartibda qaytaring. Yechimni rekursiv orqaga qaytish orqali toping: har bir raqam uchun mos harflarni birma-bir tanlab, qolgan raqamlar uchun rekursiv davom eting.\n\n**1-misol:**\nKiritma: digits = \"23\"\nNatija: [\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]\n\n**2-misol:**\nKiritma: digits = \"\"\nNatija: []",
    starterCodeJs: 'function letterCombinations(digits) {\n  // your code here\n}',
    starterCodePy: 'def letter_combinations(digits):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> letterCombinations(string digits) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-041',
    title: "So'zlarga Bo'lish II",
    difficulty: 'HARD',
    points: 86,
    tags: ['Rekursiya'],
    description: "s satri va wordDict lug'ati (so'zlar to'plami) berilgan. s ga bo'sh joylar qo'shib, har bir bo'lak wordDict dagi so'zga mos keladigan barcha mumkin bo'lgan gaplarni tuzing. Barcha to'g'ri gaplarni qaytaring. Yechimni rekursiya va memoizatsiya (har bir pozitsiyadan boshlab olingan natijalarni keshlash) yordamida toping, chunki memoizatsiyasiz rekursiya ekspotentsial vaqt talab qiladi.\n\n**1-misol:**\nKiritma: s = \"catsanddog\", wordDict = [\"cat\",\"cats\",\"and\",\"sand\",\"dog\"]\nNatija: [\"cats and dog\",\"cat sand dog\"]\n\n**2-misol:**\nKiritma: s = \"pineapplepenapple\", wordDict = [\"apple\",\"pen\",\"applepen\",\"pine\",\"pineapple\"]\nNatija: [\"pine apple pen apple\",\"pineapple pen apple\",\"pine applepen apple\"]",
    starterCodeJs: 'function wordBreakAll(s, wordDict) {\n  // your code here\n}',
    starterCodePy: 'def word_break_all(s, word_dict):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> wordBreakAll(string s, vector<string>& wordDict) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-042',
    title: "Noto'g'ri Qavslarni Olib Tashlash",
    difficulty: 'HARD',
    points: 89,
    tags: ['Rekursiya'],
    description: "Qavslar va harflardan iborat s satri berilgan. s ni to'g'ri (valid) qilish uchun olib tashlanishi kerak bo'lgan eng kam sondagi qavslarni aniqlab, shu minimal sondagi olib tashlashlar bilan hosil bo'ladigan barcha noyob to'g'ri natijalarni qaytaring. Yechimni rekursiv orqaga qaytish (BFS bilan birga yoki chuqur qidiruv va kesish - pruning - orqali) yordamida toping: har bir qavsni olib tashlash yoki qoldirishni sinab ko'ring, ammo ortiqcha olib tashlashlarni oldindan kesib tashlang.\n\n**1-misol:**\nKiritma: s = \"()())()\"\nNatija: [\"()()()\",\"(())()\"]\n\n**2-misol:**\nKiritma: s = \"(a)())()\"\nNatija: [\"(a)()()\",\"(a())()\"]",
    starterCodeJs: 'function removeInvalidParentheses(s) {\n  // your code here\n}',
    starterCodePy: 'def remove_invalid_parentheses(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> removeInvalidParentheses(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-043',
    title: "Yig'indisi Berilgan Barcha Ildiz-Barg Yo'llari",
    difficulty: 'HARD',
    points: 68,
    tags: ['Rekursiya'],
    description: "Ikkilik daraxt (binary tree) ning ildizi root va targetSum butun soni berilgan. Ildizdan bargga (leaf) qadar boradigan, yo'ldagi barcha tugun qiymatlari yig'indisi targetSum ga teng bo'lgan barcha yo'llarni qaytaring. Yechimni rekursiv DFS orqaga qaytish orqali toping: har bir tugunga kelganda joriy yo'l va qolgan yig'indini yangilab, chap va o'ng farzandlarga rekursiv o'ting, bargga yetganda yig'indini tekshiring.\n\n**1-misol:**\nKiritma: tree = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22\nNatija: [[5,4,11,2],[5,8,4,5]]\n\n**2-misol:**\nKiritma: tree = [1,2], targetSum = 0\nNatija: []",
    starterCodeJs: 'function pathSum(root, targetSum) {\n  // your code here\n}',
    starterCodePy: 'def path_sum(root, target_sum):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> pathSum(TreeNode* root, int targetSum) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-044',
    title: "N Ta Tugunli To'liq Ikkilik Daraxtlar",
    difficulty: 'HARD',
    points: 80,
    tags: ['Rekursiya'],
    description: "To'liq ikkilik daraxt (full binary tree) — har bir tuguni yo 0 ta, yo 2 ta farzandga ega bo'lgan daraxt. Toq son n berilgan holda, aynan n ta tugunga ega bo'lgan barcha struktura jihatidan noyob to'liq ikkilik daraxtlarni qaytaring (tugun qiymatlari muhim emas, faqat struktura). Yechimni rekursiya orqali toping: ildizni chiqarib tashlab qolgan n-1 tugunni chap va o'ng qism daraxtlar orasida barcha mumkin bo'lgan (toq, toq) juftliklarga bo'ling va har bir juftlik uchun rekursiv hosil qilingan quyi daraxtlarni birlashtiring.\n\n**1-misol:**\nKiritma: n = 7\nNatija: 5 ta struktura jihatidan noyob to'liq ikkilik daraxt qaytariladi.\n\n**2-misol:**\nKiritma: n = 3\nNatija: [[0,[0,null,null],[0,null,null]]]",
    starterCodeJs: 'function allPossibleFullBinaryTrees(n) {\n  // your code here\n}',
    starterCodePy: 'def all_possible_full_binary_trees(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<TreeNode*> allPossibleFullBinaryTrees(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-045',
    title: "Hanoy Minoralari - To'liq Harakatlar Ketma-Ketligi",
    difficulty: 'HARD',
    points: 61,
    tags: ['Rekursiya'],
    description: "n ta disk 'A' tayoqchasida joylashgan, ularni klassik Hanoy minoralari qoidalariga rioya qilib (bir vaqtda faqat bitta diskni ko'chirish mumkin, kattaroq disk kichigining ustiga qo'yilmaydi) 'B' tayoqchasidan yordamchi sifatida foydalanib 'C' tayoqchasiga to'liq ko'chiring. Barcha ko'chirishlar ketma-ketligini [qayerdan, qayerga] juftliklari massivi ko'rinishida qaytaring. Yechimni rekursiya orqali toping: n-1 diskni yordamchi tayoqchaga ko'chiring, eng katta diskni maqsad tayoqchaga ko'chiring, so'ng n-1 diskni yordamchidan maqsadga ko'chiring.\n\n**1-misol:**\nKiritma: n = 2\nNatija: [[\"A\",\"B\"],[\"A\",\"C\"],[\"B\",\"C\"]]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [[\"A\",\"C\"]]",
    starterCodeJs: 'function towerOfHanoiMoves(n) {\n  // your code here\n}',
    starterCodePy: 'def tower_of_hanoi_moves(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<string>> towerOfHanoiMoves(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-046',
    title: "Rekursiv To'lqin Bilan Hudud Hajmini Sanash",
    difficulty: 'HARD',
    points: 63,
    tags: ['Rekursiya'],
    description: "0 (suv) va 1 (quruqlik) lardan iborat 2D grid va boshlang'ich katak (startRow, startCol) berilgan. Rekursiv to'lqin usuli (flood-fill DFS) yordamida boshlang'ich katakni o'z ichiga olgan bog'langan quruqlik hududining hajmini (4 yo'nalishli bog'lanish: yuqori, past, chap, o'ng) toping. Agar boshlang'ich katak suv bo'lsa, natija 0 bo'lsin.\n\n**1-misol:**\nKiritma: grid = [[1,1,0],[0,1,0],[1,0,1]], start = (0,0)\nNatija: 3\n\n**2-misol:**\nKiritma: grid = [[1,1,0],[0,1,0],[1,0,1]], start = (2,0)\nNatija: 1",
    starterCodeJs: 'function floodFillRegionSize(grid, startRow, startCol) {\n  // your code here\n}',
    starterCodePy: 'def flood_fill_region_size(grid, start_row, start_col):\n    # your code here\n    pass',
    starterCodeCpp: 'int floodFillRegionSize(vector<vector<int>>& grid, int startRow, int startCol) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-047',
    title: "Sonlarni Harflarga Barcha Dekodlash Usullari",
    difficulty: 'HARD',
    points: 84,
    tags: ['Rekursiya'],
    description: "Raqamlardan va '*' belgisidan (1 dan 9 gacha bo'lgan istalgan raqamni bildiruvchi wildcard) iborat kodlangan s satri berilgan, bunda A=1, B=2, ..., Z=26. s ni dekodlashning umumiy usullari sonini toping. Bevosita rekursiya (memoizatsiyasiz) eksponensial vaqt talab qiladi, shu sababli har bir pozitsiyadan boshlab dekodlash usullari sonini keshlab (memoizatsiya yoki dinamik dasturlash bilan) hisoblang.\n\n**1-misol:**\nKiritma: s = \"12\"\nNatija: 2\nIzoh: \"AB\" (1 2) yoki \"L\" (12) sifatida dekodlanishi mumkin.\n\n**2-misol:**\nKiritma: s = \"226\"\nNatija: 3\nIzoh: \"BZ\" (2 26), \"VF\" (22 6), \"BBF\" (2 2 6).",
    starterCodeJs: 'function numDecodingsWithWildcard(s) {\n  // your code here\n}',
    starterCodePy: 'def num_decodings_with_wildcard(s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long numDecodingsWithWildcard(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-048',
    title: "N Ferzin Masalasi - Yechimlar Sonini Sanash",
    difficulty: 'HARD',
    points: 77,
    tags: ['Rekursiya'],
    description: "n x n shaxmat taxtasida n ta ferzni hech biri bir-birini urib olmaydigan tarzda joylashtirishning nechta noyob usuli borligini toping (bu safar yechimlarning o'zini emas, faqat sonini qaytarish kifoya). Yechimni rekursiv orqaga qaytish orqali toping: har bir qatorga ferz qo'yishga urinib ko'ring, band bo'lgan ustunlar va ikkala diagonalni kuzatib borish orqali samarali kesish (pruning) qiling.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 2\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function totalNQueens(n) {\n  // your code here\n}',
    starterCodePy: 'def total_n_queens(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int totalNQueens(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-049',
    title: "O'suvchi Ketma-Ketliklarni Rekursiv Topish",
    difficulty: 'HARD',
    points: 76,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi nums berilgan. Uzunligi kamida 2 bo'lgan barcha noyob o'suvchi (qat'iy o'suvchi bo'lishi shart emas, ketma-ket elementlar teng yoki katta bo'lishi mumkin) davomiy bo'lmagan qism ketma-ketliklarni (subsequence) toping. Yechimni rekursiv orqaga qaytish orqali toping: har bir pozitsiyadan boshlab keyingi elementlarni sinab ko'ring, faqat joriy ketma-ketlikning oxirgi elementidan katta yoki teng bo'lganlarini qo'shing, va bir xil rekursiya darajasida bir xil qiymatni ikki marta tanlamaslik uchun to'plam (set) dan foydalanib takroriy natijalarning oldini oling.\n\n**1-misol:**\nKiritma: nums = [4,6,7,7]\nNatija: [[4,6],[4,6,7],[4,6,7,7],[4,7],[4,7,7],[6,7],[6,7,7],[7,7]]\n\n**2-misol:**\nKiritma: nums = [4,4,3,2,1]\nNatija: [[4,4]]",
    starterCodeJs: 'function findAllIncreasingSubsequences(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_all_increasing_subsequences(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> findAllIncreasingSubsequences(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-b-050',
    title: "K Ta Teng Yig'indili Guruhlarga Bo'lish",
    difficulty: 'HARD',
    points: 85,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi nums va butun son k berilgan. nums elementlarini k ta bo'sh bo'lmagan guruhga, har bir guruh yig'indisi bir xil bo'ladigan tarzda bo'lish mumkinligini aniqlang (true yoki false qaytaring). Yechimni rekursiv orqaga qaytish orqali toping: har bir sonni navbatma-navbat k ta guruhdan biriga joylashtirishga urinib ko'ring, agar biror guruh yig'indisi maqsad qiymatdan (umumiy yig'indi / k) oshib ketsa, o'sha yo'nalishni kesib tashlang (pruning).\n\n**1-misol:**\nKiritma: nums = [4,3,2,3,5,2,1], k = 4\nNatija: true\nIzoh: masalan [5], [1,4], [2,3], [2,3] guruhlari — har birining yig'indisi 5.\n\n**2-misol:**\nKiritma: nums = [1,2,3,4], k = 3\nNatija: false",
    starterCodeJs: 'function canPartitionKSubsets(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def can_partition_k_subsets(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canPartitionKSubsets(vector<int>& nums, int k) {\n    // your code here\n}',
  },
];
