export const problems = [
  {
    key: 'hard-d-001',
    title: 'Ikkilik Daraxtda Maksimal Yo\'l Yig\'indisi',
    difficulty: 'HARD',
    points: 82,
    tags: ['Daraxtlar'],
    description: "Ildizi berilgan ikkilik daraxtda \"yo'l\" — bu bir tugundan boshlanib ota-bola bog'lanishlari orqali istalgan boshqa tugunga tugaydigan ketma-ketlik bo'lib, har bir tugun yo'lda faqat bir marta uchraydi va yo'l ildiz orqali o'tishi shart emas. Daraxt tugunlaridagi qiymatlar manfiy bo'lishi mumkin. Daraxtning ildizi berilganda, undagi istalgan yo'lning maksimal yig'indisini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: root = [1,2,3]\nNatija: 6\nIzoh: Eng yaxshi yo'l 2 -> 1 -> 3, yig'indisi 2+1+3=6.\n\n**2-misol:**\nKiritma: root = [-10,9,20,null,null,15,7]\nNatija: 42\nIzoh: Eng yaxshi yo'l 15 -> 20 -> 7, yig'indisi 15+20+7=42.",
    starterCodeJs: 'function maxPathSum(root) {\n  // your code here\n}',
    starterCodePy: 'def max_path_sum(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxPathSum(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-002',
    title: 'Ikkilik Daraxtni Seriyalash va Qayta Tiklash',
    difficulty: 'HARD',
    points: 78,
    tags: ['Daraxtlar'],
    description: "Ixtiyoriy ikkilik daraxtni bitta satrga (string) seriyalash va keyin xuddi shu tuzilishga ega daraxtga qayta tiklash imkonini beruvchi ikkita funksiya yozing: serialize(root) va deserialize(data). Kodlash formatini o'zingiz tanlaysiz, lekin deserialize(serialize(root)) natijasi original daraxt bilan struktura va qiymatlar jihatidan bir xil bo'lishi shart. null tugunlar ham hisobga olinishi kerak.\n\n**1-misol:**\nKiritma: root = [1,2,3,null,null,4,5]\nNatija: masalan \"1,2,#,#,3,4,#,#,5,#,#\"\nIzoh: serialize natijasidan deserialize orqali original daraxt tiklanadi.\n\n**2-misol:**\nKiritma: root = []\nNatija: masalan \"#\"\nIzoh: bo'sh daraxt ham to'g'ri kodlanishi va tiklanishi kerak.",
    starterCodeJs: 'function serialize(root) {\n  // your code here\n}\n\nfunction deserialize(data) {\n  // your code here\n}',
    starterCodePy: 'def serialize(root):\n    # your code here\n    pass\n\ndef deserialize(data):\n    # your code here\n    pass',
    starterCodeCpp: 'string serialize(TreeNode* root) {\n    // your code here\n}\n\nTreeNode* deserialize(string data) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-003',
    title: 'Ikkita Almashtirilgan Tugunli BSTni Tiklash',
    difficulty: 'HARD',
    points: 76,
    tags: ['Daraxtlar'],
    description: "Ikkilik qidiruv daraxtida (BST) aynan ikkita tugunning qiymatlari xato bilan bir-biri bilan almashtirilgan. Daraxt tuzilishini o'zgartirmasdan, faqat shu ikkita tugunning qiymatlarini almashtirib, BST xossasini tiklaydigan funksiya yozing. O(1) qo'shimcha xotira bilan (Morris traversal) yechish qo'shimcha ball uchun tavsiya etiladi, lekin O(n) xotira bilan yechish ham qabul qilinadi.\n\n**1-misol:**\nKiritma: root = [1,3,null,null,2]\nNatija: [3,1,null,null,2]\nIzoh: 1 va 3 tugunlari almashtirilgan edi, ular qayta almashtirilib BST tiklanadi.\n\n**2-misol:**\nKiritma: root = [3,1,4,null,null,2]\nNatija: [2,1,4,null,null,3]\nIzoh: 2 va 3 tugunlari almashtirilgan edi.",
    starterCodeJs: 'function recoverTree(root) {\n  // your code here\n}',
    starterCodePy: 'def recover_tree(root):\n    # your code here\n    pass',
    starterCodeCpp: 'void recoverTree(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-004',
    title: 'Daraxtning Vertikal Tartibli Aylanishi',
    difficulty: 'HARD',
    points: 74,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxt berilgan. Har bir tugun uchun ustun raqamini quyidagicha aniqlang: ildiz ustuni 0, chap bola ota ustunidan 1 ga kam, o'ng bola ota ustunidan 1 ga ko'p. Tugunlarni ustun raqami bo'yicha chapdan o'ngga, har bir ustun ichida qator (yuqoridan pastga) bo'yicha va bir xil pozitsiyada bir nechta qiymat bo'lsa qiymat o'sish tartibida saralab qaytaring.\n\n**1-misol:**\nKiritma: root = [3,9,20,null,null,15,7]\nNatija: [[9],[3,15],[20],[7]]\nIzoh: 9 eng chapdagi ustunda, keyin 3 va 15 bir ustunda, keyin 20, so'ng eng o'ngda 7.\n\n**2-misol:**\nKiritma: root = [1,2,3,4,5,6,7]\nNatija: [[4],[2],[1,5,6],[3],[7]]",
    starterCodeJs: 'function verticalTraversal(root) {\n  // your code here\n}',
    starterCodePy: 'def vertical_traversal(root):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> verticalTraversal(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-005',
    title: "To'liq Daraxt Tugunlarini Samarali Sanash",
    difficulty: 'HARD',
    points: 70,
    tags: ['Daraxtlar'],
    description: "To'liq ikkilik daraxt (complete binary tree) berilgan — bunda daraxtning oxirgi qatoridan tashqari barcha qatorlari to'liq to'ldirilgan va oxirgi qatordagi tugunlar imkon qadar chapga siljitilgan. Daraxtdagi umumiy tugunlar sonini oddiy O(n) chiziqli aylanishdan tezroq — chap va o'ng chekka balandliklarni solishtirish orqali O(log^2 n) vaqt murakkabligida hisoblovchi funksiya yozing.\n\n**1-misol:**\nKiritma: root = [1,2,3,4,5,6]\nNatija: 6\n\n**2-misol:**\nKiritma: root = []\nNatija: 0",
    starterCodeJs: 'function countNodes(root) {\n  // your code here\n}',
    starterCodePy: 'def count_nodes(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int countNodes(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-006',
    title: 'Preorder va Inorder Ketma-ketliklari Asosida Daraxt Qurish',
    difficulty: 'HARD',
    points: 73,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxtning preorder va inorder aylanish natijalari (ikkita butun sonlar massivi) berilgan. Bu ikki massiv aynan bitta noyob ikkilik daraxtga mos kelishini hisobga olib, o'sha daraxtni qayta tiklovchi funksiya yozing. Daraxt tugunlarida takrorlanuvchi qiymatlar yo'q deb faraz qiling.\n\n**1-misol:**\nKiritma: preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]\nNatija: [3,9,20,null,null,15,7]\n\n**2-misol:**\nKiritma: preorder = [-1], inorder = [-1]\nNatija: [-1]",
    starterCodeJs: 'function buildTree(preorder, inorder) {\n  // your code here\n}',
    starterCodePy: 'def build_tree(preorder, inorder):\n    # your code here\n    pass',
    starterCodeCpp: 'TreeNode* buildTree(vector<int>& preorder, vector<int>& inorder) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-007',
    title: 'Daraxtga Minimal Kuzatuv Kamerasi Joylashtirish',
    difficulty: 'HARD',
    points: 88,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxt berilgan, uning har bir tuguniga kamera o'rnatish mumkin. Bitta tugunga o'rnatilgan kamera o'sha tugunning o'zini, ota-tugunini va bevosita bolalarini kuzatadi. Daraxtdagi barcha tugunlarni kuzatish uchun kerak bo'ladigan minimal kamera sonini qaytaring.\n\n**1-misol:**\nKiritma: root = [0,0,null,0,0]\nNatija: 1\nIzoh: Bitta kamera ikkinchi qatordagi tugunga o'rnatilsa, barcha tugunlar kuzatiladi.\n\n**2-misol:**\nKiritma: root = [0,0,null,0,null,0,null,null,0]\nNatija: 2",
    starterCodeJs: 'function minCameraCover(root) {\n  // your code here\n}',
    starterCodePy: 'def min_camera_cover(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCameraCover(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-008',
    title: 'Bir Xil Qiymatli Eng Uzun Yo\'l',
    difficulty: 'HARD',
    points: 66,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxt berilgan. Daraxtdagi eng uzun yo'lni toping, bunda yo'ldagi barcha tugunlar bir xil qiymatga ega bo'lishi kerak. Bu yo'l bitta tugun orqali chap va o'ng tarmoqlarni bog'lab o'tishi mumkin, lekin ota tugundan yuqoriga chiqmasligi kerak. Yo'l uzunligi undagi qirralar (edges) soni bilan o'lchanadi.\n\n**1-misol:**\nKiritma: root = [5,4,5,1,1,null,5]\nNatija: 2\nIzoh: 5 -> 5 -> 5 yo'li ikkita qirradan iborat.\n\n**2-misol:**\nKiritma: root = [1,4,5,4,4,null,5]\nNatija: 2",
    starterCodeJs: 'function longestUnivaluePath(root) {\n  // your code here\n}',
    starterCodePy: 'def longest_univalue_path(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestUnivaluePath(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-009',
    title: 'Eng Chuqur Barglarning Eng Kichik Umumiy Ajdodi',
    difficulty: 'HARD',
    points: 71,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxt berilgan. Daraxtdagi eng katta chuqurlikka ega bo'lgan barcha barg tugunlarni toping, so'ngra shu barglarning barchasini o'z ichiga oluvchi eng kichik (eng pastdagi) umumiy ajdod tugunini qaytaring.\n\n**1-misol:**\nKiritma: root = [3,5,1,6,2,0,8,null,null,7,4]\nNatija: tugun qiymati 2\nIzoh: eng chuqur barglar 7 va 4 bo'lib, ularning eng kichik umumiy ajdodi 2 qiymatli tugun.\n\n**2-misol:**\nKiritma: root = [1]\nNatija: tugun qiymati 1",
    starterCodeJs: 'function lcaDeepestLeaves(root) {\n  // your code here\n}',
    starterCodePy: 'def lca_deepest_leaves(root):\n    # your code here\n    pass',
    starterCodeCpp: 'TreeNode* lcaDeepestLeaves(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-010',
    title: "Ikkilik Daraxtni Ikki Tomonlama Bog'langan Ro'yxatga Aylantirish",
    difficulty: 'HARD',
    points: 75,
    tags: ['Daraxtlar'],
    description: "Ikkilik qidiruv daraxti (BST) berilgan. Uni joyida (qo'shimcha tugunlar yaratmasdan, faqat left/right ko'rsatkichlarni qayta ishlatib) tartiblangan aylanuvchi (circular) ikki tomonlama bog'langan ro'yxatga aylantiring: left ko'rsatkich \"oldingi\" elementga, right ko'rsatkich \"keyingi\" elementga ishora qilishi kerak, va ro'yxat halqasimon bo'lishi kerak. Ro'yxatning eng kichik elementiga ishora qiluvchi tugunni qaytaring.\n\n**1-misol:**\nKiritma: BST = [4,2,5,1,3]\nNatija: qaytariladigan tugun qiymati 1\nIzoh: hosil bo'lgan aylanuvchi ro'yxat 1<->2<->3<->4<->5<->1.\n\n**2-misol:**\nKiritma: BST = [2,1,3]\nNatija: qaytariladigan tugun qiymati 1",
    starterCodeJs: 'function treeToDoublyList(root) {\n  // your code here\n}',
    starterCodePy: 'def tree_to_doubly_list(root):\n    # your code here\n    pass',
    starterCodeCpp: 'TreeNode* treeToDoublyList(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-011',
    title: "Og'irlikli Qirrali Daraxt Diametri",
    difficulty: 'HARD',
    points: 80,
    tags: ['Daraxtlar'],
    description: "n ta tugundan iborat daraxt (aciklik bog'langan graf) berilgan, u edges massivi [tugun1, tugun2, og'irlik] shaklida berilgan bo'lib, har bir qirraning musbat butun son og'irligi bor. Daraxtning \"diametri\" — bu ikkita tugun orasidagi eng uzun yo'lning umumiy og'irliklar yig'indisi. Daraxt diametrini qaytaruvchi funksiya yozing.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,3],[1,2,4],[1,3,2]]\nNatija: 7\nIzoh: 0-1-2 yo'li 3+4=7 og'irlikka ega, bu eng uzun yo'l.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1,5],[1,2,5]]\nNatija: 10",
    starterCodeJs: 'function treeDiameter(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def tree_diameter(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int treeDiameter(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-012',
    title: 'Ikki Daraxtning Strukturaviy Izomorfligi',
    difficulty: 'HARD',
    points: 69,
    tags: ['Daraxtlar'],
    description: "Ikkita ikkilik daraxtning ildizlari berilgan. Ikki daraxt \"flip-izomorf\" hisoblanadi, agar bitta daraxtni bir nechta tugunlarda chap va o'ng bolalarni almashtirish (flip qilish) orqali ikkinchi daraxtga aylantirish mumkin bo'lsa. Ikki daraxt flip-izomorf ekanligini aniqlovchi funksiya yozing.\n\n**1-misol:**\nKiritma: root1 = [1,2,3,4,5,6,null,null,null,7,8], root2 = [1,3,2,null,6,4,5,null,null,null,null,8,7]\nNatija: true\n\n**2-misol:**\nKiritma: root1 = [1,2,null,3], root2 = [1,null,2,null,3]\nNatija: false",
    starterCodeJs: 'function flipEquiv(root1, root2) {\n  // your code here\n}',
    starterCodePy: 'def flip_equiv(root1, root2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool flipEquiv(TreeNode* root1, TreeNode* root2) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-013',
    title: 'Daraxtdagi Eng Katta BST Qism Daraxtini Topish',
    difficulty: 'HARD',
    points: 79,
    tags: ['Daraxtlar'],
    description: "Ikkilik daraxt berilgan. Uning tugunlaridan biridan boshlanadigan eng katta (tugunlar soni bo'yicha) qism daraxtni toping, bu qism daraxt o'zi to'liq amaldagi ikkilik qidiruv daraxti (BST) bo'lishi kerak. Shu eng katta BST qism daraxtidagi tugunlar sonini qaytaring.\n\n**1-misol:**\nKiritma: root = [10,5,15,1,8,null,7]\nNatija: 3\nIzoh: 5, 1, 8 dan iborat qism daraxt to'g'ri BST bo'lib, u eng katta.\n\n**2-misol:**\nKiritma: root = [4,2,7,2,3,5,null]\nNatija: 2",
    starterCodeJs: 'function largestBSTSubtree(root) {\n  // your code here\n}',
    starterCodePy: 'def largest_bst_subtree(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int largestBSTSubtree(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-014',
    title: 'Baholarga Asoslangan Konfet Taqsimoti',
    difficulty: 'HARD',
    points: 77,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta bolaga baholar (ratings massivi) berilgan, har bir bolaga kamida bitta konfet berilishi kerak. Agar qo'shni ikki bolaning baholari orasida biri boshqasidan yuqori bo'lsa, yuqori bahoga ega bola qo'shnisidan ko'proq konfet olishi kerak. Barcha shartlarni qanoatlantiruvchi minimal umumiy konfetlar sonini toping.\n\n**1-misol:**\nKiritma: ratings = [1,0,2]\nNatija: 5\nIzoh: taqsimot [2,1,2], yig'indi 5.\n\n**2-misol:**\nKiritma: ratings = [1,2,2]\nNatija: 4\nIzoh: taqsimot [1,2,1] yetarli, chunki uchinchi bola ikkinchisiga teng baholi bo'lgani uchun ko'proq konfet talab qilinmaydi.",
    starterCodeJs: 'function candy(ratings) {\n  // your code here\n}',
    starterCodePy: 'def candy(ratings):\n    # your code here\n    pass',
    starterCodeCpp: 'int candy(vector<int>& ratings) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-015',
    title: "Sharlarni Yorish Uchun Minimal O'qlar Soni",
    difficulty: 'HARD',
    points: 65,
    tags: ["Ochko'zlik algoritmlari"],
    description: "2D tekislikda har biri [xstart, xend] oraliq bilan berilgan sharlar (balloons) mavjud. O'q vertikal yo'nalishda otiladi va agar shar oralig'i o'q x koordinatasini o'z ichiga olsa, shar yoriladi. Bitta o'q bir nechta sharni yorishi mumkin. Barcha sharlarni yorish uchun kerak bo'ladigan minimal o'qlar sonini toping.\n\n**1-misol:**\nKiritma: points = [[10,16],[2,8],[1,6],[7,12]]\nNatija: 2\nIzoh: bitta o'q x=6 da [1,6] va [2,8] ni, ikkinchisi x=11 da [10,16] va [7,12] ni yoradi.\n\n**2-misol:**\nKiritma: points = [[1,2],[3,4],[5,6],[7,8]]\nNatija: 4",
    starterCodeJs: 'function findMinArrowShots(points) {\n  // your code here\n}',
    starterCodePy: 'def find_min_arrow_shots(points):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinArrowShots(vector<vector<int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-016',
    title: "Yoqilg'i Stansiyalari: To'liq Aylana Isboti",
    difficulty: 'HARD',
    points: 72,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Aylana bo'ylab joylashgan n ta yoqilg'i stansiyasi bor, har birida gas[i] miqdorda yoqilg'i mavjud va i-stansiyadan i+1-stansiyagacha borish uchun cost[i] miqdorda yoqilg'i sarflanadi. Sizda cheksiz sig'imli bak bor. Qaysi boshlang'ich stansiyadan yo'lni boshlasangiz, butun aylanani bir marta aylanib chiqish mumkin bo'lishini aniqlang; agar bunday stansiya bo'lmasa -1 qaytaring. Yechim yagona bo'lishi kafolatlangan (agar mavjud bo'lsa).\n\n**1-misol:**\nKiritma: gas = [1,2,3,4,5], cost = [3,4,5,1,2]\nNatija: 3\n\n**2-misol:**\nKiritma: gas = [2,3,4], cost = [3,4,3]\nNatija: -1",
    starterCodeJs: 'function canCompleteCircuit(gas, cost) {\n  // your code here\n}',
    starterCodePy: 'def can_complete_circuit(gas, cost):\n    # your code here\n    pass',
    starterCodeCpp: 'int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-017',
    title: 'Muddatli Ishlarni Rejalashtirish va Foydani Maksimallashtirish',
    difficulty: 'HARD',
    points: 81,
    tags: ["Ochko'zlik algoritmlari"],
    description: "n ta ish berilgan, har birining muddati (deadline), foydasi (profit) bor va har bir ish bajarilishi uchun aynan 1 birlik vaqt kerak. Har bir vaqt birligida faqat bitta ish bajarish mumkin va ish faqat o'z muddatidan oldin yoki unga teng vaqtda bajarilishi mumkin. Bajarilgan ishlar sonini emas, olingan umumiy foydani maksimal qiladigan ishlarni tanlab, erishish mumkin bo'lgan maksimal umumiy foydani qaytaring.\n\n**1-misol:**\nKiritma: jobs = [{deadline:4,profit:20},{deadline:1,profit:10},{deadline:1,profit:40},{deadline:1,profit:30}]\nNatija: 60\nIzoh: job (deadline=1, profit=40) 1-vaqtda va job (deadline=4, profit=20) 4-vaqtda bajariladi, yig'indi 60.\n\n**2-misol:**\nKiritma: jobs = [{deadline:2,profit:100},{deadline:1,profit:19},{deadline:2,profit:27},{deadline:1,profit:25},{deadline:3,profit:15}]\nNatija: 142",
    starterCodeJs: 'function jobScheduling(jobs) {\n  // your code here\n}',
    starterCodePy: 'def job_scheduling(jobs):\n    # your code here\n    pass',
    starterCodeCpp: 'int jobScheduling(vector<vector<int>>& jobs) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-018',
    title: 'IPO: Maksimal Kapitalni Ta\'minlash',
    difficulty: 'HARD',
    points: 83,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Kompaniyangizda w boshlang'ich kapital bor va siz IPO orqali eng ko'p k ta loyihani tanlab amalga oshirishingiz mumkin. Har bir loyihaning ishga tushirish uchun zarur minimal kapitali (capital[i]) va u yakunlangandan keyin keltiradigan sof foydasi (profits[i]) bor. Faqat joriy kapitalingiz loyihaning talab qilingan kapitalidan katta yoki teng bo'lgandagina loyihani boshlash mumkin. k ta loyihadan keyin erishish mumkin bo'lgan maksimal yakuniy kapitalni qaytaring.\n\n**1-misol:**\nKiritma: k = 2, w = 0, profits = [1,2,3], capital = [0,1,1]\nNatija: 4\n\n**2-misol:**\nKiritma: k = 3, w = 0, profits = [1,2,3], capital = [0,1,2]\nNatija: 6",
    starterCodeJs: 'function findMaximizedCapital(k, w, profits, capital) {\n  // your code here\n}',
    starterCodePy: 'def find_maximized_capital(k, w, profits, capital):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMaximizedCapital(int k, int w, vector<int>& profits, vector<int>& capital) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-019',
    title: 'Massivni Ketma-ket Kichik Massivlarga Bo\'lish',
    difficulty: 'HARD',
    points: 74,
    tags: ["Ochko'zlik algoritmlari"],
    description: "O'sish tartibida saralangan butun sonlar massivi (takrorlanishlar bo'lishi mumkin) berilgan. Massivni bir nechta qism ketma-ketliklarga bo'lish mumkinligini aniqlang, bunda har bir qism ketma-ketlik kamida 3 ta uzunlikdagi ketma-ket o'suvchi butun sonlardan iborat bo'lishi kerak, va massivning har bir elementi aynan bitta qism ketma-ketlikka tegishli bo'lishi kerak.\n\n**1-misol:**\nKiritma: nums = [1,2,3,3,4,5]\nNatija: true\nIzoh: massivni [1,2,3] va [3,4,5] ga bo'lish mumkin.\n\n**2-misol:**\nKiritma: nums = [1,2,3,4,4,5]\nNatija: false\nIzoh: 4 sonlaridan biri yolg'iz qolib, kamida 3 uzunlikdagi ketma-ketlik hosil qila olmaydi.",
    starterCodeJs: 'function isPossible(nums) {\n  // your code here\n}',
    starterCodePy: 'def is_possible(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPossible(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-020',
    title: 'Sovutish Vaqti Bilan Vazifalarni Rejalashtirish',
    difficulty: 'HARD',
    points: 68,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Bajarilishi kerak bo'lgan vazifalar ro'yxati (harflar bilan belgilangan, tasks massivi) va sovutish vaqti n berilgan. Bir xil turdagi ikkita vazifa orasida kamida n birlik vaqt oralig'i (bo'sh yoki boshqa vazifalar bilan to'ldirilishi mumkin) bo'lishi shart. Barcha vazifalarni bajarish uchun zarur bo'ladigan minimal umumiy vaqt birliklarini toping.\n\n**1-misol:**\nKiritma: tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 2\nNatija: 8\nIzoh: masalan A B idle A B idle A B ketma-ketligi.\n\n**2-misol:**\nKiritma: tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 0\nNatija: 6",
    starterCodeJs: 'function leastInterval(tasks, n) {\n  // your code here\n}',
    starterCodePy: 'def least_interval(tasks, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int leastInterval(vector<char>& tasks, int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-021',
    title: "Bir-biriga Ustma-ust Tushmaydigan Oraliqlar Uchun Minimal O'chirish",
    difficulty: 'HARD',
    points: 66,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Oraliqlar (intervals) massivi berilgan, har biri [start, end] shaklida. Qolgan oraliqlarning hech biri bir-biri bilan ustma-ust tushmasligi (overlap) uchun massivdan o'chirilishi kerak bo'lgan minimal sondagi oraliqni toping.\n\n**1-misol:**\nKiritma: intervals = [[1,2],[2,3],[3,4],[1,3]]\nNatija: 1\nIzoh: [1,3] o'chirilsa, qolganlari ustma-ust tushmaydi.\n\n**2-misol:**\nKiritma: intervals = [[1,2],[1,2],[1,2]]\nNatija: 2",
    starterCodeJs: 'function eraseOverlapIntervals(intervals) {\n  // your code here\n}',
    starterCodePy: 'def erase_overlap_intervals(intervals):\n    # your code here\n    pass',
    starterCodeCpp: 'int eraseOverlapIntervals(vector<vector<int>>& intervals) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-022',
    title: 'Yorliqlarni Bo\'laklarga Ajratish',
    difficulty: 'HARD',
    points: 63,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Faqat kichik lotin harflaridan iborat s satri berilgan. Satrni imkon qadar ko'proq bo'lakka (partition) ajratish kerak, shunda har bir harf faqat bitta bo'lakda uchraydi. Har bir bo'lak uzunligini o'z ichiga olgan ro'yxatni qaytaring.\n\n**1-misol:**\nKiritma: s = \"ababcbacadefegdehijhklij\"\nNatija: [9,7,8]\n\n**2-misol:**\nKiritma: s = \"eccbbbbdec\"\nNatija: [10]",
    starterCodeJs: 'function partitionLabels(s) {\n  // your code here\n}',
    starterCodePy: 'def partition_labels(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> partitionLabels(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-023',
    title: 'Sakrash O\'yini II: Minimal Sakrashlar Soni',
    difficulty: 'HARD',
    points: 70,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Manfiy bo'lmagan butun sonlar massivi nums berilgan, bunda nums[i] i-pozitsiyadan qilinishi mumkin bo'lgan maksimal sakrash uzunligini bildiradi. Boshlang'ich pozitsiya 0 bo'lib, massivning oxirgi elementiga eng kam sondagi sakrashlar bilan yetib borish uchun kerak bo'ladigan minimal sakrashlar sonini qaytaring. Oxirgi elementga yetib borish har doim mumkinligi kafolatlangan.\n\n**1-misol:**\nKiritma: nums = [2,3,1,1,4]\nNatija: 2\nIzoh: 0 -> 1 -> 4 yo'li orqali ikkita sakrash yetarli.\n\n**2-misol:**\nKiritma: nums = [2,3,0,1,4]\nNatija: 2",
    starterCodeJs: 'function jumpGame2(nums) {\n  // your code here\n}',
    starterCodePy: 'def jump_game2(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int jumpGame2(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-024',
    title: "Bo'yga Qarab Navbatni Qayta Qurish",
    difficulty: 'HARD',
    points: 76,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Odamlar navbatining har bir elementi [h, k] juftligi bilan berilgan, bunda h — shu odamning bo'yi, k — undan oldin turgan va bo'yi h dan katta yoki teng bo'lgan odamlar soni. Berilgan ma'lumotlar asosida navbatni shunday qayta tuzingki, har bir [h, k] juftligi uchun shart bajarilsin.\n\n**1-misol:**\nKiritma: people = [[7,0],[4,4],[7,1],[5,0],[6,1],[5,2]]\nNatija: [[5,0],[7,0],[5,2],[6,1],[4,4],[7,1]]\n\n**2-misol:**\nKiritma: people = [[6,0],[5,0],[4,0],[3,2],[2,2],[1,4]]\nNatija: [[4,0],[5,0],[2,2],[3,2],[1,4],[6,0]]",
    starterCodeJs: 'function reconstructQueue(people) {\n  // your code here\n}',
    starterCodePy: 'def reconstruct_queue(people):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> reconstructQueue(vector<vector<int>>& people) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-025',
    title: 'Minimal Uchrashuv Xonalari II',
    difficulty: 'HARD',
    points: 69,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Uchrashuvlar oraliqlari (intervals) massivi berilgan, har biri [start, end] shaklida. Barcha uchrashuvlarni bir vaqtning o'zida o'tkazish uchun zarur bo'ladigan minimal xonalar sonini toping.\n\n**1-misol:**\nKiritma: intervals = [[0,30],[5,10],[15,20]]\nNatija: 2\n\n**2-misol:**\nKiritma: intervals = [[7,10],[2,4]]\nNatija: 1",
    starterCodeJs: 'function minMeetingRooms(intervals) {\n  // your code here\n}',
    starterCodePy: 'def min_meeting_rooms(intervals):\n    # your code here\n    pass',
    starterCodeCpp: 'int minMeetingRooms(vector<vector<int>>& intervals) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-026',
    title: 'Odamlarni Qutqarish Uchun Minimal Qayiqlar',
    difficulty: 'HARD',
    points: 62,
    tags: ["Ochko'zlik algoritmlari"],
    description: "Har bir odamning og'irligi berilgan people massivida, har bir qayiq bir vaqtning o'zida ko'pi bilan ikki kishini olib yura oladi va qayiqning yuk ko'tarish chegarasi limit dan oshmasligi kerak. Barcha odamlarni qirg'oqqa yetkazish uchun kerak bo'ladigan minimal qayiqlar sonini toping.\n\n**1-misol:**\nKiritma: people = [1,2], limit = 3\nNatija: 1\n\n**2-misol:**\nKiritma: people = [3,2,2,1], limit = 3\nNatija: 3",
    starterCodeJs: 'function numRescueBoats(people, limit) {\n  // your code here\n}',
    starterCodePy: 'def num_rescue_boats(people, limit):\n    # your code here\n    pass',
    starterCodeCpp: 'int numRescueBoats(vector<int>& people, int limit) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-027',
    title: 'Oqim Ichidagi Medianani Topish',
    difficulty: 'HARD',
    points: 80,
    tags: ['Saralash va qidiruv'],
    description: "Sonlar ketma-ket oqim (stream) sifatida kelib turadi. addNum(num) — yangi sonni oqimga qo'shadi, findMedian() — hozirgi vaqtgacha qo'shilgan barcha sonlarning medianasini qaytaradi (agar sonlar soni juft bo'lsa, ikkita o'rtadagi sonning o'rtachasi). Har ikkala amal ham samarali (addNum uchun O(log n)) ishlashi kerak.\n\n**1-misol:**\nKiritma: addNum(1), addNum(2), findMedian()\nNatija: 1.5\n\n**2-misol:**\nKiritma: addNum(3) (avvalgi holatdan keyin), findMedian()\nNatija: 2",
    starterCodeJs: 'class MedianFinder {\n  constructor() {\n    // your code here\n  }\n\n  addNum(num) {\n    // your code here\n  }\n\n  findMedian() {\n    // your code here\n  }\n}',
    starterCodePy: 'class MedianFinder:\n    def __init__(self):\n        # your code here\n        pass\n\n    def add_num(self, num):\n        # your code here\n        pass\n\n    def find_median(self):\n        # your code here\n        pass',
    starterCodeCpp: 'class MedianFinder {\npublic:\n    MedianFinder() {\n        // your code here\n    }\n\n    void addNum(int num) {\n        // your code here\n    }\n\n    double findMedian() {\n        // your code here\n    }\n};',
  },
  {
    key: 'hard-d-028',
    title: 'Saralangan Matritsada K-chi Kichik Element',
    difficulty: 'HARD',
    points: 73,
    tags: ['Saralash va qidiruv'],
    description: "n x n o'lchamdagi matritsa berilgan, unda har bir qator va har bir ustun o'sish tartibida saralangan. Matritsadagi barcha n^2 ta elementni bitta saralangan ro'yxat sifatida qaraganda, k-chi eng kichik elementni toping.\n\n**1-misol:**\nKiritma: matrix = [[1,5,9],[10,11,13],[12,13,15]], k = 8\nNatija: 13\n\n**2-misol:**\nKiritma: matrix = [[-5]], k = 1\nNatija: -5",
    starterCodeJs: 'function kthSmallest(matrix, k) {\n  // your code here\n}',
    starterCodePy: 'def kth_smallest(matrix, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int kthSmallest(vector<vector<int>>& matrix, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-029',
    title: "O'zidan Keyingi Kichik Sonlar Sonini Sanash",
    difficulty: 'HARD',
    points: 84,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan. Har bir indeks i uchun, i dan o'ngda joylashgan va nums[i] dan kichik bo'lgan elementlar sonini hisoblang. Natijani counts massivi sifatida qaytaring, bunda counts[i] — nums[i] uchun hisoblangan son. Yechim O(n log n) vaqt murakkabligida (masalan, birlashtiruvchi saralash — merge sort orqali) bo'lishi kerak.\n\n**1-misol:**\nKiritma: nums = [5,2,6,1]\nNatija: [2,1,1,0]\n\n**2-misol:**\nKiritma: nums = [-1,-1]\nNatija: [0,0]",
    starterCodeJs: 'function countSmaller(nums) {\n  // your code here\n}',
    starterCodePy: 'def count_smaller(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countSmaller(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-030',
    title: 'Ikki Saralangan Massivning Medianasi',
    difficulty: 'HARD',
    points: 87,
    tags: ['Saralash va qidiruv'],
    description: "Ikkita saralangan massiv nums1 (m ta element) va nums2 (n ta element) berilgan. Ikkala massivni birlashtirganda hosil bo'ladigan yagona saralangan massivning medianasini toping. Yechim vaqt murakkabligi O(log(m+n)) bo'lishi shart (ikkala massivni jismonan birlashtirish taqiqlanadi).\n\n**1-misol:**\nKiritma: nums1 = [1,3], nums2 = [2]\nNatija: 2.0\n\n**2-misol:**\nKiritma: nums1 = [1,2], nums2 = [3,4]\nNatija: 2.5",
    starterCodeJs: 'function findMedianSortedArrays(nums1, nums2) {\n  // your code here\n}',
    starterCodePy: 'def find_median_sorted_arrays(nums1, nums2):\n    # your code here\n    pass',
    starterCodeCpp: 'double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-031',
    title: 'Cheklangan Almashtirishlar Bilan Massivni Saralash',
    difficulty: 'HARD',
    points: 75,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums va k soni berilgan. Massivda ixtiyoriy ikkita elementni almashtirish (swap) amalidan foydalanib, uni eng ko'pi bilan k marta almashtirish orqali o'sish tartibida saralash mumkinligini tekshiring va agar mumkin bo'lsa buning uchun zarur bo'lgan minimal almashtirishlar sonini qaytaring, aks holda -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [3,1,2], k = 1\nNatija: 1\nIzoh: 3 va 1 elementlarini almashtirish orqali [1,3,2] hosil bo'ladi, keyin qo'shimcha almashtirish k limitidan oshib ketadi, shu sababli faqat bitta almashtirish bilan optimal joylashuvga erishiladi.\n\n**2-misol:**\nKiritma: nums = [4,3,2,1], k = 1\nNatija: -1\nIzoh: bitta almashtirish bilan massivni to'liq saralab bo'lmaydi.",
    starterCodeJs: 'function minSwapsToSort(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def min_swaps_to_sort(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int minSwapsToSort(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-032',
    title: 'Takrorlanuvchi Elementli Aylantirilgan Massivda Qidiruv',
    difficulty: 'HARD',
    points: 71,
    tags: ['Saralash va qidiruv'],
    description: "Avval o'sish tartibida saralangan, so'ngra noma'lum bir pivot nuqtasida aylantirilgan (rotated) butun sonlar massivi nums berilgan (massivda takrorlanuvchi qiymatlar bo'lishi mumkin). target soni berilganda, u massivda mavjud bo'lsa true, aks holda false qaytaring. Yechim imkon qadar O(log n) ga yaqin vaqt murakkabligida bo'lishi kerak.\n\n**1-misol:**\nKiritma: nums = [2,5,6,0,0,1,2], target = 0\nNatija: true\n\n**2-misol:**\nKiritma: nums = [2,5,6,0,0,1,2], target = 3\nNatija: false",
    starterCodeJs: 'function searchRotatedWithDup(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def search_rotated_with_dup(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool searchRotatedWithDup(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-033',
    title: "2D Matritsada Cho'qqi Elementni Topish",
    difficulty: 'HARD',
    points: 74,
    tags: ['Saralash va qidiruv'],
    description: "m x n o'lchamdagi matritsa berilgan. \"Cho'qqi element\" (peak element) — bu o'zining barcha to'g'ridan-to'g'ri qo'shnilaridan (yuqori, past, chap, o'ng) katta bo'lgan element. Matritsa chegarasidan tashqarida qiymat -cheksizlik deb hisoblanadi. Matritsadagi istalgan bitta cho'qqi elementning [row, col] koordinatalarini O(m log n) yoki O(n log m) vaqt murakkabligida toping.\n\n**1-misol:**\nKiritma: matrix = [[10,20,15],[21,30,14],[7,16,32]]\nNatija: [1,1] (qiymat 30) yoki [2,2] (qiymat 32)\nIzoh: ikkalasi ham to'g'ri javob hisoblanadi.\n\n**2-misol:**\nKiritma: matrix = [[10,20],[15,25]]\nNatija: [1,1]",
    starterCodeJs: 'function findPeakGrid(matrix) {\n  // your code here\n}',
    starterCodePy: 'def find_peak_grid(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findPeakGrid(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-034',
    title: 'Quickselect Orqali K-chi Eng Katta Element',
    difficulty: 'HARD',
    points: 68,
    tags: ['Saralash va qidiruv'],
    description: "Saralanmagan butun sonlar massivi nums va k soni berilgan. Massivdagi k-chi eng katta elementni toping (k-chi eng katta — bu saralangan tartibdagi k-chi element, noyob qiymatlarning k-chisi emas). Yechim o'rtacha holatda O(n) vaqt murakkabligiga ega bo'lgan quickselect algoritmidan foydalanishi kerak, to'liq saralash ishlatilmasligi kerak.\n\n**1-misol:**\nKiritma: nums = [3,2,1,5,6,4], k = 2\nNatija: 5\n\n**2-misol:**\nKiritma: nums = [3,2,3,1,2,4,5,5,6], k = 4\nNatija: 4",
    starterCodeJs: 'function findKthLargest(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def find_kth_largest(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int findKthLargest(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-035',
    title: "K ta Saralangan Ro'yxatni Birlashtirish",
    difficulty: 'HARD',
    points: 78,
    tags: ['Saralash va qidiruv'],
    description: "k ta bog'langan ro'yxat berilgan, har biri o'zicha o'sish tartibida saralangan. Barcha ro'yxatlarni bitta saralangan bog'langan ro'yxatga birlashtirib qaytaring. Yechim min-heap (ustuvor navbat) yordamida O(N log k) vaqt murakkabligida amalga oshirilishi tavsiya etiladi, bunda N — barcha elementlarning umumiy soni.\n\n**1-misol:**\nKiritma: lists = [[1,4,5],[1,3,4],[2,6]]\nNatija: [1,1,2,3,4,4,5,6]\n\n**2-misol:**\nKiritma: lists = [[]]\nNatija: []",
    starterCodeJs: 'function mergeKLists(lists) {\n  // your code here\n}',
    starterCodePy: 'def merge_k_lists(lists):\n    # your code here\n    pass',
    starterCodeCpp: 'ListNode* mergeKLists(vector<ListNode*>& lists) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-036',
    title: 'Wiggle Saralash II',
    difficulty: 'HARD',
    points: 79,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan. Massivni joyida shunday qayta tartiblangki, nums[0] < nums[1] > nums[2] < nums[3] ... shartini qanoatlantirsin (ya'ni juft indeksdagilar qo'shni toq indeksdagilardan kichik, toq indeksdagilar esa qo'shni juft indeksdagilardan katta bo'lsin). Massivda takrorlanuvchi elementlar bo'lishi mumkin.\n\n**1-misol:**\nKiritma: nums = [1,5,1,1,6,4]\nNatija: [1,6,1,5,1,4]\nIzoh: boshqa to'g'ri variantlar ham qabul qilinadi.\n\n**2-misol:**\nKiritma: nums = [1,3,2,2,3,1]\nNatija: [2,3,1,3,1,2]",
    starterCodeJs: 'function wiggleSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def wiggle_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'void wiggleSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-037',
    title: 'Takrorlanuvchi Elementli Aylantirilgan Massivda Minimal Element',
    difficulty: 'HARD',
    points: 67,
    tags: ['Saralash va qidiruv'],
    description: "Avval o'sish tartibida saralangan, so'ngra noma'lum pivot nuqtasida aylantirilgan butun sonlar massivi nums berilgan (massivda takrorlanuvchi qiymatlar bo'lishi mumkin). Massivdagi eng kichik elementni toping. Yechimda takrorlanishlar tufayli yuzaga keladigan noaniqlikni to'g'ri hal qiling va imkon qadar samarali (o'rtacha O(log n) ga yaqin) ishlang.\n\n**1-misol:**\nKiritma: nums = [1,3,5]\nNatija: 1\n\n**2-misol:**\nKiritma: nums = [2,2,2,0,1]\nNatija: 0",
    starterCodeJs: 'function findMinRotatedWithDup(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_min_rotated_with_dup(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinRotatedWithDup(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-038',
    title: 'Kitoblarni Minimal Maksimal Yuk Bilan Taqsimlash',
    difficulty: 'HARD',
    points: 76,
    tags: ['Saralash va qidiruv'],
    description: "n ta kitobning sahifalar soni ko'rsatilgan massiv pages va m ta talaba berilgan. Kitoblar talabalarga ketma-ket (bo'linmagan) bloklar shaklida taqsimlanadi, har bir talaba kamida bitta kitob olishi kerak, va har bir kitob faqat bitta talabaga beriladi. Taqsimotni shunday tanlangki, bironta talabaga tegishli sahifalar yig'indisining maksimal qiymati eng kichik bo'lsin; shu minimal maksimal qiymatni qaytaring. Agar taqsimot mumkin bo'lmasa (m talabalar soni n kitoblar sonidan ko'p bo'lsa), -1 qaytaring.\n\n**1-misol:**\nKiritma: pages = [12,34,67,90], m = 2\nNatija: 113\nIzoh: birinchi talaba 12+34+67=113 sahifa, ikkinchisi 90 sahifa oladi.\n\n**2-misol:**\nKiritma: pages = [15,17,20], m = 3\nNatija: 20",
    starterCodeJs: 'function allocateMinimumPages(pages, m) {\n  // your code here\n}',
    starterCodePy: 'def allocate_minimum_pages(pages, m):\n    # your code here\n    pass',
    starterCodeCpp: 'int allocateMinimumPages(vector<int>& pages, int m) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-039',
    title: 'Trie Yordamida Ikki Sonning Maksimal XOR Qiymati',
    difficulty: 'HARD',
    points: 82,
    tags: ['Bit amallari'],
    description: "Manfiy bo'lmagan butun sonlar massivi nums berilgan. Massivdagi ixtiyoriy ikkita elementning bitli XOR amali natijasidagi maksimal qiymatni toping. Yechim samarali bo'lishi uchun sonlarning bit ko'rinishlarini bitli trie (prefiks daraxti) tuzilmasida saqlab, har bir son uchun eng mos qarama-qarshi bitlarga ega raqamni izlash orqali amalga oshiring.\n\n**1-misol:**\nKiritma: nums = [3,10,5,25,2,8]\nNatija: 28\nIzoh: 5 XOR 25 = 28, bu maksimal qiymat.\n\n**2-misol:**\nKiritma: nums = [14,70,53,83,49,91,36,80,92,51,66,70]\nNatija: 127",
    starterCodeJs: 'function findMaximumXOR(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_maximum_xor(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMaximumXOR(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-040',
    title: "Sonlar Oralig'idagi Bitli VA Amali",
    difficulty: 'HARD',
    points: 65,
    tags: ['Bit amallari'],
    description: "Ikkita butun son m va n (m <= n) berilgan. [m, n] oralig'idagi barcha sonlarning bitli VA (AND) amalini ketma-ket bajarilganda hosil bo'ladigan natijani qaytaring (m AND (m+1) AND ... AND n). Yechim oraliqni to'liq aylanib chiqmasdan, ikkala sonning umumiy old qismini (common prefix) topish orqali samarali bajarilishi kerak.\n\n**1-misol:**\nKiritma: m = 5, n = 7\nNatija: 4\n\n**2-misol:**\nKiritma: m = 0, n = 0\nNatija: 0",
    starterCodeJs: 'function rangeBitwiseAnd(m, n) {\n  // your code here\n}',
    starterCodePy: 'def range_bitwise_and(m, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int rangeBitwiseAnd(int m, int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-041',
    title: 'Almashinuvchi Ikkilik Satrga Aylantirish Uchun Minimal Flip',
    difficulty: 'HARD',
    points: 64,
    tags: ['Bit amallari'],
    description: "Faqat '0' va '1' belgilaridan iborat ikkilik satr s berilgan. Satrni \"almashinuvchi\" (alternating) holatga keltirish uchun kerak bo'ladigan minimal bit almashtirishlar (flip) sonini toping — almashinuvchi satrda hech qanday ikkita qo'shni belgi bir xil bo'lmasligi kerak. Ikkita mumkin bo'lgan yakuniy shakl bor (\"0101...\" yoki \"1010...\"), ikkalasidan qaysi biri kamroq flip talab qilsa, o'shani hisoblang.\n\n**1-misol:**\nKiritma: s = \"0100\"\nNatija: 1\n\n**2-misol:**\nKiritma: s = \"1111\"\nNatija: 2",
    starterCodeJs: 'function minFlipsToAlternate(s) {\n  // your code here\n}',
    starterCodePy: 'def min_flips_to_alternate(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minFlipsToAlternate(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-042',
    title: 'Bir Nechta Satrlar Orasidagi Farqni XOR Orqali Topish',
    difficulty: 'HARD',
    points: 63,
    tags: ['Bit amallari'],
    description: "n ta matn satrlaridan iborat ro'yxat strs berilgan. Ro'yxatdagi barcha belgilar juft sonda uchraydi, faqat bitta belgi toq sonda (odatda bir marta ortiqcha) uchraydi. Shu \"ortiqcha\" belgini barcha satrlardagi barcha belgilarning ASCII kodlarini bitli XOR qilish orqali (qo'shimcha xotira ishlatmasdan) toping.\n\n**1-misol:**\nKiritma: strs = [\"abcd\",\"abcde\"]\nNatija: \"e\"\n\n**2-misol:**\nKiritma: strs = [\"\",\"y\"]\nNatija: \"y\"",
    starterCodeJs: 'function findTheDifferenceMulti(strs) {\n  // your code here\n}',
    starterCodePy: 'def find_the_difference_multi(strs):\n    # your code here\n    pass',
    starterCodeCpp: 'char findTheDifferenceMulti(vector<string>& strs) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-043',
    title: 'Uch Marta Takrorlangan Sonlar Orasida Yagona Sonni Topish',
    difficulty: 'HARD',
    points: 70,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan, unda har bir element aynan uch marta takrorlanadi, faqat bitta element bir marta uchraydi. O(n) vaqt va O(1) qo'shimcha xotira murakkabligida shu yagona elementni toping — har bir bit pozitsiyasi uchun 1 lar sonini 3 ga bo'lish qoldig'ini hisoblash kabi bitli amallardan foydalaning.\n\n**1-misol:**\nKiritma: nums = [2,2,3,2]\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [0,1,0,1,0,1,99]\nNatija: 99",
    starterCodeJs: 'function singleNumberOnce(nums) {\n  // your code here\n}',
    starterCodePy: 'def single_number_once(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int singleNumberOnce(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-044',
    title: '0 dan N gacha Bo\'lgan Sonlar Uchun Bitlar Sonini Hisoblash',
    difficulty: 'HARD',
    points: 61,
    tags: ['Bit amallari'],
    description: "Manfiy bo'lmagan butun son n berilgan. 0 dan n gacha (ikkalasi ham qo'shilgan holda) bo'lgan har bir son uchun uning ikkilik ko'rinishidagi 1 bitlar sonini hisoblang va natijalarni ans massivida qaytaring (ans[i] — i sonidagi 1 bitlar soni). Yechim O(n) vaqt murakkabligida, oldindan hisoblangan natijalardan foydalanuvchi dinamik dasturlash yondashuvi bilan bajarilishi kerak — har bir son uchun alohida sanashdan foydalanmang.\n\n**1-misol:**\nKiritma: n = 2\nNatija: [0,1,1]\n\n**2-misol:**\nKiritma: n = 5\nNatija: [0,1,1,2,1,2]",
    starterCodeJs: 'function countBits(n) {\n  // your code here\n}',
    starterCodePy: 'def count_bits(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countBits(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-045',
    title: 'Barcha Qism To\'plamlarning XOR Yig\'indisini Hisoblash',
    difficulty: 'HARD',
    points: 66,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan. Massivning barcha mumkin bo'lgan bo'sh bo'lmagan qism to'plamlari (subsets) uchun har bir qism to'plam ichidagi elementlarning bitli XOR qiymatini hisoblang, so'ngra shu barcha XOR qiymatlarining yig'indisini qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,3]\nNatija: 6\nIzoh: qism to'plamlar [1]->1, [3]->3, [1,3]->2, yig'indi 1+3+2=6.\n\n**2-misol:**\nKiritma: nums = [5,1,6]\nNatija: 28",
    starterCodeJs: 'function subsetXORSum(nums) {\n  // your code here\n}',
    starterCodePy: 'def subset_xor_sum(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int subsetXORSum(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-046',
    title: 'Gray Kodlar Ketma-ketligini Generatsiya Qilish',
    difficulty: 'HARD',
    points: 62,
    tags: ['Bit amallari'],
    description: "Butun son n berilgan. n-bitli Gray kod ketma-ketligini generatsiya qiling — bu 0 dan 2^n - 1 gacha bo'lgan barcha sonlarni o'z ichiga olgan ketma-ketlik bo'lib, unda har bir qo'shni ikki son (shu jumladan ketma-ketlikning oxirgi va birinchi elementi) ikkilik ko'rinishida faqat bitta bit bilan farq qiladi. Ketma-ketlik 0 dan boshlanishi kerak.\n\n**1-misol:**\nKiritma: n = 2\nNatija: [0,1,3,2]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [0,1]",
    starterCodeJs: 'function grayCode(n) {\n  // your code here\n}',
    starterCodePy: 'def gray_code(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> grayCode(int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-047',
    title: 'Plyus va Minus Amallarisiz Ikki Sonni Qo\'shish',
    difficulty: 'HARD',
    points: 68,
    tags: ['Bit amallari'],
    description: "Ikkita butun son a va b berilgan (manfiy bo'lishi ham mumkin). '+' yoki '-' arifmetik amallaridan foydalanmasdan, faqat bitli amallar (AND, OR, XOR, siljitish) yordamida ularning yig'indisini hisoblang.\n\n**1-misol:**\nKiritma: a = 1, b = 2\nNatija: 3\n\n**2-misol:**\nKiritma: a = -2, b = 3\nNatija: 1",
    starterCodeJs: 'function getSum(a, b) {\n  // your code here\n}',
    starterCodePy: 'def get_sum(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'int getSum(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-048',
    title: '32-Bitli Sonning Bitlarini Teskari Tartibga Keltirish',
    difficulty: 'HARD',
    points: 60,
    tags: ['Bit amallari'],
    description: "32-bitli belgisiz butun son (unsigned integer) berilgan. Uning ikkilik ko'rinishidagi bitlarini teskari tartibga keltirib, hosil bo'lgan yangi 32-bitli sonni qaytaring. Yechim bitli siljitish va maska amallari yordamida amalga oshirilishi kerak.\n\n**1-misol:**\nKiritma: n = 00000010100101000001111010011100 (43261596)\nNatija: 00111001011110000010100101000000 (964176192)\n\n**2-misol:**\nKiritma: n = 11111111111111111111111111111101 (4294967293)\nNatija: 10111111111111111111111111111111 (3221225471)",
    starterCodeJs: 'function reverseBits(n) {\n  // your code here\n}',
    starterCodePy: 'def reverse_bits(n):\n    # your code here\n    pass',
    starterCodeCpp: 'uint32_t reverseBits(uint32_t n) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-049',
    title: 'Massivdagi Barcha Juftliklar Uchun Umumiy Hamming Masofasi',
    difficulty: 'HARD',
    points: 78,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan. Ikki son orasidagi \"Hamming masofasi\" — bu ularning ikkilik ko'rinishlarida farq qiladigan bit pozitsiyalari soni. Massivdagi barcha mumkin bo'lgan (tartiblanmagan) juftliklar orasidagi Hamming masofalarining yig'indisini toping. Yechim barcha C(n,2) juftlikni to'g'ridan-to'g'ri sanamasdan, har bir bit pozitsiyasi uchun alohida hisoblash orqali samarali (O(n) yoki O(32n)) bajarilishi kerak.\n\n**1-misol:**\nKiritma: nums = [4,14,2]\nNatija: 6\n\n**2-misol:**\nKiritma: nums = [4,14,4]\nNatija: 4",
    starterCodeJs: 'function totalHammingDistance(nums) {\n  // your code here\n}',
    starterCodePy: 'def total_hamming_distance(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int totalHammingDistance(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-d-050',
    title: 'Kichik Diapazon So\'rovlari Uchun XOR Qiymatlarini Hisoblash',
    difficulty: 'HARD',
    points: 69,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi arr va so'rovlar ro'yxati queries berilgan, har bir so'rov [Li, Ri] shaklida. Har bir so'rov uchun arr[Li] XOR arr[Li+1] XOR ... XOR arr[Ri] qiymatini hisoblang va natijalarni massiv sifatida qaytaring. Yechim har bir so'rovni alohida chiziqli vaqtda hisoblamasdan, oldindan hisoblangan prefiks XOR massivi yordamida har bir so'rovga O(1) vaqtda javob berishi kerak.\n\n**1-misol:**\nKiritma: arr = [1,3,4,8], queries = [[0,1],[1,2],[0,3],[3,3]]\nNatija: [2,7,14,8]\n\n**2-misol:**\nKiritma: arr = [4,8,2,10], queries = [[2,3],[1,3],[0,0],[0,3]]\nNatija: [8,0,4,4]",
    starterCodeJs: 'function xorQueries(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def xor_queries(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> xorQueries(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
];
