export const problems = [
  {
    key: 'hard-c-001',
    title: "Sharlarni Portlatish",
    difficulty: 'HARD',
    points: 85,
    tags: ['Dinamik dasturlash'],
    description: "n ta shar chapdan o'ngga qatorda joylashgan, har birining ustida bir son yozilgan (nums massivi). Har safar bitta sharni portlatishingiz mumkin: agar i-indeksdagi shar portlatilsa, siz nums[left] * nums[i] * nums[right] miqdorida tanga olasiz, bu yerda left va right — hozirda portlatilmagan qo'shni sharlar (chegaradan tashqarida bo'lsa, 1 deb hisoblanadi). Barcha sharlarni portlatib, olinishi mumkin bo'lgan eng ko'p tanga miqdorini toping.\n\n**1-misol:**\nKiritma: nums = [3,1,5,8]\nNatija: 167\nIzoh: Sharlarni [1,5], [3,5], [3], [] tartibida portlatish orqali 3*1*5 + 3*5*8 + 1*3*8 + 1*8*1 = 167 tanga olinadi.\n\n**2-misol:**\nKiritma: nums = [1,5]\nNatija: 10",
    starterCodeJs: 'function maxCoins(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_coins(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxCoins(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-002',
    title: "Muntazam Ifodaga Moslashtirish",
    difficulty: 'HARD',
    points: 80,
    tags: ['Dinamik dasturlash'],
    description: "s satri va p naqsh (pattern) berilgan, bunda p tarkibida '.' (istalgan bitta belgi) va '*' (undan oldingi belgidan nol yoki undan ko'p marta takrorlanishi) belgilaridan foydalanilishi mumkin. p naqshi s satrining to'liq (butun satrni) qamrab olib mos kelish-kelmasligini aniqlang.\n\n**1-misol:**\nKiritma: s = 'aab', p = 'c*a*b'\nNatija: true\nIzoh: 'c*' nol marta takrorlanadi, 'a*' esa 'aa' ni hosil qiladi, so'ng 'b' mos keladi.\n\n**2-misol:**\nKiritma: s = 'mississippi', p = 'mis*is*p*.'\nNatija: false",
    starterCodeJs: 'function isMatch(s, p) {\n  // your code here\n}',
    starterCodePy: 'def is_match(s, p):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isMatch(string s, string p) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-003',
    title: "Aksiyalar: Sovutish Davri Bilan Maksimal Foyda",
    difficulty: 'HARD',
    points: 70,
    tags: ['Dinamik dasturlash'],
    description: "Har kunlik aksiya narxlari prices massivida berilgan. Istalgancha marta aksiya sotib olib sotishingiz mumkin (bir vaqtning o'zida faqat bitta aksiyaga ega bo'lishingiz mumkin), lekin sotishdan keyingi kuni yangi aksiya sotib ololmaysiz (sovutish davri — 1 kun). Olinishi mumkin bo'lgan eng katta umumiy foydani toping.\n\n**1-misol:**\nKiritma: prices = [1,2,3,0,2]\nNatija: 3\nIzoh: 1-kuni sotib olib 2-kuni sotamiz (foyda 1), sovutish, 4-kuni sotib olib 5-kuni sotamiz (foyda 2). Jami 3.\n\n**2-misol:**\nKiritma: prices = [1]\nNatija: 0",
    starterCodeJs: 'function maxProfitWithCooldown(prices) {\n  // your code here\n}',
    starterCodePy: 'def max_profit_with_cooldown(prices):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxProfitWithCooldown(vector<int>& prices) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-004',
    title: "Aksiyalar: K Marta Savdo Bilan Maksimal Foyda",
    difficulty: 'HARD',
    points: 75,
    tags: ['Dinamik dasturlash'],
    description: "Aksiya narxlari prices massivida berilgan va siz ko'pi bilan k marta savdo (sotib olish + sotish) qila olasiz. Bir vaqtning o'zida faqat bitta aksiyaga ega bo'lishingiz mumkin. Ko'pi bilan k ta savdo orqali olinishi mumkin bo'lgan maksimal foydani toping.\n\n**1-misol:**\nKiritma: k = 2, prices = [3,2,6,5,0,3]\nNatija: 7\nIzoh: 2-kunida sotib olib 6-kunida sotish (foyda 4), 4-kunida sotib olib 6-kunida sotish (foyda 3). Jami 7.\n\n**2-misol:**\nKiritma: k = 2, prices = [2,4,1]\nNatija: 2",
    starterCodeJs: 'function maxProfitKTransactions(k, prices) {\n  // your code here\n}',
    starterCodePy: 'def max_profit_k_transactions(k, prices):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxProfitKTransactions(int k, vector<int>& prices) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-005',
    title: "Palindromga Bo'lishning Minimal Kesimlari",
    difficulty: 'HARD',
    points: 72,
    tags: ['Dinamik dasturlash'],
    description: "s satri berilgan. Uni shunday bo'laklarga ajratingki, har bir bo'lak palindrom bo'lsin. Bunday bo'lish uchun zarur bo'lgan minimal kesimlar sonini toping (n ta bo'lak uchun n-1 ta kesim kerak).\n\n**1-misol:**\nKiritma: s = 'aab'\nNatija: 1\nIzoh: 'aa' va 'b' ikkita palindromik bo'lakka bitta kesim bilan ajratiladi.\n\n**2-misol:**\nKiritma: s = 'a'\nNatija: 0",
    starterCodeJs: 'function minPalindromeCut(s) {\n  // your code here\n}',
    starterCodePy: 'def min_palindrome_cut(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minPalindromeCut(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-006',
    title: "Ikki Satrni Aralashtirish Usullarini Sanash",
    difficulty: 'HARD',
    points: 73,
    tags: ['Dinamik dasturlash'],
    description: "s1, s2 va s3 satrlari berilgan, bunda length(s3) == length(s1) + length(s2). s3 satri s1 va s2 belgilarining har birining o'z ichidagi nisbiy tartibini saqlagan holda aralashtirilishi (interleaving) natijasida necha xil usulda hosil qilinishi mumkinligini sanang. Javobni 10^9+7 ga bo'lgandagi qoldiq sifatida qaytaring.\n\n**1-misol:**\nKiritma: s1 = 'ab', s2 = 'cd', s3 = 'acbd'\nNatija: 1\nIzoh: Faqat bitta aralashtirish usuli s3 ni hosil qiladi.\n\n**2-misol:**\nKiritma: s1 = 'aa', s2 = 'aa', s3 = 'aaaa'\nNatija: 6",
    starterCodeJs: 'function countInterleavings(s1, s2, s3) {\n  // your code here\n}',
    starterCodePy: 'def count_interleavings(s1, s2, s3):\n    # your code here\n    pass',
    starterCodeCpp: 'int countInterleavings(string s1, string s2, string s3) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-007',
    title: "Ikkilik Matritsada Maksimal To'rtburchak",
    difficulty: 'HARD',
    points: 82,
    tags: ['Dinamik dasturlash'],
    description: "Faqat 0 va 1 lardan tashkil topgan rows x cols o'lchamli ikkilik matritsa berilgan. Faqat 1 lardan tashkil topgan eng katta to'rtburchakning yuzasini (kataklar sonini) toping.\n\n**1-misol:**\nKiritma: matrix = [['1','0','1','0','0'],['1','0','1','1','1'],['1','1','1','1','1'],['1','0','0','1','0']]\nNatija: 6\n\n**2-misol:**\nKiritma: matrix = [['0']]\nNatija: 0",
    starterCodeJs: 'function maximalRectangle(matrix) {\n  // your code here\n}',
    starterCodePy: 'def maximal_rectangle(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'int maximalRectangle(vector<vector<char>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-008',
    title: "Gilos Terish",
    difficulty: 'HARD',
    points: 88,
    tags: ['Dinamik dasturlash'],
    description: "n x n o'lchamli grid berilgan, har bir katakda 0 (bo'sh), 1 (gilos bor) yoki -1 (to'siq) bo'lishi mumkin. Yuqori chap burchakdan pastki o'ng burchakka faqat o'ngga yoki pastga siljib borish, so'ng pastki o'ng burchakdan yuqori chap burchakka faqat chapga yoki yuqoriga qaytish orqali terib olinadigan maksimal gilos sonini toping (har bir katakdagi gilos faqat bir marta hisoblanadi, to'siqdan o'tib bo'lmaydi).\n\n**1-misol:**\nKiritma: grid = [[0,1,-1],[1,0,-1],[1,1,1]]\nNatija: 5\n\n**2-misol:**\nKiritma: grid = [[1,1,-1],[1,-1,1],[-1,1,1]]\nNatija: 0",
    starterCodeJs: 'function cherryPickup(grid) {\n  // your code here\n}',
    starterCodePy: 'def cherry_pickup(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int cherryPickup(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-009',
    title: "Wildcard Naqshga Moslashtirish",
    difficulty: 'HARD',
    points: 78,
    tags: ['Dinamik dasturlash'],
    description: "s satri va p naqsh berilgan, bunda p tarkibida '?' (istalgan bitta belgi) va '*' (istalgan uzunlikdagi, hatto bo'sh, belgilar ketma-ketligi) bo'lishi mumkin. p naqshi s satrining to'liq qamrab mos kelish-kelmasligini aniqlang.\n\n**1-misol:**\nKiritma: s = 'adceb', p = '*a*b'\nNatija: true\nIzoh: Birinchi '*' bo'sh, ikkinchi '*' esa 'dce' ni qamrab oladi.\n\n**2-misol:**\nKiritma: s = 'acdcb', p = 'a*c?b'\nNatija: false",
    starterCodeJs: 'function isMatchWildcard(s, p) {\n  // your code here\n}',
    starterCodePy: 'def is_match_wildcard(s, p):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isMatchWildcard(string s, string p) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-010',
    title: "Zindon O'yini: Minimal Sog'liq",
    difficulty: 'HARD',
    points: 76,
    tags: ['Dinamik dasturlash'],
    description: "m x n o'lchamli zindon grid berilgan, har bir katakda musbat (sog'liq tiklovchi) yoki manfiy (jarohat beruvchi) son yozilgan. Ritsar yuqori chap burchakdan boshlab faqat o'ngga yoki pastga siljib, pastki o'ng burchakdagi malikani qutqarishi kerak. Ritsarning sog'ligi harakat davomida hech qachon 0 yoki undan kam bo'lib qolmasligi uchun boshlanishda kerak bo'ladigan minimal sog'lik miqdorini toping.\n\n**1-misol:**\nKiritma: dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]]\nNatija: 7\n\n**2-misol:**\nKiritma: dungeon = [[0]]\nNatija: 1",
    starterCodeJs: 'function calculateMinimumHP(dungeon) {\n  // your code here\n}',
    starterCodePy: 'def calculate_minimum_hp(dungeon):\n    # your code here\n    pass',
    starterCodeCpp: 'int calculateMinimumHP(vector<vector<int>>& dungeon) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-011',
    title: "Berilgan Qadamlar Bilan Maqsadga Yetish Yo'llari",
    difficulty: 'HARD',
    points: 65,
    tags: ['Dinamik dasturlash'],
    description: "Musbat butun son target va steps massivi berilgan (steps — har bir qadamda tashlash mumkin bo'lgan qadam uzunliklari). 0 dan boshlab, steps massividagi qiymatlardan istalgan tartibda (takrorlanishlarga ruxsat berilgan holda) foydalanib aniq target songa yetib borishning necha xil tartiblangan ketma-ketligi (yo'li) borligini sanang. Javobni 10^9+7 ga bo'lgan qoldiq sifatida qaytaring.\n\n**1-misol:**\nKiritma: target = 4, steps = [1,2]\nNatija: 5\nIzoh: (1,1,1,1),(1,1,2),(1,2,1),(2,1,1),(2,2) — jami 5 ta yo'l.\n\n**2-misol:**\nKiritma: target = 3, steps = [3]\nNatija: 1",
    starterCodeJs: 'function countWaysToTarget(target, steps) {\n  // your code here\n}',
    starterCodePy: 'def count_ways_to_target(target, steps):\n    # your code here\n    pass',
    starterCodeCpp: 'int countWaysToTarget(int target, vector<int>& steps) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-012',
    title: "Ikki Satr Orasidagi Minimal Tahrirlash Masofasi",
    difficulty: 'HARD',
    points: 68,
    tags: ['Dinamik dasturlash'],
    description: "word1 va word2 satrlari berilgan. word1 ni word2 ga aylantirish uchun zarur bo'lgan minimal amallar sonini toping, bunda ruxsat etilgan amallar: bitta belgini qo'shish, o'chirish yoki almashtirish.\n\n**1-misol:**\nKiritma: word1 = 'horse', word2 = 'ros'\nNatija: 3\nIzoh: horse -> rorse -> rose -> ros.\n\n**2-misol:**\nKiritma: word1 = 'intention', word2 = 'execution'\nNatija: 5",
    starterCodeJs: 'function minDistance(word1, word2) {\n  // your code here\n}',
    starterCodePy: 'def min_distance(word1, word2):\n    # your code here\n    pass',
    starterCodeCpp: 'int minDistance(string word1, string word2) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-013',
    title: "Rus Qo'g'irchoqlari: Konvertlarni Ichma-Ich Joylashtirish",
    difficulty: 'HARD',
    points: 79,
    tags: ['Dinamik dasturlash'],
    description: "envelopes massivi berilgan, har bir elementi [width, height] juftligi. Bir konvert boshqasiga faqat kengligi ham, balandligi ham kattaroq bo'lsa joylashtirilishi mumkin (aylantirishga ruxsat yo'q). Bir-biriga ichma-ich joylashtirilishi mumkin bo'lgan maksimal konvertlar sonini (eng uzun zanjir uzunligini) toping.\n\n**1-misol:**\nKiritma: envelopes = [[5,4],[6,4],[6,7],[2,3]]\nNatija: 3\nIzoh: [2,3] => [5,4] => [6,7].\n\n**2-misol:**\nKiritma: envelopes = [[1,1],[1,1],[1,1]]\nNatija: 1",
    starterCodeJs: 'function maxEnvelopes(envelopes) {\n  // your code here\n}',
    starterCodePy: 'def max_envelopes(envelopes):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxEnvelopes(vector<vector<int>>& envelopes) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-014',
    title: "Eng Qisqa Umumiy Ust-Ketma-Ketlik",
    difficulty: 'HARD',
    points: 74,
    tags: ['Dinamik dasturlash'],
    description: "str1 va str2 satrlari berilgan. Ham str1 ni, ham str2 ni pastki ketma-ketlik (subsequence) sifatida o'z ichiga oladigan eng qisqa satrni toping. Agar bir nechta javob mavjud bo'lsa, ulardan istalganini qaytarishingiz mumkin.\n\n**1-misol:**\nKiritma: str1 = 'abac', str2 = 'cab'\nNatija: 'cabac'\nIzoh: 'cabac' tarkibida 'abac' ham, 'cab' ham pastki ketma-ketlik sifatida mavjud, va bu shartni qanoatlantiruvchi eng qisqa satr.\n\n**2-misol:**\nKiritma: str1 = 'aaaaaaaa', str2 = 'aaaaaaaa'\nNatija: 'aaaaaaaa'",
    starterCodeJs: 'function shortestCommonSupersequence(str1, str2) {\n  // your code here\n}',
    starterCodePy: 'def shortest_common_supersequence(str1, str2):\n    # your code here\n    pass',
    starterCodeCpp: 'string shortestCommonSupersequence(string str1, string str2) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-015',
    title: "Xabarni Yechish II (Wildcard Bilan)",
    difficulty: 'HARD',
    points: 77,
    tags: ['Dinamik dasturlash'],
    description: "Raqamlardan tashkil topgan s satri berilgan, unda '*' belgisi 1 dan 9 gacha bo'lgan istalgan raqamni anglatishi mumkin. 'A'->'1', 'B'->'2', ..., 'Z'->'26' kodlash qoidasiga asosan, s satrini necha xil usulda dekodlash mumkinligini sanang. Javobni 10^9+7 ga bo'lgan qoldiq sifatida qaytaring.\n\n**1-misol:**\nKiritma: s = '1*'\nNatija: 9\nIzoh: '1*' 11 dan 19 gachagi 9 ta raqamdan biriga mos kelishi mumkin.\n\n**2-misol:**\nKiritma: s = '2*'\nNatija: 15",
    starterCodeJs: 'function numDecodingsII(s) {\n  // your code here\n}',
    starterCodePy: 'def num_decodings_ii(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int numDecodingsII(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-016',
    title: "Aralashtirilgan Satrlarni Tekshirish",
    difficulty: 'HARD',
    points: 84,
    tags: ['Dinamik dasturlash'],
    description: "s1 satrini ikkiga bo'lib, ixtiyoriy sondagi bo'linish tugunlarida ikki qismini o'zaro almashtirib qayta-qayta 'aralashtirish' orqali yangi satrlar hosil qilish mumkin (bu jarayon rekursiv). s2 satri s1 dan shu tarzda aralashtirish orqali hosil qilinishi mumkin yoki yo'qligini aniqlang.\n\n**1-misol:**\nKiritma: s1 = 'great', s2 = 'rgeat'\nNatija: true\n\n**2-misol:**\nKiritma: s1 = 'abcde', s2 = 'caebd'\nNatija: false",
    starterCodeJs: 'function isScramble(s1, s2) {\n  // your code here\n}',
    starterCodePy: 'def is_scramble(s1, s2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isScramble(string s1, string s2) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-017',
    title: "So'zlarga Ajratish: Usullar Sonini Sanash",
    difficulty: 'HARD',
    points: 71,
    tags: ['Dinamik dasturlash'],
    description: "s satri va wordDict lug'ati (so'zlar massivi) berilgan. s satrini lug'atdagi so'zlarning ketma-ketligi sifatida (so'zlar bir necha marta ishlatilishi mumkin) necha xil usulda ifodalash mumkinligini sanang. Javobni 10^9+7 ga bo'lgan qoldiq sifatida qaytaring.\n\n**1-misol:**\nKiritma: s = 'catsanddog', wordDict = ['cat','cats','and','sand','dog']\nNatija: 2\nIzoh: 'cat sand dog' va 'cats and dog' — jami 2 ta usul.\n\n**2-misol:**\nKiritma: s = 'abc', wordDict = ['a','b','c']\nNatija: 1",
    starterCodeJs: 'function numWaysWordBreak(s, wordDict) {\n  // your code here\n}',
    starterCodePy: 'def num_ways_word_break(s, word_dict):\n    # your code here\n    pass',
    starterCodeCpp: 'int numWaysWordBreak(string s, vector<string>& wordDict) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-018',
    title: "Palindrom Hosil Qilish Uchun Minimal Qo'shishlar",
    difficulty: 'HARD',
    points: 66,
    tags: ['Dinamik dasturlash'],
    description: "s satri berilgan. Unga belgilar qo'shish orqali palindromga aylantirish uchun zarur bo'lgan minimal qo'shishlar sonini toping.\n\n**1-misol:**\nKiritma: s = 'mbadm'\nNatija: 2\nIzoh: 'mbdadbm' yoki 'mdbabdm' hosil qilish uchun 2 ta belgi qo'shiladi.\n\n**2-misol:**\nKiritma: s = 'leetcode'\nNatija: 5",
    starterCodeJs: 'function minInsertionsPalindrome(s) {\n  // your code here\n}',
    starterCodePy: 'def min_insertions_palindrome(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minInsertionsPalindrome(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-019',
    title: "Satrni K Ta Palindromga Bo'lish (Minimal O'zgartirish)",
    difficulty: 'HARD',
    points: 83,
    tags: ['Dinamik dasturlash'],
    description: "s satri va k butun soni berilgan. s ni aniq k ta ketma-ket bo'lakka ajrating, shunday qilib har bir bo'lakni palindromga aylantirish uchun zarur bo'ladigan belgi o'zgartirishlar sonining yig'indisi minimal bo'lsin. Har bir belgini istalgan boshqa belgiga o'zgartirish mumkin. Minimal umumiy o'zgartirishlar sonini toping.\n\n**1-misol:**\nKiritma: s = 'abc', k = 2\nNatija: 1\nIzoh: 'ab' va 'c' ga bo'lib, 'ab' ni 'aa' yoki 'bb' ga aylantirish uchun 1 ta o'zgartirish kifoya.\n\n**2-misol:**\nKiritma: s = 'aabbc', k = 3\nNatija: 0",
    starterCodeJs: 'function minChangesToPalindromePartition(s, k) {\n  // your code here\n}',
    starterCodePy: 'def min_changes_to_palindrome_partition(s, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int minChangesToPalindromePartition(string s, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-020',
    title: "Tuxum Tashlash Muammosi",
    difficulty: 'HARD',
    points: 90,
    tags: ['Dinamik dasturlash'],
    description: "k ta bir xil tuxum va n qavatli bino berilgan. Har bir tuxum ma'lum bir qavatdan tashlanganda sinishi yoki sinmasligi mumkin: undan yuqoridagi barcha qavatlardan tashlansa albatta sinadi, pastdagi barcha qavatlardan tashlansa hech qachon sinmaydi. Shu 'muhim qavat'ni har qanday holatda ham aniqlab bera oladigan strategiya uchun zarur bo'lgan minimal (eng yomon holatdagi) tashlashlar sonini toping.\n\n**1-misol:**\nKiritma: k = 2, n = 6\nNatija: 3\n\n**2-misol:**\nKiritma: k = 1, n = 10\nNatija: 10",
    starterCodeJs: 'function superEggDrop(k, n) {\n  // your code here\n}',
    starterCodePy: 'def super_egg_drop(k, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int superEggDrop(int k, int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-021',
    title: "Foydali Sxemalar Sonini Sanash",
    difficulty: 'HARD',
    points: 81,
    tags: ['Dinamik dasturlash'],
    description: "n ishchi, minProfit minimal foyda talabi, group va profit massivlari berilgan (group[i] — i-jinoyat uchun kerak bo'ladigan ishchilar soni, profit[i] — undan olinadigan foyda). Har bir ishchi ko'pi bilan bitta jinoyatda qatnashishi mumkin. Umumiy foyda kamida minProfit bo'lib, ishlatiladigan ishchilar soni n dan oshmaydigan jinoyatlar to'plamlarining sonini sanang (bo'sh to'plam ham foyda 0 bilan hisobga olinadi). Javobni 10^9+7 ga bo'lgan qoldiq sifatida qaytaring.\n\n**1-misol:**\nKiritma: n = 5, minProfit = 3, group = [2,2], profit = [2,3]\nNatija: 2\n\n**2-misol:**\nKiritma: n = 10, minProfit = 5, group = [2,3,5], profit = [6,7,8]\nNatija: 7",
    starterCodeJs: 'function profitableSchemes(n, minProfit, group, profit) {\n  // your code here\n}',
    starterCodePy: 'def profitable_schemes(n, min_profit, group, profit):\n    # your code here\n    pass',
    starterCodeCpp: 'int profitableSchemes(int n, int minProfit, vector<int>& group, vector<int>& profit) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-022',
    title: "Uylarni Bo'yash II: K Xil Rang",
    difficulty: 'HARD',
    points: 62,
    tags: ['Dinamik dasturlash'],
    description: "n ta uy va k xil rang berilgan, costs[i][j] — i-uyni j-rang bilan bo'yash narxi. Hech qanday ikki qo'shni uy bir xil rangga bo'yalmasligi sharti bilan, barcha uylarni bo'yashning minimal umumiy narxini toping.\n\n**1-misol:**\nKiritma: costs = [[1,5,3],[2,9,4]]\nNatija: 5\nIzoh: 0-uy 0-rang bilan (1), 1-uy 2-rang bilan (4) bo'yaladi, jami 5.\n\n**2-misol:**\nKiritma: costs = [[1,3],[2,4]]\nNatija: 5",
    starterCodeJs: 'function minCostPaintHousesII(costs) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_paint_houses_ii(costs):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCostPaintHousesII(vector<vector<int>>& costs) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-023',
    title: "Eng Uzun To'g'ri Qavslar Ketma-Ketligi",
    difficulty: 'HARD',
    points: 69,
    tags: ['Dinamik dasturlash'],
    description: "Faqat '(' va ')' belgilaridan tashkil topgan s satri berilgan. Eng uzun to'g'ri (valid) qavslar qism-satrining uzunligini toping.\n\n**1-misol:**\nKiritma: s = ')()())'\nNatija: 4\nIzoh: Eng uzun to'g'ri qism-satr '()()' bo'lib, uzunligi 4.\n\n**2-misol:**\nKiritma: s = '(()'\nNatija: 2",
    starterCodeJs: 'function longestValidParentheses(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_valid_parentheses(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestValidParentheses(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-024',
    title: "Ishlarni Rejalashtirish: Maksimal Foyda",
    difficulty: 'HARD',
    points: 80,
    tags: ['Dinamik dasturlash'],
    description: "n ta ish berilgan, har birining startTime[i], endTime[i] boshlanish/tugash vaqti va profit[i] foydasi bor. Bir vaqtning o'zida faqat bitta ishni bajarish mumkin (ishlar bir-biriga ustma-ust tushmasligi kerak). Bajarilishi mumkin bo'lgan ishlar to'plamidan olinadigan maksimal umumiy foydani toping.\n\n**1-misol:**\nKiritma: startTime = [1,2,3,3], endTime = [3,4,5,6], profit = [50,10,40,70]\nNatija: 120\nIzoh: [1,3] ish (foyda 50) va [3,6] ish (foyda 70) tanlanadi, jami 120.\n\n**2-misol:**\nKiritma: startTime = [1,2], endTime = [3,4], profit = [5,6]\nNatija: 11",
    starterCodeJs: 'function jobScheduling(startTime, endTime, profit) {\n  // your code here\n}',
    starterCodePy: 'def job_scheduling(start_time, end_time, profit):\n    # your code here\n    pass',
    starterCodeCpp: 'int jobScheduling(vector<int>& startTime, vector<int>& endTime, vector<int>& profit) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-025',
    title: "Massivni Bo'lish: Eng Katta Yig'indini Minimallashtirish",
    difficulty: 'HARD',
    points: 86,
    tags: ['Dinamik dasturlash'],
    description: "nums massivi va m butun soni berilgan. Massivni m ta uzluksiz (ketma-ket) qism-massivga bo'ling, shunday qilib ushbu qism-massivlarning yig'indilari orasidagi eng kattasi imkon qadar minimal bo'lsin. Ushbu minimal maksimal yig'indini toping.\n\n**1-misol:**\nKiritma: nums = [7,2,5,10,8], m = 2\nNatija: 18\nIzoh: [7,2,5] va [10,8] ga bo'linsa, yig'indilar 14 va 18, eng kattasi 18 bo'lib bu minimal mumkin bo'lgan qiymat.\n\n**2-misol:**\nKiritma: nums = [1,2,3,4,5], m = 2\nNatija: 9",
    starterCodeJs: 'function splitArray(nums, m) {\n  // your code here\n}',
    starterCodePy: 'def split_array(nums, m):\n    # your code here\n    pass',
    starterCodeCpp: 'int splitArray(vector<int>& nums, int m) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-026',
    title: "Dijkstra Algoritmi: Eng Qisqa Yo'llar",
    difficulty: 'HARD',
    points: 65,
    tags: ['Grafiklar'],
    description: "n ta tugunli (0 dan n-1 gacha raqamlangan) yo'naltirilgan vaznli graf edges massivi orqali berilgan, bunda har bir element [u, v, w] — u dan v ga w vaznli qirra (barcha vaznlar manfiy emas). src boshlang'ich tugundan barcha boshqa tugunlarga eng qisqa masofalarni toping. Agar biror tugunga yetib bo'lmasa, natijada shu o'rin uchun -1 qaytaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,4],[0,2,1],[2,1,2],[1,3,1],[2,3,5]], src = 0\nNatija: [0,3,1,4]\n\n**2-misol:**\nKiritma: n = 2, edges = [], src = 0\nNatija: [0,-1]",
    starterCodeJs: 'function dijkstra(n, edges, src) {\n  // your code here\n}',
    starterCodePy: 'def dijkstra(n, edges, src):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> dijkstra(int n, vector<vector<int>>& edges, int src) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-027',
    title: "Bellman-Ford: Manfiy Qirralar Bilan Eng Qisqa Yo'l",
    difficulty: 'HARD',
    points: 78,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilgan graf edges massivi ([u,v,w] shaklida) orqali berilgan, bunda vaznlar manfiy bo'lishi ham mumkin. src boshlang'ich tugundan barcha tugunlarga eng qisqa masofalarni toping. Agar src dan yetib borish mumkin bo'lgan manfiy sikl mavjud bo'lsa, bo'sh massiv qaytaring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1,-1],[0,2,4],[1,2,3],[1,3,2],[1,4,2],[3,2,5],[3,1,1],[4,3,-3]], src = 0\nNatija: [0,-1,2,-2,1]\n\n**2-misol:**\nKiritma: n = 2, edges = [[0,1,-1],[1,0,-1]], src = 0\nNatija: []",
    starterCodeJs: 'function bellmanFord(n, edges, src) {\n  // your code here\n}',
    starterCodePy: 'def bellman_ford(n, edges, src):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> bellmanFord(int n, vector<vector<int>>& edges, int src) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-028',
    title: "Tarmoqda Signal Tarqalish Vaqti",
    difficulty: 'HARD',
    points: 63,
    tags: ['Grafiklar'],
    description: "n ta tugun (1 dan n gacha raqamlangan) va times massivi berilgan, har bir elementi [u, v, w] — u tugunidan v tuguniga signal w vaqt birligida yetib boradi. k tugunidan signal yuborilganda, barcha n ta tugunga signal yetib borishi uchun ketadigan minimal vaqtni toping. Agar barcha tugunlarga yetib bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2\nNatija: 2\n\n**2-misol:**\nKiritma: times = [[1,2,1]], n = 2, k = 1\nNatija: 1",
    starterCodeJs: 'function networkDelayTime(times, n, k) {\n  // your code here\n}',
    starterCodePy: 'def network_delay_time(times, n, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int networkDelayTime(vector<vector<int>>& times, int n, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-029',
    title: "Floyd-Warshall: Barcha Juftliklar Orasidagi Eng Qisqa Yo'llar",
    difficulty: 'HARD',
    points: 70,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilgan vaznli graf edges massivi ([u,v,w]) orqali berilgan (n <= 100). Har bir juft tugun (i, j) orasidagi eng qisqa masofani hisoblab, n x n o'lchamli matritsa qaytaring. Agar j ga i dan yetib bo'lmasa, mos katakka -1 qo'ying.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1,4],[1,2,1],[0,2,7]]\nNatija: [[0,4,5],[-1,0,1],[-1,-1,0]]\n\n**2-misol:**\nKiritma: n = 2, edges = [[0,1,3]]\nNatija: [[0,3],[-1,0]]",
    starterCodeJs: 'function floydWarshall(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def floyd_warshall(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> floydWarshall(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-030',
    title: "Kruskal Algoritmi: Minimal Ulovchi Daraxt",
    difficulty: 'HARD',
    points: 74,
    tags: ['Grafiklar'],
    description: "n ta tugun va edges massivi ([u,v,w] shaklidagi vaznli qirralar) berilgan bog'langan yo'naltirilmagan graf berilgan. Kruskal algoritmi g'oyasidan foydalanib (birlashma-topish tuzilmasi bilan), barcha tugunlarni ulovchi minimal umumiy vaznli daraxtning (MST) umumiy vaznini toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,10],[0,2,6],[0,3,5],[1,3,15],[2,3,4]]\nNatija: 19\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1,1],[1,2,2],[0,2,4]]\nNatija: 3",
    starterCodeJs: 'function minSpanningTreeCost(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def min_spanning_tree_cost(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int minSpanningTreeCost(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-031',
    title: "Sirli Til: Alifbo Tartibini Aniqlash",
    difficulty: 'HARD',
    points: 85,
    tags: ['Grafiklar'],
    description: "Noma'lum tilning lug'atidan olingan so'zlar words massivi berilgan, ular shu tilning alifbo tartibi bo'yicha leksikografik tartiblangan. Ushbu tilning alifbosidagi harflarning tartibini aniqlab, mos keluvchi bitta satr sifatida qaytaring. Agar bunday tartib mavjud bo'lmasa (ziddiyat yoki noto'g'ri kiritma bo'lsa), bo'sh satr qaytaring.\n\n**1-misol:**\nKiritma: words = ['wrt','wrf','er','ett','rftt']\nNatija: 'wertf'\n\n**2-misol:**\nKiritma: words = ['z','x']\nNatija: 'zx'",
    starterCodeJs: 'function alienOrder(words) {\n  // your code here\n}',
    starterCodePy: 'def alien_order(words):\n    # your code here\n    pass',
    starterCodeCpp: 'string alienOrder(vector<string>& words) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-032',
    title: "So'z Zinapoyasi: Eng Qisqa Aylantirish",
    difficulty: 'HARD',
    points: 80,
    tags: ['Grafiklar'],
    description: "beginWord, endWord va wordList (so'zlar lug'ati) berilgan. Har bir qadamda so'zning faqat bitta harfini o'zgartirib, natijada hosil bo'lgan so'z wordList ichida bo'lishi kerak. beginWord dan endWord ga o'tish uchun zarur bo'lgan eng qisqa aylantirish ketma-ketligidagi so'zlar sonini toping (boshlang'ich so'z ham hisobga olinadi). Agar bunday ketma-ketlik mavjud bo'lmasa, 0 qaytaring.\n\n**1-misol:**\nKiritma: beginWord = 'hit', endWord = 'cog', wordList = ['hot','dot','dog','lot','log','cog']\nNatija: 5\nIzoh: 'hit' -> 'hot' -> 'dot' -> 'dog' -> 'cog'.\n\n**2-misol:**\nKiritma: beginWord = 'hit', endWord = 'cog', wordList = ['hot','dot','dog','lot','log']\nNatija: 0",
    starterCodeJs: 'function ladderLength(beginWord, endWord, wordList) {\n  // your code here\n}',
    starterCodePy: 'def ladder_length(begin_word, end_word, word_list):\n    # your code here\n    pass',
    starterCodeCpp: 'int ladderLength(string beginWord, string endWord, vector<string>& wordList) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-033',
    title: "Tarmoqdagi Muhim Ulanishlar (Ko'priklar)",
    difficulty: 'HARD',
    points: 87,
    tags: ['Grafiklar'],
    description: "n ta serverli (0 dan n-1 gacha) va connections massivi ([u,v] shaklidagi ikki tomonlama ulanishlar) orqali berilgan bog'langan tarmoq berilgan. Agar biror ulanish olib tashlansa, tarmoqning ba'zi qismlari bir-biridan ajralib qolishiga sabab bo'ladigan barcha 'muhim ulanishlar'ni (grafdagi ko'priklarni) toping.\n\n**1-misol:**\nKiritma: n = 4, connections = [[0,1],[1,2],[2,0],[1,3]]\nNatija: [[1,3]]\n\n**2-misol:**\nKiritma: n = 2, connections = [[0,1]]\nNatija: [[0,1]]",
    starterCodeJs: 'function criticalConnections(n, connections) {\n  // your code here\n}',
    starterCodePy: 'def critical_connections(n, connections):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> criticalConnections(int n, vector<vector<int>>& connections) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-034',
    title: "Sayohat Marshrutini Tiklash",
    difficulty: 'HARD',
    points: 82,
    tags: ['Grafiklar'],
    description: "tickets massivi berilgan, har bir elementi [from, to] — havo chiptasi (bir aeroportdan ikkinchisiga). 'JFK' aeroportidan boshlab, barcha chiptalardan aynan bir marta foydalanib, leksikografik jihatdan eng kichik bo'lgan to'liq sayohat marshrutini toping (marshrut barcha chiptalarni ishlatishi shart, va u har doim mavjud deb hisoblang).\n\n**1-misol:**\nKiritma: tickets = [['MUC','LHR'],['JFK','MUC'],['SFO','SJC'],['LHR','SFO']]\nNatija: ['JFK','MUC','LHR','SFO','SJC']\n\n**2-misol:**\nKiritma: tickets = [['JFK','SFO'],['JFK','ATL'],['SFO','ATL'],['ATL','JFK']]\nNatija: ['JFK','ATL','JFK','SFO','ATL']",
    starterCodeJs: 'function findItinerary(tickets) {\n  // your code here\n}',
    starterCodePy: 'def find_itinerary(tickets):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> findItinerary(vector<vector<string>>& tickets) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-035',
    title: "Ko'tarilayotgan Suvda Suzish",
    difficulty: 'HARD',
    points: 84,
    tags: ['Grafiklar'],
    description: "n x n o'lchamli grid berilgan, grid[i][j] — shu katakning balandligi. t vaqtida suv sathi t ga teng, va siz faqat balandligi t dan oshmaydigan kataklar orasida (yuqoriga, pastga, chapga, o'ngga) harakatlanishingiz mumkin. (0,0) dan (n-1,n-1) ga yetib borish uchun zarur bo'lgan minimal vaqtni toping.\n\n**1-misol:**\nKiritma: grid = [[0,2],[1,3]]\nNatija: 3\n\n**2-misol:**\nKiritma: grid = [[0,1,2,3,4],[24,23,22,21,5],[12,13,14,15,16],[11,17,18,19,20],[10,9,8,7,6]]\nNatija: 16",
    starterCodeJs: 'function swimInWater(grid) {\n  // your code here\n}',
    starterCodePy: 'def swim_in_water(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int swimInWater(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-036',
    title: "Ko'pi Bilan K Ta To'xtash Bilan Eng Arzon Parvoz",
    difficulty: 'HARD',
    points: 68,
    tags: ['Grafiklar'],
    description: "n ta shahar va flights massivi ([from, to, price] shaklida) berilgan. src shahridan dst shahriga ko'pi bilan k ta oraliq to'xtash (ya'ni ko'pi bilan k+1 ta parvoz) bilan yetib borishning eng arzon narxini toping. Agar bunday yo'l mavjud bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: n = 4, flights = [[0,1,100],[1,2,100],[2,0,100],[1,3,600],[2,3,200]], src = 0, dst = 3, k = 1\nNatija: 700\n\n**2-misol:**\nKiritma: n = 3, flights = [[0,1,100],[1,2,100],[0,2,500]], src = 0, dst = 2, k = 1\nNatija: 200",
    starterCodeJs: 'function findCheapestPrice(n, flights, src, dst, k) {\n  // your code here\n}',
    starterCodePy: 'def find_cheapest_price(n, flights, src, dst, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int findCheapestPrice(int n, vector<vector<int>>& flights, int src, int dst, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-037',
    title: "Daraxtning Diametri",
    difficulty: 'HARD',
    points: 71,
    tags: ['Grafiklar'],
    description: "n ta tugunli vaznli daraxt edges massivi ([u,v,w] shaklida) orqali berilgan (daraxt — siklsiz bog'langan graf). Daraxtdagi ikkita tugun orasidagi eng uzun yo'lning umumiy uzunligini (daraxt diametrini) toping.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1,1],[0,2,1],[1,3,1],[1,4,1]]\nNatija: 3\nIzoh: 2-tugundan 3 yoki 4-tugungacha bo'lgan yo'l uzunligi 3.\n\n**2-misol:**\nKiritma: n = 2, edges = [[0,1,5]]\nNatija: 5",
    starterCodeJs: 'function treeDiameter(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def tree_diameter(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int treeDiameter(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-038',
    title: "Grafdagi Muhim Tugunlar (Kesuvchi Cho'qqilar)",
    difficulty: 'HARD',
    points: 83,
    tags: ['Grafiklar'],
    description: "n ta tugunli bog'langan yo'naltirilmagan graf edges massivi ([u,v]) orqali berilgan. Olib tashlanganda grafni bir necha bog'langan qismga ajratib yuboradigan barcha tugunlarni (kesuvchi cho'qqilarni, articulation points) toping.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]\nNatija: [1,3]\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: [1]",
    starterCodeJs: 'function findArticulationPoints(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def find_articulation_points(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findArticulationPoints(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-039',
    title: "Barcha Nuqtalarni Minimal Narxda Ulash",
    difficulty: 'HARD',
    points: 79,
    tags: ['Grafiklar'],
    description: "points massivi berilgan, har bir elementi [x, y] — tekislikdagi nuqta koordinatalari. Ikki nuqta orasidagi ulanish narxi ular orasidagi Manxetten masofasiga teng (|x1-x2| + |y1-y2|). Barcha nuqtalarni bevosita yoki bilvosita bir-biriga ulash uchun zarur bo'lgan minimal umumiy narxni toping.\n\n**1-misol:**\nKiritma: points = [[0,0],[2,2],[3,10],[5,2],[7,0]]\nNatija: 20\n\n**2-misol:**\nKiritma: points = [[3,12],[-2,5],[-4,1]]\nNatija: 18",
    starterCodeJs: 'function minCostConnectPoints(points) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_connect_points(points):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCostConnectPoints(vector<vector<int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-040',
    title: "Graf Ikki Qismli (Bipartite) Ekanligini Tekshirish",
    difficulty: 'HARD',
    points: 60,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilmagan graf qo'shnilar ro'yxati (adjacency list) graph shaklida berilgan, graph[i] — i tuguniga qo'shni tugunlar ro'yxati. Tugunlarni ikkita guruhga shunday bo'lish mumkinligini tekshiringki, har bir qirra ikki xil guruhdagi tugunlarni bog'lasin (ya'ni graf ikki qismli bo'lsinmi).\n\n**1-misol:**\nKiritma: graph = [[1,2,3],[0,2],[0,1,3],[0,2]]\nNatija: false\n\n**2-misol:**\nKiritma: graph = [[1,3],[0,2],[1,3],[0,2]]\nNatija: true",
    starterCodeJs: 'function isBipartite(graph) {\n  // your code here\n}',
    starterCodePy: 'def is_bipartite(graph):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isBipartite(vector<vector<int>>& graph) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-041',
    title: "Kuchli Bog'langan Komponentalarni Sanash",
    difficulty: 'HARD',
    points: 88,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilgan graf edges massivi ([u,v]) orqali berilgan. Grafdagi kuchli bog'langan komponentalar (strongly connected components) sonini toping — har bir komponentadagi istalgan ikki tugun orasida ikki tomonlama (u dan v ga va v dan u ga) yo'l mavjud bo'lishi kerak.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[2,3],[3,4]]\nNatija: 3\nIzoh: {0,1,2}, {3}, {4} — jami 3 ta komponenta.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]]\nNatija: 1",
    starterCodeJs: 'function countStronglyConnectedComponents(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def count_strongly_connected_components(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int countStronglyConnectedComponents(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-042',
    title: "To'siqlarni Bartaraf Etib Eng Qisqa Yo'l",
    difficulty: 'HARD',
    points: 81,
    tags: ['Grafiklar'],
    description: "m x n o'lchamli ikkilik grid berilgan (0 — bo'sh katak, 1 — to'siq) va k butun soni. Siz ko'pi bilan k ta to'siqni bartaraf etib o'tishingiz mumkin. Yuqori chap burchakdan pastki o'ng burchakka (faqat 4 ta yo'nalishda harakatlanib) yetib borish uchun zarur bo'lgan minimal qadamlar sonini toping. Agar yetib bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: grid = [[0,0,0],[1,1,0],[0,0,0],[0,1,1],[0,0,0]], k = 1\nNatija: 6\n\n**2-misol:**\nKiritma: grid = [[0,1,1],[1,1,1],[1,0,0]], k = 1\nNatija: -1",
    starterCodeJs: 'function shortestPathWithObstacleElimination(grid, k) {\n  // your code here\n}',
    starterCodePy: 'def shortest_path_with_obstacle_elimination(grid, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestPathWithObstacleElimination(vector<vector<int>>& grid, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-043',
    title: "Ortiqcha Qirrani Aniqlash",
    difficulty: 'HARD',
    points: 64,
    tags: ['Grafiklar'],
    description: "Boshida n ta tugunli daraxt bo'lib, unga tasodifan bitta qo'shimcha qirra qo'shilgan (natijada aynan bitta sikl hosil bo'lgan). edges massivi ([u,v] juftliklari, kiritilish tartibida) berilgan. Olib tashlansa, natijada qolgan graf yana n ta tugunli daraxtga aylanadigan ortiqcha qirrani toping. Agar bir nechta javob mavjud bo'lsa, edges massivida oxirgi paydo bo'lganini qaytaring.\n\n**1-misol:**\nKiritma: edges = [[1,2],[1,3],[2,3]]\nNatija: [2,3]\n\n**2-misol:**\nKiritma: edges = [[1,2],[2,3],[3,4],[1,4],[1,5]]\nNatija: [1,4]",
    starterCodeJs: 'function findRedundantConnection(edges) {\n  // your code here\n}',
    starterCodePy: 'def find_redundant_connection(edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findRedundantConnection(vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-044',
    title: "Maksimal Ehtimollik Bilan Yo'l Topish",
    difficulty: 'HARD',
    points: 72,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilmagan graf edges massivi ([u,v] juftliklari) va succProb massivi (har bir qirra bo'ylab muvaffaqiyatli o'tish ehtimoli) berilgan. start tugunidan end tugunigacha bo'lgan yo'lning ehtimoli — unga kiruvchi barcha qirralar ehtimolining ko'paytmasi sifatida hisoblanadi. start dan end gacha bo'lgan eng katta ehtimollikni toping (agar yo'l mavjud bo'lmasa, 0 qaytaring).\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[0,2]], succProb = [0.5,0.5,0.2], start = 0, end = 2\nNatija: 0.25\nIzoh: 0->1->2 yo'li 0.5*0.5=0.25 ehtimollikka ega, bu 0->2 to'g'ridan-to'g'ri yo'l (0.2) dan katta.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1]], succProb = [0.5], start = 0, end = 2\nNatija: 0",
    starterCodeJs: 'function maxProbabilityPath(n, edges, succProb, start, end) {\n  // your code here\n}',
    starterCodePy: 'def max_probability_path(n, edges, succ_prob, start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'double maxProbabilityPath(int n, vector<vector<int>>& edges, vector<double>& succProb, int start, int end) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-045',
    title: "Yo'naltirilgan Siklsiz Grafda Eng Uzun Yo'l",
    difficulty: 'HARD',
    points: 75,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilgan siklsiz graf (DAG) edges massivi ([u,v,w] vaznli qirralar) orqali berilgan. Grafdagi istalgan ikki tugun orasidagi eng uzun yo'lning umumiy vaznini toping.\n\n**1-misol:**\nKiritma: n = 6, edges = [[0,1,5],[0,2,3],[1,3,6],[1,2,2],[2,4,4],[2,5,2],[2,3,7],[3,5,1],[4,5,-1]]\nNatija: 15\nIzoh: 0->1->2->3->5 yo'li 5+2+7+1=15 umumiy vaznga ega.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1,2],[1,2,3]]\nNatija: 5",
    starterCodeJs: 'function longestPathInDAG(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def longest_path_in_dag(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestPathInDAG(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-046',
    title: "Manzilga Yetib Borish Yo'llari Sonini Sanash",
    difficulty: 'HARD',
    points: 80,
    tags: ['Grafiklar'],
    description: "n ta chorraha (0 dan n-1 gacha, 0 — boshlang'ich, n-1 — manzil) va roads massivi ([u,v,time] shaklida, ikki tomonlama yo'llar) berilgan. 0-chorrahadan (n-1)-chorrahaga eng qisqa vaqt sarflaydigan yo'llarning sonini sanang. Javobni 10^9+7 ga bo'lgan qoldiq sifatida qaytaring.\n\n**1-misol:**\nKiritma: n = 7, roads = [[0,6,7],[0,1,2],[1,2,3],[1,3,3],[6,3,3],[3,5,1],[6,5,1],[2,5,1],[0,4,5],[4,6,2]]\nNatija: 4\n\n**2-misol:**\nKiritma: n = 2, roads = [[0,1,5]]\nNatija: 1",
    starterCodeJs: 'function countPathsToDestination(n, roads) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_to_destination(n, roads):\n    # your code here\n    pass',
    starterCodeCpp: 'int countPathsToDestination(int n, vector<vector<int>>& roads) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-047',
    title: "Grafik Orqali Bo'linishlarni Baholash",
    difficulty: 'HARD',
    points: 77,
    tags: ['Grafiklar'],
    description: "equations massivi (har biri [A, B] o'zgaruvchilar juftligi) va values massivi (A/B nisbatining qiymati) berilgan — bular og'irlikli yo'naltirilgan graf sifatida ifodalanishi mumkin. queries massividagi har bir [C, D] so'rovi uchun C/D nisbatini hisoblang; agar hisoblab bo'lmasa (o'zgaruvchi mavjud emas yoki yo'l topilmasa), -1.0 qaytaring.\n\n**1-misol:**\nKiritma: equations = [['a','b'],['b','c']], values = [2.0,3.0], queries = [['a','c'],['b','a'],['a','e']]\nNatija: [6.0,0.5,-1.0]\n\n**2-misol:**\nKiritma: equations = [['a','b']], values = [0.5], queries = [['a','b'],['b','a']]\nNatija: [0.5,2.0]",
    starterCodeJs: 'function calcEquation(equations, values, queries) {\n  // your code here\n}',
    starterCodePy: 'def calc_equation(equations, values, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<double> calcEquation(vector<vector<string>>& equations, vector<double>& values, vector<vector<string>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-048',
    title: "Manzilga Yetib Borishning Ikkinchi Minimal Vaqti",
    difficulty: 'HARD',
    points: 89,
    tags: ['Grafiklar'],
    description: "n ta tugunli (1 dan n gacha) bog'langan yo'naltirilmagan graf edges massivi orqali berilgan. Har bir qirradan o'tish uchun time daqiqa kerak, har bir tugundagi svetofor change daqiqada yashildan qizilga va aksincha almashadi (0-daqiqada yashil boshlanadi; qizil paytida to'xtab kutish kerak, harakatlanib bo'lmaydi). 1-tugundan n-tugungacha yetib borishning ikkinchi (qat'iy) minimal vaqtini toping (birinchi minimal vaqtdan qat'iy katta bo'lgan eng kichik yetib borish vaqti).\n\n**1-misol:**\nKiritma: n = 5, edges = [[1,2],[1,3],[1,4],[3,4],[4,5]], time = 3, change = 5\nNatija: 13\n\n**2-misol:**\nKiritma: n = 2, edges = [[1,2]], time = 3, change = 2\nNatija: 11",
    starterCodeJs: 'function secondMinimumTime(n, edges, time, change) {\n  // your code here\n}',
    starterCodePy: 'def second_minimum_time(n, edges, time, change):\n    # your code here\n    pass',
    starterCodeCpp: 'int secondMinimumTime(int n, vector<vector<int>>& edges, int time, int change) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-049',
    title: "Eng Keng Yo'l: Maksimal Minimal Qirra Og'irligi",
    difficulty: 'HARD',
    points: 78,
    tags: ['Grafiklar'],
    description: "n ta tugunli yo'naltirilmagan vaznli graf edges massivi ([u,v,w], w — qirraning 'sig'imi') orqali berilgan. start dan end gacha bo'lgan barcha mumkin yo'llar orasidan, yo'ldagi eng kichik qirra og'irligi eng katta bo'lgan yo'lni tanlang va o'sha eng kichik qiymatni (yo'lning 'kengligini') qaytaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,4],[0,2,2],[1,3,3],[2,3,5]], start = 0, end = 3\nNatija: 3\nIzoh: 0->1->3 yo'lida minimal qirra og'irligi min(4,3)=3, 0->2->3 yo'lida min(2,5)=2. Eng katta 3.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1,1],[1,2,1]], start = 0, end = 2\nNatija: 1",
    starterCodeJs: 'function maximumMinimumPath(n, edges, start, end) {\n  // your code here\n}',
    starterCodePy: 'def maximum_minimum_path(n, edges, start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'int maximumMinimumPath(int n, vector<vector<int>>& edges, int start, int end) {\n    // your code here\n}',
  },
  {
    key: 'hard-c-050',
    title: "Kurslar Tartibi: Topologik Saralash",
    difficulty: 'HARD',
    points: 61,
    tags: ['Grafiklar'],
    description: "numCourses ta kurs (0 dan numCourses-1 gacha) va prerequisites massivi ([a,b] — b kursi a kursidan oldin tugallanishi kerak) berilgan. Barcha kurslarni tugallash mumkin bo'lgan bitta to'g'ri tartibni toping. Agar barcha kurslarni tugallash mumkin bo'lmasa (siklik bog'liqlik mavjud bo'lsa), bo'sh massiv qaytaring.\n\n**1-misol:**\nKiritma: numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]\nNatija: [0,1,2,3]\nIzoh: 0 dan keyin 1 va 2, ulardan keyin 3 kursini o'tish mumkin (boshqa to'g'ri tartiblar ham qabul qilinadi).\n\n**2-misol:**\nKiritma: numCourses = 2, prerequisites = [[1,0],[0,1]]\nNatija: []",
    starterCodeJs: 'function findOrder(numCourses, prerequisites) {\n  // your code here\n}',
    starterCodePy: 'def find_order(num_courses, prerequisites):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findOrder(int numCourses, vector<vector<int>>& prerequisites) {\n    // your code here\n}',
  },
];
