export const problems = [
  {
    key: 'hard-a-001',
    title: "Yomg'ir Suvini Yig'ish",
    difficulty: 'HARD',
    points: 70,
    tags: ['Massivlar'],
    description: "n ta ustunning balandliklarini ifodalovchi height massivi berilgan. Har bir ustun kengligi 1 ga teng devor bo'lib, yomg'ir yog'gandan keyin ustunlar orasida qancha suv yig'ilishini hisoblang. Yechim O(n) vaqt va O(1) qo'shimcha xotirada ishlashi kerak (ikki ko'rsatkich usuli).\n\n**1-misol:**\nKiritma: height = [0,1,0,2,1,0,1,3,2,1,2,1]\nNatija: 6\n\n**2-misol:**\nKiritma: height = [4,2,0,3,2,5]\nNatija: 9",
    starterCodeJs: 'function trap(height) {\n  // your code here\n}',
    starterCodePy: 'def trap(height):\n    # your code here\n    pass',
    starterCodeCpp: 'int trap(vector<int>& height) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-002',
    title: "Sirg'anuvchi Oyna Maksimumi",
    difficulty: 'HARD',
    points: 65,
    tags: ['Massivlar'],
    description: "nums massivi va k o'lchamli sirg'anuvchi oyna berilgan. Oyna har safar bitta pozitsiyaga o'ngga siljiganda, har bir holatdagi oynadagi maksimal elementni qaytaring. Yechim O(n) vaqt murakkabligida (monoton deque - ikki tomonlama navbat) bo'lishi shart, oddiy O(n*k) qabul qilinmaydi.\n\n**1-misol:**\nKiritma: nums = [1,3,-1,-3,5,3,6,7], k = 3\nNatija: [3,3,5,5,6,7]",
    starterCodeJs: 'function maxSlidingWindow(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def maxSlidingWindow(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> maxSlidingWindow(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-003',
    title: "Yo'qolgan Birinchi Musbat Son",
    difficulty: 'HARD',
    points: 75,
    tags: ['Massivlar'],
    description: "Saralanmagan butun sonlar massivi nums berilgan. Massivda uchramaydigan eng kichik musbat butun sonni toping. Yechim O(n) vaqt va O(1) qo'shimcha xotirada (massivning o'zini indekslash uchun ishlatib) ishlashi kerak.\n\n**1-misol:**\nKiritma: nums = [3,4,-1,1]\nNatija: 2\n\n**2-misol:**\nKiritma: nums = [1,2,0]\nNatija: 3",
    starterCodeJs: 'function firstMissingPositive(nums) {\n  // your code here\n}',
    starterCodePy: 'def firstMissingPositive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int firstMissingPositive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-004',
    title: "Ikki Saralangan Massiv Mediani",
    difficulty: 'HARD',
    points: 90,
    tags: ['Massivlar'],
    description: "Ikkita saralangan massiv nums1 (m ta element) va nums2 (n ta element) berilgan. Ularni birlashtirgandagi mediani toping. Umumiy vaqt murakkabligi O(log(m+n)) bo'lishi shart, oddiy birlashtirib saralash yechimi qabul qilinmaydi.\n\n**1-misol:**\nKiritma: nums1 = [1,3], nums2 = [2]\nNatija: 2.0\n\n**2-misol:**\nKiritma: nums1 = [1,2], nums2 = [3,4]\nNatija: 2.5",
    starterCodeJs: 'function findMedianSortedArrays(nums1, nums2) {\n  // your code here\n}',
    starterCodePy: 'def findMedianSortedArrays(nums1, nums2):\n    # your code here\n    pass',
    starterCodeCpp: 'double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-005',
    title: "2D Matritsada Maksimal Yig'indili To'rtburchak",
    difficulty: 'HARD',
    points: 80,
    tags: ['Massivlar'],
    description: "m x n o'lchamli butun sonlardan iborat matritsa berilgan. Ushbu matritsa ichidagi elementlar yig'indisi maksimal bo'lgan to'rtburchak qism-matritsani toping va uning yig'indisini qaytaring. Yechim O(n^2 * m) atrofida bo'lishi kerak (har bir ustun juftligi uchun Kadane algoritmini qo'llash orqali).\n\n**1-misol:**\nKiritma: matrix = [[1,0,1],[0,-2,3]]\nNatija: 4\nIzoh: 3-ustun (indeks 2) ikkala qatordan iborat qism-matritsa 1+3=4 yig'indini beradi.",
    starterCodeJs: 'function maxSumSubmatrix(matrix) {\n  // your code here\n}',
    starterCodePy: 'def maxSumSubmatrix(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxSumSubmatrix(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-006',
    title: "Oraliq Yig'indilar Soni",
    difficulty: 'HARD',
    points: 75,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi hamda lower va upper chegaralari berilgan. S(i,j) massivning i dan j gacha (ikkalasi ham kiritilgan) bo'lgan qism yig'indisi bo'lsin. lower <= S(i,j) <= upper shartini qanoatlantiradigan (i,j) juftliklar sonini toping. Yechim O(n log n) vaqtda ishlashi kerak (modifikatsiyalangan merge sort orqali).\n\n**1-misol:**\nKiritma: nums = [-2,5,-1], lower = -2, upper = 2\nNatija: 3\nIzoh: mos qism yig'indilar: -2, -1, va 5+(-2)+(-1)=... aslida S(0,0)=-2, S(2,2)=-1, S(0,2)=2.",
    starterCodeJs: 'function countRangeSum(nums, lower, upper) {\n  // your code here\n}',
    starterCodePy: 'def countRangeSum(nums, lower, upper):\n    # your code here\n    pass',
    starterCodeCpp: 'int countRangeSum(vector<int>& nums, int lower, int upper) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-007',
    title: "Gistogrammadagi Eng Katta To'rtburchak",
    difficulty: 'HARD',
    points: 70,
    tags: ['Massivlar'],
    description: "Har bir ustun kengligi 1 bo'lgan gistogramma balandliklari heights massivida berilgan. Gistogramma ichidagi eng katta yuzali to'g'ri to'rtburchakning yuzasini toping. Yechim O(n) vaqtda (monoton stek yordamida) ishlashi lozim, O(n^2) yechim katta kirishlarda vaqt chegarasidan chiqadi.\n\n**1-misol:**\nKiritma: heights = [2,1,5,6,2,3]\nNatija: 10\nIzoh: 5 va 6 balandlikdagi ustunlardan tashkil topgan to'rtburchak 2*5=10 yuzani beradi.",
    starterCodeJs: 'function largestRectangleArea(heights) {\n  // your code here\n}',
    starterCodePy: 'def largestRectangleArea(heights):\n    # your code here\n    pass',
    starterCodeCpp: 'int largestRectangleArea(vector<int>& heights) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-008',
    title: "K ta Saralangan Massivni Birlashtirish",
    difficulty: 'HARD',
    points: 65,
    tags: ['Massivlar'],
    description: "k ta saralangan butun sonlar massivlaridan iborat arrays ro'yxati berilgan. Ularning barchasini bitta saralangan massivga birlashtiring. Yechim min-heap (ustuvorlik navbati) yordamida O(N log k) vaqtda ishlashi kerak, bu yerda N - barcha elementlarning umumiy soni.\n\n**1-misol:**\nKiritma: arrays = [[1,4,5],[1,3,4],[2,6]]\nNatija: [1,1,2,3,4,4,5,6]",
    starterCodeJs: 'function mergeKArrays(arrays) {\n  // your code here\n}',
    starterCodePy: 'def merge_k_arrays(arrays):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergeKArrays(vector<vector<int>>& arrays) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-009',
    title: "Aniq K Xil Son Bo'lgan Qism Massivlar",
    difficulty: 'HARD',
    points: 78,
    tags: ['Massivlar'],
    description: "Musbat sonlardan iborat nums massivi va k soni berilgan. Ichida aniq k xil son bo'lgan uzluksiz qism massivlar (subarrays) sonini toping. Yechim O(n) vaqtda ishlashi kerak (\"ko'pi bilan k xil son\" funksiyasidan \"ko'pi bilan k-1 xil son\" funksiyasini ayirish formulasi orqali).\n\n**1-misol:**\nKiritma: nums = [1,2,1,2,3], k = 2\nNatija: 7",
    starterCodeJs: 'function subarraysWithKDistinct(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def subarraysWithKDistinct(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int subarraysWithKDistinct(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-010',
    title: "Yig'indisi K Dan Katta Bo'lgan Eng Qisqa Qism Massiv",
    difficulty: 'HARD',
    points: 82,
    tags: ['Massivlar'],
    description: "Butun sonlardan (manfiy bo'lishi ham mumkin) iborat nums massivi va k soni berilgan. Yig'indisi kamida k bo'lgan eng qisqa (bo'sh bo'lmagan) uzluksiz qism massivning uzunligini toping, agar bunday qism massiv mavjud bo'lmasa -1 qaytaring. Yechim O(n) vaqtda (prefiks yig'indi va monoton deque kombinatsiyasi orqali) ishlashi kerak.\n\n**1-misol:**\nKiritma: nums = [2,-1,2], k = 3\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [1,2], k = 4\nNatija: -1",
    starterCodeJs: 'function shortestSubarray(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def shortestSubarray(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestSubarray(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-011',
    title: "Yomg'ir Suvini Yig'ish II",
    difficulty: 'HARD',
    points: 85,
    tags: ['Massivlar'],
    description: "m x n o'lchamli musbat butun sonlardan iborat heightMap matritsasi berilgan, u yer relyefining balandliklarini ifodalaydi. Yomg'ir yog'gandan so'ng relyef qancha suv ushlab qola olishini hisoblang. Yechim chekka katakchalardan boshlab min-heap yordamida ichkariga siljish orqali O(m*n*log(m*n)) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: heightMap = [[1,4,3,1,3,2],[3,2,1,3,2,4],[2,3,3,2,3,1]]\nNatija: 4",
    starterCodeJs: 'function trapRainWater(heightMap) {\n  // your code here\n}',
    starterCodePy: 'def trapRainWater(heightMap):\n    # your code here\n    pass',
    starterCodeCpp: 'int trapRainWater(vector<vector<int>>& heightMap) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-012',
    title: "Sirg'anuvchi Oyna Mediani",
    difficulty: 'HARD',
    points: 72,
    tags: ['Massivlar'],
    description: "nums massivi va k o'lchamli oyna berilgan. Oyna har safar bitta pozitsiyaga siljiganda, oynadagi elementlarning medianini qaytaring. Yechim ikkita balanslangan tuzilma (masalan, tartiblangan konteyner yoki ikkita heap) yordamida har bir siljish uchun O(log k) vaqtda yangilanishi kerak, oddiy har safar qayta saralash O(n*k log k) qabul qilinmaydi.\n\n**1-misol:**\nKiritma: nums = [1,3,-1,-3,5,3,6,7], k = 3\nNatija: [1,-1,-1,3,5,6]",
    starterCodeJs: 'function medianSlidingWindow(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def medianSlidingWindow(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<double> medianSlidingWindow(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-013',
    title: "Saralangan Matritsadagi K-chi Kichik Element",
    difficulty: 'HARD',
    points: 68,
    tags: ['Massivlar'],
    description: "n x n o'lchamli matritsa berilgan, unda har bir qatorning va ustunning elementlari o'sish tartibida saralangan. Matritsadagi k-chi kichik elementni toping. Yechim to'liq O(n^2) elementni saralashdan tezroq, masalan binary search on value yoki heap yordamida ishlashi tavsiya etiladi.\n\n**1-misol:**\nKiritma: matrix = [[1,5,9],[10,11,13],[12,13,15]], k = 8\nNatija: 13",
    starterCodeJs: 'function kthSmallest(matrix, k) {\n  // your code here\n}',
    starterCodePy: 'def kthSmallest(matrix, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int kthSmallest(vector<vector<int>>& matrix, int k) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-014',
    title: "Sharlarni Yorish Uchun Minimal O'qlar Soni",
    difficulty: 'HARD',
    points: 64,
    tags: ['Massivlar'],
    description: "Har bir sharning gorizontal diapazonini ifodalovchi [xstart, xend] juftliklaridan iborat points massivi berilgan. Vertikal yo'nalishda otilgan o'q o'z diapazoniga tegib turgan barcha sharlarni yorib o'tadi. Barcha sharlarni yorish uchun zarur bo'lgan minimal o'qlar sonini toping. Yechim O(n log n) vaqtda (diapazonlarni tugash nuqtasi bo'yicha saralab, ochko'z (greedy) usulda) ishlashi kerak.\n\n**1-misol:**\nKiritma: points = [[10,16],[2,8],[1,6],[7,12]]\nNatija: 2",
    starterCodeJs: 'function findMinArrowShots(points) {\n  // your code here\n}',
    starterCodePy: 'def findMinArrowShots(points):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinArrowShots(vector<vector<int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-015',
    title: "Massivni Maksimal Qism Yig'indisi Minimal Bo'ladigan Qilib Bo'lish",
    difficulty: 'HARD',
    points: 80,
    tags: ['Massivlar'],
    description: "Manfiy bo'lmagan butun sonlardan iborat nums massivi va m soni berilgan. Massivni ketma-ket m ta uzluksiz qismga (bo'linish tartibini o'zgartirmasdan) bo'lish kerak, shunday qilib qismlarning yig'indilaridan eng kattasi mumkin bo'lgan eng kichik qiymatga ega bo'lsin. Ushbu minimal maksimal yig'indini toping. Yechim binary search on answer + ochko'z tekshirish orqali O(n log(sum)) vaqtda bo'lishi kerak.\n\n**1-misol:**\nKiritma: nums = [7,2,5,10,8], m = 2\nNatija: 18\nIzoh: [7,2,5] va [10,8] qismlariga bo'lish orqali maksimal yig'indi 18 bo'ladi va bu minimal mumkin bo'lgan qiymat.",
    starterCodeJs: 'function splitArray(nums, m) {\n  // your code here\n}',
    starterCodePy: 'def splitArray(nums, m):\n    # your code here\n    pass',
    starterCodeCpp: 'int splitArray(vector<int>& nums, int m) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-016',
    title: "Ruscha Quti",
    difficulty: 'HARD',
    points: 74,
    tags: ['Massivlar'],
    description: "envelopes massivi berilgan, har bir element [width, height] juftligidan iborat. Bir konvert boshqasiga faqat ikkala o'lchami ham qat'iy kichik bo'lgandagina joylashtirilishi mumkin (aylantirishga ruxsat yo'q). Bir-biriga ichma-ich joylashtirilishi mumkin bo'lgan konvertlarning maksimal sonini toping. Yechim O(n log n) vaqtda (kengligi bo'yicha saralash, so'ng balandlik bo'yicha eng uzun qat'iy o'suvchi ketma-ketlik) ishlashi kerak.\n\n**1-misol:**\nKiritma: envelopes = [[5,4],[6,4],[6,7],[2,3]]\nNatija: 3\nIzoh: [2,3] -> [5,4] -> [6,7] zanjiri 3 ta konvertdan iborat.",
    starterCodeJs: 'function maxEnvelopes(envelopes) {\n  // your code here\n}',
    starterCodePy: 'def maxEnvelopes(envelopes):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxEnvelopes(vector<vector<int>>& envelopes) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-017',
    title: "Teskari Juftliklar Soni",
    difficulty: 'HARD',
    points: 76,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi berilgan. i < j va nums[i] > 2*nums[j] shartini qanoatlantiradigan (i,j) juftliklar (\"teskari juftliklar\") sonini toping. Yechim O(n log n) vaqtda (modifikatsiyalangan merge sort yoki Fenwick daraxti/BIT yordamida) ishlashi kerak, O(n^2) to'liq qidiruv katta kirishlarda vaqt chegarasidan chiqadi.\n\n**1-misol:**\nKiritma: nums = [1,3,2,3,1]\nNatija: 2\n\n**2-misol:**\nKiritma: nums = [2,4,3,5,1]\nNatija: 3",
    starterCodeJs: 'function reversePairs(nums) {\n  // your code here\n}',
    starterCodePy: 'def reversePairs(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int reversePairs(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-018',
    title: "O'zidan Keyin Kichik Sonlar Soni",
    difficulty: 'HARD',
    points: 70,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi berilgan. Har bir i indeksi uchun counts[i] qiymati nums[i] dan o'ng tomonda joylashgan va undan qat'iy kichik bo'lgan elementlar sonini bildiradi. counts massivini qaytaring. Yechim O(n log n) vaqtda (Fenwick daraxti/BIT yoki modifikatsiyalangan merge sort asosida) ishlashi kerak.\n\n**1-misol:**\nKiritma: nums = [5,2,6,1]\nNatija: [2,1,1,0]",
    starterCodeJs: 'function countSmaller(nums) {\n  // your code here\n}',
    starterCodePy: 'def countSmaller(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countSmaller(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-019',
    title: "Maksimal Farq",
    difficulty: 'HARD',
    points: 62,
    tags: ['Massivlar'],
    description: "Manfiy bo'lmagan butun sonlardan iborat nums massivi berilgan. Massivni saralagandan keyin qo'shni elementlar orasidagi eng katta farqni toping. Agar massivda 2 tadan kam element bo'lsa 0 qaytaring. Yechim taqqoslashga asoslangan saralashdan (comparison sort) foydalanmasdan, chelak (bucket) usuli yordamida O(n) vaqt va O(n) xotirada ishlashi shart.\n\n**1-misol:**\nKiritma: nums = [3,6,9,1]\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [10]\nNatija: 0",
    starterCodeJs: 'function maximumGap(nums) {\n  // your code here\n}',
    starterCodePy: 'def maximumGap(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maximumGap(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-020',
    title: "Konfet Taqsimoti",
    difficulty: 'HARD',
    points: 66,
    tags: ['Massivlar'],
    description: "n ta bola qatorga tizilgan, har bir bolaning reyting qiymati ratings massivida berilgan. Har bir bolaga kamida bitta konfet berilishi, va reytingi yuqoriroq bo'lgan bola qo'shnisiga qaraganda ko'proq konfet olishi kerak. Berilishi kerak bo'lgan minimal umumiy konfetlar sonini toping. Yechim O(n) vaqtda (chapdan o'ngga va o'ngdan chapga ikki marta o'tish orqali) ishlashi kerak.\n\n**1-misol:**\nKiritma: ratings = [1,0,2]\nNatija: 5\n\n**2-misol:**\nKiritma: ratings = [1,2,2]\nNatija: 4",
    starterCodeJs: 'function candy(ratings) {\n  // your code here\n}',
    starterCodePy: 'def candy(ratings):\n    # your code here\n    pass',
    starterCodeCpp: 'int candy(vector<int>& ratings) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-021',
    title: "Vazifalar Rejalashtiruvchisi",
    difficulty: 'HARD',
    points: 68,
    tags: ['Massivlar'],
    description: "tasks massivida harflar bilan ifodalangan vazifalar va n - bir xil turdagi ikkita vazifa orasidagi minimal sovutish (cooldown) davri berilgan. CPU bir vaqtning o'zida faqat bitta vazifani bajaradi yoki bo'sh turadi. Barcha vazifalarni bajarish uchun zarur bo'lgan minimal umumiy vaqt birliklarini toping. Yechim O(n) vaqtda (chastotalarni hisoblash va matematik formuladan foydalanib) ishlashi kerak.\n\n**1-misol:**\nKiritma: tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 2\nNatija: 8\nIzoh: A -> B -> bo'sh -> A -> B -> bo'sh -> A -> B tartibi 8 birlik vaqt talab qiladi.",
    starterCodeJs: 'function leastInterval(tasks, n) {\n  // your code here\n}',
    starterCodePy: 'def leastInterval(tasks, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int leastInterval(vector<char>& tasks, int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-022',
    title: "Minimal Uchrashuv Xonalari",
    difficulty: 'HARD',
    points: 64,
    tags: ['Massivlar'],
    description: "Uchrashuvlarning [boshlanish, tugash] vaqt oraliqlaridan iborat intervals massivi berilgan. Barcha uchrashuvlarni bir vaqtning o'zida o'tkazish uchun zarur bo'lgan minimal xonalar sonini toping. Yechim O(n log n) vaqtda (boshlanish va tugash vaqtlarini alohida saralab, ikki ko'rsatkich yoki min-heap yordamida) ishlashi kerak.\n\n**1-misol:**\nKiritma: intervals = [[0,30],[5,10],[15,20]]\nNatija: 2",
    starterCodeJs: 'function minMeetingRooms(intervals) {\n  // your code here\n}',
    starterCodePy: 'def minMeetingRooms(intervals):\n    # your code here\n    pass',
    starterCodeCpp: 'int minMeetingRooms(vector<vector<int>>& intervals) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-023',
    title: "O(n log n) da Eng Uzun O'suvchi Ketma-ketlik",
    difficulty: 'HARD',
    points: 78,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi berilgan. Eng uzun qat'iy o'suvchi qism-ketma-ketlikning (subsequence) uzunligini toping. Yechim O(n log n) vaqtda (binary search + \"tails\" massivi usuli) ishlashi shart, O(n^2) dinamik dasturlash yechimi qabul qilinmaydi.\n\n**1-misol:**\nKiritma: nums = [10,9,2,5,3,7,101,18]\nNatija: 4\nIzoh: eng uzun o'suvchi qism-ketma-ketlik [2,3,7,101] bo'lib, uzunligi 4 ga teng.",
    starterCodeJs: 'function lengthOfLIS(nums) {\n  // your code here\n}',
    starterCodePy: 'def lengthOfLIS(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int lengthOfLIS(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-024',
    title: "Super Tuxum Tashlash Muammosi",
    difficulty: 'HARD',
    points: 88,
    tags: ['Massivlar'],
    description: "k ta bir xil tuxum va n qavatli bino berilgan. Ma'lum bir kritik qavat f (0 <= f <= n) mavjud bo'lib, undan yuqorida tashlangan tuxum sinadi, pastda esa sinmaydi. Tuxum sinmaydigan eng yuqori qavatni aniq topish uchun eng yomon holatda zarur bo'ladigan minimal tashlashlar sonini toping. Yechim O(k*n log n) yoki undan yaxshiroq dinamik dasturlash yordamida ishlashi kerak, oddiy eksponensial rekursiya katta n qiymatlarida vaqt chegarasidan chiqadi.\n\n**1-misol:**\nKiritma: k = 1, n = 2\nNatija: 2\n\n**2-misol:**\nKiritma: k = 2, n = 6\nNatija: 3",
    starterCodeJs: 'function superEggDrop(k, n) {\n  // your code here\n}',
    starterCodePy: 'def superEggDrop(k, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int superEggDrop(int k, int n) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-025',
    title: "Shahar Silueti",
    difficulty: 'HARD',
    points: 84,
    tags: ['Massivlar'],
    description: "Shahardagi to'g'ri to'rtburchak binolarni ifodalovchi buildings massivi berilgan, har bir bino [left, right, height] uchligi bilan berilgan. Barcha binolarning tashqi konturi (silueti) - balandlik o'zgargan nuqtalar ro'yxatini [x, height] juftliklari ko'rinishida qaytaring. Yechim supurish chizig'i (sweep line) va max-heap yordamida O(n log n) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: buildings = [[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]]\nNatija: [[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]",
    starterCodeJs: 'function getSkyline(buildings) {\n  // your code here\n}',
    starterCodePy: 'def getSkyline(buildings):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> getSkyline(vector<vector<int>>& buildings) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-026',
    title: "Muntazam Ifodalar Mosligi",
    difficulty: 'HARD',
    points: 74,
    tags: ['Satrlar'],
    description: "s satri va '.' hamda '*' belgilarini o'z ichiga olgan p naqsh (pattern) satri berilgan. '.' istalgan bitta belgiga, '*' esa undan oldingi belgining 0 yoki undan ko'p marta takrorlanishiga mos keladi. p naqshi s satrining butun uzunligiga mos kelish-kelmasligini aniqlang. Yechim dinamik dasturlash yordamida O(|s|*|p|) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"aa\", p = \"a*\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"mississippi\", p = \"mis*is*p*.\"\nNatija: false",
    starterCodeJs: 'function isMatch(s, p) {\n  // your code here\n}',
    starterCodePy: 'def isMatch(s, p):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isMatch(string s, string p) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-027',
    title: "Wildcard Mosligi",
    difficulty: 'HARD',
    points: 72,
    tags: ['Satrlar'],
    description: "s satri va '?' hamda '*' belgilarini o'z ichiga olgan p naqsh satri berilgan. '?' istalgan bitta belgiga, '*' esa (bo'sh satrni ham qo'shgan holda) istalgan uzunlikdagi ketma-ketlikka mos keladi. p naqshi butun s ga mos kelish-kelmasligini aniqlang. Yechim O(|s|*|p|) dinamik dasturlash yoki O(|s|+|p|) ochko'z ikki ko'rsatkich usuli bilan ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"adceb\", p = \"*a*b\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"acdcb\", p = \"a*c?b\"\nNatija: false",
    starterCodeJs: 'function isMatchWildcard(s, p) {\n  // your code here\n}',
    starterCodePy: 'def isMatchWildcard(s, p):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isMatchWildcard(string s, string p) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-028',
    title: "Minimal Oyna Qism Satri",
    difficulty: 'HARD',
    points: 80,
    tags: ['Satrlar'],
    description: "s va t satrlari berilgan. s ning ichida t dagi barcha belgilarni (takrorlanishlari bilan birga) o'z ichiga olgan eng qisqa uzluksiz qism satrni toping. Agar bunday qism satr mavjud bo'lmasa, bo'sh satr qaytaring. Yechim sirg'anuvchi oyna texnikasi bilan O(|s|+|t|) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"ADOBECODEBANC\", t = \"ABC\"\nNatija: \"BANC\"\n\n**2-misol:**\nKiritma: s = \"a\", t = \"aa\"\nNatija: \"\"",
    starterCodeJs: 'function minWindow(s, t) {\n  // your code here\n}',
    starterCodePy: 'def minWindow(s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'string minWindow(string s, string t) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-029',
    title: "Xarajatlar Bilan Tahrirlash Masofasi",
    difficulty: 'HARD',
    points: 66,
    tags: ['Satrlar'],
    description: "word1 va word2 satrlari, shuningdek qo'shish (insertCost), o'chirish (deleteCost) va almashtirish (replaceCost) amallarining narxlari berilgan. word1 ni word2 ga aylantirish uchun zarur bo'lgan minimal umumiy xarajatni toping. Yechim ikki o'lchamli dinamik dasturlash orqali O(|word1|*|word2|) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: word1 = \"horse\", word2 = \"ros\", insertCost = 1, deleteCost = 1, replaceCost = 1\nNatija: 3\nIzoh: horse -> rorse (almashtirish) -> rose (o'chirish) -> ros (o'chirish), umumiy xarajat 3.",
    starterCodeJs: 'function minDistanceWithCost(word1, word2, insertCost, deleteCost, replaceCost) {\n  // your code here\n}',
    starterCodePy: 'def minDistanceWithCost(word1, word2, insertCost, deleteCost, replaceCost):\n    # your code here\n    pass',
    starterCodeCpp: 'int minDistanceWithCost(string word1, string word2, int insertCost, int deleteCost, int replaceCost) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-030',
    title: "Eng Uzun To'g'ri Qavslar Ketma-ketligi",
    difficulty: 'HARD',
    points: 70,
    tags: ['Satrlar'],
    description: "Faqat '(' va ')' belgilaridan iborat s satri berilgan. Eng uzun to'g'ri (valid) qavslar qism satrining uzunligini toping. Yechim stek yoki O(1) qo'shimcha xotira bilan ikki tomonlama sanash usuli orqali O(n) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"(()\"\nNatija: 2\n\n**2-misol:**\nKiritma: s = \")()())\"\nNatija: 4",
    starterCodeJs: 'function longestValidParentheses(s) {\n  // your code here\n}',
    starterCodePy: 'def longestValidParentheses(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestValidParentheses(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-031',
    title: "Farqli Qism Ketma-ketliklar Soni",
    difficulty: 'HARD',
    points: 76,
    tags: ['Satrlar'],
    description: "s va t satrlari berilgan. s dagi belgilarni (tartibni saqlagan holda, ba'zilarini o'chirib) t ga aylantirishning nechta xil usuli borligini hisoblang. Yechim dinamik dasturlash yordamida O(|s|*|t|) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"rabbbit\", t = \"rabbit\"\nNatija: 3\n\n**2-misol:**\nKiritma: s = \"babgbag\", t = \"bag\"\nNatija: 5",
    starterCodeJs: 'function numDistinct(s, t) {\n  // your code here\n}',
    starterCodePy: 'def numDistinct(s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'int numDistinct(string s, string t) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-032',
    title: "Aralashtirilgan Satr Tekshiruvi",
    difficulty: 'HARD',
    points: 85,
    tags: ['Satrlar'],
    description: "s1 satrini rekursiv ravishda ikkiga bo'lib, so'ng ixtiyoriy ravishda har ikki qismning joyini almashtirish orqali \"aralashtirish\" mumkin. s1 ni shu tarzda aralashtirib s2 ni hosil qilish mumkinligini aniqlang. Yechim memoizatsiya (uch o'lchamli DP yoki xesh xarita) yordamida polinomial vaqtda ishlashi kerak, oddiy to'liq rekursiv qidiruv juda sekin bo'ladi.\n\n**1-misol:**\nKiritma: s1 = \"great\", s2 = \"rgeat\"\nNatija: true\n\n**2-misol:**\nKiritma: s1 = \"abcde\", s2 = \"caebd\"\nNatija: false",
    starterCodeJs: 'function isScramble(s1, s2) {\n  // your code here\n}',
    starterCodePy: 'def isScramble(s1, s2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isScramble(string s1, string s2) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-033',
    title: "Matnni Tekislash",
    difficulty: 'HARD',
    points: 78,
    tags: ['Satrlar'],
    description: "words so'zlar ro'yxati va maxWidth maksimal qator kengligi berilgan. Matnni har bir qator aniq maxWidth belgiga teng bo'ladigan, so'zlar orasidagi bo'shliqlar imkon qadar teng taqsimlangan (chap tomondagi bo'shliqlar ko'proq bo'lishi mumkin) qatorlarga tekislang. Oxirgi qator va faqat bitta so'zdan iborat qatorlar chapga tekislanadi, qolgan joy esa o'ngda bo'sh qoldiriladi. Natijani tekislangan qatorlar ro'yxati sifatida qaytaring.\n\n**1-misol:**\nKiritma: words = [\"This\",\"is\",\"an\",\"example\",\"of\",\"text\",\"justification.\"], maxWidth = 16\nNatija: [\"This    is    an\",\"example  of text\",\"justification.  \"]",
    starterCodeJs: 'function fullJustify(words, maxWidth) {\n  // your code here\n}',
    starterCodePy: 'def fullJustify(words, maxWidth):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> fullJustify(vector<string>& words, int maxWidth) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-034',
    title: "Prefiks Qo'shish Orqali Eng Qisqa Palindrom",
    difficulty: 'HARD',
    points: 82,
    tags: ['Satrlar'],
    description: "s satri berilgan. Faqat s ning boshiga belgilar qo'shish orqali uni palindromga aylantirishning eng qisqa natijasini toping. Yechim KMP algoritmining \"failure function\"idan yoki string hashingdan foydalanib O(n) yoki O(n log n) vaqtda ishlashi kerak, oddiy O(n^2) tekshirish katta kirishlarda vaqt chegarasidan chiqadi.\n\n**1-misol:**\nKiritma: s = \"aacecaaa\"\nNatija: \"aaacecaaa\"\n\n**2-misol:**\nKiritma: s = \"abcd\"\nNatija: \"dcbabcd\"",
    starterCodeJs: 'function shortestPalindrome(s) {\n  // your code here\n}',
    starterCodePy: 'def shortestPalindrome(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string shortestPalindrome(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-035',
    title: "Kesishgan Satr Tekshiruvi",
    difficulty: 'HARD',
    points: 70,
    tags: ['Satrlar'],
    description: "s1, s2 va s3 satrlari berilgan. s3 ning s1 va s2 elementlarining nisbiy tartibini saqlagan holda kesishtirilishi (interleave qilinishi) natijasida hosil bo'lishi mumkinligini aniqlang. Yechim ikki o'lchamli dinamik dasturlash orqali O(|s1|*|s2|) vaqt va xotirada ishlashi kerak.\n\n**1-misol:**\nKiritma: s1 = \"aabcc\", s2 = \"dbbca\", s3 = \"aadbbcbcac\"\nNatija: true\n\n**2-misol:**\nKiritma: s1 = \"aabcc\", s2 = \"dbbca\", s3 = \"aadbbbaccc\"\nNatija: false",
    starterCodeJs: 'function isInterleave(s1, s2, s3) {\n  // your code here\n}',
    starterCodePy: 'def isInterleave(s1, s2, s3):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isInterleave(string s1, string s2, string s3) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-036',
    title: "So'zlarni Bo'lish II",
    difficulty: 'HARD',
    points: 80,
    tags: ['Satrlar'],
    description: "s satri va wordDict lug'at so'zlari ro'yxati berilgan. s ni bo'shliq bilan ajratilgan, wordDict dagi so'zlardan tashkil topgan barcha mumkin bo'lgan jumlalarni qaytaring (bir xil so'z bir necha marta ishlatilishi mumkin). Yechim memoizatsiya (DP + backtracking) yordamida ortiqcha qayta hisoblashlardan qochib ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"catsanddog\", wordDict = [\"cat\",\"cats\",\"and\",\"sand\",\"dog\"]\nNatija: [\"cats and dog\",\"cat sand dog\"]",
    starterCodeJs: 'function wordBreak(s, wordDict) {\n  // your code here\n}',
    starterCodePy: 'def wordBreak(s, wordDict):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> wordBreak(string s, vector<string>& wordDict) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-037',
    title: "Palindromga Bo'lishning Minimal Kesimlari",
    difficulty: 'HARD',
    points: 74,
    tags: ['Satrlar'],
    description: "s satri berilgan. Uni shunday bo'laklarga bo'lish kerakki, har bir bo'lak palindrom bo'lsin. Buning uchun zarur bo'ladigan minimal kesimlar sonini toping. Yechim O(n^2) dinamik dasturlash yordamida ishlashi kerak (palindromlik jadvalini oldindan hisoblab, so'ng minimal kesim uchun DP qo'llash orqali).\n\n**1-misol:**\nKiritma: s = \"aab\"\nNatija: 1\nIzoh: \"aa\" va \"b\" ikkita palindromga bo'lish uchun 1 ta kesim yetarli.\n\n**2-misol:**\nKiritma: s = \"a\"\nNatija: 0",
    starterCodeJs: 'function minCut(s) {\n  // your code here\n}',
    starterCodePy: 'def minCut(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCut(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-038',
    title: "Eng Uzun Palindromik Qism Satr (Chiziqli Vaqt)",
    difficulty: 'HARD',
    points: 70,
    tags: ['Satrlar'],
    description: "s satri berilgan. Undagi eng uzun palindromik qism satrni toping. Yechim Manacher algoritmi yordamida O(n) vaqtda ishlashi shart; O(n^2) markazdan kengaytirish usuli katta kirishlarda vaqt chegarasidan chiqadi.\n\n**1-misol:**\nKiritma: s = \"babad\"\nNatija: \"bab\"\nIzoh: \"aba\" ham to'g'ri javob hisoblanadi.\n\n**2-misol:**\nKiritma: s = \"cbbd\"\nNatija: \"bb\"",
    starterCodeJs: 'function longestPalindrome(s) {\n  // your code here\n}',
    starterCodePy: 'def longestPalindrome(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestPalindrome(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-039',
    title: "So'z Zanjiri II",
    difficulty: 'HARD',
    points: 88,
    tags: ['Satrlar'],
    description: "beginWord, endWord va wordList berilgan. Har bir qadamda faqat bitta harf o'zgartirilib, natijaviy so'z wordList ichida bo'lishi sharti bilan beginWord dan endWord ga o'tuvchi barcha eng qisqa transformatsiya ketma-ketliklarini toping. Yechim BFS (qatlamlar bo'yicha) yordamida grafni qurib, so'ng DFS/backtracking bilan barcha eng qisqa yo'llarni tiklashi kerak.\n\n**1-misol:**\nKiritma: beginWord = \"hit\", endWord = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]\nNatija: [[\"hit\",\"hot\",\"dot\",\"dog\",\"cog\"],[\"hit\",\"hot\",\"lot\",\"log\",\"cog\"]]",
    starterCodeJs: 'function findLadders(beginWord, endWord, wordList) {\n  // your code here\n}',
    starterCodePy: 'def findLadders(beginWord, endWord, wordList):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<string>> findLadders(string beginWord, string endWord, vector<string>& wordList) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-040',
    title: "Dekodlash Usullari II",
    difficulty: 'HARD',
    points: 72,
    tags: ['Satrlar'],
    description: "Faqat raqamlar va '*' belgisidan (har qanday '1'-'9' raqamini bildiruvchi joker belgi) iborat s satri berilgan, u 'A'-'Z' harflariga '1'->'A', ..., '26'->'Z' mosligida kodlangan xabarni ifodalaydi. s ni dekodlashning nechta xil usuli borligini hisoblang. Natijani 10^9+7 modul bo'yicha qaytaring. Yechim dinamik dasturlash bilan O(n) vaqtda, barcha '*' holatlarini to'g'ri hisobga olgan holda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"*\"\nNatija: 9\n\n**2-misol:**\nKiritma: s = \"1*\"\nNatija: 18",
    starterCodeJs: 'function numDecodings(s) {\n  // your code here\n}',
    starterCodePy: 'def numDecodings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int numDecodings(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-041',
    title: "Eng Uzun Takrorlanuvchi Qism Satr",
    difficulty: 'HARD',
    points: 78,
    tags: ['Satrlar'],
    description: "s satri berilgan. Kamida ikki marta (kesishmagan holda) uchraydigan eng uzun qism satrni toping, agar bunday qism satr mavjud bo'lmasa bo'sh satr qaytaring. Yechim binary search on length va rolling hash (Rabin-Karp) kombinatsiyasi yordamida O(n log n) o'rtacha vaqtda ishlashi tavsiya etiladi.\n\n**1-misol:**\nKiritma: s = \"banana\"\nNatija: \"ana\"\n\n**2-misol:**\nKiritma: s = \"abcd\"\nNatija: \"\"",
    starterCodeJs: 'function longestDupSubstring(s) {\n  // your code here\n}',
    starterCodePy: 'def longestDupSubstring(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestDupSubstring(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-042',
    title: "Palindrom Qilish Uchun Minimal Qo'shish",
    difficulty: 'HARD',
    points: 66,
    tags: ['Satrlar'],
    description: "s satri berilgan. Unga istalgan joyga belgilar qo'shish orqali uni palindromga aylantirish uchun zarur bo'lgan minimal qo'shimchalar sonini toping. Yechim eng uzun palindromik qism-ketma-ketlik (LPS) g'oyasidan foydalanib O(n^2) dinamik dasturlashda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"zzazz\"\nNatija: 0\n\n**2-misol:**\nKiritma: s = \"mbadm\"\nNatija: 2",
    starterCodeJs: 'function minInsertions(s) {\n  // your code here\n}',
    starterCodePy: 'def minInsertions(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minInsertions(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-043',
    title: "Farqli Palindromik Qism Ketma-ketliklar Soni",
    difficulty: 'HARD',
    points: 84,
    tags: ['Satrlar'],
    description: "s satri berilgan. Undagi barcha farqli bo'sh bo'lmagan palindromik qism-ketma-ketliklar (subsequence) sonini toping. Natijani 10^9+7 modul bo'yicha qaytaring. Yechim ikki o'lchamli dinamik dasturlash orqali O(n^2) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"bccb\"\nNatija: 6\n\n**2-misol:**\nKiritma: s = \"abcdabcdabcdabcdabcdabcdabcdabcddcbadcbadcbadcbadcbadcbadcbadcba\"\nNatija: 104860361",
    starterCodeJs: 'function countPalindromicSubsequences(s) {\n  // your code here\n}',
    starterCodePy: 'def countPalindromicSubsequences(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int countPalindromicSubsequences(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-044',
    title: "Eng Uzun Umumiy Qism Ketma-ketlik va Uni Tiklash",
    difficulty: 'HARD',
    points: 75,
    tags: ['Satrlar'],
    description: "text1 va text2 satrlari berilgan. Ularning eng uzun umumiy qism-ketma-ketligi (LCS) uzunligini hisoblang va bevosita LCS satrining o'zini ham qaytaring. Yechim O(m*n) dinamik dasturlash jadvalini qurib, so'ngra jadval bo'ylab orqaga qarab yurish (backtrack) orqali LCS ni tiklashi kerak.\n\n**1-misol:**\nKiritma: text1 = \"abcde\", text2 = \"ace\"\nNatija: uzunlik 3, ketma-ketlik \"ace\"",
    starterCodeJs: 'function longestCommonSubsequence(text1, text2) {\n  // your code here\n}',
    starterCodePy: 'def longestCommonSubsequence(text1, text2):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<int, string> longestCommonSubsequence(string text1, string text2) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-045',
    title: "Birlashtirilgan So'zlar",
    difficulty: 'HARD',
    points: 80,
    tags: ['Satrlar'],
    description: "words - bir-biridan farqli satrlardan iborat massiv (bo'sh satrsiz). Ro'yxatdagi boshqa ikkita yoki undan ko'p (takrorlanishi mumkin) so'zlarni ketma-ket birlashtirish orqali hosil qilinishi mumkin bo'lgan barcha \"birlashtirilgan so'zlarni\" toping. Yechim har bir so'zni uzunligi bo'yicha saralab, DP/backtracking (so'zlar to'plamidan foydalanib) orqali samarali tekshirishi kerak.\n\n**1-misol:**\nKiritma: words = [\"cat\",\"cats\",\"catsdogcats\",\"dog\",\"dogcatsdog\",\"hippopotamuses\",\"rat\",\"ratcatdogcat\"]\nNatija: [\"catsdogcats\",\"dogcatsdog\",\"ratcatdogcat\"]",
    starterCodeJs: 'function findAllConcatenatedWords(words) {\n  // your code here\n}',
    starterCodePy: 'def findAllConcatenatedWords(words):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> findAllConcatenatedWords(vector<string>& words) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-046',
    title: "G'alati Printer",
    difficulty: 'HARD',
    points: 76,
    tags: ['Satrlar'],
    description: "G'alati printer faqat bitta xil belgidan iborat ketma-ketlikni chop etishi mumkin, har safar istalgan joyga (hatto avval chop etilgan belgilar ustiga) yozish mumkin. s satrini shu printer bilan chop etish uchun zarur bo'lgan minimal buyruqlar sonini toping. Yechim intervalli dinamik dasturlash orqali O(n^3) yoki yaxshiroq vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"aaabbb\"\nNatija: 2\n\n**2-misol:**\nKiritma: s = \"aba\"\nNatija: 2",
    starterCodeJs: 'function strangePrinter(s) {\n  // your code here\n}',
    starterCodePy: 'def strangePrinter(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int strangePrinter(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-047',
    title: "Kalkulyator III",
    difficulty: 'HARD',
    points: 82,
    tags: ['Satrlar'],
    description: "Faqat manfiy bo'lmagan butun sonlar, '+', '-', '*', '/' amallari va qavslardan ('(' , ')') iborat s ifoda satri berilgan. Amallarning standart ustunlik tartibiga (avval * va /, keyin + va -) rioya qilgan holda ifodani hisoblang. Bo'sh joylarni e'tiborsiz qoldiring. Yechim stek asosida, qavslarni rekursiya yordamida qayta ishlab, O(n) vaqtda ishlashi kerak.\n\n**1-misol:**\nKiritma: s = \"3+2*2\"\nNatija: 7\n\n**2-misol:**\nKiritma: s = \"(2+6* 3+5- (3*14/7+2)*5)+3\"\nNatija: -12",
    starterCodeJs: 'function calculate(s) {\n  // your code here\n}',
    starterCodePy: 'def calculate(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int calculate(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-048',
    title: "Noto'g'ri Qavslarni Olib Tashlash",
    difficulty: 'HARD',
    points: 78,
    tags: ['Satrlar'],
    description: "Faqat '(' , ')' va kichik lotin harflaridan iborat s satri berilgan. Undan minimal miqdorda noto'g'ri qavslarni olib tashlab, to'g'ri qavslangan satr hosil qilishning barcha mumkin bo'lgan natijalarini (takrorlanishlarsiz) qaytaring. Yechim BFS yoki backtracking + budash (pruning) yordamida amalga oshirilishi kerak, hech qanday keraksiz uzunroq natija qaytarilmasligi kerak.\n\n**1-misol:**\nKiritma: s = \"()())()\"\nNatija: [\"(())()\",\"()()()\"]\n\n**2-misol:**\nKiritma: s = \"(a)())()\"\nNatija: [\"(a)()()\",\"(a())()\"]",
    starterCodeJs: 'function removeInvalidParentheses(s) {\n  // your code here\n}',
    starterCodePy: 'def removeInvalidParentheses(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> removeInvalidParentheses(string s) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-049',
    title: "Qavslarni Turlicha Joylashtirish Natijalari",
    difficulty: 'HARD',
    points: 70,
    tags: ['Satrlar'],
    description: "Faqat sonlar va '+', '-', '*' amal belgilaridan iborat expression ifoda satri berilgan. Qavslarni turli usullarda joylashtirish orqali hosil bo'ladigan barcha mumkin bo'lgan natijalarni hisoblang va ularni istalgan tartibda qaytaring. Yechim ifodani rekursiv ravishda amal belgilari bo'yicha bo'lib, memoizatsiya bilan qayta hisoblashlardan qochishi kerak.\n\n**1-misol:**\nKiritma: expression = \"2-1-1\"\nNatija: [0,2]\n\n**2-misol:**\nKiritma: expression = \"2*3-4*5\"\nNatija: [-34,-14,-10,-10,10]",
    starterCodeJs: 'function diffWaysToCompute(expression) {\n  // your code here\n}',
    starterCodePy: 'def diffWaysToCompute(expression):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> diffWaysToCompute(string expression) {\n    // your code here\n}',
  },
  {
    key: 'hard-a-050',
    title: "Palindrom Juftliklar",
    difficulty: 'HARD',
    points: 86,
    tags: ['Satrlar'],
    description: "Bir-biridan farqli so'zlardan iborat words massivi berilgan. words[i] + words[j] birlashmasi palindrom hosil qiladigan barcha (i, j) juftliklarning indekslarini toping (i != j). Yechim to'liq qidiruv O(n^2 * k) o'rniga, har bir so'zni teskarisi bilan xesh xaritada qidirib va prefiks/suffiks palindromligini tekshirib, O(n * k^2) vaqtda ishlashi tavsiya etiladi, bu yerda k - so'zning maksimal uzunligi.\n\n**1-misol:**\nKiritma: words = [\"abcd\",\"dcba\",\"lls\",\"s\",\"sssll\"]\nNatija: [[0,1],[1,0],[3,2],[2,4]]",
    starterCodeJs: 'function palindromePairs(words) {\n  // your code here\n}',
    starterCodePy: 'def palindromePairs(words):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> palindromePairs(vector<string>& words) {\n    // your code here\n}',
  },
];
