export const problems = [
  {
    key: 'master-b-001',
    title: 'Ko\'phadlarni Tez Furye Almashtirish Bilan Ko\'paytirish',
    difficulty: 'MASTER',
    points: 190,
    tags: ['Matematika'],
    description: "Ikkita ko'phad koeffitsientlari a (darajasi n-1) va b (darajasi m-1) massivlar ko'rinishida berilgan, n va m 10^5 gacha yetishi mumkin, har bir koeffitsientning mutlaq qiymati 10^9 dan oshmaydi. Ularning ko'paytmasi bo'lgan ko'phadning barcha koeffitsientlarini toping. Oddiy usul O(n*m) vaqt talab qiladi va bu chegaradan chiqib ketadi, shuning uchun tez Furye almashtirish (FFT) yordamida O((n+m) log(n+m)) vaqtda hisoblang; oraliq hisoblashlarda double aniqlikdan foydalanib, yakuniy natijani eng yaqin butun songa yaxlitlang.\n\n**1-misol:**\nKiritma: a = [1,2,3], b = [4,5,6]\nNatija: [4,13,28,27,18]\nIzoh: (1+2x+3x^2)(4+5x+6x^2) ko'paytmasining koeffitsientlari.",
    starterCodeJs: 'function multiplyPolynomials(a, b) {\n  // your code here\n}',
    starterCodePy: 'def multiply_polynomials(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> multiplyPolynomials(vector<long long>& a, vector<long long>& b) {\n    // your code here\n}',
  },
  {
    key: 'master-b-002',
    title: 'Jokerli Satr Qidirish (Tez Furye Almashtirish)',
    difficulty: 'MASTER',
    points: 205,
    tags: ['Matematika'],
    description: "text (uzunligi n<=10^5) va pattern (uzunligi m<=n) satrlari berilgan. pattern tarkibida '*' belgisi istalgan bitta belgiga mos kelishi mumkin (wildcard). Barcha i pozitsiyalarni topingki, text[i..i+m-1] pattern ga to'liq mos keladi (har bir pozitsiyada belgilar teng yoki pattern belgisi '*'). Naive tekshirish O(n*m) bo'lib katta testlarda vaqt chegarasidan chiqadi, shuning uchun har bir belgini songa aylantirib, mosliksizlik funksiyasini convolution ko'rinishida ifodalab, FFT yordamida O(n log n) da yeching.\n\n**1-misol:**\nKiritma: text = \"abcxyz\", pattern = \"c*y\"\nNatija: [2]\nIzoh: text[2..4] = \"cxy\" bo'lib, c=c, *=x (istalgan), y=y mos keladi.",
    starterCodeJs: 'function findWildcardMatches(text, pattern) {\n  // your code here\n}',
    starterCodePy: 'def find_wildcard_matches(text, pattern):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findWildcardMatches(string text, string pattern) {\n    // your code here\n}',
  },
  {
    key: 'master-b-003',
    title: 'FFT Yordamida Juftlik Yig\'indilarini Sanash',
    difficulty: 'MASTER',
    points: 180,
    tags: ['Matematika'],
    description: "n ta manfiy bo'lmagan butun sondan iborat massiv a berilgan (0<=a[i]<=10^5, n<=2*10^5). Har bir s = 0..2*10^5 qiymati uchun nechta juftlik (i,j), i<j, a[i]+a[j]=s ekanligini toping. Bevosita hisoblash O(n^2) bo'lib yo'l qo'yilmaydi; chastota massivini o'zi bilan convolution qilib, buni FFT orqali O(V log V) da hisoblang (V - qiymatlar oralig'i), so'ng diagonal hadlarni (i=j) chiqarib tashlab, qolgan natijani 2 ga bo'ling.\n\n**1-misol:**\nKiritma: a = [1,2,3], maxSum = 5\nNatija: [0,0,0,1,1,1]\nIzoh: index s dagi qiymat necha juftlik yig'indisi s ga tengligini bildiradi: 1+2=3, 1+3=4, 2+3=5.",
    starterCodeJs: 'function countPairSums(a, maxSum) {\n  // your code here\n}',
    starterCodePy: 'def count_pair_sums(a, max_sum):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> countPairSums(vector<int>& a, int maxSum) {\n    // your code here\n}',
  },
  {
    key: 'master-b-004',
    title: 'Sonlarni Sonlar Nazariy Almashtiruvi (NTT) Bilan Ko\'paytirish',
    difficulty: 'MASTER',
    points: 220,
    tags: ['Matematika'],
    description: "Ikki juda katta musbat butun son A va B ularning o'nlik raqamlari kichik xonadan boshlab (little-endian) massiv ko'rinishida berilgan (har birida 10^5 tagacha raqam). Ularning ko'paytmasini raqamlar massivi (little-endian, keraksiz yetakchi nollarsiz) ko'rinishida qaytaring. Uzun ko'paytirish O(n*m) bo'lib katta testlarda yo'l qo'yilmaydi, floating FFT esa aniqlik yo'qotishi mumkin; shuning uchun modul p=998244353 (NTT-friendly tub son) ustida sonlar nazariy almashtirish (Number Theoretic Transform) qo'llab O(n log n) da ko'paytiring, so'ng natijani carry orqali to'g'ri raqamli songa aylantiring.\n\n**1-misol:**\nKiritma: a = [9,9] (99 sonini bildiradi), b = [9] (9 sonini bildiradi)\nNatija: [1,9,8]\nIzoh: 99 * 9 = 891, little-endian ko'rinishda [1,9,8].",
    starterCodeJs: 'function multiplyBigNumbers(a, b) {\n  // your code here\n}',
    starterCodePy: 'def multiply_big_numbers(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> multiplyBigNumbers(vector<int>& a, vector<int>& b) {\n    // your code here\n}',
  },
  {
    key: 'master-b-005',
    title: 'Chastotalar Konvolyutsiyasi (NTT) Bilan Yig\'indilarni Sanash',
    difficulty: 'MASTER',
    points: 210,
    tags: ['Matematika'],
    description: "Ikki chastota massivi freqA va freqB berilgan, bu yerda freqA[v] - birinchi to'plamda v qiymatining necha marta uchrashini bildiradi (qiymatlar 0..10^5 oralig'ida, umumiy elementlar soni 2*10^5 gacha). Har bir s uchun (birinchi to'plamdan bitta, ikkinchisidan bitta olib) yig'indisi s ga teng bo'ladigan juftliklar sonini modul mod bo'yicha hisoblang. Chastotalarni ko'phad koeffitsienti sifatida qarab, ularning ko'paytmasini NTT yordamida hisoblang (natija katta bo'lgani uchun floating FFT aniqlik yo'qotadi, mod NTT-friendly tub son sifatida tanlangan).\n\n**1-misol:**\nKiritma: freqA = [0,1], freqB = [0,0,1], mod = 1000000007\nNatija: [0,0,0,1]\nIzoh: freqA'dagi qiymat1 (1 dona) va freqB'dagi qiymat2 (1 dona) yig'indisi 3, shuning uchun result[3]=1.",
    starterCodeJs: 'function convolveFrequenciesMod(freqA, freqB, mod) {\n  // your code here\n}',
    starterCodePy: 'def convolve_frequencies_mod(freq_a, freq_b, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> convolveFrequenciesMod(vector<long long>& freqA, vector<long long>& freqB, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-006',
    title: 'Burnside Lemmasi: Marjon Ranglanishlarini Sanash',
    difficulty: 'MASTER',
    points: 175,
    tags: ['Matematika'],
    description: "n ta munchoqdan iborat aylana shaklidagi marjonni k xil rangda bo'yash mumkin. Ikki bo'yash aylanma siljish (rotation) orqali bir-biriga o'tsa, ular bir xil hisoblanadi. n va k 10^9 gacha yetishi mumkin, natijani modul 10^9+7 bo'yicha qaytaring. Burnside lemmasi (Polya sanash teoremasi) yordamida farqli marjonlar sonini (1/n) * summa(d|n) phi(n/d)*k^d formulasi bo'yicha hisoblang: n ning barcha bo'luvchilarini toping, Eyler funksiyasini hisoblang va k^d ni tez darajaga ko'tarish orqali baholang, chunki barcha aylanishlarni sanab chiqish n katta bo'lganda mumkin emas.\n\n**1-misol:**\nKiritma: n = 4, k = 2\nNatija: 6\nIzoh: 4 ta munchoqni 2 rangda bo'yashning aylanmaga nisbatan farqli 6 usuli mavjud.",
    starterCodeJs: 'function countNecklaces(n, k, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_necklaces(n, k, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countNecklaces(long long n, long long k, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-007',
    title: 'Burnside Lemmasi: Kub Yoqlarini Ranglash',
    difficulty: 'MASTER',
    points: 185,
    tags: ['Matematika'],
    description: "Kubning 6 ta yog'ini k xil rangda bo'yash mumkin, ikkita bo'yash agar kubni fazoda aylantirish orqali bir-biriga mos kelsa bir xil hisoblanadi (kubning aylanish guruhi 24 elementdan iborat). k 10^9 gacha bo'lishi mumkin, natijani modul 10^9+7 bo'yicha qaytaring. Kubning aylanish guruhidagi har bir simmetriyaning yoqlar ustidagi tsikl strukturasini aniqlab (identity, uch juft yoq o'qi bo'yicha 90/180/270 gradusli aylanishlar, qirralar va uchlar orqali aylanishlar), Burnside lemmasini qo'llang: har bir simmetriya uchun k^(tsikllar soni) ni yig'ib, 24 ga bo'ling.\n\n**1-misol:**\nKiritma: k = 2\nNatija: 10\nIzoh: Kub yoqlarini 2 rangda bo'yashning fazoviy aylanmaga nisbatan farqli 10 usuli bor.",
    starterCodeJs: 'function countCubeColorings(k, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_cube_colorings(k, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countCubeColorings(long long k, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-008',
    title: 'Hosil Qiluvchi Funksiyalar: Cheklangan Qismlar Bilan Yig\'indi Sanash',
    difficulty: 'MASTER',
    points: 195,
    tags: ['Matematika'],
    description: "Musbat butun sonlardan iborat parts to'plami (o'lchami <=100, har bir qiymat <=10^5) va maqsad n (<=10^5) berilgan. Har bir part istalgan marta (0 yoki undan ko'p) ishlatilishi mumkin bo'lgan holda, ularning yig'indisi aniq n ga teng bo'ladigan tanlovlar sonini (tartib muhim emas) modul mod bo'yicha toping. Har bir part uchun hosil qiluvchi funksiya 1/(1-x^part) ko'rinishida bo'lib, barcha partlar bo'yicha ketma-ket DP orqali koeffitsientlarni yangilab boring; naive rekursiya eksponensial vaqt talab qilgani uchun bu texnika zarur.\n\n**1-misol:**\nKiritma: n = 5, parts = [1,2,5], mod = 1000000007\nNatija: 4\nIzoh: 5; 1+2+2; 1+1+1+2; 1+1+1+1+1 - jami 4 usul.",
    starterCodeJs: 'function countPartitionsLimited(n, parts, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_partitions_limited(n, parts, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPartitionsLimited(int n, vector<int>& parts, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-009',
    title: 'Hosil Qiluvchi Funksiyalar: Cheklangan Sondagi Tangalar',
    difficulty: 'MASTER',
    points: 200,
    tags: ['Matematika'],
    description: "Tanga turlari berilgan, har biri qiymati values[i] va maksimal ishlatilish soni limits[i] bilan xarakterlanadi (turlar soni <=50, values va limits 10^5 gacha), maqsad summa n (<=10^5) berilgan. Har bir tanga turidan 0 dan limits[i] gacha bo'lgan miqdorda olib, umumiy yig'indi aniq n ga teng bo'ladigan (tartibsiz) tanlovlar sonini modul mod bo'yicha toping. Har bir tanga uchun hosil qiluvchi funksiya (1+x^v+...+x^(limit*v)) ko'rinishida, buni geometrik yig'indi ayirmasi (1-x^(v*(limit+1)))/(1-x^v) orqali DP bilan samarali qo'shib chiqing (bounded knapsack counting), chunki naive to'liq sanash yo'l qo'yilmaydi.\n\n**1-misol:**\nKiritma: values = [1,2], limits = [2,1], n = 3, mod = 1000000007\nNatija: 1\nIzoh: Yagona usul - bitta 1 va bitta 2 tanga (1+2=3), chunki uchta 1 tanga ishlatib bo'lmaydi (limit 2).",
    starterCodeJs: 'function countLimitedCoinWays(values, limits, n, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_limited_coin_ways(values, limits, n, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countLimitedCoinWays(vector<int>& values, vector<int>& limits, int n, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-010',
    title: 'Hosil Qiluvchi Funksiyalar: Chegaralangan Qismli Kompozitsiyalar',
    difficulty: 'MASTER',
    points: 170,
    tags: ['Matematika'],
    description: "n va m berilgan (n,m<=10^6). n sonini tartib muhim bo'lgan holda, har bir qismi 1 dan m gacha bo'lgan musbat butun sonlardan iborat ketma-ketliklarga (kompozitsiyalarga) yig'indisi n ga teng bo'ladigan yo'llar bilan yozish usullari sonini modul mod bo'yicha toping. Hosil qiluvchi funksiya f(x)=(x+x^2+...+x^m) bo'lib, javob [x^n] 1/(1-f(x)) ga teng; buni chiziqli rekurrenta ans(i)=ans(i-1)+...+ans(i-m) prefiks yig'indisi orqali O(n) da hisoblang, chunki m ham katta bo'lishi mumkin va naive summa har qadamda O(m) qo'shsa umumiy vaqt yo'l qo'ymaydi.\n\n**1-misol:**\nKiritma: n = 4, m = 2, mod = 1000000007\nNatija: 5\nIzoh: (1,1,1,1),(1,1,2),(1,2,1),(2,1,1),(2,2) - jami 5 ta kompozitsiya.",
    starterCodeJs: 'function countBoundedCompositions(n, m, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_bounded_compositions(n, m, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countBoundedCompositions(long long n, long long m, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-011',
    title: 'Berlekamp-Massey Algoritmi: n-chi Hadni Topish',
    difficulty: 'MASTER',
    points: 230,
    tags: ['Matematika'],
    description: "Chiziqli rekurrent ketma-ketlikning dastlabki hadlari (uzunligi <=2000, qiymatlar modul p=10^9+7 bo'yicha berilgan, ketma-ketlik tartibi noma'lum) hamda juda katta n (10^18 gacha) berilgan. Ketma-ketlikning minimal chiziqli rekurrent tenglamasini Berlekamp-Massey algoritmi orqali tiklang, so'ng n-chi hadni topish uchun x^n ni topilgan xarakteristik ko'phad bo'yicha qoldiqqa qisqartirish (Kitamasa usuli: ko'phad kvadratga ko'tarish va mod olish, ikkilik daraja ko'tarish) orqali O(k^2 log n) vaqtda hisoblang, bu yerda k - topilgan rekurrenta tartibi; to'g'ridan-to'g'ri n martalik iteratsiya n juda katta bo'lgani uchun yo'l qo'yilmaydi.\n\n**1-misol:**\nKiritma: sequence = [1,1,2,3,5,8], n = 10, mod = 1000000007\nNatija: 89\nIzoh: Ketma-ketlik Fibonachchi qonuniga bo'ysunadi, 10-chi (1-indeksli) had 89 ga teng.",
    starterCodeJs: 'function findNthTerm(sequence, n, mod) {\n  // your code here\n}',
    starterCodePy: 'def find_nth_term(sequence, n, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long findNthTerm(vector<long long>& sequence, long long n, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-012',
    title: 'Berlekamp-Massey: Signal Davomini Bashorat Qilish',
    difficulty: 'MASTER',
    points: 215,
    tags: ['Matematika'],
    description: "Noma'lum tartibli chiziqli rekurrent sensor signalining dastlabki hadlari (uzunligi <=1000, qiymatlar modul p=10^9+7 bo'yicha) berilgan. Berlekamp-Massey algoritmi yordamida signalni ishlab chiqargan eng qisqa chiziqli rekurrent munosabatni toping va shu munosabat asosida signalning keyingi hadini hisoblang. Agar topilgan rekurrenta tartibi ketma-ketlik uzunligining yarmidan katta bo'lib qolsa (ya'ni ketma-ketlik ishonchli tarzda chiziqli rekurrentaga mos kelmasa), -1 qaytaring.\n\n**1-misol:**\nKiritma: sequence = [2,4,8,16,32], mod = 1000000007\nNatija: 64\nIzoh: Har bir had oldingisining 2 barobari, keyingi had 64.",
    starterCodeJs: 'function predictNextValue(sequence, mod) {\n  // your code here\n}',
    starterCodePy: 'def predict_next_value(sequence, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long predictNextValue(vector<long long>& sequence, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-013',
    title: 'Pollard Rho: Eng Katta Tub Ko\'paytuvchi',
    difficulty: 'MASTER',
    points: 175,
    tags: ['Matematika'],
    description: "n butun soni berilgan (2<=n<=10^18). n ning eng katta tub ko'paytuvchisini toping. n juda katta bo'lgani uchun oddiy sinab ko'rish (trial division) O(sqrt(n)) usuli katta tub ko'paytuvchilar uchun juda sekin ishlaydi, shuning uchun Pollard rho faktorizatsiya algoritmini Miller-Rabin asoslik testi bilan birgalikda qo'llab, n ni tub ko'paytuvchilarga rekursiv ravishda ajrating va ular orasidan eng kattasini toping.\n\n**1-misol:**\nKiritma: n = 600851475143\nNatija: 6857\nIzoh: 600851475143 = 71 * 839 * 1471 * 6857, eng kattasi 6857.",
    starterCodeJs: 'function largestPrimeFactor(n) {\n  // your code here\n}',
    starterCodePy: 'def largest_prime_factor(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long largestPrimeFactor(long long n) {\n    // your code here\n}',
  },
  {
    key: 'master-b-014',
    title: 'Pollard Rho: Bo\'luvchilar Sonini Hisoblash',
    difficulty: 'MASTER',
    points: 165,
    tags: ['Matematika'],
    description: "n butun soni berilgan (2<=n<=10^18). n ning musbat bo'luvchilari sonini toping. n ni Pollard rho (Miller-Rabin bilan birga) yordamida tub ko'paytuvchilarga ajrating, so'ng agar n=p1^e1*p2^e2*...*pk^ek bo'lsa, bo'luvchilar soni (e1+1)*(e2+1)*...*(ek+1) formulasi orqali hisoblang; oddiy trial division n=10^18 uchun juda sekin ishlaydi.\n\n**1-misol:**\nKiritma: n = 28\nNatija: 6\nIzoh: 28 ning bo'luvchilari: 1,2,4,7,14,28 - jami 6 ta.",
    starterCodeJs: 'function countDivisors(n) {\n  // your code here\n}',
    starterCodePy: 'def count_divisors(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDivisors(long long n) {\n    // your code here\n}',
  },
  {
    key: 'master-b-015',
    title: 'Pollard Rho: Bo\'luvchilar Yig\'indisi Modul Bo\'yicha',
    difficulty: 'MASTER',
    points: 180,
    tags: ['Matematika'],
    description: "n (2<=n<=10^18) va modul mod berilgan. n ning barcha musbat bo'luvchilari yig'indisini modul mod bo'yicha hisoblang. n ni Pollard rho orqali tub ko'paytuvchilarga ajrating, har bir p^e ko'paytuvchi uchun 1+p+p^2+...+p^e geometrik yig'indisini modul arifmetikasida (teskari element yoki to'g'ridan-to'g'ri qo'shish orqali) hisoblang, so'ng barcha ko'paytuvchi guruhlarining natijalarini modul bo'yicha ko'paytiring.\n\n**1-misol:**\nKiritma: n = 12, mod = 1000000007\nNatija: 28\nIzoh: 12 ning bo'luvchilari yig'indisi 1+2+3+4+6+12=28.",
    starterCodeJs: 'function sumOfDivisorsMod(n, mod) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_divisors_mod(n, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long sumOfDivisorsMod(long long n, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-016',
    title: 'Diskret Logarifm: Baby-Step Giant-Step',
    difficulty: 'MASTER',
    points: 225,
    tags: ['Matematika'],
    description: "Tub modul p (p<=10^9), asos g (1<g<p) va h (0<h<p) berilgan. g^x ≡ h (mod p) tenglamasini qanoatlantiruvchi eng kichik manfiy bo'lmagan x ni toping, agar bunday x mavjud bo'lmasa -1 qaytaring. x ni 0 dan p-1 gacha sinab ko'rish O(p) vaqt talab qiladi va p katta bo'lganda yo'l qo'yilmaydi; buning o'rniga baby-step giant-step usulini qo'llab, x ni x=i*m-j ko'rinishida ifodalab, hash jadval yordamida O(sqrt(p) log p) da toping.\n\n**1-misol:**\nKiritma: g = 2, h = 11, p = 13\nNatija: 7\nIzoh: 2^7 mod 13 = 128 mod 13 = 11.",
    starterCodeJs: 'function discreteLog(g, h, p) {\n  // your code here\n}',
    starterCodePy: 'def discrete_log(g, h, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long discreteLog(long long g, long long h, long long p) {\n    // your code here\n}',
  },
  {
    key: 'master-b-017',
    title: 'Diskret Logarifm: Ochiq Kalitlar Almashinuvida Maxfiy Ko\'rsatkichni Topish',
    difficulty: 'MASTER',
    points: 210,
    tags: ['Matematika'],
    description: "Diffie-Hellman kalit almashinuvi tub modul p (p<=10^9) va asos g yordamida amalga oshirilgan, tarmoqda A tomonning ochiq kaliti publicKey = g^a mod p ushlab qolingan. Tizim zaifligini namoyish qilish uchun g^a ≡ publicKey (mod p) tenglamasidan a maxfiy ko'rsatkichni toping (0<=a<p, eng kichigini qaytaring; yechim yo'q bo'lsa -1). Baby-step giant-step usulidan foydalanib O(sqrt(p) log p) murakkablikda yeching, chunki p katta bo'lganda to'g'ridan-to'g'ri sinash yo'l qo'yilmaydi.\n\n**1-misol:**\nKiritma: g = 5, publicKey = 19, p = 23\nNatija: 6\nIzoh: 5^6 mod 23 = 19.",
    starterCodeJs: 'function findSharedExponent(g, publicKey, p) {\n  // your code here\n}',
    starterCodePy: 'def find_shared_exponent(g, public_key, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long findSharedExponent(long long g, long long publicKey, long long p) {\n    // your code here\n}',
  },
  {
    key: 'master-b-018',
    title: 'Umumlashgan Xitoy Qoldiqlar Teoremasi (O\'zaro Tub Bo\'lmagan Modullar)',
    difficulty: 'MASTER',
    points: 170,
    tags: ['Matematika'],
    description: "n ta kongruensiya x ≡ remainders[i] (mod moduli[i]) berilgan (n<=10^5), bu yerda moduli[i] lar juft-jufti bilan o'zaro tub bo'lishi shart emas (umumiy CRT holati). Barcha kongruensiyalarni bir vaqtda qanoatlantiruvchi eng kichik manfiy bo'lmagan x hamda umumiy modul M ni toping; agar yechim mavjud bo'lmasa null qaytaring. Kongruensiyalarni juftlab birlashtiring: har qadamda g=gcd(m1,m2) hisoblab, (r1-r2) ning g ga bo'linishini tekshiring (bo'linmasa yechim yo'q), aks holda kengaytirilgan Evklid algoritmi orqali yangi (r, lcm(m1,m2)) juftlikni hosil qiling.\n\n**1-misol:**\nKiritma: remainders = [2,4], moduli = [4,6]\nNatija: [10, 12]\nIzoh: x=10: 10 mod 4 = 2, 10 mod 6 = 4; umumiy modul lcm(4,6)=12.",
    starterCodeJs: 'function solveCongruences(remainders, moduli) {\n  // your code here\n}',
    starterCodePy: 'def solve_congruences(remainders, moduli):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<long long,long long> solveCongruences(vector<long long>& remainders, vector<long long>& moduli) {\n    // your code here\n}',
  },
  {
    key: 'master-b-019',
    title: 'Davriy Hodisalarni Sinxronlashtirish (CRT)',
    difficulty: 'MASTER',
    points: 185,
    tags: ['Matematika'],
    description: "n ta davriy hodisa berilgan, har biri offsets[i] vaqtida boshlanadi va period[i] vaqt birligida qaytadan takrorlanadi (period[i] lar o'zaro tub bo'lishi shart emas, n<=10^5). Barcha hodisalar bir vaqtning o'zida (t>=0) sodir bo'ladigan eng kichik t vaqtni toping (har bir i uchun t ≡ offsets[i] (mod periods[i])); agar bunday t mavjud bo'lmasa -1 qaytaring. Umumlashgan Xitoy qoldiqlar teoremasini ketma-ket qo'llang, har safar gcd tekshiruvi orqali kongruensiyalar mosligini tasdiqlab, kengaytirilgan Evklid algoritmi bilan birlashtiring.\n\n**1-misol:**\nKiritma: offsets = [1,3], periods = [4,5]\nNatija: 13\nIzoh: 13 mod 4 = 1, 13 mod 5 = 3, va bu shartlarni qanoatlantiruvchi eng kichik manfiy bo'lmagan son.",
    starterCodeJs: 'function findSyncTime(offsets, periods) {\n  // your code here\n}',
    starterCodePy: 'def find_sync_time(offsets, periods):\n    # your code here\n    pass',
    starterCodeCpp: 'long long findSyncTime(vector<long long>& offsets, vector<long long>& periods) {\n    // your code here\n}',
  },
  {
    key: 'master-b-020',
    title: 'Taqsimlangan Hisoblash Natijalarini CRT Orqali Birlashtirish',
    difficulty: 'MASTER',
    points: 195,
    tags: ['Matematika'],
    description: "Katta X sonini hisoblash n ta serverga bo'lingan, har bir server o'z modul m_i bo'yicha X mod m_i = r_i qoldiqni qaytargan, pairs massivi [r_i, m_i] juftliklaridan iborat (n<=10^4, m_i lar juft-jufti bilan o'zaro tub bo'lishi shart emas). Barcha serverlar natijalariga mos keladigan eng kichik manfiy bo'lmagan X ni tiklang; agar natijalar ziddiyatli bo'lsa (hech qanday X mavjud bo'lmasa) null qaytaring. Katta modul M=lcm(barcha m_i) bilan ishlash uchun uzun arifmetika va kengaytirilgan Evklid algoritmidan foydalaning.\n\n**1-misol:**\nKiritma: pairs = [[2,6],[5,9]]\nNatija: 14\nIzoh: 14 mod 6 = 2, 14 mod 9 = 5.",
    starterCodeJs: 'function mergeResidues(pairs) {\n  // your code here\n}',
    starterCodePy: 'def merge_residues(pairs):\n    # your code here\n    pass',
    starterCodeCpp: 'long long mergeResidues(vector<pair<long long,long long>>& pairs) {\n    // your code here\n}',
  },
  {
    key: 'master-b-021',
    title: 'GF(2) Ustida Gauss Elementatsiyasi: Chiroqlarni O\'chirish Boshqotirmasi',
    difficulty: 'MASTER',
    points: 200,
    tags: ['Matematika'],
    description: "n ta chiroq va m ta tugma berilgan (n,m<=500), har bir tugma bosilganda ma'lum chiroqlar to'plamining holatini XOR orqali teskarisiga o'zgartiradi (toggles[j] - shu tugma ta'sir qiladigan chiroqlar ro'yxati). Boshlang'ich holat given va maqsad holat target (har biri 0/1 massiv) berilgan. Har bir tugmani 0 yoki 1 marta bosish orqali given holatdan target holatga o'tish mumkinmi, agar mumkin bo'lsa bosilishi kerak bo'lgan tugmalar indekslari to'plamini (istalgan bitta yechim) toping, aks holda null qaytaring. Masalani GF(2) ustidagi chiziqli tenglamalar sistemasi sifatida ifodalab, XOR asosidagi Gauss elementatsiyasi orqali yeching.\n\n**1-misol:**\nKiritma: toggles = [[0,1],[1,2]], given = [0,0,0], target = [1,1,0]\nNatija: [0]\nIzoh: Faqat 0-tugmani bosish [0,0,0] ni [1,1,0] ga aylantiradi.",
    starterCodeJs: 'function solveLightsOut(toggles, given, target) {\n  // your code here\n}',
    starterCodePy: 'def solve_lights_out(toggles, given, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> solveLightsOut(vector<vector<int>>& toggles, vector<int>& given, vector<int>& target) {\n    // your code here\n}',
  },
  {
    key: 'master-b-022',
    title: 'Chiziqli Bazis: Eng Katta XOR Qiymatini Topish',
    difficulty: 'MASTER',
    points: 190,
    tags: ['Matematika'],
    description: "n ta manfiy bo'lmagan butun sondan iborat massiv nums berilgan (n<=2*10^5, har bir son <=10^18). Massivning istalgan bo'sh bo'lmagan qism to'plamini tanlab, ularning XOR yig'indisini maksimal qilish kerak - shu maksimal qiymatni toping. Har bir sonni ikkilik bitlar bo'yicha chiziqli bazisga (GF(2) ustidagi vektor fazo bazisi) Gauss elementatsiyasi orqali qo'shib boring (yuqori bitdan pastga qarab, agar mos bit bazisda band bo'lsa XOR qilib kamaytiring), so'ng bazis vektorlarini eng yuqori bitdan boshlab greedy tarzda joriy natijaga qo'shib maksimal XOR qiymatini hosil qiling.\n\n**1-misol:**\nKiritma: nums = [3,10,5,25,2,8]\nNatija: 28\nIzoh: 5 xor 25 xor 2 = 28, bu massivning istalgan qism to'plamidan olinadigan maksimal XOR qiymati.",
    starterCodeJs: 'function maxXorSubset(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_xor_subset(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxXorSubset(vector<long long>& nums) {\n    // your code here\n}',
  },
  {
    key: 'master-b-023',
    title: 'Chiziqli Bazis: Farqli XOR Qiymatlari Sonini Sanash',
    difficulty: 'MASTER',
    points: 175,
    tags: ['Matematika'],
    description: "n ta manfiy bo'lmagan butun sondan iborat massiv nums berilgan (n<=10^5, qiymatlar <=10^9). Massivning barcha qism to'plamlaridan (bo'sh to'plam ham hisoblanadi, uning XOR yig'indisi 0) hosil bo'ladigan farqli XOR qiymatlari sonini modul mod bo'yicha toping. Sonlarni GF(2) ustidagi chiziqli bazisga Gauss elementatsiyasi orqali qisqartiring; agar bazis o'lchami (rangi) r bo'lsa, javob 2^r bo'ladi, chunki bazisning har bir farqli chiziqli kombinatsiyasi farqli qiymat beradi - buni tez darajaga oshirish orqali modul bo'yicha hisoblang.\n\n**1-misol:**\nKiritma: nums = [1,2,3], mod = 1000000007\nNatija: 4\nIzoh: 3 = 1 xor 2 bo'lgani uchun chiziqli bazis rangi 2, farqli XOR qiymatlari soni 2^2=4 (0,1,2,3).",
    starterCodeJs: 'function countDistinctXorValues(nums, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_xor_values(nums, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDistinctXorValues(vector<int>& nums, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-024',
    title: 'Matritsa Darajasi va Ko\'phad Qisqartirish: Rekurrent Hadni Tezkor Topish',
    difficulty: 'MASTER',
    points: 235,
    tags: ['Matematika'],
    description: "k-tartibli chiziqli rekurrent munosabat a[i] = coeffs[0]*a[i-1]+coeffs[1]*a[i-2]+...+coeffs[k-1]*a[i-k] (mod berilgan modul bo'yicha) va boshlang'ich k ta had (initial) berilgan (k<=1000). Juda katta n (10^18 gacha) uchun a[n] ni toping. k*k o'lchamli matritsani n-darajaga ko'tarish O(k^3 log n) k katta bo'lganda juda sekin; buning o'rniga x^n ni rekurrentaning k-darajali xarakteristik ko'phadiga bo'lib qoldiqni Kitamasa usuli (ko'phad ko'paytirish va mod olish, ikkilik daraja ko'tarish) orqali O(k^2 log n) da hisoblang, so'ng qoldiq ko'phad koeffitsientlarini boshlang'ich hadlar bilan chiziqli kombinatsiya qilib javobni oling.\n\n**1-misol:**\nKiritma: coeffs = [1,1], initial = [0,1], n = 10, mod = 1000000007\nNatija: 55\nIzoh: coeffs=[1,1] Fibonachchi rekurrentasini bildiradi, a10=55.",
    starterCodeJs: 'function nthTermFast(coeffs, initial, n, mod) {\n  // your code here\n}',
    starterCodePy: 'def nth_term_fast(coeffs, initial, n, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nthTermFast(vector<long long>& coeffs, vector<long long>& initial, long long n, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-025',
    title: 'Grafda Yurishlar Sonini Ko\'phad Qisqartirish Bilan Sanash',
    difficulty: 'MASTER',
    points: 245,
    tags: ['Matematika'],
    description: "n ta uchli (n<=500) og'irliksiz yo'naltirilgan graf qo'shnilik matritsasi (adjacency) va juda katta qadam soni steps (10^18 gacha) berilgan. u dan v ga aniq steps ta qadamda boradigan yo'llar sonini modul mod bo'yicha toping. Qo'shnilik matritsasini to'g'ridan-to'g'ri steps-darajaga ko'tarish O(n^3 log steps) n=500 da juda sekin; Keli-Gamilton teoremasidan foydalanib matritsaning xarakteristik ko'phadini (darajasi n) toping, x^steps ni shu ko'phad bo'yicha qoldiqqa qisqartiring (ko'phad kvadratga ko'tarish va mod olish, ikkilik daraja ko'tarish), so'ng qoldiq ko'phad koeffitsientlari yordamida A^steps ni faqat A^0..A^(n-1) matritsalarining chiziqli kombinatsiyasi sifatida hisoblang.\n\n**1-misol:**\nKiritma: adjacency = [[0,1],[1,0]], u = 0, v = 1, steps = 3, mod = 1000000007\nNatija: 1\nIzoh: A^3 = A bo'lgani uchun A^3[0][1] = 1.",
    starterCodeJs: 'function countWalksMod(adjacency, u, v, steps, mod) {\n  // your code here\n}',
    starterCodePy: 'def count_walks_mod(adjacency, u, v, steps, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countWalksMod(vector<vector<int>>& adjacency, int u, int v, long long steps, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'master-b-026',
    title: 'Knuth Optimallashtirish: Optimal Qidiruv Daraxti',
    difficulty: 'MASTER',
    points: 210,
    tags: ['Rekursiya'],
    description: "n ta kalit va ularning qidirish chastotalari freq[1..n] berilgan (n<=5000). Kalitlarni ikkilik qidiruv daraxtiga shunday joylashtiringki, kutilayotgan qidiruv qiymati (har bir kalit chastotasi ko'paytirilgan uning chuqurligi yig'indisi, ildiz chuqurligi 1 deb olinadi) minimal bo'lsin - shu minimal qiymatni toping. Oddiy DP cost[i][j] = min_k(cost[i][k-1]+cost[k+1][j]) + sum(freq[i..j]) rekurrentasi O(n^3) vaqt talab qiladi va n=5000 da yo'l qo'yilmaydi; optimal bo'linish nuqtasi k ning monotonlik xossasidan (Knuth optimallashtirish: opt[i][j-1]<=opt[i][j]<=opt[i+1][j]) foydalanib, har bir cost[i][j] ni faqat opt[i][j-1] va opt[i+1][j] oralig'ida rekursiv ravishda qidirib, umumiy vaqtni O(n^2) ga tushiring.\n\n**1-misol:**\nKiritma: freq = [10,20,30]\nNatija: 100\nIzoh: Kalitlar 2 yoki 3-ni ildiz qilib qurilgan optimal daraxt umumiy qidiruv qiymati 100 ni beradi.",
    starterCodeJs: 'function optimalBST(freq) {\n  // your code here\n}',
    starterCodePy: 'def optimal_bst(freq):\n    # your code here\n    pass',
    starterCodeCpp: 'long long optimalBST(vector<long long>& freq) {\n    // your code here\n}',
  },
  {
    key: 'master-b-027',
    title: 'Knuth Optimallashtirish: Massivni k Qismga Bo\'lish',
    difficulty: 'MASTER',
    points: 195,
    tags: ['Rekursiya'],
    description: "n elementli massiv arr va k soni berilgan (n<=10^5, k<=n). Massivni k ta ketma-ket (bo'sh bo'lmagan) qismga bo'ling, har bir qismning narxi shu qism elementlari yig'indisining kvadratiga teng bo'lsin. Umumiy narx minimal bo'ladigan bo'linishning minimal umumiy narxini toping. dp[i][j] = min_{p<i}(dp[p][j-1] + cost(p+1,i)) rekurrentasi to'g'ridan-to'g'ri O(n^2*k) beradi; cost funksiyasi to'rtburchak tengsizligini qanoatlantirgani uchun har bir qatlam uchun optimal bo'linish nuqtasining monotonligidan foydalanib, rekursiv divide-and-conquer optimallashtirish (Knuth optimallashtirishning D&C ko'rinishi) orqali har bir qatlamni O(n log n) da hisoblang, jami O(n*k*log n).\n\n**1-misol:**\nKiritma: arr = [1,2,3,4], k = 2\nNatija: 52\nIzoh: [1,2,3] va [4] ga bo'lish narxi 6^2+4^2=52, bu minimal.",
    starterCodeJs: 'function minPartitionCost(arr, k) {\n  // your code here\n}',
    starterCodePy: 'def min_partition_cost(arr, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minPartitionCost(vector<long long>& arr, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-b-028',
    title: 'Knuth Optimallashtirish: Toshlarni Optimal Birlashtirish',
    difficulty: 'MASTER',
    points: 200,
    tags: ['Rekursiya'],
    description: "n ta tosh to'dasi qatorda joylashgan, har birining og'irligi piles[i] berilgan (n<=5000). Har bir amalda faqat qo'shni ikkita to'dani birlashtirish mumkin, buning narxi ikkala to'da og'irliklari yig'indisiga teng, yangi to'da shu yig'indiga teng og'irlikka ega bo'ladi. Barcha to'dalarni bitta to'daga birlashtirish uchun umumiy minimal narxni toping. dp[i][j]=min_k(dp[i][k]+dp[k+1][j])+sum(i,j) rekurrentasi O(n^3) beradi; to'rtburchak tengsizligi asosida optimal bo'linish nuqtasi k ning monotonligidan foydalanib, rekursiv Knuth optimallashtirish orqali O(n^2) ga tushiring.\n\n**1-misol:**\nKiritma: piles = [4,5,6]\nNatija: 24\nIzoh: Avval 4 va 5 ni birlashtirish (narx 9), so'ng 9 va 6 ni birlashtirish (narx 15), jami 24 - bu minimal.",
    starterCodeJs: 'function minMergeCost(piles) {\n  // your code here\n}',
    starterCodePy: 'def min_merge_cost(piles):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minMergeCost(vector<long long>& piles) {\n    // your code here\n}',
  },
  {
    key: 'master-b-029',
    title: 'Sentroid Dekompozitsiyasi: Uzunligi k Bo\'lgan Yo\'llarni Sanash',
    difficulty: 'MASTER',
    points: 220,
    tags: ['Rekursiya'],
    description: "n ta tugunli daraxt (n<=10^5, edges - qirralar ro'yxati) va butun son k berilgan. Daraxtdagi ikkita farqli tugun orasidagi yo'ldagi qirralar sonini yo'l uzunligi deb ataymiz. Aynan k ta qirradan iborat tartibsiz (u,v) juftliklar sonini toping. Har bir tugundan DFS orqali barcha juftliklarni tekshirish O(n^2) beradi; sentroid dekompozitsiyasidan rekursiv foydalaning: har bir sentroidda undan chiquvchi barcha tugunlargacha bo'lgan masofalarni hisoblab, shu sentroid orqali o'tuvchi masofa=k bo'lgan juftliklarni chastota massivi yordamida sanang (bir xil farzand pog'onasidan kelgan juftliklarni ikki marta hisoblamaslik uchun inklyuziya-eksklyuziya qo'llang), so'ng daraxtni sentroid bo'yicha kichik qismlarga bo'lib rekursiv davom eting - umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: n = 4, edges = [[1,2],[2,3],[3,4]], k = 2\nNatija: 2\nIzoh: Masofasi 2 bo'lgan juftliklar (1,3) va (2,4).",
    starterCodeJs: 'function countPathsOfLength(n, edges, k) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_of_length(n, edges, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsOfLength(int n, vector<vector<int>>& edges, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-b-030',
    title: 'Sentroid Dekompozitsiyasi: Yig\'indisi k dan Oshmaydigan Yo\'llarni Sanash',
    difficulty: 'MASTER',
    points: 225,
    tags: ['Rekursiya'],
    description: "n ta tugunli og'irlikli daraxt (n<=10^5, edges - [u,v,weight] ro'yxati, weight>=0) va chegara k berilgan. Daraxtdagi barcha (u,v) juft tugunlar orasidagi yo'ldagi qirralar og'irliklari yig'indisi k dan oshmaydigan juftliklar sonini toping. Sentroid dekompozitsiyasidan rekursiv foydalaning: har bir sentroidda undan barcha tugunlargacha bo'lgan masofalarni hisoblab tartiblang, ikki ko'rsatkich usuli bilan yig'indisi<=k bo'lgan juftliklarni sanang, bir xil farzanddan kelgan juftliklarni qayta hisoblamaslik uchun har bir farzand pog'onasi uchun mos hisoblarni ayirib tashlang (inklyuziya-eksklyuziya); daraxtni kichik qismlarga bo'lib rekursiv davom eting - umumiy murakkablik O(n log^2 n).\n\n**1-misol:**\nKiritma: n = 4, edges = [[1,2,1],[2,3,2],[3,4,1]], k = 3\nNatija: 5\nIzoh: (1,2)=1,(2,3)=2,(3,4)=1,(1,3)=3,(2,4)=3 juftliklari k=3 dan oshmaydi, (1,4)=4 esa oshadi.",
    starterCodeJs: 'function countPathsWithSumAtMost(n, edges, k) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_with_sum_at_most(n, edges, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsWithSumAtMost(int n, vector<vector<long long>>& edges, long long k) {\n    // your code here\n}',
  },
  {
    key: 'master-b-031',
    title: 'Sentroid Dekompozitsiyasi: XOR Qiymati x ga Teng Bo\'lgan Yo\'llarni Sanash',
    difficulty: 'MASTER',
    points: 230,
    tags: ['Rekursiya'],
    description: "n ta tugunli og'irlikli daraxt (n<=10^5, qirra og'irliklari 0..2^20 oralig'ida, edges - [u,v,weight] ro'yxati) va x qiymati berilgan. Daraxtdagi (u,v) juft tugunlar orasidagi yo'ldagi qirra og'irliklarining XOR yig'indisi aniq x ga teng bo'lgan juftliklar sonini toping. Sentroid dekompozitsiyasidan rekursiv foydalaning: har bir sentroidda undan barcha tugunlargacha bo'lgan XOR masofalarini hisoblab xesh-jadvalda saqlang va har bir tugun uchun XOR=x ni beruvchi juftni tez qidiring; bir xil farzand pog'onasidan kelgan juftliklarni qayta hisoblamaslik uchun inklyuziya-eksklyuziya qo'llang. Daraxtni kichik qismlarga bo'lib rekursiv davom eting, umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: n = 4, edges = [[1,2,1],[2,3,2],[3,4,4]], x = 3\nNatija: 1\nIzoh: Faqat (1,3) juftligi 1 xor 2 = 3 ni beradi.",
    starterCodeJs: 'function countPathsWithXor(n, edges, x) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_with_xor(n, edges, x):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsWithXor(int n, vector<vector<long long>>& edges, long long x) {\n    // your code here\n}',
  },
  {
    key: 'master-b-032',
    title: 'Persistent Segment Daraxti: Oraliqdagi k-Chi Kichik Element',
    difficulty: 'MASTER',
    points: 205,
    tags: ['Rekursiya'],
    description: "n elementli massiv arr (n<=10^5) va q ta so'rov (l,r,k) berilgan (q<=10^5), har biri arr[l..r] kesmasidagi k-chi kichik elementni topishni talab qiladi. Har bir so'rov uchun alohida saralash O(q*n log n) juda sekin; qiymatlar bo'yicha siqilgan (coordinate compression) segment daraxtini chapdan o'ngga rekursiv ravishda persistent tarzda quring (har elementdan keyin yangi versiya, faqat o'zgargan tugunlarni rekursiv nusxalab), so'ng har bir so'rov uchun r-versiya va (l-1)-versiya daraxtlari orasidagi chastotalar ayirmasi bo'yicha k-chi kichik elementni segment daraxtida rekursiv ikkilik qidiruv orqali O(log n) da toping.\n\n**1-misol:**\nKiritma: arr = [5,2,6,1], queries = [[1,3,2]]\nNatija: [5]\nIzoh: arr[1..3]=[5,2,6] saralanganda [2,5,6], 2-chi kichik element 5.",
    starterCodeJs: 'function kthSmallestInRange(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def kth_smallest_in_range(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> kthSmallestInRange(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-b-033',
    title: 'Persistent Segment Daraxti: Tarixiy Versiyalarda Oraliq Yig\'indi',
    difficulty: 'MASTER',
    points: 215,
    tags: ['Rekursiya'],
    description: "Boshlang'ich n elementli massiv (n<=10^5) ustida m ta amal ketma-ket bajariladi (m<=10^5): har bir amal \"update(i, val)\" (i-pozitsiyani val ga o'zgartirish, yangi versiya yaratadi) yoki \"query(version, l, r)\" (versiya raqamidagi massivning [l,r] kesmasi yig'indisini so'rash) turida bo'ladi. Har bir versiyani to'liq nusxalash O(n) bo'lib m marta bajarilganda O(n*m) beradi; har bir update amalida faqat segment daraxtining ildizdan o'zgargan barggacha bo'lgan yo'lini (O(log n) tugun) rekursiv ravishda nusxalab, qolgan tugunlarni oldingi versiya bilan bo'lishuvchi persistent segment tree tuzilmasi orqali qurib boring, natijada har bir amal O(log n) da bajariladi.\n\n**1-misol:**\nKiritma: initial = [1,2,3], operations = [[\"update\",1,10],[\"query\",1,1,2],[\"query\",0,1,3]]\nNatija: [12, 6]\nIzoh: update(1,10) dan keyingi versiya1=[10,2,3], query(1,1,2)=12; query(0,1,3) - boshlang'ich versiya yig'indisi 6.",
    starterCodeJs: 'function processVersionedOperations(initial, operations) {\n  // your code here\n}',
    starterCodePy: 'def process_versioned_operations(initial, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processVersionedOperations(vector<long long>& initial, vector<vector<long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-b-034',
    title: 'Parallel Ikkilik Qidiruv: Bog\'lanish Vaqtlarini Topish',
    difficulty: 'MASTER',
    points: 220,
    tags: ['Rekursiya'],
    description: "n ta tugun va m ta qirra berilgan, har bir qirra time[i] vaqtida faollashadi (m<=10^5). q ta so'rov berilgan, har biri (u,v) juftligidan iborat bo'lib, u va v qaysi eng erta vaqtda bir xil bog'langan komponentga tushishini so'raydi (q<=10^5). Har bir so'rov uchun alohida binar qidiruv+DSU qurish O(q*m*alpha(n)) juda sekin; barcha so'rovlar uchun parallel binar qidiruvni qo'llang: rekursiv funksiya solve(so'rovlar, chapVaqt, o'ngVaqt) - agar chapVaqt==o'ngVaqt bo'lsa javobni belgilang, aks holda o'rta vaqtgacha bo'lgan qirralarni DSU ga qo'shib, har bir so'rovni checker (u,v bir komponentdami) yordamida tekshirib ikkiga bo'ling va chap/o'ng yarmlarga rekursiv chaqiring, so'ng DSU holatini rollback qiling. Umumiy murakkablik O((n+m+q) log m).\n\n**1-misol:**\nKiritma: n = 3, edges = [[1,2,5],[2,3,10]], queries = [[1,3]]\nNatija: [10]\nIzoh: 1 va 3 faqat ikkala qirra ham faollashgandan keyin (t=10) bir komponentga tushadi.",
    starterCodeJs: 'function findConnectivityTimes(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def find_connectivity_times(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> findConnectivityTimes(int n, vector<vector<long long>>& edges, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-b-035',
    title: 'Parallel Ikkilik Qidiruv: Buyurtmalarni Bajarish Kunlarini Topish',
    difficulty: 'MASTER',
    points: 225,
    tags: ['Rekursiya'],
    description: "Omborda n xil mahsulot bor, har biri kuniga capacities[i] dona ishlab chiqariladi (kunlar 1 dan boshlanadi, jamlanib boradi). m ta buyurtma berilgan, har biri (mahsulot turi, kerakli miqdor) ko'rinishida, buyurtmalar kelish tartibida navbatga qo'yiladi va shu tartibda xizmat qilinadi (har bir mahsulot turi uchun alohida FIFO navbat, n,m<=10^5, capacity<=10^9). Har bir buyurtma to'liq bajariladigan eng erta kunni toping. Har bir buyurtma uchun alohida binar qidiruv+simulyatsiya sekin bo'lgani uchun, barcha buyurtmalar uchun parallel binar qidiruvni qo'llang: rekursiv solve(buyurtmalarQismi, kunChap, kunO'ng) funksiyasida checker (berilgan kungacha jamlangan ishlab chiqarish shu buyurtmagacha bo'lgan navbatdagi barcha talabni qoplaydimi) yordamida ikkiga bo'lib rekursiv chaqiring. Umumiy murakkablik O((n+m) log(maxDay)).\n\n**1-misol:**\nKiritma: capacities = [3], orders = [[1,5],[1,4]]\nNatija: [2, 3]\nIzoh: 2-kunga qadar jami 6 dona ishlab chiqariladi, shu bilan birinchi buyurtma (5 dona) bajariladi; 3-kunga qadar jami 9 dona, ikkinchi buyurtma (jami talab 9) bajariladi.",
    starterCodeJs: 'function findFulfillmentDays(capacities, orders) {\n  // your code here\n}',
    starterCodePy: 'def find_fulfillment_days(capacities, orders):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> findFulfillmentDays(vector<long long>& capacities, vector<vector<long long>>& orders) {\n    // your code here\n}',
  },
  {
    key: 'master-b-036',
    title: 'CDQ Bo\'lib-Boshqarish: Uch O\'lchamli Ustunlik Juftliklarini Sanash',
    difficulty: 'MASTER',
    points: 235,
    tags: ['Rekursiya'],
    description: "n ta nuqta berilgan, har biri (x,y,z) uch koordinataga ega (n<=10^5, koordinatalar 10^9 gacha, takrorlanishlar bo'lishi mumkin). Har bir nuqta uchun undan \"ustun\" bo'lgan (x'<=x, y'<=y, z'<=z va o'zidan farqli) nuqtalar sonini toping. To'g'ridan-to'g'ri har bir juftni solishtirish O(n^2); CDQ divide-and-conquer usulini qo'llang: nuqtalarni x bo'yicha saralab, rekursiv funksiya solve(l,r) o'rtadan ikkiga bo'lib, chap va o'ng yarmlarni alohida rekursiv yechadi, so'ng chap yarmning ta'sirini o'ng yarmga y bo'yicha saralab, z ustida Fenwick daraxti (BIT) yordamida qo'shadi - umumiy murakkablik O(n log^2 n).\n\n**1-misol:**\nKiritma: points = [[1,1,1],[2,2,2],[1,2,1]]\nNatija: [0, 2, 1]\nIzoh: [2,2,2] ni [1,1,1] va [1,2,1] ustun qiladi (2 ta), [1,2,1] ni faqat [1,1,1] ustun qiladi (1 ta).",
    starterCodeJs: 'function countDominanceCounts(points) {\n  // your code here\n}',
    starterCodePy: 'def count_dominance_counts(points):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> countDominanceCounts(vector<vector<long long>>& points) {\n    // your code here\n}',
  },
  {
    key: 'master-b-037',
    title: 'CDQ Bo\'lib-Boshqarish: Uch Kalitli Inversiyalarni Sanash',
    difficulty: 'MASTER',
    points: 225,
    tags: ['Rekursiya'],
    description: "n ta element berilgan, har biri uchta massivdagi qiymatlarga ega: a[i], b[i], c[i] (n<=10^5). Nechta (i,j) juftlik (i<j) mavjudki, a[i]<=a[j], b[i]<=b[j], c[i]<=c[j] shartlarining barchasi bajarilsin. n^2 tekshirish sekin bo'lgani uchun, elementlarni a bo'yicha saralab (teng a lar maxsus tartibda), CDQ divide-and-conquer qo'llang: rekursiv solve(l,r) chap/o'ng yarmga bo'linadi, chap yarmning b qiymatlari bo'yicha saralangan ta'siri o'ng yarmga c koordinatasi ustida Fenwick daraxti orqali yig'iladi, umumiy murakkablik O(n log^2 n).\n\n**1-misol:**\nKiritma: a = [1,2,3], b = [1,2,3], c = [1,2,3]\nNatija: 3\nIzoh: (1,2),(1,3),(2,3) juftliklari barcha uchta shartni qanoatlantiradi.",
    starterCodeJs: 'function countInversionsTriple(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def count_inversions_triple(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countInversionsTriple(vector<int>& a, vector<int>& b, vector<int>& c) {\n    // your code here\n}',
  },
  {
    key: 'master-b-038',
    title: 'CDQ Bo\'lib-Boshqarish: Onlayn Kiritish va Ustunlik So\'rovlari',
    difficulty: 'MASTER',
    points: 230,
    tags: ['Rekursiya'],
    description: "m ta amal ketma-ket beriladi (m<=10^5), har biri \"insert(x,y)\" (yangi nuqta qo'shish) yoki \"query(x,y)\" (hozirgacha kiritilgan nuqtalar orasida x'<=x va y'<=y shartini qanoatlantiruvchi nuqtalar sonini so'rash) turida. Amallar tartibi tabiiy ravishda uchinchi o'lchov vazifasini bajaradi, shuning uchun masala 3 o'lchamli qisman tartib masalasiga aylanadi. Har bir so'rovni to'g'ridan-to'g'ri barcha oldingi insertlar bilan solishtirish O(m^2) sekin; CDQ divide-and-conquer qo'llang: amallarni vaqt bo'yicha ikkiga bo'lib, rekursiv solve(l,r) chaqiruvida chap yarmdagi insertlarning o'ng yarmdagi querylarga ta'sirini x bo'yicha saralab, y ustida Fenwick daraxti orqali hisoblang - umumiy murakkablik O(m log^2 m).\n\n**1-misol:**\nKiritma: operations = [[\"insert\",1,1],[\"query\",2,2],[\"insert\",3,0],[\"query\",2,2]]\nNatija: [1, 1]\nIzoh: Birinchi query paytida faqat (1,1) kiritilgan va u shartga mos, ikkinchi query paytida (3,0) ham kiritilgan lekin x=3>2 bo'lgani uchun mos emas.",
    starterCodeJs: 'function processInsertDominanceQueries(operations) {\n  // your code here\n}',
    starterCodePy: 'def process_insert_dominance_queries(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processInsertDominanceQueries(vector<vector<long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-b-039',
    title: 'Kichikni Kattaga Qo\'shish: Qism Daraxtidagi Farqli Ranglar Soni',
    difficulty: 'MASTER',
    points: 190,
    tags: ['Rekursiya'],
    description: "n tugunli ildizli daraxt (n<=10^5, edges - qirralar ro'yxati), har bir tugunning rangi colors[i] berilgan. Har bir tugun uchun uning qism daraxtidagi (o'zi va barcha avlodlari) farqli ranglar sonini toping. Har bir tugun uchun alohida DFS orqali hisoblash O(n^2) sekin; \"kichikni kattaga qo'shish\" (small-to-large merging / DSU on tree) texnikasidan rekursiv foydalaning: har bir tugun uchun DFS orqali avval eng katta farzandning rang-chastota xesh to'plamini saqlab qoling (uni yo'q qilmang), qolgan kichik farzandlarning to'plamlarini shu katta to'plamga bittalab rekursiv qo'shib chiqing - umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: n = 4, edges = [[1,2],[1,3],[3,4]], colors = [1,2,2,3]\nNatija: [3, 1, 2, 1]\nIzoh: 1-tugun qism daraxti barcha 4 ta tugunni o'z ichiga oladi, ranglar {1,2,2,3} - farqlilari 3 ta; 3-tugun qism daraxti {2,3} - 2 ta farqli.",
    starterCodeJs: 'function distinctColorsInSubtree(n, edges, colors) {\n  // your code here\n}',
    starterCodePy: 'def distinct_colors_in_subtree(n, edges, colors):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> distinctColorsInSubtree(int n, vector<vector<int>>& edges, vector<int>& colors) {\n    // your code here\n}',
  },
  {
    key: 'master-b-040',
    title: 'Kichikni Kattaga Qo\'shish: Qism Daraxtidagi Dominant Rang',
    difficulty: 'MASTER',
    points: 195,
    tags: ['Rekursiya'],
    description: "n tugunli ildizli daraxt (n<=10^5), har bir tugun rangi colors[i] berilgan. Har bir tugun uchun uning qism daraxtida eng ko'p uchraydigan rangni (agar bir nechta rang bir xil maksimal chastotaga ega bo'lsa, ular orasidagi eng kichik rang qiymatini) toping. DSU on tree (kichikni kattaga qo'shish) texnikasi bilan rekursiv DFS orqali har bir tugun uchun rang->chastota xesh jadvalini va joriy maksimal chastota/minimal dominant rangni saqlab, farzandlarning kichik to'plamlarini katta to'plamga rekursiv birlashtirib chiqing (har birlashtirishda maksimalni yangilang), umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: n = 3, edges = [[1,2],[1,3]], colors = [5,5,7]\nNatija: [5, 5, 7]\nIzoh: 1-tugun qism daraxtida rang5 ikki marta, rang7 bir marta uchraydi, dominant rang 5.",
    starterCodeJs: 'function dominantColorInSubtree(n, edges, colors) {\n  // your code here\n}',
    starterCodePy: 'def dominant_color_in_subtree(n, edges, colors):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> dominantColorInSubtree(int n, vector<vector<int>>& edges, vector<int>& colors) {\n    // your code here\n}',
  },
  {
    key: 'master-b-041',
    title: 'Suffiks Avtomati: Farqli Qism Satrlar Sonini Sanash',
    difficulty: 'MASTER',
    points: 210,
    tags: ['Rekursiya'],
    description: "s satri berilgan (uzunligi n<=10^5, faqat kichik lotin harflari). s ning barcha farqli (bo'sh bo'lmagan) qism satrlari sonini toping. Barcha qism satrlarni to'plamga solish O(n^2) xotira/vaqt talab qiladi va n=10^5 da yo'l qo'yilmaydi; suffiks avtomatini har bir belgini ketma-ket qo'shib rekursiv kengaytirish (extend) orqali O(n) vaqtda quring - har bir holat uchun link (bog'lovchi) orqali eng uzun va eng qisqa qamrab olingan qism satr uzunliklari farqini yig'ib, javobni oling: javob = summa(len[holat] - len[link[holat]]) barcha holatlar bo'yicha.\n\n**1-misol:**\nKiritma: s = \"aab\"\nNatija: 5\nIzoh: Farqli qism satrlar: a, aa, aab, ab, b - jami 5 ta.",
    starterCodeJs: 'function countDistinctSubstrings(s) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_substrings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDistinctSubstrings(string s) {\n    // your code here\n}',
  },
  {
    key: 'master-b-042',
    title: 'Suffiks Avtomati: Ikki Satrning Eng Uzun Umumiy Qism Satri',
    difficulty: 'MASTER',
    points: 220,
    tags: ['Rekursiya'],
    description: "Ikki satr a va b berilgan (har birining uzunligi 10^5 gacha). Ularning eng uzun umumiy qism satrini toping (bir nechta yechim bo'lsa, istalganini qaytaring). Dinamik dasturlash orqali yechish O(n*m) xotira/vaqt talab qiladi va katta satrlar uchun yo'l qo'yilmaydi; a satri uchun suffiks avtomatini quring (har bir belgini ketma-ket qo'shib rekursiv kengaytirish orqali O(n)), so'ng b satrini avtomat bo'ylab yurgizib, har bir pozitsiyada joriy mos kelayotgan uzunlikni kuzatib boring - agar joriy holatdan o'tish mavjud bo'lmasa, link (bog'lovchi) zanjiri bo'ylab rekursiv qisqaroq holatga o'ting, maksimal uzunlikni yangilab boring - umumiy murakkablik O(n+m).\n\n**1-misol:**\nKiritma: a = \"abcbabc\", b = \"babca\"\nNatija: \"babc\"\nIzoh: \"babc\" ikkala satrda ham uchraydigan eng uzun umumiy qism satr (uzunligi 4).",
    starterCodeJs: 'function longestCommonSubstring(a, b) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonSubstring(string a, string b) {\n    // your code here\n}',
  },
  {
    key: 'master-b-043',
    title: 'Bo\'lib-Boshqarish: Qavariq Qobiqni Birlashtirish Orqali Qurish',
    difficulty: 'MASTER',
    points: 200,
    tags: ['Rekursiya'],
    description: "Tekislikdagi n ta nuqta berilgan (n<=10^5, koordinatalar 10^9 gacha, kollinear holatlar ham to'g'ri ishlanishi kerak). Ularning qavariq qobig'ini (convex hull) soat strelkasiga teskari yo'nalishda tartiblangan uchlar ro'yxati sifatida toping. Bu masala uchun rekursiv bo'lib-boshqarish (divide and conquer) usulini qo'llang: nuqtalarni x bo'yicha saralab, o'rtadan ikkiga bo'ling, har bir yarmning qavariq qobig'ini rekursiv toping, so'ng ikkita qobiqni yuqori va pastki \"ko'prik\" (tangent) chiziqlarini topib birlashtiring - umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: points = [[0,0],[1,1],[2,2],[0,2],[2,0]]\nNatija: [[0,0],[2,0],[2,2],[0,2]]\nIzoh: [1,1] nuqtasi qobiq ichida qoladi, qolgan 4 ta nuqta qavariq qobiqni tashkil qiladi.",
    starterCodeJs: 'function convexHull(points) {\n  // your code here\n}',
    starterCodePy: 'def convex_hull(points):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<long long>> convexHull(vector<vector<long long>>& points) {\n    // your code here\n}',
  },
  {
    key: 'master-b-044',
    title: 'Bo\'lib-Boshqarish: Eng Yaqin Nuqtalar Juftligi',
    difficulty: 'MASTER',
    points: 190,
    tags: ['Rekursiya'],
    description: "Tekislikdagi n ta nuqta berilgan (n<=10^5). Ularning orasidagi eng kichik Evklid masofasini toping. Barcha juftliklarni solishtirish O(n^2) sekin (n=10^5 da yo'l qo'yilmaydi); klassik rekursiv bo'lib-boshqarish algoritmini qo'llang: nuqtalarni x bo'yicha saralab, o'rtadan ikkiga bo'ling, har bir yarmda eng yaqin juftlikni rekursiv toping, so'ng o'rta chiziqqa yaqin (masofasi joriy minimal d dan kichik) nuqtalarni y bo'yicha saralab, har biri uchun faqat keyingi 7 ta nuqta bilan solishtirib, chegara oralig'idagi eng yaqin juftlikni tekshiring - umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: points = [[0,0],[3,4],[1,1]]\nNatija: 1.4142135624\nIzoh: (0,0) va (1,1) orasidagi masofa sqrt(2) - bu eng kichik masofa.",
    starterCodeJs: 'function closestPairDistance(points) {\n  // your code here\n}',
    starterCodePy: 'def closest_pair_distance(points):\n    # your code here\n    pass',
    starterCodeCpp: 'double closestPairDistance(vector<vector<long long>>& points) {\n    // your code here\n}',
  },
  {
    key: 'master-b-045',
    title: 'Bo\'lib-Boshqarish: Nuqtalar To\'plamining Diametri',
    difficulty: 'MASTER',
    points: 210,
    tags: ['Rekursiya'],
    description: "Tekislikdagi n ta nuqta berilgan (n<=10^5). Ular orasidagi eng katta Evklid masofasini (to'plam diametrini) toping. Barcha juftliklarni solishtirish O(n^2) sekin; avval qavariq qobiqni rekursiv bo'lib-boshqarish (divide and conquer merge) orqali O(n log n) da quring (diametrni beruvchi juftlik har doim qavariq qobiq uchlarida joylashadi, chunki qobiq ichidagi nuqtalar diametrga ta'sir qilmaydi), so'ng qobiq uchlari ustida \"aylanuvchi ko'rsatkichlar\" (rotating calipers) usulini qo'llab, maksimal masofani O(h) da toping (h - qobiq uchlari soni), umumiy murakkablik O(n log n).\n\n**1-misol:**\nKiritma: points = [[0,0],[4,0],[2,3]]\nNatija: 4\nIzoh: (0,0) va (4,0) orasidagi masofa 4, bu eng katta masofa (boshqa juftliklar masofasi sqrt(13)≈3.6).",
    starterCodeJs: 'function diameterOfPointSet(points) {\n  // your code here\n}',
    starterCodePy: 'def diameter_of_point_set(points):\n    # your code here\n    pass',
    starterCodeCpp: 'double diameterOfPointSet(vector<vector<long long>>& points) {\n    // your code here\n}',
  },
  {
    key: 'master-b-046',
    title: 'Link-Cut Daraxt: Dinamik Bog\'lanish va Yo\'ldagi Maksimal Og\'irlik',
    difficulty: 'MASTER',
    points: 245,
    tags: ['Rekursiya'],
    description: "n ta tugun (dastlab hech qanday qirrasiz, alohida-alohida) ustida q ta amal ketma-ket beriladi (n,q<=10^5): \"link(u,v,w)\" (u va v orasida og'irligi w bo'lgan qirra qo'shish, agar ular allaqachon bir komponentda bo'lsa amal bekor qilinadi), \"cut(u,v)\" (u-v qirrasini o'chirish, agar mavjud bo'lsa), \"query(u,v)\" (agar u va v bir xil daraxtda bo'lsa ular orasidagi yo'ldagi eng katta qirra og'irligini qaytarish, aks holda -1). Har bir so'rov uchun DFS/BFS qilish O(n) bo'lib, q marta bajarilganda O(n*q) sekin; link-cut daraxt (splay daraxtlar asosidagi rekursiv access/splay operatsiyalari bilan) tuzilmasidan foydalaning - access(v) funksiyasi ildizdan v gacha bo'lgan afzal yo'lni rekursiv splay operatsiyalari bilan bitta afzal yo'lga aylantiradi, bu orqali link, cut va path-query amallarini amortizatsion O(log n) da bajaring.\n\n**1-misol:**\nKiritma: n = 3, operations = [[\"link\",1,2,5],[\"link\",2,3,3],[\"query\",1,3],[\"cut\",2,3],[\"query\",1,3]]\nNatija: [5, -1]\nIzoh: Birinchi query paytida yo'l 1-2-3 bo'ylab maksimal og'irlik 5; cut(2,3) dan keyin 1 va 3 bog'lanmagan.",
    starterCodeJs: 'function processLinkCutOperations(n, operations) {\n  // your code here\n}',
    starterCodePy: 'def process_link_cut_operations(n, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processLinkCutOperations(int n, vector<vector<long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-b-047',
    title: 'Link-Cut Daraxt: Dinamik Daraxtda Yo\'l Yig\'indisi',
    difficulty: 'MASTER',
    points: 250,
    tags: ['Rekursiya'],
    description: "n ta tugun (har birining boshlang'ich qiymati initialValues[i]) ustida q ta amal beriladi (n,q<=10^5): \"link(u,v)\" (u va v ni bog'lash, agar ular bir komponentda bo'lmasa), \"cut(u,v)\" (mavjud qirrani o'chirish), \"update(u,x)\" (u tugunining qiymatini x ga o'zgartirish), \"query(u,v)\" (u va v bir komponentda bo'lsa ular orasidagi yo'ldagi barcha tugun qiymatlari yig'indisini qaytarish, aks holda -1). Daraxt tuzilishi dinamik ravishda o'zgargani uchun statik HLD ishlatib bo'lmaydi; link-cut daraxt (splay daraxtlar asosida, har bir splay tugunida qism yig'indi saqlanadi) tuzilmasidan foydalaning - access va splay operatsiyalarini rekursiv ravishda amalga oshirib, har bir amalni amortizatsion O(log n) da bajaring.\n\n**1-misol:**\nKiritma: n = 3, initialValues = [1,2,3], operations = [[\"link\",1,2],[\"link\",2,3],[\"query\",1,3],[\"update\",2,10],[\"query\",1,3]]\nNatija: [6, 14]\nIzoh: Boshida yig'indi 1+2+3=6, update(2,10) dan keyin 1+10+3=14.",
    starterCodeJs: 'function processDynamicTreeQueries(n, initialValues, operations) {\n  // your code here\n}',
    starterCodePy: 'def process_dynamic_tree_queries(n, initial_values, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processDynamicTreeQueries(int n, vector<long long>& initialValues, vector<vector<long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-b-048',
    title: 'Og\'ir-Yengil Dekompozitsiya: Rekursiv Eng Yaqin Umumiy Ajdod',
    difficulty: 'MASTER',
    points: 180,
    tags: ['Rekursiya'],
    description: "n tugunli ildizli daraxt (n<=10^5) va q ta so'rov (u,v) juftliklari (q<=10^5) berilgan. Har bir so'rov uchun u va v ning eng yaqin umumiy ajdodini (LCA) toping. Har bir so'rov uchun ildizgacha yo'lni yig'ish O(n) bo'lib q marta bajarilganda sekin; og'ir-yengil dekompozitsiya (heavy-light decomposition) qo'llang: rekursiv DFS orqali har bir tugunning og'ir farzandini (eng katta qism daraxtga ega farzand) aniqlang va har bir tugunga u yotgan zanjirning boshini (head) rekursiv DFS orqali tayinlang, so'ng LCA so'rovini: ikkala tugun boshqa zanjirlarda bo'lguncha, chuqurroq zanjirning boshiga sakrab yuqoriga ko'tarilib boring, bir xil zanjirga tushganda chuqurligi kichik tugun javob bo'ladi - har bir so'rov O(log n) da javob topadi.\n\n**1-misol:**\nKiritma: n = 5, edges = [[1,2],[1,3],[2,4],[2,5]], root = 1, queries = [[4,5],[4,3]]\nNatija: [2, 1]\nIzoh: 4 va 5 ning eng yaqin umumiy ajdodi 2; 4 va 3 ning eng yaqin umumiy ajdodi 1.",
    starterCodeJs: 'function findLCAs(n, edges, root, queries) {\n  // your code here\n}',
    starterCodePy: 'def find_lcas(n, edges, root, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findLCAs(int n, vector<vector<int>>& edges, int root, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-b-049',
    title: 'Og\'ir-Yengil Dekompozitsiya: Yo\'ldagi Maksimal Qiymat So\'rovi',
    difficulty: 'MASTER',
    points: 195,
    tags: ['Rekursiya'],
    description: "n tugunli og'irlikli daraxt (n<=10^5, edges - [u,v,weight] ro'yxati) va q ta so'rov (u,v) berilgan. Har bir so'rov uchun u va v orasidagi yo'ldagi qirralarning maksimal og'irligini toping. Har bir so'rov uchun yo'lni to'g'ridan-to'g'ri yig'ish O(n) sekin; og'ir-yengil dekompozitsiyadan foydalaning: daraxtni rekursiv DFS orqali zanjirlarga bo'lib, har bir tugunga Euler tartibi (in-time) bering, qirra og'irliklarini pastdagi tugun qiymati sifatida segment daraxtiga joylang; har bir so'rovda ikkala tugun bir xil zanjirga tushguncha, chuqurroq zanjirning boshidan joriy tugungacha bo'lgan kesmani segment daraxtidan rekursiv max-query orqali so'rab, natijalarni yig'ib boring - yakunda bir xil zanjirdagi qoldiq kesmani ham so'rab, umumiy murakkablik O(log^2 n) har bir so'rov uchun.\n\n**1-misol:**\nKiritma: n = 4, edges = [[1,2,5],[2,3,3],[2,4,7]], queries = [[3,4]]\nNatija: [7]\nIzoh: 3 va 4 orasidagi yo'l 3-2-4 bo'lib, og'irliklar max(3,7)=7.",
    starterCodeJs: 'function pathMaxQueries(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def path_max_queries(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> pathMaxQueries(int n, vector<vector<long long>>& edges, vector<pair<int,int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-b-050',
    title: 'Og\'ir-Yengil Dekompozitsiya: Masofa va k-Ajdod So\'rovlari',
    difficulty: 'MASTER',
    points: 210,
    tags: ['Rekursiya'],
    description: "n tugunli ildizli daraxt (n<=10^5) va q ta so'rov beriladi (q<=10^5), har bir so'rov ikki turdan biri: \"distance(u,v)\" (u va v orasidagi qirralar sonini so'rash) yoki \"kthAncestor(u,k)\" (u tugunining k-avlod yuqoridagi ajdodini so'rash, agar mavjud bo'lmasa -1). Har birini naive tarzda yechish (LCA uchun ildizgacha yurish, k-ajdod uchun k marta yuqoriga ko'tarilish) O(n) har bir so'rov uchun, umumiy O(n*q) sekin; og'ir-yengil dekompozitsiyadan (rekursiv DFS bilan zanjirlarga bo'lish) foydalanib LCA ni O(log n) da toping (distance(u,v)=depth[u]+depth[v]-2*depth[LCA(u,v)]), k-ajdod so'rovi uchun esa har bir tugunning zanjir boshigacha bo'lgan chuqurligidan foydalanib, zanjirdan zanjirga sakrab (har sakrashda k dan zanjirdagi masofani ayirib) O(log n) da javob toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[1,2],[2,3],[2,4]], root = 1, queries = [[\"distance\",3,4],[\"kthAncestor\",3,2]]\nNatija: [2, 1]\nIzoh: 3 va 4 orasidagi masofa 2 (3-2-4 orqali); 3-tugunning 2-ajdodi (3->2->1) - 1.",
    starterCodeJs: 'function processTreeQueries(n, edges, root, queries) {\n  // your code here\n}',
    starterCodePy: 'def process_tree_queries(n, edges, root, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> processTreeQueries(int n, vector<vector<int>>& edges, int root, vector<vector<long long>>& queries) {\n    // your code here\n}',
  },
];
