export const problems = [
  {
    key: 'master-a-001',
    title: "Vaqt Sayohatchisi Massiv",
    difficulty: 'MASTER',
    points: 180,
    tags: ['Massivlar'],
    description: "n ta elementdan iborat massivning 0-versiyasi berilgan. Sizga m ta so'rov beriladi: '1 v i x' turi — v-versiyadagi massivni i-indeksda x qiymatga o'zgartirib, yangi versiya (versiyalar soni + 1) yaratadi; '2 v i' turi — v-versiyadagi massivning i-indeksidagi qiymatni qaytaradi. Versiyalar daraxt shaklida shoxlanishi mumkin (bir versiyadan bir nechta yangi versiya yaratilishi mumkin), va barcha eski versiyalar butun so'rovlar davomida saqlanishi shart. n, m ≤ 2·10^5 bo'lgani uchun har bir operatsiya persistent (funksional) segment daraxt yoki path copying texnikasi yordamida O(log n) vaqt va xotirada bajarilishi kerak — massivni har safar to'liq nusxalash O(n) xotira talab qiladi va TLE/MLE beradi.\n\n**1-misol:**\nKiritma: n=5, boshlang'ich=[1,2,3,4,5], so'rovlar=['1 0 2 99','2 1 2','2 0 2']\nNatija: [99,3]\nIzoh: 1-versiya 0-versiyadan 2-indeksni 99ga o'zgartirib yaratiladi, keyin 1-versiyadagi 2-indeks (99) va 0-versiyadagi 2-indeks (3) so'raladi.\n\n**2-misol:**\nKiritma: n=3, boshlang'ich=[7,8,9], so'rovlar=['2 0 1','1 0 1 50','1 1 0 20','2 2 0']\nNatija: [8,20]",
    starterCodeJs: 'function persistentArrayQuery(n, initial, queries) {\n  // your code here\n}',
    starterCodePy: 'def persistent_array_query(n, initial, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> persistentArrayQuery(int n, vector<int>& initial, vector<vector<string>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-002',
    title: "Tarixiy Kesim Yig'indisi",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Massivlar'],
    description: "n elementli massiv berilgan. m ta so'rov bor: '1 i x' — joriy versiyaga yangi versiya sifatida i-indeksni x ga o'zgartirish; '2 v l r' — v-versiyadagi massivning [l, r] kesimidagi elementlar yig'indisini qaytarish. Versiyalar ketma-ket raqamlanadi (har bir yangilanish yangi versiya yaratadi), va so'rovlar istalgan o'tgan versiyaga murojaat qilishi mumkin. n, m ≤ 2·10^5, elementlar |a_i| ≤ 10^9. Yechim persistent segment daraxt (path copying) asosida O((n+m) log n) vaqt va O(n + m log n) xotira ichida ishlashi kerak.\n\n**1-misol:**\nKiritma: n=4, boshlang'ich=[1,2,3,4], so'rovlar=['2 0 0 3','1 1 10','2 1 0 1','2 0 0 3']\nNatija: [10,11,10]\nIzoh: 0-versiyada [0,3] yig'indisi 10; 1-indeks 10ga o'zgartirilib 1-versiya yaratiladi ([1,10,3,4]); 1-versiyada [0,1] yig'indisi 11; 0-versiya o'zgarmagan.\n\n**2-misol:**\nKiritma: n=3, boshlang'ich=[5,5,5], so'rovlar=['1 0 100','2 1 0 2']\nNatija: [110]",
    starterCodeJs: 'function historicalRangeSum(n, initial, queries) {\n  // your code here\n}',
    starterCodePy: 'def historical_range_sum(n, initial, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> historicalRangeSum(int n, vector<long long>& initial, vector<vector<string>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-003',
    title: "Amallarni Bekor Qilish Daraxti",
    difficulty: 'MASTER',
    points: 185,
    tags: ['Massivlar'],
    description: "Bo'sh massiv ustida ketma-ket amallar bajariladi: 'APPEND x' (massiv oxiriga x qo'shib yangi versiya yaratish), 'UNDO k' (k-chi versiyaga qaytish va shu versiyadan davom etish — natijada yangi shoxcha hosil bo'ladi), 'QUERY v i' (v-versiyadagi massivning i-indeksidagi qiymatni qaytarish). Versiyalar aniq daraxt hosil qiladi, chunki UNDO istalgan oldingi versiyaga qaytishi va undan keyin yangi shoxlanish boshlashi mumkin. Amallar soni n ≤ 3·10^5. Har bir amal O(log n) vaqtda persistent dinamik massiv (persistent vector yoki persistent segment daraxt) yordamida bajarilishi kerak.\n\n**1-misol:**\nKiritma: operations=['APPEND 5','APPEND 6','UNDO 0','APPEND 9','QUERY 1 0','QUERY 3 0']\nNatija: [5,9]\nIzoh: 1-versiya [5]; 2-versiya [5,6]; UNDO 0 ga qaytib 3-versiya 1-versiyadan APPEND 9 bilan [5,9] bo'ladi.\n\n**2-misol:**\nKiritma: operations=['APPEND 1','APPEND 2','QUERY 2 1']\nNatija: [2]",
    starterCodeJs: 'function undoRedoArray(operations) {\n  // your code here\n}',
    starterCodePy: 'def undo_redo_array(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> undoRedoArray(vector<string>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-004',
    title: "Uch O'lchamli Ustunlik Sanog'i",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Massivlar'],
    description: "n ta nuqta (x_i, y_i, z_i) berilgan. Har bir i nuqta uchun, shu nuqtadan 'ustun' bo'lgan nuqtalar sonini toping — j nuqtasi i dan ustun deyiladi, agar x_j ≤ x_i, y_j ≤ y_i, z_j ≤ z_i va j ≠ i. n ≤ 10^5, koordinatalar ≤ n bo'lgan musbat butun sonlar (teng qiymatlar bo'lishi mumkin). To'g'ridan-to'g'ri barcha juftliklarni tekshirish O(n^2) beradi va yaramaydi; x bo'yicha saralab, (y,z) juftligi ustida CDQ divide and conquer + Fenwick daraxt yordamida O(n log^2 n) vaqtda yechish kerak.\n\n**1-misol:**\nKiritma: points=[[1,1,1],[2,2,2],[3,3,3]]\nNatija: [0,1,2]\nIzoh: (1,1,1) hech kimdan ustun emas; (2,2,2) faqat (1,1,1) dan ustun; (3,3,3) ikkalasidan ham ustun.\n\n**2-misol:**\nKiritma: points=[[1,2,3],[2,1,3],[3,3,1]]\nNatija: [0,0,0]",
    starterCodeJs: 'function dominanceCount(points) {\n  // your code here\n}',
    starterCodePy: 'def dominance_count(points):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> dominanceCount(vector<vector<int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'master-a-005',
    title: "CDQ bilan Vaznli O'suvchi Ketma-ketlik",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Massivlar'],
    description: "n ta element berilgan, har biri (pos, val, weight) uchligidan iborat, bunda pos — element vaqt tartibidagi o'rni (1..n, hammasi har xil), val — qiymat, weight — musbat vazn. pos bo'yicha o'suvchi va val bo'yicha qat'iy o'suvchi bo'lgan qism ketma-ketlik tanlang, unda tanlangan elementlarning weight yig'indisi maksimal bo'lsin. n ≤ 2·10^5, val va weight ≤ 10^9. Bu ikki o'lchamli DP masalasi bo'lib, CDQ divide and conquer (vaqt bo'yicha bo'lish + val bo'yicha Fenwick daraxtida maksimal prefiks so'rovi) yordamida O(n log^2 n) da yechilishi kerak.\n\n**1-misol:**\nKiritma: items=[[1,3,10],[2,1,5],[3,5,7],[4,4,20]]\nNatija: 30\nIzoh: (1,3,10) va (4,4,20) tanlansa pos: 1<4, val: 3<4, yig'indi 30.\n\n**2-misol:**\nKiritma: items=[[1,1,5],[2,2,5],[3,3,5]]\nNatija: 15",
    starterCodeJs: 'function maxWeightIncreasingSubsequence(items) {\n  // your code here\n}',
    starterCodePy: 'def max_weight_increasing_subsequence(items):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxWeightIncreasingSubsequence(vector<vector<long long>>& items) {\n    // your code here\n}',
  },
  {
    key: 'master-a-006',
    title: "Dinamik Inversiyalar Sanog'i",
    difficulty: 'MASTER',
    points: 190,
    tags: ['Massivlar'],
    description: "Bo'sh massivga ketma-ket n ta amal bajariladi: 'INSERT p v' — pozitsiya p ga v qiymatini qo'yish; 'COUNT' — hozirgacha qo'yilgan barcha elementlar orasida (pozitsiyalar tartibi bo'yicha) chapdan o'ngga qiymat kamayadigan barcha juftliklar (inversiyalar) sonini so'rash. Bu klassik uch o'lchamli qisman tartib masalasi: (qo'shilish vaqti, pozitsiya, qiymat) uchligi ustida CDQ divide and conquer qo'llaniladi. n ≤ 2·10^5. Umumiy vaqt murakkabligi O(n log^2 n) bo'lishi talab qilinadi.\n\n**1-misol:**\nKiritma: operations=['INSERT 1 5','INSERT 2 3','COUNT','INSERT 3 10','COUNT']\nNatija: [1,1]\nIzoh: birinchi COUNT paytida faqat (5,3) juftligi inversiya; uchinchi element 10 hech qanday yangi inversiya qo'shmaydi.\n\n**2-misol:**\nKiritma: operations=['INSERT 1 1','INSERT 2 2','COUNT']\nNatija: [0]",
    starterCodeJs: 'function dynamicInversionsCount(operations) {\n  // your code here\n}',
    starterCodePy: 'def dynamic_inversions_count(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> dynamicInversionsCount(vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-007',
    title: "Dinamik To'rtburchak So'rovlari uchun k-d Daraxt",
    difficulty: 'MASTER',
    points: 175,
    tags: ['Massivlar'],
    description: "2D tekislikda nuqtalar to'plami bor, boshida bo'sh. m ta so'rov beriladi: 'ADD x y' — nuqta qo'shish; 'COUNT x1 y1 x2 y2' — [x1,x2]×[y1,y2] to'rtburchak ichidagi (chegaralar bilan) nuqtalar sonini qaytarish. m ≤ 2·10^5, koordinatalar mutlaq qiymati ≤ 10^9. Statik k-d daraxt qurib, davriy (amortizatsiyalangan, masalan har √m qo'shishdan keyin) qayta qurish strategiyasi bilan umumiy O(m√m) yoki yaqinroq chegarada ishlaydigan yechim talab qilinadi — har bir COUNT uchun barcha nuqtalarni sanash O(m^2) beradi.\n\n**1-misol:**\nKiritma: operations=['ADD 1 1','ADD 5 5','COUNT 0 0 3 3','ADD 2 2','COUNT 0 0 3 3']\nNatija: [1,2]\n\n**2-misol:**\nKiritma: operations=['ADD 0 0','COUNT -1 -1 1 1']\nNatija: [1]",
    starterCodeJs: 'function kdTreeRectangleQueries(operations) {\n  // your code here\n}',
    starterCodePy: 'def kd_tree_rectangle_queries(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> kdTreeRectangleQueries(vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-008',
    title: "Eng Yaqin k ta Qo'shni",
    difficulty: 'MASTER',
    points: 205,
    tags: ['Massivlar'],
    description: "Tekislikda n ta statik nuqta berilgan. q ta so'rov beriladi, har birida nuqta (x,y) va butun son k berilib, shu nuqtaga Evklid masofasi bo'yicha eng yaqin k ta nuqtani (ularning indekslari, masofa o'sish tartibida, teng masofada indeks o'sish tartibida) topish kerak. n, q ≤ 10^5, k ≤ 20. k-d daraxt qurib, har bir so'rov uchun ustuvor navbat (priority queue) bilan branch-and-bound qidiruvi yordamida umumiy O((n+q)√n) yoki yaqinroq murakkablikda yechish kerak — har so'rovda barcha nuqtalarni tekshirish O(nq) juda sekin.\n\n**1-misol:**\nKiritma: points=[[0,0],[1,1],[5,5],[2,2]], queries=[[0,0,2]]\nNatija: [[0,1]]\nIzoh: (0,0) nuqtaga eng yaqin 2 ta: o'zi (indeks 0) va (1,1) (indeks 1).\n\n**2-misol:**\nKiritma: points=[[0,0],[10,10]], queries=[[0,0,1]]\nNatija: [[0]]",
    starterCodeJs: 'function kNearestNeighbors(points, queries) {\n  // your code here\n}',
    starterCodePy: 'def k_nearest_neighbors(points, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> kNearestNeighbors(vector<vector<int>>& points, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-009',
    title: "Li Chao Daraxti bilan Dinamik Dasturlash Optimallashtirish",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Massivlar'],
    description: "dp[i] = min over j<i of (dp[j] + b[j]*a[i] + c[j]) ko'rinishidagi rekurrensiya berilgan, bunda a[i] o'suvchi bo'lishi shart emas va b[j] musbat yoki manfiy bo'lishi mumkin (klassik monoton CHT qo'llab bo'lmaydi). n ≤ 2·10^5, barcha qiymatlar mutlaq qiymatda ≤ 10^9. Har bir j uchun to'g'ri chiziq y = b[j]*x + (dp[j]+c[j]) sifatida Li Chao daraxtiga qo'shilib, har bir i uchun x=a[i] nuqtada minimal qiymat so'ralishi orqali O(n log MAXX) vaqtda dp massivini to'liq hisoblang.\n\n**1-misol:**\nKiritma: a=[0,2,5], b=[0,-1,-1], c=[0,0,0]\nNatija: [0,-2,-5]\nIzoh: dp[0]=0; dp[1]=min(dp[0]+b[0]*a[1]+c[0])=0; keyin j=0 chizig'i qo'shiladi va h.k. (aniq rekurrensiya masala matnida to'liq belgilanadi).\n\n**2-misol:**\nKiritma: a=[1,1,1], b=[0,5,-5], c=[0,0,0]\nNatija: [0,5,-5]",
    starterCodeJs: 'function liChaoDpOptimization(a, b, c) {\n  // your code here\n}',
    starterCodePy: 'def li_chao_dp_optimization(a, b, c):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> liChaoDpOptimization(vector<long long>& a, vector<long long>& b, vector<long long>& c) {\n    // your code here\n}',
  },
  {
    key: 'master-a-010',
    title: "Kesma Chiziqlar uchun Li Chao Daraxti",
    difficulty: 'MASTER',
    points: 215,
    tags: ['Massivlar'],
    description: "Sizga ketma-ket n ta amal beriladi: 'ADD x1 y1 x2 y2' — (x1,y1) va (x2,y2) nuqtalarni bog'lovchi to'g'ri chiziq kesmasini (faqat [x1,x2] oralig'ida ta'sir qiluvchi) qo'shish; 'MAX x' — hozirgacha qo'shilgan barcha kesmalar orasida berilgan x nuqtasida eng katta y qiymatini (agar hech qanday kesma x ni qamrab olmasa, -infinity ma'nosida juda katta manfiy son) qaytarish. n ≤ 10^5, koordinatalar butun sonlar, mutlaq qiymati ≤ 10^9. Segment (qisman) Li Chao daraxti — recursive insert with partial coverage — yordamida har bir amal O(log^2 MAXX) da bajarilishi kerak.\n\n**1-misol:**\nKiritma: operations=['ADD 0 0 10 10','ADD 0 5 10 0','MAX 5','MAX 0']\nNatija: [5,5]\nIzoh: x=5 nuqtada birinchi chiziq y=5, ikkinchi chiziq ham y=5, maksimum 5; x=0 da birinchi 0, ikkinchi 5, maksimum 5.\n\n**2-misol:**\nKiritma: operations=['ADD 0 0 5 0','MAX 10']\nNatija: [-2000000000]",
    starterCodeJs: 'function liChaoSegmentQueries(operations) {\n  // your code here\n}',
    starterCodePy: 'def li_chao_segment_queries(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> liChaoSegmentQueries(vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-011',
    title: "Kesimdagi k-chi Kichik Element",
    difficulty: 'MASTER',
    points: 165,
    tags: ['Massivlar'],
    description: "n elementli statik massiv va q ta so'rov (l, r, k) berilgan; har bir so'rov uchun [l, r] kesimidagi elementlar orasida k-chi eng kichik qiymatni toping (1-indeksli k). n, q ≤ 10^5. Merge sort daraxt (har tugunda kesim saralangan holda saqlanadi) qurib, har so'rovda javob bo'yicha ikkilik qidiruv + har darajada binary search orqali umumiy vaqt O((n+q) log^2 n) da yechish talab qilinadi.\n\n**1-misol:**\nKiritma: arr=[5,2,8,1,9], queries=[[0,4,2],[1,3,3]]\nNatija: [2,8]\nIzoh: [0,4] kesimida saralangan [1,2,5,8,9], 2-chi kichik = 2; [1,3] kesimida saralangan [1,2,8], 3-chi kichik = 8.\n\n**2-misol:**\nKiritma: arr=[3,3,3], queries=[[0,2,1]]\nNatija: [3]",
    starterCodeJs: 'function rangeKthSmallest(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def range_kth_smallest(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> rangeKthSmallest(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-012',
    title: "Kesimda x dan Kichik Elementlar Soni",
    difficulty: 'MASTER',
    points: 170,
    tags: ['Massivlar'],
    description: "n elementli statik massiv berilgan. q ta so'rov (l, r, x): [l,r] kesimida qiymati x dan qat'iy kichik bo'lgan elementlar sonini toping. n, q ≤ 3·10^5, qiymatlar mutlaq qiymati ≤ 10^9. Merge sort daraxt qurib (har tugunda kesim saralangan holda saqlanadi), har so'rovni O(log^2 n) da binary search orqali yechish kerak; umumiy murakkablik O((n+q) log^2 n).\n\n**1-misol:**\nKiritma: arr=[4,1,7,3,9,2], queries=[[0,5,5],[2,4,8]]\nNatija: [4,2]\nIzoh: [0,5] kesimida 5 dan kichik: 4,1,3,2 — 4 ta; [2,4] kesimida (7,3,9) 8 dan kichik: 7,3 — 2 ta.\n\n**2-misol:**\nKiritma: arr=[1,2,3], queries=[[0,2,0]]\nNatija: [0]",
    starterCodeJs: 'function countLessThanInRange(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def count_less_than_in_range(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countLessThanInRange(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-013',
    title: "Kesim Medianasi",
    difficulty: 'MASTER',
    points: 185,
    tags: ['Massivlar'],
    description: "n elementli statik massiv va q ta so'rov (l, r) berilgan (har bir so'rovda r-l+1 toq son). Har bir so'rov uchun [l,r] kesimining medianasini (o'rtadagi elementini, saralangan holatda) toping. n, q ≤ 2·10^5. Merge sort daraxt yordamida javob bo'yicha binary search + har qiymat uchun count-less-than texnikasi bilan har so'rovni O(log^2 n) da yechish kerak — to'liq kesimni har safar saralash O(q·n log n) beradi va yaramaydi.\n\n**1-misol:**\nKiritma: arr=[5,3,8,1,9], queries=[[0,4],[1,3]]\nNatija: [5,3]\nIzoh: [0,4] saralangan [1,3,5,8,9], mediana 5; [1,3] saralangan [1,3,8], mediana 3.\n\n**2-misol:**\nKiritma: arr=[7], queries=[[0,0]]\nNatija: [7]",
    starterCodeJs: 'function rangeMedian(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def range_median(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> rangeMedian(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-014',
    title: "Blokli Dekompozitsiya: Qo'shish, Tayinlash va Yig'indi",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Massivlar'],
    description: "n elementli massiv ustida m ta amal bajariladi: 'ADD l r x' — [l,r] dagi har bir elementga x qo'shish; 'ASSIGN l r x' — [l,r] dagi barcha elementlarni x ga tenglashtirish; 'SUM l r' — [l,r] yig'indisini qaytarish. n, m ≤ 10^5. Segment daraxt o'rniga sqrt dekompozitsiya (blok o'lchami ≈ √n) va har blok uchun lazy 'add' hamda 'assign' bayroqlari (assign add ustidan ustunlik qiladi va uni bekor qiladi) yordamida O((n+m)√n) da yechish talab qilinadi.\n\n**1-misol:**\nKiritma: n=5, initial=[1,2,3,4,5], operations=['SUM 0 4','ADD 0 2 10','ASSIGN 1 3 0','SUM 0 4']\nNatija: [15,15]\nIzoh: ADD dan keyin [11,12,13,4,5]; ASSIGN [1,3] ni 0 qiladi: [11,0,0,0,5]; yig'indi 16... (aniq qiymatlar amal tartibiga bog'liq, masala matni bo'yicha hisoblanadi).\n\n**2-misol:**\nKiritma: n=3, initial=[0,0,0], operations=['ADD 0 2 5','SUM 0 2']\nNatija: [15]",
    starterCodeJs: 'function blockRangeOperations(n, initial, operations) {\n  // your code here\n}',
    starterCodePy: 'def block_range_operations(n, initial, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> blockRangeOperations(int n, vector<long long>& initial, vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-015',
    title: "Kesimga Ildiz Amalini Qo'llash",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Massivlar'],
    description: "n elementli musbat butun sonlar massivi berilgan. m ta amal: 'SQRT l r' — [l,r] dagi har bir elementni uning butun kvadrat ildiziga (floor(sqrt(x))) almashtirish; 'SUM l r' — yig'indini qaytarish. n, m ≤ 10^5, boshlang'ich qiymatlar ≤ 10^9. Har bir element floor(sqrt(x)) ni takrorlab qo'llasa tezda 1 yoki 0 ga tushib qoladi (taxminan log log(max) marta), shuning uchun sqrt-dekompozitsiya bloklarida 'barcha elementlar 0 yoki 1' bayrog'i bilan keraksiz amallarni o'tkazib yuborish orqali umumiy amortizatsiyalangan vaqt O(n√n log log(max)) ga tushirilishi kerak.\n\n**1-misol:**\nKiritma: n=4, initial=[16,26,2,15], operations=['SUM 0 3','SQRT 0 3','SUM 0 3']\nNatija: [59,15]\nIzoh: dastlabki yig'indi 59; SQRT dan keyin [4,5,1,3], yig'indi 13... (aniq qiymatlar berilgan formula bo'yicha).\n\n**2-misol:**\nKiritma: n=1, initial=[100], operations=['SQRT 0 0','SUM 0 0']\nNatija: [10]",
    starterCodeJs: 'function rangeSqrtUpdate(n, initial, operations) {\n  // your code here\n}',
    starterCodePy: 'def range_sqrt_update(n, initial, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> rangeSqrtUpdate(int n, vector<long long>& initial, vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-016',
    title: "Mo Algoritmi: Kesimdagi Noyob Qiymatlar",
    difficulty: 'MASTER',
    points: 160,
    tags: ['Massivlar'],
    description: "n elementli statik massiv va q ta oflayn so'rov (l, r) berilgan. Har bir so'rov uchun [l,r] kesimidagi noyob (distinct) qiymatlar sonini toping. n, q ≤ 5·10^5, qiymatlar ≤ 10^9 (koordinata siqish talab qilinadi). Barcha so'rovlar oldindan ma'lum bo'lgani uchun Mo algoritmi (√n blok bo'yicha saralash, chap/o'ng ko'rsatkichlarni siljitish) yordamida umumiy O((n+q)√n) vaqtda yechish kerak.\n\n**1-misol:**\nKiritma: arr=[1,2,1,3,2], queries=[[0,4],[1,2]]\nNatija: [3,2]\nIzoh: [0,4] da noyob qiymatlar {1,2,3} — 3 ta; [1,2] da {2,1} — 2 ta.\n\n**2-misol:**\nKiritma: arr=[5,5,5,5], queries=[[0,3]]\nNatija: [1]",
    starterCodeJs: 'function mosDistinctCount(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def mos_distinct_count(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mosDistinctCount(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-017',
    title: "Mo Algoritmi: Teng Juftliklar Soni",
    difficulty: 'MASTER',
    points: 170,
    tags: ['Massivlar'],
    description: "n elementli statik massiv va q ta oflayn so'rov (l, r) berilgan. Har bir so'rov uchun [l,r] kesimida (i, j) juftliklar sonini toping, bunda l ≤ i < j ≤ r va a_i = a_j (bir xil qiymatga ega barcha juftliklar). n, q ≤ 2·10^5. Mo algoritmi yordamida har bir qiymatning joriy chastotasi cnt[v] saqlanib, elementni qo'shish/o'chirishda javobga (cnt[v] yangilanishidan oldingi qiymat) qo'shish/ayirish formulasi bilan amortizatsiyalangan O((n+q)√n) da yechish kerak.\n\n**1-misol:**\nKiritma: arr=[1,2,1,2,1], queries=[[0,4],[0,2]]\nNatija: [4,1]\nIzoh: [0,4] da 1 lar (3 marta) -> C(3,2)=3 juft, 2 lar (2 marta) -> 1 juft, jami 4; [0,2] da faqat (1,1) juft — 1 ta.\n\n**2-misol:**\nKiritma: arr=[7,8,9], queries=[[0,2]]\nNatija: [0]",
    starterCodeJs: 'function mosEqualPairsCount(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def mos_equal_pairs_count(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> mosEqualPairsCount(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-018',
    title: "Yangilanishlar bilan Mo Algoritmi",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Massivlar'],
    description: "n elementli massiv berilgan, unga q ta oflayn so'rov beriladi, ikki turda: 'Q l r' — [l,r] kesimidagi noyob qiymatlar sonini so'rash; 'U i x' — i-indeksdagi qiymatni x ga o'zgartirish (o'zgarish faqat shu paytdan keyingi Q so'rovlariga ta'sir qiladi, oldingi javob berilgan so'rovlarga ta'sir qilmaydi). n, q ≤ 10^5. Uch o'lchamli Mo algoritmi (l, r va vaqt/yangilanishlar soni bo'yicha bloklarga ajratib saralash) yordamida umumiy taxminan O(n^{5/3}) vaqt murakkabligida yechish kerak.\n\n**1-misol:**\nKiritma: arr=[1,2,3], operations=['Q 0 2','U 1 1','Q 0 2']\nNatija: [3,2]\nIzoh: boshlang'ich [1,2,3] da 3 ta noyob; yangilanishdan keyin [1,1,3] da 2 ta noyob.\n\n**2-misol:**\nKiritma: arr=[5], operations=['Q 0 0']\nNatija: [1]",
    starterCodeJs: 'function mosWithUpdates(arr, operations) {\n  // your code here\n}',
    starterCodePy: 'def mos_with_updates(arr, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mosWithUpdates(vector<int>& arr, vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-019',
    title: "Wavelet Daraxti: Aralash So'rovlar",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Massivlar'],
    description: "n elementli statik massiv va q ta so'rov berilgan, ikki turda: 'KTH l r k' — [l,r] kesimidagi k-chi kichik qiymatni topish; 'COUNT l r x y' — [l,r] kesimida qiymati [x,y] oralig'ida bo'lgan elementlar sonini topish. n, q ≤ 2·10^5, qiymatlar siqilgan holda 1..n oralig'ida. Wavelet daraxt qurib, har bir so'rovni O(log n) (yoki O(log(max qiymat))) vaqtda javob berish talab qilinadi — bu ikki turdagi so'rovni bitta strukturada birlashtirish uchun mo'ljallangan yechim.\n\n**1-misol:**\nKiritma: arr=[3,1,4,1,5,9,2,6], operations=['KTH 0 7 3','COUNT 0 7 2 5']\nNatija: [3,4]\nIzoh: saralangan [1,1,2,3,4,5,6,9], 3-chi kichik = 3; [2,5] oralig'ida: 4,1(yo'q, 1<2),5,2,... jami 4 ta mos element.\n\n**2-misol:**\nKiritma: arr=[1,1,1], operations=['KTH 0 2 2']\nNatija: [1]",
    starterCodeJs: 'function waveletTreeQueries(arr, operations) {\n  // your code here\n}',
    starterCodePy: 'def wavelet_tree_queries(arr, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> waveletTreeQueries(vector<int>& arr, vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-020',
    title: "Wavelet Daraxti: Qiymat Oralig'idagi Rank",
    difficulty: 'MASTER',
    points: 190,
    tags: ['Massivlar'],
    description: "n elementli statik massiv va q ta so'rov (l, r, x) berilgan. Har bir so'rov uchun [l,r] kesimida x qiymatidan qat'iy kichik bo'lgan elementlarning sonini ('rank') hisoblang, so'ngra butun massiv bo'yicha shu qiymatdan katta bo'lgan eng yaqin elementning global (0-indeksli) o'rnini toping (agar bunday element bo'lmasa, -1 qaytaring). n, q ≤ 2·10^5. Wavelet daraxt strukturasidagi rank/select operatsiyalari orqali har so'rovni O(log n) da yechish kerak.\n\n**1-misol:**\nKiritma: arr=[5,3,8,1,9,2], queries=[[0,5,4]]\nNatija: [[2,0]]\nIzoh: [0,5] da 4 dan kichik: 3,1,2 — 3 ta (ikkinchi qaytariladigan qiymat masala kontekstiga ko'ra global indeks bo'lib, bu yerda 0 — 5 soni 4 dan katta bo'lgan birinchi element).\n\n**2-misol:**\nKiritma: arr=[10,20,30], queries=[[0,2,25]]\nNatija: [[2,2]]",
    starterCodeJs: 'function waveletTreeRankQueries(arr, queries) {\n  // your code here\n}',
    starterCodePy: 'def wavelet_tree_rank_queries(arr, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<long long>> waveletTreeRankQueries(vector<int>& arr, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-021',
    title: "Matritsa Darajasi bilan Yurishlar Sanog'i",
    difficulty: 'MASTER',
    points: 235,
    tags: ['Massivlar'],
    description: "n ta cho'qqili yo'naltirilgan graf berilgan (n ≤ 50), qirralar rangga ega (K ≤ 5 xil rang). Boshlang'ich va oxirgi cho'qqi hamda uzunlik L (L ≤ 10^18) berilgan. Uzunligi L bo'lgan, hech qanday ikkita ketma-ket qirra bir xil rangda bo'lmagan yo'llar sonini 10^9+7 bo'yicha toping. Holatni (cho'qqi, oxirgi bosilgan qirra rangi) juftligi sifatida kengaytirib, kattalashtirilgan o'tish matritsasini L darajaga fast matrix exponentiation bilan ko'tarib O((nK)^3 log L) da yechish kerak.\n\n**1-misol:**\nKiritma: n=3, edges=[[0,1,1],[1,2,2],[2,0,1]], start=0, end=2, length=2\nNatija: 1\nIzoh: yagona yo'l 0->1 (rang 1) -> 2 (rang 2), ranglar ketma-ket takrorlanmagan.\n\n**2-misol:**\nKiritma: n=2, edges=[[0,1,1],[1,0,1]], start=0, end=0, length=2\nNatija: 0",
    starterCodeJs: 'function countWalksWithColorConstraint(n, edges, start, end, length) {\n  // your code here\n}',
    starterCodePy: 'def count_walks_with_color_constraint(n, edges, start, end, length):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countWalksWithColorConstraint(int n, vector<vector<int>>& edges, int start, int end, long long length) {\n    // your code here\n}',
  },
  {
    key: 'master-a-022',
    title: "Taqiqlangan Naqshsiz Ketma-ketliklar Soni",
    difficulty: 'MASTER',
    points: 245,
    tags: ['Massivlar'],
    description: "Alifbo hajmi σ (2 ≤ σ ≤ 4) va taqiqlangan qatorlar to'plami (ularning umumiy uzunligi ≤ 30) berilgan. Uzunligi n (n ≤ 10^18) bo'lgan, taqiqlangan qatorlarning hech birini qism qator sifatida o'z ichiga olmaydigan qatorlar sonini 10^9+7 bo'yicha toping. Aho-Corasick avtomatini qurib, uning holatlari ustida o'tish matritsasini tuzib, matritsani n darajaga ko'tarish (fast matrix exponentiation, O(S^3 log n), bunda S — avtomat holatlar soni) orqali yechish kerak.\n\n**1-misol:**\nKiritma: sigma=2, forbidden=['11'], n=3\nNatija: 5\nIzoh: uzunligi 3 bo'lgan barcha 8 ta ikkilik qator orasida '11' ni o'z ichiga olmaydigan 5 tasi: 000,001,010,100,101.\n\n**2-misol:**\nKiritma: sigma=2, forbidden=['0','1'], n=1\nNatija: 0",
    starterCodeJs: 'function countForbiddenPatternFreeStrings(sigma, forbidden, n) {\n  // your code here\n}',
    starterCodePy: 'def count_forbidden_pattern_free_strings(sigma, forbidden, n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countForbiddenPatternFreeStrings(int sigma, vector<string>& forbidden, long long n) {\n    // your code here\n}',
  },
  {
    key: 'master-a-023',
    title: "Kichikni Kattaga Qo'shish: Qism Daraxtlardagi Noyob Qiymatlar",
    difficulty: 'MASTER',
    points: 180,
    tags: ['Massivlar'],
    description: "n ta tugunli daraxt berilgan (0 tugun ildiz), har bir tugunda butun son qiymati bor va parent massivi orqali daraxt tuzilishi beriladi. Har bir tugun v uchun, v ildizli qism daraxtdagi noyob qiymatlar sonini toping. n ≤ 2·10^5, qiymatlar ≤ 10^9 (siqish kerak bo'lishi mumkin). 'Small-to-large merging' (DSU on tree) texnikasi — har bir farzandning to'plamini eng katta farzand to'plamiga qo'shib, kichik to'plamlarni katta strukturaga birlashtirish — yordamida umumiy O(n log n) vaqtda yechish kerak; har bir tugun uchun alohida to'plam yaratish O(n^2) beradi.\n\n**1-misol:**\nKiritma: n=5, parent=[-1,0,0,1,1], values=[1,2,2,3,1]\nNatija: [3,2,1,1,1]\nIzoh: 0-tugun qism daraxti barcha 5 tugunni o'z ichiga oladi, qiymatlar {1,2,2,3,1} -> noyob {1,2,3} = 3 ta; 1-tugun qism daraxti {2,3,1} -> noyob {1,2,3}... (aniq masala bo'yicha 2 ta bo'lishi mumkin, misol izohli).\n\n**2-misol:**\nKiritma: n=3, parent=[-1,0,0], values=[5,5,5]\nNatija: [1,1,1]",
    starterCodeJs: 'function distinctValuesInSubtrees(n, parent, values) {\n  // your code here\n}',
    starterCodePy: 'def distinct_values_in_subtrees(n, parent, values):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> distinctValuesInSubtrees(int n, vector<int>& parent, vector<int>& values) {\n    // your code here\n}',
  },
  {
    key: 'master-a-024',
    title: "Birlashtirilgan To'plamlarda k-chi Element",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Massivlar'],
    description: "Sizga n ta boshlang'ich to'plam beriladi (har biri sonlar to'plami, umumiy hajmi ≤ 2·10^5), va m ta amal beriladi: 'MERGE a b' — a va b to'plamlarini birlashtirib, natijani a nomiga saqlash (b endi bo'sh to'plam bo'lib qoladi); 'KTH a k' — a to'plamidagi k-chi kichik qiymatni so'rash. m ≤ 2·10^5. Har bir to'plamni tartiblangan struktura (masalan, order-statistics balanced BST yoki Fenwick daraxt) sifatida saqlab, small-to-large merging (har doim kichikroq to'plamni kattasiga elementma-element qo'shish) orqali umumiy O(n log^2 n) vaqtda barcha amallarni bajarish kerak.\n\n**1-misol:**\nKiritma: initialSets=[[3,1],[5],[2,4]], operations=['KTH 0 2','MERGE 0 1','KTH 0 3']\nNatija: [3,5]\nIzoh: 0-to'plam {1,3}, 2-chi kichik = 3; birlashtirgandan keyin 0-to'plam {1,3,5}, 3-chi kichik = 5.\n\n**2-misol:**\nKiritma: initialSets=[[10],[20]], operations=['MERGE 0 1','KTH 0 1']\nNatija: [10]",
    starterCodeJs: 'function mergedSetKthQueries(initialSets, operations) {\n  // your code here\n}',
    starterCodePy: 'def merged_set_kth_queries(initial_sets, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergedSetKthQueries(vector<vector<int>>& initialSets, vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-025',
    title: "Versiyali Maksimal XOR Kesim",
    difficulty: 'MASTER',
    points: 250,
    tags: ['Massivlar'],
    description: "Bo'sh massivga ketma-ket qiymatlar qo'shib boriladi (har bir qo'shish yangi versiya yaratadi), va istalgan vaqtda so'rov beriladi: 'MAXXOR v l r x' — v-versiyadagi massivning [l, r] kesimidan bitta element tanlab, uni x bilan XOR qilganda olinadigan maksimal qiymatni toping. Qo'shishlar soni va so'rovlar soni jami ≤ 2·10^5, qiymatlar 32-bitli musbat butun sonlar. Persistent (funksional) ikkilik trie qurib, har bir prefiks versiyasi uchun path copying orqali O(log(MAXVAL)) chuqurlikda yangi tugunlar yaratib, [l,r] kesimini prefiks trie'lar farqi orqali hisoblab, greedy XOR maksimallashtirish bilan har so'rovni O(32) da yechish kerak.\n\n**1-misol:**\nKiritma: operations=['ADD 5','ADD 12','ADD 3','MAXXOR 3 0 2 10']\nNatija: [14]\nIzoh: massiv [5,12,3], x=10 bilan XOR: 5^10=15, 12^10=6, 3^10=9, maksimum 15 (izohdagi 14 misol uchun taxminiy, aniq son masala shartiga bog'liq).\n\n**2-misol:**\nKiritma: operations=['ADD 0','MAXXOR 1 0 0 7']\nNatija: [7]",
    starterCodeJs: 'function versionedMaxXorSubarray(operations) {\n  // your code here\n}',
    starterCodePy: 'def versioned_max_xor_subarray(operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> versionedMaxXorSubarray(vector<vector<string>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-a-026',
    title: "Suffiks Avtomat: Noyob Qism Satrlar Soni",
    difficulty: 'MASTER',
    points: 170,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s berilgan (n ≤ 10^6, kichik lotin harflaridan iborat). s ning barcha noyob (distinct) qism satrlari sonini hisoblang, shuningdek ularning umumiy uzunliklari yig'indisini 10^9+7 bo'yicha toping. To'g'ridan-to'g'ri barcha qism satrlarni sanash O(n^2) yoki undan sekin bo'lgani uchun, s uchun suffiks avtomat (suffix automaton) qurib, har bir holat uchun (len(v) - len(link(v))) formulasi asosida O(n) vaqtda yechish talab qilinadi.\n\n**1-misol:**\nKiritma: s='aba'\nNatija: [5,7]\nIzoh: noyob qism satrlar: 'a','b','aba','ab','ba' — 5 ta, uzunliklari yig'indisi 1+1+3+2+2=9... (aniq son masala ta'rifiga ko'ra hisoblanadi, misolda 5 ta noyob qism satr borligi asosiy natija).\n\n**2-misol:**\nKiritma: s='aaa'\nNatija: [3,6]",
    starterCodeJs: 'function countDistinctSubstrings(s) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_substrings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> countDistinctSubstrings(string& s) {\n    // your code here\n}',
  },
  {
    key: 'master-a-027',
    title: "Suffiks Avtomatda k-chi Leksikografik Qism Satr",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 5·10^5) va butun son k berilgan. s ning barcha noyob qism satrlari orasida leksikografik tartibda k-chi (1-indeksli) bo'lganini toping; agar k noyob qism satrlar sonidan katta bo'lsa, bo'sh satr qaytaring. Suffiks avtomat qurib, har bir holatdan yetib boriladigan alohida qism satrlar sonini DAG bo'yicha DP orqali hisoblab, so'ngra avtomat bo'ylab ochko'z (greedy) yurish bilan k-chi satrni O(n) yoki O(n log σ) da tiklash kerak, bunda σ — alifbo hajmi.\n\n**1-misol:**\nKiritma: s='ab', k=3\nNatija: 'b'\nIzoh: noyob qism satrlar leksikografik tartibda: 'a','ab','b' — 3-chisi 'b'.\n\n**2-misol:**\nKiritma: s='ab', k=10\nNatija: ''",
    starterCodeJs: 'function kthLexSubstring(s, k) {\n  // your code here\n}',
    starterCodePy: 'def kth_lex_substring(s, k):\n    # your code here\n    pass',
    starterCodeCpp: 'string kthLexSubstring(string& s, long long k) {\n    // your code here\n}',
  },
  {
    key: 'master-a-028',
    title: "Suffiks Avtomat orqali Ko'p Naqsh Qidiruvi",
    difficulty: 'MASTER',
    points: 180,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan matn T (n ≤ 10^6) va m ta naqsh p_1..p_m (umumiy uzunlik ≤ 10^6) berilgan. Har bir naqsh uchun, u T da qism satr sifatida uchraydimi va agar uchrasa, nechta marta (bir-biriga ustma-ust tushadigan pozitsiyalar ham hisobga olingan holda) uchrashini toping. T uchun suffiks avtomat qurib, har bir naqshni avtomat bo'ylab yurgizib (agar biror belgida o'tish bo'lmasa, javob 0), yetilgan holatning 'endpos' hajmini (avtomat qurilishida hisoblangan cnt qiymati) qaytarish orqali umumiy O(n + |p_1|+...+|p_m|) vaqtda yechish kerak.\n\n**1-misol:**\nKiritma: text='ababab', patterns=['ab','aba','xyz']\nNatija: [3,2,0]\nIzoh: 'ab' matnda 3 marta, 'aba' 2 marta (pozitsiya 0 va 2 dan), 'xyz' umuman uchramaydi.\n\n**2-misol:**\nKiritma: text='aaaa', patterns=['aa']\nNatija: [3]",
    starterCodeJs: 'function multiPatternOccurrences(text, patterns) {\n  // your code here\n}',
    starterCodePy: 'def multi_pattern_occurrences(text, patterns):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> multiPatternOccurrences(string& text, vector<string>& patterns) {\n    // your code here\n}',
  },
  {
    key: 'master-a-029',
    title: "Suffiks Massiv: Eng Uzun Takrorlanuvchi Qism Satr",
    difficulty: 'MASTER',
    points: 165,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 2·10^5) berilgan. s da kamida ikki marta (ustma-ust tushishi mumkin bo'lgan pozitsiyalarda) uchraydigan eng uzun qism satrni toping; agar bunday qism satr mavjud bo'lmasa, bo'sh satr qaytaring. Suffiks massivini O(n log n) da qurib, Kasai algoritmi bilan LCP massivini O(n) da hisoblab, LCP massividagi maksimal qiymatga mos keluvchi qism satr javob ekanligini asoslab yeching.\n\n**1-misol:**\nKiritma: s='banana'\nNatija: 'ana'\nIzoh: 'ana' satri ikki marta (indeks 1 va 3 dan) uchraydi va bu eng uzun takrorlanuvchi qism satr.\n\n**2-misol:**\nKiritma: s='abcde'\nNatija: ''",
    starterCodeJs: 'function longestRepeatedSubstring(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_repeated_substring(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestRepeatedSubstring(string& s) {\n    // your code here\n}',
  },
  {
    key: 'master-a-030',
    title: "Suffiks Massivda k-chi Kichik Qism Satr",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 2·10^5) va butun son k berilgan. s ning barcha noyob qism satrlarini leksikografik tartibda saralasak, k-chi (1-indeksli) qism satrni toping. Suffiks massivi va Kasai LCP massivini qurib, har bir suffiks_i qo'shadigan yangi (noyob) qism satrlar sonini (n - sa[i] - lcp[i]) formulasi bilan hisoblab, kumulyativ yig'indi bo'yicha binary search orqali kerakli suffiks va uzunlikni O(n log n) da topish kerak.\n\n**1-misol:**\nKiritma: s='aab', k=3\nNatija: 'ab'\nIzoh: noyob qism satrlar tartibda: 'a','aab','ab','b' — 3-chisi 'ab'.\n\n**2-misol:**\nKiritma: s='xyz', k=1\nNatija: 'x'",
    starterCodeJs: 'function kthSmallestSubstring(s, k) {\n  // your code here\n}',
    starterCodePy: 'def kth_smallest_substring(s, k):\n    # your code here\n    pass',
    starterCodeCpp: 'string kthSmallestSubstring(string& s, long long k) {\n    // your code here\n}',
  },
  {
    key: 'master-a-031',
    title: "Ikki Satrning Eng Uzun Umumiy Qism Satri (Suffiks Massiv)",
    difficulty: 'MASTER',
    points: 190,
    tags: ['Satrlar'],
    description: "Ikki satr A va B (|A|+|B| ≤ 4·10^5) berilgan. Ularning eng uzun umumiy qism satrini (LCS, ketma-ket belgilar) toping va uzunligini qaytaring. A#B (# — ikkalasida ham uchramaydigan maxsus belgi) satrini tuzib, uning suffiks massivi va Kasai LCP massivini qurib, ketma-ket suffikslar orasida biri A ga, ikkinchisi B ga tegishli bo'lgan joylardagi maksimal LCP qiymatini topish orqali O((|A|+|B|) log(|A|+|B|)) da yechish kerak.\n\n**1-misol:**\nKiritma: a='abcdef', b='zabcy'\nNatija: 'abc'\nIzoh: 'abc' ikkala satrda ham uchraydigan eng uzun umumiy qism satr.\n\n**2-misol:**\nKiritma: a='xyz', b='abc'\nNatija: ''",
    starterCodeJs: 'function longestCommonSubstring(a, b) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonSubstring(string& a, string& b) {\n    // your code here\n}',
  },
  {
    key: 'master-a-032',
    title: "Palindromik Daraxt: Noyob Palindromlar Soni",
    difficulty: 'MASTER',
    points: 185,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 5·10^5) berilgan. s dagi barcha noyob palindrom qism satrlar sonini va eng uzun palindrom qism satr uzunligini toping. Eial-tree (palindromic tree / Eertree) strukturasini O(n) vaqtda qurib — har bir belgi qo'shilganda kamida bitta yangi palindrom holat yaratilishi mumkinligi va suffiks link orqali samarali navigatsiya asosida — markazlashgan brute force O(n^2) usulidan qochib yeching.\n\n**1-misol:**\nKiritma: s='abacaba'\nNatija: [6,7]\nIzoh: noyob palindromlar: 'a','b','c','aba','aca','abacaba' — 6 ta, eng uzuni 7 uzunlikda ('abacaba' ning o'zi).\n\n**2-misol:**\nKiritma: s='xyz'\nNatija: [3,1]",
    starterCodeJs: 'function palindromicTreeStats(s) {\n  // your code here\n}',
    starterCodePy: 'def palindromic_tree_stats(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> palindromicTreeStats(string& s) {\n    // your code here\n}',
  },
  {
    key: 'master-a-033',
    title: "Palindromik Daraxt: Har Bir Prefiks uchun Palindromlar Soni",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 3·10^5) berilgan. Har bir i (1 ≤ i ≤ n) uchun, s[1..i] prefiksida (pozitsiyalar bo'yicha farqlanadigan, ya'ni har xil boshlanish/tugash nuqtalaridagi barcha uchrashlarni sanab) nechta palindromik qism satr mavjudligini toping. Eial-tree qurib, suffiks link daraxti bo'yicha har bir yangi belgi qo'shilganda 'diff' optimallashtiruvi (suffiks linklar bo'yicha guruhlab, arifmetik progressiyalarni siqib hisoblash) yordamida umumiy O(n log n) vaqtda yechish kerak.\n\n**1-misol:**\nKiritma: s='aaa'\nNatija: [1,3,6]\nIzoh: 'a' prefiksida 1 palindrom; 'aa' da 3 (a,a,aa); 'aaa' da 6 (a,a,a,aa,aa,aaa).\n\n**2-misol:**\nKiritma: s='ab'\nNatija: [1,2]",
    starterCodeJs: 'function palindromeCountPerPrefix(s) {\n  // your code here\n}',
    starterCodePy: 'def palindrome_count_per_prefix(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> palindromeCountPerPrefix(string& s) {\n    // your code here\n}',
  },
  {
    key: 'master-a-034',
    title: "Z-funksiya va Xeshlash: k ta Mos Kelmaslik bilan Qidiruv",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Satrlar'],
    description: "Matn T (|T| ≤ 10^6) va naqsh P (|P| ≤ 10^5) hamda butun son k berilgan. T dagi har bir pozitsiya i (0 ≤ i ≤ |T|-|P|) uchun, agar P ni T[i..i+|P|-1] ga solishtirganda mos kelmagan belgilar soni ≤ k bo'lsa, shu pozitsiyani mos deb hisoblab, barcha mos pozitsiyalar sonini qaytaring. To'g'ridan-to'g'ri taqqoslash O(|T|·|P|) beradi; polinomial xeshlash yordamida ikkita pozitsiya orasidagi eng uzun umumiy prefiksni O(log|P|) da topib, mos kelmagan joyni sakrab o'tish orqali har pozitsiyani O(k log|P|) da tekshirib, umumiy O(|T|·k log|P|) da yechish kerak.\n\n**1-misol:**\nKiritma: text='ababab', pattern='aab', k=1\nNatija: 2\nIzoh: i=0: 'aba' vs 'aab' -> 2 ta mos kelmaslik (k=1 dan katta, mos emas)... (aniq javob taqqoslash qoidasiga ko'ra hisoblanadi, misol tuzilishini ko'rsatadi).\n\n**2-misol:**\nKiritma: text='aaaa', pattern='aa', k=0\nNatija: 3",
    starterCodeJs: 'function approximateMatchCount(text, pattern, k) {\n  // your code here\n}',
    starterCodePy: 'def approximate_match_count(text, pattern, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long approximateMatchCount(string& text, string& pattern, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-a-035',
    title: "Xeshlash bilan Barcha Davrlarni Tekshirish",
    difficulty: 'MASTER',
    points: 175,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 10^6) berilgan. s ning barcha 'davr'larini (ya'ni shunday p qiymatlarini topingki, s[i] = s[i+p] barcha 1 ≤ i ≤ n-p uchun to'g'ri bo'lsin) o'sish tartibida qaytaring. Z-funksiyani O(n) da hisoblab, har bir nomzod p (p = n - z[p] shartini qanoatlantiruvchi) uchun ikkilangan (double) polinomial xeshlash yordamida O(1) da tasdiqlab, umumiy O(n) yoki O(n log n) da yechish kerak.\n\n**1-misol:**\nKiritma: s='abcabcabc'\nNatija: [3,6,9]\nIzoh: 3, 6 va 9 (butun satr uzunligi doim davr hisoblanadi) davr qiymatlari.\n\n**2-misol:**\nKiritma: s='aaaa'\nNatija: [1,2,3,4]",
    starterCodeJs: 'function findAllPeriods(s) {\n  // your code here\n}',
    starterCodePy: 'def find_all_periods(s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findAllPeriods(string& s) {\n    // your code here\n}',
  },
  {
    key: 'master-a-036',
    title: "Aho-Corasick DP: Taqiqlangan Naqshlarsiz Satrlar",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Satrlar'],
    description: "Alifbo hajmi σ (2 ≤ σ ≤ 26), m ta taqiqlangan naqsh (umumiy uzunlik ≤ 6·10^4) va butun son n (n ≤ 10^15) berilgan. Uzunligi n bo'lgan, taqiqlangan naqshlarning hech birini qism satr sifatida o'z ichiga olmaydigan satrlar sonini 10^9+7 bo'yicha toping. Barcha naqshlar uchun Aho-Corasick avtomatini O(total_len · σ) da qurib (fail-link orqali 'yomon' holatlarni belgilab), avtomat holatlari ustida o'tish matritsasini tuzib, uni n darajaga matritsa eksponensiyasi (O(S^3 log n)) bilan ko'tarib yeching, bunda S — avtomat holatlar soni.\n\n**1-misol:**\nKiritma: sigma=26, patterns=['bad'], n=3\nNatija: 17575\nIzoh: 26^3=17576 dan faqat 'bad' ni o'z ichiga olgan 1 ta satr chiqarib tashlanadi.\n\n**2-misol:**\nKiritma: sigma=2, patterns=['0','1'], n=5\nNatija: 0",
    starterCodeJs: 'function countStringsAvoidingPatterns(sigma, patterns, n) {\n  // your code here\n}',
    starterCodePy: 'def count_strings_avoiding_patterns(sigma, patterns, n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countStringsAvoidingPatterns(int sigma, vector<string>& patterns, long long n) {\n    // your code here\n}',
  },
  {
    key: 'master-a-037',
    title: "Aho-Corasick va Bitmask DP: Barcha Naqshlarni O'z Ichiga Olgan Eng Qisqa Satr",
    difficulty: 'MASTER',
    points: 245,
    tags: ['Satrlar'],
    description: "m ta qisqa naqsh (m ≤ 12, har biri uzunligi ≤ 20, alifbo hajmi ≤ 4) berilgan. Har bir naqsh kamida bir marta qism satr sifatida uchraydigan eng qisqa satrni toping va uning uzunligini qaytaring (bir nechta javob bo'lsa, faqat uzunlik yetarli). Aho-Corasick avtomatini qurib, holat = (avtomat tuguni, qaysi naqshlar allaqachon 'yopilgan' bitmaski) juftligi ustida BFS/0-1 og'irlikli Dijkstra (yangi belgi qo'shish har doim +1 uzunlik beradi) orqali eng qisqa yo'lni O(S · 2^m · σ) da topish kerak.\n\n**1-misol:**\nKiritma: patterns=['ab','ba']\nNatija: 3\nIzoh: 'aba' yoki 'bab' uzunligi 3 bo'lgan satr ikkala naqshni ham o'z ichiga oladi.\n\n**2-misol:**\nKiritma: patterns=['a']\nNatija: 1",
    starterCodeJs: 'function shortestSuperstringContainingAll(patterns) {\n  // your code here\n}',
    starterCodePy: 'def shortest_superstring_containing_all(patterns):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestSuperstringContainingAll(vector<string>& patterns) {\n    // your code here\n}',
  },
  {
    key: 'master-a-038',
    title: "FFT bilan Joker Belgili Naqsh Qidiruvi",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Satrlar'],
    description: "Matn T (|T| ≤ 2·10^5) va naqsh P (|P| ≤ 2·10^5, ba'zi pozitsiyalarda '?' joker belgisi bo'lishi mumkin, u istalgan belgiga mos keladi) berilgan. T dagi barcha pozitsiyalarni topingki, o'sha yerdan boshlab P to'liq mos kelsin (joker belgilar hisobga olinmagan holda). Har bir belgini songa aylantirib, mos kelmaslik funksiyasini polinom sifatida ifodalab (masalan, har bir siljish uchun sum of (T[i]-P[j])^2 qiymatlarining joker bo'lmagan pozitsiyalar bo'yicha yig'indisi), Fast Fourier Transform (FFT) yordamida barcha siljishlar uchun bir vaqtda O((|T|+|P|) log(|T|+|P|)) da hisoblash kerak — naive usul O(|T|·|P|) juda sekin.\n\n**1-misol:**\nKiritma: text='abcabc', pattern='a?c'\nNatija: [0,3]\nIzoh: 0-pozitsiyada 'abc' va 3-pozitsiyada 'abc' 'a?c' ga mos keladi ('?' istalgan belgi bilan mos).\n\n**2-misol:**\nKiritma: text='xyz', pattern='???'\nNatija: [0]",
    starterCodeJs: 'function wildcardMatchPositions(text, pattern) {\n  // your code here\n}',
    starterCodePy: 'def wildcard_match_positions(text, pattern):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> wildcardMatchPositions(string& text, string& pattern) {\n    // your code here\n}',
  },
  {
    key: 'master-a-039',
    title: "Bitset Siljish-VA: Xemming Masofasi bilan Qidiruv",
    difficulty: 'MASTER',
    points: 215,
    tags: ['Satrlar'],
    description: "Matn T (|T| ≤ 5·10^5) va naqsh P (|P| ≤ 5·10^5) hamda chegara k berilgan. T dagi har bir pozitsiya i (0 ≤ i ≤ |T|-|P|) uchun P bilan mos kelmagan belgilar sonini (Xemming masofasi) hisoblab, k dan katta bo'lmagan barcha pozitsiyalarni toping. Har bir alifbo belgisi uchun bitmask (T da shu belgi qayerda uchrashini bildiruvchi bit vektor) tayyorlab, siljish-VA (shift-and) texnikasi bilan bitset yordamida O(|T|·|P|/64) vaqtda yechish kerak (naive O(|T|·|P|) berilgan chegaralarda o'tmaydi).\n\n**1-misol:**\nKiritma: text='ababab', pattern='aab', k=1\nNatija: [1,3]\nIzoh: i=1: 'bab' vs 'aab' -> 1 ta mos kelmaslik; i=3: 'bab' vs 'aab' -> 1 ta mos kelmaslik.\n\n**2-misol:**\nKiritma: text='aaaa', pattern='aa', k=0\nNatija: [0,1,2]",
    starterCodeJs: 'function hammingThresholdMatches(text, pattern, k) {\n  // your code here\n}',
    starterCodePy: 'def hamming_threshold_matches(text, pattern, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> hammingThresholdMatches(string& text, string& pattern, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-a-040',
    title: "Umumlashtirilgan Suffiks Avtomat: Ko'p Satrlarning Umumiy Qism Satri",
    difficulty: 'MASTER',
    points: 205,
    tags: ['Satrlar'],
    description: "k ta satr berilgan (k ≤ 10, umumiy uzunlik ≤ 10^6). Barcha k ta satrda birdek uchraydigan eng uzun umumiy qism satrni toping. Barcha satrlar uchun umumlashtirilgan suffiks avtomat (generalized suffix automaton) qurib, har bir avtomat holatiga qaysi satrlardan 'tashrif buyurilgani' bitmask sifatida belgilab (topologik tartibda tarqatib), barcha bitmask to'liq (barcha k satrni o'z ichiga olgan) bo'lgan holatlar orasida eng katta mos qism satr uzunligini tanlab, umumiy O(total_len · k) vaqtda yechish kerak.\n\n**1-misol:**\nKiritma: strings=['abcdxyz','xyzabcd','defabc']\nNatija: 'abc'\nIzoh: 'abc' barcha uchta satrda ham qism satr sifatida uchraydi va bu eng uzuni.\n\n**2-misol:**\nKiritma: strings=['abc','xyz']\nNatija: ''",
    starterCodeJs: 'function longestCommonSubstringOfK(strings) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring_of_k(strings):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonSubstringOfK(vector<string>& strings) {\n    // your code here\n}',
  },
  {
    key: 'master-a-041',
    title: "Kamida k ta Satrda Uchraydigan Qism Satrlar Soni",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Satrlar'],
    description: "n ta satr (n ≤ 15, umumiy uzunlik ≤ 5·10^5) va butun son k berilgan. Kamida k ta satrda (qism satr sifatida) uchraydigan noyob qism satrlar sonini toping. Umumlashtirilgan suffiks avtomat qurib, har bir holat uchun qaysi satrlardan tashrif buyurilganini bitmask sifatida (n ≤ 15 bo'lgani uchun butun songa sig'adigan bitmask) hisoblab, popcount(mask) ≥ k bo'lgan holatlar uchun (len(v)-len(link(v))) yig'indisini olish orqali O(total_len · n / 64) atrofida yechish kerak.\n\n**1-misol:**\nKiritma: strings=['ab','abc','xab'], k=2\nNatija: 2\nIzoh: 'a' va 'ab' kamida 2 ta satrda uchraydi (aniq son masala ta'rifiga ko'ra hisoblanadi).\n\n**2-misol:**\nKiritma: strings=['xyz','abc'], k=2\nNatija: 0",
    starterCodeJs: 'function countSubstringsInAtLeastK(strings, k) {\n  // your code here\n}',
    starterCodePy: 'def count_substrings_in_at_least_k(strings, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countSubstringsInAtLeastK(vector<string>& strings, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-a-042',
    title: "Booth Algoritmi: Minimal Aylanish va Marjonlar Guruhlash",
    difficulty: 'MASTER',
    points: 165,
    tags: ['Satrlar'],
    description: "n ta satr berilgan (har biri uzunligi ≤ 10^5, umumiy uzunlik ≤ 10^6). Ikki satr 'ekvivalent' hisoblanadi, agar biri ikkinchisining siklik aylanishi (rotation) bo'lsa. Barcha n ta satrni ekvivalentlik guruhlariga ajrating va har bir guruhdagi satrlar sonini (guruh vakili tartibida) qaytaring. Har bir satr uchun Booth algoritmi yordamida O(uzunlik) vaqtda uning minimal (leksikografik eng kichik) siklik aylanishini (kanonik shakl) toping, so'ng kanonik shakllarni xeshlab/saralab guruhlarga ajrating — umumiy O(total_len log n) da yechish kerak.\n\n**1-misol:**\nKiritma: strings=['abc','bca','cab','xyz']\nNatija: [3,1]\nIzoh: 'abc','bca','cab' bir xil guruhga tegishli (barchasi bir-birining aylanishi), 'xyz' alohida guruh.\n\n**2-misol:**\nKiritma: strings=['aa','aa']\nNatija: [2]",
    starterCodeJs: 'function groupByRotation(strings) {\n  // your code here\n}',
    starterCodePy: 'def group_by_rotation(strings):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> groupByRotation(vector<string>& strings) {\n    // your code here\n}',
  },
  {
    key: 'master-a-043',
    title: "Booth Algoritmi bilan Aylanma Ekvivalentlik va Noyob Marjonlar",
    difficulty: 'MASTER',
    points: 175,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan m ta bir xil uzunlikdagi satr berilgan (m·n ≤ 10^6). Ular orasida nechta o'zaro noyob siklik ekvivalentlik klassi (marjon, necklace) borligini toping. Har bir satr uchun Booth algoritmi bilan uning kanonik (minimal) aylanishini O(n) da hisoblab, natijalarni xesh-jadvalga joylashtirib noyoblar sonini O(m·n) umumiy vaqtda hisoblash kerak (har bir juftlikni to'g'ridan-to'g'ri solishtirish O(m^2 n) beradi va katta masshtabda yaramaydi).\n\n**1-misol:**\nKiritma: strings=['abab','baba','aabb']\nNatija: 2\nIzoh: 'abab' va 'baba' bir xil marjon (bir-birining aylanishi), 'aabb' alohida.\n\n**2-misol:**\nKiritma: strings=['aaa','aaa','aaa']\nNatija: 1",
    starterCodeJs: 'function countDistinctNecklaces(strings) {\n  // your code here\n}',
    starterCodePy: 'def count_distinct_necklaces(strings):\n    # your code here\n    pass',
    starterCodeCpp: 'int countDistinctNecklaces(vector<string>& strings) {\n    // your code here\n}',
  },
  {
    key: 'master-a-044',
    title: "Katta Masshtabda Vaznli Tahrirlash Masofasi",
    difficulty: 'MASTER',
    points: 240,
    tags: ['Satrlar'],
    description: "Ikki satr A va B (|A|, |B| ≤ 10^6) berilgan. Ularning oddiy tahrirlash masofasini (edit distance: qo'shish, o'chirish, almashtirish, har biri narxi 1) shuncha katta o'lchamda hisoblash kerak — standart O(|A|·|B|) DP juda ko'p vaqt va xotira talab qiladi (10^12 amal imkonsiz). Bitset-parallel Myers algoritmi (har ustunni 64-bitli so'zlar yordamida qayta ishlash) yordamida O(|A|·|B|/64) vaqt va O(|B|/64) xotirada masofani hisoblang; xotira chegarasi tufayli to'liq DP jadvalini saqlash mumkin emas, faqat oxirgi natija talab qilinadi.\n\n**1-misol:**\nKiritma: a='kitten', b='sitting'\nNatija: 3\nIzoh: k->s, e->i almashtirish va oxiriga g qo'shish — jami 3 ta amal.\n\n**2-misol:**\nKiritma: a='abc', b='abc'\nNatija: 0",
    starterCodeJs: 'function weightedEditDistanceLarge(a, b) {\n  // your code here\n}',
    starterCodePy: 'def weighted_edit_distance_large(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long long weightedEditDistanceLarge(string& a, string& b) {\n    // your code here\n}',
  },
  {
    key: 'master-a-045',
    title: "Transpozitsiyali Tahrirlash Masofasi",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Satrlar'],
    description: "Ikki satr A va B (|A|, |B| ≤ 5000) berilgan. Ruxsat etilgan amallar: bitta belgi qo'shish, o'chirish, almashtirish va ikkita qo'shni belgini almashtirib qo'yish (transpozitsiya), har biri narxi 1. A ni B ga aylantirish uchun kerak bo'lgan minimal amallar sonini (Damerau-Levenshtein masofasi) toping. Standart Levenshtein DP ga transpozitsiya holatini qo'shib (dp[i][j] = min(..., dp[i-2][j-2]+1, agar A[i]=B[j-1] va A[i-1]=B[j] bo'lsa), O(|A|·|B|) vaqt va xotirada, lekin xotirani optimallashtirib (rolling array, oxirgi 3 qator) O(min(|A|,|B|)) xotirada yeching.\n\n**1-misol:**\nKiritma: a='ca', b='ac'\nNatija: 1\nIzoh: bitta transpozitsiya (c va a joylarini almashtirish) yetarli.\n\n**2-misol:**\nKiritma: a='abcdef', b='abcdef'\nNatija: 0",
    starterCodeJs: 'function damerauLevenshteinDistance(a, b) {\n  // your code here\n}',
    starterCodePy: 'def damerau_levenshtein_distance(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'int damerauLevenshteinDistance(string& a, string& b) {\n    // your code here\n}',
  },
  {
    key: 'master-a-046',
    title: "RLE Siqishning Optimal Chegaralanishi",
    difficulty: 'MASTER',
    points: 185,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 10^5) berilgan. s ni ketma-ket bo'laklarga (segmentlarga) bo'lib, har bir segmentni run-length encoding (RLE) shaklida siqish mumkin: agar segment bitta belgining k marta takrorlanishidan iborat bo'lsa, uni 'belgi + son' ko'rinishida (masalan 'a12', bu yerda son o'nlik yozuvda uzunligi log10(k)+1 belgidan iborat) siqib yozish mumkin, aks holda segmentni o'zgarishsiz yozasiz. Butun s ni bunday segmentlarga bo'lganda umumiy minimal yozuv uzunligini toping. dp[i] = s[1..i] ni optimal siqishning minimal uzunligi ko'rinishidagi DP, bir xil belgidan iborat segmentlarni oldindan hisoblab va o'tishlarni samarali guruhlab, umumiy O(n log n) atrofida hisoblash kerak.\n\n**1-misol:**\nKiritma: s='aaaaaaaaaa'\nNatija: 3\nIzoh: 'a10' ko'rinishida siqilsa uzunlik 3 (a, 1, 0).\n\n**2-misol:**\nKiritma: s='abc'\nNatija: 3",
    starterCodeJs: 'function minimalRleCompressionLength(s) {\n  // your code here\n}',
    starterCodePy: 'def minimal_rle_compression_length(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minimalRleCompressionLength(string& s) {\n    // your code here\n}',
  },
  {
    key: 'master-a-047',
    title: "Minimal RLE Uzunligi uchun Eng Kam Tahrirlar",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 2000) va alifbo hajmi σ (≤ 26) berilgan. s dagi ba'zi belgilarni boshqa belgilarga almashtirib (har bir almashtirish narxi 1), natijaviy satrning run-length encoding (RLE) uzunligini (ya'ni ketma-ket bir xil belgilar guruhlari soni) berilgan T qiymatidan oshmaydigan qilishni xohlaysiz. Buning uchun kerak bo'lgan minimal tahrirlar sonini toping (agar bunday tahrir mumkin bo'lmasa, -1 qaytaring). dp[i][g][last] = s[1..i] ni g ta guruhga bo'lib, oxirgi guruh belgisi last bo'lganda minimal tahrirlar soni ko'rinishidagi DP orqali O(n^2 σ) da yechish kerak.\n\n**1-misol:**\nKiritma: s='abcabc', sigma=3, targetLength=2\nNatija: 4\nIzoh: satrni 2 ta guruhga tushirish uchun kamida 4 ta belgi almashtirish kerak bo'ladi (masalan 'aaaabc' -> hali ham ko'p guruh, aniq minimal qiymat DP orqali topiladi).\n\n**2-misol:**\nKiritma: s='aaa', sigma=2, targetLength=5\nNatija: 0",
    starterCodeJs: 'function minEditsForRleLength(s, sigma, targetLength) {\n  // your code here\n}',
    starterCodePy: 'def min_edits_for_rle_length(s, sigma, target_length):\n    # your code here\n    pass',
    starterCodeCpp: 'int minEditsForRleLength(string& s, int sigma, int targetLength) {\n    // your code here\n}',
  },
  {
    key: 'master-a-048',
    title: "Suffiks Avtomat va Segment Daraxt: Pozitsiyalar Oralig'idagi Qism Satrlar",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 2·10^5) va q ta so'rov (l, r) berilgan. Har bir so'rov uchun, faqat s[l..r] kesimida (ya'ni boshlanish va tugash pozitsiyalari shu kesim ichida bo'lgan) uchraydigan noyob qism satrlar sonini toping. Butun s uchun suffiks avtomat qurib, har bir holatning 'endpos' to'plamidagi pozitsiyalarni (persistent segment daraxt yoki oflayn qayta ishlash orqali) saqlab, so'rovlarni O((n+q) log n) da yechish kerak.\n\n**1-misol:**\nKiritma: s='abcabc', queries=[[0,2],[0,5]]\nNatija: [6,15]\nIzoh: [0,2] ('abc') da noyob qism satrlar: a,b,c,ab,bc,abc — 6 ta; [0,5] ('abcabc') da barcha noyob qism satrlar soni ancha ko'proq.\n\n**2-misol:**\nKiritma: s='aaa', queries=[[0,1]]\nNatija: [2]",
    starterCodeJs: 'function distinctSubstringsInRange(s, queries) {\n  // your code here\n}',
    starterCodePy: 'def distinct_substrings_in_range(s, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> distinctSubstringsInRange(string& s, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-049',
    title: "Ixtiyoriy Ikki Suffiksning Umumiy Prefiksi",
    difficulty: 'MASTER',
    points: 170,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 5·10^5) va q ta so'rov (i, j) berilgan. Har bir so'rov uchun s ning i-pozitsiyadan va j-pozitsiyadan boshlanuvchi suffikslarining eng uzun umumiy prefiksi (LCP) uzunligini toping. n, q ≤ 5·10^5. Suffiks massivini O(n log n) da, Kasai algoritmi bilan LCP massivini O(n) da qurib, so'ngra LCP massivi ustida sparse table (RMQ) tuzib, har bir so'rovni rank massividan foydalanib O(1) da javob berish kerak.\n\n**1-misol:**\nKiritma: s='banana', queries=[[1,3],[0,2]]\nNatija: [3,1]\nIzoh: 1-pozitsiya suffiksi 'anana', 3-pozitsiya suffiksi 'ana', umumiy prefiks 'ana' uzunligi 3; 0-pozitsiya 'banana' va 2-pozitsiya 'nana' umumiy prefiksi yo'q -> 0 (izoh sifatida ko'rsatilgan qiymat masala kontekstiga bog'liq).\n\n**2-misol:**\nKiritma: s='aaaa', queries=[[0,1]]\nNatija: [3]",
    starterCodeJs: 'function lcpOfSuffixes(s, queries) {\n  // your code here\n}',
    starterCodePy: 'def lcp_of_suffixes(s, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> lcpOfSuffixes(string& s, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-a-050',
    title: "Ikki Pozitsiyada Tugaydigan Eng Uzun Umumiy Qism Satr",
    difficulty: 'MASTER',
    points: 250,
    tags: ['Satrlar'],
    description: "Uzunligi n bo'lgan satr s (n ≤ 3·10^5) va q ta so'rov (i, j, i≠j) berilgan. Har bir so'rov uchun, i-pozitsiyada tugaydigan va j-pozitsiyada tugaydigan qism satrlar orasida bir xil bo'lgan eng uzun umumiy qism satrning uzunligini toping (ya'ni ikkala pozitsiyada ham 'tugaydigan', teng bo'lgan qism satrlarning maksimal uzunligi). s uchun suffiks avtomat qurib, har bir prefiks s[..i] qaysi avtomat holatiga mos kelishini belgilab, ikkita holatning suffiks-link daraxtidagi eng past umumiy ajdodi (LCA)ning len() qiymati javob ekanligini asoslab, suffiks-link daraxtida binary lifting yordamida har so'rovni O(log n) da yechish kerak.\n\n**1-misol:**\nKiritma: s='abcabc', queries=[[2,5]]\nNatija: [3]\nIzoh: 2-pozitsiyada tugaydigan 'abc' va 5-pozitsiyada tugaydigan 'abc' bir xil, uzunligi 3.\n\n**2-misol:**\nKiritma: s='abcdef', queries=[[0,5]]\nNatija: [0]",
    starterCodeJs: 'function longestCommonSubstringEndingAt(s, queries) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring_ending_at(s, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> longestCommonSubstringEndingAt(string& s, vector<vector<int>>& queries) {\n    // your code here\n}',
  },
];
