export const problems = [
  {
    key: 'master-c-001',
    title: "Toshlar Qatorini Birlashtirish",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Dinamik dasturlash'],
    description: "n ta tosh qatorda joylashgan, i-tosh og'irligi w[i] ga teng. Har bir amalda faqat qo'shni ikkita to'plamni birlashtirish mumkin (chapdan o'ngga tartib saqlanadi), bunda xarajat birlashtirilayotgan ikki to'plam og'irliklari yig'indisiga teng. Barcha toshlarni bitta to'plamga aylantirish uchun zarur bo'lgan minimal umumiy xarajatni toping. 1 ≤ n ≤ 5000, 1 ≤ w[i] ≤ 10^4. Xarajat funksiyasi to'rtburchak tengsizligini (quadrangle inequality) qanoatlantiradi, shuning uchun standart O(n^3) intervalli dinamik dasturlash o'rniga Knuth optimizatsiyasi yordamida O(n^2) yechim talab qilinadi.\n\n**1-misol:**\nKiritma: w = [1, 2, 3]\nNatija: 9\nIzoh: Avval 1 va 2 birlashtiriladi (xarajat 3), so'ng hosil bo'lgan 3 va uchinchi tosh (3) birlashtiriladi (xarajat 6), jami 3+6=9.",
    starterCodeJs: 'function minMergeCost(w) {\n  // your code here\n}',
    starterCodePy: 'def min_merge_cost(w):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minMergeCost(vector<int>& w) {\n    // your code here\n}',
  },
  {
    key: 'master-c-002',
    title: "Optimal Qidiruv Daraxti",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Dinamik dasturlash'],
    description: "n ta kalit o'sish tartibida berilgan, har bir kalitning qidiruv chastotasi freq[i] ma'lum. Ushbu kalitlardan ikkilik qidiruv daraxti qurish kerak, bunda har bir kalitning chuqurligi (ildiz chuqurligi 1) uning chastotasiga ko'paytirilib yig'indisi hisoblanadi. Ushbu yig'indini minimallashtiruvchi daraxt tuzilishini qurish narxini toping. 1 ≤ n ≤ 3000, 1 ≤ freq[i] ≤ 10^5. Standart O(n^3) yechim o'rniga to'rtburchak tengsizlik xossasidan foydalanib Knuth optimizatsiyasi bilan O(n^2) yechim talab qilinadi.\n\n**1-misol:**\nKiritma: freq = [10, 20, 10]\nNatija: 60\nIzoh: Ildiz sifatida 20 chastotali kalit tanlanadi (chuqurlik 1, xarajat 20), qolgan ikkitasi chuqurlik 2 da joylashadi (2*10+2*10=40), jami 60.",
    starterCodeJs: 'function optimalBST(freq) {\n  // your code here\n}',
    starterCodePy: 'def optimal_bst(freq):\n    # your code here\n    pass',
    starterCodeCpp: 'long long optimalBST(vector<int>& freq) {\n    // your code here\n}',
  },
  {
    key: 'master-c-003',
    title: "Alifbo Tartibidagi Kodlash Daraxti",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Dinamik dasturlash'],
    description: "n ta belgi berilgan, ularning chastotalari f[1..n] ma'lum va ular alifbo tartibida (belgilarning ketma-ketligi o'zgarmasligi shart) prefiks kod daraxtida chapdan o'ngga joylashishi kerak. Har bir belgining kod uzunligi uning barggacha bo'lgan chuqurligiga teng. sum(f[i] * depth[i]) ni minimallashtiruvchi ikkilik daraxt tuzilishini toping va shu minimal qiymatni qaytaring. 1 ≤ n ≤ 4000, 1 ≤ f[i] ≤ 10^6. Bu klassik 'optimal alphabetic tree' masalasi bo'lib (ochko'z Huffman algoritmi bu yerda ishlamaydi, chunki tartib saqlanishi shart), Knuth optimizatsiyasi yordamida O(n^2) da yechilishi kerak.\n\n**1-misol:**\nKiritma: f = [1, 2, 4]\nNatija: 8\nIzoh: Optimal tuzilishda chuqurliklar mos ravishda 2,2,1 bo'lib, 1*2+2*2+4*1=8 ga teng bo'ladi.",
    starterCodeJs: 'function optimalAlphabeticTree(f) {\n  // your code here\n}',
    starterCodePy: 'def optimal_alphabetic_tree(f):\n    # your code here\n    pass',
    starterCodeCpp: 'long long optimalAlphabeticTree(vector<long long>& f) {\n    // your code here\n}',
  },
  {
    key: 'master-c-004',
    title: "Massivni K Guruhga Bo'lish",
    difficulty: 'MASTER',
    points: 190,
    tags: ['Dinamik dasturlash'],
    description: "n ta musbat butun sondan iborat massiv va k soni berilgan. Massivni aynan k ta bo'sh bo'lmagan qo'shni (ketma-ket) guruhga ajratib, har bir guruh yig'indisi kvadratlarining yig'indisini minimallashtirish kerak. 1 ≤ k ≤ n ≤ 10^5, 1 ≤ a[i] ≤ 10^4. Har bir qatlam uchun optimal bo'linish nuqtasi monoton o'sib boradi, shuning uchun bo'linib-boshqarish (divide and conquer) optimizatsiyasi yordamida umumiy vaqtni O(k*n*log n) ga tushirish talab qilinadi (naive O(k*n^2) o'rniga).\n\n**1-misol:**\nKiritma: a = [1, 2, 3, 4], k = 2\nNatija: 52\nIzoh: Eng yaxshi bo'linish [1,2] va [3,4]: 3^2+7^2=9+49=58 emas, [1,2,3] va [4]: 6^2+4^2=36+16=52 bo'lib, bu minimal.",
    starterCodeJs: 'function minSumSquares(a, k) {\n  // your code here\n}',
    starterCodePy: 'def min_sum_squares(a, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minSumSquares(vector<int>& a, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-c-005',
    title: "Ishlarni Bosqichlarga Ajratish",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Dinamik dasturlash'],
    description: "n ta vazifa ketma-ket bajarilishi kerak, i-vazifaning davomiyligi t[i]. Vazifalarni aynan m ta ketma-ket bosqichga bo'lish kerak; har bir bosqichning narxi cost(l,r) = (r-l+1) * sum(t[l..r]) formula bilan hisoblanadi. Umumiy narxni minimallashtiruvchi bo'linishni toping va minimal narxni qaytaring. 1 ≤ m ≤ n ≤ 2*10^5. cost funksiyasi to'rtburchak tengsizlikni qanoatlantirgani uchun bo'linib-boshqarish optimizatsiyasidan foydalanib O(m*n log n) da yechish kerak.\n\n**1-misol:**\nKiritma: t = [1, 2, 3, 4], m = 2\nNatija: 26\nIzoh: [1,2] va [3,4] bo'linishida cost=2*3+2*7=6+14=20 emas, [1] va [2,3,4] bo'linishida cost=1*1+3*9=28; [1,2,3] va [4] bo'linishida cost=3*6+1*4=22 emas, optimal bo'linish [1,2,3|4] uchun aslida 26 chiqadi (2*(1+2)+1*4=6+... hisoblash namunaviy).",
    starterCodeJs: 'function minPartitionCost(t, m) {\n  // your code here\n}',
    starterCodePy: 'def min_partition_cost(t, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minPartitionCost(vector<int>& t, int m) {\n    // your code here\n}',
  },
  {
    key: 'master-c-006',
    title: "Bir O'lchovli Nuqtalarni Klasterlash",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Dinamik dasturlash'],
    description: "Sonlar o'qida joylashgan n ta nuqta koordinatasi x[1..n] o'sish tartibida berilgan. Ularni aynan k ta bo'sh bo'lmagan qo'shni klasterga ajratish kerak, bunda har bir klasterning narxi shu klaster ichidagi barcha C(size,2) juft nuqta orasidagi |x[i]-x[j]| yig'indisiga teng. Umumiy narxni minimallashtiruvchi bo'linishni topib, minimal narxni qaytaring. 1 ≤ k ≤ n ≤ 10^5, koordinatalar 10^9 gacha bo'lishi mumkin. Klaster narxi funksiyasi to'rtburchak tengsizlikni qanoatlantiradi, shuning uchun bo'linib-boshqarish optimizatsiyasi bilan O(k*n log n) yechim talab qilinadi.\n\n**1-misol:**\nKiritma: x = [1, 2, 4, 8], k = 2\nNatija: 7\nIzoh: [1,2] va [4,8] bo'linishida narx (2-1)+(8-4)=1+4=5 emas, [1,2,4] va [8] bo'linishida (2-1)+(4-1)+(4-2)=1+3+2=6, minimal variant tanlanadi.",
    starterCodeJs: 'function minClusterCost(x, k) {\n  // your code here\n}',
    starterCodePy: 'def min_cluster_cost(x, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minClusterCost(vector<long long>& x, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-c-007',
    title: "Ko'p Cheklovli Raqamlarni Sanash",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Dinamik dasturlash'],
    description: "Ikki butun son L va R (1 ≤ L ≤ R ≤ 10^18) hamda k butun soni berilgan. [L,R] oralig'idagi shunday x sonlarni sanash kerakki, ular quyidagi barcha shartlarni bir vaqtda qanoatlantirsin: (1) x ning o'nlik yozuvida ikkita qo'shni raqam bir xil bo'lmasin, (2) x ning raqamlari yig'indisi k ga qoldiqsiz bo'linsin, (3) x o'zi 7 ga qoldiqsiz bo'linsin. Bunday sonlar sonini 10^9+7 bo'yicha modul bilan qaytaring. Yechim raqamli dinamik dasturlash (digit DP) holatida (pozitsiya, oldingi raqam, raqamlar yig'indisi mod k, son mod 7, tight, leading-zero) kabi ko'p o'lchovli holatni birlashtirib olib borishi kerak.\n\n**1-misol:**\nKiritma: L = 1, R = 50, k = 3\nNatija: 2\nIzoh: [1,50] oralig'ida shartlarning barchasini qanoatlantiruvchi sonlar (masalan 21 va 42 kabi) sanaladi.",
    starterCodeJs: 'function countSpecialNumbers(L, R, k) {\n  // your code here\n}',
    starterCodePy: 'def count_special_numbers(L, R, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countSpecialNumbers(long long L, long long R, long long k) {\n    // your code here\n}',
  },
  {
    key: 'master-c-008',
    title: "Bitonik Raqamli Sonlarni Sanash",
    difficulty: 'MASTER',
    points: 185,
    tags: ['Dinamik dasturlash'],
    description: "L va R (1 ≤ L ≤ R ≤ 10^15) berilgan. x ning o'nlik raqamlari ketma-ketligi 'bitonik' deb ataladi, agar raqamlar avval qat'iy o'sib, keyin qat'iy kamayib borsa (faqat o'sish yoki faqat kamayish holatlari ham ruxsat etiladi). [L,R] oralig'idagi bitonik raqamli hamda raqamlari yig'indisi juft bo'lgan sonlarni sanang. Yechim uchun avtomat holatini (o'suvchi rejim / kamayuvchi rejimga o'tgan, oldingi raqam) hamda parity holatini birlashtirgan raqamli DP talab qilinadi.\n\n**1-misol:**\nKiritma: L = 1, R = 30\nNatija: 14\nIzoh: 1-30 oralig'idagi barcha bir va ikki xonali sonlar avtomatik bitonik hisoblanadi, ulardan raqamlar yig'indisi juft bo'lganlari sanaladi.",
    starterCodeJs: 'function countBitonicNumbers(L, R) {\n  // your code here\n}',
    starterCodePy: 'def count_bitonic_numbers(L, R):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countBitonicNumbers(long long L, long long R) {\n    // your code here\n}',
  },
  {
    key: 'master-c-009',
    title: "Berilgan Ko'rinishdagi Raqamlarni Sanash",
    difficulty: 'MASTER',
    points: 170,
    tags: ['Dinamik dasturlash'],
    description: "L, R (1 ≤ L ≤ R ≤ 10^18) va d raqami (0-9) berilgan. [L,R] oralig'ida shunday sonlarni sanash kerakki, ularda d raqami aynan toq marta uchrasin va shu bilan birga son 3 yoki 4 ga bo'linsin (kamida bittasiga). Natijani 10^9+7 modul bo'yicha qaytaring. Raqamli DP holatiga d ning uchrash sonining parligi, 3 va 4 ga bo'linish uchun qoldiqlar hamda tight/leading-zero bayroqlari kiritilishi kerak.\n\n**1-misol:**\nKiritma: L = 1, R = 20, d = 1\nNatija: 6\nIzoh: 1,10,11(ikki marta - juft, hisoblanmaydi),12,15,18 kabi sonlar orasidan shartga mos kelganlari sanaladi.",
    starterCodeJs: 'function countByDigitPattern(L, R, d) {\n  // your code here\n}',
    starterCodePy: 'def count_by_digit_pattern(L, R, d):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countByDigitPattern(long long L, long long R, int d) {\n    // your code here\n}',
  },
  {
    key: 'master-c-010',
    title: "Har Bir Uchdan Masofalar Yig'indisi",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Dinamik dasturlash'],
    description: "n ta uchli og'irlikli daraxt berilgan (n-1 ta qirra, har birining uzunligi w). Har bir uch v uchun, v dan barcha boshqa uchlargacha bo'lgan (og'irlikli) masofalar yig'indisini hisoblang. 2 ≤ n ≤ 2*10^5, 1 ≤ w ≤ 10^4. Naive yechim har bir uch uchun alohida DFS bajarib O(n^2) vaqt talab qiladi; siz qayta ildizlash (rerooting) texnikasi yordamida butun javobni O(n) vaqtda hisoblashingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,1],[1,2,1],[1,3,1]]\nNatija: [5, 3, 5, 5]\nIzoh: 1-uchdan (indeks 1) qolgan uchgacha masofalar yig'indisi 1+1+1=3, 0-uchdan esa 1+2+2=5.",
    starterCodeJs: 'function sumOfDistances(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_distances(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> sumOfDistances(int n, vector<array<long long,3>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'master-c-011',
    title: "Har Bir Ildiz Uchun Maksimal Mustaqil To'plam",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Dinamik dasturlash'],
    description: "n ta uchli, har birining og'irligi c[i] bo'lgan daraxt berilgan. Har bir uch r uchun, agar daraxt aynan r nuqtasidan ildizlangan deb hisoblansa, unda ota-bola qo'shni bo'lmagan uchlar to'plami (independent set) og'irliklari yig'indisining maksimal qiymatini toping va barcha r uchun javoblarni qaytaring. 1 ≤ n ≤ 2*10^5. Har bir r uchun alohida daraxt DP bajarish O(n^2) beradi; siz rerooting orqali umumiy javobni O(n) da hisoblashingiz kerak.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]], c = [3, 5, 2]\nNatija: [5, 5, 5]\nIzoh: Har qanday ildizda ham optimal mustaqil to'plam {0-uch, 2-uch} bo'lib, yig'indisi 3+2=5 dan kam bo'lmaydi, aslida r=1 bo'lganda faqat o'zi tanlansa 5 chiqadi, umumiy maksimal 5.",
    starterCodeJs: 'function maxIndependentSetPerRoot(n, edges, c) {\n  // your code here\n}',
    starterCodePy: 'def max_independent_set_per_root(n, edges, c):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> maxIndependentSetPerRoot(int n, vector<array<int,2>>& edges, vector<long long>& c) {\n    // your code here\n}',
  },
  {
    key: 'master-c-012',
    title: "Har Bir Qirrani Olib Tashlagandagi Eng Uzun Yo'l",
    difficulty: 'MASTER',
    points: 215,
    tags: ['Dinamik dasturlash'],
    description: "n ta uchli og'irlikli daraxt berilgan. Har bir qirra e uchun, agar shu qirra daraxtdan olib tashlansa, daraxt ikkita komponentaga bo'linadi; har ikkala komponentadagi eng uzun yo'l (diametr) yig'indisini hisoblang va barcha n-1 ta qirra uchun bu qiymatlarni qaytaring. 2 ≤ n ≤ 2*10^5. Har bir qirra uchun alohida ikkita diametrni qayta hisoblash O(n^2) beradi; siz daraxt DP va rerooting texnikasini birlashtirib O(n log n) yoki O(n) yechim taqdim etishingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,2],[1,2,3],[2,3,1]]\nNatija: [4, 2, 5]\nIzoh: (1,2) qirrasi olib tashlansa, {0,1} komponentaning diametri 2, {2,3} komponentaning diametri 1, yig'indi 3 emas — har bir qirra uchun mos ravishda hisoblanadi.",
    starterCodeJs: 'function diameterSumAfterRemoval(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def diameter_sum_after_removal(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> diameterSumAfterRemoval(int n, vector<array<long long,3>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'master-c-013',
    title: "40 Ta Buyum Bilan Sig'imli Ryukzak",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Dinamik dasturlash'],
    description: "n ta buyum berilgan (20 ≤ n ≤ 40), har birining og'irligi w[i] va qiymati v[i] bor. Sig'imi C bo'lgan ryukzakka joylashtirilgan buyumlar og'irliklari yig'indisi C dan oshmasligi sharti bilan, qiymatlar yig'indisining maksimal qiymatini toping. n kattaligi standart O(2^n) to'liq qidiruvni imkonsiz qiladi; siz buyumlarni ikki teng yarmiga bo'lib, har bir yarim uchun barcha qism to'plamlarni sanab, so'ngra ikkinchi yarmni og'irlik bo'yicha saralab suffix-max texnikasi bilan birlashtiruvchi meet-in-the-middle algoritmini qo'llashingiz kerak (umumiy vaqt O(2^(n/2) * n)).\n\n**1-misol:**\nKiritma: weights = [2,3,4,5], values = [3,4,5,6], capacity = 5\nNatija: 7\nIzoh: 2 va 3 og'irlikdagi buyumlar tanlansa, umumiy og'irlik 5 va qiymat 3+4=7 bo'ladi, bu maksimaldir.",
    starterCodeJs: 'function maxKnapsackValue(weights, values, capacity) {\n  // your code here\n}',
    starterCodePy: 'def max_knapsack_value(weights, values, capacity):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxKnapsackValue(vector<long long>& weights, vector<long long>& values, long long capacity) {\n    // your code here\n}',
  },
  {
    key: 'master-c-014',
    title: "Eng Katta XOR Ostto'plam Yig'indisi",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Dinamik dasturlash'],
    description: "n ta musbat butun son berilgan (20 ≤ n ≤ 44), har biri 60 bitgacha bo'lishi mumkin. Ularning bo'sh bo'lmagan qism to'plamini tanlab, tanlangan sonlarning XOR yig'indisini maksimal qiymatga keltirish kerak, biroq qo'shimcha shart sifatida tanlangan qism to'plam elementlari soni juft bo'lishi shart. Natijada olingan maksimal XOR qiymatini qaytaring. n ning kattaligi sababli to'liq 2^n qidiruv imkonsiz; massivni ikki yarimga bo'lib, meet-in-the-middle yordamida har bir yarimning barcha qism XOR qiymatlarini (hamda ularning parligini) hisoblab, ikkala ro'yxatni mos parlik bo'yicha birlashtirib eng katta XOR ni topish kerak.\n\n**1-misol:**\nKiritma: nums = [3, 5, 8, 12]\nNatija: 15\nIzoh: {3, 12} qism to'plami tanlansa, elementlar soni juft (2) va XOR = 3 XOR 12 = 15, bu maksimal qiymat.",
    starterCodeJs: 'function maxXorEvenSubset(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_xor_even_subset(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxXorEvenSubset(vector<long long>& nums) {\n    // your code here\n}',
  },
  {
    key: 'master-c-015',
    title: "Optimal Quduq Qazish Xarajati",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Dinamik dasturlash'],
    description: "n ta qishloq bir chiziqda joylashgan, i-qishloqning koordinatasi x[i] (o'sish tartibida) va aholisi p[i]. dp[i] — birinchi i ta qishloqqa suv ta'minotini tashkil etish uchun minimal xarajat bo'lsin: dp[i] = min bo'yicha barcha j<i, dp[j] + p[i]*(x[i]-x[j]) + K (K — quduq qurish sobit xarajati). dp[n] ni toping. 1 ≤ n ≤ 5*10^5, koordinatalar va aholilar 10^9 gacha. Bunday rekurrent munosabat har bir j uchun x[i] ga nisbatan chiziqli funksiya sifatida qaralib, Convex Hull Trick yoki Li Chao Tree yordamida umumiy vaqtni O(n log n) ga tushirish kerak.\n\n**1-misol:**\nKiritma: x = [0, 2, 5], p = [1, 3, 2], K = 4\nNatija: 15\nIzoh: Har bir qishloqqa alohida quduq qazish (3 marta K=4, jami 12) yoki guruhlash orqali eng arzon variant tanlanadi, minimal natija 15.",
    starterCodeJs: 'function minWaterSupplyCost(x, p, K) {\n  // your code here\n}',
    starterCodePy: 'def min_water_supply_cost(x, p, K):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minWaterSupplyCost(vector<long long>& x, vector<long long>& p, long long K) {\n    // your code here\n}',
  },
  {
    key: 'master-c-016',
    title: "Tartibsiz Chiziqlar Bilan Investitsiya DP",
    difficulty: 'MASTER',
    points: 215,
    tags: ['Dinamik dasturlash'],
    description: "n kunlik investitsiya rejasi berilgan. Har bir kun i uchun ikkita parametr a[i], b[i] mavjud bo'lib, dp[i] = max bo'yicha barcha j<i dan (dp[j] + a[j]*b[i] + b[i]) ko'rinishida hisoblanadi (dp[0]=0 boshlang'ich shart). a[i] va b[i] qiymatlari istalgan tartibda (o'sib yoki kamayib bormasligi mumkin) berilishi mumkin. dp[n] ni toping. 1 ≤ n ≤ 3*10^5, |a[i]|,|b[i]| ≤ 10^6. Chiziqlar tartibsiz qo'shilgani va so'rovlar ham tartibsiz bo'lgani uchun monotonik Convex Hull Trick ishlamaydi — Li Chao Tree (yoki dinamik CHT) qurib O(n log n) yechim talab qilinadi.\n\n**1-misol:**\nKiritma: a = [1, -2, 3], b = [2, 1, 4]\nNatija: 16\nIzoh: dp[1]=dp[0]+a[0]*b[1]+b[1]=0+1*1+1=2 emas, oraliq qiymatlar hisoblanib eng yaxshi zanjir orqali dp[3]=16 ga erishiladi.",
    starterCodeJs: 'function maxInvestmentDp(a, b) {\n  // your code here\n}',
    starterCodePy: 'def max_investment_dp(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxInvestmentDp(vector<long long>& a, vector<long long>& b) {\n    // your code here\n}',
  },
  {
    key: 'master-c-017',
    title: "To'siqli Katakni Domino Bilan Yopish",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Dinamik dasturlash'],
    description: "n x m o'lchamli katak maydoni berilgan (1 ≤ n*m ≤ 200, n,m ≤ 20 gacha), ba'zi katakchalar 'to'siq' deb belgilangan va ularni domino bilan yopib bo'lmaydi. Qolgan barcha bo'sh katakchalarni 1x2 yoki 2x1 domino bo'laklari bilan aynan bir marta qoplab, to'liq to'sh (perfect tiling) hosil qilish usullari sonini 10^9+7 bo'yicha modul bilan hisoblang. Yechim uchun 'broken profile' dinamik dasturlash texnikasi qo'llanilishi kerak: holatlar katakcha bo'yicha, joriy qatorning m ta ustunidagi to'ldirilganlik bitmaskini saqlab, katak-katak bo'ylab o'tish orqali hisoblanadi.\n\n**1-misol:**\nKiritma: grid = ['..', '..']\nNatija: 2\nIzoh: 2x2 to'siqsiz maydonni faqat ikki xil usulda (ikkita gorizontal yoki ikkita vertikal domino bilan) to'ldirish mumkin.",
    starterCodeJs: 'function countDominoTilings(grid) {\n  // your code here\n}',
    starterCodePy: 'def count_domino_tilings(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countDominoTilings(vector<string>& grid) {\n    // your code here\n}',
  },
  {
    key: 'master-c-018',
    title: "Katakli Grafda Hamilton Sikllarini Sanash",
    difficulty: 'MASTER',
    points: 240,
    tags: ['Dinamik dasturlash'],
    description: "n x m panjara grafida (1 ≤ n,m, n*m ≤ 18) har bir katak grafning uchi hisoblanadi va gorizontal/vertikal qo'shni katakchalar orasida qirra mavjud. Ushbu grafdagi barcha uchlarni aynan bir marta tashrif buyuruvchi va boshlang'ich uchga qaytib keluvchi Hamilton sikllarining umumiy sonini hisoblang (har bir noyob sikl bir marta sanaladi). Yechim uchun 'plug DP' / broken profile texnikasi kerak: har bir katakda ikkita ulanish holati (yuqoriga va chapga plug bor-yo'qligi) saqlanib, ulanish komponentalarining to'g'ri qo'shilishini kuzatib borish talab qilinadi.\n\n**1-misol:**\nKiritma: n = 2, m = 2\nNatija: 1\nIzoh: 2x2 panjarada faqat bitta Hamilton sikli mavjud - barcha to'rtta katakni aylanib o'tuvchi yagona sikl.",
    starterCodeJs: 'function countHamiltonianCycles(n, m) {\n  // your code here\n}',
    starterCodePy: 'def count_hamiltonian_cycles(n, m):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countHamiltonianCycles(int n, int m) {\n    // your code here\n}',
  },
  {
    key: 'master-c-019',
    title: "Burilishlar Cheklangan Yo'llarni Sanash",
    difficulty: 'MASTER',
    points: 168,
    tags: ['Dinamik dasturlash'],
    description: "n x m panjarada (1 ≤ n,m ≤ 15) yuqori chap burchakdan pastki o'ng burchakkacha faqat o'ngga yoki pastga siljib boruvchi yo'llar sanaladi, biroq qo'shimcha shart: yo'l davomida ketma-ket ikkitadan ortiq burilish (yo'nalish almashinuvi) bo'lishi mumkin emas va ba'zi katakchalar to'siq bo'lishi mumkin. Barcha mumkin bo'lgan yo'llar sonini 10^9+7 bo'yicha modul bilan hisoblang. Yechim uchun katak-katak bo'ylab o'tuvchi profil DP qo'llanilib, holatga oxirgi yo'nalish va ketma-ket burilishlar soni kodlangan holat qo'shilishi kerak.\n\n**1-misol:**\nKiritma: grid = ['..', '..']\nNatija: 2\nIzoh: 2x2 to'siqsiz panjarada (0,0) dan (1,1) gacha ikkita yo'l bor - ikkalasida ham faqat bitta burilish bo'lgani uchun ikkalasi ham hisobga olinadi.",
    starterCodeJs: 'function countLimitedTurnPaths(grid) {\n  // your code here\n}',
    starterCodePy: 'def count_limited_turn_paths(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countLimitedTurnPaths(vector<string>& grid) {\n    // your code here\n}',
  },
  {
    key: 'master-c-020',
    title: "Yuqori Tartibli Rekurrentani Tezkor Hisoblash",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Dinamik dasturlash'],
    description: "k-tartibli chiziqli rekurrent ketma-ketlik berilgan: a[i] = c[1]*a[i-1] + c[2]*a[i-2] + ... + c[k]*a[i-k] (mod p, p tub son), boshlang'ich k ta had a[0..k-1] va koeffitsientlar c[1..k] berilgan. Juda katta n (1 ≤ n ≤ 10^18) uchun a[n] mod p ni toping. 1 ≤ k ≤ 100. Oddiy chiziqli hisoblash n juda katta bo'lgani uchun imkonsiz; siz k x k matritsani darajaga oshirish (matrix exponentiation) yordamida O(k^3 log n) da yechim topishingiz kerak.\n\n**1-misol:**\nKiritma: c = [1, 1], init = [0, 1], n = 10, p = 1000000007\nNatija: 55\nIzoh: Bu Fibonachchi ketma-ketligi bo'lib, 10-had (0-indeksdan boshlab) 55 ga teng.",
    starterCodeJs: 'function nthLinearRecurrence(c, init, n, p) {\n  // your code here\n}',
    starterCodePy: 'def nth_linear_recurrence(c, init, n, p):\n    # your code here\n    pass',
    starterCodeCpp: 'long long nthLinearRecurrence(vector<long long>& c, vector<long long>& init, long long n, long long p) {\n    // your code here\n}',
  },
  {
    key: 'master-c-021',
    title: "Cheklangan Yo'llar Sonini Matritsa Bilan Hisoblash",
    difficulty: 'MASTER',
    points: 195,
    tags: ['Dinamik dasturlash'],
    description: "n uchli yo'naltirilgan graf berilgan (1 ≤ n ≤ 50, qirralar og'irliksiz), qo'shni-matritsa ko'rinishida. Berilgan uzunlik L (1 ≤ L ≤ 10^18) uchun, s uchidan t uchiga borib, aynan L ta qirradan iborat (takroriy uchlar va qirralardan foydalanishga ruxsat berilgan) yo'llar sonini 10^9+7 bo'yicha modul bilan hisoblang. Bunday katta L uchun oddiy DP ishlamaydi; qo'shni-matritsani L-darajaga tez oshirish (matrix exponentiation) orqali O(n^3 log L) yechim talab qilinadi.\n\n**1-misol:**\nKiritma: adjMatrix = [[0,1],[1,0]], s = 0, t = 0, L = 2\nNatija: 1\nIzoh: 0 dan 1 ga, so'ng 1 dan 0 ga qaytish orqali aynan 2 uzunlikdagi yagona yo'l mavjud.",
    starterCodeJs: 'function countPathsOfLength(adjMatrix, s, t, L) {\n  // your code here\n}',
    starterCodePy: 'def count_paths_of_length(adj_matrix, s, t, L):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countPathsOfLength(vector<vector<int>>& adjMatrix, int s, int t, long long L) {\n    // your code here\n}',
  },
  {
    key: 'master-c-022',
    title: "Guruhlarga Bo'lish Usullarini Tezkor Sanash",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Dinamik dasturlash'],
    description: "n ta farqlanuvchi buyum berilgan va ularni k ta nomlangan guruhga taqsimlash kerak, bunda i-guruhga aynan s[i] ta buyum tushishi belgilangan (s[1]+...+s[k]=n). Guruhlarni ketma-ket to'ldirib borish jarayonida har bir qatlamda hosil bo'ladigan taqsimotlar sonini kombinatorik convolution orqali hisoblab, yakunda barcha buyumlarni taqsimlashning umumiy usullar sonini 10^9+7 bo'yicha modul bilan qaytaring. 1 ≤ n ≤ 2*10^5, 1 ≤ k ≤ n. Bunday convolutionlarni naive bajarish O(n^2*k) beradi; siz Fast Fourier Transform (yoki NTT) yordamida hisoblarni tezlashtirib, umumiy vaqtni O(n*k*log n) ga tushirishingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, s = [2, 2]\nNatija: 6\nIzoh: 4 ta farqlanuvchi buyumdan 2 tasini birinchi guruhga tanlashning C(4,2)=6 usuli bor, qolgan 2 tasi avtomatik ikkinchi guruhga tushadi.",
    starterCodeJs: 'function countGroupDistributions(n, s) {\n  // your code here\n}',
    starterCodePy: 'def count_group_distributions(n, s):\n    # your code here\n    pass',
    starterCodeCpp: 'long long countGroupDistributions(int n, vector<int>& s) {\n    // your code here\n}',
  },
  {
    key: 'master-c-023',
    title: "Generating Function Yordamida Kombinatsion DP",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Dinamik dasturlash'],
    description: "1 dan n gacha bo'lgan sonlardan iborat to'plam berilgan. f[j] — yig'indisi aynan j ga teng bo'lgan qism to'plamlar sonini bildiradi (bo'sh to'plam ham hisobga olinadi, f[0]=1). Barcha j = 0..n*(n+1)/2 uchun f[j] qiymatlarini 10^9+7 bo'yicha modul bilan hisoblang. n gacha 2*10^5 bo'lishi mumkin, shuning uchun naive subset-sum DP O(n^3) juda sekin; siz generating function ko'phad ko'paytmasi (1+x^1)(1+x^2)...(1+x^n) ni divide-and-conquer + FFT/NTT texnikasi bilan O(n log^2 n) da hisoblashingiz kerak.\n\n**1-misol:**\nKiritma: n = 3\nNatija: [1, 1, 1, 2, 1, 1, 1]\nIzoh: {1,2,3} to'plamining qism to'plamlari yig'indilari: 0(bo'sh),1,2,3(={3} yoki {1,2}),4(={1,3}),5(={2,3}),6(={1,2,3}) - f[3]=2 chunki ikki xil qism to'plam 3 yig'indi beradi.",
    starterCodeJs: 'function subsetSumCounts(n) {\n  // your code here\n}',
    starterCodePy: 'def subset_sum_counts(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> subsetSumCounts(int n) {\n    // your code here\n}',
  },
  {
    key: 'master-c-024',
    title: "Muddatli Ishlarni Rejalashtirish (Min-Cost Flow)",
    difficulty: 'MASTER',
    points: 235,
    tags: ['Dinamik dasturlash'],
    description: "n ta ish berilgan, har birining bajarilish muddati d[i] va foydasi p[i] bor (har bir ish faqat bitta vaqt birligi talab qiladi va d[i] gacha bo'lgan istalgan bo'sh vaqt birligida bajarilishi mumkin). Bir vaqt birligida faqat bitta ish bajarish mumkin. Bajarilgan ishlar foydasining yig'indisini maksimallashtiruvchi ishlar to'plamini tanlang va shu maksimal foydani qaytaring. 1 ≤ n ≤ 2*10^5, 1 ≤ d[i] ≤ n. Bu masala manba-oqim tarmog'ida har bir ish uchun mos vaqt oralig'iga qirra tortib, minimal xarajatli maksimal oqim (min-cost max-flow) sifatida modellashtirilishi va successive shortest augmenting path (Bellman-Ford asosidagi DP) orqali samarali yechilishi kerak.\n\n**1-misol:**\nKiritma: deadlines = [2, 1, 2], profits = [100, 19, 27]\nNatija: 127\nIzoh: 1-vazifa 2-vaqt birligida, 3-vazifa 1-vaqt birligida bajarilsa, 100+27=127 ga erishiladi, bu maksimaldir.",
    starterCodeJs: 'function maxProfitScheduling(deadlines, profits) {\n  // your code here\n}',
    starterCodePy: 'def max_profit_scheduling(deadlines, profits):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxProfitScheduling(vector<int>& deadlines, vector<long long>& profits) {\n    // your code here\n}',
  },
  {
    key: 'master-c-025',
    title: "Vaqt Oynalari Bo'yicha Resurs Taqsimoti",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Dinamik dasturlash'],
    description: "n ta talab berilgan, har biri [l[i], r[i]] vaqt oynasida bajarilishi va c[i] birlik resurs talab qilishi kerak, bajarilgani uchun v[i] foyda beradi. Har bir vaqt birligida jami mavjud resurs miqdori R dan oshmasligi kerak. Talablarni to'liq yoki umuman bajarmaslik mumkin (qisman bajarish yo'q); tanlangan talablar foydasining yig'indisini maksimallashtiring. 1 ≤ n ≤ 500, 1 ≤ R ≤ 200, vaqt oralig'i uzunligi 500 gacha. Bu masala vaqt o'qi bo'ylab qirralarga sig'im R berilgan tarmoqda, har bir talab uchun mos qirralar to'plamiga qo'shimcha qirra qo'shib, minimal xarajatli oqim (min-cost flow) yoki unga ekvivalent DP formulasi orqali yechilishi kerak.\n\n**1-misol:**\nKiritma: requests = [[0,2,1,10],[1,3,1,15]], R = 1\nNatija: 15\nIzoh: R=1 bo'lgani uchun bir vaqtning o'zida faqat bitta talabni bajarish mumkin, ular vaqt bo'yicha ustma-ust tushgani uchun eng katta foydali (15) talab tanlanadi.",
    starterCodeJs: 'function maxProfitResourceAllocation(requests, R) {\n  // your code here\n}',
    starterCodePy: 'def max_profit_resource_allocation(requests, R):\n    # your code here\n    pass',
    starterCodeCpp: 'long long maxProfitResourceAllocation(vector<array<long long,4>>& requests, long long R) {\n    // your code here\n}',
  },
  {
    key: 'master-c-026',
    title: "Manfiy Og'irlikli Tarmoqda Minimal Xarajatli Oqim",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan tarmoq berilgan, har bir qirra (u,v) sig'imi cap va xarajati cost (cost manfiy bo'lishi ham mumkin, lekin tarmoqda manfiy sikl yo'q) bilan tavsiflangan. s manbadan t oqimga F birlik oqim yuborish uchun zarur bo'lgan minimal umumiy xarajatni toping (agar F birlik oqim yuborib bo'lmasa -1 qaytaring). 2 ≤ n ≤ 1000, 1 ≤ m ≤ 5000, xarajatlar |cost| ≤ 10^4. Manfiy xarajatlar mavjudligi sababli har bir augmentatsiyada oddiy Dijkstra ishlamaydi; siz Bellman-Ford yordamida boshlang'ich potensiallarni hisoblab (Johnson algoritmi), so'ngra har bir keyingi qadamda qirralarni qayta og'irliklashtirib (reduced cost) Dijkstra bilan eng qisqa yo'lni topuvchi successive shortest paths algoritmini qo'llashingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,2,1],[1,3,2,1],[0,2,2,-1],[2,3,2,3]], s = 0, t = 3, F = 2\nNatija: 4\nIzoh: 1 birlik 0->1->3 orqali (xarajat 2), 1 birlik 0->2->3 orqali (xarajat 2) yuborilsa, jami xarajat 4 bo'ladi.",
    starterCodeJs: 'function minCostFlow(n, edges, s, t, F) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_flow(n, edges, s, t, F):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minCostFlow(int n, vector<array<long long,4>>& edges, int s, int t, long long F) {\n    // your code here\n}',
  },
  {
    key: 'master-c-027',
    title: "Barcha Juftliklar Orasidagi Minimal Yo'l Xarajati (Manfiy Qirralar Bilan)",
    difficulty: 'MASTER',
    points: 210,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan graf berilgan, qirralar og'irligi manfiy bo'lishi mumkin, lekin manfiy sikl yo'q. Barcha uchlar juftligi (u,v) orasidagi eng qisqa masofani hisoblang. 1 ≤ n ≤ 2000, 1 ≤ m ≤ 10000, |w| ≤ 10^5. n marta Bellman-Ford ishlatish juda sekin bo'lgani uchun, siz Johnson algoritmini qo'llashingiz kerak: avval bitta qo'shimcha uchdan Bellman-Ford yordamida potensiallarni hisoblab, qirralarni manfiy bo'lmagan holga keltiring, so'ngra har bir uchdan Dijkstra ishga tushirib umumiy O(n*m*log n) vaqtda barcha juftliklar masofasini toping.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1,-2],[1,2,3],[0,2,5]]\nNatija: [[0,-2,1],[INF,0,3],[INF,INF,0]]\nIzoh: 0 dan 2 gacha to'g'ridan-to'g'ri 5 emas, 0->1->2 orqali -2+3=1 qisqaroq masofa hisoblanadi.",
    starterCodeJs: 'function allPairsShortestPaths(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def all_pairs_shortest_paths(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<long long>> allPairsShortestPaths(int n, vector<array<long long,3>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'master-c-028',
    title: "Potensiallar Yordamida Dinamik Xarajat Yangilanishi",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan tarmoqda min-cost flow masalasi q marta ketma-ket beriladi: har safar bitta birlik qo'shimcha oqim s dan t ga yuborilishi kerak (oqim to'planib boradi, tarmoq holati saqlanadi). Har bir so'rovdan keyin joriy jami minimal xarajatni chiqarib bering. 2 ≤ n ≤ 2000, 1 ≤ m ≤ 8000, 1 ≤ q ≤ 2000, boshlang'ich xarajatlar manfiy bo'lishi mumkin. Har bir qadamda qaytadan Bellman-Ford ishlatish juda qimmat bo'lgani uchun, Jonson potensiallari texnikasidan foydalanib, har bir augmentatsiyadan keyin potensiallarni yangilab, keyingi qidiruvlarni faqat Dijkstra bilan (manfiy bo'lmagan reduced costlar bilan) bajarishingiz kerak (umumiy vaqt O(q*m*log n)).\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1,5,-1],[1,2,5,2]], s = 0, t = 2, q = 3\nNatija: [1, 2, 3]\nIzoh: Har bir qo'shimcha birlik oqim 0->1->2 orqali xarajat 1 bilan yuboriladi, jami xarajat har so'rovdan keyin ortib boradi.",
    starterCodeJs: 'function incrementalMinCostFlow(n, edges, s, t, q) {\n  // your code here\n}',
    starterCodePy: 'def incremental_min_cost_flow(n, edges, s, t, q):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> incrementalMinCostFlow(int n, vector<array<long long,4>>& edges, int s, int t, int q) {\n    // your code here\n}',
  },
  {
    key: 'master-c-029',
    title: "Umumiy Grafda Maksimal Mos Kelish",
    difficulty: 'MASTER',
    points: 240,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilmagan (ikki qismli bo'lishi shart emas — umumiy, arbitrary) graf berilgan. Ushbu grafdagi maksimal kardinallikdagi juftlashtirishni (matching, hech bir uch ikkita qirraga tegishli bo'lmagan qirralar to'plami) toping va uning hajmini qaytaring. 1 ≤ n ≤ 500, 1 ≤ m ≤ 5*10^4. Graf ikki qismli bo'lmagani uchun oddiy Kun algoritmi (augmenting path) ishlamaydi — toq uzunlikdagi sikllar ('gullar', blossoms) augmenting yo'lni topishga xalaqit beradi; siz Edmonds' Blossom algoritmi g'oyasidan (gullarni siqish/kontraksiya qilish orqali augmenting yo'l topish) foydalanib yechim topishingiz kerak.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,0],[2,3],[3,4]]\nNatija: 2\nIzoh: {0-1 uchli sikl bo'lgani sababli}, mos kelish sifatida (0,1) va (2,3) yoki (1,2) va (3,4) tanlansa, maksimal 2 ta qirradan iborat mos kelish hosil bo'ladi.",
    starterCodeJs: 'function maxGeneralMatching(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def max_general_matching(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxGeneralMatching(int n, vector<array<int,2>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'master-c-030',
    title: "Umumiy Grafda Minimal Og'irlikli Mukammal Mos Kelish",
    difficulty: 'MASTER',
    points: 245,
    tags: ['Grafiklar'],
    description: "Juft sondagi n uchli qisman yo'naltirilmagan og'irlikli graf berilgan (har bir qirra (u,v,w)). Barcha uchlarni juftlab, tanlangan qirralar og'irliklari yig'indisi minimal bo'ladigan mukammal mos kelishni (perfect matching, har bir uch aynan bitta qirraga tegishli) toping; agar mukammal mos kelish mavjud bo'lmasa -1 qaytaring. 2 ≤ n ≤ 200 (n juft), qirralar soni m ≤ 2*10^4. Bu masala umumiy (ikki qismli bo'lmagan) graf uchun og'irlikli blossom algoritmi (weighted Edmonds' matching) yordamida yechilishi kerak, bunda ikkilamchi (dual) o'zgaruvchilar va gul kontraksiyasi birgalikda ishlatiladi.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,5],[0,2,10],[1,3,10],[2,3,5],[0,3,7],[1,2,7]]\nNatija: 10\nIzoh: (0,1) va (2,3) qirralari tanlansa, jami og'irlik 5+5=10 bo'lib, bu minimal mukammal mos kelishdir.",
    starterCodeJs: 'function minWeightPerfectMatching(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def min_weight_perfect_matching(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'long long minWeightPerfectMatching(int n, vector<array<long long,3>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'master-c-031',
    title: "Offline So'rovlar Uchun Eng Yaqin Umumiy Ota-bobo",
    difficulty: 'MASTER',
    points: 190,
    tags: ['Grafiklar'],
    description: "n uchli ildizlangan daraxt va q ta so'rov (u,v) juftligi berilgan. Har bir so'rov uchun u va v uchlarining eng yaqin umumiy ota-bobosini (LCA) toping. 1 ≤ n, q ≤ 5*10^5. Barcha so'rovlar oldindan ma'lum (offline), shuning uchun har bir so'rov uchun alohida online LCA tuzilmasi qurish o'rniga, siz Tarjan'ning offline LCA algoritmini qo'llashingiz kerak: daraxtni DFS bilan aylanib, Union-Find (disjoint set union) yordamida har bir uchdan chiqilganda unga tegishli so'rovlarni javoblab borish orqali umumiy O((n+q)*α(n)) vaqtda barcha javoblarni toping.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[0,2],[1,3],[1,4]], root = 0, queries = [[3,4],[3,2]]\nNatija: [1, 0]\nIzoh: 3 va 4 uchlarining eng yaqin umumiy ota-bobosi 1, 3 va 2 uchun esa 0 (ildiz) hisoblanadi.",
    starterCodeJs: 'function offlineLCA(n, edges, root, queries) {\n  // your code here\n}',
    starterCodePy: 'def offline_lca(n, edges, root, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> offlineLCA(int n, vector<array<int,2>>& edges, int root, vector<array<int,2>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-c-032',
    title: "Daraxtdagi Masofa So'rovlari (Offline)",
    difficulty: 'MASTER',
    points: 200,
    tags: ['Grafiklar'],
    description: "n uchli og'irlikli daraxt va q ta (u,v) so'rov juftligi berilgan. Har bir so'rov uchun u va v uchlari orasidagi (qirralar og'irliklari yig'indisi bo'yicha) masofani hisoblang. 1 ≤ n, q ≤ 5*10^5. dist(u,v) = depth(u) + depth(v) - 2*depth(LCA(u,v)) formulasidan foydalanish uchun barcha so'rovlar bo'yicha LCA larni offline tarzda samarali hisoblashingiz kerak; buning uchun Tarjan'ning DFS + Union-Find asosidagi offline LCA algoritmini qo'llab, umumiy vaqtni O((n+q)*α(n)) da ushlab turing.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,2],[1,2,3],[1,3,1]], queries = [[2,3],[0,2]]\nNatija: [4, 5]\nIzoh: 2 va 3 orasidagi masofa 1 orqali 3+1=4, 0 va 2 orasidagi masofa 2+3=5 ga teng.",
    starterCodeJs: 'function offlineTreeDistances(n, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def offline_tree_distances(n, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> offlineTreeDistances(int n, vector<array<long long,3>>& edges, vector<array<int,2>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-c-033',
    title: "Boshqaruv Oqimi Grafida Dominatorlarni Aniqlash",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan graf va boshlang'ich uch s berilgan (bu boshqaruv oqimi grafi bo'lib, s dan barcha uchlarga yetib borish mumkin deb faraz qilinadi). Uch u, uch v ni 'dominatsiya qiladi' deyiladi, agar s dan v ga boradigan har qanday yo'l albatta u orqali o'tsa. Har bir uch uchun uning bevosita dominatori (immediate dominator)ni toping. 1 ≤ n ≤ 2*10^5, 1 ≤ m ≤ 4*10^5. Har bir uch uchun barcha yo'llarni tekshirish imkonsiz bo'lgani uchun, siz Lengauer-Tarjan algoritmi yordamida dominator daraxtini samarali vaqtda qurishingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[0,2],[1,3],[2,3]], s = 0\nNatija: [-1, 0, 0, 0]\nIzoh: 3-uchga ham 1 orqali, ham 2 orqali yetib borish mumkin bo'lgani uchun uning bevosita dominatori 0 (ildiz) hisoblanadi.",
    starterCodeJs: 'function computeDominatorTree(n, edges, s) {\n  // your code here\n}',
    starterCodePy: 'def compute_dominator_tree(n, edges, s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> computeDominatorTree(int n, vector<array<int,2>>& edges, int s) {\n    // your code here\n}',
  },
  {
    key: 'master-c-034',
    title: "Dominator Daraxti Yordamida Muhim Uchlarni Topish",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan graf va boshlang'ich uch s berilgan. 'Muhim uch' deb, agar u olib tashlansa s dan yetib bo'lmaydigan kamida bitta boshqa uch paydo bo'ladigan (s dan farqli) uchga aytiladi. Barcha muhim uchlarni aniqlang. 1 ≤ n ≤ 2*10^5, 1 ≤ m ≤ 4*10^5. Bu masala s ildizli dominator daraxtini qurish bilan ekvivalent: dominator daraxtida kamida bitta bolasi bo'lgan har bir uch muhim uch hisoblanadi. Lengauer-Tarjan algoritmi yordamida dominator daraxtini samarali qurib, javobni chiqaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[1,3]], s = 0\nNatija: [1]\nIzoh: 1-uch dominator daraxtida ikkita bolaga (2 va 3) ega bo'lgani uchun muhim uch hisoblanadi - u olib tashlansa 2 va 3 ga yetib bo'lmaydi.",
    starterCodeJs: 'function findCriticalVertices(n, edges, s) {\n  // your code here\n}',
    starterCodePy: 'def find_critical_vertices(n, edges, s):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findCriticalVertices(int n, vector<array<int,2>>& edges, int s) {\n    // your code here\n}',
  },
  {
    key: 'master-c-035',
    title: "Eng Kichik Kesuvchi Uchlar To'plami (Dominator Asosida)",
    difficulty: 'MASTER',
    points: 235,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan graf, boshlang'ich uch s va maqsad uch t berilgan (s ≠ t, s dan t ga yetib borish mumkin). s dan t ga boradigan har qanday yo'lda albatta qatnashadigan barcha uchlarni (s va t dan tashqari, t ning barcha majburiy dominatorlarini) ildizdan t tomon dominator zanjiri bo'yicha tartiblab chiqaring. 1 ≤ n ≤ 2*10^5, 1 ≤ m ≤ 4*10^5. Bu s ildizli dominator daraxtida ildizdan t gacha bo'lgan yo'lni topish bilan ekvivalent; Lengauer-Tarjan algoritmini qo'llab dominator daraxtini quring va so'ralgan zanjirni chiqaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]], s = 0, t = 3\nNatija: [1, 2]\nIzoh: 0 dan 3 ga faqat yagona yo'l 0->1->2->3 mavjud, shuning uchun 1 va 2 uchlari majburiy dominatorlar hisoblanadi.",
    starterCodeJs: 'function findMandatoryVertices(n, edges, s, t) {\n  // your code here\n}',
    starterCodePy: 'def find_mandatory_vertices(n, edges, s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findMandatoryVertices(int n, vector<array<int,2>>& edges, int s, int t) {\n    // your code here\n}',
  },
  {
    key: 'master-c-036',
    title: "Planar Grafda Tezlashtirilgan Eng Qisqa Yo'l",
    difficulty: 'MASTER',
    points: 215,
    tags: ['Grafiklar'],
    description: "Tekislikda chizilgan (planar) n uchli, m qirrali yo'naltirilmagan graf berilgan (qirralar kesishmaydi, har bir uchning geometrik koordinatalari berilgan), qirra og'irliklari manfiy emas. q ta (s,t) so'rov uchun eng qisqa masofani toping. 1 ≤ n ≤ 2*10^5, 1 ≤ m ≤ 6*10^5 (planarlik tufayli m ≤ 3n-6), 1 ≤ q ≤ 1000. Har bir so'rov uchun alohida Dijkstra ishlatish O(q*m*log n) beradi, bu katta q uchun sekin; siz grafning planarligidan foydalanib (planar separator asosida ierarxik bo'linish qurib) so'rovlarni tezroq javoblashingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, points = [[0,0],[1,0],[1,1],[0,1]], edges = [[0,1,1],[1,2,1],[2,3,1],[3,0,1]], queries = [[0,2]]\nNatija: [2]\nIzoh: 0 dan 2 gacha eng qisqa yo'l 0->1->2 yoki 0->3->2 bo'lib, uzunligi 2 ga teng.",
    starterCodeJs: 'function planarShortestPaths(n, points, edges, queries) {\n  // your code here\n}',
    starterCodePy: 'def planar_shortest_paths(n, points, edges, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> planarShortestPaths(int n, vector<array<long long,2>>& points, vector<array<long long,3>>& edges, vector<array<int,2>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-c-037',
    title: "Planar Separator Yordamida Masofa So'rovlari",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Grafiklar'],
    description: "n uchli planar graf berilgan (qirralar og'irliksiz), grafning planar joylashuvi berilgan emas, faqat qo'shnilik ro'yxati va grafning planar ekanligi kafolatlangan. q ta juft uch orasidagi eng qisqa masofa (qirralar soni bo'yicha) so'raladi. 1 ≤ n ≤ 10^5, 1 ≤ q ≤ 10^5. Planar graflar uchun O(sqrt(n)) o'lchamdagi separator mavjudligidan foydalanib, grafni rekursiv ravishda bo'lib, har bir separator darajasida BFS ishga tushirib, ko'p so'rovlarni samarali javoblash kerak.\n\n**1-misol:**\nKiritma: n = 5, adjList = [[1,2],[0,3],[0,3],[1,2,4],[3]], queries = [[0,4]]\nNatija: [3]\nIzoh: 0 dan 4 gacha eng qisqa yo'l 0->1->3->4 (yoki 0->2->3->4) bo'lib, uzunligi 3 qirradan iborat.",
    starterCodeJs: 'function planarSeparatorDistances(n, adjList, queries) {\n  // your code here\n}',
    starterCodePy: 'def planar_separator_distances(n, adj_list, queries):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> planarSeparatorDistances(int n, vector<vector<int>>& adjList, vector<array<int,2>>& queries) {\n    // your code here\n}',
  },
  {
    key: 'master-c-038',
    title: "Dinamik Bog'lanuvchanlik So'rovlari",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Grafiklar'],
    description: "n uchli graf bo'sh holatdan boshlanadi va q ta amal beriladi: 'ADD u v' (u va v orasiga qirra qo'shish), 'REMOVE u v' (mavjud qirrani olib tashlash), 'QUERY u v' (u va v bir xil bog'langan komponentada ekanligini so'rash). Har bir QUERY amaliga javob bering. 1 ≤ n ≤ 2*10^5, 1 ≤ q ≤ 3*10^5. Qirralarni olib tashlash imkoniyati oddiy Union-Find dan foydalanishni imkonsiz qiladi; siz link-cut trees (yoki Euler tour trees / offline vaqt bo'yicha segment daraxti + rollback DSU) texnikasidan foydalanib, har bir amalni amortizatsiyalangan O(log^2 n) yoki yaxshiroq vaqtda bajarishingiz kerak.\n\n**1-misol:**\nKiritma: n = 3, operations = [['ADD',0,1],['QUERY',0,2],['ADD',1,2],['QUERY',0,2],['REMOVE',0,1],['QUERY',0,2]]\nNatija: [false, true, true]\nIzoh: 0 va 2 boshida bog'lanmagan, 1-2 qirrasi qo'shilgach 0-1-2 zanjiri orqali bog'lanadi, 0-1 qirrasi olib tashlansa ham 1-2 orqali emas endi 0 alohida qoladi - lekin misolda ular hali 1 orqali ulanmagani uchun natija kontekstga bog'liq.",
    starterCodeJs: 'function dynamicConnectivity(n, operations) {\n  // your code here\n}',
    starterCodePy: 'def dynamic_connectivity(n, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<bool> dynamicConnectivity(int n, vector<tuple<string,int,int>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-c-039',
    title: "Link-Cut Daraxtda Yo'l Yig'indisi So'rovlari",
    difficulty: 'MASTER',
    points: 235,
    tags: ['Grafiklar'],
    description: "n ta alohida uchdan (har birining boshlang'ich qiymati bor) tashkil topgan o'rmon (forest) berilgan, unga q ta amal ketma-ket beriladi: 'LINK u v' (agar u va v turli komponentlarda bo'lsa ularni bog'lash), 'CUT u v' (mavjud qirrani uzish), 'UPDATE v x' (v uchining qiymatini x ga o'zgartirish), 'PATH_SUM u v' (agar u va v bir komponentda bo'lsa, ular orasidagi yo'ldagi barcha uchlar qiymatlarining yig'indisini qaytarish). 1 ≤ n, q ≤ 2*10^5. Daraxt tuzilishi dinamik ravishda o'zgarib turgani uchun statik Euler tour + segment daraxti ishlamaydi; siz link-cut trees (splay-tree asosidagi preferred-path decomposition) ma'lumotlar tuzilmasini amalga oshirib, har bir amalni amortizatsiyalangan O(log n) vaqtda bajarishingiz kerak.\n\n**1-misol:**\nKiritma: n = 3, values = [1, 2, 3], operations = [['LINK',0,1],['LINK',1,2],['PATH_SUM',0,2],['CUT',1,2],['PATH_SUM',0,2]]\nNatija: [6, -1]\nIzoh: Barcha uchlar bog'langanda yig'indi 1+2+3=6, qirra uzilgach 0 va 2 alohida komponentalarda bo'lgani uchun -1 (mavjud emas) qaytariladi.",
    starterCodeJs: 'function linkCutForest(n, values, operations) {\n  // your code here\n}',
    starterCodePy: 'def link_cut_forest(n, values, operations):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> linkCutForest(int n, vector<long long>& values, vector<tuple<string,int,long long>>& operations) {\n    // your code here\n}',
  },
  {
    key: 'master-c-040',
    title: "Minimal Yopuvchi Daraxtni Dinamik Yangilash",
    difficulty: 'MASTER',
    points: 240,
    tags: ['Grafiklar'],
    description: "n uchli graf qirralar ketma-ket qo'shilib boruvchi (faqat qo'shish, olib tashlash yo'q) tarzda beriladi: har bir amalda yangi og'irlikli qirra (u,v,w) qo'shiladi va shu paytdagi minimal yopuvchi o'rmon (MST forest) umumiy og'irligini chiqarish kerak. 1 ≤ n ≤ 2*10^5, 1 ≤ q ≤ 4*10^5 ta qirra qo'shish amali. Har bir qadamda MST ni noldan qayta qurish O(q*n log n) beradi; siz har bir komponentni link-cut tree sifatida saqlab, yangi qirra qo'shilganda hosil bo'lgan sikldagi eng og'ir qirrani O(log n) da topib (agar yangi qirra undan yengil bo'lsa almashtirib), umumiy vaqtni O(q log n) ga tushirishingiz kerak.\n\n**1-misol:**\nKiritma: n = 3, edgeStream = [[0,1,5],[1,2,3],[0,2,1]]\nNatija: [5, 8, 4]\nIzoh: Birinchi qirradan keyin MST og'irligi 5, ikkinchisidan keyin 5+3=8, uchinchi qirra (0,2,1) qo'shilganda sikldagi eng og'ir qirra (0,1,5) almashtirilib jami 3+1=4 bo'ladi.",
    starterCodeJs: 'function dynamicMST(n, edgeStream) {\n  // your code here\n}',
    starterCodePy: 'def dynamic_mst(n, edge_stream):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> dynamicMST(int n, vector<array<long long,3>>& edgeStream) {\n    // your code here\n}',
  },
  {
    key: 'master-c-041',
    title: "Graf Ustida Steiner Daraxti",
    difficulty: 'MASTER',
    points: 245,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilmagan og'irlikli bog'langan graf va terminal uchlar to'plami T (|T| = k, k ≤ 12) berilgan. Barcha T dagi terminal uchlarni o'zaro bog'laydigan (boshqa oraliq uchlardan foydalanishga ruxsat berilgan holda) minimal og'irlikli qism daraxtni (Steiner tree) toping va uning umumiy og'irligini qaytaring. 1 ≤ n ≤ 100, 1 ≤ m ≤ 5000, 1 ≤ k ≤ 12. k kichik bo'lgani uchun siz Dreyfus-Wagner algoritmidan (dp[mask][v] = terminal to'plamining mask qismini v uchi orqali bog'lovchi minimal daraxt og'irligi) foydalanib, umumiy O(3^k * n + 2^k * (m log n)) vaqtda yechim toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,1],[1,2,1],[2,3,1],[0,3,4]], terminals = [0, 2, 3]\nNatija: 3\nIzoh: 0-1-2 va 2-3 qirralaridan foydalanib barcha uchta terminal 0, 2, 3 ni bog'lovchi daraxt og'irligi 1+1+1=3, bu minimaldir.",
    starterCodeJs: 'function steinerTreeWeight(n, edges, terminals) {\n  // your code here\n}',
    starterCodePy: 'def steiner_tree_weight(n, edges, terminals):\n    # your code here\n    pass',
    starterCodeCpp: 'long long steinerTreeWeight(int n, vector<array<long long,3>>& edges, vector<int>& terminals) {\n    // your code here\n}',
  },
  {
    key: 'master-c-042',
    title: "Minimal Steiner Daraxtining Tarkibini Tiklash",
    difficulty: 'MASTER',
    points: 250,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilmagan og'irlikli bog'langan graf va terminal to'plam T (|T|=k ≤ 12) berilgan. Faqat minimal Steiner daraxt og'irligini emas, balki shu daraxtga kiruvchi barcha qirralarni ham aniqlashingiz kerak. 1 ≤ n ≤ 100, 1 ≤ m ≤ 5000. Dreyfus-Wagner dinamik dasturlash jarayonida har bir holat uchun optimal yechim qanday olinganini (subset bo'linishi orqalimi yoki qo'shni uchdan kengaytirilganmi) kuzatib boruvchi 'parent' ma'lumotlarini saqlab, oxirida optimal daraxtni orqaga qarab tiklashingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,1],[1,2,1],[2,3,1],[0,3,4]], terminals = [0, 2, 3]\nNatija: [[0,1],[1,2],[2,3]]\nIzoh: Minimal Steiner daraxt uchta qirradan (0-1, 1-2, 2-3) tashkil topib, umumiy og'irligi 3 ga teng bo'ladi.",
    starterCodeJs: 'function reconstructSteinerTree(n, edges, terminals) {\n  // your code here\n}',
    starterCodePy: 'def reconstruct_steiner_tree(n, edges, terminals):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<array<int,2>> reconstructSteinerTree(int n, vector<array<long long,3>>& edges, vector<int>& terminals) {\n    // your code here\n}',
  },
  {
    key: 'master-c-043',
    title: "Cheklangan Byudjetli Steiner O'rmoni",
    difficulty: 'MASTER',
    points: 240,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali og'irlikli graf berilgan; terminal uchlar bir nechta guruhga bo'lingan (har bir guruh o'zaro bog'lanishi kerak bo'lgan terminallar to'plami), guruhlar soni g ≤ 6, barcha guruhlardagi terminallar jami k ≤ 12. Har bir guruh ichidagi terminallarni bog'lovchi minimal umumiy og'irlikdagi Steiner o'rmonini (barcha guruhlar uchun birgalikda, qirralar guruhlar orasida ulashilishi mumkin, ammo har bir qirra faqat bir marta hisoblanadi) toping. 1 ≤ n ≤ 80. Umumiy terminallar soni kichik bo'lgani uchun kengaytirilgan Dreyfus-Wagner uslubidagi bitmask DP (barcha terminallarni yagona 2^k holatlar maydonida birlashtirib, qaysi guruhga tegishliligini alohida kuzatib borish) qo'llanilishi kerak.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1,1],[1,2,1],[2,3,1],[3,4,1]], groups = [[0,1],[3,4]]\nNatija: 2\nIzoh: Birinchi guruh (0,1) uchun 0-1 qirrasi (og'irlik 1), ikkinchi guruh (3,4) uchun 3-4 qirrasi (og'irlik 1) yetarli, jami 2.",
    starterCodeJs: 'function steinerForestWeight(n, edges, groups) {\n  // your code here\n}',
    starterCodePy: 'def steiner_forest_weight(n, edges, groups):\n    # your code here\n    pass',
    starterCodeCpp: 'long long steinerForestWeight(int n, vector<array<long long,3>>& edges, vector<vector<int>>& groups) {\n    // your code here\n}',
  },
  {
    key: 'master-c-044',
    title: "K Ta Eng Qisqa Yo'lni Topish",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan og'irlikli graf (og'irliklar manfiy emas), boshlang'ich uch s, maqsad uch t va butun son k berilgan. s dan t ga boradigan (uchlar takrorlanishi mumkin emas — oddiy yo'llar) eng qisqa k ta turli yo'lning uzunliklarini o'sish tartibida chiqaring (agar k tadan kam yo'l mavjud bo'lsa, mavjud barchasini chiqaring). 1 ≤ n ≤ 500, 1 ≤ m ≤ 5000, 1 ≤ k ≤ 100. Yechim uchun Yen algoritmini qo'llash kerak: avval Dijkstra bilan eng qisqa yo'lni toping, so'ngra har bir qadamda oldingi yo'llarning har bir deviatsiya nuqtasidan yangi nomzod yo'llarni hosil qilib, ularni ustuvorlik navbatida saqlab eng yaxshisini tanlab boring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,1],[0,2,2],[1,3,3],[2,3,1]], s = 0, t = 3, k = 2\nNatija: [3, 4]\nIzoh: Eng qisqa yo'l 0->2->3 uzunligi 3, ikkinchi eng qisqa yo'l 0->1->3 uzunligi 4 ga teng.",
    starterCodeJs: 'function kShortestPaths(n, edges, s, t, k) {\n  // your code here\n}',
    starterCodePy: 'def k_shortest_paths(n, edges, s, t, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> kShortestPaths(int n, vector<array<long long,3>>& edges, int s, int t, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-c-045',
    title: "Loop-Free K-Eng-Qisqa Yo'llar Yig'indisi",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilgan og'irlikli graf, boshlang'ich uch s, maqsad uch t va k berilgan. s dan t ga boradigan eng qisqa k ta oddiy (sikllarsiz) yo'lning umumiy og'irliklari yig'indisini hisoblang (agar k tadan kam yo'l mavjud bo'lsa, mavjudlarining yig'indisini qaytaring, agar umuman yo'l bo'lmasa -1 qaytaring). 1 ≤ n ≤ 300, 1 ≤ m ≤ 3000, 1 ≤ k ≤ 50. Yechim Yen algoritmi asosida bo'lib, har bir iteratsiyada A ro'yxatidagi oxirgi qabul qilingan yo'lning har bir prefiksidan deviatsiya qilib, taqiqlangan qirra/uchlarni hisobga olgan holda qisqartirilgan Dijkstra ishga tushirilishi va natijalar min-heap orqali birlashtirilishi kerak.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1,1],[1,2,1],[0,2,3]], s = 0, t = 2, k = 2\nNatija: 5\nIzoh: Eng qisqa yo'l 0->1->2 uzunligi 2, ikkinchisi 0->2 uzunligi 3, yig'indi 2+3=5.",
    starterCodeJs: 'function sumOfKShortestPaths(n, edges, s, t, k) {\n  // your code here\n}',
    starterCodePy: 'def sum_of_k_shortest_paths(n, edges, s, t, k):\n    # your code here\n    pass',
    starterCodeCpp: 'long long sumOfKShortestPaths(int n, vector<array<long long,3>>& edges, int s, int t, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-c-046',
    title: "Ikki Grafning Izomorfligini Tekshirish",
    difficulty: 'MASTER',
    points: 220,
    tags: ['Grafiklar'],
    description: "Ikkita n uchli graf G1 va G2 (har birida m ta qirra) berilgan. G1 dan G2 ga uchlarni shunday moslashtirish (bijection) mavjudligini aniqlangki, u qo'shnilik munosabatini saqlasin (ya'ni G1 da (u,v) qirra bo'lsa, moslashtirilgan uchlar orasida ham G2 da qirra bo'lishi va aksincha). Agar bunday moslashtirish mavjud bo'lsa, true (yoki mos moslashtirishni), aks holda false qaytaring. 1 ≤ n ≤ 2000, 1 ≤ m ≤ 10^4. Umumiy holatda graf izomorfizmi murakkab masala bo'lgani uchun to'liq eksponensial qidiruv katta n uchun imkonsiz; siz amaliy heuristikalar (uchlar daraja ketma-ketligi, Weisfeiler-Lehman rangan invariantlari asosida uchlarni kanonik guruhlarga bo'lish, so'ngra qolgan noaniqliklarni tekshiruvchi backtracking) qo'llab samarali yechim topishingiz kerak.\n\n**1-misol:**\nKiritma: n = 3, edges1 = [[0,1],[1,2]], edges2 = [[0,1],[1,2]]\nNatija: true\nIzoh: Ikkala graf ham 3 uchli zanjir (path) bo'lgani uchun ular izomorfdir - masalan ayniy moslashtirish ishlaydi.",
    starterCodeJs: 'function areGraphsIsomorphic(n, edges1, edges2) {\n  // your code here\n}',
    starterCodePy: 'def are_graphs_isomorphic(n, edges1, edges2):\n    # your code here\n    pass',
    starterCodeCpp: 'bool areGraphsIsomorphic(int n, vector<array<int,2>>& edges1, vector<array<int,2>>& edges2) {\n    // your code here\n}',
  },
  {
    key: 'master-c-047',
    title: "Kanonik Shakl Yordamida Graflarni Guruhlash",
    difficulty: 'MASTER',
    points: 215,
    tags: ['Grafiklar'],
    description: "q ta kichik graf berilgan (har birida uchlar soni n ≤ 12), ularni o'zaro izomorf bo'lgan guruhlarga ajratish kerak (bir xil guruhga faqat bir-biriga izomorf graflar tushadi). Har bir noyob izomorfizm sinfiga vakil sifatida birinchi uchragan grafning indeksini biriktirib, har bir grafning qaysi sinfga tegishli ekanligini chiqaring. 1 ≤ q ≤ 2000. n kichik bo'lsa-da q katta bo'lgani uchun har bir juftlikni to'g'ridan-to'g'ri solishtirish O(q^2) sekin bo'lishi mumkin; siz Weisfeiler-Lehman refinement yordamida har bir graf uchun kanonik xesh (invariant) hisoblab, xeshlar bo'yicha guruhlab, faqat bir xil xeshli graflarni to'liq tekshiruvchi backtracking bilan solishtirishingiz kerak.\n\n**1-misol:**\nKiritma: graphs = [{n:3, edges:[[0,1],[1,2]]}, {n:3, edges:[[0,1],[0,2]]}, {n:3, edges:[[1,2],[2,0]]}]\nNatija: [0, 0, 0]\nIzoh: Barcha uchta graf ham 3 uchli zanjir (path) shakliga izomorf bo'lgani uchun bittasi guruhga - vakili 0-indeksli graf - tushadi.",
    starterCodeJs: 'function groupIsomorphicGraphs(graphs) {\n  // your code here\n}',
    starterCodePy: 'def group_isomorphic_graphs(graphs):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> groupIsomorphicGraphs(vector<pair<int, vector<array<int,2>>>>& graphs) {\n    // your code here\n}',
  },
  {
    key: 'master-c-048',
    title: "Global Minimal Kesim",
    difficulty: 'MASTER',
    points: 225,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilmagan og'irlikli bog'langan graf berilgan. Grafni ikki bo'sh bo'lmagan qismga ajratuvchi va kesilgan qirralar og'irliklari yig'indisi minimal bo'lgan kesimni toping (manba/oqim belgilanmagan — global minimal kesim). 2 ≤ n ≤ 600, 1 ≤ m ≤ 10^5, og'irliklar manfiy emas. n(n-1)/2 marta s-t minimal kesim (max-flow) hisoblash juda sekin bo'ladi; siz Stoer-Wagner algoritmini qo'llab, har bir bosqichda 'maximum adjacency ordering' orqali uchlarni birlashtirib borib, umumiy O(n^3) vaqtda global minimal kesimni toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,3],[1,2,1],[2,3,3],[0,3,1],[0,2,2]]\nNatija: 2\nIzoh: {1} va {0,2,3} qismlarga ajratish natijasida kesilgan qirralar (0,1) va (1,2) og'irliklari yig'indisi 3+1=4 emas, aslida eng arzon kesim {3} ni ajratish orqali 3+1=4 yoki boshqa kombinatsiya orqali minimal 2 ga erishiladi.",
    starterCodeJs: 'function globalMinCut(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def global_min_cut(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'long long globalMinCut(int n, vector<array<long long,3>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'master-c-049',
    title: "Global Minimal Kesimni Kafolatlaydigan Eng Kam Qirra Qo'shish",
    difficulty: 'MASTER',
    points: 235,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilmagan og'irliksiz bog'langan graf berilgan. Grafning global minimal kesimi (ya'ni grafni ikkiga ajratish uchun olib tashlanishi kerak bo'lgan eng kam qirralar soni) qiymatini k ga (berilgan maqsad qiymat, k > joriy min-cut) ko'tarish uchun qo'shilishi kerak bo'lgan minimal sonli yangi qirralarni toping (qirralarni istalgan ikki uch orasiga qo'shish mumkin). 2 ≤ n ≤ 300. Joriy min-cut qiymatini avval Stoer-Wagner algoritmi yordamida hisoblang, so'ngra qanday va qancha qirra qo'shish global bog'lanishni mustahkamlashini tahlil qilib minimal sonini qaytaring.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3],[3,0]], k = 3\nNatija: 2\nIzoh: 4 uchli sikl grafining joriy min-cut qiymati 2 (har bir uch ikkita qirraga ega), uni 3 ga ko'tarish uchun kamida 2 ta qo'shimcha qirra kerak bo'ladi.",
    starterCodeJs: 'function minEdgesToRaiseConnectivity(n, edges, k) {\n  // your code here\n}',
    starterCodePy: 'def min_edges_to_raise_connectivity(n, edges, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int minEdgesToRaiseConnectivity(int n, vector<array<int,2>>& edges, int k) {\n    // your code here\n}',
  },
  {
    key: 'master-c-050',
    title: "Tarmoqning Eng Zaif Bo'linish Nuqtasi",
    difficulty: 'MASTER',
    points: 230,
    tags: ['Grafiklar'],
    description: "n uchli, m qirrali yo'naltirilmagan og'irlikli bog'langan tarmoq berilgan, har bir qirraning 'ishonchlilik xarajati' w[i] bor. Tarmoqni ikki bo'lakka ajratish uchun buzilishi kerak bo'lgan eng arzon qirralar to'plamini (global minimal kesim) hamda shu kesim natijasida hosil bo'ladigan ikki bo'lakning har birining uchlari ro'yxatini toping. 2 ≤ n ≤ 800, 1 ≤ m ≤ 2*10^5. Barcha s-t juftliklari uchun max-flow min-cut hisoblash imkonsiz darajada sekin bo'lgani uchun, Stoer-Wagner global minimal kesim algoritmini qo'llab, umumiy O(n^3) vaqtda javobni (kesim og'irligi va ikki bo'lak tarkibi) topishingiz kerak.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,5],[1,2,1],[2,3,5],[0,3,1]]\nNatija: {weight: 2, partA: [0, 3], partB: [1, 2]}\nIzoh: (0,3) va (1,2) qirralarini kesish orqali graf {0,3} va {1,2} qismlarga ajraladi, kesim og'irligi 1+1=2 bo'lib bu minimaldir.",
    starterCodeJs: 'function weakestNetworkCut(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def weakest_network_cut(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'pair<long long, vector<int>> weakestNetworkCut(int n, vector<array<long long,3>>& edges) {\n    // your code here\n}',
  },
];
