export const problems = [
  {
    key: 'medium-a-001',
    title: "Uchlik Yig'indisi",
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi berilgan. Massivdan uchta elementni tanlab, ularning yig'indisi 0 ga teng bo'ladigan barcha noyob (bir-biriga o'xshamaydigan) uchliklarni toping. Har bir uchlik ichida sonlar o'sish tartibida bo'lishi shart emas, lekin natijadagi uchliklar orasida takror bo'lmasligi kerak.\n\n**1-misol:**\nKiritma: nums = [-1,0,1,2,-1,-4]\nNatija: [[-1,-1,2],[-1,0,1]]\nIzoh: Ikkita uchlik yig'indisi 0 ga teng.\n\n**2-misol:**\nKiritma: nums = [0,1,1]\nNatija: []\nIzoh: Yig'indisi 0 ga teng bo'lgan uchlik mavjud emas.",
    starterCodeJs: 'function threeSum(nums) {\n  // your code here\n}',
    starterCodePy: 'def three_sum(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> threeSum(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-002',
    title: "Massivning O'zidan Boshqa Elementlar Ko'paytmasi",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi berilgan. Har bir indeks i uchun nums[i] dan tashqari barcha elementlarning ko'paytmasidan iborat answer massivini qaytaring. Bo'lish amalidan foydalanmang va yechim O(n) vaqt murakkabligiga ega bo'lsin.\n\n**1-misol:**\nKiritma: nums = [1,2,3,4]\nNatija: [24,12,8,6]\n\n**2-misol:**\nKiritma: nums = [-1,1,0,-3,3]\nNatija: [0,0,9,0,0]",
    starterCodeJs: 'function productExceptSelf(nums) {\n  // your code here\n}',
    starterCodePy: 'def product_except_self(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> productExceptSelf(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-003',
    title: 'Maksimal Ketma-Ket Qism Massiv Yig’indisi',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Massivlar'],
    description: "Musbat va manfiy sonlarni o'z ichiga olishi mumkin bo'lgan nums butun sonlar massivi berilgan. Yig'indisi eng katta bo'lgan uzluksiz (ketma-ket joylashgan) qism massivning yig'indisini toping.\n\n**1-misol:**\nKiritma: nums = [-2,1,-3,4,-1,2,1,-5,4]\nNatija: 6\nIzoh: [4,-1,2,1] qism massivining yig'indisi eng katta.\n\n**2-misol:**\nKiritma: nums = [1]\nNatija: 1",
    starterCodeJs: 'function maxSubArray(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_sub_array(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxSubArray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-004',
    title: 'Kesishgan Oraliqlarni Birlashtirish',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Massivlar'],
    description: "intervals - [boshlanish, tugash] juftliklaridan iborat massiv berilgan. Bir-biri bilan kesishadigan barcha oraliqlarni birlashtiring va natijada bir-biri bilan kesishmaydigan oraliqlar massivini qaytaring.\n\n**1-misol:**\nKiritma: intervals = [[1,3],[2,6],[8,10],[15,18]]\nNatija: [[1,6],[8,10],[15,18]]\nIzoh: [1,3] va [2,6] kesishgani uchun [1,6] ga birlashtiriladi.\n\n**2-misol:**\nKiritma: intervals = [[1,4],[4,5]]\nNatija: [[1,5]]",
    starterCodeJs: 'function mergeIntervals(intervals) {\n  // your code here\n}',
    starterCodePy: 'def merge_intervals(intervals):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> mergeIntervals(vector<vector<int>>& intervals) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-005',
    title: 'Matritsani 90 Darajaga Burish',
    difficulty: 'MEDIUM',
    points: 48,
    tags: ['Massivlar'],
    description: "n x n o'lchamli kvadrat matrix berilgan. Uni joyida (qo'shimcha matritsa yaratmasdan) soat strelkasi yo'nalishida 90 darajaga burang.\n\n**1-misol:**\nKiritma: matrix = [[1,2,3],[4,5,6],[7,8,9]]\nNatija: [[7,4,1],[8,5,2],[9,6,3]]\n\n**2-misol:**\nKiritma: matrix = [[1,2],[3,4]]\nNatija: [[3,1],[4,2]]",
    starterCodeJs: 'function rotate(matrix) {\n  // your code here\n}',
    starterCodePy: 'def rotate(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'void rotate(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-006',
    title: "Spiral Tartibda Matritsani Aylanib O'tish",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Massivlar'],
    description: "m x n o'lchamli matrix berilgan. Uning barcha elementlarini spiral tartibda (tashqi qatlamdan boshlab soat strelkasi yo'nalishida ichkariga qarab) bitta massiv sifatida qaytaring.\n\n**1-misol:**\nKiritma: matrix = [[1,2,3],[4,5,6],[7,8,9]]\nNatija: [1,2,3,6,9,8,7,4,5]\n\n**2-misol:**\nKiritma: matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]\nNatija: [1,2,3,4,8,12,11,10,9,5,6,7]",
    starterCodeJs: 'function spiralOrder(matrix) {\n  // your code here\n}',
    starterCodePy: 'def spiral_order(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> spiralOrder(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-007',
    title: 'Massivdagi Takrorlanuvchi Sonni Topish',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Massivlar'],
    description: "1 dan n gacha bo'lgan sonlardan tashkil topgan, uzunligi n+1 bo'lgan nums massivi berilgan (aynan bitta son bir yoki bir necha marta takrorlanadi). Massivni o'zgartirmasdan va O(1) dan ortiq qo'shimcha xotira ishlatmasdan takrorlanuvchi sonni toping.\n\n**1-misol:**\nKiritma: nums = [1,3,4,2,2]\nNatija: 2\n\n**2-misol:**\nKiritma: nums = [3,1,3,4,2]\nNatija: 3",
    starterCodeJs: 'function findDuplicate(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_duplicate(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findDuplicate(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-008',
    title: 'Keyingi Permutatsiya',
    difficulty: 'MEDIUM',
    points: 44,
    tags: ['Massivlar'],
    description: "1 dan n gacha sonlarning permutatsiyasi bo'lgan nums massivi berilgan. Sonlarning leksikografik tartibda keyingi kattaroq permutatsiyasini toping va uni joyida nums ichiga yozing. Agar bunday permutatsiya mavjud bo'lmasa (massiv eng katta permutatsiya bo'lsa), massivni eng kichik (o'sish tartibidagi) permutatsiyaga aylantiring.\n\n**1-misol:**\nKiritma: nums = [1,2,3]\nNatija: [1,3,2]\n\n**2-misol:**\nKiritma: nums = [3,2,1]\nNatija: [1,2,3]\nIzoh: [3,2,1] eng katta permutatsiya bo'lgani uchun eng kichigiga qaytariladi.",
    starterCodeJs: 'function nextPermutation(nums) {\n  // your code here\n}',
    starterCodePy: 'def next_permutation(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'void nextPermutation(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-009',
    title: "Eng Ko'p Suv Sig'diruvchi Idish",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Massivlar'],
    description: "height massivi berilgan, bunda har bir element vertikal chiziqning balandligini bildiradi va chiziqlar orasidagi masofa ularning indekslari farqiga teng. Ikkita chiziqni tanlab, ular va x o'qi orasida hosil bo'ladigan idishning eng katta suv sig'imini toping.\n\n**1-misol:**\nKiritma: height = [1,8,6,2,5,4,8,3,7]\nNatija: 49\n\n**2-misol:**\nKiritma: height = [1,1]\nNatija: 1",
    starterCodeJs: 'function maxArea(height) {\n  // your code here\n}',
    starterCodePy: 'def max_area(height):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxArea(vector<int>& height) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-010',
    title: "Yomg'ir Suvini Ushlab Qolish",
    difficulty: 'MEDIUM',
    points: 47,
    tags: ['Massivlar'],
    description: "height massivi devorlar balandligini bildiradi (har bir devorning kengligi 1 ga teng). Yomg'ir yog'gandan so'ng devorlar orasida ushlab qolinishi mumkin bo'lgan suvning umumiy hajmini hisoblang.\n\n**1-misol:**\nKiritma: height = [0,1,0,2,1,0,1,3,2,1,2,1]\nNatija: 6\n\n**2-misol:**\nKiritma: height = [4,2,0,3,2,5]\nNatija: 9",
    starterCodeJs: 'function trap(height) {\n  // your code here\n}',
    starterCodePy: 'def trap(height):\n    # your code here\n    pass',
    starterCodeCpp: 'int trap(vector<int>& height) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-011',
    title: 'Siljiydigan Oyna Maksimumi',
    difficulty: 'MEDIUM',
    points: 50,
    tags: ['Massivlar'],
    description: "nums massivi va k butun soni berilgan. Uzunligi k bo'lgan oyna massiv bo'ylab chapdan o'ngga bittadan siljiydi. Har bir holatdagi oynaning maksimal qiymatlaridan iborat massivni qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,3,-1,-3,5,3,6,7], k = 3\nNatija: [3,3,5,5,6,7]\n\n**2-misol:**\nKiritma: nums = [1], k = 1\nNatija: [1]",
    starterCodeJs: 'function maxSlidingWindow(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def max_sliding_window(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> maxSlidingWindow(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-012',
    title: "Yig'indisi K ga Teng Bo'lgan Qism Massivlar Soni",
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Massivlar'],
    description: "nums butun sonlar massivi va k butun soni berilgan. Yig'indisi aynan k ga teng bo'lgan uzluksiz qism massivlarning umumiy sonini toping.\n\n**1-misol:**\nKiritma: nums = [1,1,1], k = 2\nNatija: 2\n\n**2-misol:**\nKiritma: nums = [1,2,3], k = 3\nNatija: 2",
    starterCodeJs: 'function subarraySum(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def subarray_sum(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int subarraySum(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-013',
    title: 'Ranglarni Saralash',
    difficulty: 'MEDIUM',
    points: 31,
    tags: ['Massivlar'],
    description: "Faqat 0, 1 va 2 sonlaridan iborat nums massivi berilgan (mos ravishda qizil, oq va ko'k ranglarni bildiradi). Massivni joyida, bitta o'tishda (one-pass), qo'shimcha saralash funksiyasidan foydalanmasdan o'sish tartibida saralang.\n\n**1-misol:**\nKiritma: nums = [2,0,2,1,1,0]\nNatija: [0,0,1,1,2,2]\n\n**2-misol:**\nKiritma: nums = [2,0,1]\nNatija: [0,1,2]",
    starterCodeJs: 'function sortColors(nums) {\n  // your code here\n}',
    starterCodePy: 'def sort_colors(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'void sortColors(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-014',
    title: 'Ustuvor Element',
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Massivlar'],
    description: "Uzunligi n bo'lgan nums massivi berilgan. Massivda n/2 martadan ko'proq uchraydigan elementni toping (bunday element har doim mavjud deb hisoblanadi). Iloji boricha O(n) vaqt va O(1) qo'shimcha xotira bilan yeching.\n\n**1-misol:**\nKiritma: nums = [3,2,3]\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [2,2,1,1,1,2,2]\nNatija: 2",
    starterCodeJs: 'function majorityElement(nums) {\n  // your code here\n}',
    starterCodePy: 'def majority_element(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int majorityElement(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-015',
    title: "Saralangan Massivda Ikki Sonning Yig'indisi",
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Massivlar'],
    description: "O'sish tartibida saralangan numbers massivi va target soni berilgan. Yig'indisi target ga teng bo'ladigan ikkita sonning indekslarini (1 dan boshlab hisoblangan) qaytaring. Yechim O(n) vaqt va O(1) qo'shimcha xotira bilan bo'lishi kerak.\n\n**1-misol:**\nKiritma: numbers = [2,7,11,15], target = 9\nNatija: [1,2]\n\n**2-misol:**\nKiritma: numbers = [2,3,4], target = 6\nNatija: [1,3]",
    starterCodeJs: 'function twoSumSorted(numbers, target) {\n  // your code here\n}',
    starterCodePy: 'def two_sum_sorted(numbers, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> twoSumSorted(vector<int>& numbers, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-016',
    title: 'Ikki Saralangan Massivni Birlashtirish',
    difficulty: 'MEDIUM',
    points: 39,
    tags: ['Massivlar'],
    description: "nums1 (o'lchami m+n bo'lib, oxirida m ta nol qiymat qo'shimcha joy sifatida turadi) va nums2 (o'lchami n) o'sish tartibida saralangan massivlar berilgan. nums2 ni nums1 ichiga shu tarzda birlashtiringki, natijada nums1 ham o'sish tartibida saralangan bo'lsin. Amalni joyida bajaring.\n\n**1-misol:**\nKiritma: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3\nNatija: [1,2,2,3,5,6]\n\n**2-misol:**\nKiritma: nums1 = [1], m = 1, nums2 = [], n = 0\nNatija: [1]",
    starterCodeJs: 'function merge(nums1, m, nums2, n) {\n  // your code here\n}',
    starterCodePy: 'def merge(nums1, m, nums2, n):\n    # your code here\n    pass',
    starterCodeCpp: 'void merge(vector<int>& nums1, int m, vector<int>& nums2, int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-017',
    title: 'Aylantirilgan Saralangan Massivdagi Minimum',
    difficulty: 'MEDIUM',
    points: 41,
    tags: ['Massivlar'],
    description: "Avvaldan o'sish tartibida saralangan va takrorlanmaydigan elementlardan iborat nums massivi noma'lum marta aylantirilgan (rotate qilingan). Massivdagi eng kichik elementni O(log n) vaqt murakkabligida toping.\n\n**1-misol:**\nKiritma: nums = [3,4,5,1,2]\nNatija: 1\n\n**2-misol:**\nKiritma: nums = [4,5,6,7,0,1,2]\nNatija: 0",
    starterCodeJs: 'function findMin(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_min(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMin(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-018',
    title: 'Aylantirilgan Saralangan Massivda Qidiruv',
    difficulty: 'MEDIUM',
    points: 46,
    tags: ['Massivlar'],
    description: "Avvaldan o'sish tartibida saralangan va takrorlanmaydigan nums massivi noma'lum marta aylantirilgan, shuningdek target soni berilgan. target ning indeksini O(log n) vaqt murakkabligida toping, agar mavjud bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [4,5,6,7,0,1,2], target = 0\nNatija: 4\n\n**2-misol:**\nKiritma: nums = [4,5,6,7,0,1,2], target = 3\nNatija: -1",
    starterCodeJs: 'function search(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def search(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int search(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-019',
    title: 'Massivdagi K-Chi Eng Katta Element',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Massivlar'],
    description: "nums massivi va k butun soni berilgan. Massiv saralangan taqdirda k-chi eng katta bo'ladigan elementni toping (eng katta element 1-o'rinda hisoblanadi, saralangan nusxa yaratish shart emas).\n\n**1-misol:**\nKiritma: nums = [3,2,1,5,6,4], k = 2\nNatija: 5\n\n**2-misol:**\nKiritma: nums = [3,2,3,1,2,4,5,5,6], k = 4\nNatija: 4",
    starterCodeJs: 'function findKthLargest(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def find_kth_largest(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int findKthLargest(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-020',
    title: 'Nollarni Massiv Oxiriga Surish',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Massivlar'],
    description: "nums massivi berilgan. Nolga teng bo'lmagan elementlarning o'zaro nisbiy tartibini saqlagan holda, barcha nollarni massivning oxiriga suring. Amalni joyida, qo'shimcha massiv nusxasi yaratmasdan bajaring.\n\n**1-misol:**\nKiritma: nums = [0,1,0,3,12]\nNatija: [1,3,12,0,0]\n\n**2-misol:**\nKiritma: nums = [0]\nNatija: [0]",
    starterCodeJs: 'function moveZeroes(nums) {\n  // your code here\n}',
    starterCodePy: 'def move_zeroes(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'void moveZeroes(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-021',
    title: 'Eng Uzun Ketma-Ket Sonlar Ketma-Ketligi',
    difficulty: 'MEDIUM',
    points: 43,
    tags: ['Massivlar'],
    description: "Saralanmagan nums butun sonlar massivi berilgan. Massivdagi sonlardan tuzilishi mumkin bo'lgan eng uzun ketma-ket (masalan 3,4,5,6 kabi birma-bir ortib boruvchi) sonlar ketma-ketligining uzunligini O(n) vaqt murakkabligida toping.\n\n**1-misol:**\nKiritma: nums = [100,4,200,1,3,2]\nNatija: 4\nIzoh: Eng uzun ketma-ketlik [1,2,3,4].\n\n**2-misol:**\nKiritma: nums = [0,3,7,2,5,8,4,6,0,1]\nNatija: 9",
    starterCodeJs: 'function longestConsecutive(nums) {\n  // your code here\n}',
    starterCodePy: 'def longest_consecutive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestConsecutive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-022',
    title: "Matritsa Nollarini O'rnatish",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Massivlar'],
    description: "m x n o'lchamli matrix berilgan. Agar biror element 0 ga teng bo'lsa, uning butun qatori va butun ustuni 0 ga aylantirilishi kerak. Amalni joyida bajaring.\n\n**1-misol:**\nKiritma: matrix = [[1,1,1],[1,0,1],[1,1,1]]\nNatija: [[1,0,1],[0,0,0],[1,0,1]]\n\n**2-misol:**\nKiritma: matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]\nNatija: [[0,0,0,0],[0,4,5,0],[0,3,1,0]]",
    starterCodeJs: 'function setZeroes(matrix) {\n  // your code here\n}',
    starterCodePy: 'def set_zeroes(matrix):\n    # your code here\n    pass',
    starterCodeCpp: 'void setZeroes(vector<vector<int>>& matrix) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-023',
    title: 'Maksimal Ko’paytma Qism Massiv',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Massivlar'],
    description: "Musbat, manfiy va nol qiymatlarni o'z ichiga olishi mumkin bo'lgan nums butun sonlar massivi berilgan. Ko'paytmasi eng katta bo'lgan uzluksiz qism massivning ko'paytmasini toping.\n\n**1-misol:**\nKiritma: nums = [2,3,-2,4]\nNatija: 6\nIzoh: [2,3] qism massivining ko'paytmasi 6.\n\n**2-misol:**\nKiritma: nums = [-2,0,-1]\nNatija: 0",
    starterCodeJs: 'function maxProduct(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_product(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxProduct(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-024',
    title: 'Massivni K Qadamga Aylantirish',
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Massivlar'],
    description: "nums massivi va k butun soni berilgan. Massivni o'ngga qarab k pozitsiyaga aylantiring (rotate qiling). Amalni joyida, O(1) qo'shimcha xotira bilan bajaring.\n\n**1-misol:**\nKiritma: nums = [1,2,3,4,5,6,7], k = 3\nNatija: [5,6,7,1,2,3,4]\n\n**2-misol:**\nKiritma: nums = [-1,-100,3,99], k = 2\nNatija: [3,99,-1,-100]",
    starterCodeJs: 'function rotateArray(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def rotate_array(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'void rotateArray(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-025',
    title: 'Massivdagi Barcha Takrorlanuvchi Sonlarni Topish',
    difficulty: 'MEDIUM',
    points: 49,
    tags: ['Massivlar'],
    description: "1 dan n gacha bo'lgan sonlardan tashkil topgan, uzunligi n bo'lgan nums massivi berilgan, bunda ba'zi sonlar aynan ikki marta, qolganlari esa bir marta uchraydi. Aynan ikki marta uchraydigan barcha sonlarni O(n) vaqt va O(1) qo'shimcha xotira (natija massivi hisobga kirmaydi) bilan toping.\n\n**1-misol:**\nKiritma: nums = [4,3,2,7,8,2,3,1]\nNatija: [2,3]\n\n**2-misol:**\nKiritma: nums = [1,1,2]\nNatija: [1]",
    starterCodeJs: 'function findDuplicates(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_duplicates(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findDuplicates(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-026',
    title: 'Takrorlanmaydigan Belgilardan Iborat Eng Uzun Qatorcha',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Satrlar'],
    description: "s satri berilgan. Unda takrorlanuvchi belgilarni o'z ichiga olmaydigan eng uzun qatorchaning (substring) uzunligini toping.\n\n**1-misol:**\nKiritma: s = 'abcabcbb'\nNatija: 3\nIzoh: Javob 'abc' qatorchasi, uzunligi 3.\n\n**2-misol:**\nKiritma: s = 'bbbbb'\nNatija: 1",
    starterCodeJs: 'function lengthOfLongestSubstring(s) {\n  // your code here\n}',
    starterCodePy: 'def length_of_longest_substring(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int lengthOfLongestSubstring(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-027',
    title: 'Anagrammalarni Guruhlash',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Satrlar'],
    description: "strs satrlar massivi berilgan. Bir-birining anagrammasi (bir xil harflardan tashkil topgan, faqat tartibi boshqacha satrlar) bo'lgan satrlarni guruhlarga birlashtiring va guruhlar ro'yxatini qaytaring, guruhlar va ular ichidagi elementlar tartibi muhim emas.\n\n**1-misol:**\nKiritma: strs = ['eat','tea','tan','ate','nat','bat']\nNatija: [['eat','tea','ate'],['tan','nat'],['bat']]\n\n**2-misol:**\nKiritma: strs = ['']\nNatija: [['']]",
    starterCodeJs: 'function groupAnagrams(strs) {\n  // your code here\n}',
    starterCodePy: 'def group_anagrams(strs):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<string>> groupAnagrams(vector<string>& strs) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-028',
    title: 'Eng Uzun Palindromik Qatorcha',
    difficulty: 'MEDIUM',
    points: 44,
    tags: ['Satrlar'],
    description: "s satri berilgan. Uning ichidagi eng uzun palindrom (old tomondan va orqa tomondan bir xil o'qiladigan) qatorchani toping. Agar bir nechta javob mavjud bo'lsa, ulardan istalgan birini qaytarish yetarli.\n\n**1-misol:**\nKiritma: s = 'babad'\nNatija: 'bab'\nIzoh: 'aba' ham to'g'ri javob hisoblanadi.\n\n**2-misol:**\nKiritma: s = 'cbbd'\nNatija: 'bb'",
    starterCodeJs: 'function longestPalindrome(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_palindrome(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestPalindrome(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-029',
    title: 'Satrni Butun Songa Aylantirish',
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Satrlar'],
    description: "s satri berilgan. Uni C tilidagi atoi funksiyasi kabi butun songa aylantiring: avval boshidagi bo'sh joylarni tashlab yuboring, ixtiyoriy bitta '+' yoki '-' belgisini hisobga oling, so'ngra ketma-ket kelgan raqamlarni o'qing, keyingi raqam bo'lmagan belgidan boshlab qolgan qismini e'tiborsiz qoldiring. Agar natija 32-bitli signed integer chegarasidan ([-2147483648, 2147483647]) tashqariga chiqsa, mos chegaraga qisqartiring. Agar hech qanday raqam topilmasa, 0 qaytaring.\n\n**1-misol:**\nKiritma: s = '   -42'\nNatija: -42\n\n**2-misol:**\nKiritma: s = '4193 with words'\nNatija: 4193",
    starterCodeJs: 'function myAtoi(s) {\n  // your code here\n}',
    starterCodePy: 'def my_atoi(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int myAtoi(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-030',
    title: "Qavslarning Barcha To'g'ri Kombinatsiyalarini Yaratish",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Satrlar'],
    description: "n butun soni berilgan. n juft ochiluvchi va yopiluvchi qavslardan tuzilishi mumkin bo'lgan barcha to'g'ri (well-formed) qavslar kombinatsiyalarini o'z ichiga olgan ro'yxatni qaytaring.\n\n**1-misol:**\nKiritma: n = 3\nNatija: ['((()))','(()())','(())()','()(())','()()()']\n\n**2-misol:**\nKiritma: n = 1\nNatija: ['()']",
    starterCodeJs: 'function generateParenthesis(n) {\n  // your code here\n}',
    starterCodePy: 'def generate_parenthesis(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> generateParenthesis(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-031',
    title: 'Minimal Oyna Qatorchasi',
    difficulty: 'MEDIUM',
    points: 47,
    tags: ['Satrlar'],
    description: "s va t satrlar berilgan. s ichidan t ning barcha belgilarini (takrorlanishlari bilan birga) o'z ichiga oladigan eng qisqa uzluksiz qatorchani toping. Agar bunday qatorcha mavjud bo'lmasa, bo'sh satr qaytaring.\n\n**1-misol:**\nKiritma: s = 'ADOBECODEBANC', t = 'ABC'\nNatija: 'BANC'\n\n**2-misol:**\nKiritma: s = 'a', t = 'a'\nNatija: 'a'",
    starterCodeJs: 'function minWindow(s, t) {\n  // your code here\n}',
    starterCodePy: 'def min_window(s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'string minWindow(string s, string t) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-032',
    title: 'Satrni Siqish',
    difficulty: 'MEDIUM',
    points: 31,
    tags: ['Satrlar'],
    description: "Belgilardan iborat chars massivi berilgan. Uni joyida siqing: har bir ketma-ket takrorlanuvchi belgilar guruhini bitta belgi va undan keyin (agar takrorlanish soni 1 dan katta bo'lsa) sonning har bir raqami alohida element sifatida yozib qo'ying. Siqilgan massivning yangi uzunligini qaytaring.\n\n**1-misol:**\nKiritma: chars = ['a','a','b','b','c','c','c']\nNatija: 6\nIzoh: Massiv ['a','2','b','2','c','3'] ko'rinishiga keladi.\n\n**2-misol:**\nKiritma: chars = ['a']\nNatija: 1",
    starterCodeJs: 'function compress(chars) {\n  // your code here\n}',
    starterCodePy: 'def compress(chars):\n    # your code here\n    pass',
    starterCodeCpp: 'int compress(vector<char>& chars) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-033',
    title: 'Zigzag Konversiya',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Satrlar'],
    description: "s satri va numRows butun soni berilgan. Satrni zigzag shaklida numRows qatorga yozib (yuqoridan pastga, so'ng pastdan yuqoriga diagonal tarzda), so'ngra qatorlarni birin-ketin chapdan o'ngga o'qib chiqib hosil bo'ladigan yangi satrni qaytaring.\n\n**1-misol:**\nKiritma: s = 'PAYPALISHIRING', numRows = 3\nNatija: 'PAHNAPLSIIGYIR'\n\n**2-misol:**\nKiritma: s = 'PAYPALISHIRING', numRows = 4\nNatija: 'PINALSIGYAHRPI'",
    starterCodeJs: 'function convert(s, numRows) {\n  // your code here\n}',
    starterCodePy: 'def convert(s, num_rows):\n    # your code here\n    pass',
    starterCodeCpp: 'string convert(string s, int numRows) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-034',
    title: 'So’z Andozasiga Moslik',
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Satrlar'],
    description: "pattern satri va bo'shliq bilan ajratilgan so'zlardan iborat s satri berilgan. s dagi har bir so'z pattern dagi mos harfga bir-biriga mos keladigan (bijektiv, ya'ni har bir harf faqat bitta so'zga va aksincha) tarzda moslashishini tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: pattern = 'abba', s = 'dog cat cat dog'\nNatija: true\n\n**2-misol:**\nKiritma: pattern = 'abba', s = 'dog cat cat fish'\nNatija: false",
    starterCodeJs: 'function wordPattern(pattern, s) {\n  // your code here\n}',
    starterCodePy: 'def word_pattern(pattern, s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool wordPattern(string pattern, string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-035',
    title: 'Eng Uzun Umumiy Prefiks',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Satrlar'],
    description: "strs satrlar massivi berilgan. Ularning barchasiga tegishli bo'lgan eng uzun umumiy prefiksni toping. Agar umumiy prefiks mavjud bo'lmasa, bo'sh satr qaytaring.\n\n**1-misol:**\nKiritma: strs = ['flower','flow','flight']\nNatija: 'fl'\n\n**2-misol:**\nKiritma: strs = ['dog','racecar','car']\nNatija: ''",
    starterCodeJs: 'function longestCommonPrefix(strs) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_prefix(strs):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestCommonPrefix(vector<string>& strs) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-036',
    title: 'Takrorlanish Soni Bilan Kodlangan Satrni Ochish',
    difficulty: 'MEDIUM',
    points: 46,
    tags: ['Satrlar'],
    description: "s kodlangan satr berilgan, format quyidagicha: k[qatorcha], bunda kvadrat qavs ichidagi qatorcha aynan k marta ketma-ket takrorlanishi kerak. Kodlash ichma-ich (nested) bo'lishi mumkin. Kodlangan satrni to'liq ochib (decode qilib), natijaviy satrni qaytaring.\n\n**1-misol:**\nKiritma: s = '3[a]2[bc]'\nNatija: 'aaabcbc'\n\n**2-misol:**\nKiritma: s = '3[a2[c]]'\nNatija: 'accaccacc'",
    starterCodeJs: 'function decodeString(s) {\n  // your code here\n}',
    starterCodePy: 'def decode_string(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string decodeString(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-037',
    title: "Satr Ko'rinishidagi Sonlarni Ko'paytirish",
    difficulty: 'MEDIUM',
    points: 48,
    tags: ['Satrlar'],
    description: "num1 va num2 - manfiy bo'lmagan butun sonlarni ifodalovchi satrlar berilgan (sonlar juda katta bo'lishi mumkin, shuning uchun tilning o'rnatilgan katta sonlar bilan ishlash imkoniyatidan yoki to'g'ridan-to'g'ri raqamga aylantirishdan foydalanmang). Ularning ko'paytmasini ham satr ko'rinishida qaytaring.\n\n**1-misol:**\nKiritma: num1 = '123', num2 = '456'\nNatija: '56088'\n\n**2-misol:**\nKiritma: num1 = '2', num2 = '3'\nNatija: '6'",
    starterCodeJs: 'function multiply(num1, num2) {\n  // your code here\n}',
    starterCodePy: 'def multiply(num1, num2):\n    # your code here\n    pass',
    starterCodeCpp: 'string multiply(string num1, string num2) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-038',
    title: 'Log Fayl Yozuvlarini Qayta Tartiblash',
    difficulty: 'MEDIUM',
    points: 41,
    tags: ['Satrlar'],
    description: "logs satrlar massivi berilgan, har bir yozuv 'identifikator so’z1 so’z2 ...' formatida bo'ladi. Ikki turdagi yozuvlar mavjud: harf-yozuvlari (identifikatordan keyin faqat harflardan iborat so'zlar keladi) va raqam-yozuvlari (identifikatordan keyin faqat raqamlar keladi). Harf-yozuvlarini avval mazmuni bo'yicha alifbo tartibida (mazmun bir xil bo'lsa identifikatori bo'yicha) joylashtiring, so'ngra ular ketidan raqam-yozuvlarini asl tartibda joylashtirib qaytaring.\n\n**1-misol:**\nKiritma: logs = ['dig1 8 1 5 1','let1 art can','dig2 3 6','let2 own kit dig','let3 art zero']\nNatija: ['let1 art can','let3 art zero','let2 own kit dig','dig1 8 1 5 1','dig2 3 6']\n\n**2-misol:**\nKiritma: logs = ['a1 9 2 3 1','g1 act car','zo4 4 7']\nNatija: ['g1 act car','a1 9 2 3 1','zo4 4 7']",
    starterCodeJs: 'function reorderLogFiles(logs) {\n  // your code here\n}',
    starterCodePy: 'def reorder_log_files(logs):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> reorderLogFiles(vector<string>& logs) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-039',
    title: 'Anagramma Ekanligini Tekshirish',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Satrlar'],
    description: "s va t satrlar berilgan. t satri s ning anagrammasi ekanligini, ya'ni ikkala satr bir xil harflardan (bir xil sondagi takrorlanishlar bilan) tashkil topganini tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: s = 'anagram', t = 'nagaram'\nNatija: true\n\n**2-misol:**\nKiritma: s = 'rat', t = 'car'\nNatija: false",
    starterCodeJs: 'function isAnagram(s, t) {\n  // your code here\n}',
    starterCodePy: 'def is_anagram(s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isAnagram(string s, string t) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-040',
    title: "Gapdagi So'zlarni Teskari Tartibga O'tkazish",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Satrlar'],
    description: "s satri berilgan, unda so'zlar bittadan yoki bir nechtadan bo'sh joy bilan ajratilgan bo'lishi mumkin. So'zlarning tartibini teskari qiling, so'zlar orasida faqat bitta bo'sh joy qoldiring hamda satrning boshi va oxiridagi ortiqcha bo'sh joylarni olib tashlang.\n\n**1-misol:**\nKiritma: s = '  the sky is blue  '\nNatija: 'blue is sky the'\n\n**2-misol:**\nKiritma: s = 'a good   example'\nNatija: 'example good a'",
    starterCodeJs: 'function reverseWords(s) {\n  // your code here\n}',
    starterCodePy: 'def reverse_words(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string reverseWords(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-041',
    title: 'Bir Tahrirlik Masofa Tekshiruvi',
    difficulty: 'MEDIUM',
    points: 39,
    tags: ['Satrlar'],
    description: "s va t satrlar berilgan. Ular orasida aynan bitta tahrir amali (bitta belgini qo'shish, o'chirish yoki boshqa belgiga almashtirish) yordamida bir-biriga aylantirish mumkinligini tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: s = 'cat', t = 'cats'\nNatija: true\n\n**2-misol:**\nKiritma: s = 'cat', t = 'dog'\nNatija: false",
    starterCodeJs: 'function isOneEditDistance(s, t) {\n  // your code here\n}',
    starterCodePy: 'def is_one_edit_distance(s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isOneEditDistance(string s, string t) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-042',
    title: 'Satrdagi Anagramma Boshlanish Indekslari',
    difficulty: 'MEDIUM',
    points: 44,
    tags: ['Satrlar'],
    description: "s va p satrlar berilgan. s ichidagi p ning barcha anagrammasi bo'lgan uzunligi p.length ga teng qatorchalarning boshlanish indekslarini toping.\n\n**1-misol:**\nKiritma: s = 'cbaebabacd', p = 'abc'\nNatija: [0,6]\n\n**2-misol:**\nKiritma: s = 'abab', p = 'ab'\nNatija: [0,1,2]",
    starterCodeJs: 'function findAnagrams(s, p) {\n  // your code here\n}',
    starterCodePy: 'def find_anagrams(s, p):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findAnagrams(string s, string p) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-043',
    title: 'Butun Sonni Rim Raqamiga Aylantirish',
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Satrlar'],
    description: "1 dan 3999 gacha bo'lgan num butun soni berilgan. Uni Rim raqamlari (Roman numerals) ko'rinishidagi satrga aylantiring.\n\n**1-misol:**\nKiritma: num = 1994\nNatija: 'MCMXCIV'\n\n**2-misol:**\nKiritma: num = 58\nNatija: 'LVIII'",
    starterCodeJs: 'function intToRoman(num) {\n  // your code here\n}',
    starterCodePy: 'def int_to_roman(num):\n    # your code here\n    pass',
    starterCodeCpp: 'string intToRoman(int num) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-044',
    title: 'Rim Raqamini Butun Songa Aylantirish',
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Satrlar'],
    description: "s - to'g'ri Rim raqamlari (Roman numerals) ko'rinishida tuzilgan satr berilgan. Uni mos butun songa aylantiring.\n\n**1-misol:**\nKiritma: s = 'LVIII'\nNatija: 58\nIzoh: L = 50, V = 5, III = 3.\n\n**2-misol:**\nKiritma: s = 'MCMXCIV'\nNatija: 1994",
    starterCodeJs: 'function romanToInt(s) {\n  // your code here\n}',
    starterCodePy: 'def roman_to_int(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int romanToInt(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-045',
    title: "Qavslarni To'g'irlash Uchun Minimal Qo'shish",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Satrlar'],
    description: "Faqat '(' va ')' belgilaridan iborat s satri berilgan. Uni to'g'ri (valid) qavslar ketma-ketligiga aylantirish uchun qo'shilishi zarur bo'lgan eng kam sondagi qavslar sonini toping.\n\n**1-misol:**\nKiritma: s = '())'\nNatija: 1\n\n**2-misol:**\nKiritma: s = '((('\nNatija: 3",
    starterCodeJs: 'function minAddToMakeValid(s) {\n  // your code here\n}',
    starterCodePy: 'def min_add_to_make_valid(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int minAddToMakeValid(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-046',
    title: 'Hisoblash Va Aytish Ketma-Ketligi',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Satrlar'],
    description: "n butun soni berilgan. 'Hisobla va ayt' (count-and-say) ketma-ketligining n-chi hadini qaytaring: 1-had '1' ga teng, har keyingi had oldingi haddagi ketma-ket bir xil raqamlar guruhlarini 'son+raqam' tarzida tavsiflash orqali hosil qilinadi.\n\n**1-misol:**\nKiritma: n = 1\nNatija: '1'\n\n**2-misol:**\nKiritma: n = 4\nNatija: '1211'\nIzoh: '1' -> '11' -> '21' -> '1211'.",
    starterCodeJs: 'function countAndSay(n) {\n  // your code here\n}',
    starterCodePy: 'def count_and_say(n):\n    # your code here\n    pass',
    starterCodeCpp: 'string countAndSay(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-047',
    title: 'Izomorf Satrlar',
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Satrlar'],
    description: "s va t bir xil uzunlikdagi satrlar berilgan. s dagi har bir belgi t dagi mos belgiga bir-biriga mos keladigan (bijektiv, ya'ni har bir belgi doim bitta belgiga almashtiriladi va aksincha) tarzda almashtirilishi mumkinligini tekshiring.\n\n**1-misol:**\nKiritma: s = 'egg', t = 'add'\nNatija: true\n\n**2-misol:**\nKiritma: s = 'foo', t = 'bar'\nNatija: false",
    starterCodeJs: 'function isIsomorphic(s, t) {\n  // your code here\n}',
    starterCodePy: 'def is_isomorphic(s, t):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isIsomorphic(string s, string t) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-048',
    title: "Maxsus Tartib Bo'yicha Saralash",
    difficulty: 'MEDIUM',
    points: 43,
    tags: ['Satrlar'],
    description: "order va s satrlari berilgan, order dagi barcha belgilar noyob. s dagi belgilarni order da ko'rsatilgan nisbiy tartibda joylashtiring; order da uchramaydigan belgilarni esa natija satrining oxiriga, ular orasidagi asl nisbiy tartibni saqlagan holda joylashtiring.\n\n**1-misol:**\nKiritma: order = 'cba', s = 'abcd'\nNatija: 'cbad'\n\n**2-misol:**\nKiritma: order = 'bcafg', s = 'abcd'\nNatija: 'bcad'",
    starterCodeJs: 'function customSortString(order, s) {\n  // your code here\n}',
    starterCodePy: 'def custom_sort_string(order, s):\n    # your code here\n    pass',
    starterCodeCpp: 'string customSortString(string order, string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-049',
    title: "Unix Fayl Yo'lini Soddalashtirish",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Satrlar'],
    description: "Unix uslubidagi absolyut fayl yo'li bo'lgan path satri berilgan. Uni soddalashtirilgan kanonik shaklga keltiring: '.' joriy papkani, '..' bir daraja yuqoriga chiqishni bildiradi, ortiqcha yoki ketma-ket kelgan '/' belgilarini bitta '/' ga qisqartiring va yo'l '/' bilan tugamasin (ildiz bundan mustasno).\n\n**1-misol:**\nKiritma: path = '/a/./b/../../c/'\nNatija: '/c'\n\n**2-misol:**\nKiritma: path = '/home//foo/'\nNatija: '/home/foo'",
    starterCodeJs: 'function simplifyPath(path) {\n  // your code here\n}',
    starterCodePy: 'def simplify_path(path):\n    # your code here\n    pass',
    starterCodeCpp: 'string simplifyPath(string path) {\n    // your code here\n}',
  },
  {
    key: 'medium-a-050',
    title: 'Takrorlanuvchi Qism Satr Andozasini Tekshirish',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Satrlar'],
    description: "s satri berilgan. Uning o'zi biror qism satrning (substring) bir necha marta ketma-ket takrorlanishidan hosil bo'lishi mumkinligini tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: s = 'abab'\nNatija: true\nIzoh: 'ab' qism satri ikki marta ketma-ket takrorlangan.\n\n**2-misol:**\nKiritma: s = 'aba'\nNatija: false",
    starterCodeJs: 'function repeatedSubstringPattern(s) {\n  // your code here\n}',
    starterCodePy: 'def repeated_substring_pattern(s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool repeatedSubstringPattern(string s) {\n    // your code here\n}',
  },
];
