export const problems = [
  {
    key: 'medium-d-001',
    title: "BST'ga Element Qo'shish",
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Daraxtlar'],
    description: "Ikkilik qidiruv daraxti (BST) ning ildizi root va butun son value berilgan. value ni BST xususiyatini buzmagan holda daraxtga qo'shing va yangi ildizni qaytaring.\n\n**1-misol:**\nKiritma: root = [4,2,7,1,3], value = 5\nNatija: [4,2,7,1,3,5]\nIzoh: 5 soni 4 dan kichik, 7 dan kichik bo'lgani uchun 7 ning chap farzandi sifatida qo'shiladi.\n\n**2-misol:**\nKiritma: root = [], value = 10\nNatija: [10]",
    starterCodeJs: 'function insertIntoBST(root, value) {\n  // your code here\n}',
    starterCodePy: 'def insert_into_bst(root, value):\n    # your code here\n    pass',
    starterCodeCpp: 'TreeNode* insertIntoBST(TreeNode* root, int value) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-002',
    title: 'Ikkilik Qidiruv Daraxtini Tekshirish',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan. Bu daraxt haqiqiy ikkilik qidiruv daraxti (BST) ekanligini tekshiring, ya'ni har bir tugun uchun chap qism daraxtdagi barcha qiymatlar undan kichik, o'ng qism daraxtdagi barcha qiymatlar undan katta bo'lishi kerak.\n\n**1-misol:**\nKiritma: root = [2,1,3]\nNatija: true\n\n**2-misol:**\nKiritma: root = [5,1,4,null,null,3,6]\nNatija: false\nIzoh: Ildiz 5 dan o'ng qism daraxtdagi 3 kichik bo'lgani uchun BST shartini buzadi.",
    starterCodeJs: 'function isValidBST(root) {\n  // your code here\n}',
    starterCodePy: 'def is_valid_bst(root):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isValidBST(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-003',
    title: "Daraxtni Daraja Bo'yicha Aylanib Chiqish",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan. Daraxt tugunlarini daraja (level) bo'yicha, chapdan o'ngga qarab, har bir darajani alohida massiv sifatida qaytaring.\n\n**1-misol:**\nKiritma: root = [3,9,20,null,null,15,7]\nNatija: [[3],[9,20],[15,7]]\n\n**2-misol:**\nKiritma: root = [1]\nNatija: [[1]]",
    starterCodeJs: 'function levelOrder(root) {\n  // your code here\n}',
    starterCodePy: 'def level_order(root):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> levelOrder(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-004',
    title: 'Eng Past Umumiy Ajdodni Topish',
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Daraxtlar'],
    description: "Ikkilik qidiruv daraxtining ildizi root va ikkita tugun p, q berilgan. Ushbu ikki tugunning eng past umumiy ajdodini (LCA) toping.\n\n**1-misol:**\nKiritma: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8\nNatija: 6\nIzoh: 2 va 8 tugunlarining eng past umumiy ajdodi 6 hisoblanadi.\n\n**2-misol:**\nKiritma: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4\nNatija: 2",
    starterCodeJs: 'function lowestCommonAncestor(root, p, q) {\n  // your code here\n}',
    starterCodePy: 'def lowest_common_ancestor(root, p, q):\n    # your code here\n    pass',
    starterCodeCpp: 'TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-005',
    title: 'Binar Daraxt Diametrini Topish',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan. Daraxt diametrini, ya'ni ixtiyoriy ikki tugun orasidagi eng uzun yo'lda joylashgan qirralar sonini toping. Bu yo'l ildiz orqali o'tishi shart emas.\n\n**1-misol:**\nKiritma: root = [1,2,3,4,5]\nNatija: 3\nIzoh: Eng uzun yo'l [4,2,1,3] yoki [5,2,1,3] orqali o'tadi va 3 ta qirradan iborat.\n\n**2-misol:**\nKiritma: root = [1,2]\nNatija: 1",
    starterCodeJs: 'function diameterOfBinaryTree(root) {\n  // your code here\n}',
    starterCodePy: 'def diameter_of_binary_tree(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int diameterOfBinaryTree(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-006',
    title: 'Binar Daraxtni Teskari Aylantirish',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan. Daraxtning har bir tugunidagi chap va o'ng farzandlarni almashtirib, daraxtning ko'zgu aksini hosil qiling va yangi ildizni qaytaring.\n\n**1-misol:**\nKiritma: root = [4,2,7,1,3,6,9]\nNatija: [4,7,2,9,6,3,1]\n\n**2-misol:**\nKiritma: root = [2,1,3]\nNatija: [2,3,1]",
    starterCodeJs: 'function invertTree(root) {\n  // your code here\n}',
    starterCodePy: 'def invert_tree(root):\n    # your code here\n    pass',
    starterCodeCpp: 'TreeNode* invertTree(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-007',
    title: "Yig'indiga Teng Yo'lni Tekshirish",
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root va butun son targetSum berilgan. Ildizdan bargga (leaf) qadar boradigan shunday yo'l mavjudligini tekshiringki, yo'ldagi barcha tugunlar qiymatlarining yig'indisi targetSum ga teng bo'lsin.\n\n**1-misol:**\nKiritma: root = [5,4,8,11,null,13,4,7,2,null,null,null,1], targetSum = 22\nNatija: true\nIzoh: 5->4->11->2 yo'li 22 ga teng yig'indi beradi.\n\n**2-misol:**\nKiritma: root = [1,2,3], targetSum = 5\nNatija: false",
    starterCodeJs: 'function hasPathSum(root, targetSum) {\n  // your code here\n}',
    starterCodePy: 'def has_path_sum(root, target_sum):\n    # your code here\n    pass',
    starterCodeCpp: 'bool hasPathSum(TreeNode* root, int targetSum) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-008',
    title: 'Muvozanatlashgan Daraxtni Tekshirish',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan. Daraxt balandlik bo'yicha muvozanatlashgan ekanligini tekshiring, ya'ni har bir tugun uchun uning chap va o'ng qism daraxtlari balandliklari farqi 1 dan oshmasligi kerak.\n\n**1-misol:**\nKiritma: root = [3,9,20,null,null,15,7]\nNatija: true\n\n**2-misol:**\nKiritma: root = [1,2,2,3,3,null,null,4,4]\nNatija: false",
    starterCodeJs: 'function isBalanced(root) {\n  // your code here\n}',
    starterCodePy: 'def is_balanced(root):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isBalanced(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-009',
    title: 'Binar Daraxtni Ketma-Ketlikka Aylantirish Va Qayta Tiklash',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Daraxtlar'],
    description: 'Binar daraxtning ildizi root berilgan. Daraxtni birorta matn ko\'rinishidagi ketma-ketlikka (masalan, vergul bilan ajratilgan qiymatlar va null belgilari) aylantiradigan serialize funksiyasini va shu ketma-ketlikdan asl daraxtni qayta tiklaydigan deserialize funksiyasini yozing.\n\n**1-misol:**\nKiritma: root = [1,2,3,null,null,4,5]\nNatija: "1,2,3,null,null,4,5" (serialize natijasi), keyin deserialize qilinganda asl daraxt qaytadi\n\n**2-misol:**\nKiritma: root = []\nNatija: "null"',
    starterCodeJs: 'function serialize(root) {\n  // your code here\n}\n\nfunction deserialize(data) {\n  // your code here\n}',
    starterCodePy: 'def serialize(root):\n    # your code here\n    pass\n\n\ndef deserialize(data):\n    # your code here\n    pass',
    starterCodeCpp: 'string serialize(TreeNode* root) {\n    // your code here\n}\n\nTreeNode* deserialize(string data) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-010',
    title: "BST'da K-Chi Eng Kichik Elementni Topish",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Daraxtlar'],
    description: "Ikkilik qidiruv daraxtining ildizi root va butun son k berilgan. Daraxtdagi k-chi eng kichik qiymatni toping (1-indeksdan boshlab).\n\n**1-misol:**\nKiritma: root = [3,1,4,null,2], k = 1\nNatija: 1\n\n**2-misol:**\nKiritma: root = [5,3,6,2,4,null,null,1], k = 3\nNatija: 3",
    starterCodeJs: 'function kthSmallest(root, k) {\n  // your code here\n}',
    starterCodePy: 'def kth_smallest(root, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int kthSmallest(TreeNode* root, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-011',
    title: 'Daraxt Simmetrikligini Tekshirish',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan. Daraxt o'zining vertikal o'qi bo'yicha simmetrik (ko'zguda aks etganidek bir xil) ekanligini tekshiring.\n\n**1-misol:**\nKiritma: root = [1,2,2,3,4,4,3]\nNatija: true\n\n**2-misol:**\nKiritma: root = [1,2,2,null,3,null,3]\nNatija: false",
    starterCodeJs: 'function isSymmetric(root) {\n  // your code here\n}',
    starterCodePy: 'def is_symmetric(root):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isSymmetric(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-012',
    title: 'Ikki Daraxtning Bir Xilligini Tekshirish',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Daraxtlar'],
    description: "Ikkita binar daraxtning ildizlari p va q berilgan. Bu ikki daraxt bir xil tuzilishga va bir xil tugun qiymatlariga ega ekanligini tekshiring.\n\n**1-misol:**\nKiritma: p = [1,2,3], q = [1,2,3]\nNatija: true\n\n**2-misol:**\nKiritma: p = [1,2], q = [1,null,2]\nNatija: false",
    starterCodeJs: 'function isSameTree(p, q) {\n  // your code here\n}',
    starterCodePy: 'def is_same_tree(p, q):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isSameTree(TreeNode* p, TreeNode* q) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-013',
    title: "Ildizdan Bargacha Sonlar Yig'indisi",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Daraxtlar'],
    description: "Binar daraxtning ildizi root berilgan, unda har bir tugun 0 dan 9 gacha bo'lgan raqamni ifodalaydi. Har bir ildizdan bargga qadar bo'lgan yo'l bitta ko'p xonali sonni hosil qiladi. Barcha bunday sonlarning yig'indisini toping.\n\n**1-misol:**\nKiritma: root = [1,2,3]\nNatija: 25\nIzoh: 1->2 yo'li 12 sonini, 1->3 yo'li 13 sonini beradi, 12+13=25.\n\n**2-misol:**\nKiritma: root = [4,9,0,5,1]\nNatija: 1026",
    starterCodeJs: 'function sumNumbers(root) {\n  // your code here\n}',
    starterCodePy: 'def sum_numbers(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int sumNumbers(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-014',
    title: 'Kasrli Xaltacha Masalasi',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "n ta buyumning og'irliklari weights va qiymatlari values massivlarida berilgan, xaltachaning sig'imi capacity berilgan. Har bir buyumning istalgan qismini olish mumkin. Xaltachaga solingan buyumlarning umumiy qiymatini maksimallashtiring va shu maksimal qiymatni qaytaring.\n\n**1-misol:**\nKiritma: weights = [10,20,30], values = [60,100,120], capacity = 50\nNatija: 240.0\nIzoh: Qiymat/og'irlik nisbati eng yuqori bo'lgan 1- va 2-buyumlar to'liq olinadi, 3-buyumdan esa qolgan 20 birlik sig'imga mos 2/3 qismi olinadi: 60+100+80=240.\n\n**2-misol:**\nKiritma: weights = [20,30], values = [100,120], capacity = 25\nNatija: 120.0",
    starterCodeJs: 'function fractionalKnapsack(weights, values, capacity) {\n  // your code here\n}',
    starterCodePy: 'def fractional_knapsack(weights, values, capacity):\n    # your code here\n    pass',
    starterCodeCpp: 'double fractionalKnapsack(vector<int>& weights, vector<int>& values, int capacity) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-015',
    title: 'Foydani Maksimallashtirish Uchun Ishlarni Rejalashtirish',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Har bir ish uchun muddat (deadline) va foyda (profit) massivlarida berilgan n ta ish mavjud. Har bir ish bittadan vaqt birligini oladi va faqat bitta ish bir vaqt birligida bajarilishi mumkin. Har bir ish o'z muddatigacha bajarilishi kerak. Bajarilgan ishlardan olinadigan maksimal umumiy foydani toping.\n\n**1-misol:**\nKiritma: deadlines = [4,1,1,1], profits = [20,10,40,30]\nNatija: 60\nIzoh: 3-ish (foyda 40) 1-vaqt birligida, 1-ish (foyda 20) 4-vaqt birligida bajariladi, jami 60.\n\n**2-misol:**\nKiritma: deadlines = [2,2,1], profits = [100,10,15]\nNatija: 115",
    starterCodeJs: 'function jobScheduling(deadlines, profits) {\n  // your code here\n}',
    starterCodePy: 'def job_scheduling(deadlines, profits):\n    # your code here\n    pass',
    starterCodeCpp: 'int jobScheduling(vector<int>& deadlines, vector<int>& profits) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-016',
    title: 'Gaz Stansiyasi Aylanma Marshruti',
    difficulty: 'MEDIUM',
    points: 37,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Doiraviy marshrutda joylashgan n ta gaz stansiyasi bor. gas[i] massivi har bir stansiyadagi yoqilg'i miqdorini, cost[i] massivi esa i-stansiyadan (i+1)-stansiyagacha borish uchun ketadigan yoqilg'ini bildiradi. Agar mashina qaysi stansiyadan boshlab butun doiraviy marshrutni bir marta to'liq aylanib chiqa olsa, o'sha boshlang'ich stansiya indeksini qaytaring; aks holda -1 qaytaring.\n\n**1-misol:**\nKiritma: gas = [1,2,3,4,5], cost = [3,4,5,1,2]\nNatija: 3\nIzoh: 3-indeksdan boshlab yoqilg'i har doim yetarli bo'ladi.\n\n**2-misol:**\nKiritma: gas = [2,3,4], cost = [3,4,3]\nNatija: -1",
    starterCodeJs: 'function canCompleteCircuit(gas, cost) {\n  // your code here\n}',
    starterCodePy: 'def can_complete_circuit(gas, cost):\n    # your code here\n    pass',
    starterCodeCpp: 'int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-017',
    title: 'Minimal Platformalar Sonini Topish',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Temir yo'l stansiyasiga keladigan poyezdlarning kelish vaqtlari arrival va jo'nash vaqtlari departure massivlarida berilgan. Bir vaqtning o'zida barcha poyezdlarga xizmat ko'rsatish uchun zarur bo'lgan minimal platformalar sonini toping.\n\n**1-misol:**\nKiritma: arrival = [900,940,950,1100,1500,1800], departure = [910,1200,1120,1130,1900,2000]\nNatija: 3\n\n**2-misol:**\nKiritma: arrival = [900,1100,1235], departure = [1000,1200,1240]\nNatija: 1",
    starterCodeJs: 'function minPlatforms(arrival, departure) {\n  // your code here\n}',
    starterCodePy: 'def min_platforms(arrival, departure):\n    # your code here\n    pass',
    starterCodeCpp: 'int minPlatforms(vector<int>& arrival, vector<int>& departure) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-018',
    title: 'Konfetlarni Adolatli Taqsimlash',
    difficulty: 'MEDIUM',
    points: 39,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "n ta bolaning reyting ballari ratings massivida berilgan. Har bir bolaga kamida bitta konfet berilishi kerak, shuningdek qo'shni bolalardan reytingi yuqoriroq bo'lgan bola ko'proq konfet olishi kerak. Bolalarga taqsimlanadigan minimal umumiy konfetlar sonini toping.\n\n**1-misol:**\nKiritma: ratings = [1,0,2]\nNatija: 5\nIzoh: Konfetlar taqsimoti [2,1,2] bo'ladi, jami 5.\n\n**2-misol:**\nKiritma: ratings = [1,2,2]\nNatija: 4",
    starterCodeJs: 'function candy(ratings) {\n  // your code here\n}',
    starterCodePy: 'def candy(ratings):\n    # your code here\n    pass',
    starterCodeCpp: 'int candy(vector<int>& ratings) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-019',
    title: "Massiv Bo'ylab Minimal Sakrashlar Soni",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Manfiy bo'lmagan butun sonlardan iborat nums massivi berilgan, bunda nums[i] i-indeksdan eng ko'p qancha uzoqlikka sakrash mumkinligini bildiradi. Massivning boshidan oxirigacha yetib borish uchun zarur bo'lgan minimal sakrashlar sonini toping.\n\n**1-misol:**\nKiritma: nums = [2,3,1,1,4]\nNatija: 2\nIzoh: Avval indeks 0 dan 1 ga, keyin 1 dan 4 ga sakrash orqali oxiriga yetib boriladi.\n\n**2-misol:**\nKiritma: nums = [2,3,0,1,4]\nNatija: 2",
    starterCodeJs: 'function jump(nums) {\n  // your code here\n}',
    starterCodePy: 'def jump(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int jump(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-020',
    title: 'Sovutish Davri Bilan Vazifalarni Rejalashtirish',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Katta harflar bilan belgilangan vazifalar massivi tasks va butun son n (sovutish davri) berilgan. Bir xil turdagi ikkita vazifa orasida kamida n vaqt birligi o'tishi kerak. Barcha vazifalarni bajarish uchun zarur bo'lgan minimal umumiy vaqt birliklarini toping (bo'sh turish vaqtlarini ham hisobga olib).\n\n**1-misol:**\nKiritma: tasks = ['A','A','A','B','B','B'], n = 2\nNatija: 8\nIzoh: Masalan A B idle A B idle A B tartibida bajariladi.\n\n**2-misol:**\nKiritma: tasks = ['A','A','A','B','B','B'], n = 0\nNatija: 6",
    starterCodeJs: 'function leastInterval(tasks, n) {\n  // your code here\n}',
    starterCodePy: 'def least_interval(tasks, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int leastInterval(vector<char>& tasks, int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-021',
    title: 'Sharlarni Yorish Uchun Minimal Strelkalar Soni',
    difficulty: 'MEDIUM',
    points: 37,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Har bir sharning gorizontal diapazoni [xstart, xend] ko'rinishida points massivida berilgan. Vertikal strelka otilganda, uning x koordinatasidagi diapazonga tegishli barcha sharlar yoriladi. Barcha sharlarni yorish uchun zarur bo'lgan minimal strelkalar sonini toping.\n\n**1-misol:**\nKiritma: points = [[10,16],[2,8],[1,6],[7,12]]\nNatija: 2\nIzoh: Bitta strelka x=6 da [2,8] va [1,6] sharlarini, ikkinchisi x=11 da [10,16] va [7,12] sharlarini yoradi.\n\n**2-misol:**\nKiritma: points = [[1,2],[3,4],[5,6],[7,8]]\nNatija: 4",
    starterCodeJs: 'function findMinArrowShots(points) {\n  // your code here\n}',
    starterCodePy: 'def find_min_arrow_shots(points):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMinArrowShots(vector<vector<int>>& points) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-022',
    title: 'Faoliyatlarni Tanlash Masalasi',
    difficulty: 'MEDIUM',
    points: 34,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Har birining boshlanish va tugash vaqtlari start va finish massivlarida berilgan n ta faoliyat mavjud. Bir vaqtning o'zida faqat bitta resurs ishlatilishi mumkin bo'lgani uchun, bir-biriga vaqt jihatidan mos kelmaydigan (overlap qilmaydigan) maksimal sonli faoliyatlarni tanlang va shu sonni qaytaring.\n\n**1-misol:**\nKiritma: start = [1,3,0,5,8,5], finish = [2,4,6,7,9,9]\nNatija: 4\n\n**2-misol:**\nKiritma: start = [1,2,3], finish = [2,3,4]\nNatija: 3",
    starterCodeJs: 'function maxActivities(start, finish) {\n  // your code here\n}',
    starterCodePy: 'def max_activities(start, finish):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxActivities(vector<int>& start, vector<int>& finish) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-023',
    title: 'Arqonlarni Minimal Xarajat Bilan Ulash',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Turli uzunlikdagi arqonlar ropes massivida berilgan. Ikki arqonni ulash narxi ularning uzunliklari yig'indisiga teng. Barcha arqonlarni bitta arqonga ulash uchun zarur bo'lgan minimal umumiy xarajatni toping.\n\n**1-misol:**\nKiritma: ropes = [4,3,2,6]\nNatija: 29\nIzoh: Avval 2 va 3 ulanadi (xarajat 5), keyin 5 va 4 ulanadi (xarajat 9), oxirida 9 va 6 ulanadi (xarajat 15), jami 5+9+15=29.\n\n**2-misol:**\nKiritma: ropes = [1,2,3,4,5]\nNatija: 33",
    starterCodeJs: 'function minCostToConnectRopes(ropes) {\n  // your code here\n}',
    starterCodePy: 'def min_cost_to_connect_ropes(ropes):\n    # your code here\n    pass',
    starterCodeCpp: 'int minCostToConnectRopes(vector<int>& ropes) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-024',
    title: 'Ikki Shahar Orasida Sayohat Xarajatini Minimallashtirish',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "2n kishidan iborat guruh bor, ularning har birini A yoki B shahriga yuborish kerak, aynan n kishi har bir shaharga borishi shart. i-kishini A shahriga yuborish narxi costs[i][0], B shahriga yuborish narxi costs[i][1] bilan berilgan. Barcha guruhni yuborish uchun zarur bo'lgan minimal umumiy xarajatni toping.\n\n**1-misol:**\nKiritma: costs = [[10,20],[30,200],[400,50],[30,20]]\nNatija: 110\n\n**2-misol:**\nKiritma: costs = [[259,770],[448,54],[926,667],[184,139],[840,118],[577,469]]\nNatija: 1859",
    starterCodeJs: 'function twoCitySchedCost(costs) {\n  // your code here\n}',
    starterCodePy: 'def two_city_sched_cost(costs):\n    # your code here\n    pass',
    starterCodeCpp: 'int twoCitySchedCost(vector<vector<int>>& costs) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-025',
    title: "Aksiyalarni Ko'p Marta Sotib Olish Va Sotish Orqali Maksimal Foyda",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "Har kungi aksiya narxlari prices massivida berilgan. Har kuni ko'pi bilan bitta aksiya sotib olish yoki sotish mumkin (bir vaqtning o'zida faqat bitta aksiyaga egalik qilish mumkin) va istalgancha marta savdo qilish mumkin. Olinishi mumkin bo'lgan maksimal umumiy foydani toping.\n\n**1-misol:**\nKiritma: prices = [7,1,5,3,6,4]\nNatija: 7\nIzoh: Har bir narx ko'tarilishidan foyda undirish orqali (masalan 1->5 va 3->6) jami 4+3=7 foyda olinadi.\n\n**2-misol:**\nKiritma: prices = [1,2,3,4,5]\nNatija: 4",
    starterCodeJs: 'function maxProfit(prices) {\n  // your code here\n}',
    starterCodePy: 'def max_profit(prices):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxProfit(vector<int>& prices) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-026',
    title: "Mijozlarni Xizmat Ko'rsatish Vaqtini Minimallashtirish",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ["Ochko\'zlik algoritmlari"],
    description: "n ta mijozga xizmat ko'rsatish uchun ketadigan vaqtlar serviceTimes massivida berilgan. Mijozlar birin-ketin xizmat ko'rsatiladi va har bir mijozning kutish vaqti undan oldin xizmat ko'rsatilgan barcha mijozlarning xizmat vaqtlari yig'indisiga teng. Mijozlarni shunday tartibga soling-ki, barcha mijozlarning umumiy kutish vaqti minimal bo'lsin va shu minimal qiymatni qaytaring.\n\n**1-misol:**\nKiritma: serviceTimes = [4,3,2]\nNatija: 7\nIzoh: Eng qisqa xizmat vaqtidan boshlab [2,3,4] tartibida xizmat ko'rsatilsa, kutish vaqtlari 0, 2, 5 bo'lib, yig'indisi 7 ga teng.\n\n**2-misol:**\nKiritma: serviceTimes = [1,2,3]\nNatija: 4",
    starterCodeJs: 'function minTotalWaitingTime(serviceTimes) {\n  // your code here\n}',
    starterCodePy: 'def min_total_waiting_time(service_times):\n    # your code here\n    pass',
    starterCodeCpp: 'int minTotalWaitingTime(vector<int>& serviceTimes) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-027',
    title: 'Merge Sort Algoritmini Amalga Oshirish',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan. Massivni merge sort (birlashtirib saralash) algoritmi yordamida o'sish tartibida saralang va saralangan massivni qaytaring.\n\n**1-misol:**\nKiritma: nums = [5,2,4,6,1,3]\nNatija: [1,2,3,4,5,6]\n\n**2-misol:**\nKiritma: nums = [3,3,1]\nNatija: [1,3,3]",
    starterCodeJs: 'function mergeSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def merge_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergeSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-028',
    title: 'Quicksort Algoritmini Amalga Oshirish',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan. Massivni quicksort (tezkor saralash) algoritmi yordamida, bo'lish (partition) usulidan foydalanib o'sish tartibida saralang va saralangan massivni qaytaring.\n\n**1-misol:**\nKiritma: nums = [10,7,8,9,1,5]\nNatija: [1,5,7,8,9,10]\n\n**2-misol:**\nKiritma: nums = [4,2,2,8,3]\nNatija: [2,2,3,4,8]",
    starterCodeJs: 'function quickSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def quick_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> quickSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-029',
    title: 'Aylantirilgan Saralangan Massivda Qidiruv',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Saralash va qidiruv'],
    description: "Avval o'sish tartibida saralangan, so'ngra noma'lum nuqtada aylantirilgan (rotate qilingan) takrorlanmas sonlardan iborat nums massivi va target soni berilgan. target ning massivdagi indeksini O(log n) vaqt murakkabligida toping, agar mavjud bo'lmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [4,5,6,7,0,1,2], target = 0\nNatija: 4\n\n**2-misol:**\nKiritma: nums = [4,5,6,7,0,1,2], target = 3\nNatija: -1",
    starterCodeJs: 'function search(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def search(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int search(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-030',
    title: "Massivda Cho'qqi Elementni Topish",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan, unda nums[-1] va nums[n] ni cheksiz kichik (-infinity) deb hisoblang. Cho'qqi elementi - qo'shni elementlaridan katta bo'lgan element. O(log n) vaqt murakkabligida ixtiyoriy bitta cho'qqi elementning indeksini toping.\n\n**1-misol:**\nKiritma: nums = [1,2,3,1]\nNatija: 2\nIzoh: nums[2]=3 qo'shnilaridan katta bo'lgani uchun cho'qqi hisoblanadi.\n\n**2-misol:**\nKiritma: nums = [1,2,1,3,5,6,4]\nNatija: 5",
    starterCodeJs: 'function findPeakElement(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_peak_element(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findPeakElement(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-031',
    title: "Bo'lish Usuli Orqali K-Chi Eng Katta Elementni Topish",
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Saralash va qidiruv'],
    description: "Saralanmagan butun sonlar massivi nums va butun son k berilgan. Massivdagi k-chi eng katta elementni quicksort'dagi bo'lish (partition/quickselect) usulidan foydalanib toping.\n\n**1-misol:**\nKiritma: nums = [3,2,1,5,6,4], k = 2\nNatija: 5\n\n**2-misol:**\nKiritma: nums = [3,2,3,1,2,4,5,5,6], k = 4\nNatija: 4",
    starterCodeJs: 'function findKthLargest(nums, k) {\n  // your code here\n}',
    starterCodePy: 'def find_kth_largest(nums, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int findKthLargest(vector<int>& nums, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-032',
    title: 'Ikki Saralangan Massivning Medianasini Topish',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Saralash va qidiruv'],
    description: "Ikkita o'sish tartibida saralangan nums1 va nums2 massivlari berilgan. Ikkala massivni birlashtirgandagi medianani toping. Yechim ikkilik qidiruv yordamida O(log(m+n)) vaqt murakkabligida amalga oshirilishi kerak.\n\n**1-misol:**\nKiritma: nums1 = [1,3], nums2 = [2]\nNatija: 2.0\n\n**2-misol:**\nKiritma: nums1 = [1,2], nums2 = [3,4]\nNatija: 2.5",
    starterCodeJs: 'function findMedianSortedArrays(nums1, nums2) {\n  // your code here\n}',
    starterCodePy: 'def find_median_sorted_arrays(nums1, nums2):\n    # your code here\n    pass',
    starterCodeCpp: 'double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-033',
    title: "O'zidan Keyingi Kichik Elementlar Sonini Hisoblash",
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan. Har bir indeks i uchun, i dan o'ngda joylashgan va nums[i] dan kichik bo'lgan elementlar sonini hisoblab, natijalar massivini qaytaring.\n\n**1-misol:**\nKiritma: nums = [5,2,6,1]\nNatija: [2,1,1,0]\nIzoh: 5 dan o'ngda undan kichik 2 ta son (2 va 1) bor, 2 dan o'ngda kichik 1 ta (1), 6 dan o'ngda kichik 1 ta (1), 1 dan o'ngda kichik yo'q.\n\n**2-misol:**\nKiritma: nums = [-1,-1]\nNatija: [0,0]",
    starterCodeJs: 'function countSmaller(nums) {\n  // your code here\n}',
    starterCodePy: 'def count_smaller(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countSmaller(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-034',
    title: 'Saralangan Massivda Elementning Boshlanish Va Tugash Pozitsiyasini Topish',
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Saralash va qidiruv'],
    description: "O'sish tartibida saralangan butun sonlar massivi nums va target soni berilgan. target ning massivdagi birinchi va oxirgi uchrash indekslarini O(log n) vaqt murakkabligida toping. Agar target massivda mavjud bo'lmasa, [-1,-1] qaytaring.\n\n**1-misol:**\nKiritma: nums = [5,7,7,8,8,10], target = 8\nNatija: [3,4]\n\n**2-misol:**\nKiritma: nums = [5,7,7,8,8,10], target = 6\nNatija: [-1,-1]",
    starterCodeJs: 'function searchRange(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def search_range(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> searchRange(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-035',
    title: 'Aylantirilgan Saralangan Massivda Minimal Elementni Topish',
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Saralash va qidiruv'],
    description: "Avval o'sish tartibida saralangan, so'ngra noma'lum nuqtada aylantirilgan takrorlanmas sonlardan iborat nums massivi berilgan. Massivdagi minimal elementni O(log n) vaqt murakkabligida toping.\n\n**1-misol:**\nKiritma: nums = [3,4,5,1,2]\nNatija: 1\n\n**2-misol:**\nKiritma: nums = [4,5,6,7,0,1,2]\nNatija: 0",
    starterCodeJs: 'function findMin(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_min(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMin(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-036',
    title: 'Reyting Asosida H-Indeksni Hisoblash',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Saralash va qidiruv'],
    description: "Olimning har bir maqolasi olgan iqtiboslar sonini ifodalovchi citations massivi berilgan. Olimning h-indeksini hisoblang - h-indeks shunday eng katta h qiymatiki, olimning kamida h ta maqolasi kamida h martadan iqtibos olgan bo'lsin.\n\n**1-misol:**\nKiritma: citations = [3,0,6,1,5]\nNatija: 3\nIzoh: 3 ta maqola kamida 3 martadan iqtibos olgan (3, 6, 5), shuning uchun h-indeks 3 ga teng.\n\n**2-misol:**\nKiritma: citations = [1,3,1]\nNatija: 1",
    starterCodeJs: 'function hIndex(citations) {\n  // your code here\n}',
    starterCodePy: 'def h_index(citations):\n    # your code here\n    pass',
    starterCodeCpp: 'int hIndex(vector<int>& citations) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-037',
    title: 'Ikki Saralangan Massivni Birlashtirish',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Saralash va qidiruv'],
    description: "O'sish tartibida saralangan nums1 (oxirida m ta elementdan keyin bo'sh joy bor, umumiy uzunligi m+n) va nums2 (n ta element) massivlari berilgan. nums2 ni nums1 ichiga shunday birlashtiringki, nums1 bitta saralangan massivga aylansin (natija nums1 ichida saqlanadi).\n\n**1-misol:**\nKiritma: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3\nNatija: [1,2,2,3,5,6]\n\n**2-misol:**\nKiritma: nums1 = [1], m = 1, nums2 = [], n = 0\nNatija: [1]",
    starterCodeJs: 'function merge(nums1, m, nums2, n) {\n  // your code here\n}',
    starterCodePy: 'def merge(nums1, m, nums2, n):\n    # your code here\n    pass',
    starterCodeCpp: 'void merge(vector<int>& nums1, int m, vector<int>& nums2, int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-038',
    title: 'Eng Qisqa Saralanmagan Kichik Massivni Topish',
    difficulty: 'MEDIUM',
    points: 39,
    tags: ['Saralash va qidiruv'],
    description: "Butun sonlar massivi nums berilgan. Massivning eng qisqa uzluksiz kichik qismini (subarray) toping, agar shu qismni o'sish tartibida saralasangiz, butun massiv o'sish tartibida saralangan bo'lib qoladi. Shu kichik qismning uzunligini qaytaring.\n\n**1-misol:**\nKiritma: nums = [2,6,4,8,10,9,15]\nNatija: 5\nIzoh: [6,4,8,10,9] qismini saralash butun massivni saralangan holga keltiradi.\n\n**2-misol:**\nKiritma: nums = [1,2,3,4]\nNatija: 0",
    starterCodeJs: 'function findUnsortedSubarray(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_unsorted_subarray(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findUnsortedSubarray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-039',
    title: 'Yagona Son II',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan, unda har bir element aynan uch marta takrorlanadi, faqat bitta element bir marta uchraydi. Shu yagona elementni bit amallari yordamida O(n) vaqt va O(1) qo'shimcha xotira bilan toping.\n\n**1-misol:**\nKiritma: nums = [2,2,3,2]\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [0,1,0,1,0,1,99]\nNatija: 99",
    starterCodeJs: 'function singleNumber(nums) {\n  // your code here\n}',
    starterCodePy: 'def single_number(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int singleNumber(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-040',
    title: 'Ikkita Noyob Sonni Topish',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan, unda aynan ikkita element bir marta, qolgan barcha elementlar esa ikki martadan uchraydi. Shu ikkita noyob elementni bit amallari (XOR) yordamida toping va ixtiyoriy tartibda qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,2,1,3,2,5]\nNatija: [3,5]\n\n**2-misol:**\nKiritma: nums = [-1,0]\nNatija: [-1,0]",
    starterCodeJs: 'function singleNumberIII(nums) {\n  // your code here\n}',
    starterCodePy: 'def single_number_iii(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> singleNumberIII(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-041',
    title: '0 Dan N Gachagi Sonlar Uchun Bitlar Sonini Hisoblash',
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Bit amallari'],
    description: "Manfiy bo'lmagan butun son n berilgan. 0 dan n gacha (n ni ham qo'shgan holda) bo'lgan har bir son uchun ikkilik ko'rinishidagi 1 raqamlari sonini hisoblab, natijalar massivini qaytaring.\n\n**1-misol:**\nKiritma: n = 2\nNatija: [0,1,1]\nIzoh: 0->0, 1->1, 2->10, mos ravishda 0,1,1 ta birlik bit.\n\n**2-misol:**\nKiritma: n = 5\nNatija: [0,1,1,2,1,2]",
    starterCodeJs: 'function countBits(n) {\n  // your code here\n}',
    starterCodePy: 'def count_bits(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> countBits(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-042',
    title: "Qo'shish Amalisiz Ikkita Sonni Qo'shish",
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Bit amallari'],
    description: "Ikkita butun son a va b berilgan. + yoki - arifmetik amallaridan foydalanmasdan, faqat bit amallari (AND, XOR, siljitish) yordamida ularning yig'indisini hisoblang.\n\n**1-misol:**\nKiritma: a = 1, b = 2\nNatija: 3\n\n**2-misol:**\nKiritma: a = 2, b = 3\nNatija: 5",
    starterCodeJs: 'function getSum(a, b) {\n  // your code here\n}',
    starterCodePy: 'def get_sum(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'int getSum(int a, int b) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-043',
    title: '32-Bitli Sonning Bitlarini Teskari Aylantirish',
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Bit amallari'],
    description: "32 bitli imzosiz butun son n berilgan. Uning ikkilik ko'rinishidagi bitlarini teskari tartibga keltirib, hosil bo'lgan yangi 32 bitli sonni qaytaring.\n\n**1-misol:**\nKiritma: n = 43261596 (ikkilik: 00000010100101000001111010011100)\nNatija: 964176192 (ikkilik: 00111001011110000010100101000000)\n\n**2-misol:**\nKiritma: n = 0\nNatija: 0",
    starterCodeJs: 'function reverseBits(n) {\n  // your code here\n}',
    starterCodePy: 'def reverse_bits(n):\n    # your code here\n    pass',
    starterCodeCpp: 'uint32_t reverseBits(uint32_t n) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-044',
    title: 'Diapazondagi Sonlarning Bitli AND Natijasi',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Bit amallari'],
    description: "Ikkita butun son left va right (left <= right) berilgan. [left, right] oralig'idagi barcha sonlarning bitli AND (&) natijasini hisoblang.\n\n**1-misol:**\nKiritma: left = 5, right = 7\nNatija: 4\nIzoh: 5 & 6 & 7 = 4.\n\n**2-misol:**\nKiritma: left = 1, right = 2147483647\nNatija: 0",
    starterCodeJs: 'function rangeBitwiseAnd(left, right) {\n  // your code here\n}',
    starterCodePy: 'def range_bitwise_and(left, right):\n    # your code here\n    pass',
    starterCodeCpp: 'int rangeBitwiseAnd(int left, int right) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-045',
    title: "Bitmask Yordamida Barcha Kichik To'plamlarni Generatsiya Qilish",
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Bit amallari'],
    description: "Takrorlanmas butun sonlardan iborat nums massivi berilgan. Bitmask usulidan foydalanib, massivning barcha mumkin bo'lgan kichik to'plamlarini (bo'sh to'plam va massivning o'zini ham qo'shgan holda) hosil qiling va qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,2,3]\nNatija: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]\n\n**2-misol:**\nKiritma: nums = [0]\nNatija: [[],[0]]",
    starterCodeJs: 'function subsets(nums) {\n  // your code here\n}',
    starterCodePy: 'def subsets(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> subsets(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-046',
    title: 'Massivdagi Ikkita Sonning Maksimal XOR Qiymati',
    difficulty: 'MEDIUM',
    points: 44,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan. Massivdagi ixtiyoriy ikkita elementning XOR (a XOR b) qiymatlari orasidan eng kattasini toping.\n\n**1-misol:**\nKiritma: nums = [3,10,5,25,2,8]\nNatija: 28\nIzoh: 5 XOR 25 = 28, bu eng katta qiymat hisoblanadi.\n\n**2-misol:**\nKiritma: nums = [14,70,53,83,49,91,36,80,92,51,66,70]\nNatija: 127",
    starterCodeJs: 'function findMaximumXOR(nums) {\n  // your code here\n}',
    starterCodePy: 'def find_maximum_xor(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int findMaximumXOR(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-047',
    title: "Massivdagi Barcha Juftliklarning Umumiy Hamming Masofasi",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Bit amallari'],
    description: "Butun sonlar massivi nums berilgan. Ikki sonning Hamming masofasi - ularning ikkilik ko'rinishida farq qiladigan bit pozitsiyalari soni. Massivdagi barcha (i, j) juftliklari (i < j) uchun Hamming masofalarining yig'indisini toping.\n\n**1-misol:**\nKiritma: nums = [4,14,2]\nNatija: 6\nIzoh: 4(100), 14(1110), 2(010) juftliklarining Hamming masofalari mos ravishda 2, 2, 2 bo'lib, yig'indisi 6.\n\n**2-misol:**\nKiritma: nums = [4,14,4]\nNatija: 4",
    starterCodeJs: 'function totalHammingDistance(nums) {\n  // your code here\n}',
    starterCodePy: 'def total_hamming_distance(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int totalHammingDistance(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-048',
    title: "Bir Xil Sonli Birlarga Ega Bo'lgan Keyingi Kattaroq Sonni Topish",
    difficulty: 'MEDIUM',
    points: 43,
    tags: ['Bit amallari'],
    description: "Manfiy bo'lmagan butun son n berilgan. n dan katta va uning ikkilik ko'rinishidagi 1 raqamlari soni bilan bir xil sonli 1 raqamlariga ega bo'lgan eng kichik sonni toping.\n\n**1-misol:**\nKiritma: n = 6 (ikkilik: 110)\nNatija: 9 (ikkilik: 1001)\n\n**2-misol:**\nKiritma: n = 1 (ikkilik: 1)\nNatija: 2 (ikkilik: 10)",
    starterCodeJs: 'function nextGreaterWithSameBits(n) {\n  // your code here\n}',
    starterCodePy: 'def next_greater_with_same_bits(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long nextGreaterWithSameBits(long n) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-049',
    title: 'Gray Kodini Generatsiya Qilish',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Bit amallari'],
    description: "Butun son n berilgan. n bitli Gray kod ketma-ketligini hosil qiling - bu shunday ketma-ketlikki, unda 0 dan 2^n - 1 gachagi barcha sonlar mavjud bo'lib, ketma-ket ikki son ikkilik ko'rinishida faqat bitta bit bilan farq qiladi.\n\n**1-misol:**\nKiritma: n = 2\nNatija: [0,1,3,2]\nIzoh: Ikkilik ko'rinishlari 00,01,11,10 bo'lib, har bir qo'shni juftlik faqat bitta bit bilan farq qiladi.\n\n**2-misol:**\nKiritma: n = 1\nNatija: [0,1]",
    starterCodeJs: 'function grayCode(n) {\n  // your code here\n}',
    starterCodePy: 'def gray_code(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> grayCode(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-d-050',
    title: "Sonlarni Siljitish Amallari Yordamida Ko'paytirish",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Bit amallari'],
    description: "Ikkita manfiy bo'lmagan butun son a va b berilgan. * (ko'paytirish) amalidan foydalanmasdan, faqat bitli siljitish va qo'shish amallaridan foydalanib (rus dehqonlari usuli), a va b ning ko'paytmasini hisoblang.\n\n**1-misol:**\nKiritma: a = 5, b = 6\nNatija: 30\n\n**2-misol:**\nKiritma: a = 7, b = 3\nNatija: 21",
    starterCodeJs: 'function multiplyUsingBitShifts(a, b) {\n  // your code here\n}',
    starterCodePy: 'def multiply_using_bit_shifts(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'long multiplyUsingBitShifts(long a, long b) {\n    // your code here\n}',
  },
];
