export const problems = [
  {
    key: 'medium-c-001',
    title: 'Zinapoyadan Ko\'tarilish',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Dinamik dasturlash'],
    description: "n ta pog'onadan iborat zinapoyadan ko'tarilyapsiz. Har bir qadamda 1 yoki 2 pog'onaga ko'tarilishingiz mumkin. Zinapoyaning yuqorisiga chiqishning nechta turli usuli borligini toping.\n\n**1-misol:**\nKiritma: n = 2\nNatija: 2\nIzoh: (1+1) yoki (2) - ikki xil usul mavjud.\n\n**2-misol:**\nKiritma: n = 3\nNatija: 3",
    starterCodeJs: 'function climbStairs(n) {\n  // your code here\n}',
    starterCodePy: 'def climb_stairs(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int climbStairs(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-002',
    title: 'Uch Xil Qadam Bilan Zinapoya',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Dinamik dasturlash'],
    description: "n ta pog'onadan iborat zinapoya berilgan. Har bir qadamda 1, 2 yoki 3 pog'onaga ko'tarilish mumkin. Zinapoyaning yuqorisiga chiqishning nechta usuli borligini toping.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 4\n\n**2-misol:**\nKiritma: n = 4\nNatija: 7",
    starterCodeJs: 'function climbStairsThreeSteps(n) {\n  // your code here\n}',
    starterCodePy: 'def climb_stairs_three_steps(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int climbStairsThreeSteps(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-003',
    title: 'Uy O\'g\'risi',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Dinamik dasturlash'],
    description: "Ko'cha bo'ylab joylashgan uylarda pul saqlanadi, nums massivi har bir uydagi pul miqdorini bildiradi. Qo'shni ikkita uyni bir kechada o'g'irlab bo'lmaydi (signalizatsiya ishga tushadi). O'g'irlanadigan maksimal umumiy pul miqdorini toping.\n\n**1-misol:**\nKiritma: nums = [1,2,3,1]\nNatija: 4\nIzoh: 1-uy va 3-uy (indeks 0 va 2) tanlansa 1+3=4 bo'ladi.\n\n**2-misol:**\nKiritma: nums = [2,7,9,3,1]\nNatija: 12",
    starterCodeJs: 'function rob(nums) {\n  // your code here\n}',
    starterCodePy: 'def rob(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int rob(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-004',
    title: 'Uy O\'g\'risi II (Doiraviy Ko\'cha)',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Dinamik dasturlash'],
    description: "Uylar doiraviy ko'cha bo'ylab joylashgan, ya'ni birinchi va oxirgi uy ham bir-biriga qo'shni hisoblanadi. Qo'shni ikkita uyni o'g'irlab bo'lmaydi. O'g'irlanadigan maksimal umumiy pul miqdorini toping.\n\n**1-misol:**\nKiritma: nums = [2,3,2]\nNatija: 3\n\n**2-misol:**\nKiritma: nums = [1,2,3,1]\nNatija: 4",
    starterCodeJs: 'function robCircular(nums) {\n  // your code here\n}',
    starterCodePy: 'def rob_circular(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int robCircular(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-005',
    title: 'Eng Kam Sonli Tangalar',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Dinamik dasturlash'],
    description: "coins massivida turli nominaldagi tangalar va amount maqsadli summa berilgan. amount summasini yig'ish uchun zarur bo'lgan eng kam sonli tangalar sonini toping. Agar bu mumkin bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: coins = [1,2,5], amount = 11\nNatija: 3\nIzoh: 11 = 5+5+1.\n\n**2-misol:**\nKiritma: coins = [2], amount = 3\nNatija: -1",
    starterCodeJs: 'function coinChange(coins, amount) {\n  // your code here\n}',
    starterCodePy: 'def coin_change(coins, amount):\n    # your code here\n    pass',
    starterCodeCpp: 'int coinChange(vector<int>& coins, int amount) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-006',
    title: 'Tangalar Bilan To\'lash Usullari',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Dinamik dasturlash'],
    description: "coins massivida turli nominaldagi cheksiz sondagi tangalar va amount maqsadli summa berilgan. amount summasini aynan yig'adigan turli tanga kombinatsiyalari sonini toping (tartib muhim emas).\n\n**1-misol:**\nKiritma: coins = [1,2,5], amount = 5\nNatija: 4\nIzoh: (5), (1,1,1,1,1), (1,1,1,2), (1,2,2) kombinatsiyalari.\n\n**2-misol:**\nKiritma: coins = [2], amount = 3\nNatija: 0",
    starterCodeJs: 'function coinChangeWays(coins, amount) {\n  // your code here\n}',
    starterCodePy: 'def coin_change_ways(coins, amount):\n    # your code here\n    pass',
    starterCodeCpp: 'int coinChangeWays(vector<int>& coins, int amount) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-007',
    title: 'Eng Uzun O\'suvchi Qism Ketma-ketlik',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Dinamik dasturlash'],
    description: "nums butun sonlar massivi berilgan. Eng uzun qat'iy o'suvchi qism ketma-ketlikning uzunligini toping (elementlar massivda ketma-ket bo'lishi shart emas, lekin tartib saqlanishi kerak).\n\n**1-misol:**\nKiritma: nums = [10,9,2,5,3,7,101,18]\nNatija: 4\nIzoh: [2,3,7,101] eng uzun o'suvchi qism ketma-ketlik.\n\n**2-misol:**\nKiritma: nums = [0,1,0,3,2,3]\nNatija: 4",
    starterCodeJs: 'function lengthOfLIS(nums) {\n  // your code here\n}',
    starterCodePy: 'def length_of_lis(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int lengthOfLIS(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-008',
    title: 'Panjarada Noyob Yo\'llar',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Dinamik dasturlash'],
    description: "m x n o'lchamli panjaraning yuqori chap burchagida robot turibdi. Robot faqat o'ngga yoki pastga siljiy oladi. Robot pastki o'ng burchakka yetib borishning nechta noyob yo'li borligini toping.\n\n**1-misol:**\nKiritma: m = 3, n = 2\nNatija: 3\n\n**2-misol:**\nKiritma: m = 3, n = 3\nNatija: 6",
    starterCodeJs: 'function uniquePaths(m, n) {\n  // your code here\n}',
    starterCodePy: 'def unique_paths(m, n):\n    # your code here\n    pass',
    starterCodeCpp: 'int uniquePaths(int m, int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-009',
    title: 'To\'siqlar Bilan Noyob Yo\'llar',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Dinamik dasturlash'],
    description: "m x n panjara berilgan, unda ba'zi katakchalar to'siq (1) bilan belgilangan, qolganlari bo'sh (0). Robot yuqori chap burchakdan pastki o'ng burchakka faqat o'ngga yoki pastga siljib boradi va to'siqli katakchalardan o'ta olmaydi. Noyob yo'llar sonini toping.\n\n**1-misol:**\nKiritma: grid = [[0,0,0],[0,1,0],[0,0,0]]\nNatija: 2\n\n**2-misol:**\nKiritma: grid = [[0,1],[0,0]]\nNatija: 1",
    starterCodeJs: 'function uniquePathsWithObstacles(grid) {\n  // your code here\n}',
    starterCodePy: 'def unique_paths_with_obstacles(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int uniquePathsWithObstacles(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-010',
    title: 'Panjarada Minimal Yo\'l Yig\'indisi',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Dinamik dasturlash'],
    description: "m x n panjarada har bir katakcha manfiy bo'lmagan songa ega. Yuqori chap burchakdan pastki o'ng burchakka faqat o'ngga yoki pastga siljib borilganda, yo'l bo'ylab yig'iladigan sonlar yig'indisi minimal bo'lgan qiymatni toping.\n\n**1-misol:**\nKiritma: grid = [[1,3,1],[1,5,1],[4,2,1]]\nNatija: 7\n\n**2-misol:**\nKiritma: grid = [[1,2,3],[4,5,6]]\nNatija: 12",
    starterCodeJs: 'function minPathSum(grid) {\n  // your code here\n}',
    starterCodePy: 'def min_path_sum(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int minPathSum(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-011',
    title: 'Tahrirlash Masofasi',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Dinamik dasturlash'],
    description: "word1 va word2 ikkita satr berilgan. word1 ni word2 ga aylantirish uchun zarur bo'lgan minimal amallar sonini toping. Ruxsat etilgan amallar: bitta belgini qo'shish, o'chirish yoki almashtirish.\n\n**1-misol:**\nKiritma: word1 = 'horse', word2 = 'ros'\nNatija: 3\nIzoh: horse -> rorse -> rose -> ros.\n\n**2-misol:**\nKiritma: word1 = 'intention', word2 = 'execution'\nNatija: 5",
    starterCodeJs: 'function minDistance(word1, word2) {\n  // your code here\n}',
    starterCodePy: 'def min_distance(word1, word2):\n    # your code here\n    pass',
    starterCodeCpp: 'int minDistance(string word1, string word2) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-012',
    title: 'Eng Uzun Umumiy Qism Ketma-ketlik',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Dinamik dasturlash'],
    description: "text1 va text2 ikkita satr berilgan. Ularning eng uzun umumiy qism ketma-ketligining uzunligini toping (elementlar ketma-ket kelishi shart emas, lekin tartib saqlanishi kerak). Agar umumiy qism ketma-ketlik bo'lmasa, 0 qaytaring.\n\n**1-misol:**\nKiritma: text1 = 'abcde', text2 = 'ace'\nNatija: 3\n\n**2-misol:**\nKiritma: text1 = 'abc', text2 = 'def'\nNatija: 0",
    starterCodeJs: 'function longestCommonSubsequence(text1, text2) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_subsequence(text1, text2):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestCommonSubsequence(string text1, string text2) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-013',
    title: 'Massivni Teng Ikki Qismga Bo\'lish',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Dinamik dasturlash'],
    description: "nums musbat butun sonlar massivi berilgan. Massivni yig'indilari teng bo'lgan ikkita qism to'plamga bo'lish mumkinligini aniqlang.\n\n**1-misol:**\nKiritma: nums = [1,5,11,5]\nNatija: true\nIzoh: [1,5,5] va [11] yig'indilari teng (11=11).\n\n**2-misol:**\nKiritma: nums = [1,2,3,5]\nNatija: false",
    starterCodeJs: 'function canPartition(nums) {\n  // your code here\n}',
    starterCodePy: 'def can_partition(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canPartition(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-014',
    title: 'Kodni Ochish Usullari Soni',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Dinamik dasturlash'],
    description: "Faqat raqamlardan iborat s satri berilgan, unda 'A'-'Z' harflari '1'-'26' raqamlariga mos keladi. s ni necha xil usulda dekodlash mumkinligini toping.\n\n**1-misol:**\nKiritma: s = '226'\nNatija: 3\nIzoh: '2,2,6', '22,6', '2,26' usullari mavjud.\n\n**2-misol:**\nKiritma: s = '06'\nNatija: 0\nIzoh: '06' harfga mos kelmaydi, chunki yetakchi nol bilan boshlanadi.",
    starterCodeJs: 'function numDecodings(s) {\n  // your code here\n}',
    starterCodePy: 'def num_decodings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int numDecodings(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-015',
    title: 'Sakrash O\'yini: Oxirgi Indeksga Yetib Borish',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Dinamik dasturlash'],
    description: "nums massivi berilgan, bunda nums[i] i-indeksdan qilinishi mumkin bo'lgan maksimal sakrash uzunligini bildiradi. 0-indeksdan boshlab, massivning oxirgi indeksiga yetib borish mumkinligini aniqlang.\n\n**1-misol:**\nKiritma: nums = [2,3,1,1,4]\nNatija: true\n\n**2-misol:**\nKiritma: nums = [3,2,1,0,4]\nNatija: false",
    starterCodeJs: 'function canJump(nums) {\n  // your code here\n}',
    starterCodePy: 'def can_jump(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canJump(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-016',
    title: 'Sakrash O\'yini: Minimal Sakrashlar Soni',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Dinamik dasturlash'],
    description: "nums massivi berilgan, bunda nums[i] i-indeksdan qilinishi mumkin bo'lgan maksimal sakrash uzunligini bildiradi. 0-indeksdan oxirgi indeksga yetib borish uchun zarur bo'lgan minimal sakrashlar sonini toping (oxirgi indeksga yetib borish har doim mumkin deb hisoblanadi).\n\n**1-misol:**\nKiritma: nums = [2,3,1,1,4]\nNatija: 2\n\n**2-misol:**\nKiritma: nums = [2,3,0,1,4]\nNatija: 2",
    starterCodeJs: 'function jump(nums) {\n  // your code here\n}',
    starterCodePy: 'def jump(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int jump(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-017',
    title: 'Maksimal Ko\'paytmali Qism Massiv',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Dinamik dasturlash'],
    description: "nums butun sonlar massivi berilgan (manfiy sonlarni ham o'z ichiga olishi mumkin). Ketma-ket elementlardan tuzilgan qism massivning maksimal ko'paytmasini toping.\n\n**1-misol:**\nKiritma: nums = [2,3,-2,4]\nNatija: 6\n\n**2-misol:**\nKiritma: nums = [-2,0,-1]\nNatija: 0",
    starterCodeJs: 'function maxProduct(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_product(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxProduct(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-018',
    title: 'Matnni Lug\'at So\'zlariga Bo\'lish',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Dinamik dasturlash'],
    description: "s satri va wordDict lug'at so'zlari ro'yxati berilgan. s ni bo'sh joy bilan ajratilgan bir yoki bir nechta lug'at so'zlaridan iborat ketma-ketlikka bo'lish mumkinligini aniqlang (bir xil so'zni bir necha marta ishlatish mumkin).\n\n**1-misol:**\nKiritma: s = 'leetcode', wordDict = ['leet','code']\nNatija: true\n\n**2-misol:**\nKiritma: s = 'catsandog', wordDict = ['cats','dog','sand','and','cat']\nNatija: false",
    starterCodeJs: 'function wordBreak(s, wordDict) {\n  // your code here\n}',
    starterCodePy: 'def word_break(s, word_dict):\n    # your code here\n    pass',
    starterCodeCpp: 'bool wordBreak(string s, vector<string>& wordDict) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-019',
    title: 'Maksimal Qism Massiv Yig\'indisi',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Dinamik dasturlash'],
    description: "nums butun sonlar massivi berilgan (manfiy sonlarni ham o'z ichiga olishi mumkin). Ketma-ket elementlardan tuzilgan qism massivning maksimal yig'indisini toping.\n\n**1-misol:**\nKiritma: nums = [-2,1,-3,4,-1,2,1,-5,4]\nNatija: 6\nIzoh: [4,-1,2,1] qism massiv yig'indisi eng katta.\n\n**2-misol:**\nKiritma: nums = [1]\nNatija: 1",
    starterCodeJs: 'function maxSubArray(nums) {\n  // your code here\n}',
    starterCodePy: 'def max_sub_array(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int maxSubArray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-020',
    title: 'Eng Uzun Palindromik Qism Qator',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Dinamik dasturlash'],
    description: "s satri berilgan. s ichidagi eng uzun palindromik qism qatorni toping (satr chapdan o'ngga va o'ngdan chapga bir xil o'qilsa, u palindrom hisoblanadi).\n\n**1-misol:**\nKiritma: s = 'babad'\nNatija: 'bab'\nIzoh: 'aba' ham to'g'ri javob hisoblanadi.\n\n**2-misol:**\nKiritma: s = 'cbbd'\nNatija: 'bb'",
    starterCodeJs: 'function longestPalindrome(s) {\n  // your code here\n}',
    starterCodePy: 'def longest_palindrome(s):\n    # your code here\n    pass',
    starterCodeCpp: 'string longestPalindrome(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-021',
    title: 'Uchburchakda Minimal Yo\'l Yig\'indisi',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Dinamik dasturlash'],
    description: "triangle - sonlar uchburchagi (massivlar massivi) berilgan. Uchburchakning yuqorisidan pastigacha, har bir qadamda faqat pastki qatordagi qo'shni elementga o'tib, yig'iladigan sonlar yig'indisi minimal bo'lgan yo'lni toping.\n\n**1-misol:**\nKiritma: triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]\nNatija: 11\nIzoh: 2+3+5+1=11.\n\n**2-misol:**\nKiritma: triangle = [[-10]]\nNatija: -10",
    starterCodeJs: 'function minimumTotal(triangle) {\n  // your code here\n}',
    starterCodePy: 'def minimum_total(triangle):\n    # your code here\n    pass',
    starterCodeCpp: 'int minimumTotal(vector<vector<int>>& triangle) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-022',
    title: 'Mukammal Kvadratlar Yig\'indisi',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Dinamik dasturlash'],
    description: "n butun soni berilgan. n ni mukammal kvadrat sonlar (1, 4, 9, 16, ...) yig'indisi sifatida ifodalash uchun zarur bo'lgan eng kam sonli qo'shiluvchilar sonini toping.\n\n**1-misol:**\nKiritma: n = 12\nNatija: 3\nIzoh: 12 = 4+4+4.\n\n**2-misol:**\nKiritma: n = 13\nNatija: 2\nIzoh: 13 = 4+9.",
    starterCodeJs: 'function numSquares(n) {\n  // your code here\n}',
    starterCodePy: 'def num_squares(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int numSquares(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-023',
    title: 'Eng Uzun Umumiy Qism Qator (Substring)',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Dinamik dasturlash'],
    description: "text1 va text2 ikkita satr berilgan. Ularning eng uzun umumiy qism qatorining (substring, ya'ni ketma-ket kelgan belgilar) uzunligini toping.\n\n**1-misol:**\nKiritma: text1 = 'abcdef', text2 = 'zabcx'\nNatija: 3\nIzoh: umumiy qism qator 'abc'.\n\n**2-misol:**\nKiritma: text1 = 'abc', text2 = 'def'\nNatija: 0",
    starterCodeJs: 'function longestCommonSubstring(text1, text2) {\n  // your code here\n}',
    starterCodePy: 'def longest_common_substring(text1, text2):\n    # your code here\n    pass',
    starterCodeCpp: 'int longestCommonSubstring(string text1, string text2) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-024',
    title: '2xN Xonani Domino Bilan Yopish',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Dinamik dasturlash'],
    description: "2 x n o'lchamli taxtacha berilgan. Uni 1x2 o'lchamli domino bo'laklari bilan (gorizontal yoki vertikal holatda) to'liq yopishning nechta usuli borligini toping.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 3\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function numTilings(n) {\n  // your code here\n}',
    starterCodePy: 'def num_tilings(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int numTilings(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-025',
    title: '0/1 Ryukzak Masalasi',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Dinamik dasturlash'],
    description: "n ta buyum berilgan, har birining weights[i] og'irligi va values[i] qiymati bor. Ryukzak sig'imi capacity dan oshmagan holda, har bir buyumni ko'pi bilan bir marta olib, umumiy qiymatni maksimal qilish mumkin bo'lgan natijani toping.\n\n**1-misol:**\nKiritma: weights = [1,3,4,5], values = [1,4,5,7], capacity = 7\nNatija: 9\nIzoh: og'irligi 3 (qiymati 4) va og'irligi 4 (qiymati 5) bo'lgan buyumlar tanlanadi.\n\n**2-misol:**\nKiritma: weights = [2,3,4], values = [3,4,5], capacity = 5\nNatija: 7",
    starterCodeJs: 'function knapsack(weights, values, capacity) {\n  // your code here\n}',
    starterCodePy: 'def knapsack(weights, values, capacity):\n    # your code here\n    pass',
    starterCodeCpp: 'int knapsack(vector<int>& weights, vector<int>& values, int capacity) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-026',
    title: 'Orollar Soni',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Grafiklar'],
    description: "grid - '1' (quruqlik) va '0' (suv) belgilaridan iborat 2 o'lchamli panjara berilgan. Faqat gorizontal yoki vertikal yo'nalishda bog'langan quruqlik katakchalari bitta orolni tashkil qiladi. Panjaradagi orollar sonini toping.\n\n**1-misol:**\nKiritma: grid = [['1','1','0'],['0','1','0'],['0','0','1']]\nNatija: 2\n\n**2-misol:**\nKiritma: grid = [['1','1','1'],['0','1','0'],['1','1','1']]\nNatija: 1",
    starterCodeJs: 'function numIslands(grid) {\n  // your code here\n}',
    starterCodePy: 'def num_islands(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int numIslands(vector<vector<char>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-027',
    title: 'Kurslarni Tugatish Mumkinmi',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Grafiklar'],
    description: "numCourses ta kurs (0 dan numCourses-1 gacha raqamlangan) va prerequisites ro'yxati berilgan, bunda [a, b] juftligi 'a' kursini olishdan oldin 'b' kursini o'tash kerakligini bildiradi. Barcha kurslarni tugatish mumkinligini aniqlang (ya'ni talablar grafida sikl yo'qligini tekshiring).\n\n**1-misol:**\nKiritma: numCourses = 2, prerequisites = [[1,0]]\nNatija: true\n\n**2-misol:**\nKiritma: numCourses = 2, prerequisites = [[1,0],[0,1]]\nNatija: false",
    starterCodeJs: 'function canFinish(numCourses, prerequisites) {\n  // your code here\n}',
    starterCodePy: 'def can_finish(num_courses, prerequisites):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-028',
    title: 'Grafni Klonlash',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Grafiklar'],
    description: "n tugunli bog'langan yo'naltirilmagan graf qo'shnilar ro'yxati (adjacency list) ko'rinishida berilgan, bunda adjList[i] massivi i-tugunga qo'shni bo'lgan tugunlar indekslarini o'z ichiga oladi. Grafning chuqur nusxasini (klonini) yaratib, xuddi shu ko'rinishda qaytaring.\n\n**1-misol:**\nKiritma: adjList = [[1,2],[0,2],[0,1]]\nNatija: [[1,2],[0,2],[0,1]]\n\n**2-misol:**\nKiritma: adjList = [[1],[0]]\nNatija: [[1],[0]]",
    starterCodeJs: 'function cloneGraph(adjList) {\n  // your code here\n}',
    starterCodePy: 'def clone_graph(adj_list):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> cloneGraph(vector<vector<int>>& adjList) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-029',
    title: 'Og\'irliksiz Grafda Eng Qisqa Yo\'l',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Grafiklar'],
    description: "n ta tugundan (0 dan n-1 gacha) va edges - yo'naltirilmagan, og'irliksiz qirralar ro'yxatidan iborat graf berilgan. start tugunidan end tugunigacha bo'lgan eng qisqa yo'lning uzunligini (qirralar sonini) toping. Agar yo'l mavjud bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,3],[3,4],[0,4]], start = 0, end = 3\nNatija: 2\nIzoh: 0 -> 4 -> 3 yo'li eng qisqa.\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1]], start = 0, end = 2\nNatija: -1",
    starterCodeJs: 'function shortestPath(n, edges, start, end) {\n  // your code here\n}',
    starterCodePy: 'def shortest_path(n, edges, start, end):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestPath(int n, vector<vector<int>>& edges, int start, int end) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-030',
    title: 'Yo\'naltirilgan Grafda Sikl Borligini Aniqlash',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilgan graf edges (qirralar) ro'yxati bilan berilgan. Grafda sikl (bir tugundan boshlanib, o'sha tugunga qaytadigan yo'naltirilgan yo'l) mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]]\nNatija: true\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2]]\nNatija: false",
    starterCodeJs: 'function hasCycleDirected(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def has_cycle_directed(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'bool hasCycleDirected(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-031',
    title: 'Yo\'naltirilmagan Grafda Sikl Borligini Aniqlash',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Grafiklar'],
    description: "n ta tugundan iborat yo'naltirilmagan graf edges (qirralar) ro'yxati bilan berilgan. Grafda sikl mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3],[3,0]]\nNatija: true\n\n**2-misol:**\nKiritma: n = 4, edges = [[0,1],[1,2],[2,3]]\nNatija: false",
    starterCodeJs: 'function hasCycleUndirected(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def has_cycle_undirected(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'bool hasCycleUndirected(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-032',
    title: 'Bog\'langan Komponentalar Soni',
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Grafiklar'],
    description: "n ta tugundan (0 dan n-1 gacha) va edges yo'naltirilmagan qirralar ro'yxatidan iborat graf berilgan. Grafdagi bog'langan komponentalar sonini toping.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[3,4]]\nNatija: 2\n\n**2-misol:**\nKiritma: n = 4, edges = []\nNatija: 4",
    starterCodeJs: 'function countComponents(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def count_components(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int countComponents(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-033',
    title: 'Rangni To\'ldirish (Flood Fill)',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Grafiklar'],
    description: "image - ranglar bilan berilgan 2 o'lchamli panjara, sr va sc - boshlang'ich katakcha koordinatalari, newColor - yangi rang. Boshlang'ich katakchadan boshlab, unga gorizontal yoki vertikal bog'langan va bir xil rangdagi barcha katakchalarni newColor rangiga bo'yang (rangni to'ldirish).\n\n**1-misol:**\nKiritma: image = [[1,1,1],[1,1,0],[1,0,1]], sr = 1, sc = 1, newColor = 2\nNatija: [[2,2,2],[2,2,0],[2,0,1]]\n\n**2-misol:**\nKiritma: image = [[0,0,0]], sr = 0, sc = 0, newColor = 2\nNatija: [[2,2,2]]",
    starterCodeJs: 'function floodFill(image, sr, sc, newColor) {\n  // your code here\n}',
    starterCodePy: 'def flood_fill(image, sr, sc, new_color):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> floodFill(vector<vector<int>>& image, int sr, int sc, int newColor) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-034',
    title: 'Ikki Tomonlama (Bipartite) Graf Ekanligini Tekshirish',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Grafiklar'],
    description: "graph qo'shnilar ro'yxati ko'rinishida berilgan yo'naltirilmagan graf. Grafning ikki tomonlama (bipartite) ekanligini, ya'ni tugunlarni ikkita rangga shunday bo'yash mumkinligini aniqlangki, har bir qirraning ikki uchi turli rangda bo'lsin.\n\n**1-misol:**\nKiritma: graph = [[1,3],[0,2],[1,3],[0,2]]\nNatija: true\n\n**2-misol:**\nKiritma: graph = [[1,2,3],[0,2],[0,1,3],[0,2]]\nNatija: false",
    starterCodeJs: 'function isBipartite(graph) {\n  // your code here\n}',
    starterCodePy: 'def is_bipartite(graph):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isBipartite(vector<vector<int>>& graph) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-035',
    title: 'Minimal Yoyilgan Daraxt Og\'irligi',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Grafiklar'],
    description: "n ta tugundan va edges - [u, v, weight] ko'rinishidagi og'irlikli yo'naltirilmagan qirralar ro'yxatidan iborat bog'langan graf berilgan. Barcha tugunlarni bog'laydigan minimal yoyilgan daraxtning (MST) umumiy og'irligini toping.\n\n**1-misol:**\nKiritma: n = 4, edges = [[0,1,1],[1,2,2],[2,3,3],[0,3,4]]\nNatija: 6\n\n**2-misol:**\nKiritma: n = 3, edges = [[0,1,5],[1,2,3],[0,2,1]]\nNatija: 4",
    starterCodeJs: 'function minSpanningTreeWeight(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def min_spanning_tree_weight(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int minSpanningTreeWeight(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-036',
    title: 'Dijkstra Algoritmi Bilan Eng Qisqa Yo\'l',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Grafiklar'],
    description: "n ta tugundan va edges - [u, v, weight] ko'rinishidagi manfiy bo'lmagan og'irlikli yo'naltirilgan qirralar ro'yxatidan iborat graf berilgan. Dijkstra algoritmidan foydalanib, source tugunidan barcha boshqa tugunlargacha bo'lgan eng qisqa masofalarni massiv sifatida qaytaring (yetib bo'lmasa -1).\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1,4],[0,2,1],[2,1,2]], source = 0\nNatija: [0,3,1]\n\n**2-misol:**\nKiritma: n = 2, edges = [], source = 0\nNatija: [0,-1]",
    starterCodeJs: 'function dijkstra(n, edges, source) {\n  // your code here\n}',
    starterCodePy: 'def dijkstra(n, edges, source):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> dijkstra(int n, vector<vector<int>>& edges, int source) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-037',
    title: 'Graf Haqiqiy Daraxt Ekanligini Tekshirish',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Grafiklar'],
    description: "0 dan n-1 gacha raqamlangan n ta tugun va edges yo'naltirilmagan qirralar ro'yxati berilgan. Bu qirralar haqiqiy daraxt (barcha tugunlar bog'langan va hech qanday sikl yo'q) hosil qilishini tekshiring.\n\n**1-misol:**\nKiritma: n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]\nNatija: true\n\n**2-misol:**\nKiritma: n = 5, edges = [[0,1],[1,2],[2,3],[1,3],[1,4]]\nNatija: false",
    starterCodeJs: 'function validTree(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def valid_tree(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'bool validTree(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-038',
    title: 'Do\'stlar Doiralari Soni',
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Grafiklar'],
    description: "n x n o'lchamli isConnected qo'shnilik matritsasi berilgan, bunda isConnected[i][j] = 1 agar i va j shaharlari to'g'ridan-to'g'ri bog'langan bo'lsa. Bir-biri bilan to'g'ridan-to'g'ri yoki bilvosita bog'langan shaharlar guruhlari (provinsiyalar) sonini toping.\n\n**1-misol:**\nKiritma: isConnected = [[1,1,0],[1,1,0],[0,0,1]]\nNatija: 2\n\n**2-misol:**\nKiritma: isConnected = [[1,0,0],[0,1,0],[0,0,1]]\nNatija: 3",
    starterCodeJs: 'function findCircleNum(isConnected) {\n  // your code here\n}',
    starterCodePy: 'def find_circle_num(is_connected):\n    # your code here\n    pass',
    starterCodeCpp: 'int findCircleNum(vector<vector<int>>& isConnected) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-039',
    title: 'So\'z Zinapoyasi (Word Ladder)',
    difficulty: 'MEDIUM',
    points: 48,
    tags: ['Grafiklar'],
    description: "beginWord, endWord satrlari va wordList lug'at so'zlari ro'yxati berilgan. Har bir qadamda faqat bitta harfni almashtirish orqali va natijaviy so'z wordList ichida mavjud bo'lishi sharti bilan, beginWord dan endWord gacha bo'lgan eng qisqa transformatsiyalar ketma-ketligining uzunligini (so'zlar sonini) toping. Agar bunday yo'l mavjud bo'lmasa, 0 qaytaring.\n\n**1-misol:**\nKiritma: beginWord = 'hit', endWord = 'cog', wordList = ['hot','dot','dog','lot','log','cog']\nNatija: 5\nIzoh: hit -> hot -> dot -> dog -> cog.\n\n**2-misol:**\nKiritma: beginWord = 'hit', endWord = 'cog', wordList = ['hot','dot','dog','lot','log']\nNatija: 0",
    starterCodeJs: 'function ladderLength(beginWord, endWord, wordList) {\n  // your code here\n}',
    starterCodePy: 'def ladder_length(begin_word, end_word, word_list):\n    # your code here\n    pass',
    starterCodeCpp: 'int ladderLength(string beginWord, string endWord, vector<string>& wordList) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-040',
    title: 'Chirigan Apelsinlar',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Grafiklar'],
    description: "grid panjarasida har bir katakcha quyidagilardan birini bildiradi: 0 - bo'sh joy, 1 - yangi apelsin, 2 - chirigan apelsin. Har daqiqada chirigan apelsinga gorizontal yoki vertikal qo'shni bo'lgan yangi apelsinlar ham chirib qoladi. Barcha yangi apelsinlar chirib bo'lguncha zarur bo'lgan minimal daqiqalar sonini toping. Agar bu mumkin bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: grid = [[2,1,1],[1,1,0],[0,1,1]]\nNatija: 4\n\n**2-misol:**\nKiritma: grid = [[0,2]]\nNatija: 0",
    starterCodeJs: 'function orangesRotting(grid) {\n  // your code here\n}',
    starterCodePy: 'def oranges_rotting(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int orangesRotting(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-041',
    title: 'O\'ralgan Hududlarni Almashtirish',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Grafiklar'],
    description: "board - 'X' va 'O' belgilaridan iborat m x n taxtacha berilgan. Taxtaning chetiga (chekkasiga) tegib turmagan va faqat 'X' bilan o'ralgan barcha 'O' hududlarni 'X' ga aylantiring.\n\n**1-misol:**\nKiritma: board = [['X','X','X','X'],['X','O','O','X'],['X','X','O','X'],['X','O','X','X']]\nNatija: [['X','X','X','X'],['X','X','X','X'],['X','X','X','X'],['X','O','X','X']]\n\n**2-misol:**\nKiritma: board = [['X']]\nNatija: [['X']]",
    starterCodeJs: 'function solveSurroundedRegions(board) {\n  // your code here\n}',
    starterCodePy: 'def solve_surrounded_regions(board):\n    # your code here\n    pass',
    starterCodeCpp: 'void solveSurroundedRegions(vector<vector<char>>& board) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-042',
    title: 'Tarmoq Kechikish Vaqti',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Grafiklar'],
    description: "n ta tugun (1 dan n gacha raqamlangan) va times - [u, v, w] ko'rinishidagi yo'naltirilgan qirralar ro'yxati berilgan, bu yerda w signal u dan v ga yetib borishi uchun ketadigan vaqt. k tugunidan signal yuborilganda, signal barcha tugunlarga yetib borishi uchun zarur bo'lgan minimal vaqtni toping. Agar barcha tugunlarga yetib bo'lmasa, -1 qaytaring.\n\n**1-misol:**\nKiritma: times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2\nNatija: 2\n\n**2-misol:**\nKiritma: times = [[1,2,1]], n = 2, k = 1\nNatija: 1",
    starterCodeJs: 'function networkDelayTime(times, n, k) {\n  // your code here\n}',
    starterCodePy: 'def network_delay_time(times, n, k):\n    # your code here\n    pass',
    starterCodeCpp: 'int networkDelayTime(vector<vector<int>>& times, int n, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-043',
    title: 'Yulduz Grafi Markazini Topish',
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Grafiklar'],
    description: "n tugunli yulduz shaklidagi graf berilgan, unda markaziy tugun qolgan barcha n-1 ta tugun bilan bevosita bog'langan. edges - qirralar ro'yxati berilgan holda, yulduz grafining markaziy tugunini toping.\n\n**1-misol:**\nKiritma: edges = [[1,2],[2,3],[4,2]]\nNatija: 2\n\n**2-misol:**\nKiritma: edges = [[1,2],[5,1],[1,3],[1,4]]\nNatija: 1",
    starterCodeJs: 'function findCenter(edges) {\n  // your code here\n}',
    starterCodePy: 'def find_center(edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int findCenter(vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-044',
    title: 'Manbadan Maqsadgacha Barcha Yo\'llar',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Grafiklar'],
    description: "n tugunli yo'naltirilgan atsiklik graf (DAG) qo'shnilar ro'yxati graph ko'rinishida berilgan (graph[i] - i tugunidan chiqadigan qirralar). 0-tugundan (n-1)-tugungacha bo'lgan barcha mumkin bo'lgan yo'llarni toping.\n\n**1-misol:**\nKiritma: graph = [[1,2],[3],[3],[]]\nNatija: [[0,1,3],[0,2,3]]\n\n**2-misol:**\nKiritma: graph = [[1],[]]\nNatija: [[0,1]]",
    starterCodeJs: 'function allPathsSourceTarget(graph) {\n  // your code here\n}',
    starterCodePy: 'def all_paths_source_target(graph):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> allPathsSourceTarget(vector<vector<int>>& graph) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-045',
    title: 'Ikki Orol Orasidagi Eng Qisqa Ko\'prik',
    difficulty: 'MEDIUM',
    points: 48,
    tags: ['Grafiklar'],
    description: "grid - faqat ikkita orolni (gorizontal yoki vertikal bog'langan '1' katakchalar guruhi) o'z ichiga olgan ikkilik panjara berilgan. Ikki orolni bog'lash uchun '0' dan '1' ga aylantirilishi kerak bo'lgan eng kam sonli katakchalarni (eng qisqa ko'prikni) toping.\n\n**1-misol:**\nKiritma: grid = [[0,1],[1,0]]\nNatija: 1\n\n**2-misol:**\nKiritma: grid = [[0,1,0],[0,0,0],[0,0,1]]\nNatija: 2",
    starterCodeJs: 'function shortestBridge(grid) {\n  // your code here\n}',
    starterCodePy: 'def shortest_bridge(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int shortestBridge(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-046',
    title: 'Yopiq Orollar Soni',
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Grafiklar'],
    description: "grid - 0 (quruqlik) va 1 (suv) dan iborat panjara berilgan. Yopiq orol - gorizontal yoki vertikal bog'langan 0 katakchalar guruhi bo'lib, u panjara chetiga tegib turmaydi va to'liq 1 lar bilan o'ralgan bo'ladi. Panjaradagi yopiq orollar sonini toping.\n\n**1-misol:**\nKiritma: grid = [[1,1,1,1,1,1,1,0],[1,0,0,0,0,1,1,0],[1,0,1,0,1,1,1,0],[1,0,0,0,0,1,0,1],[1,1,1,1,1,1,1,0]]\nNatija: 2\n\n**2-misol:**\nKiritma: grid = [[0,0,1,0,0],[0,1,0,1,0],[0,1,1,1,0]]\nNatija: 1",
    starterCodeJs: 'function closedIsland(grid) {\n  // your code here\n}',
    starterCodePy: 'def closed_island(grid):\n    # your code here\n    pass',
    starterCodeCpp: 'int closedIsland(vector<vector<int>>& grid) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-047',
    title: 'Ikki Tugun Orasida Yo\'l Mavjudligini Tekshirish',
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Grafiklar'],
    description: "n ta tugun va edges yo'naltirilmagan qirralar ro'yxati berilgan. source tugunidan destination tugunigacha yo'l mavjudligini aniqlang.\n\n**1-misol:**\nKiritma: n = 3, edges = [[0,1],[1,2],[2,0]], source = 0, destination = 2\nNatija: true\n\n**2-misol:**\nKiritma: n = 6, edges = [[0,1],[0,2],[3,5],[5,4],[4,3]], source = 0, destination = 5\nNatija: false",
    starterCodeJs: 'function validPathExists(n, edges, source, destination) {\n  // your code here\n}',
    starterCodePy: 'def valid_path_exists(n, edges, source, destination):\n    # your code here\n    pass',
    starterCodeCpp: 'bool validPathExists(int n, vector<vector<int>>& edges, int source, int destination) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-048',
    title: 'Kurslarni O\'qish Tartibi (Topologik Saralash)',
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Grafiklar'],
    description: "numCourses ta kurs va prerequisites - [a, b] ko'rinishidagi ro'yxat berilgan, bu yerda 'a' kursini olishdan oldin 'b' kursini o'tash kerak. Barcha kurslarni o'tash mumkin bo'lgan har qanday to'g'ri tartibni qaytaring. Agar bunday tartib mavjud bo'lmasa, bo'sh massiv qaytaring.\n\n**1-misol:**\nKiritma: numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]\nNatija: [0,1,2,3]\n\n**2-misol:**\nKiritma: numCourses = 2, prerequisites = [[1,0],[0,1]]\nNatija: []",
    starterCodeJs: 'function findOrder(numCourses, prerequisites) {\n  // your code here\n}',
    starterCodePy: 'def find_order(num_courses, prerequisites):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> findOrder(int numCourses, vector<vector<int>>& prerequisites) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-049',
    title: 'Eng Katta Bog\'langan Komponent Hajmi',
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Grafiklar'],
    description: "n ta tugun va edges yo'naltirilmagan qirralar ro'yxati berilgan. Grafdagi eng katta bog'langan komponentaning hajmini (undagi tugunlar sonini) toping.\n\n**1-misol:**\nKiritma: n = 6, edges = [[0,1],[1,2],[3,4]]\nNatija: 3\n\n**2-misol:**\nKiritma: n = 4, edges = []\nNatija: 1",
    starterCodeJs: 'function largestComponentSize(n, edges) {\n  // your code here\n}',
    starterCodePy: 'def largest_component_size(n, edges):\n    # your code here\n    pass',
    starterCodeCpp: 'int largestComponentSize(int n, vector<vector<int>>& edges) {\n    // your code here\n}',
  },
  {
    key: 'medium-c-050',
    title: 'Barcha Xonalarni Ochish Mumkinmi (Keys and Rooms)',
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Grafiklar'],
    description: "n ta xona (0 dan n-1 gacha raqamlangan) berilgan, rooms[i] massivi i-xonada topilgan kalitlarni (ochilishi mumkin bo'lgan xonalar raqamlarini) bildiradi. Siz 0-xonadan boshlaysiz, u har doim ochiq. Barcha xonalarga kirish mumkinligini aniqlang.\n\n**1-misol:**\nKiritma: rooms = [[1],[2],[3],[]]\nNatija: true\n\n**2-misol:**\nKiritma: rooms = [[1,3],[3,0,1],[2],[0]]\nNatija: false",
    starterCodeJs: 'function canVisitAllRooms(rooms) {\n  // your code here\n}',
    starterCodePy: 'def can_visit_all_rooms(rooms):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canVisitAllRooms(vector<vector<int>>& rooms) {\n    // your code here\n}',
  },
];
