export const problems = [
  {
    key: 'medium-b-001',
    title: "Eratosfen Elak Usuli",
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Matematika'],
    description: "Berilgan n butun soni uchun, Eratosfen elak usulidan foydalanib, 2 dan n gacha (n ni ham hisobga olgan holda) bo'lgan barcha tub sonlarni o'sish tartibida massiv sifatida qaytaring.\n\n**1-misol:**\nKiritma: n = 10\nNatija: [2,3,5,7]\nIzoh: 10 gacha bo'lgan tub sonlar shular.\n\n**2-misol:**\nKiritma: n = 20\nNatija: [2,3,5,7,11,13,17,19]",
    starterCodeJs: 'function sieveOfEratosthenes(n) {\n  // your code here\n}',
    starterCodePy: 'def sieve_of_eratosthenes(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> sieveOfEratosthenes(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-002',
    title: "N Dan Kichik Tub Sonlar Soni",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Berilgan n soni uchun, n dan kichik (n ni hisobga olmasdan) bo'lgan tub sonlar sonini qaytaring. Yechim samarali bo'lishi uchun Eratosfen elak usulidan foydalaning.\n\n**1-misol:**\nKiritma: n = 10\nNatija: 4\nIzoh: 2, 3, 5, 7 - jami 4 ta tub son.\n\n**2-misol:**\nKiritma: n = 0\nNatija: 0",
    starterCodeJs: 'function countPrimes(n) {\n  // your code here\n}',
    starterCodePy: 'def count_primes(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int countPrimes(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-003',
    title: "Sonni Tub Ko'paytuvchilarga Ajratish",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Matematika'],
    description: "Berilgan musbat butun n soni uchun uning tub ko'paytuvchilarga yoyilmasini toping. Natijani {tub_son: daraja} ko'rinishidagi ob'ekt (yoki lug'at) sifatida qaytaring.\n\n**1-misol:**\nKiritma: n = 84\nNatija: {2: 2, 3: 1, 7: 1}\nIzoh: 84 = 2^2 * 3 * 7.\n\n**2-misol:**\nKiritma: n = 17\nNatija: {17: 1}\nIzoh: 17 tub son.",
    starterCodeJs: 'function primeFactorization(n) {\n  // your code here\n}',
    starterCodePy: 'def prime_factorization(n):\n    # your code here\n    pass',
    starterCodeCpp: 'map<int,int> primeFactorization(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-004',
    title: "Massiv Elementlarining Eng Katta Umumiy Bo'luvchisi",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Butun sonlardan iborat nums massivi berilgan. Massivdagi barcha elementlarning eng katta umumiy bo'luvchisini (GCD) qaytaring.\n\n**1-misol:**\nKiritma: nums = [12, 18, 24]\nNatija: 6\n\n**2-misol:**\nKiritma: nums = [7, 5, 3]\nNatija: 1",
    starterCodeJs: 'function gcdOfArray(nums) {\n  // your code here\n}',
    starterCodePy: 'def gcd_of_array(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'int gcdOfArray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-005',
    title: "Massiv Elementlarining Eng Kichik Umumiy Karralisi",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Matematika'],
    description: "Butun sonlardan iborat nums massivi berilgan. Massivdagi barcha elementlarning eng kichik umumiy karralisini (LCM) qaytaring. Natija juda katta bo'lishi mumkinligini hisobga oling.\n\n**1-misol:**\nKiritma: nums = [4, 6]\nNatija: 12\n\n**2-misol:**\nKiritma: nums = [3, 5, 7]\nNatija: 105",
    starterCodeJs: 'function lcmOfArray(nums) {\n  // your code here\n}',
    starterCodePy: 'def lcm_of_array(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'long long lcmOfArray(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-006',
    title: "Modul Bo'yicha Tez Darajaga Ko'tarish",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Matematika'],
    description: "Uchta butun son: base, exp va mod berilgan. (base^exp) % mod qiymatini samarali (tez darajaga ko'tarish algoritmi orqali) hisoblang, chunki exp juda katta bo'lishi mumkin.\n\n**1-misol:**\nKiritma: base = 2, exp = 10, mod = 1000\nNatija: 24\nIzoh: 2^10 = 1024, 1024 % 1000 = 24.\n\n**2-misol:**\nKiritma: base = 3, exp = 200, mod = 13\nNatija: 9",
    starterCodeJs: 'function modPow(base, exp, mod) {\n  // your code here\n}',
    starterCodePy: 'def mod_pow(base, exp, mod):\n    # your code here\n    pass',
    starterCodeCpp: 'long long modPow(long long base, long long exp, long long mod) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-007',
    title: "x Ning n-Darajasi (Tez Algoritm)",
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Matematika'],
    description: "Haqiqiy son x va butun son n berilgan. x^n qiymatini hisoblang. n manfiy bo'lishi mumkin. Yechim O(log n) vaqt murakkabligiga ega bo'lishi kerak (oddiy tsikl orqali ko'paytirish emas).\n\n**1-misol:**\nKiritma: x = 2.0, n = 10\nNatija: 1024.0\n\n**2-misol:**\nKiritma: x = 2.0, n = -2\nNatija: 0.25",
    starterCodeJs: 'function myPow(x, n) {\n  // your code here\n}',
    starterCodePy: 'def my_pow(x, n):\n    # your code here\n    pass',
    starterCodeCpp: 'double myPow(double x, int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-008',
    title: "Ikki Kichik Matritsani Ko'paytirish",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Matematika'],
    description: "A (m x n o'lchamli) va B (n x p o'lchamli) ikkita matritsa berilgan. Ularning ko'paytmasi bo'lgan (m x p o'lchamli) natijaviy matritsani qaytaring.\n\n**1-misol:**\nKiritma: A = [[1,2],[3,4]], B = [[5,6],[7,8]]\nNatija: [[19,22],[43,50]]\n\n**2-misol:**\nKiritma: A = [[1,0],[0,1]], B = [[4,5],[6,7]]\nNatija: [[4,5],[6,7]]",
    starterCodeJs: 'function multiplyMatrices(A, B) {\n  // your code here\n}',
    starterCodePy: 'def multiply_matrices(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> multiplyMatrices(vector<vector<int>>& a, vector<vector<int>>& b) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-009',
    title: "Butun Sonni Rim Raqamiga O'tkazish",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Matematika'],
    description: "1 dan 3999 gacha bo'lgan butun son berilgan. Uni Rim raqamlari (Roman numeral) ko'rinishidagi satrga o'tkazing.\n\n**1-misol:**\nKiritma: num = 58\nNatija: \"LVIII\"\nIzoh: L = 50, V = 5, III = 3.\n\n**2-misol:**\nKiritma: num = 1994\nNatija: \"MCMXCIV\"",
    starterCodeJs: 'function intToRoman(num) {\n  // your code here\n}',
    starterCodePy: 'def int_to_roman(num):\n    # your code here\n    pass',
    starterCodeCpp: 'string intToRoman(int num) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-010',
    title: "Rim Raqamini Butun Songa O'tkazish",
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Matematika'],
    description: "Rim raqamlaridan tashkil topgan s satri berilgan. Uni mos butun songa o'tkazing.\n\n**1-misol:**\nKiritma: s = \"LVIII\"\nNatija: 58\n\n**2-misol:**\nKiritma: s = \"MCMXCIV\"\nNatija: 1994",
    starterCodeJs: 'function romanToInt(s) {\n  // your code here\n}',
    starterCodePy: 'def roman_to_int(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int romanToInt(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-011',
    title: "Excel Ustun Nomini Songa O'tkazish",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Excel jadvalidagi ustun nomi (masalan, \"A\", \"B\", ..., \"AA\", \"AB\", ...) ifodalovchi columnTitle satri berilgan. Unga mos ustun raqamini qaytaring.\n\n**1-misol:**\nKiritma: columnTitle = \"A\"\nNatija: 1\n\n**2-misol:**\nKiritma: columnTitle = \"AB\"\nNatija: 28",
    starterCodeJs: 'function titleToNumber(columnTitle) {\n  // your code here\n}',
    starterCodePy: 'def title_to_number(column_title):\n    # your code here\n    pass',
    starterCodeCpp: 'int titleToNumber(string columnTitle) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-012',
    title: "Sonni Excel Ustun Nomiga O'tkazish",
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Matematika'],
    description: "Musbat butun columnNumber soni berilgan. Uni Excel jadvalidagi mos ustun nomiga (masalan, 1 -> \"A\", 28 -> \"AB\") o'tkazing.\n\n**1-misol:**\nKiritma: columnNumber = 1\nNatija: \"A\"\n\n**2-misol:**\nKiritma: columnNumber = 701\nNatija: \"ZY\"",
    starterCodeJs: 'function convertToTitle(columnNumber) {\n  // your code here\n}',
    starterCodePy: 'def convert_to_title(column_number):\n    # your code here\n    pass',
    starterCodeCpp: 'string convertToTitle(int columnNumber) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-013',
    title: "Baxtli Son (Happy Number)",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. Sonning har bir raqamini kvadratga ko'tarib yig'indisini hisoblash jarayonini takrorlang. Agar bu jarayon natijasida yig'indi 1 ga teng bo'lsa, n \"baxtli son\" hisoblanadi. n baxtli son bo'lsa true, aks holda false qaytaring (jarayon cheksiz tsiklga tushib qolishi ham mumkin, buni aniqlang).\n\n**1-misol:**\nKiritma: n = 19\nNatija: true\nIzoh: 1^2+9^2=82, 8^2+2^2=68, 6^2+8^2=100, 1^2+0^2+0^2=1.\n\n**2-misol:**\nKiritma: n = 2\nNatija: false",
    starterCodeJs: 'function isHappy(n) {\n  // your code here\n}',
    starterCodePy: 'def is_happy(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isHappy(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-014',
    title: "Suv Va Idishlar Masalasi",
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Matematika'],
    description: "x va y litrlik ikkita idish hamda maqsad z litr berilgan. Idishlarni to'ldirish, bo'shatish va bir-biriga quyish amallaridan foydalanib, ikkita idishning birortasida aynan z litr suv hosil qilish mumkinligini aniqlang (true yoki false qaytaring). Bu masalani Bezu (Bezout) identligi va GCD tushunchasi asosida yeching.\n\n**1-misol:**\nKiritma: x = 3, y = 5, z = 4\nNatija: true\n\n**2-misol:**\nKiritma: x = 2, y = 6, z = 5\nNatija: false",
    starterCodeJs: 'function canMeasureWater(x, y, z) {\n  // your code here\n}',
    starterCodePy: 'def can_measure_water(x, y, z):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canMeasureWater(int x, int y, int z) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-015',
    title: "Kamida Nechta Butun Kvadrat Yig'indisi",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. n sonini butun kvadrat sonlar (1, 4, 9, 16, ...) yig'indisi sifatida ifodalash uchun zarur bo'lgan eng kam qo'shiluvchilar sonini toping.\n\n**1-misol:**\nKiritma: n = 12\nNatija: 3\nIzoh: 12 = 4+4+4.\n\n**2-misol:**\nKiritma: n = 13\nNatija: 2\nIzoh: 13 = 4+9.",
    starterCodeJs: 'function numSquares(n) {\n  // your code here\n}',
    starterCodePy: 'def num_squares(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int numSquares(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-016',
    title: "Armstrong (Narsissistik) Son",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. Agar n sonining har bir raqami sonning raqamlar sonidagi darajaga ko'tarilib yig'ilganda yana n ga teng bo'lsa, n Armstrong son hisoblanadi. n Armstrong son ekanligini tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: n = 153\nNatija: true\nIzoh: 1^3+5^3+3^3 = 153.\n\n**2-misol:**\nKiritma: n = 123\nNatija: false",
    starterCodeJs: 'function isArmstrong(n) {\n  // your code here\n}',
    starterCodePy: 'def is_armstrong(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isArmstrong(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-017',
    title: "Mukammal Son (Perfect Number)",
    difficulty: 'MEDIUM',
    points: 31,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. Agar n sonining o'zidan tashqari barcha musbat bo'luvchilari yig'indisi n ga teng bo'lsa, u mukammal son hisoblanadi. n mukammal son ekanligini aniqlab, true yoki false qaytaring.\n\n**1-misol:**\nKiritma: n = 28\nNatija: true\nIzoh: 1+2+4+7+14 = 28.\n\n**2-misol:**\nKiritma: n = 12\nNatija: false",
    starterCodeJs: 'function isPerfectNumber(n) {\n  // your code here\n}',
    starterCodePy: 'def is_perfect_number(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPerfectNumber(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-018',
    title: "Kollats Ketma-Ketligi Uzunligi",
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. Kollats qoidasi bo'yicha: agar son juft bo'lsa uni 2 ga bo'ling, toq bo'lsa uni 3 ga ko'paytirib 1 qo'shing; bu jarayonni son 1 ga yetguncha davom ettiring. n dan boshlab 1 ga yetguncha bo'lgan qadamlar sonini (ketma-ketlik uzunligini) qaytaring.\n\n**1-misol:**\nKiritma: n = 6\nNatija: 8\nIzoh: 6,3,10,5,16,8,4,2,1 - 1 ga yetguncha 8 qadam.\n\n**2-misol:**\nKiritma: n = 1\nNatija: 0",
    starterCodeJs: 'function collatzLength(n) {\n  // your code here\n}',
    starterCodePy: 'def collatz_length(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int collatzLength(long long n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-019',
    title: "Raqamlar Yig'indisini Qisqartirish (Digital Root)",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. Sonning raqamlari yig'indisini hisoblang; agar natija bir xonali songa aylanmaguncha bu jarayonni takrorlang. Yakuniy bir xonali sonni qaytaring.\n\n**1-misol:**\nKiritma: n = 493193\nNatija: 2\nIzoh: 4+9+3+1+9+3=29, 2+9=11, 1+1=2.\n\n**2-misol:**\nKiritma: n = 0\nNatija: 0",
    starterCodeJs: 'function digitalRoot(n) {\n  // your code here\n}',
    starterCodePy: 'def digital_root(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int digitalRoot(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-020',
    title: "Butun Sonni Teskari Yozish (32-bit Overflow Bilan)",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Matematika'],
    description: "32-bitli ishorali butun son x berilgan. Uning raqamlarini teskari tartibda yozib chiqing. Agar natija 32-bitli ishorali butun son diapazonidan ([-2^31, 2^31 - 1]) chiqib ketsa, 0 qaytaring.\n\n**1-misol:**\nKiritma: x = 123\nNatija: 321\n\n**2-misol:**\nKiritma: x = -120\nNatija: -21",
    starterCodeJs: 'function reverseInteger(x) {\n  // your code here\n}',
    starterCodePy: 'def reverse_integer(x):\n    # your code here\n    pass',
    starterCodeCpp: 'int reverseInteger(int x) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-021',
    title: "Palindrom Sonni Satrga Aylantirmasdan Tekshirish",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Butun son x berilgan. Uni satrga aylantirmasdan (faqat matematik amallar yordamida), x palindrom ekanligini (old va orqadan bir xil o'qilishini) tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: x = 121\nNatija: true\n\n**2-misol:**\nKiritma: x = -121\nNatija: false\nIzoh: Manfiy sonlar palindrom hisoblanmaydi.",
    starterCodeJs: 'function isPalindromeNumber(x) {\n  // your code here\n}',
    starterCodePy: 'def is_palindrome_number(x):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPalindromeNumber(int x) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-022',
    title: "Butun Sonning Kvadrat Ildizi (Ichki Funksiyasiz)",
    difficulty: 'MEDIUM',
    points: 35,
    tags: ['Matematika'],
    description: "Manfiy bo'lmagan butun son x berilgan. sqrt kabi tayyor funksiyalardan foydalanmasdan, x ning kvadrat ildizining butun qismini (pastga yaxlitlangan holda) qaytaring.\n\n**1-misol:**\nKiritma: x = 8\nNatija: 2\nIzoh: sqrt(8) taxminan 2.828, butun qismi 2.\n\n**2-misol:**\nKiritma: x = 4\nNatija: 2",
    starterCodeJs: 'function mySqrt(x) {\n  // your code here\n}',
    starterCodePy: 'def my_sqrt(x):\n    # your code here\n    pass',
    starterCodeCpp: 'int mySqrt(int x) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-023',
    title: "Faktorialdagi Nollar Soni",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Matematika'],
    description: "Musbat butun n soni berilgan. n! (n faktorial) sonining o'nlik yozuvi oxiridagi nollar sonini, n! ni to'liq hisoblamasdan, samarali usulda toping.\n\n**1-misol:**\nKiritma: n = 5\nNatija: 1\nIzoh: 5! = 120, oxirida 1 ta nol.\n\n**2-misol:**\nKiritma: n = 10\nNatija: 2\nIzoh: 10! = 3628800, oxirida 2 ta nol.",
    starterCodeJs: 'function trailingZeroes(n) {\n  // your code here\n}',
    starterCodePy: 'def trailing_zeroes(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int trailingZeroes(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-024',
    title: "Sonning Uchning Darajasi Ekanligini Tekshirish",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Matematika'],
    description: "Butun son n berilgan. n sonini 3 ning butun darajasi (masalan, 1, 3, 9, 27, ...) sifatida ifodalash mumkinligini aniqlang va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: n = 27\nNatija: true\nIzoh: 27 = 3^3.\n\n**2-misol:**\nKiritma: n = 45\nNatija: false",
    starterCodeJs: 'function isPowerOfThree(n) {\n  // your code here\n}',
    starterCodePy: 'def is_power_of_three(n):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPowerOfThree(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-025',
    title: "Katta Sonlarni Satr Ko'rinishida Ko'paytirish",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Matematika'],
    description: "Manfiy bo'lmagan ikkita katta sonni ifodalovchi num1 va num2 satrlari berilgan (ular built-in katta son turlariga sig'masligi mumkin). Ularning ko'paytmasini yana satr ko'rinishida qaytaring, ichki big-integer turlaridan foydalanmasdan.\n\n**1-misol:**\nKiritma: num1 = \"123\", num2 = \"456\"\nNatija: \"56088\"\n\n**2-misol:**\nKiritma: num1 = \"9\", num2 = \"9\"\nNatija: \"81\"",
    starterCodeJs: 'function multiplyStrings(num1, num2) {\n  // your code here\n}',
    starterCodePy: 'def multiply_strings(num1, num2):\n    # your code here\n    pass',
    starterCodeCpp: 'string multiplyStrings(string num1, string num2) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-026',
    title: "Barcha Kichik To'plamlarni Rekursiya Bilan Hosil Qilish",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Rekursiya'],
    description: "Turli elementlardan tashkil topgan nums massivi berilgan. Rekursiv usuldan foydalanib, massivning barcha mumkin bo'lgan kichik to'plamlarini (bo'sh to'plam va massivning o'zini ham qo'shgan holda) qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,2,3]\nNatija: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]\n\n**2-misol:**\nKiritma: nums = [0]\nNatija: [[],[0]]",
    starterCodeJs: 'function subsets(nums) {\n  // your code here\n}',
    starterCodePy: 'def subsets(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> subsets(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-027',
    title: "Massiv Permutatsiyalarini Rekursiya Bilan Generatsiya Qilish",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Rekursiya'],
    description: "Turli elementlardan tashkil topgan nums massivi berilgan. Rekursiv backtracking usulidan foydalanib, massivning barcha mumkin bo'lgan permutatsiyalarini (elementlar tartibini) qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,2,3]\nNatija: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]\n\n**2-misol:**\nKiritma: nums = [0,1]\nNatija: [[0,1],[1,0]]",
    starterCodeJs: 'function permute(nums) {\n  // your code here\n}',
    starterCodePy: 'def permute(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> permute(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-028',
    title: "N-Queens: Yechimlar Sonini Rekursiya Bilan Hisoblash",
    difficulty: 'MEDIUM',
    points: 45,
    tags: ['Rekursiya'],
    description: "n x n o'lchamli shaxmat taxtasida bir-biriga hujum qilmaydigan n ta ferzni (queen) joylashtirishning nechta usuli borligini rekursiv backtracking algoritmi yordamida hisoblang.\n\n**1-misol:**\nKiritma: n = 4\nNatija: 2\n\n**2-misol:**\nKiritma: n = 1\nNatija: 1",
    starterCodeJs: 'function totalNQueens(n) {\n  // your code here\n}',
    starterCodePy: 'def total_n_queens(n):\n    # your code here\n    pass',
    starterCodeCpp: 'int totalNQueens(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-029',
    title: "Combination Sum: Yig'indiga Teng Kombinatsiyalar",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Rekursiya'],
    description: "Takrorlanmaydigan musbat sonlardan iborat candidates massivi va target soni berilgan. Rekursiv usul yordamida, elementlarni istalgancha marta qayta ishlatib, yig'indisi target ga teng bo'lgan barcha noyob kombinatsiyalarni toping.\n\n**1-misol:**\nKiritma: candidates = [2,3,6,7], target = 7\nNatija: [[2,2,3],[7]]\n\n**2-misol:**\nKiritma: candidates = [2,3,5], target = 8\nNatija: [[2,2,2,2],[2,3,3],[3,5]]",
    starterCodeJs: 'function combinationSum(candidates, target) {\n  // your code here\n}',
    starterCodePy: 'def combination_sum(candidates, target):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> combinationSum(vector<int>& candidates, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-030',
    title: "Telefon Raqami Harflari Kombinatsiyalari",
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Rekursiya'],
    description: "2 dan 9 gacha raqamlardan tashkil topgan digits satri berilgan (telefon tugmalari kabi). Har bir raqamga mos harflarning barcha mumkin bo'lgan kombinatsiyalarini rekursiya yordamida qaytaring.\n\n**1-misol:**\nKiritma: digits = \"23\"\nNatija: [\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]\n\n**2-misol:**\nKiritma: digits = \"\"\nNatija: []",
    starterCodeJs: 'function letterCombinations(digits) {\n  // your code here\n}',
    starterCodePy: 'def letter_combinations(digits):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> letterCombinations(string digits) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-031',
    title: "Rekursiv Merge Sort Algoritmi",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi nums berilgan. Massivni rekursiv merge sort algoritmi yordamida (massivni ikkiga bo'lib, har birini alohida saralab, so'ng birlashtirib) o'sish tartibida saralang.\n\n**1-misol:**\nKiritma: nums = [5,2,4,1,3]\nNatija: [1,2,3,4,5]\n\n**2-misol:**\nKiritma: nums = [3,3,1]\nNatija: [1,3,3]",
    starterCodeJs: 'function mergeSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def merge_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergeSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-032',
    title: "Rekursiv Quicksort (Partition) Algoritmi",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi nums berilgan. Quicksort algoritmini rekursiv tarzda amalga oshiring: har safar bir tayanch element (pivot) tanlab, massivni ikkiga bo'ling (partition) va har ikkala qismni rekursiv ravishda saralang.\n\n**1-misol:**\nKiritma: nums = [10,7,8,9,1,5]\nNatija: [1,5,7,8,9,10]\n\n**2-misol:**\nKiritma: nums = [4,2,2,8]\nNatija: [2,2,4,8]",
    starterCodeJs: 'function quickSort(nums) {\n  // your code here\n}',
    starterCodePy: 'def quick_sort(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> quickSort(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-033',
    title: "Hanoy Minorasi: Barcha Yurishlar Ro'yxati",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Rekursiya'],
    description: "n ta diskli Hanoy minorasi masalasida, disklarni A tayoqchadan C tayoqchaga (B tayoqchani yordamchi sifatida ishlatib) qoidalarga muvofiq ko'chirish uchun zarur bo'lgan barcha yurishlarni rekursiya yordamida topib, [\"A->C\", ...] kabi satrlar ro'yxati sifatida qaytaring.\n\n**1-misol:**\nKiritma: n = 2\nNatija: [\"A->B\",\"A->C\",\"B->C\"]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [\"A->C\"]",
    starterCodeJs: 'function towerOfHanoi(n) {\n  // your code here\n}',
    starterCodePy: 'def tower_of_hanoi(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> towerOfHanoi(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-034',
    title: "Rekursiv Flood Fill Algoritmi",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Rekursiya'],
    description: "image nomli m x n o'lchamli tasvir matritsasi, boshlang'ich (sr, sc) piksel koordinatalari va yangi rang color berilgan. Rekursiv flood fill algoritmi yordamida boshlang'ich pikseldan boshlab, unga 4 tomonlama (yuqori, past, chap, o'ng) ulangan va bir xil rangdagi barcha piksellarni yangi rangga bo'yang, so'ng yangilangan tasvirni qaytaring.\n\n**1-misol:**\nKiritma: image = [[1,1,1],[1,1,0],[1,0,1]], sr = 1, sc = 1, color = 2\nNatija: [[2,2,2],[2,2,0],[2,0,1]]\n\n**2-misol:**\nKiritma: image = [[0,0,0]], sr = 0, sc = 0, color = 5\nNatija: [[5,5,5]]",
    starterCodeJs: 'function floodFill(image, sr, sc, color) {\n  // your code here\n}',
    starterCodePy: 'def flood_fill(image, sr, sc, color):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> floodFill(vector<vector<int>>& image, int sr, int sc, int color) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-035',
    title: "Decode Ways: Dekodlash Usullari Sonini Rekursiya Bilan Topish",
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Rekursiya'],
    description: "Faqat raqamlardan tashkil topgan s satri berilgan, unda '1'->'A', '2'->'B', ..., '26'->'Z' kabi kodlash qoidasi qo'llanilgan. Rekursiya va memoizatsiya yordamida, s satrini qancha xil usulda dekodlash mumkinligini hisoblang.\n\n**1-misol:**\nKiritma: s = \"226\"\nNatija: 3\nIzoh: \"BZ\" (2 26), \"VF\" (22 6), yoki \"BBF\" (2 2 6).\n\n**2-misol:**\nKiritma: s = \"06\"\nNatija: 0\nIzoh: \"06\" 6 emas, 06 kabi noto'g'ri kodlash hisoblanadi.",
    starterCodeJs: 'function numDecodings(s) {\n  // your code here\n}',
    starterCodePy: 'def num_decodings(s):\n    # your code here\n    pass',
    starterCodeCpp: 'int numDecodings(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-036',
    title: "Ikkilik Daraxtda Ildizdan Bargacha Barcha Yo'llar",
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Rekursiya'],
    description: "Ikkilik daraxt (binary tree) ildizi root sifatida berilgan (har bir tugun {val, left, right} ko'rinishida). Rekursiya yordamida ildizdan har bir bargga (leaf) qadar bo'lgan barcha yo'llarni \"1->2->5\" kabi satrlar ro'yxati sifatida qaytaring.\n\n**1-misol:**\nKiritma: root = {val:1, left:{val:2, right:{val:5}}, right:{val:3}}\nNatija: [\"1->2->5\",\"1->3\"]\n\n**2-misol:**\nKiritma: root = {val:1}\nNatija: [\"1\"]",
    starterCodeJs: 'function binaryTreePaths(root) {\n  // your code here\n}',
    starterCodePy: 'def binary_tree_paths(root):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> binaryTreePaths(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-037',
    title: "Fibonacci Ketma-Ketligini Memoizatsiya Bilan To'liq Hosil Qilish",
    difficulty: 'MEDIUM',
    points: 32,
    tags: ['Rekursiya'],
    description: "Musbat butun n soni berilgan. Rekursiya va memoizatsiya (hisoblangan qiymatlarni saqlab qolish) yordamida Fibonachchi ketma-ketligining birinchi n ta hadini (F(0), F(1), ..., F(n-1)) massiv sifatida qaytaring, bunda F(0)=0, F(1)=1.\n\n**1-misol:**\nKiritma: n = 6\nNatija: [0,1,1,2,3,5]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [0]",
    starterCodeJs: 'function fibonacciSequence(n) {\n  // your code here\n}',
    starterCodePy: 'def fibonacci_sequence(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<long long> fibonacciSequence(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-038',
    title: "Rekursiv Binary Search Algoritmi",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Rekursiya'],
    description: "O'sish tartibida saralangan nums massivi va target soni berilgan. Rekursiv (aynan rekursiv, tsikl orqali emas) binary search algoritmi yordamida target ning massivdagi indeksini toping; agar topilmasa -1 qaytaring.\n\n**1-misol:**\nKiritma: nums = [-1,0,3,5,9,12], target = 9\nNatija: 4\n\n**2-misol:**\nKiritma: nums = [-1,0,3,5,9,12], target = 2\nNatija: -1",
    starterCodeJs: 'function recursiveBinarySearch(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def recursive_binary_search(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'int recursiveBinarySearch(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-039',
    title: "Massivni Rekursiya Bilan Teskarisiga O'girish",
    difficulty: 'MEDIUM',
    points: 30,
    tags: ['Rekursiya'],
    description: "Butun sonlar massivi nums berilgan. Faqat rekursiya yordamida (tsikl ishlatmasdan) massiv elementlarini teskari tartibga o'tkazing va natijaviy massivni qaytaring.\n\n**1-misol:**\nKiritma: nums = [1,2,3,4,5]\nNatija: [5,4,3,2,1]\n\n**2-misol:**\nKiritma: nums = [7]\nNatija: [7]",
    starterCodeJs: 'function reverseArrayRecursive(nums) {\n  // your code here\n}',
    starterCodePy: 'def reverse_array_recursive(nums):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> reverseArrayRecursive(vector<int>& nums) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-040',
    title: "Satrning Palindromligini Rekursiya Bilan Tekshirish",
    difficulty: 'MEDIUM',
    points: 31,
    tags: ['Rekursiya'],
    description: "s satri berilgan. Faqat rekursiya yordamida (tsikl ishlatmasdan), s ning palindrom (old va orqadan bir xil o'qiladigan) ekanligini tekshiring va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: s = \"level\"\nNatija: true\n\n**2-misol:**\nKiritma: s = \"dunyo\"\nNatija: false",
    starterCodeJs: 'function isPalindromeStringRecursive(s) {\n  // your code here\n}',
    starterCodePy: 'def is_palindrome_string_recursive(s):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isPalindromeStringRecursive(string s) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-041',
    title: "N Juft Qavslarning To'g'ri Kombinatsiyalarini Generatsiya Qilish",
    difficulty: 'MEDIUM',
    points: 39,
    tags: ['Rekursiya'],
    description: "Musbat butun n soni berilgan (juft qavslar soni). Rekursiv backtracking yordamida, n juft qavsdan tashkil topgan barcha to'g'ri (well-formed) qavslar kombinatsiyalarini generatsiya qiling.\n\n**1-misol:**\nKiritma: n = 3\nNatija: [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]\n\n**2-misol:**\nKiritma: n = 1\nNatija: [\"()\"]",
    starterCodeJs: 'function generateParenthesis(n) {\n  // your code here\n}',
    starterCodePy: 'def generate_parenthesis(n):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> generateParenthesis(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-042',
    title: "Subset Sum: Berilgan Yig'indiga Erishish Mumkinligini Tekshirish",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Rekursiya'],
    description: "Manfiy bo'lmagan sonlardan iborat nums massivi va target soni berilgan. Rekursiya (va memoizatsiya) yordamida, massivning ba'zi elementlarini tanlab, yig'indisi aynan target ga teng bo'lgan kichik to'plam mavjudligini aniqlang va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: nums = [3,34,4,12,5,2], target = 9\nNatija: true\nIzoh: 4+5=9.\n\n**2-misol:**\nKiritma: nums = [1,2,3], target = 7\nNatija: false",
    starterCodeJs: 'function canSumSubset(nums, target) {\n  // your code here\n}',
    starterCodePy: 'def can_sum_subset(nums, target):\n    # your code here\n    pass',
    starterCodeCpp: 'bool canSumSubset(vector<int>& nums, int target) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-043',
    title: "Word Break: Satrni Lug'at So'zlariga Bo'lish",
    difficulty: 'MEDIUM',
    points: 42,
    tags: ['Rekursiya'],
    description: "s satri va wordDict so'zlar ro'yxati berilgan. Rekursiya va memoizatsiya yordamida, s satrini bir yoki bir nechta wordDict so'zlaridan iborat ketma-ketlik sifatida ifodalash mumkinligini aniqlang va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: s = \"leetcode\", wordDict = [\"leet\",\"code\"]\nNatija: true\n\n**2-misol:**\nKiritma: s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]\nNatija: false",
    starterCodeJs: 'function wordBreak(s, wordDict) {\n  // your code here\n}',
    starterCodePy: 'def word_break(s, word_dict):\n    # your code here\n    pass',
    starterCodeCpp: 'bool wordBreak(string s, vector<string>& wordDict) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-044',
    title: "Ikkilik Daraxt Diametrini Rekursiya Bilan Hisoblash",
    difficulty: 'MEDIUM',
    points: 40,
    tags: ['Rekursiya'],
    description: "Ikkilik daraxt (binary tree) ildizi root berilgan. Daraxtning diametrini — ixtiyoriy ikkita tugun orasidagi eng uzun yo'lda joylashgan qirralar (edges) sonini — rekursiya yordamida hisoblang.\n\n**1-misol:**\nKiritma: root = {val:1, left:{val:2, left:{val:4}, right:{val:5}}, right:{val:3}}\nNatija: 3\nIzoh: Eng uzun yo'l 4->2->5 yoki 4->2->1->3 kabi yo'llar orasida 3 qirra.\n\n**2-misol:**\nKiritma: root = {val:1}\nNatija: 0",
    starterCodeJs: 'function diameterOfBinaryTree(root) {\n  // your code here\n}',
    starterCodePy: 'def diameter_of_binary_tree(root):\n    # your code here\n    pass',
    starterCodeCpp: 'int diameterOfBinaryTree(TreeNode* root) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-045',
    title: "Labirintdagi Barcha Yo'llarni Rekursiya Bilan Topish",
    difficulty: 'MEDIUM',
    points: 44,
    tags: ['Rekursiya'],
    description: "n x n o'lchamli maze matritsasi berilgan, bunda 1 - o'tish mumkin bo'lgan katak, 0 - to'siq. Chapdan yuqori burchak (0,0) dan boshlab, faqat o'ngga yoki pastga harakatlanib, o'ng-past burchak (n-1,n-1) gacha yetib borishning barcha mumkin bo'lgan yo'llarini rekursiv backtracking yordamida \"DDRR\" kabi harakatlar satrlari (D-pastga, R-o'ngga) ro'yxati sifatida qaytaring.\n\n**1-misol:**\nKiritma: maze = [[1,0],[1,1]]\nNatija: [\"DR\"]\n\n**2-misol:**\nKiritma: maze = [[1,1],[1,1]]\nNatija: [\"DR\",\"RD\"]",
    starterCodeJs: 'function findMazePaths(maze) {\n  // your code here\n}',
    starterCodePy: 'def find_maze_paths(maze):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<string> findMazePaths(vector<vector<int>>& maze) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-046',
    title: "2xN Taxtani Domino Bilan Qoplash Usullari Soni",
    difficulty: 'MEDIUM',
    points: 33,
    tags: ['Rekursiya'],
    description: "Musbat butun n soni berilgan. 2xN o'lchamli taxtani 1x2 o'lchamli domino toshlari bilan (gorizontal yoki vertikal joylashtirib) to'liq qoplashning nechta usuli borligini rekursiya (va memoizatsiya) yordamida hisoblang.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 3\n\n**2-misol:**\nKiritma: n = 4\nNatija: 5",
    starterCodeJs: 'function tilingWays(n) {\n  // your code here\n}',
    starterCodePy: 'def tiling_ways(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long tilingWays(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-047',
    title: "Katalon Sonini Rekursiv Formula Bilan Hisoblash",
    difficulty: 'MEDIUM',
    points: 36,
    tags: ['Rekursiya'],
    description: "Manfiy bo'lmagan butun n soni berilgan. n-chi Katalon sonini C(n) = sum(C(i)*C(n-1-i)) rekursiv formulasidan foydalanib hisoblang, bunda C(0) = 1.\n\n**1-misol:**\nKiritma: n = 3\nNatija: 5\n\n**2-misol:**\nKiritma: n = 4\nNatija: 14",
    starterCodeJs: 'function catalanNumber(n) {\n  // your code here\n}',
    starterCodePy: 'def catalan_number(n):\n    # your code here\n    pass',
    starterCodeCpp: 'long long catalanNumber(int n) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-048',
    title: "1 Dan N Gacha Sonlardan K Talik Kombinatsiyalar",
    difficulty: 'MEDIUM',
    points: 38,
    tags: ['Rekursiya'],
    description: "Ikkita butun son n va k berilgan. Rekursiv backtracking yordamida, 1 dan n gacha bo'lgan sonlardan tuzilishi mumkin bo'lgan barcha k elementli kombinatsiyalarni qaytaring.\n\n**1-misol:**\nKiritma: n = 4, k = 2\nNatija: [[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]\n\n**2-misol:**\nKiritma: n = 3, k = 3\nNatija: [[1,2,3]]",
    starterCodeJs: 'function combine(n, k) {\n  // your code here\n}',
    starterCodePy: 'def combine(n, k):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<vector<int>> combine(int n, int k) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-049',
    title: "Ikki Saralangan Massivni Rekursiya Bilan Birlashtirish",
    difficulty: 'MEDIUM',
    points: 34,
    tags: ['Rekursiya'],
    description: "O'sish tartibida saralangan ikkita a va b massivlari berilgan. Faqat rekursiya yordamida (asosiy tsikl ishlatmasdan) ularni bitta saralangan massivga birlashtiring va natijani qaytaring.\n\n**1-misol:**\nKiritma: a = [1,3,5], b = [2,4,6]\nNatija: [1,2,3,4,5,6]\n\n**2-misol:**\nKiritma: a = [], b = [1,2]\nNatija: [1,2]",
    starterCodeJs: 'function mergeSortedArraysRecursive(a, b) {\n  // your code here\n}',
    starterCodePy: 'def merge_sorted_arrays_recursive(a, b):\n    # your code here\n    pass',
    starterCodeCpp: 'vector<int> mergeSortedArraysRecursive(vector<int>& a, vector<int>& b) {\n    // your code here\n}',
  },
  {
    key: 'medium-b-050',
    title: "Ikkilik Daraxtning Muvozanatlashganligini Rekursiya Bilan Tekshirish",
    difficulty: 'MEDIUM',
    points: 37,
    tags: ['Rekursiya'],
    description: "Ikkilik daraxt (binary tree) ildizi root berilgan. Rekursiya yordamida, daraxtning har bir tugunida chap va o'ng qism daraxtlar balandliklari farqi 1 dan oshmasligini tekshirib, daraxt muvozanatlashgan (balanced) ekanligini aniqlang va true yoki false qaytaring.\n\n**1-misol:**\nKiritma: root = {val:3, left:{val:9}, right:{val:20, left:{val:15}, right:{val:7}}}\nNatija: true\n\n**2-misol:**\nKiritma: root = {val:1, left:{val:2, left:{val:3, left:{val:4}}}}\nNatija: false",
    starterCodeJs: 'function isBalanced(root) {\n  // your code here\n}',
    starterCodePy: 'def is_balanced(root):\n    # your code here\n    pass',
    starterCodeCpp: 'bool isBalanced(TreeNode* root) {\n    // your code here\n}',
  },
];
