// Hand-authored practice problems for backend lessons 5-8 (Oy 1).
// Every `expectedStdout` below was produced by running a reference solution
// inside the Piston sandbox (python 3.10.0) — none of them are written by hand.
import type { LessonProblemRecord } from './types';

export const backendProblemsM1B: LessonProblemRecord[] = [
  {
    lessonKey: "backend-dars-05",
    key: "backend-dars-05-easy",
    title: "So'zning uchta harfi",
    difficulty: "EASY",
    points: 10,
    tags: ["python", "satr", "indeks"],
    description: "Foydalanuvchidan bitta so'z olinadi (u stdin orqali beriladi — `input()` bilan o'qing).\n\nShu so'zning birinchi, o'rtadagi va oxirgi harfini AYNAN quyidagi ko'rinishda, uch qatorda chiqaring:\n\n```\nBirinchi: <birinchi harf>\nO'rtadagi: <o'rtadagi harf>\nOxirgi: <oxirgi harf>\n```\n\nO'rtadagi harf deganda `len(soz) // 2` indeksdagi harf tushuniladi.\n\nMisol — kirish:\n```\nSALOM\n```\nKutilgan chiqish:\n```\nBirinchi: S\nO'rtadagi: L\nOxirgi: M\n```",
    starterCodePy: "# So'zni input() bilan o'qing va uni soz o'zgaruvchisiga saqlang.\n# Keyin soz[0], soz[len(soz) // 2] va soz[-1] harflarini\n# yuqoridagi format bo'yicha uchta print() bilan chiqaring.\n",
    testCases: [
      {
        stdin: "SALOM\n",
        expectedStdout: "Birinchi: S\nO'rtadagi: L\nOxirgi: M\n",
        hidden: false,
        label: "Misoldagi so'z",
      },
      {
        stdin: "python\n",
        expectedStdout: "Birinchi: p\nO'rtadagi: h\nOxirgi: n\n",
        hidden: false,
        label: "Kichik harfli so'z",
      },
      {
        stdin: "a\n",
        expectedStdout: "Birinchi: a\nO'rtadagi: a\nOxirgi: a\n",
        hidden: true,
        label: "Bitta harfdan iborat so'z",
      },
      {
        stdin: "TOSHKENT\n",
        expectedStdout: "Birinchi: T\nO'rtadagi: K\nOxirgi: T\n",
        hidden: true,
        label: "Uzun so'z",
      },
    ],
  },
  {
    lessonKey: "backend-dars-05",
    key: "backend-dars-05-medium",
    title: "Bosh harflar (A.K.)",
    difficulty: "MEDIUM",
    points: 20,
    tags: ["python", "satr", "indeks", "slicing"],
    description: "Foydalanuvchi bitta qatorda ism va familiyani yozadi, ular orasida bitta bo'sh joy bo'ladi (stdin orqali beriladi).\n\nSiz faqat ularning bosh harflarini KATTA harfda, nuqtalar bilan, bitta qatorda chiqarishingiz kerak:\n\n```\nA.K.\n```\n\nYa'ni: ismning birinchi harfi, nuqta, familiyaning birinchi harfi, nuqta. Kirish kichik harflarda bo'lsa ham natija katta harfda bo'ladi.\n\nMisol — kirish:\n```\nAli Karimov\n```\nKutilgan chiqish:\n```\nA.K.\n```",
    starterCodePy: "# Qatorni input() bilan o'qing.\n# Bo'sh joy indeksini toping (masalan .index(\" \") bilan),\n# ismning va familiyaning birinchi harfini ajratib oling,\n# ularni .upper() bilan katta harfga aylantiring\n# va \"A.K.\" ko'rinishida bitta print() bilan chiqaring.\n",
    testCases: [
      {
        stdin: "Ali Karimov\n",
        expectedStdout: "A.K.\n",
        hidden: false,
        label: "Misoldagi ism-familiya",
      },
      {
        stdin: "dilnoza usmonova\n",
        expectedStdout: "D.U.\n",
        hidden: true,
        label: "Kichik harflar bilan yozilgan",
      },
      {
        stdin: "Bobur Mirzo\n",
        expectedStdout: "B.M.\n",
        hidden: false,
        label: "Boshqa ism-familiya",
      },
    ],
  },
  {
    lessonKey: "backend-dars-05",
    key: "backend-dars-05-hard",
    title: "Teskari so'z va palindrom",
    difficulty: "HARD",
    points: 35,
    tags: ["python", "satr", "slicing", "palindrom"],
    description: "Foydalanuvchidan bitta so'z olinadi (stdin orqali beriladi).\n\nDastur ikki qator chiqarishi kerak:\n\n```\nTeskari: <so'zning teskari ko'rinishi>\nPalindrom: Ha\n```\n\nIkkinchi qatorda, agar teskari so'z asl so'z bilan bir xil bo'lsa `Palindrom: Ha`, aks holda `Palindrom: Yo'q` yoziladi.\n\nMisol — kirish:\n```\nsalom\n```\nKutilgan chiqish:\n```\nTeskari: molas\nPalindrom: Yo'q\n```",
    starterCodePy: "# So'zni input() bilan o'qing.\n# Teskari ko'rinishini slicing yordamida oling: soz[::-1]\n# Birinchi qatorda teskari so'zni chiqaring,\n# so'ng if bilan taqqoslab \"Palindrom: Ha\" yoki \"Palindrom: Yo'q\" deb yozing.\n",
    testCases: [
      {
        stdin: "salom\n",
        expectedStdout: "Teskari: molas\nPalindrom: Yo'q\n",
        hidden: false,
        label: "Misoldagi so'z (palindrom emas)",
      },
      {
        stdin: "kanak\n",
        expectedStdout: "Teskari: kanak\nPalindrom: Ha\n",
        hidden: false,
        label: "Palindrom so'z",
      },
      {
        stdin: "a\n",
        expectedStdout: "Teskari: a\nPalindrom: Ha\n",
        hidden: true,
        label: "Bitta harf — har doim palindrom",
      },
      {
        stdin: "anna\n",
        expectedStdout: "Teskari: anna\nPalindrom: Ha\n",
        hidden: true,
        label: "Juft uzunlikdagi palindrom",
      },
    ],
  },
  {
    lessonKey: "backend-dars-06",
    key: "backend-dars-06-easy",
    title: "Katta va kichik harflar",
    difficulty: "EASY",
    points: 10,
    tags: ["python", "satr", "metodlar", "upper", "lower"],
    description: "Foydalanuvchidan bitta gap olinadi (stdin orqali beriladi).\n\nGapni avval boshidagi va oxiridagi ortiqcha bo'sh joylardan tozalang (`strip()`), so'ng ikki qator chiqaring:\n\n1-qator — gap butunlay KATTA harflarda;\n2-qator — gap butunlay kichik harflarda.\n\nBoshqa hech qanday matn (izoh, sarlavha) chiqarilmaydi.\n\nMisol — kirish:\n```\nBugun havo issiq\n```\nKutilgan chiqish:\n```\nBUGUN HAVO ISSIQ\nbugun havo issiq\n```",
    starterCodePy: "# Gapni input() bilan o'qing va .strip() bilan tozalang.\n# Birinchi print() da .upper(), ikkinchisida .lower() natijasini chiqaring.\n",
    testCases: [
      {
        stdin: "Bugun havo issiq\n",
        expectedStdout: "BUGUN HAVO ISSIQ\nbugun havo issiq\n",
        hidden: false,
        label: "Misoldagi gap",
      },
      {
        stdin: "   Python O'RGANAMIZ   \n",
        expectedStdout: "PYTHON O'RGANAMIZ\npython o'rganamiz\n",
        hidden: true,
        label: "Ortiqcha bo'sh joylar bilan",
      },
      {
        stdin: "SALOM Dunyo\n",
        expectedStdout: "SALOM DUNYO\nsalom dunyo\n",
        hidden: false,
        label: "Aralash harflar",
      },
    ],
  },
  {
    lessonKey: "backend-dars-06",
    key: "backend-dars-06-medium",
    title: "So'zlar soni va birinchi so'z",
    difficulty: "MEDIUM",
    points: 20,
    tags: ["python", "satr", "split", "len"],
    description: "Foydalanuvchidan bitta gap olinadi (stdin orqali beriladi).\n\nGapdagi so'zlar sonini va eng birinchi so'zni AYNAN quyidagi ko'rinishda, ikki qatorda chiqaring:\n\n```\nSo'zlar soni: <son>\nBirinchi so'z: <birinchi so'z>\n```\n\nSo'zlar bo'sh joy bilan ajratilgan. Agar so'zlar orasida bir nechta bo'sh joy bo'lsa ham, bo'sh joylar so'z hisoblanmaydi — `split()` buni o'zi to'g'ri hal qiladi.\n\nMisol — kirish:\n```\nMen bugun python o'rganaman\n```\nKutilgan chiqish:\n```\nSo'zlar soni: 4\nBirinchi so'z: Men\n```",
    starterCodePy: "# Gapni input() bilan o'qing, .strip() bilan tozalang.\n# .split() yordamida so'zlar ro'yxatini oling.\n# len() bilan so'zlar sonini, [0] bilan birinchi so'zni chiqaring.\n",
    testCases: [
      {
        stdin: "Men bugun python o'rganaman\n",
        expectedStdout: "So'zlar soni: 4\nBirinchi so'z: Men\n",
        hidden: false,
        label: "Misoldagi gap",
      },
      {
        stdin: "   Salom    dunyo   \n",
        expectedStdout: "So'zlar soni: 2\nBirinchi so'z: Salom\n",
        hidden: true,
        label: "Ortiqcha bo'sh joylar bilan",
      },
      {
        stdin: "Assalomu\n",
        expectedStdout: "So'zlar soni: 1\nBirinchi so'z: Assalomu\n",
        hidden: true,
        label: "Faqat bitta so'z",
      },
    ],
  },
  {
    lessonKey: "backend-dars-06",
    key: "backend-dars-06-hard",
    title: "Unli harflarni sanash",
    difficulty: "HARD",
    points: 35,
    tags: ["python", "satr", "sanash", "unlilar"],
    description: "Foydalanuvchidan bitta gap olinadi (stdin orqali beriladi).\n\nGapdagi unli harflar (a, e, i, o, u) sonini sanang. Katta harflar ham hisobga olinadi: `A` ham unli, `a` ham unli.\n\nNatijani AYNAN bitta qatorda chiqaring:\n\n```\nUnlilar soni: <son>\n```\n\nMisol — kirish:\n```\nBugun havo issiq\n```\nKutilgan chiqish:\n```\nUnlilar soni: 6\n```",
    starterCodePy: "# Gapni input() bilan o'qing va .lower() bilan kichik harfga o'tkazing.\n# Hisoblagich o'zgaruvchi yarating (soni = 0),\n# gapning har bir harfini tekshirib, u \"aeiou\" ichida bo'lsa soni ni oshiring.\n# Oxirida \"Unlilar soni:\" bilan birga chiqaring.\n",
    testCases: [
      {
        stdin: "Bugun havo issiq\n",
        expectedStdout: "Unlilar soni: 6\n",
        hidden: false,
        label: "Misoldagi gap",
      },
      {
        stdin: "PYTHON\n",
        expectedStdout: "Unlilar soni: 1\n",
        hidden: false,
        label: "Deyarli unlisiz so'z",
      },
      {
        stdin: "brr\n",
        expectedStdout: "Unlilar soni: 0\n",
        hidden: true,
        label: "Umuman unli yo'q",
      },
      {
        stdin: "AEIOU aeiou\n",
        expectedStdout: "Unlilar soni: 10\n",
        hidden: true,
        label: "Faqat unlilar, katta va kichik",
      },
    ],
  },
  {
    lessonKey: "backend-dars-07",
    key: "backend-dars-07-easy",
    title: "100 dan katta yoki kichik",
    difficulty: "EASY",
    points: 10,
    tags: ["python", "if", "taqqoslash"],
    description: "Foydalanuvchidan bitta butun son olinadi (stdin orqali beriladi).\n\nSonni 100 bilan solishtiring va AYNAN bitta qator chiqaring:\n\n- son 100 dan katta bo'lsa: `100 dan katta`\n- son 100 dan kichik bo'lsa: `100 dan kichik`\n- son roppa-rosa 100 bo'lsa: `100 ga teng`\n\nMisol — kirish:\n```\n250\n```\nKutilgan chiqish:\n```\n100 dan katta\n```",
    starterCodePy: "# Sonni int(input()) bilan o'qing.\n# if / elif / else yordamida uni 100 bilan solishtiring\n# va yuqoridagi uchta matndan mosini chiqaring.\n",
    testCases: [
      {
        stdin: "250\n",
        expectedStdout: "100 dan katta\n",
        hidden: false,
        label: "Misol — katta son",
      },
      {
        stdin: "7\n",
        expectedStdout: "100 dan kichik\n",
        hidden: false,
        label: "Kichik son",
      },
      {
        stdin: "100\n",
        expectedStdout: "100 ga teng\n",
        hidden: true,
        label: "Roppa-rosa 100",
      },
      {
        stdin: "-4\n",
        expectedStdout: "100 dan kichik\n",
        hidden: true,
        label: "Manfiy son",
      },
    ],
  },
  {
    lessonKey: "backend-dars-07",
    key: "backend-dars-07-medium",
    title: "Balldan bahoga",
    difficulty: "MEDIUM",
    points: 20,
    tags: ["python", "if", "elif", "baho"],
    description: "Foydalanuvchidan bitta butun ball olinadi (0 dan 100 gacha, stdin orqali beriladi).\n\nBallni bahoga aylantiring:\n\n- ball >= 90 → baho 5\n- ball >= 70 → baho 4\n- ball >= 50 → baho 3\n- aks holda → baho 2\n\nNatijani AYNAN bitta qatorda chiqaring:\n```\nBaho: <baho>\n```\n\nMisol — kirish:\n```\n95\n```\nKutilgan chiqish:\n```\nBaho: 5\n```",
    starterCodePy: "# Ballni int(input()) bilan o'qing.\n# if / elif / elif / else yordamida bahoni aniqlang.\n# Shartlar tartibi muhim — eng kattasidan boshlang.\n# Natijani \"Baho:\" bilan birga chiqaring.\n",
    testCases: [
      {
        stdin: "95\n",
        expectedStdout: "Baho: 5\n",
        hidden: false,
        label: "Misol — a'lo ball",
      },
      {
        stdin: "70\n",
        expectedStdout: "Baho: 4\n",
        hidden: true,
        label: "Chegara ball 70",
      },
      {
        stdin: "49\n",
        expectedStdout: "Baho: 2\n",
        hidden: false,
        label: "Chegaradan bir pastda",
      },
      {
        stdin: "0\n",
        expectedStdout: "Baho: 2\n",
        hidden: true,
        label: "Eng past ball",
      },
      {
        stdin: "100\n",
        expectedStdout: "Baho: 5\n",
        hidden: true,
        label: "Maksimal ball",
      },
    ],
  },
  {
    lessonKey: "backend-dars-07",
    key: "backend-dars-07-hard",
    title: "Kabisa yili",
    difficulty: "HARD",
    points: 35,
    tags: ["python", "if", "kabisa", "modul"],
    description: "Foydalanuvchidan bitta yil (butun son) olinadi (stdin orqali beriladi).\n\nYil kabisa yili bo'ladi, agar:\n- u 4 ga bo'linsa VA 100 ga bo'linmasa,\n- YOKI u 400 ga bo'linsa.\n\nNatijani AYNAN bitta qatorda chiqaring: kabisa bo'lsa `Kabisa`, aks holda `Kabisa emas`.\n\nMisol — kirish:\n```\n2024\n```\nKutilgan chiqish:\n```\nKabisa\n```",
    starterCodePy: "# Yilni int(input()) bilan o'qing.\n# % (qoldiq) operatoridan foydalanib shartni yozing:\n# (yil % 4 == 0 va yil % 100 != 0) yoki yil % 400 == 0\n# Natijaga qarab \"Kabisa\" yoki \"Kabisa emas\" chiqaring.\n",
    testCases: [
      {
        stdin: "2024\n",
        expectedStdout: "Kabisa\n",
        hidden: false,
        label: "Misol — oddiy kabisa yil",
      },
      {
        stdin: "1900\n",
        expectedStdout: "Kabisa emas\n",
        hidden: true,
        label: "100 ga bo'linadi, lekin 400 ga yo'q",
      },
      {
        stdin: "2000\n",
        expectedStdout: "Kabisa\n",
        hidden: true,
        label: "400 ga bo'linadi",
      },
      {
        stdin: "2023\n",
        expectedStdout: "Kabisa emas\n",
        hidden: false,
        label: "Oddiy yil",
      },
    ],
  },
  {
    lessonKey: "backend-dars-08",
    key: "backend-dars-08-easy",
    title: "Ikkalasi ham musbatmi?",
    difficulty: "EASY",
    points: 10,
    tags: ["python", "and", "mantiq"],
    description: "Stdin orqali ikkita butun son beriladi — har biri alohida qatorda. Ularni ikkita `input()` bilan o'qing.\n\n`and` operatoridan foydalanib, ikkala son ham musbat (noldan katta) ekanini tekshiring va AYNAN bitta qator chiqaring:\n\n- ikkalasi ham musbat bo'lsa: `Ikkalasi ham musbat`\n- aks holda: `Ikkalasi ham musbat emas`\n\nDiqqat: 0 musbat son EMAS.\n\nMisol — kirish:\n```\n5\n12\n```\nKutilgan chiqish:\n```\nIkkalasi ham musbat\n```",
    starterCodePy: "# Ikkita sonni ketma-ket int(input()) bilan o'qing.\n# if a > 0 and b > 0: shartini yozing\n# va mos matnni chiqaring.\n",
    testCases: [
      {
        stdin: "5\n12\n",
        expectedStdout: "Ikkalasi ham musbat\n",
        hidden: false,
        label: "Misol — ikkalasi musbat",
      },
      {
        stdin: "-3\n8\n",
        expectedStdout: "Ikkalasi ham musbat emas\n",
        hidden: false,
        label: "Biri manfiy",
      },
      {
        stdin: "0\n0\n",
        expectedStdout: "Ikkalasi ham musbat emas\n",
        hidden: true,
        label: "Ikkalasi ham nol",
      },
      {
        stdin: "1\n1\n",
        expectedStdout: "Ikkalasi ham musbat\n",
        hidden: true,
        label: "Eng kichik musbat sonlar",
      },
    ],
  },
  {
    lessonKey: "backend-dars-08",
    key: "backend-dars-08-medium",
    title: "Chegirma foizi",
    difficulty: "MEDIUM",
    points: 20,
    tags: ["python", "and", "or", "chegirma"],
    description: "Stdin orqali ikkita qator beriladi:\n1-qator — yosh (butun son);\n2-qator — talabalik holati: `ha` yoki `yoq`.\n\nChegirmani quyidagi tartibda aniqlang (birinchi mos kelgan qoida ishlaydi):\n\n- yosh 12 dan kichik → 50\n- yosh 60 dan katta yoki teng → 40\n- talabalik holati `ha` → 30\n- aks holda → 0\n\nNatijani AYNAN bitta qatorda chiqaring:\n```\nChegirma: <foiz>%\n```\n\nMisol — kirish:\n```\n10\nyoq\n```\nKutilgan chiqish:\n```\nChegirma: 50%\n```",
    starterCodePy: "# Birinchi qatordan yoshni int(input()) bilan,\n# ikkinchi qatordan talabalik holatini input().strip().lower() bilan o'qing.\n# if / elif zanjiri bilan chegirmani aniqlang (tartib muhim!)\n# va \"Chegirma: 50%\" ko'rinishida chiqaring.\n",
    testCases: [
      {
        stdin: "10\nyoq\n",
        expectedStdout: "Chegirma: 50%\n",
        hidden: false,
        label: "Misol — bola, talaba emas",
      },
      {
        stdin: "20\nha\n",
        expectedStdout: "Chegirma: 30%\n",
        hidden: false,
        label: "Talaba",
      },
      {
        stdin: "65\nha\n",
        expectedStdout: "Chegirma: 40%\n",
        hidden: true,
        label: "Keksa va talaba — yosh qoidasi ustun",
      },
      {
        stdin: "35\nyoq\n",
        expectedStdout: "Chegirma: 0%\n",
        hidden: false,
        label: "Chegirmasiz",
      },
      {
        stdin: "12\nha\n",
        expectedStdout: "Chegirma: 30%\n",
        hidden: true,
        label: "12 yosh — bolalar chegirmasi tugadi",
      },
    ],
  },
  {
    lessonKey: "backend-dars-08",
    key: "backend-dars-08-hard",
    title: "Uchta sondan eng kattasi",
    difficulty: "HARD",
    points: 35,
    tags: ["python", "if", "elif", "taqqoslash"],
    description: "Stdin orqali uchta butun son beriladi — har biri alohida qatorda.\n\nUlarning eng kattasini toping. `max()` funksiyasidan FOYDALANMANG — faqat `if` / `elif` va taqqoslash operatorlaridan foydalaning.\n\nNatijani AYNAN bitta qatorda chiqaring:\n```\nEng katta: <son>\n```\n\nSonlar teng bo'lishi ham mumkin — bunda o'sha qiymatning o'zi chiqariladi.\n\nMisol — kirish:\n```\n3\n9\n5\n```\nKutilgan chiqish:\n```\nEng katta: 9\n```",
    starterCodePy: "# Uchta sonni ketma-ket int(input()) bilan o'qing.\n# if a >= b and a >= c: ... elif ... else ... zanjirini yozing\n# va eng kattasini \"Eng katta:\" bilan birga chiqaring.\n",
    testCases: [
      {
        stdin: "3\n9\n5\n",
        expectedStdout: "Eng katta: 9\n",
        hidden: false,
        label: "Misol — o'rtadagi son eng katta",
      },
      {
        stdin: "-10\n-4\n-7\n",
        expectedStdout: "Eng katta: -4\n",
        hidden: true,
        label: "Manfiy sonlar",
      },
      {
        stdin: "7\n7\n7\n",
        expectedStdout: "Eng katta: 7\n",
        hidden: true,
        label: "Uchalasi teng",
      },
      {
        stdin: "100\n2\n99\n",
        expectedStdout: "Eng katta: 100\n",
        hidden: false,
        label: "Birinchi son eng katta",
      },
    ],
  },
];
