// Hand-authored practice problems for backend lessons 09–12 (1-oy, 3–4-hafta).
// Har bir masala mos darsning makeEasy / makeMedium / makeHard topshirig'idan olingan.
// Barcha `expectedStdout` qiymatlari etalon yechimni jonli Piston (python 3.10.0)
// sandbox'ida ishga tushirib olingan — qo'lda yozilmagan.
import type { LessonProblemRecord } from './types';

export const backendProblemsM1c: LessonProblemRecord[] = [
  // ─── Dars 09 — while sikli ────────────────────────────────────────────────
  {
    lessonKey: 'backend-dars-09',
    key: 'backend-dars-09-easy',
    title: 'Kvadratlar jadvali (while)',
    difficulty: 'EASY',
    points: 10,
    tags: ['python', 'while', 'sikl'],
    description: [
      "Kirishda bitta butun son **N** beriladi (test stdin orqali uzatiladi).",
      '',
      "`while` sikli yordamida 1 dan N gacha bo'lgan har bir son uchun bitta qator chiqaring.",
      "Qator formati aniq shunday bo'lsin:",
      '',
      '```',
      'i * i = kvadrat',
      '```',
      '',
      "Ya'ni son, probel, yulduzcha, probel, yana o'sha son, probel, teng, probel, natija.",
      '',
      '**Misol.** Kirish:',
      '```',
      '3',
      '```',
      'Chiqish:',
      '```',
      '1 * 1 = 1',
      '2 * 2 = 4',
      '3 * 3 = 9',
      '```',
    ].join('\n'),
    starterCodePy: [
      '# N ni o\'qib oling va while sikli bilan 1 dan N gacha',
      '# "i * i = kvadrat" ko\'rinishidagi qatorlarni chiqaring.',
      'n = int(input())',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '3\n',
        expectedStdout: '1 * 1 = 1\n2 * 2 = 4\n3 * 3 = 9\n',
        hidden: false,
        label: 'Misoldagi holat: N = 3',
      },
      {
        stdin: '10\n',
        expectedStdout:
          '1 * 1 = 1\n2 * 2 = 4\n3 * 3 = 9\n4 * 4 = 16\n5 * 5 = 25\n6 * 6 = 36\n7 * 7 = 49\n8 * 8 = 64\n9 * 9 = 81\n10 * 10 = 100\n',
        hidden: false,
        label: "Darsdagi asosiy holat: N = 10",
      },
      {
        stdin: '1\n',
        expectedStdout: '1 * 1 = 1\n',
        hidden: true,
        label: "Chegara holat: N = 1, faqat bitta qator",
      },
      {
        stdin: '5\n',
        expectedStdout: '1 * 1 = 1\n2 * 2 = 4\n3 * 3 = 9\n4 * 4 = 16\n5 * 5 = 25\n',
        hidden: true,
        label: 'Yashirin holat: N = 5',
      },
    ],
  },
  {
    lessonKey: 'backend-dars-09',
    key: 'backend-dars-09-medium',
    title: "Nol kelguncha yig'indi",
    difficulty: 'MEDIUM',
    points: 20,
    tags: ['python', 'while', 'input', 'break'],
    description: [
      "Dastur `while` sikli ichida foydalanuvchidan sonlarni birma-bir so'raydi.",
      "Har bir son alohida qatorda keladi (test stdin orqali beradi).",
      '',
      "**0** kiritilgan zahoti sikl to'xtaydi. 0 ning o'zi yig'indiga qo'shilmaydi.",
      '',
      "Oxirida faqat bitta qator chiqaring:",
      '```',
      "Yig'indi: X",
      '```',
      "bu yerda X — kiritilgan sonlarning yig'indisi. Sonlar manfiy ham bo'lishi mumkin.",
      '',
      '**Misol.** Kirish:',
      '```',
      '5',
      '7',
      '3',
      '0',
      '```',
      'Chiqish:',
      '```',
      "Yig'indi: 15",
      '```',
    ].join('\n'),
    starterCodePy: [
      "# while sikli bilan sonlarni o'qing, 0 kelganda break qiling",
      "# va oxirida \"Yig'indi: X\" ni chiqaring.",
      'total = 0',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '5\n7\n3\n0\n',
        expectedStdout: "Yig'indi: 15\n",
        hidden: false,
        label: 'Misoldagi holat: 5, 7, 3, keyin 0',
      },
      {
        stdin: '1\n2\n3\n4\n5\n0\n',
        expectedStdout: "Yig'indi: 15\n",
        hidden: false,
        label: "Beshta son ketma-ket",
      },
      {
        stdin: '0\n',
        expectedStdout: "Yig'indi: 0\n",
        hidden: true,
        label: "Chegara holat: darrov 0 kiritildi",
      },
      {
        stdin: '100\n-40\n0\n',
        expectedStdout: "Yig'indi: 60\n",
        hidden: true,
        label: "Manfiy son ham qatnashadi",
      },
    ],
  },
  {
    lessonKey: 'backend-dars-09',
    key: 'backend-dars-09-hard',
    title: "Sonni top: katta/kichik yo'riqnomasi",
    difficulty: 'HARD',
    points: 35,
    tags: ['python', 'while', 'shart', 'oyin'],
    description: [
      "«Sonni top» o'yinining tekshiriladigan varianti. Tasodifiy son ishlatmaymiz —",
      "yashirin son ham stdin orqali beriladi, shunda natija har safar bir xil bo'ladi.",
      '',
      '**Kirish tartibi:**',
      '1. Birinchi qator — yashirin son (1 dan 100 gacha).',
      "2. Keyingi har bir qator — o'yinchining navbatdagi taxmini.",
      '',
      "Har bir taxmindan keyin bitta qator chiqaring:",
      "- taxmin yashirin sondan **kichik** bo'lsa — `Kattaroq`",
      "- taxmin yashirin sondan **katta** bo'lsa — `Kichikroq`",
      "- **teng** bo'lsa — `Topdingiz! K ta urinish` (K — jami taxminlar soni) va sikl to'xtaydi.",
      '',
      "To'g'ri taxmin albatta kiritishlar ichida bor.",
      '',
      '**Misol.** Kirish:',
      '```',
      '42',
      '50',
      '20',
      '42',
      '```',
      'Chiqish:',
      '```',
      'Kichikroq',
      'Kattaroq',
      'Topdingiz! 3 ta urinish',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# Avval yashirin sonni o'qing, keyin while True ichida taxminlarni o'qing.",
      "# Kattaroq / Kichikroq / Topdingiz! K ta urinish — deb javob bering.",
      'sir = int(input())',
      'urinish = 0',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '42\n50\n20\n42\n',
        expectedStdout: 'Kichikroq\nKattaroq\nTopdingiz! 3 ta urinish\n',
        hidden: false,
        label: "Misoldagi holat: yashirin son 42",
      },
      {
        stdin: '100\n1\n50\n75\n90\n100\n',
        expectedStdout:
          'Kattaroq\nKattaroq\nKattaroq\nKattaroq\nTopdingiz! 5 ta urinish\n',
        hidden: false,
        label: "Pastdan yuqoriga qidiruv: yashirin son 100",
      },
      {
        stdin: '7\n7\n',
        expectedStdout: 'Topdingiz! 1 ta urinish\n',
        hidden: true,
        label: "Chegara holat: birinchi urinishdayoq topildi",
      },
      {
        stdin: '1\n100\n2\n1\n',
        expectedStdout: 'Kichikroq\nKichikroq\nTopdingiz! 3 ta urinish\n',
        hidden: true,
        label: "Eng kichik yashirin son: 1",
      },
    ],
  },

  // ─── Dars 10 — for sikli va range() ───────────────────────────────────────
  {
    lessonKey: 'backend-dars-10',
    key: 'backend-dars-10-easy',
    title: 'Kvadratlar jadvali (for + range)',
    difficulty: 'EASY',
    points: 10,
    tags: ['python', 'for', 'range'],
    description: [
      "Kirishda bitta butun son **N** beriladi (test stdin orqali uzatiladi).",
      '',
      "Endi `while` emas, `for` va `range()` ishlating. 1 dan N gacha har bir son uchun",
      'bitta qator chiqaring. Qator formati aniq shunday:',
      '```',
      'i ning kvadrati: natija',
      '```',
      '',
      "Diqqat: `range(1, N + 1)` — N ning o'zi ham kirishi kerak.",
      '',
      '**Misol.** Kirish:',
      '```',
      '4',
      '```',
      'Chiqish:',
      '```',
      '1 ning kvadrati: 1',
      '2 ning kvadrati: 4',
      '3 ning kvadrati: 9',
      '4 ning kvadrati: 16',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# N ni o'qing va for i in range(1, n + 1) bilan",
      '# "i ning kvadrati: natija" qatorlarini chiqaring.',
      'n = int(input())',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '4\n',
        expectedStdout:
          '1 ning kvadrati: 1\n2 ning kvadrati: 4\n3 ning kvadrati: 9\n4 ning kvadrati: 16\n',
        hidden: false,
        label: 'Misoldagi holat: N = 4',
      },
      {
        stdin: '10\n',
        expectedStdout:
          '1 ning kvadrati: 1\n2 ning kvadrati: 4\n3 ning kvadrati: 9\n4 ning kvadrati: 16\n5 ning kvadrati: 25\n6 ning kvadrati: 36\n7 ning kvadrati: 49\n8 ning kvadrati: 64\n9 ning kvadrati: 81\n10 ning kvadrati: 100\n',
        hidden: false,
        label: "Darsdagi asosiy holat: N = 10",
      },
      {
        stdin: '1\n',
        expectedStdout: '1 ning kvadrati: 1\n',
        hidden: true,
        label: 'Chegara holat: N = 1',
      },
      {
        stdin: '7\n',
        expectedStdout:
          '1 ning kvadrati: 1\n2 ning kvadrati: 4\n3 ning kvadrati: 9\n4 ning kvadrati: 16\n5 ning kvadrati: 25\n6 ning kvadrati: 36\n7 ning kvadrati: 49\n',
        hidden: true,
        label: 'Yashirin holat: N = 7',
      },
    ],
  },
  {
    lessonKey: 'backend-dars-10',
    key: 'backend-dars-10-medium',
    title: "So'zni harflarga ajratish",
    difficulty: 'MEDIUM',
    points: 20,
    tags: ['python', 'for', 'satr'],
    description: [
      "Kirishda bitta qatorda **so'z** beriladi (test stdin orqali uzatadi).",
      '',
      "`for harf in soz:` sikli bilan so'zning **har bir harfini alohida qatorda** chiqaring.",
      "Harflar so'zdagi tartibda chiqishi kerak, hech qanday qo'shimcha matn qo'shmang.",
      '',
      "Katta-kichik harf o'zgartirilmaydi — kiritilganidek chiqadi.",
      '',
      '**Misol.** Kirish:',
      '```',
      'salom',
      '```',
      'Chiqish:',
      '```',
      's',
      'a',
      'l',
      'o',
      'm',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# So'zni o'qing va for sikli bilan har bir harfini alohida qatorda chiqaring.",
      'soz = input()',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: 'salom\n',
        expectedStdout: 's\na\nl\no\nm\n',
        hidden: false,
        label: "Misoldagi holat: \"salom\"",
      },
      {
        stdin: 'backend\n',
        expectedStdout: 'b\na\nc\nk\ne\nn\nd\n',
        hidden: false,
        label: "Yetti harfli so'z: \"backend\"",
      },
      {
        stdin: 'a\n',
        expectedStdout: 'a\n',
        hidden: true,
        label: 'Chegara holat: bitta harf',
      },
      {
        stdin: 'Toshkent\n',
        expectedStdout: 'T\no\ns\nh\nk\ne\nn\nt\n',
        hidden: true,
        label: 'Bosh harf bilan boshlanadi',
      },
    ],
  },
  {
    lessonKey: 'backend-dars-10',
    key: 'backend-dars-10-hard',
    title: 'Yulduzchali uchburchak',
    difficulty: 'HARD',
    points: 35,
    tags: ['python', 'for', 'range', 'ichma-ich'],
    description: [
      'Kirishda bitta butun son **N** beriladi — uchburchak qatorlari soni.',
      '',
      "Har bir qatorda yulduzchalar (`*`) chiqaring: 1-qatorda 1 ta, 2-qatorda 2 ta,",
      "… N-qatorda N ta. Yulduzchalar orasida probel yo'q.",
      '',
      "Ichma-ich `for` bilan yozing (ichki sikl bitta qatorni yig'adi).",
      '',
      '**Misol.** Kirish:',
      '```',
      '5',
      '```',
      'Chiqish:',
      '```',
      '*',
      '**',
      '***',
      '****',
      '*****',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# N ni o'qing va ichma-ich for bilan uchburchak chizing.",
      '# i-qatorda i ta yulduzcha bo\'lsin.',
      'n = int(input())',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '5\n',
        expectedStdout: '*\n**\n***\n****\n*****\n',
        hidden: false,
        label: 'Misoldagi holat: N = 5',
      },
      {
        stdin: '3\n',
        expectedStdout: '*\n**\n***\n',
        hidden: false,
        label: 'Kichik uchburchak: N = 3',
      },
      {
        stdin: '1\n',
        expectedStdout: '*\n',
        hidden: true,
        label: 'Chegara holat: N = 1',
      },
      {
        stdin: '8\n',
        expectedStdout: '*\n**\n***\n****\n*****\n******\n*******\n********\n',
        hidden: true,
        label: 'Kattaroq uchburchak: N = 8',
      },
    ],
  },

  // ─── Dars 11 — List (ro'yxat) ─────────────────────────────────────────────
  {
    lessonKey: 'backend-dars-11',
    key: 'backend-dars-11-easy',
    title: "Ro'yxat yig'indisi",
    difficulty: 'EASY',
    points: 10,
    tags: ['python', 'list', 'for'],
    description: [
      "Kirishda **bitta qatorda**, probel bilan ajratilgan butun sonlar beriladi.",
      "Ularni ro'yxatga (`list`) yig'ing va yig'indisini toping.",
      '',
      "Maslahat: `sonlar = [int(x) for x in input().split()]` yoki oddiy `for` bilan `append()`.",
      '',
      "Natijani aniq shu formatda bitta qatorda chiqaring:",
      '```',
      "Yig'indi: X",
      '```',
      '',
      '**Misol.** Kirish:',
      '```',
      '4 8 15 16 23',
      '```',
      'Chiqish:',
      '```',
      "Yig'indi: 66",
      '```',
    ].join('\n'),
    starterCodePy: [
      "# Bitta qatordagi sonlarni ro'yxatga aylantiring va yig'indisini chiqaring.",
      'sonlar = [int(x) for x in input().split()]',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '4 8 15 16 23\n',
        expectedStdout: "Yig'indi: 66\n",
        hidden: false,
        label: "Misoldagi holat: 5 ta son",
      },
      {
        stdin: '1 1 1 1 1 1 1 1 1 1\n',
        expectedStdout: "Yig'indi: 10\n",
        hidden: false,
        label: "O'nta bir xil son",
      },
      {
        stdin: '7\n',
        expectedStdout: "Yig'indi: 7\n",
        hidden: true,
        label: "Chegara holat: ro'yxatda bitta son",
      },
      {
        stdin: '10 -3 -7 0 5\n',
        expectedStdout: "Yig'indi: 5\n",
        hidden: true,
        label: 'Manfiy va nol qatnashadi',
      },
    ],
  },
  {
    lessonKey: 'backend-dars-11',
    key: 'backend-dars-11-medium',
    title: "Ismlarni tartiblash",
    difficulty: 'MEDIUM',
    points: 20,
    tags: ['python', 'list', 'sort', 'input'],
    description: [
      '**Kirish tartibi:**',
      '1. Birinchi qator — ismlar soni **N**.',
      '2. Keyingi N ta qator — ismlar (har biri alohida qatorda).',
      '',
      "Ismlarni ro'yxatga `append()` qiling, `sort()` bilan alifbo tartibida tartiblang",
      "va **har birini alohida qatorda** chiqaring. Boshqa hech narsa chiqarmang.",
      '',
      "Barcha ismlar bosh harf bilan boshlanadi.",
      '',
      '**Misol.** Kirish:',
      '```',
      '5',
      'Zarina',
      'Ali',
      'Madina',
      'Bobur',
      'Sarvar',
      '```',
      'Chiqish:',
      '```',
      'Ali',
      'Bobur',
      'Madina',
      'Sarvar',
      'Zarina',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# N ni o'qing, N ta ismni ro'yxatga yig'ing,",
      '# sort() bilan tartiblang va har birini alohida qatorda chiqaring.',
      'n = int(input())',
      'ismlar = []',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '5\nZarina\nAli\nMadina\nBobur\nSarvar\n',
        expectedStdout: 'Ali\nBobur\nMadina\nSarvar\nZarina\n',
        hidden: false,
        label: 'Misoldagi holat: 5 ta ism',
      },
      {
        stdin: '4\nSanjar\nDilnoza\nAziz\nYulduz\n',
        expectedStdout: 'Aziz\nDilnoza\nSanjar\nYulduz\n',
        hidden: false,
        label: "To'rtta ism",
      },
      {
        stdin: '1\nAli\n',
        expectedStdout: 'Ali\n',
        hidden: true,
        label: 'Chegara holat: bitta ism',
      },
      {
        stdin: '3\nOybek\nGulnora\nAkmal\n',
        expectedStdout: 'Akmal\nGulnora\nOybek\n',
        hidden: true,
        label: 'Teskari tartibda kiritilgan ismlar',
      },
    ],
  },
  {
    lessonKey: 'backend-dars-11',
    key: 'backend-dars-11-hard',
    title: 'max/min siz eng katta va eng kichik',
    difficulty: 'HARD',
    points: 35,
    tags: ['python', 'list', 'for', 'algoritm'],
    description: [
      "Kirishda **bitta qatorda**, probel bilan ajratilgan butun sonlar beriladi.",
      '',
      "`max()` va `min()` funksiyalarini **ishlatmasdan**, `for` sikli va shartlar bilan",
      "eng katta va eng kichik sonni toping.",
      '',
      'Natijani aniq ikki qatorda chiqaring:',
      '```',
      'Eng katta: X',
      'Eng kichik: Y',
      '```',
      '',
      "Sonlar manfiy ham bo'lishi mumkin, shuning uchun boshlang'ich qiymat sifatida 0 emas,",
      "ro'yxatning birinchi elementini oling.",
      '',
      '**Misol.** Kirish:',
      '```',
      '4 8 15 16 23',
      '```',
      'Chiqish:',
      '```',
      'Eng katta: 23',
      'Eng kichik: 4',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# max() va min() ishlatmang! for sikli va if bilan toping.",
      'sonlar = [int(x) for x in input().split()]',
      'katta = sonlar[0]',
      'kichik = sonlar[0]',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '4 8 15 16 23\n',
        expectedStdout: 'Eng katta: 23\nEng kichik: 4\n',
        hidden: false,
        label: 'Misoldagi holat: 5 ta musbat son',
      },
      {
        stdin: '-9 -2 -50 -1\n',
        expectedStdout: 'Eng katta: -1\nEng kichik: -50\n',
        hidden: false,
        label: 'Barcha sonlar manfiy',
      },
      {
        stdin: '5\n',
        expectedStdout: 'Eng katta: 5\nEng kichik: 5\n',
        hidden: true,
        label: 'Chegara holat: bitta son',
      },
      {
        stdin: '3 3 3 3\n',
        expectedStdout: 'Eng katta: 3\nEng kichik: 3\n',
        hidden: true,
        label: "Barcha sonlar teng",
      },
    ],
  },

  // ─── Dars 12 — Tuple + Loyiha ─────────────────────────────────────────────
  {
    lessonKey: 'backend-dars-12',
    key: 'backend-dars-12-easy',
    title: "«Sonni top» o'yini (1–50)",
    difficulty: 'EASY',
    points: 10,
    tags: ['python', 'while', 'oyin', 'loyiha'],
    description: [
      "1-oy loyihasining birinchi bosqichi. Tekshirish mumkin bo'lishi uchun yashirin son",
      "tasodifiy emas — u ham stdin orqali beriladi.",
      '',
      '**Kirish tartibi:**',
      '1. Birinchi qator — yashirin son (1 dan 50 gacha).',
      "2. Keyingi qatorlar — o'yinchining taxminlari.",
      '',
      "Har bir taxminga bitta qator javob yozing:",
      "- taxmin yashirin sondan kichik — `Katta son ayting`",
      "- taxmin yashirin sondan katta — `Kichik son ayting`",
      "- taxmin to'g'ri — `Topdingiz!` va o'yin tugaydi.",
      '',
      '**Misol.** Kirish:',
      '```',
      '25',
      '10',
      '40',
      '25',
      '```',
      'Chiqish:',
      '```',
      'Katta son ayting',
      'Kichik son ayting',
      'Topdingiz!',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# Yashirin sonni o'qing, keyin while True ichida taxminlarni tekshiring.",
      "# Katta son ayting / Kichik son ayting / Topdingiz!",
      'sir = int(input())',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '25\n10\n40\n25\n',
        expectedStdout: 'Katta son ayting\nKichik son ayting\nTopdingiz!\n',
        hidden: false,
        label: 'Misoldagi holat: yashirin son 25',
      },
      {
        stdin: '37\n50\n1\n37\n',
        expectedStdout: 'Kichik son ayting\nKatta son ayting\nTopdingiz!\n',
        hidden: false,
        label: 'Avval katta, keyin kichik taxmin',
      },
      {
        stdin: '1\n1\n',
        expectedStdout: 'Topdingiz!\n',
        hidden: true,
        label: 'Chegara holat: birinchi urinishda topildi',
      },
      {
        stdin: '50\n25\n45\n49\n50\n',
        expectedStdout:
          'Katta son ayting\nKatta son ayting\nKatta son ayting\nTopdingiz!\n',
        hidden: true,
        label: "Chegara holat: yashirin son 50",
      },
    ],
  },
  {
    lessonKey: 'backend-dars-12',
    key: 'backend-dars-12-medium',
    title: "«Sonni top»: 7 ta urinish chegarasi",
    difficulty: 'MEDIUM',
    points: 20,
    tags: ['python', 'while', 'oyin', 'shart'],
    description: [
      "Oldingi o'yinni takomillashtiramiz: o'yinchida **eng ko'pi bilan 7 ta urinish** bor.",
      '',
      '**Kirish tartibi:**',
      '1. Birinchi qator — yashirin son (1 dan 50 gacha).',
      '2. Keyingi qatorlar — taxminlar (7 tadan oshmaydi).',
      '',
      'Javoblar:',
      "- taxmin kichik — `Katta son ayting`",
      "- taxmin katta — `Kichik son ayting`",
      "- taxmin to'g'ri — `Topdingiz! K ta urinish` (K — nechanchi urinish) va o'yin tugaydi.",
      "- 7 ta urinish ham topa olmasa, oxirida `Yutqazdingiz! Son: X` chiqsin (X — yashirin son).",
      '',
      '**Misol.** Kirish:',
      '```',
      '25',
      '10',
      '40',
      '25',
      '```',
      'Chiqish:',
      '```',
      'Katta son ayting',
      'Kichik son ayting',
      'Topdingiz! 3 ta urinish',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# Urinishlar sonini sanang. 7 tadan oshsa \"Yutqazdingiz! Son: X\" chiqaring.",
      'sir = int(input())',
      'urinish = 0',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '25\n10\n40\n25\n',
        expectedStdout:
          'Katta son ayting\nKichik son ayting\nTopdingiz! 3 ta urinish\n',
        hidden: false,
        label: 'Misoldagi holat: 3-urinishda topildi',
      },
      {
        stdin: '13\n1\n2\n3\n4\n5\n6\n7\n',
        expectedStdout:
          'Katta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nYutqazdingiz! Son: 13\n',
        hidden: false,
        label: '7 ta urinish tugadi — yutqazish',
      },
      {
        stdin: '50\n50\n',
        expectedStdout: 'Topdingiz! 1 ta urinish\n',
        hidden: true,
        label: 'Chegara holat: birinchi urinishda topildi',
      },
      {
        stdin: '8\n1\n2\n3\n4\n5\n6\n8\n',
        expectedStdout:
          'Katta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nKatta son ayting\nTopdingiz! 7 ta urinish\n',
        hidden: true,
        label: "Chegara holat: aynan 7-urinishda topildi",
      },
    ],
  },
  {
    lessonKey: 'backend-dars-12',
    key: 'backend-dars-12-hard',
    title: 'Matnli kalkulyator',
    difficulty: 'HARD',
    points: 35,
    tags: ['python', 'while', 'kalkulyator', 'loyiha'],
    description: [
      "1-oy yakuniy loyihasi: to'xtovsiz ishlaydigan kalkulyator.",
      '',
      '**Kirish tartibi (takrorlanadi):**',
      '1. Bitta qatorda amal: `+`, `-`, `*`, `/` yoki `chiq`.',
      "2. `chiq` bo'lmasa — keyingi ikki qatorda ikkita butun son: **a** va **b**.",
      '',
      '**Chiqish qoidalari:**',
      '- `+`, `-`, `*` uchun: `a AMAL b = natija` (natija butun son).',
      "- `/` uchun: `a / b = natija`, bu yerda natija `round(a / b, 2)` bilan hisoblanadi",
      "  (masalan `7 / 2 = 3.5`, `6 / 3 = 2.0`).",
      "- Agar `/` da **b = 0** bo'lsa — `Nolga bo'lib bo'lmaydi`.",
      "- `chiq` kiritilganda — `Xayr!` chiqaring va dastur tugaydi.",
      '',
      '**Misol.** Kirish:',
      '```',
      '*',
      '6',
      '7',
      '-',
      '10',
      '25',
      '/',
      '7',
      '2',
      'chiq',
      '```',
      'Chiqish:',
      '```',
      '6 * 7 = 42',
      '10 - 25 = -15',
      '7 / 2 = 3.5',
      'Xayr!',
      '```',
    ].join('\n'),
    starterCodePy: [
      "# while True ichida amalni o'qing. \"chiq\" bo'lsa \"Xayr!\" chiqarib break qiling.",
      "# Aks holda ikkita sonni o'qib, natijani \"a AMAL b = natija\" ko'rinishida chiqaring.",
      'while True:',
      '    amal = input()',
      '',
    ].join('\n'),
    testCases: [
      {
        stdin: '*\n6\n7\n-\n10\n25\n/\n7\n2\nchiq\n',
        expectedStdout: '6 * 7 = 42\n10 - 25 = -15\n7 / 2 = 3.5\nXayr!\n',
        hidden: false,
        label: 'Misoldagi holat: uchta amal',
      },
      {
        stdin: '+\n3\n4\nchiq\n',
        expectedStdout: '3 + 4 = 7\nXayr!\n',
        hidden: false,
        label: "Oddiy qo'shish",
      },
      {
        stdin: 'chiq\n',
        expectedStdout: 'Xayr!\n',
        hidden: true,
        label: "Chegara holat: darrov chiqildi",
      },
      {
        stdin: '/\n5\n0\n/\n6\n3\nchiq\n',
        expectedStdout: "Nolga bo'lib bo'lmaydi\n6 / 3 = 2.0\nXayr!\n",
        hidden: true,
        label: "Nolga bo'lish va o'nlik natija",
      },
    ],
  },
];
