/**
 * Offline enrichment: asks Gemini for three bonus practice problems per lesson,
 * grounded in that lesson's own M — MAKE tiers.
 *
 *   GEMINI_API_KEY=... npx tsx scripts/generateLessonProblems.ts
 *
 * The output is committed to `prisma/lessonsData/backendProblems.ts` and read by
 * the seed, so nothing calls the model at runtime. Problems are optional bonus
 * XP — the required homework still comes verbatim from the deck.
 *
 * Only lessons that can actually be solved in the Piston sandbox get problems.
 * Git, SQL, Django, Docker and deployment lessons are skipped, and the script
 * prints exactly which ones so the gap is visible rather than silent.
 */
import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { backendLessons } from '../prisma/lessonsData/backend';
import type { LessonProblemRecord, LessonRecord } from '../prisma/lessonsData/types';
import { askGeminiJson } from '../src/server/ai/gemini';

const OUTPUT_FILE = path.join(process.cwd(), 'prisma', 'lessonsData', 'backendProblems.ts');

/** Sections whose lessons are plain Python and therefore runnable + auto-judgeable. */
const RUNNABLE_SECTIONS = new Set(['Python asoslari', 'Python chuqurroq', 'OOP', "Ilg'or Python"]);

/** Environment/tooling lessons inside those sections that have nothing to code. */
const TOOLING_LESSONS = new Set([1, 21, 34, 35]);

const TIERS = [
  { difficulty: 'EASY' as const, points: 10, label: 'oson' },
  { difficulty: 'MEDIUM' as const, points: 20, label: "o'rta" },
  { difficulty: 'HARD' as const, points: 35, label: 'qiyin' },
];

function isRunnable(lesson: LessonRecord): boolean {
  return (
    RUNNABLE_SECTIONS.has(lesson.section) && lesson.kind !== 'project' && !TOOLING_LESSONS.has(lesson.order)
  );
}

interface GeneratedProblem {
  title: string;
  description: string;
  starterCodePy: string;
  tags: string[];
}

function promptFor(lesson: LessonRecord): string {
  return `Siz Python o'qituvchisisiz. Quyidagi dars uchun 3 ta mustaqil mashq masalasi yozing.

Dars ${lesson.order}/96: ${lesson.title} (${lesson.section})
Mavzu qisqacha: ${lesson.summary}
Darsdan xulosalar:
${lesson.objectives.map((o) => `- ${o}`).join('\n')}
Darsda berilgan mashq darajalari:
- Oson: ${lesson.makeEasy}
- O'rta: ${lesson.makeMedium}
- Qiyin: ${lesson.makeHard}

QAT'IY TALABLAR:
- Har bir masala FAQAT shu darsda va undan oldingi darslarda o'rganilgan Python imkoniyatlari bilan yechilsin.
- Har bir masala bitta funksiya yozishni talab qilsin (input() ishlatilmasin).
- Tavsifda kamida 2 ta misol bo'lsin: "Kiritma: ... Natija: ..." ko'rinishida.
- starterCodePy faqat funksiya imzosi va "# kodingizni shu yerga yozing" izohidan iborat bo'lsin.
- Barcha matn o'zbek tilida.

Javobni faqat quyidagi JSON formatida qaytaring:
{
  "problems": [
    { "title": "...", "description": "...", "starterCodePy": "def ...:\\n    # kodingizni shu yerga yozing\\n    pass", "tags": ["..."] },
    { ...o'rta daraja... },
    { ...qiyin daraja... }
  ]
}`;
}

async function generateForLesson(lesson: LessonRecord): Promise<LessonProblemRecord[]> {
  const result = await askGeminiJson<{ problems: GeneratedProblem[] }>(promptFor(lesson), { problems: [] });

  if (!Array.isArray(result.problems) || result.problems.length !== TIERS.length) {
    throw new Error(
      `Dars ${lesson.order}: ${TIERS.length} ta masala kutilgan, ${result.problems?.length ?? 0} ta keldi.`
    );
  }

  return result.problems.map((problem, index) => {
    const tier = TIERS[index];
    if (!problem.title || !problem.description || !problem.starterCodePy) {
      throw new Error(`Dars ${lesson.order}, ${tier.label} masala to'liq emas.`);
    }
    return {
      lessonKey: lesson.key,
      key: `${lesson.key}-${tier.difficulty.toLowerCase()}`,
      title: problem.title.trim(),
      difficulty: tier.difficulty,
      points: tier.points,
      tags: Array.isArray(problem.tags) && problem.tags.length > 0 ? problem.tags : [lesson.section],
      description: problem.description.trim(),
      starterCodePy: problem.starterCodePy,
      // Test cases are authored by hand — the generator never invents them.
      testCases: [],
    };
  });
}

function render(problems: LessonProblemRecord[]): string {
  return [
    '// GENERATED by scripts/generateLessonProblems.ts — do not edit by hand.',
    '// Bonus practice attached to backend lessons; review before committing.',
    "import type { LessonProblemRecord } from './types';",
    '',
    `export const backendLessonProblems: LessonProblemRecord[] = ${JSON.stringify(problems, null, 2)};`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY sozlanmagan — .env fayliga kalitni qo\'shing va qaytadan ishga tushiring.');
  }

  const runnable = backendLessons.filter(isRunnable);
  const skipped = backendLessons.filter((lesson) => !isRunnable(lesson));

  console.log(`${runnable.length} ta dars uchun masala generatsiya qilinadi.`);
  console.log(
    `${skipped.length} ta dars o'tkazib yuborildi (Piston'da bajarilmaydi): ${skipped
      .map((lesson) => lesson.order)
      .join(', ')}`
  );

  const problems: LessonProblemRecord[] = [];
  for (const lesson of runnable) {
    const generated = await generateForLesson(lesson);
    problems.push(...generated);
    console.log(`  dars ${lesson.order} — ${lesson.title}: ${generated.length} ta masala`);
  }

  fs.writeFileSync(OUTPUT_FILE, render(problems), 'utf8');
  console.log(`\n${problems.length} ta masala yozildi: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  console.log('Commit qilishdan oldin qo\'lda ko\'rib chiqing.');
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
