import { Router } from 'express';
import { authRouter } from './auth';
import { usersRouter } from './users';
import { classesRouter } from './classes';
import { assignmentsRouter } from './assignments';
import { submissionsRouter } from './submissions';
import { gradesRouter } from './grades';
import { homeworkRouter } from './homework';
import { attendanceRouter } from './attendance';
import { notificationsRouter } from './notifications';
import { calendarRouter } from './calendar';
import { questsRouter } from './quests';
import { progressRouter } from './progress';
import { cityRouter } from './city';
import { achievementsRouter } from './achievements';
import { leaderboardRouter } from './leaderboard';
import { shopRouter } from './shop';
import { teamsRouter } from './teams';
import { problemsRouter } from './problems';
import { battlesRouter } from './battles';
import { mentorRouter } from './mentor';
import { socialRouter } from './social';
import { reviewCodeRouter } from './reviewCode';
import { dailyExerciseRouter } from './dailyExercise';
import { uploadsRouter } from './uploads';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/classes', classesRouter);
apiRouter.use('/assignments', assignmentsRouter);
apiRouter.use('/submissions', submissionsRouter);
apiRouter.use('/grades', gradesRouter);
apiRouter.use('/homework', homeworkRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/calendar', calendarRouter);
apiRouter.use('/quests', questsRouter);
apiRouter.use('/progress', progressRouter);
apiRouter.use('/city', cityRouter);
apiRouter.use('/achievements', achievementsRouter);
apiRouter.use('/leaderboard', leaderboardRouter);
apiRouter.use('/shop', shopRouter);
apiRouter.use('/teams', teamsRouter);
apiRouter.use('/problems', problemsRouter);
apiRouter.use('/battles', battlesRouter);
apiRouter.use('/mentor', mentorRouter);
apiRouter.use('/social', socialRouter);
apiRouter.use('/daily-exercise', dailyExerciseRouter);
apiRouter.use('/uploads', uploadsRouter);
apiRouter.use(reviewCodeRouter);
